Repository paritytech/substrate, pull requests merged in 2018-08, with the labels that each got.

#472 Update service.rs
  polkadot/consensus/src/service.rs
Labels: A2-insubstantial

#475 Fix the --key generation
  substrate/keystore/src/lib.rs
  substrate/service/src/lib.rs
Labels: A8-looksgood

#466 Wasm execution optimizations
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  polkadot/api/src/full.rs
  polkadot/parachain/Cargo.toml
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
  substrate/client/src/genesis.rs
  substrate/client/src/light/call_executor.rs
  substrate/executor/Cargo.toml
  substrate/executor/src/error.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/primitives/Cargo.toml
  substrate/runtime-sandbox/Cargo.toml
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
  substrate/state-machine/src/lib.rs
  substrate/test-client/src/client_ext.rs
Labels: A8-looksgood

#464 Storage changes subscription
  Cargo.lock
  demo/cli/src/lib.rs
  substrate/client/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/client.rs
  substrate/client/src/lib.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/notifications.rs
  substrate/primitives/src/storage.rs
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
  substrate/service/src/lib.rs
  substrate/state-machine/src/lib.rs
Labels: M6-rpcapi

#438 Collator for the "adder" (formerly basic-add) parachain and various small fixes
  Cargo.lock
  Cargo.toml
  common.sh
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/collator/src/lib.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/shared_table/mod.rs
  polkadot/network/src/consensus.rs
  polkadot/network/src/lib.rs
  polkadot/network/src/router.rs
  polkadot/parachain/test-chains/basic_add/Cargo.toml
  polkadot/parachain/test-chains/basic_add/build.sh
  polkadot/parachain/test-chains/basic_add/src/lib.rs
  polkadot/parachain/tests/adder.rs
  polkadot/parachain/tests/res/adder.wasm
  polkadot/parachain/tests/res/basic_add.wasm
  polkadot/runtime/src/parachains.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/src/lib.rs
  polkadot/test-parachains/.gitignore
  polkadot/test-parachains/README.md
  polkadot/test-parachains/adder/Cargo.toml
  polkadot/test-parachains/adder/collator/Cargo.toml
  polkadot/test-parachains/adder/collator/src/main.rs
  polkadot/test-parachains/adder/src/lib.rs
  polkadot/test-parachains/adder/src/src
  polkadot/test-parachains/adder/wasm/Cargo.toml
  polkadot/test-parachains/adder/wasm/src/lib.rs
  polkadot/test-parachains/build.sh
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/network/src/consensus_gossip.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#477 force BFT delay in consensus service, not in proposer logic
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
Labels: A0-pleasereview

#484 [backport] Lower bft timeout
  Cargo.toml
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  substrate/bft/src/lib.rs
Labels: A2-insubstantial

#483 Lower BFT timeout
  substrate/bft/src/lib.rs
Labels: A8-looksgood

#481 Use hex_literal in tests, use rustc-hex from crates
  Cargo.lock
  substrate/executor/Cargo.toml
  substrate/executor/src/lib.rs
  substrate/executor/src/wasm_executor.rs
  substrate/primitives/Cargo.toml
Labels: A2-insubstantial, F5-task

#486 should be MAX_IMPORTING_BLOCKS
  substrate/network/src/sync.rs
Labels: A2-insubstantial

#476 Add seed generation tests
  substrate/keystore/src/lib.rs
Labels: A8-looksgood, M4-core

#413 [docs] Add links to tags and house style in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: A0-pleasereview, A2-insubstantial

#463 Improve docker image size with a 2 stages image
  .dockerignore
  Dockerfile
  README.adoc
  ci/script.sh
  docker/Dockerfile
  docker/build.sh
  docker/cleanup.sh
  docker/readme-docker.adoc
  docker/version
  scripts/build-demos.sh
  scripts/build.sh
  scripts/common.sh
  scripts/init.sh
Labels: A8-looksgood

#493 Send initial values with subscription.
  Cargo.lock
  substrate/client/src/client.rs
  substrate/client/src/notifications.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/chain/error.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
  substrate/test-client/src/block_builder_ext.rs
  substrate/test-client/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#496 --version commit hash - style improvement
  substrate/cli/src/lib.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
Labels: A8-looksgood

#497 Add doc to install a specific tagged version
  README.adoc
Labels: A2-insubstantial, F5-documentation

#465 Availability/Extrinsic store
  Cargo.lock
  Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/availability-store/Cargo.toml
  polkadot/availability-store/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/collation.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/consensus/src/shared_table/mod.rs
  polkadot/network/Cargo.toml
  polkadot/network/src/lib.rs
  polkadot/network/src/router.rs
  polkadot/network/src/tests.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/Cargo.toml
  polkadot/service/src/lib.rs
  substrate/client/src/client.rs
  substrate/client/src/lib.rs
  substrate/codec/src/codec.rs
  substrate/service/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#462 NetworkService::new starts the network
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/src/service.rs
  substrate/service/src/lib.rs
Labels: A8-looksgood, M4-core

#500 remove the extra ? in the license header
  polkadot/cli/src/chain_spec.rs
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
  substrate/network-libp2p/src/transport.rs
  substrate/network/src/blocks.rs
  substrate/network/src/config.rs
  substrate/network/src/consensus_gossip.rs
  substrate/network/src/error.rs
  substrate/network/src/import_queue.rs
  substrate/network/src/io.rs
  substrate/network/src/lib.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
  substrate/service/src/config.rs
Labels: A0-pleasereview

#501 fix some formatting grumbles
  polkadot/consensus/src/service.rs
  polkadot/consensus/src/shared_table/mod.rs
Labels: A2-insubstantial

#502 Place call data into newly allocated pages
  polkadot/parachain/src/wasm.rs
  polkadot/parachain/tests/adder.rs
Labels: A8-looksgood, M4-core

#514 Locked Cargo.lock
  ci/script.sh
Labels: A2-insubstantial, M1-ci

#510 substrate: return Option in all storage related RPC methods
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
Labels: A8-looksgood, M6-rpcapi

#504 Some networking cleanups
  Cargo.lock
  substrate/cli/Cargo.toml
  substrate/cli/src/lib.rs
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/traits.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/src/service.rs
Labels: A8-looksgood, M4-core

#503 If contract reaches max depth, return Err
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/tests.rs
Labels: A0-pleasereview, M4-core

#495 New flags to listen to all interfaces
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
  substrate/runtime/staking/src/lib.rs
Labels: A0-pleasereview

#515 Merge storage and storage_at RPCs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
Labels: A0-pleasereview, M6-rpcapi

#518 README: fixed typo in docker run command
  README.adoc
Labels: A2-insubstantial

#521 Remove safe-mix
  Cargo.lock
  Cargo.toml
  demo/runtime/Cargo.toml
  demo/runtime/wasm/Cargo.toml
  polkadot/runtime/Cargo.toml
  polkadot/runtime/wasm/Cargo.toml
  safe-mix/Cargo.toml
  safe-mix/build.rs
  safe-mix/src/lib.rs
  substrate/runtime/council/Cargo.toml
  substrate/runtime/democracy/Cargo.toml
  substrate/runtime/session/Cargo.toml
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/system/Cargo.toml
Labels: A0-pleasereview

#519 Add blocks per second and some colors to the informant
  substrate/cli/src/informant.rs
Labels: A2-insubstantial, M4-core

#522 Expose node public key to telemetry
  substrate/service/src/lib.rs
Labels: A0-pleasereview, M4-core

#528 Reserved peers CLI flag
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
  substrate/network-libp2p/src/service.rs
Labels: A0-pleasereview

#527 Td bps
  substrate/cli/src/informant.rs
Labels: A8-looksgood

#526 Mh public key for telemetry
  substrate/service/src/lib.rs
Labels: A8-looksgood

#532 Update libp2p and some log
  Cargo.lock
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A0-pleasereview, M4-core

#536 don't wait for all futures to resolve before shutdown
  polkadot/cli/src/lib.rs
Labels: A8-looksgood

#538 Continue sync after ancestry search
  substrate/network/src/sync.rs
Labels: A0-pleasereview

#539 fix block body fetch for availability pruning
  polkadot/consensus/src/service.rs
Labels: A8-looksgood

#541 [Backport] Vote out offline authorities
  Cargo.lock
  demo/runtime/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/src/full.rs
  polkadot/api/src/lib.rs
  polkadot/api/src/light.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/dynamic_inclusion.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/offline_tracker.rs
  polkadot/consensus/src/service.rs
  polkadot/network/Cargo.toml
  polkadot/primitives/src/lib.rs
  polkadot/runtime/src/checked_block.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/parachains.rs
  polkadot/runtime/src/utils.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/transaction-pool/src/lib.rs
  substrate/bft/Cargo.toml
  substrate/bft/src/lib.rs
  substrate/executor/wasm/Cargo.lock
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/misbehavior-check/Cargo.toml
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/test-client/Cargo.toml
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-backport

#547 [backport] --version commit hash - style improvement (#496)
  substrate/cli/src/lib.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
Labels: A8-backport

#524 Vote out offline authorities
  Cargo.lock
  demo/runtime/src/lib.rs
  polkadot/api/src/full.rs
  polkadot/api/src/lib.rs
  polkadot/api/src/light.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/dynamic_inclusion.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/offline_tracker.rs
  polkadot/consensus/src/service.rs
  polkadot/network/Cargo.toml
  polkadot/primitives/src/lib.rs
  polkadot/runtime/src/checked_block.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/parachains.rs
  polkadot/runtime/src/utils.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/transaction-pool/src/lib.rs
  substrate/bft/Cargo.toml
  substrate/bft/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/misbehavior-check/Cargo.toml
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/test-client/Cargo.toml
Labels: A7-looksgoodcantmerge, A9-buythatmanabeer

#548 Backport Dockerfile to v0.2.x
  .dockerignore
  Dockerfile
Labels: A2-insubstantial

#252 Fetching storage proofs by light client
  Cargo.lock
  substrate/client/src/blockchain.rs
  substrate/client/src/client.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/call_executor.rs
  substrate/client/src/light/fetcher.rs
  substrate/client/src/light/mod.rs
  substrate/network/Cargo.toml
  substrate/network/src/chain.rs
  substrate/network/src/lib.rs
  substrate/network/src/message.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/service/src/components.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/trie_backend.rs
Labels: A0-pleasereview

#546 Less verbosity
  polkadot/transaction-pool/src/lib.rs
  substrate/extrinsic-pool/src/listener.rs
Labels: A2-insubstantial

#537 RPC: query historical storage entries
  substrate/primitives/src/storage.rs
  substrate/rpc/src/state/error.rs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
Labels: A0-pleasereview, M6-rpcapi

#558 Reject too large transactions
  polkadot/consensus/src/lib.rs
  polkadot/transaction-pool/src/error.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/extrinsic-pool/src/pool.rs
Labels: A0-pleasereview, M4-core

#559 Update libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/lib.rs
Labels: A0-pleasereview

#565 Update some outdated slashing tests in runtime
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/tests.rs
Labels: A8-looksgood

#563 RPC: Pending Extrinsics
  Cargo.lock
  demo/cli/src/lib.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/extrinsic-pool/src/api.rs
  substrate/extrinsic-pool/src/pool.rs
  substrate/rpc-servers/Cargo.toml
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/src/author/mod.rs
  substrate/rpc/src/author/tests.rs
  substrate/service/src/lib.rs
Labels: A7-looksgoodtestsfail, M6-rpcapi

#556 Fix typo in staking/src/lib.rs
  substrate/runtime/staking/src/lib.rs
Labels: A8-looksgood

#564 RPC: Get block
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
Labels: A8-looksgood, M6-rpcapi

#428 Ensure total tokens in system is kept up to date
  demo/executor/src/lib.rs
  polkadot/test-parachains/adder/src/src
  substrate/runtime/contract/src/gas.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/tests.rs
Labels: A8-looksgood

#499 send memory usage and cpu usage to telemetry
  Cargo.lock
  substrate/cli/Cargo.toml
  substrate/cli/src/informant.rs
  substrate/cli/src/lib.rs
  substrate/telemetry/src/lib.rs
Labels: A8-looksgood

#566 add build status in README
  README.adoc
Labels: A2-insubstantial

#576 Remove _wasm block specialistions in tests.
  demo/executor/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
Labels: A8-looksgood

#580 Authoring with WASM runtime.
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/staking/src/lib.rs
Labels: A0-pleasereview

#583 [forward port] continue rounds
  Cargo.lock
  substrate/bft/src/lib.rs
Labels: A0-pleasereview

#582 Continue from next round when re-building on same block
  Cargo.lock
  polkadot/consensus/src/service.rs
  substrate/bft/src/lib.rs
Labels: A0-pleasereview

#585 Paranoid authoring mode
  Cargo.toml
  substrate/client/src/block_builder.rs
Labels: A0-pleasereview

#569 RPC for returning the runtime version
  Cargo.lock
  substrate/rpc/Cargo.toml
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/lib.rs
  substrate/runtime/version/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#579 More generic extrinsic pool
  Cargo.lock
  demo/cli/src/lib.rs
  substrate/cli/Cargo.toml
  substrate/cli/src/informant.rs
  substrate/cli/src/lib.rs
  substrate/extrinsic-pool/Cargo.toml
  substrate/extrinsic-pool/src/api.rs
  substrate/extrinsic-pool/src/error.rs
  substrate/extrinsic-pool/src/lib.rs
  substrate/extrinsic-pool/src/pool.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/test/mod.rs
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/src/author/error.rs
  substrate/rpc/src/author/mod.rs
  substrate/rpc/src/author/tests.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/service/src/components.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
Labels: A8-looksgood

#586 Fix runtime version cache
  substrate/codec/derive/src/lib.rs
  substrate/executor/src/native_executor.rs
Labels: A0-pleasereview

#587 Fix logging
  substrate/executor/src/native_executor.rs
  substrate/state-machine/src/lib.rs
Labels: A8-looksgood

#589 refactor BFT delay: update rhododendron and poll after delaying.
  Cargo.lock
  polkadot/consensus/src/service.rs
Labels: A8-looksgood

#599 cargo --force to allow CI to build.
  scripts/init.sh
Labels: A2-insubstantial, M1-ci

#593 BFT delay adjustments
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  substrate/bft/src/lib.rs
Labels: A0-pleasereview

#594 Time-based transaction banning
  polkadot/transaction-pool/src/error.rs
  polkadot/transaction-pool/src/lib.rs
  polkadot/transaction-pool/src/rotator.rs
Labels: A8-looksgood, M4-core

#602 [forwardport] Time-based transaction banning (#594)
  substrate/extrinsic-pool/src/lib.rs
  substrate/extrinsic-pool/src/pool.rs
  substrate/extrinsic-pool/src/rotator.rs
Labels: A8-backport, M4-core

#600 Minor fixes for nightly 2018-08-18
  substrate/executor/wasm/build.sh
  substrate/runtime-std/src/lib.rs
Labels: A2-insubstantial

#584 RPC: Block number to block hash
  substrate/codec/derive/src/lib.rs
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/helpers.rs
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/mod.rs
Labels: A8-looksgood, M6-rpcapi

#608 typo fixes
  substrate/rpc/src/metadata.rs
Labels: A2-insubstantial

#614 rename Polkadot to Substrate in the license header
  build.rs
  substrate/client/db/src/cache.rs
  substrate/client/db/src/lib.rs
  substrate/client/db/src/light.rs
  substrate/client/db/src/utils.rs
  substrate/client/src/backend.rs
  substrate/client/src/blockchain.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/error.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/blockchain.rs
  substrate/client/src/light/call_executor.rs
  substrate/client/src/light/fetcher.rs
  substrate/client/src/light/mod.rs
  substrate/environmental/src/lib.rs
  substrate/environmental/with_std.rs
  substrate/environmental/without_std.rs
  substrate/extrinsic-pool/src/error.rs
  substrate/extrinsic-pool/src/lib.rs
  substrate/extrinsic-pool/src/listener.rs
  substrate/extrinsic-pool/src/rotator.rs
  substrate/extrinsic-pool/src/watcher.rs
  substrate/keyring/src/lib.rs
  substrate/misbehavior-check/src/lib.rs
  substrate/network/src/blocks.rs
  substrate/network/src/chain.rs
  substrate/network/src/config.rs
  substrate/network/src/consensus_gossip.rs
  substrate/network/src/error.rs
  substrate/network/src/import_queue.rs
  substrate/network/src/io.rs
  substrate/network/src/lib.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
  substrate/network/src/test/sync.rs
  substrate/primitives/src/authority_id.rs
  substrate/primitives/src/bytes.rs
  substrate/primitives/src/hash.rs
  substrate/primitives/src/hasher.rs
  substrate/primitives/src/hashing.rs
  substrate/primitives/src/hexdisplay.rs
  substrate/primitives/src/lib.rs
  substrate/primitives/src/rlp_codec.rs
  substrate/primitives/src/storage.rs
  substrate/primitives/src/tests.rs
  substrate/primitives/src/uint.rs
  substrate/runtime-support/src/hashable.rs
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/state-db/src/lib.rs
  substrate/state-db/src/pruning.rs
  substrate/state-db/src/test.rs
  substrate/state-db/src/unfinalized.rs
Labels: A2-insubstantial

#613 extrinsic-pool: use retain()
  substrate/extrinsic-pool/src/rotator.rs
Labels: A9-buythatmanabeer

#478 Contract signatures checking
  Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/runtime-sandbox/Cargo.toml
  substrate/runtime-sandbox/src/lib.rs
  substrate/runtime-sandbox/with_std.rs
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/vm.rs
  substrate/runtime/contract/src/vm/env_def/macros.rs
  substrate/runtime/contract/src/vm/env_def/mod.rs
  substrate/runtime/contract/src/vm/mod.rs
  substrate/runtime/contract/src/vm/prepare.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A6-mustntgrumble, M4-core

#570 New slashing logic
  .gitlab-ci.yml
  Cargo.lock
  README.adoc
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/Cargo.toml
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/staking/src/tests.rs
Labels: A8-backport, A8-looksgood

#609 add cli for purge chain
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
Labels: A8-looksgood

#610 set the current repo in Cargo.toml
  Cargo.toml
Labels: A8-looksgood

#611 add a new unit test for extrinsic pool
  substrate/extrinsic-pool/src/rotator.rs
Labels: A8-looksgood

#616 update substrate/extrinsic-pool
  Cargo.lock
  substrate/extrinsic-pool/Cargo.toml
  substrate/extrinsic-pool/src/listener.rs
  substrate/extrinsic-pool/src/pool.rs
Labels: A8-looksgood

#615 Make sure to ban invalid transactions.
  polkadot/transaction-pool/src/lib.rs
  polkadot/transaction-pool/src/rotator.rs
Labels: A8-looksgood, M4-core

#607 Introduce Runtime Events
  Cargo.lock
  README.adoc
  demo/cli/src/lib.rs
  demo/executor/Cargo.toml
  demo/executor/src/lib.rs
  demo/runtime/Cargo.toml
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/Cargo.toml
  substrate/runtime-support/src/lib.rs
  substrate/runtime/contract/src/account_db.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/Cargo.toml
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/Cargo.toml
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/staking/src/tests.rs
  substrate/runtime/system/Cargo.toml
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
Labels: A8-looksgood

#577 Allow specifying listening multiaddresses
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/traits.rs
Labels: A8-looksgood, M4-core

#619 Forward-port BFT fixes from v0.2 and restructure agreement cancelling
  Cargo.lock
  substrate/bft/src/lib.rs
  substrate/client/src/client.rs
Labels: A0-pleasereview

#620 [forwardport] Make sure to ban invalid transactions. (#615)
  substrate/extrinsic-pool/src/pool.rs
  substrate/extrinsic-pool/src/rotator.rs
Labels: A8-looksgood, M4-core

#506 Contracts: Per block gas limit
  substrate/runtime/contract/src/gas.rs
  substrate/runtime/contract/src/genesis_config.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
Labels: A8-looksgood, M4-core

#623 5 random fixes (#2)
  demo/cli/src/error.rs
  demo/cli/src/lib.rs
  subkey/src/main.rs
  substrate/cli/src/error.rs
  substrate/client/db/src/lib.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/mod.rs
  substrate/executor/wasm/src/lib.rs
  substrate/extrinsic-pool/src/pool.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network/src/blocks.rs
  substrate/network/src/protocol.rs
  substrate/primitives/src/bytes.rs
  substrate/primitives/src/rlp_codec.rs
  substrate/rpc/src/author/tests.rs
  substrate/runtime-io/src/lib.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime-sandbox/src/lib.rs
  substrate/runtime-std/src/lib.rs
  substrate/runtime/contract/src/vm/mod.rs
  substrate/service/src/components.rs
  substrate/state-db/src/unfinalized.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/trie_backend.rs
Labels: A2-insubstantial

#624 Avoid need for ident strings in storage
  demo/executor/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#635 Allow to build_upon skipped entries, but don't walk back
  substrate/bft/src/lib.rs
Labels: A8-looksgood

#637 Empty becomes (), reflecting convention
  substrate/runtime/primitives/src/traits.rs
Labels: A2-insubstantial

#638 random fixes
  substrate/environmental/src/lib.rs
  substrate/state-db/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#631 fix wasm executor compile error
  README.adoc
Labels: A2-insubstantial

#643 Install llvm-tools-preview component
  scripts/init.sh
Labels: A0-pleasereview, A2-insubstantial, M1-ci

#641 Backport removing mplex buffer in libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
Labels: A2-insubstantial

#640 Events to track extrinsic success
  demo/executor/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/bft/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood
