Repository paritytech/substrate, pull requests merged in 2018-05, with the labels that each got.

#139 Substrate test client crate & chain subscription test
  Cargo.lock
  substrate/client/Cargo.toml
  substrate/client/src/blockchain.rs
  substrate/client/src/client.rs
  substrate/client/src/genesis.rs
  substrate/client/src/lib.rs
  substrate/network/Cargo.toml
  substrate/network/src/lib.rs
  substrate/network/src/test/mod.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/tests.rs
  substrate/test-client/Cargo.toml
  substrate/test-client/src/client_ext.rs
  substrate/test-client/src/lib.rs
Labels: A8-looksgood

#140 Sandboxing and the simplest smart-contract runtime
  Cargo.lock
  Cargo.toml
  build.sh
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/init.sh
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/init.sh
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/codec/src/slicable.rs
  substrate/executor/Cargo.toml
  substrate/executor/src/lib.rs
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/Cargo.lock
  substrate/executor/wasm/Cargo.toml
  substrate/executor/wasm/build.sh
  substrate/executor/wasm/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/primitives/Cargo.toml
  substrate/primitives/src/lib.rs
  substrate/primitives/src/sandbox.rs
  substrate/runtime-sandbox/Cargo.toml
  substrate/runtime-sandbox/build.rs
  substrate/runtime-sandbox/src/lib.rs
  substrate/runtime-sandbox/with_std.rs
  substrate/runtime-sandbox/without_std.rs
  substrate/runtime/council/Cargo.toml
  substrate/runtime/primitives/Cargo.toml
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/contract.rs
  substrate/runtime/staking/src/lib.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/init.sh
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#133 Database backend
  .travis.yml
  Cargo.lock
  Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/cli/Cargo.toml
  polkadot/cli/src/lib.rs
  polkadot/keystore/Cargo.toml
  polkadot/keystore/src/lib.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/Cargo.toml
  polkadot/service/src/config.rs
  polkadot/service/src/lib.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/network/src/sync.rs
  substrate/runtime-io/without_std.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/testing.rs
Labels: A8-looksgood

#145 More testnet fixes
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/src/lib.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#147 Ensure all known BFT messages are imported when starting consensus
  polkadot/consensus/src/service.rs
  substrate/bft/src/generic/accumulator.rs
  substrate/bft/src/lib.rs
  substrate/network/src/consensus.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/test/consensus.rs
  substrate/network/src/test/mod.rs
Labels: A0-pleasereview

#149 node-key CLI option
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
Labels: A0-pleasereview

#148 Ensure VoteAdvance messages propagate
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  substrate/bft/src/generic/accumulator.rs
  substrate/bft/src/generic/mod.rs
  substrate/bft/src/lib.rs
  substrate/network/src/consensus.rs
Labels: A0-pleasereview

#151 update PoC-1 bootnodes
  polkadot/service/src/lib.rs
Labels: A2-insubstantial

#154 Fixed local net CLI example
  README.md
Labels: A2-insubstantial

#152 Fix sync: ensure block hash gets read from the DB correctly
  Cargo.lock
  polkadot/keystore/Cargo.toml
  polkadot/keystore/src/lib.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
Labels: A8-looksgood

#155 Networking and backend fixes
  substrate/network/src/blocks.rs
  substrate/network/src/consensus.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/consensus.rs
  substrate/network/src/test/mod.rs
Labels: A8-looksgood

#161 check if block is known before importing
  substrate/client/src/client.rs
  substrate/network/src/sync.rs
Labels: A8-looksgood

#158 Hook RPC extrinsic import into propagation
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/lib.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/rpc/src/author/mod.rs
  substrate/rpc/src/author/tests.rs
Labels: A8-looksgood

#157 Store trie nodes in DB
  Cargo.lock
  polkadot/api/src/lib.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/client.rs
  substrate/client/src/genesis.rs
  substrate/client/src/in_mem.rs
  substrate/network/src/service.rs
  substrate/state-machine/Cargo.toml
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/testing.rs
Labels: A8-looksgood

#153 Sandbox: run start function.
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
Labels: A8-looksgood

#166 Archive Mode and groundwork for state-preserving handles
  polkadot/consensus/src/service.rs
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/in_mem.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/lib.rs
Labels: A8-looksgood

#167 install wasm-gc using nightly
  polkadot/runtime/wasm/init.sh
Labels: A0-pleasereview

#165 Smart-contract inspection and instrumentation.
  Cargo.lock
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/contract.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#168 Contracts: Make Balance Slicable.
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/staking/src/contract.rs
  substrate/runtime/staking/src/lib.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#171 Contracts: Memory and Module instance teardowns
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-sandbox/without_std.rs
Labels: A8-looksgood

#174 Update transaction-pool dependency and remove ethereum-types
  Cargo.lock
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/lib.rs
Labels: A8-looksgood, M4-core

#150 Preparing light client structure [v2]
  Cargo.lock
  demo/cli/src/lib.rs
  polkadot/api/src/full.rs
  polkadot/api/src/lib.rs
  polkadot/api/src/light.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/informant.rs
  polkadot/cli/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/service/Cargo.toml
  polkadot/service/src/lib.rs
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/lib.rs
  substrate/client/src/light.rs
  substrate/network/Cargo.toml
  substrate/network/src/chain.rs
  substrate/network/src/lib.rs
  substrate/network/src/message.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/state/mod.rs
  substrate/test-client/src/client_ext.rs
  substrate/test-client/src/lib.rs
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/src/system.rs
  substrate/test-runtime/wasm/genesis.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#162 Balance is 128-bit value
  Cargo.lock
  polkadot/primitives/src/lib.rs
  polkadot/service/src/lib.rs
  substrate/runtime/primitives/src/int128.rs
  substrate/runtime/primitives/src/lib.rs
Labels: A8-looksgood

#176 Key generation utility
  Cargo.lock
  Cargo.toml
  subkey/Cargo.toml
  subkey/src/main.rs
  substrate/ed25519/Cargo.toml
  substrate/ed25519/src/lib.rs
Labels: A8-looksgood

#186 Use a simpler increment seed iterator.
  Cargo.lock
  subkey/Cargo.toml
  subkey/src/main.rs
Labels: A0-pleasereview

#191 Fixed consensus message garbage collection
  substrate/client/src/client.rs
  substrate/network/src/consensus.rs
  substrate/network/src/protocol.rs
Labels: A0-pleasereview

#193 Backport of #191
  substrate/client/src/client.rs
  substrate/network/src/consensus.rs
  substrate/network/src/protocol.rs
Labels: A8-backport

#178 Public extrinsic apply doesn't panic
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/src/config.rs
  polkadot/service/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/staking/src/contract.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#182 Extrinsic pool
  Cargo.lock
  Cargo.toml
  demo/cli/Cargo.toml
  demo/cli/src/lib.rs
  polkadot/cli/src/lib.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/service/src/config.rs
  polkadot/service/src/lib.rs
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/error.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/client/src/client.rs
  substrate/extrinsic-pool/Cargo.toml
  substrate/extrinsic-pool/src/api.rs
  substrate/extrinsic-pool/src/lib.rs
  substrate/extrinsic-pool/src/listener.rs
  substrate/extrinsic-pool/src/pool.rs
  substrate/extrinsic-pool/src/watcher.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/test/mod.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/author/error.rs
  substrate/rpc/src/author/mod.rs
  substrate/rpc/src/author/tests.rs
  substrate/rpc/src/lib.rs
Labels: A8-looksgood, M6-rpcapi
