Repository paritytech/substrate, pull requests merged in 2018-12, with the labels that each got.

#1189 make start_aura bounds more lenient
  core/consensus/aura/src/lib.rs
Labels: A2-insubstantial

#1195 Make `sr-api-macros` require at least `syn-0.15.22`
  core/sr-api-macros/Cargo.toml
Labels: A2-insubstantial

#1194 Cleanup the cli interface
  core/cli/src/lib.rs
  core/cli/src/params.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview

#1191 make block builder and construct_runtime! generic over inherent-data
  core/client/src/block_builder/api.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/client.rs
  core/consensus/rhd/src/lib.rs
  core/network/src/test/mod.rs
  core/service/src/consensus.rs
  core/service/test/src/lib.rs
  core/sr-primitives/src/lib.rs
  core/test-client/src/block_builder_ext.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/inherent.rs
  srml/support/src/runtime.rs
Labels: A8-looksgood

#1197 docs: typo and formatting fixes in code of conduct and contributors guidelines
  CODE_OF_CONDUCT.adoc
  CONTRIBUTING.adoc
Labels: A2-insubstantial, M3-docs

#1204 CheckInherentError can now report when something would be valid
  Cargo.lock
  core/consensus/rhd/src/lib.rs
  core/sr-primitives/src/lib.rs
  srml/support/src/inherent.rs
  srml/timestamp/Cargo.toml
  srml/timestamp/src/lib.rs
Labels: A8-looksgood

#1207 Update `rocksdb` to try minimizing memory leaks
  Cargo.lock
  README.adoc
  core/client/Cargo.toml
  core/client/db/Cargo.toml
Labels: A4-awaitingci

#1224 Move create network folder structure to top level of start_service
  core/network-libp2p/src/secret.rs
  core/network-libp2p/src/service_task.rs
Labels: A8-looksgood

#1190 Grandpa validator set handoff justification
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/fetcher.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/rhd/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/import_queue.rs
  core/network/src/test/mod.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/state/tests.rs
  core/service/src/chain_ops.rs
  core/sr-primitives/src/generic/block.rs
  core/test-client/src/client_ext.rs
  core/test-client/src/trait_tests.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/service.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1231 Configure max payload for HTTP & WS
  Cargo.lock
  core/rpc-servers/src/lib.rs
Labels: A8-looksgood

#1234 core: fix max depth handling of best_containing
  core/client/src/client.rs
Labels: A0-pleasereview

#1239 Fix master test build
  core/client/src/client.rs
Labels: A2-insubstantial

#1176 `decl_storage` as a proc_macro
  Cargo.lock
  Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/balances/src/mock.rs
  srml/consensus/src/mock.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/council/src/motions.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/Cargo.toml
  srml/support/procedural/Cargo.toml
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/Cargo.toml
  srml/support/procedural/tools/derive/Cargo.toml
  srml/support/procedural/tools/derive/src/lib.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  srml/upgrade-key/Cargo.toml
  srml/upgrade-key/src/lib.rs
Labels: A0-pleasereview

#1238 Remove BestAuthorities struct
  core/client/db/src/light.rs
Labels: A2-insubstantial

#1214 Make cli subcommands accept `--dev`, `--chain` and `--base_path`
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview

#1226 Make runtime api generate version and identifier information
  Cargo.lock
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/executor/src/native_executor.rs
  core/finality-grandpa/src/tests.rs
  core/rpc/src/chain/tests.rs
  core/service/src/consensus.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/sr-version/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1241 Update fixed-hash pin version and fix cargo locks
  Cargo.toml
  core/executor/wasm/Cargo.lock
  core/primitives/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  test-utils/chain-spec-builder/Cargo.lock
Labels: A2-insubstantial, A7-looksgoodtestsfail

#1230 Make `decl_module` not require a return type for functions
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/dispatch.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  srml/upgrade-key/src/lib.rs
Labels: A8-looksgood

#1213 Make CallApiAt::call_api_at work at light client
  core/client/src/blockchain.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/trie_backend_essence.rs
Labels: A8-looksgood, M4-core

#1236 Move pool maintainance to a background task.
  core/cli/src/lib.rs
  core/client/src/client.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/src/test/mod.rs
  core/service/src/components.rs
  core/service/src/error.rs
  core/service/src/lib.rs
  core/telemetry/src/lib.rs
  core/transaction-pool/graph/src/pool.rs
  srml/support/src/lib.rs
Labels: A8-looksgood, M4-core

#1233 Upload builds to releases.parity.io
  .gitlab-ci.yml
Labels: A8-looksgood

#1243 [RPC] Move runtime version from chain to state
  Cargo.lock
  core/rpc/src/author/mod.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
Labels: A8-looksgood, M6-rpcapi

#1249 add on_exit parameter to aura thread builder
  core/consensus/aura/src/lib.rs
Labels: A0-pleasereview

#1246 Do not compute storage root when proving execution/checking proof
  core/client/src/call_executor.rs
  core/state-machine/src/lib.rs
Labels: A0-pleasereview

#1250 Add simple keygen command to subkey
  subkey/src/cli.yml
  subkey/src/main.rs
  subkey/src/vanity.rs
Labels: A0-pleasereview

#1261 Add cli param to limit database cache size
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
Labels: A8-looksgood

#1263 fix overflow in slashing logic
  core/sr-primitives/src/traits.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, A8-looksgood

#1251 AuxStore on light clients
  core/client/db/src/light.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
Labels: A8-looksgood

#1266 srml-contract: caller follow-up
  srml/contract/COMPLEXITY.md
  srml/contract/src/tests.rs
  srml/contract/src/vm/mod.rs
Labels: A2-insubstantial, M3-docs

#1254 Lock-voting
  core/sr-primitives/src/testing.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/src/lib.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/democracy/src/vote_threshold.rs
Labels: A8-looksgood

#1185 Update SRML Assets: add total supply query, refactor with specific tests
  srml/assets/src/lib.rs
Labels: A4-awaitingci, A8-looksgood

#1271 Remove grandpa liveness oracle
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#1276 Update wabt to 0.7
  Cargo.lock
  core/executor/Cargo.toml
  core/sr-sandbox/Cargo.toml
  node/executor/Cargo.toml
  srml/contract/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#1267 Upgrade `sysinfo` to fix compilation on windows
  Cargo.lock
  core/cli/Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A2-insubstantial

#1269 Expose system health via RPC and REST
  Cargo.lock
  core/rpc-servers/src/lib.rs
  core/rpc/Cargo.toml
  core/rpc/src/lib.rs
  core/rpc/src/system/error.rs
  core/rpc/src/system/helpers.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/Cargo.toml
  core/service/src/components.rs
  core/service/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#1274 Consensus data added with generic use in service/src/consensus.rs. Th…
  Cargo.lock
  core/consensus/aura/primitives/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/lib.rs
  core/service/Cargo.toml
  core/service/src/consensus.rs
  core/service/src/lib.rs
Labels: A0-pleasereview

#1283 Don't call runtime if pool is empty.
  core/service/src/components.rs
  core/transaction-pool/graph/src/base_pool.rs
Labels: A8-looksgood, M4-core

#1286 Add additional Charred Cherry chain specification properties
  node/cli/res/charred-cherry.json
Labels: A8-looksgood

#1287 Avoid duplicate depencency declare via package re-export
  Cargo.lock
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  core/test-runtime/wasm/src
  core/test-runtime/wasm/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/runtime/wasm/src
  node/runtime/wasm/src/lib.rs
Labels: A8-looksgood

#1298 Reformat types string for decl_storage
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/src/storage/generator.rs
Labels: A8-looksgood

#1291 Fix usage error in README
  README.adoc
Labels: A8-looksgood

#1264 Include default values in storage metadata
  Cargo.lock
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/metadata/src/lib.rs
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/derive/src/lib.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
  srml/system/src/lib.rs
Labels: A8-looksgood

#1305 Fixed common block tracking on new block announcement
  core/network/src/sync.rs
Labels: A0-pleasereview

#1307 Bump to v0.9.1
  Cargo.lock
  Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A2-insubstantial

#1314 Compact extrinsics
  core/client/src/client.rs
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
Labels: A2-insubstantial

#1306 node: remove grandpa authority flags
  node/cli/src/lib.rs
  node/cli/src/params.rs
  node/cli/src/service.rs
Labels: A8-looksgood

#1315 Sudo module
  Cargo.lock
  Cargo.toml
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/sudo/Cargo.toml
  srml/sudo/src/lib.rs
Labels: A2-insubstantial

#1308 node: fix shutdown
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
Labels: A8-looksgood

#1319 typo: Hash -> Self::Hash
  core/sr-primitives/src/generic/digest.rs
Labels: A2-insubstantial

#1309 Make `deposit_event` work with none generic events
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/balances/src/lib.rs
  srml/contract/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/sudo/src/lib.rs
  srml/support/src/dispatch.rs
  srml/treasury/src/lib.rs
  srml/upgrade-key/src/lib.rs
Labels: A6-mustntgrumble

#1338 Make sure displaced leaves are removed from the db
  core/client/src/leaves.rs
Labels: A8-looksgood

#1282 Move import queue out of network
  Cargo.lock
  core/client/src/client.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/error.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/chain.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/service/src/chain_ops.rs
  core/service/src/components.rs
  core/test-client/src/client_ext.rs
Labels: A5-grumble

#1257 Moving core/service/consensus into new core/authorship crate
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/basic-authorship/src/lib.rs
  core/service/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/service.rs
Labels: A7-looksgoodcantmerge
