Repository paritytech/substrate, pull requests merged in 2018-03, with the labels that each got.

#80 Integrate transaction pool to the proposal logic
  Cargo.lock
  Cargo.toml
  polkadot/api/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/error.rs
  polkadot/consensus/src/lib.rs
  polkadot/primitives/src/transaction.rs
  polkadot/runtime/src/api.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#87 Format published wasm binaries package version with semver
  publish-wasm.sh
Labels: A2-insubstantial, A8-looksgood

#84 Slash Authorities for irrefutable misbehavior
  Cargo.lock
  Cargo.toml
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/lib.rs
  polkadot/executor/src/lib.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/transaction.rs
  polkadot/runtime/Cargo.toml
  polkadot/runtime/src/environment.rs
  polkadot/runtime/src/genesismap.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/runtime/consensus.rs
  polkadot/runtime/src/runtime/session.rs
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/Cargo.toml
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/bft/src/generic/accumulator.rs
  substrate/bft/src/generic/mod.rs
  substrate/bft/src/generic/tests.rs
  substrate/bft/src/lib.rs
  substrate/client/src/client.rs
  substrate/keyring/src/lib.rs
  substrate/misbehavior-check/Cargo.toml
  substrate/misbehavior-check/src/lib.rs
  substrate/network/src/test/mod.rs
  substrate/primitives/src/bft.rs
  substrate/runtime-std/with_std.rs
  substrate/runtime-std/without_std.rs
  substrate/runtime-support/src/storage.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#79 Substrate demo (a basic blockchain made with substrate)
  .gitignore
  Cargo.lock
  Cargo.toml
  build.sh
  demo/cli/Cargo.toml
  demo/cli/src/cli.yml
  demo/cli/src/error.rs
  demo/cli/src/lib.rs
  demo/executor/Cargo.toml
  demo/executor/src/lib.rs
  demo/primitives/Cargo.toml
  demo/primitives/src/block.rs
  demo/primitives/src/lib.rs
  demo/primitives/src/transaction.rs
  demo/runtime/Cargo.toml
  demo/runtime/src/api.rs
  demo/runtime/src/dispatch.rs
  demo/runtime/src/environment.rs
  demo/runtime/src/genesismap.rs
  demo/runtime/src/lib.rs
  demo/runtime/src/runtime/consensus.rs
  demo/runtime/src/runtime/council.rs
  demo/runtime/src/runtime/council_vote.rs
  demo/runtime/src/runtime/democracy.rs
  demo/runtime/src/runtime/mod.rs
  demo/runtime/src/runtime/session.rs
  demo/runtime/src/runtime/staking.rs
  demo/runtime/src/runtime/system.rs
  demo/runtime/src/runtime/timestamp.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/Cargo.toml
  demo/runtime/wasm/build.sh
  demo/runtime/wasm/genesis.wasm
  demo/runtime/wasm/init.sh
  demo/runtime/wasm/src
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  demo/src/main.rs
  polkadot/api/src/lib.rs
  polkadot/cli/src/cli.yml
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/codec/src/keyedvec.rs
  substrate/codec/src/slicable.rs
  substrate/ed25519/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/keyring/Cargo.toml
  substrate/keyring/src/lib.rs
  substrate/primitives/src/block.rs
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime-std/with_std.rs
  substrate/runtime-std/without_std.rs
  substrate/runtime-support/src/storage.rs
  substrate/test-runtime/src/block.rs
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#86 runtime-storage macro
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime-support/src/storage/mod.rs
Labels: A8-looksgood

#97 KeyStore implementation + key derivation
  Cargo.lock
  Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.yml
  polkadot/cli/src/error.rs
  polkadot/cli/src/lib.rs
  polkadot/keystore/Cargo.toml
  polkadot/keystore/src/lib.rs
  substrate/ed25519/src/lib.rs
Labels: A8-looksgood

#95 Modularised dispatch
  Cargo.lock
  demo/executor/src/lib.rs
  demo/primitives/src/block.rs
  demo/primitives/src/lib.rs
  demo/primitives/src/transaction.rs
  demo/runtime/Cargo.toml
  demo/runtime/src/block.rs
  demo/runtime/src/dispatch.rs
  demo/runtime/src/lib.rs
  demo/runtime/src/runtime/council.rs
  demo/runtime/src/runtime/council_vote.rs
  demo/runtime/src/runtime/democracy.rs
  demo/runtime/src/runtime/session.rs
  demo/runtime/src/runtime/staking.rs
  demo/runtime/src/runtime/system.rs
  demo/runtime/src/runtime/timestamp.rs
  demo/runtime/src/transaction.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/codec/src/endiansensitive.rs
  substrate/codec/src/lib.rs
  substrate/codec/src/slicable.rs
  substrate/ed25519/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#98 Refactor all (demo) runtime modules to use new storage
  demo/executor/src/lib.rs
  demo/runtime/src/genesismap.rs
  demo/runtime/src/lib.rs
  demo/runtime/src/runtime/council.rs
  demo/runtime/src/runtime/council_vote.rs
  demo/runtime/src/runtime/democracy.rs
  demo/runtime/src/runtime/session.rs
  demo/runtime/src/runtime/staking.rs
  demo/runtime/src/runtime/system.rs
  demo/runtime/src/runtime/timestamp.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#96 A random beacon
  demo/executor/src/lib.rs
  demo/runtime/src/api.rs
  demo/runtime/src/environment.rs
  demo/runtime/src/lib.rs
  demo/runtime/src/runtime/council.rs
  demo/runtime/src/runtime/council_vote.rs
  demo/runtime/src/runtime/democracy.rs
  demo/runtime/src/runtime/session.rs
  demo/runtime/src/runtime/staking.rs
  demo/runtime/src/runtime/system.rs
  demo/runtime/src/safe_mix.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/src/runtime/governance.rs
  polkadot/runtime/src/runtime/session.rs
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview
