Repository paritytech/substrate, pull requests merged in 2018-04, with the labels that each got.

#107 add BFT-with-startup-delay test
  substrate/bft/src/generic/tests.rs
Labels: A8-looksgood

#106 BFT gossip
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/keystore/src/lib.rs
  polkadot/service/src/config.rs
  polkadot/service/src/error.rs
  polkadot/service/src/lib.rs
  substrate/client/Cargo.toml
  substrate/client/src/client.rs
  substrate/client/src/lib.rs
  substrate/ed25519/src/lib.rs
  substrate/network/Cargo.toml
  substrate/network/src/consensus.rs
  substrate/network/src/lib.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
Labels: A0-pleasereview

#103 Migrate from parity-wasmi to wasmi.
  Cargo.lock
  substrate/executor/Cargo.toml
  substrate/executor/src/error.rs
  substrate/executor/src/lib.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/src/wasm_utils.rs
Labels: A8-looksgood

#109 Expose transaction pool from the polkadot service
  polkadot/service/src/lib.rs
Labels: A8-looksgood

#105 Make Polkadot use the Substrate traity libraries
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/primitives/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/Cargo.toml
  polkadot/api/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/lib.rs
  polkadot/executor/src/lib.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/block.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/parachain.rs
  polkadot/primitives/src/transaction.rs
  polkadot/primitives/src/validator.rs
  polkadot/runtime/Cargo.toml
  polkadot/runtime/src/api.rs
  polkadot/runtime/src/environment.rs
  polkadot/runtime/src/genesismap.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/parachains.rs
  polkadot/runtime/src/runtime/consensus.rs
  polkadot/runtime/src/runtime/governance.rs
  polkadot/runtime/src/runtime/mod.rs
  polkadot/runtime/src/runtime/parachains.rs
  polkadot/runtime/src/runtime/session.rs
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/src/runtime/timestamp.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/Cargo.toml
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/Cargo.toml
  polkadot/service/src/lib.rs
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/primitives/src/block.rs
  substrate/runtime/consensus/Cargo.toml
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/generic.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/Cargo.toml
  substrate/runtime/timestamp/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#116 Bumped devp2p
  Cargo.lock
  polkadot/cli/src/lib.rs
  substrate/network/Cargo.toml
  substrate/network/src/io.rs
  substrate/network/src/lib.rs
  substrate/network/src/service.rs
Labels: A2-insubstantial

#99 Transaction queue integration + submission RPC
  Cargo.lock
  demo/cli/Cargo.toml
  demo/cli/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/cli/src/lib.rs
  polkadot/consensus/src/lib.rs
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/lib.rs
  substrate/primitives/src/block.rs
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/author/error.rs
  substrate/rpc/src/author/mod.rs
  substrate/rpc/src/author/tests.rs
  substrate/rpc/src/lib.rs
Labels: A0-pleasereview

#112 Refactor Externalities to AccountDb.
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/staking/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#118 Basic informant
  Cargo.lock
  Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/cli/src/informant.rs
  polkadot/cli/src/lib.rs
  polkadot/src/main.rs
  substrate/client/src/client.rs
  substrate/network/src/lib.rs
Labels: A8-looksgood

#119 Fixed block proagation after import and import notifications
  .travis.yml
  polkadot/service/src/lib.rs
  substrate/client/src/client.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
Labels: A8-looksgood

#120 Extrinsics root is calculated as part of block-building
  Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/Cargo.toml
  polkadot/api/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/Cargo.toml
  polkadot/transaction-pool/Cargo.toml
  polkadot/transaction-pool/src/lib.rs
  substrate/bft/Cargo.toml
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/rpc/Cargo.toml
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/mod.rs
  substrate/rpc/src/state/tests.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#121 kill post_finalise
  demo/cli/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/src/lib.rs
  polkadot/consensus/src/error.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#123 artificial slowdown of consensus: delay before voting on proposals
  polkadot/api/src/lib.rs
  polkadot/consensus/src/error.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
Labels: A8-looksgood

#127 prune finalized transactions from the pool
  polkadot/service/src/lib.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/client.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/test/mod.rs
  substrate/primitives/src/block.rs
  substrate/runtime/primitives/src/traits.rs
Labels: A0-pleasereview

#126 Chain head subscription
  Cargo.lock
  build.sh
  demo/cli/Cargo.toml
  demo/cli/src/lib.rs
  polkadot/api/src/lib.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  substrate/client/src/client.rs
  substrate/rpc-servers/Cargo.toml
  substrate/rpc-servers/src/lib.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/author/error.rs
  substrate/rpc/src/author/tests.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/lib.rs
  substrate/rpc/src/metadata.rs
  substrate/rpc/src/subscriptions.rs
Labels: A8-looksgood

#137 handle exit and avoid threads hanging
  Cargo.lock
  polkadot/cli/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/service/Cargo.toml
  polkadot/service/src/lib.rs
  substrate/client/src/client.rs
Labels: A8-looksgood

#138 Improved logging
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/informant.rs
  polkadot/cli/src/lib.rs
Labels: A8-looksgood
