Repository paritytech/substrate, pull requests merged in 2018-09, with the labels that each got.

#639 WIP on chain heap
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  substrate/cli/src/cli.yml
  substrate/cli/src/lib.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/genesis.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/call_executor.rs
  substrate/executor/src/lib.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
  substrate/state-machine/Cargo.toml
  substrate/state-machine/src/lib.rs
  substrate/test-client/src/client_ext.rs
  substrate/test-runtime/src/genesismap.rs
  substrate/test-runtime/wasm/Cargo.lock
Labels: A3-inprogress

#601 Contract runtime polishing
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/contract/src/vm/env_def/macros.rs
  substrate/runtime/contract/src/vm/env_def/mod.rs
  substrate/runtime/contract/src/vm/mod.rs
Labels: A8-looksgood, M4-core

#648 Check for pruned block state
  substrate/client/db/src/lib.rs
  substrate/state-db/src/lib.rs
  substrate/state-db/src/pruning.rs
Labels: A8-looksgood

#649 Backport the current networking to v0.2
  Cargo.lock
  substrate/cli/src/lib.rs
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
  substrate/network-libp2p/src/traits.rs
  substrate/network-libp2p/src/transport.rs
  substrate/network-libp2p/tests/tests.rs
Labels: A8-backport

#645 Add a reputation system
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/topology.rs
  substrate/network-libp2p/src/transport.rs
Labels: A8-looksgood, M4-core

#653 Backport: Fix warnings in networking
  substrate/network-libp2p/src/service.rs
Labels: A2-insubstantial

#652 Fix warnings in networking
  substrate/network-libp2p/src/service.rs
Labels: A2-insubstantial

#656 Off-the-table staking preference
  Cargo.lock
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/tests.rs
Labels: A8-looksgood

#512 Replace old headers with CHT in light clients
  Cargo.lock
  substrate/client/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/db/src/light.rs
  substrate/client/src/blockchain.rs
  substrate/client/src/cht.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/client/src/genesis.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/lib.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/blockchain.rs
  substrate/client/src/light/fetcher.rs
  substrate/network/src/chain.rs
  substrate/network/src/message.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/service/src/components.rs
Labels: A8-looksgood

#660 Upgrade to libp2p master
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/service.rs
Labels: A2-insubstantial

#662 Backport: Reduce max backoff to 60 seconds
  substrate/network-libp2p/src/topology.rs
Labels: A2-insubstantial

#659 Minor refactor for staking module
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/tests.rs
Labels: A8-looksgood

#513 Limit number of retries for light client queries
  substrate/client/src/light/backend.rs
  substrate/client/src/light/blockchain.rs
  substrate/client/src/light/call_executor.rs
  substrate/client/src/light/fetcher.rs
  substrate/network/src/on_demand.rs
Labels: A8-looksgood

#617 Fetch parity-common dependencies from crates
  Cargo.lock
  demo/cli/Cargo.toml
  demo/executor/Cargo.toml
  demo/executor/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/client/Cargo.toml
  substrate/client/db/Cargo.toml
  substrate/executor/Cargo.toml
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/Cargo.lock
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/keystore/Cargo.toml
  substrate/network-libp2p/Cargo.toml
  substrate/primitives/Cargo.toml
  substrate/runtime-io/Cargo.toml
  substrate/runtime-io/with_std.rs
  substrate/state-machine/Cargo.toml
  substrate/test-client/Cargo.toml
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood, M5-dependencies

#642 Revert "fix wasm executor compile error"
  README.adoc
Labels: A6-revertrevert

#644 Revert "Install llvm-tools-preview component (#643)"
  scripts/init.sh
Labels: A6-revertrevert

#650 DigestItem trait (v2)
  Cargo.lock
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/lib.rs
  substrate/runtime/consensus/Cargo.toml
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/generic.rs
  substrate/runtime/primitives/src/testing.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A4-awaitingci, A8-looksgood

#666 Remove requirement of function indices for decl_module!
  demo/runtime/src/lib.rs
  substrate/runtime-support/src/dispatch.rs
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/example/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
Labels: A9-buythatmanabeer

#671 Speedup compilation of substrate-network-libp2p
  substrate/network-libp2p/src/service.rs
Labels: A0-pleasereview

#665 impl MaybeEmpty for H256 and u64 (aka AccountId in prod/tests)
  substrate/runtime/primitives/src/traits.rs
Labels: A7-looksgoodcantmerge

#670 Implement storage json metadata
  substrate/runtime-support/src/dispatch.rs
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
Labels: A8-looksgood

#674 Backport #673 to v0.2
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A8-backport

#673 Update to latest libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A0-pleasereview

#676 Update libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
Labels: A8-backport

#685 Backport networking changes 2018-09-07 edition
  Cargo.lock
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/topology.rs
Labels: A8-backport

#686 Switch to using parity/rust:substrate which has latest rust nightly
  .gitlab-ci.yml
Labels: A8-looksgood

#679 Fixed sync stalling when import queue is full
  substrate/network/src/sync.rs
Labels: A8-looksgood

#684 Use BufReader and BufWriter
  substrate/network-libp2p/src/topology.rs
Labels: A0-pleasereview

#688 Improvements to the Kademlia system
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/topology.rs
Labels: A0-pleasereview

#672 Implement json metadata for outer events
  Cargo.lock
  substrate/runtime-support/Cargo.toml
  substrate/runtime-support/src/event.rs
  substrate/runtime-support/src/lib.rs
Labels: A7-looksgoodcantmerge

#678 New extrinsic dispatch model
  Cargo.lock
  demo/executor/src/lib.rs
  demo/primitives/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/dispatch.rs
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/balances/src/mock.rs
  substrate/runtime/balances/src/tests.rs
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/contract/Cargo.toml
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/democracy/Cargo.toml
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/example/src/lib.rs
  substrate/runtime/executive/Cargo.toml
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/generic.rs
  substrate/runtime/primitives/src/generic/block.rs
  substrate/runtime/primitives/src/generic/checked_extrinsic.rs
  substrate/runtime/primitives/src/generic/header.rs
  substrate/runtime/primitives/src/generic/mod.rs
  substrate/runtime/primitives/src/generic/tests.rs
  substrate/runtime/primitives/src/generic/unchecked_extrinsic.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/primitives/src/testing.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/staking/src/tests.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
  substrate/runtime/version/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#691 [frontport] Fixed sync stalling when import queue is full
  substrate/network/src/sync.rs
Labels: A8-backport

#695 add mutate api
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/runtime/example/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
Labels: A9-buythatmanabeer

#573 LocalCallExecutor and RemoteCallRequest generic over Hasher and NodeCodec
  Cargo.lock
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/client/src/call_executor.rs
  substrate/client/src/light/call_executor.rs
  substrate/client/src/light/mod.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/Cargo.lock
  substrate/executor/wasm/Cargo.toml
  substrate/executor/wasm/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-io/Cargo.toml
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/service/src/components.rs
  substrate/test-client/src/lib.rs
  substrate/test-runtime/src/system.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A7-looksgoodcantmerge, M4-core

#697 Democracy module events
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A7-looksgoodtestsfail

#699 Remove docker from Substrate
  .dockerignore
  docker/build.sh
  docker/docker-compose.yml
  docker/readme-docker.adoc
Labels: A8-looksgood

#694 Council motions for approving treasury proposals
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/Cargo.toml
  demo/executor/src/lib.rs
  demo/runtime/Cargo.toml
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/primitives/src/lib.rs
  substrate/primitives/src/u32_trait.rs
  substrate/runtime-support/src/event.rs
  substrate/runtime-support/src/lib.rs
  substrate/runtime/council/Cargo.toml
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/motions.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#692 Implements `json_metadata` RPC call
  Cargo.lock
  demo/runtime/src/lib.rs
  substrate/client/src/client.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/error.rs
  substrate/rpc/src/state/mod.rs
  substrate/runtime-support/src/dispatch.rs
  substrate/runtime-support/src/event.rs
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/metadata.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/test-runtime/src/lib.rs
Labels: A8-looksgood

#702 Flag if the node is an Authority for Telemetry
  substrate/service/src/lib.rs
Labels: A8-looksgood

#687 DigestItem trait (v3)
  demo/primitives/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-support/src/lib.rs
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/primitives/src/generic/digest.rs
  substrate/runtime/primitives/src/generic/header.rs
  substrate/runtime/primitives/src/generic/mod.rs
  substrate/runtime/primitives/src/generic/tests.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/primitives/src/testing.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A4-awaitingci, A8-looksgood

#675 Integrate contracts into substrate-demo runtime
  Cargo.lock
  demo/runtime/Cargo.toml
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-std/with_std.rs
  substrate/runtime-std/without_std.rs
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/genesis_config.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/contract/src/vm/env_def/macros.rs
  substrate/runtime/contract/src/vm/env_def/mod.rs
  substrate/runtime/contract/src/vm/prepare.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#703 Council events
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/rpc/src/state/mod.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/council/src/motions.rs
  substrate/runtime/council/src/seats.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#704 Don't use Ext outside of runtime!!!
  substrate/client/src/call_executor.rs
Labels: A8-looksgood

#707 Fix treasury minting
  demo/executor/src/lib.rs
  demo/service/src/chain_spec.rs
  substrate/runtime-support/src/storage/generator.rs
  substrate/runtime/balances/src/genesis_config.rs
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/treasury/src/lib.rs
Labels: A8-looksgood

#701 Try to remove the caching from the build
  .gitlab-ci.yml
Labels: A2-insubstantial

#683 generic hash
  substrate/environmental/src/lib.rs
  substrate/environmental/with_std.rs
  substrate/environmental/without_std.rs
Labels: A0-pleasereview

#710 Improve event json metadata
  substrate/client/src/client.rs
  substrate/runtime-support/src/event.rs
  substrate/runtime-support/src/metadata.rs
  substrate/runtime/balances/src/lib.rs
  substrate/runtime/council/src/motions.rs
  substrate/runtime/council/src/seats.rs
  substrate/runtime/council/src/voting.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/example/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/treasury/src/lib.rs
  substrate/test-runtime/src/lib.rs
Labels: A6-mustntgrumble

#714 Remove cruft
  demo/api/src/lib.rs
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  substrate/client/src/client.rs
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#713 Timestamp module docs
  substrate/runtime/timestamp/src/lib.rs
Labels: A6-mustntgrumble

#712 Contracts: Add contract's GenesisConfig in demo-runtime
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/service/src/chain_spec.rs
  substrate/runtime/contract/src/genesis_config.rs
Labels: A8-looksgood

#716 Extract SimpleAddressDeterminator
  demo/runtime/src/lib.rs
  substrate/runtime/contract/src/lib.rs
Labels: A8-looksgood

#720 enhance dispatch
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
  srml/support/src/dispatch.rs
  srml/treasury/src/lib.rs
Labels: A9-buythatmanabeer

#723 Make `decl_event!` more ergonomic
  srml/balances/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/event.rs
  srml/support/src/metadata.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood

#724 Check if `cargo` already from nighlty in wasm build scripts
  core/executor/wasm/build.sh
  core/test-runtime/wasm/build.sh
  node/runtime/wasm/build.sh
Labels: A8-looksgood

#725 add a python script to show the runtime packages' dependencies
  scripts/runtime-dep.py
Labels: A8-looksgood

#727 Try to remove IPFS nodes from DHT
  substrate/network-libp2p/src/service.rs
Labels: A8-looksgood

#729 Make `impl_outer_event!` aware of required generic parameters
  node/runtime/src/lib.rs
  srml/council/src/lib.rs
  srml/executive/src/lib.rs
  srml/support/src/event.rs
  srml/support/src/metadata.rs
Labels: A7-looksgoodcantmerge

#735 Remove redundant code and merge rest into rt-std
  Cargo.lock
  Cargo.toml
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/sr-std/Cargo.toml
  core/sr-std/without_std.rs
  core/test-runtime/wasm/Cargo.lock
  doc/packages/substrate.adoc
  node/runtime/wasm/Cargo.lock
  pwasm-alloc/Cargo.toml
  pwasm-alloc/README.adoc
  pwasm-alloc/build.rs
  pwasm-alloc/src/lib.rs
  pwasm-libc/Cargo.toml
  pwasm-libc/README.adoc
  pwasm-libc/src/lib.rs
Labels: A8-looksgood

#737 Remove/use published versions of code
  Cargo.toml
  codec/Cargo.toml
  codec/README.adoc
  codec/derive/Cargo.toml
  codec/derive/src/decode.rs
  codec/derive/src/encode.rs
  codec/derive/src/lib.rs
  codec/derive/tests/mod.rs
  codec/src/codec.rs
  codec/src/joiner.rs
  codec/src/keyedvec.rs
  codec/src/lib.rs
  core/bft/Cargo.toml
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/extrinsic-pool/Cargo.toml
  core/metadata/Cargo.toml
  core/misbehavior-check/Cargo.toml
  core/network/Cargo.toml
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-sandbox/Cargo.toml
  core/sr-version/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.toml
  environmental/Cargo.toml
  environmental/README.adoc
  environmental/src/lib.rs
  environmental/with_std.rs
  environmental/without_std.rs
  node/consensus/Cargo.toml
  node/executor/Cargo.toml
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.toml
  node/transaction-pool/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A2-insubstantial

#743 Build project with --locked on CI
  .gitlab-ci.yml
  Cargo.lock
Labels: A2-insubstantial, M1-ci

#711 Contracts: return arbitrary sized buffers
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/vm/env_def/mod.rs
  srml/contract/src/vm/mod.rs
Labels: A0-pleasereview

#752 Update libp2p and increase listeners slots
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/traits.rs
Labels: A2-insubstantial

#755 SRML: fix OOB in srml_staking new_era.
  srml/staking/src/lib.rs
Labels: A8-looksgood

#757 Telemetry refactor
  Cargo.lock
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
Labels: A8-looksgood

#741 Generalised Transaction Queue API
  Cargo.lock
  core/bft/Cargo.toml
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/extrinsic-pool/Cargo.toml
  core/metadata/Cargo.toml
  core/misbehavior-check/Cargo.toml
  core/network/Cargo.toml
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/src/chain/tests.rs
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/transaction_validity.rs
  core/sr-sandbox/Cargo.toml
  core/sr-version/Cargo.toml
  core/sr-version/src/lib.rs
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  node/api/Cargo.toml
  node/api/src/lib.rs
  node/consensus/Cargo.toml
  node/executor/Cargo.toml
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/transaction-pool/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A0-pleasereview

#759 Make substrate node be the default exec to run
  Cargo.toml
  node/Cargo.toml
  node/build.rs
Labels: A2-insubstantial

#764 Extract well known keys into a single place
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/light/fetcher.rs
  core/primitives/src/storage.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  srml/consensus/src/lib.rs
  srml/system/src/lib.rs
Labels: A8-looksgood

#761 Implement codec for U256
  core/primitives/src/hasher.rs
  core/primitives/src/uint.rs
Labels: A0-pleasereview

#744 Fix error handling in sandboxing/contracts modules
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/src/lib.rs
  core/sr-sandbox/src/lib.rs
  core/sr-sandbox/with_std.rs
  core/sr-sandbox/without_std.rs
  srml/contract/src/vm/mod.rs
Labels: A0-pleasereview

#771 Cleanup client errors
  core/client/src/client.rs
  core/client/src/error.rs
Labels: A2-insubstantial

#766 Replace JSON metadata with custom metadata structures
  Cargo.lock
  Cargo.toml
  core/client/Cargo.toml
  core/client/src/client.rs
  core/client/src/lib.rs
  core/metadata/Cargo.toml
  core/metadata/src/lib.rs
  core/rpc/src/state/mod.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/metadata/Cargo.toml
  srml/metadata/README.adoc
  srml/metadata/src/lib.rs
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/runtime.rs
  srml/support/src/storage/generator.rs
Labels: A4-gotissues

#779 remove duplicate try_into_trie_backend
  core/state-machine/src/backend.rs
Labels: A8-looksgood

#758 Transaction eras
  Cargo.lock
  Cargo.toml
  core/cli/src/informant.rs
  core/client/src/client.rs
  core/rpc/Cargo.toml
  core/rpc/src/author/error.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/lib.rs
  core/service/Cargo.toml
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/generic/era.rs
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/transaction-pool/Cargo.toml
  core/transaction-pool/README.adoc
  core/transaction-pool/src/error.rs
  core/transaction-pool/src/lib.rs
  core/transaction-pool/src/listener.rs
  core/transaction-pool/src/pool.rs
  core/transaction-pool/src/rotator.rs
  core/transaction-pool/src/watcher.rs
  doc/packages/substrate.adoc
  node/api/src/lib.rs
  node/consensus/src/lib.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/service/src/lib.rs
  node/transaction-pool/Cargo.toml
  node/transaction-pool/src/error.rs
  node/transaction-pool/src/lib.rs
  srml/balances/src/lib.rs
  srml/council/src/seats.rs
  srml/executive/src/lib.rs
  srml/staking/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#782 Address grumbles in eras PR
  core/client/src/client.rs
  core/sr-primitives/src/generic/era.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/traits.rs
  node/api/src/lib.rs
  node/consensus/src/lib.rs
  node/executor/src/lib.rs
  node/transaction-pool/src/lib.rs
  srml/balances/src/lib.rs
  srml/system/src/lib.rs
Labels: A7-looksgoodtestsfail

#781 Rewards & slashes proportional to the least-slashable validator
  core/sr-primitives/src/lib.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/service/src/chain_spec.rs
  srml/staking/src/genesis_config.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A8-looksgood

#783 Get rid of core::string in sr-std.
  core/sr-std/with_std.rs
  core/sr-std/without_std.rs
  srml/contract/src/vm/env_def/macros.rs
  srml/contract/src/vm/env_def/mod.rs
  srml/contract/src/vm/prepare.rs
Labels: A8-looksgood

#760 Introduce notion of finality to substrate
  core/client/db/src/cache.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/service/src/chain_ops.rs
  core/sr-primitives/src/traits.rs
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/pruning.rs
  core/test-client/src/client_ext.rs
  srml/system/src/lib.rs
Labels: A8-looksgood

#786 Bump codec
  Cargo.lock
  core/bft/Cargo.toml
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/misbehavior-check/Cargo.toml
  core/network/Cargo.toml
  core/network/src/on_demand.rs
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/generic/tests.rs
  core/sr-sandbox/Cargo.toml
  core/sr-version/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/state-machine/src/ext.rs
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  core/transaction-pool/Cargo.toml
  node/consensus/Cargo.toml
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/transaction-pool/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/metadata/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/support/Cargo.toml
  srml/support/src/storage/mod.rs
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A2-insubstantial

#790 Removed From<H256> bound
  core/client/db/src/light.rs
  core/client/src/cht.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/service/src/components.rs
Labels: A8-looksgood

#788 Contracts: clean
  srml/contract/src/exec.rs
  srml/contract/src/vm/env_def/macros.rs
  srml/contract/src/vm/env_def/mod.rs
  srml/contract/src/vm/mod.rs
  srml/contract/src/vm/prepare.rs
  srml/contract/src/vm/runtime.rs
Labels: A8-looksgood

#791 Finality notification streams
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/in_mem.rs
  core/client/src/lib.rs
  core/network/src/chain.rs
  core/network/src/import_queue.rs
  core/network/src/service.rs
  core/network/src/specialization.rs
  core/network/src/test/mod.rs
  core/test-client/src/client_ext.rs
Labels: A8-looksgood

#787 Transactions dependency graph
  Cargo.lock
  Cargo.toml
  core/transaction-graph/Cargo.toml
  core/transaction-graph/src/error.rs
  core/transaction-graph/src/future.rs
  core/transaction-graph/src/lib.rs
  core/transaction-graph/src/pool.rs
  core/transaction-graph/src/ready.rs
Labels: A8-looksgood, M4-core, Z1-question

#794 Fixed extrinsic encoding
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  node/executor/src/lib.rs
Labels: A7-looksgoodtestsfail

#801 Contracts: Add transfer event
  Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/contract/Cargo.toml
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
Labels: A8-looksgood

#742 Rewrite the libp2p networking
  .cargo/config
  Cargo.lock
  core/cli/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/custom_proto.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/network_state.rs
  core/network-libp2p/src/node_handler.rs
  core/network-libp2p/src/secret.rs
  core/network-libp2p/src/service.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/swarm.rs
  core/network-libp2p/src/topology.rs
  core/network-libp2p/src/traits.rs
  core/network-libp2p/src/transport.rs
  core/network/src/lib.rs
Labels: A6-seemsok

#740 best_containing operations (issue 603)
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/leaves.rs
  core/client/src/lib.rs
  core/client/src/light/blockchain.rs
  core/test-client/src/block_builder_ext.rs
  core/test-client/src/client_ext.rs
  core/test-client/src/lib.rs
  core/test-client/src/trait_tests.rs
Labels: A6-seemsok

#804 Remove `node-api`
  Cargo.lock
  Cargo.toml
  node/api/Cargo.toml
  node/api/src/lib.rs
  node/consensus/Cargo.toml
  node/consensus/src/error.rs
  node/consensus/src/evaluation.rs
  node/consensus/src/lib.rs
  node/consensus/src/service.rs
  node/network/Cargo.toml
  node/network/src/consensus.rs
  node/network/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/transaction-pool/Cargo.toml
  node/transaction-pool/src/error.rs
  node/transaction-pool/src/lib.rs
Labels: A8-looksgood

#806 Remove accidentally-added .cargo/config
  .cargo/config
Labels: A2-insubstantial

#812 Remove `ethereum-types` as direct dependency
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/traits.rs
Labels: A2-insubstantial

#815 Updates dependencies and tries to consolidate multiple version
  Cargo.lock
  Cargo.toml
  build.rs
  core/bft/Cargo.toml
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network/Cargo.toml
  core/rpc-servers/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/state-machine/Cargo.toml
  core/telemetry/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.toml
  core/transaction-graph/Cargo.toml
  core/transaction-pool/Cargo.toml
  node/cli/Cargo.toml
  node/consensus/Cargo.toml
  node/service/Cargo.toml
  node/src/main.rs
  node/transaction-pool/Cargo.toml
Labels: A8-looksgood

#816 Support authoring for multiple runtime versions
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/light/call_executor.rs
  core/executor/src/lib.rs
  core/executor/src/native_executor.rs
  core/sr-version/src/lib.rs
  core/test-client/src/lib.rs
  core/test-runtime/src/lib.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood

#810 Fix block generation by updating codec versions in wasm
  Cargo.lock
  core/bft/Cargo.toml
  core/cli/src/cli.yml
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/executor/wasm/Cargo.toml
  core/keystore/Cargo.toml
  core/network/Cargo.toml
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/serializer/Cargo.toml
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-sandbox/Cargo.toml
  core/sr-version/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  core/transaction-pool/Cargo.toml
  core/trie/Cargo.toml
  node/cli/src/lib.rs
  node/consensus/Cargo.toml
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/service/res/bbq-birch.json
  node/service/src/chain_spec.rs
  node/transaction-pool/Cargo.toml
  scripts/update.sh
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/metadata/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A0-pleasereview

#821 Fix newline.
  core/cli/src/lib.rs
Labels: A2-insubstantial

#820 ensure meta is actually in the right column and sanity check on iterator
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/leaves.rs
Labels: A0-pleasereview

#822 Introduce ExtBuilder in balances tests
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
Labels: A0-pleasereview

#825 More dependency cleanup
  Cargo.lock
  ci/script.sh
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/src/lib.rs
  core/executor/Cargo.toml
  core/executor/src/lib.rs
  core/executor/wasm/Cargo.lock
  core/keystore/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/lib.rs
  core/rpc-servers/Cargo.toml
  core/rpc-servers/src/lib.rs
  core/rpc/Cargo.toml
  core/rpc/src/lib.rs
  core/sr-sandbox/Cargo.toml
  core/sr-sandbox/src/lib.rs
  core/sr-version/src/lib.rs
  core/state-db/src/lib.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/lib.rs
  core/test-client/Cargo.toml
  core/test-client/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/transaction-pool/Cargo.toml
  node/transaction-pool/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/contract/src/lib.rs
  srml/council/Cargo.toml
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/staking/Cargo.toml
  srml/staking/src/lib.rs
  srml/support/Cargo.toml
  srml/support/src/lib.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A9-buythatmanabeer

#823 SS58 addresses in BFT
  core/primitives/src/authority_id.rs
Labels: A7-looksgoodtestsfail

#824 Prevent exploiting overflow in Balances::transfer
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
Labels: A7-looksgoodcantmerge

#827 pass correct header column to read_meta again
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
Labels: A6-seemsok

#829 Add test that ensures drain funds to death works
  srml/contract/src/double_map.rs
  srml/contract/src/exec.rs
  srml/contract/src/tests.rs
Labels: A8-looksgood

#828 Load code from the overlay not from the database
  srml/contract/src/exec.rs
Labels: A8-looksgood

#805 Integration tests
  Cargo.lock
  Cargo.toml
  core/cli/src/cli.yml
  core/cli/src/lib.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/mod.rs
  core/network/src/lib.rs
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/Cargo.toml
  core/service/test/src/lib.rs
  core/state-machine/Cargo.toml
  core/test-client/src/client_ext.rs
  core/test-client/src/lib.rs
  node/cli/src/lib.rs
  node/consensus/src/lib.rs
  node/consensus/src/service.rs
  node/network/src/consensus.rs
  node/runtime/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  srml/staking/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A6-seemsok

#769 Fetching changes proof from remote nodes
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/test-client/src/client_ext.rs
  core/test-client/src/lib.rs
  core/test-client/src/trait_tests.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
Labels: A6-seemsok

#832 Clean up the "custom protocol" code
  core/network-libp2p/src/custom_proto.rs
  core/network-libp2p/src/node_handler.rs
Labels: A8-looksgood

#838 Limit gossip for non-authorities
  Cargo.lock
  core/network/Cargo.toml
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/sync.rs
Labels: A8-looksgood

#841 Fixed consensus message garbage collection & DB initialization
  core/client/src/client.rs
  core/network/src/consensus_gossip.rs
  core/service/test/src/lib.rs
  node/network/src/lib.rs
Labels: A8-looksgood

#843 Add `restore` command to subkey
  Cargo.lock
  subkey/Cargo.toml
  subkey/src/cli.yml
  subkey/src/main.rs
  subkey/src/vanity.rs
Labels: A0-pleasereview

#842 Take and return Bytes in state_call
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
Labels: A8-looksgood

#844 Remove `#![feature(panic_handler)]`
  core/executor/wasm/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-sandbox/src/lib.rs
  core/sr-std/src/lib.rs
Labels: A0-pleasereview

#846 metadata returns Bytes
  core/rpc/src/state/mod.rs
Labels: A0-pleasereview

#850 Fixed transaction propagation
  Cargo.lock
  core/network/src/protocol.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  node/runtime/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview

#854 Fixed panic on duplicate extrinsic import
  core/service/src/lib.rs
Labels: A0-pleasereview

#849 Auxiliary data storage in client backend
  core/client/db/src/lib.rs
  core/client/db/src/utils.rs
  core/client/src/backend.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
Labels: A0-pleasereview
