Repository paritytech/substrate, pull requests merged in 2018-11, with the labels that each got.

#958 Support multi trie in genesis generation
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/genesis.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/mod.rs
  core/finality-grandpa/src/lib.rs
  core/network/src/chain.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/state/mod.rs
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/consensus.rs
  core/sr-primitives/src/lib.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
  core/test-client/src/lib.rs
  core/transaction-pool/src/api.rs
  node/executor/src/lib.rs
  srml/assets/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/consensus/src/lib.rs
  srml/consensus/src/mock.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/council/src/motions.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A7-looksgoodcantmerge

#1038 Refine Complexity.md
  srml/contract/COMPLEXITY.md
Labels: A0-pleasereview

#1047 docker: use alpine to slim down images
  Dockerfile
Labels: A7-looksgoodcantmerge

#1057 Make `balance::Trait::Balance` require `Member`
  srml/balances/src/lib.rs
Labels: A2-insubstantial

#1062 Backport #931 to bbq-birch
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/custom_proto.rs
  core/network-libp2p/src/node_handler.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/swarm.rs
  core/network-libp2p/src/transport.rs
Labels: A8-backport

#941 Delete unused extern
  Cargo.lock
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
Labels: A2-insubstantial, A4-clasignoffneeded

#1078 Update fixed-hash & uint utilities
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/src/genesis.rs
  core/client/src/light/fetcher.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/network/src/on_demand.rs
  core/network/src/test/mod.rs
  core/primitives/Cargo.toml
  core/primitives/src/ed25519.rs
  core/primitives/src/hash.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/chain/tests.rs
  core/sr-io/with_std.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/test.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/test-client/src/block_builder_ext.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/graph/src/pool.rs
  core/trie/src/lib.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A7-looksgoodtestsfail, A8-looksgood

#1080 Last finalised block PubSub & RPC
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
Labels: A8-looksgood, M6-rpcapi

#1081 Fix race in import queue stopping
  core/network/src/import_queue.rs
Labels: A0-pleasereview

#1101 Fix docker image
  Dockerfile
Labels: A0-pleasereview

#1104 RPC: expose chain spec `properties`
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/src/chain_spec.rs
  core/service/src/lib.rs
  node/cli/res/bbq-birch.json
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, M6-rpcapi

#1044 srml-contract: Extract schedule
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/COMPLEXITY.md
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/vm/env_def/macros.rs
  srml/contract/src/vm/mod.rs
  srml/contract/src/vm/prepare.rs
  srml/contract/src/vm/runtime.rs
Labels: A0-pleasereview

#950 Changes tries: support forks
  core/client/db/src/lib.rs
  core/client/db/src/utils.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/executor/src/wasm_executor.rs
  core/primitives/src/hash.rs
  core/primitives/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/system/src/lib.rs
Labels: A8-looksgood

#1094 Implement runtime api client side directly in the runtime
  Cargo.lock
  Cargo.toml
  core/cli/src/informant.rs
  core/client/Cargo.toml
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/block_builder/api.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/block_builder/mod.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/light/mod.rs
  core/client/src/runtime_api/core.rs
  core/client/src/runtime_api/macros.rs
  core/client/src/runtime_api/mod.rs
  core/client/src/runtime_api/traits.rs
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/network/src/chain.rs
  core/network/src/import_queue.rs
  core/network/src/test/mod.rs
  core/primitives/src/lib.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/state/mod.rs
  core/service/src/components.rs
  core/service/src/consensus.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-api/Cargo.toml
  core/sr-primitives/src/traits.rs
  core/test-client/Cargo.toml
  core/test-client/src/block_builder_ext.rs
  core/test-client/src/client_ext.rs
  core/test-client/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/src/api.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/metadata/Cargo.toml
  srml/metadata/src/lib.rs
Labels: A8-looksgood

#1109 Fix extrinsic impl
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  srml/support/src/dispatch.rs
Labels: A2-insubstantial

#1111 Clean up justification
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/rhd/src/lib.rs
  core/network/src/import_queue.rs
  core/test-client/src/client_ext.rs
  node/cli/src/service.rs
Labels: A8-looksgood

#896 Fetch changes trie roots + CHT-based proof for these roots
  core/client/db/src/light.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/in_mem.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/fetcher.rs
  core/client/src/light/mod.rs
  core/network/src/chain.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/service/src/components.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1113 Fix overflow in srml-contract
  srml/contract/src/gas.rs
Labels: A8-looksgood

#1121 Try to get grandpa tests compiling again
  core/client/db/src/light.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/client.rs
  core/client/src/light/blockchain.rs
  core/client/src/runtime_api/macros.rs
  core/client/src/runtime_api/mod.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/test-client/src/block_builder_ext.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1123 rename fg-primitives to more verbose name
  Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/primitives/Cargo.toml
  core/finality-grandpa/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
Labels: A2-insubstantial

#1126 add extra verification for aura
  core/consensus/aura/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#1129 Make sure to call the runtime trait functions
  core/client/src/runtime_api/macros.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A6-seemsok

#1119 Update wasmi
  Cargo.lock
  core/executor/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-sandbox/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1133 Revert and redo #952
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/src/runtime_api/macros.rs
  core/consensus/aura/src/lib.rs
  core/executor/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-sandbox/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/mock.rs
  srml/consensus/src/mock.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/src/storage/generator.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview

#1130 Fix light client startup
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/client.rs
Labels: A8-looksgood

#1136 Fix typo in `apply_extrinsic`
  core/client/src/block_builder/api.rs
Labels: A2-insubstantial

#1137 Fix doc on set_validator_count
  srml/staking/src/lib.rs
Labels: A2-insubstantial

#1135 alter DB schema to fix lookup race
  core/client/db/src/cache/list_storage.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
Labels: A8-looksgood

#1141 docs: Fix typos
  srml/council/src/seats.rs
Labels: A2-insubstantial, A8-looksgood

#1140 Removed duplicate source, fix paritytech/substrate#549
  Cargo.lock
  substrate/rpc/Cargo.toml
Labels: A0-pleasereview

#1153 Make `grandpa` export its calls
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A2-insubstantial

#1154 add leaves function to ChainHead trait
  core/client/src/client.rs
Labels: A2-insubstantial

#1164 Fix purge-chain cli option
  core/cli/src/lib.rs
Labels: A2-insubstantial

#1166 Simplify consensus message sending
  core/finality-grandpa/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A8-looksgood

#1169 Misspelled words
  core/finality-grandpa/src/authorities.rs
Labels: A2-insubstantial

#1171 Remove Proposer from Service
  Cargo.lock
  core/service/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli/src/service.rs
Labels: A4-awaitingci

#1174 Rewrite `impl_runtime_apis!` and `decl_runtime_apis!` as proc-macro
  Cargo.lock
  Cargo.toml
  core/client/Cargo.toml
  core/client/src/block_builder/api.rs
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/runtime_api.rs
  core/client/src/runtime_api/core.rs
  core/client/src/runtime_api/macros.rs
  core/client/src/runtime_api/traits.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/import_queue.rs
  core/network/src/test/mod.rs
  core/service/src/consensus.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/src/utils.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-primitives/src/generic/era.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/test-client/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/consensus/src/lib.rs
  srml/support/src/inherent.rs
  srml/support/src/lib.rs
  srml/support/src/runtime.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview

#1180 Make `AuthorityId` serialize/deserialize to/from `ss58`
  core/primitives/src/authority_id.rs
  core/primitives/src/ed25519.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview
