Repository paritytech/substrate, pull requests merged in 2018-02, with the labels that each got.

#56 Publish wasm runtime binaries from CI
  .gitignore
  .travis.yml
  publish-wasm.sh
Labels: A8-looksgood, M1-ci

#71 Sed explicit parameters
  publish-wasm.sh
Labels: A0-pleasereview, A2-insubstantial

#69 Additional runtime tests for the test-runtime
  Cargo.lock
  Cargo.toml
  polkadot/api/src/lib.rs
  polkadot/cli/src/lib.rs
  polkadot/executor/Cargo.toml
  polkadot/executor/src/lib.rs
  polkadot/runtime/Cargo.toml
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/runtime/governance.rs
  polkadot/runtime/src/runtime/parachains.rs
  polkadot/runtime/src/runtime/session.rs
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/client/Cargo.toml
  substrate/client/src/backend.rs
  substrate/client/src/error.rs
  substrate/client/src/genesis.rs
  substrate/client/src/lib.rs
  substrate/ed25519/Cargo.toml
  substrate/ed25519/src/lib.rs
  substrate/executor/src/lib.rs
  substrate/executor/src/native_executor.rs
  substrate/keyring/Cargo.toml
  substrate/keyring/src/lib.rs
  substrate/runtime-support/Cargo.toml
  substrate/runtime-support/src/lib.rs
  substrate/runtime-support/src/testing.rs
  substrate/state-machine/src/lib.rs
  substrate/test-runtime/Cargo.toml
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/src/system.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/Cargo.toml
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#74 Add codec tests
  substrate/primitives/src/block.rs
  substrate/test-runtime/src/transaction.rs
  substrate/test-runtime/src/unchecked_transaction.rs
Labels: A8-looksgood

#72 Split BFT into substrate-bft and runtime-specific proposer logic
  Cargo.lock
  Cargo.toml
  polkadot/candidate-agreement/Cargo.toml
  polkadot/candidate-agreement/src/handle_incoming.rs
  polkadot/candidate-agreement/src/lib.rs
  polkadot/candidate-agreement/src/round_robin.rs
  polkadot/candidate-agreement/src/tests/mod.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/lib.rs
  polkadot/primitives/src/parachain.rs
  polkadot/primitives/src/transaction.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/statement-table/Cargo.toml
  polkadot/statement-table/src/generic.rs
  polkadot/statement-table/src/lib.rs
  substrate/bft/Cargo.toml
  substrate/bft/src/error.rs
  substrate/bft/src/generic/accumulator.rs
  substrate/bft/src/generic/mod.rs
  substrate/bft/src/generic/tests.rs
  substrate/bft/src/lib.rs
  substrate/codec/src/slicable.rs
  substrate/ed25519/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/primitives/src/bft.rs
  substrate/primitives/src/block.rs
  substrate/primitives/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#73 Block builder (substrate)
  Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/client/Cargo.toml
  substrate/client/src/backend.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/lib.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/wasm_executor.rs
  substrate/network/Cargo.toml
  substrate/network/src/lib.rs
  substrate/network/src/test/mod.rs
  substrate/network/src/test/sync.rs
  substrate/primitives/src/block.rs
  substrate/primitives/src/lib.rs
  substrate/rpc/Cargo.toml
  substrate/rpc/src/chain/tests.rs
  substrate/rpc/src/lib.rs
  substrate/rpc/src/state/tests.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/lib.rs
  substrate/test-runtime/src/genesismap.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#76 Verify header justification during import
  Cargo.lock
  polkadot/api/src/lib.rs
  polkadot/primitives/src/block.rs
  substrate/bft/Cargo.toml
  substrate/bft/src/error.rs
  substrate/bft/src/generic/accumulator.rs
  substrate/bft/src/lib.rs
  substrate/client/Cargo.toml
  substrate/client/src/backend.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/blockchain.rs
  substrate/client/src/error.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/lib.rs
  substrate/ed25519/src/lib.rs
  substrate/network/Cargo.toml
  substrate/network/src/blocks.rs
  substrate/network/src/chain.rs
  substrate/network/src/lib.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
  substrate/network/src/test/sync.rs
  substrate/primitives/src/bft.rs
  substrate/primitives/src/block.rs
  substrate/primitives/src/lib.rs
  substrate/rpc/src/chain/mod.rs
  substrate/rpc/src/state/mod.rs
  substrate/runtime-std/with_std.rs
  substrate/runtime-std/without_std.rs
Labels: A8-looksgood

#75 Optional storage entries
  polkadot/executor/src/lib.rs
  polkadot/runtime/src/runtime/governance.rs
  polkadot/runtime/src/runtime/parachains.rs
  polkadot/runtime/src/runtime/session.rs
  polkadot/runtime/src/runtime/staking.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/src/runtime/timestamp.rs
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/client/src/backend.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/client/src/genesis.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/lib.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/rpc/src/state/tests.rs
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime-support/src/storage.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/testing.rs
  substrate/test-runtime/src/system.rs
  substrate/test-runtime/wasm/genesis.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#77 Proposal creation and evaluation to plug into BFT
  Cargo.lock
  polkadot/api/Cargo.toml
  polkadot/api/src/lib.rs
  polkadot/collator/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/error.rs
  polkadot/consensus/src/lib.rs
  polkadot/executor/src/lib.rs
  polkadot/primitives/src/block.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/parachain.rs
  polkadot/primitives/src/transaction.rs
  polkadot/runtime/src/api.rs
  polkadot/runtime/src/environment.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/runtime/system.rs
  polkadot/runtime/src/runtime/timestamp.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/bft/src/error.rs
  substrate/bft/src/generic/mod.rs
  substrate/bft/src/generic/tests.rs
  substrate/bft/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/primitives/src/block.rs
  substrate/runtime-support/src/storage.rs
  substrate/state-machine/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview
