Repository paritytech/substrate, pull requests merged in 2018-10, with the labels that each got.

#848 Global unique subscription ids.
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/lib.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
  core/rpc/src/subscriptions.rs
  core/service/src/lib.rs
  subkey/src/vanity.rs
Labels: A7-looksgoodtestsfail, M6-rpcapi

#858 RPC: return correct block hash in extrinsics watchers
  core/rpc-servers/src/lib.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/transaction-pool/src/lib.rs
  core/transaction-pool/src/listener.rs
  core/transaction-pool/src/pool.rs
  core/transaction-pool/src/watcher.rs
  node/transaction-pool/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#859 The NodeId is always available in the session info
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service.rs
  core/network-libp2p/src/traits.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#868 Updating Moment to support Mul/Div with BlockNumber
  srml/session/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview

#871 Fix CPU metrics on Linux
  Cargo.lock
  core/cli/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#869 Compare digests item-by-item
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/traits.rs
  srml/executive/src/lib.rs
Labels: A8-looksgood

#874 Extract search of digest item into Digest::log() function
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/sr-primitives/src/traits.rs
Labels: A2-insubstantial, A8-looksgood

#866 Initial GRANDPA integration
  Cargo.lock
  Cargo.toml
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/lib.rs
  core/network/Cargo.toml
  core/network/src/consensus_gossip.rs
  core/network/src/import_queue.rs
  core/network/src/lib.rs
  core/network/src/test/mod.rs
  node/network/src/lib.rs
Labels: A6-seemsok

#877 Add missing `As` imports.
  srml/session/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#862 Filter peers on light nodes
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
Labels: A6-seemsok

#881 Clean up the networking layer
  Cargo.lock
  core/network-libp2p/src/connection_filter.rs
  core/network-libp2p/src/custom_proto.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/node_handler.rs
  core/network-libp2p/src/service.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/swarm.rs
  core/network-libp2p/src/timeouts.rs
  core/network-libp2p/src/traits.rs
  core/network-libp2p/tests/tests.rs
  core/network/Cargo.toml
  core/network/src/io.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  node/network/src/consensus.rs
Labels: A8-looksgood

#836 authorities_at cache update
  core/client/db/src/cache.rs
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/list_entry.rs
  core/client/db/src/cache/list_storage.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
Labels: A6-seemsok

#904 Silence Telemetry WS errors
  core/cli/src/lib.rs
  core/telemetry/src/lib.rs
Labels: A0-pleasereview, M4-core

#906 System should provide default Lookup impl
  srml/system/src/lib.rs
Labels: A2-insubstantial

#909 Rename min-peers and max-peers CLI options
  core/cli/src/cli.yml
  core/cli/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/traits.rs
  core/service/test/src/lib.rs
Labels: A8-looksgood

#903 Pool: Longevity handling.
  core/service/src/lib.rs
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/lib.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/graph/src/rotator.rs
  core/transaction-pool/src/tests.rs
  node/consensus/src/lib.rs
Labels: A0-pleasereview, M4-core

#900 Remove the packet ID system
  core/network-libp2p/src/custom_proto.rs
Labels: A8-looksgood

#856 Pruning changes tries
  core/client/db/src/lib.rs
  core/primitives/src/changes_trie.rs
  core/state-db/src/lib.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
Labels: A0-pleasereview

#905 Contracts: COMPLEXITY.md
  srml/contract/COMPLEXITY.md
  srml/contract/src/lib.rs
  srml/contract/src/vm/runtime.rs
Labels: A0-pleasereview

#890 Index blocks by number in the DB
  core/client/db/src/cache/list_storage.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
Labels: A8-looksgood

#922 Pool: parallel ready and runtime changes
  core/client/src/client.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/rpc/src/author/mod.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-primitives/src/transaction_validity.rs
  core/test-runtime/src/system.rs
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/src/tests.rs
  srml/executive/src/lib.rs
Labels: A8-looksgood, M4-core

#924 Move inherent implementation into the modules
  Cargo.lock
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/client.rs
  core/client/src/notifications.rs
  core/network/src/blocks.rs
  core/network/src/consensus_gossip.rs
  core/sr-api/Cargo.toml
  core/sr-api/src/lib.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/generic/block.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-std/without_std.rs
  core/sr-version/Cargo.toml
  core/sr-version/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  node/consensus/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/consensus/src/lib.rs
  srml/support/src/inherent.rs
  srml/support/src/lib.rs
  srml/support/src/runtime.rs
  srml/timestamp/Cargo.toml
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview

#929 Fixes tests on master
  core/transaction-pool/graph/src/pool.rs
Labels: A2-insubstantial

#902 Multiple storage root support
  core/client/src/cht.rs
  core/client/src/light/backend.rs
  core/executor/src/wasm_executor.rs
  core/network-libp2p/src/custom_proto.rs
  core/primitives/src/storage.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/trie/src/lib.rs
Labels: A6-seemsok, M4-core

#932 Moved DigestItem impl to impl_outer_log
  .gitlab-ci.yml
  core/service/test/src/lib.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood, M4-core

#936 Remove nonsense code and options, fix score and generally make subkey work
  core/service/src/lib.rs
  node/cli/src/service.rs
  subkey/src/main.rs
  subkey/src/vanity.rs
Labels: A8-looksgood

#940 Add runtime so that cargo install works
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A2-insubstantial

#956 Make `decl_storage!` assume less about the environment
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/lib.rs
  srml/support/src/storage/generator.rs
Labels: A0-pleasereview

#953 Multiple improvements to the `decl_module!` macro
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/contract/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/dispatch.rs
  srml/support/src/metadata.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview

#934 Use local index for misbehaviour calculation
  node/consensus/src/lib.rs
Labels: A8-looksgood, M4-core

#1041 Use the upstream version of integer-sqrt.
  Cargo.lock
  core/sr-primitives/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
Labels: A2-insubstantial, A4-awaitingci
