Repository paritytech/substrate, pull requests merged in 2018-07, with the labels that each got.

#229 Serialisable genesis config
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/src/full.rs
  polkadot/cli/Cargo.toml
  polkadot/cli/poc-1.json
  polkadot/cli/src/chain_spec.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/consensus/src/shared_table/mod.rs
  polkadot/runtime/src/lib.rs
  polkadot/runtime/src/parachains.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/Cargo.toml
  polkadot/service/res/poc-1.json
  polkadot/service/src/chain_spec.rs
  polkadot/service/src/components.rs
  polkadot/service/src/config.rs
  polkadot/service/src/lib.rs
  substrate/bft/src/lib.rs
  substrate/client/src/client.rs
  substrate/client/src/genesis.rs
  substrate/ed25519/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/misbehavior-check/src/lib.rs
  substrate/network/src/test/consensus.rs
  substrate/primitives/src/authority_id.rs
  substrate/primitives/src/bytes.rs
  substrate/primitives/src/lib.rs
  substrate/runtime/consensus/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
  substrate/test-client/src/client_ext.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#274 Bump wabt-rs to 0.4.
  Cargo.lock
  substrate/executor/Cargo.toml
  substrate/runtime-sandbox/Cargo.toml
  substrate/runtime/contract/Cargo.toml
  substrate/runtime/staking/Cargo.toml
Labels: A2-insubstantial

#256 Runtime version
  Cargo.lock
  Cargo.toml
  demo/executor/src/lib.rs
  demo/runtime/Cargo.toml
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/api/src/full.rs
  polkadot/api/src/lib.rs
  polkadot/api/src/light.rs
  polkadot/consensus/src/collation.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/service.rs
  polkadot/executor/src/lib.rs
  polkadot/runtime/Cargo.toml
  polkadot/runtime/src/lib.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/Cargo.toml
  polkadot/runtime/wasm/genesis.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/transaction-pool/src/lib.rs
  substrate/bft/src/error.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/client/src/genesis.rs
  substrate/client/src/lib.rs
  substrate/client/src/light/call_executor.rs
  substrate/codec/src/lib.rs
  substrate/codec/src/slicable.rs
  substrate/executor/Cargo.toml
  substrate/executor/src/lib.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/rpc/src/chain/tests.rs
  substrate/runtime/version/Cargo.toml
  substrate/runtime/version/src/lib.rs
  substrate/test-client/src/lib.rs
  substrate/test-runtime/Cargo.toml
  substrate/test-runtime/src/lib.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/Cargo.toml
  substrate/test-runtime/wasm/genesis.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
  update-genesis.sh
Labels: A8-looksgood

#272 Block import and export
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/service/src/lib.rs
  substrate/client/src/client.rs
  substrate/client/src/lib.rs
  substrate/codec/src/slicable.rs
  substrate/primitives/src/authority_id.rs
  substrate/runtime/primitives/src/generic.rs
Labels: A8-looksgood

#270 Prevent account storage leakage
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/client/src/light/backend.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/src/lib.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/runtime/staking/src/account_db.rs
  substrate/runtime/staking/src/double_map.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/tests.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/proving_backend.rs
  substrate/state-machine/src/testing.rs
  substrate/state-machine/src/trie_backend.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#278 Bump wasmi to 0.3.0
  Cargo.lock
  polkadot/parachain/Cargo.toml
  substrate/executor/Cargo.toml
  substrate/executor/src/wasm_utils.rs
  substrate/primitives/Cargo.toml
  substrate/primitives/src/sandbox.rs
  substrate/runtime-sandbox/Cargo.toml
  substrate/runtime-sandbox/with_std.rs
Labels: A2-insubstantial

#276 Improve Runtime execution by caching runtime lookup
  Cargo.lock
  substrate/executor/Cargo.toml
  substrate/executor/src/lib.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/wasm_executor.rs
Labels: A8-looksgood

#282 Update versions, docs.
  demo/runtime/src/lib.rs
  polkadot/runtime/src/lib.rs
  substrate/runtime/version/src/lib.rs
Labels: A8-looksgood

#281 PoC-1 backwards compatibility
  substrate/executor/src/native_executor.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
Labels: A8-looksgood

#283 Cache the RuntimeVersion for code blocks, too
  substrate/client/src/call_executor.rs
  substrate/client/src/client.rs
  substrate/client/src/light/call_executor.rs
  substrate/executor/src/error.rs
  substrate/executor/src/lib.rs
  substrate/executor/src/native_executor.rs
Labels: A8-looksgood

#285 fix typo
  polkadot/consensus/src/shared_table/mod.rs
Labels: A2-insubstantial

#280 Collator node workflow
  Cargo.lock
  Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/cli/src/lib.rs
  polkadot/collator/Cargo.toml
  polkadot/collator/src/lib.rs
  polkadot/consensus/Cargo.toml
  polkadot/consensus/src/collation.rs
  polkadot/consensus/src/lib.rs
  polkadot/consensus/src/shared_table/mod.rs
  polkadot/network/src/consensus.rs
  polkadot/network/src/tests.rs
  polkadot/primitives/src/parachain.rs
  polkadot/service/src/lib.rs
  polkadot/src/main.rs
Labels: A8-looksgood, M4-core

#290 Update code to the latest nightly
  Cargo.lock
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-std/without_std.rs
  substrate/runtime/contract/Cargo.toml
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#291 PoC-1 backwards compatibility
  polkadot/network/src/lib.rs
  polkadot/network/src/tests.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
Labels: A8-looksgood

#293 PoC-2 tweaks
  Cargo.lock
  polkadot/cli/src/chain_spec.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/service/src/chain_spec.rs
Labels: A8-looksgood

#296 Fix for nightly 2018-07-10
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/parachain/test-chains/basic_add/src/lib.rs
  polkadot/parachain/test-chains/basic_add/src/wasm.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-io/src/lib.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime/system/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#287 Issue 212 - refactor Checkable trait to be more generic
  polkadot/runtime/src/utils.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/generic.rs
  substrate/runtime/primitives/src/testing.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/test-runtime/src/lib.rs
Labels: A8-looksgood

#299 Improve Wasm extern errors and increase heap
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/src/wasm_utils.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#295 Validator side of the collation protocol.
  polkadot/collator/src/lib.rs
  polkadot/consensus/src/collation.rs
  polkadot/network/src/collator_pool.rs
  polkadot/network/src/consensus.rs
  polkadot/network/src/lib.rs
  polkadot/network/src/tests.rs
  polkadot/primitives/src/parachain.rs
  substrate/network/src/protocol.rs
  substrate/network/src/specialization.rs
Labels: A8-looksgood, M4-core

#307 environmental! handles generics
  substrate/environmental/src/lib.rs
Labels: A0-pleasereview

#306 More timely block import notifications
  .gitignore
  Cargo.lock
  polkadot/cli/src/informant.rs
  substrate/client/Cargo.toml
  substrate/client/src/client.rs
  substrate/client/src/lib.rs
  substrate/telemetry/src/lib.rs
Labels: A8-looksgood

#313 Fixed spec serialization
  polkadot/service/src/chain_spec.rs
Labels: A8-looksgood

#311 Dual execution
  Cargo.lock
  demo/executor/Cargo.toml
  demo/executor/src/lib.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/service/src/components.rs
  polkadot/service/src/config.rs
  polkadot/service/src/lib.rs
  substrate/client/db/src/lib.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/call_executor.rs
  substrate/client/src/client.rs
  substrate/client/src/genesis.rs
  substrate/client/src/light/call_executor.rs
  substrate/client/src/light/mod.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/runtime/consensus/src/lib.rs
  substrate/state-machine/src/lib.rs
Labels: A0-pleasereview

#268 Switch from devp2p to libp2p
  Cargo.lock
  README.md
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
  substrate/network-libp2p/src/transport.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/Cargo.toml
  substrate/network/src/lib.rs
  substrate/network/src/service.rs
Labels: A0-pleasereview

#318 Avoid accounts destroyed in payments from being aux
  polkadot/service/src/chain_spec.rs
  substrate/runtime/staking/src/lib.rs
Labels: A8-looksgood

#316 Use --export-table from the latest LLD
  README.md
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  init.sh
  polkadot/parachain/test-chains/build.sh
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/build.sh
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#320 Disable peers only for 5 minutes
  substrate/network-libp2p/src/network_state.rs
Labels: A5-grumble

#322 Issue 279 - unique path for each chains db, network, keystore to prevent collisions
  polkadot/cli/src/lib.rs
  polkadot/service/res/poc-1.json
  polkadot/service/src/chain_spec.rs
  substrate/service/src/chain_spec.rs
Labels: A8-looksgood

#325 Use --export-table from the latest LLD [2]
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A2-insubstantial

#321 Ensure any call to disable peer has a reason
  Cargo.lock
  polkadot/network/src/lib.rs
  polkadot/network/src/tests.rs
  polkadot/runtime/src/parachains.rs
  substrate/executor/src/wasm_executor.rs
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/traits.rs
  substrate/network-libp2p/src/transport.rs
  substrate/network/src/io.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
  substrate/primitives/src/hexdisplay.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/primitives/Cargo.toml
  substrate/runtime/primitives/src/lib.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/system/src/lib.rs
  substrate/runtime/timestamp/src/lib.rs
Labels: A7-looksgoodtestsfail

#327 heap-size is a CLI arg, make it 512 by default [v0.2-devp2p]
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  substrate/client/src/genesis.rs
  substrate/client/src/light/call_executor.rs
  substrate/executor/src/native_executor.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
  substrate/test-client/src/client_ext.rs
  substrate/test-client/src/lib.rs
Labels: A8-backport

#336 hash random seed when using to choose round proposer
  polkadot/consensus/src/lib.rs
Labels: A0-pleasereview

#260 Fix light sync deadlock (blocks import queue)
  substrate/network/src/chain.rs
  substrate/network/src/error.rs
  substrate/network/src/import_queue.rs
  substrate/network/src/lib.rs
  substrate/network/src/message.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
Labels: A8-looksgood

#337 Better reporting in libp2p
  substrate/network-libp2p/src/service.rs
Labels: A8-looksgood, M4-core

#328 Adaptive heap size
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  polkadot/api/src/full.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  substrate/client/src/error.rs
  substrate/client/src/genesis.rs
  substrate/client/src/light/call_executor.rs
  substrate/executor/Cargo.toml
  substrate/executor/src/error.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/src/sandbox.rs
  substrate/executor/src/wasm_executor.rs
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
  substrate/state-machine/src/backend.rs
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
  substrate/state-machine/src/trie_backend.rs
  substrate/test-client/src/client_ext.rs
  substrate/test-client/src/lib.rs
Labels: A8-looksgood

#342 Fixed AsyncImportQueue drop deadlock
  substrate/network/src/import_queue.rs
  substrate/network/src/on_demand.rs
Labels: A4-awaitingci, A8-looksgood

#341 Remove old bootnodes
  polkadot/service/res/poc-1.json
Labels: A2-insubstantial

#343 More robust connections
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
Labels: A8-looksgood, M4-core

#348 Final tweaks for PoC-2 runtime upgrade
  README.md
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/cli/src/chain_spec.rs
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/res/krummelanke.json
  polkadot/service/src/chain_spec.rs
  substrate/executor/src/wasm_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime-io/with_std.rs
  substrate/runtime-io/without_std.rs
  substrate/runtime-support/src/storage/mod.rs
  substrate/service/src/config.rs
  substrate/test-runtime/wasm/Cargo.lock
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#352 Specialised polkadot service network()
  polkadot/service/src/lib.rs
Labels: A8-looksgood

#354 Fix install command in README
  README.md
Labels: A2-insubstantial

#353 Fix deadlock for too-small heap
  substrate/executor/src/wasm_executor.rs
Labels: A8-looksgood

#355 Download bodies when authority nodes are syncing
  substrate/network/src/sync.rs
Labels: A8-looksgood

#356 Use create instead of open for export blocks
  polkadot/cli/src/lib.rs
Labels: A2-insubstantial

#360 Explicit stop of import queue thread
  substrate/network/src/import_queue.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/sync.rs
Labels: A8-looksgood

#359 Gossip through all peers.
  polkadot/network/src/lib.rs
  substrate/network/src/consensus_gossip.rs
Labels: A6-mustntgrumble

#364 Fix the networking
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A6-mustntgrumble, M4-core

#365 Fix style in #364
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A2-insubstantial

#368 Fixed block import
  polkadot/cli/src/lib.rs
  substrate/codec/src/codec.rs
Labels: A8-looksgood

#351 Collator-side of collator protocol
  Cargo.lock
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  polkadot/collator/Cargo.toml
  polkadot/collator/src/lib.rs
  polkadot/network/src/consensus.rs
  polkadot/network/src/lib.rs
  polkadot/network/src/local_collations.rs
  polkadot/network/src/tests.rs
  polkadot/service/src/lib.rs
  substrate/service/src/components.rs
  substrate/service/src/config.rs
  substrate/service/src/lib.rs
Labels: A0-pleasereview

#372 Timeouts now repeat forever
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
Labels: A8-looksgood, M4-core

#367 Various small v0.2 improvements
  README.md
  polkadot/cli/src/lib.rs
  polkadot/transaction-pool/src/lib.rs
  substrate/primitives/src/hexdisplay.rs
  substrate/telemetry/src/lib.rs
Labels: A5-grumble

#379 Panic hook
  Cargo.lock
  Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/cli/src/lib.rs
  polkadot/cli/src/panic_hook.rs
Labels: A8-looksgood

#381 Use SSL to submit Telemetry
  polkadot/cli/src/lib.rs
Labels: A2-insubstantial, F8-enhancement

#374 Network improvements
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A0-pleasereview, M4-core

#382 Explicit disconnect on timeout
  substrate/network/src/protocol.rs
Labels: A0-pleasereview

#340 Add support for shell completion
  README.md
  polkadot/cli/Cargo.toml
  polkadot/cli/build.rs
Labels: A6-mustntgrumble

#384 More networking fixes
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/transport.rs
Labels: A8-looksgood, M4-core

#385 Register protocols at the same time as we start
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/src/service.rs
Labels: A7-looksgoodtestsfail, M4-core

#386 Allow bootnodes as IP:PORT, query Peer-id
  polkadot/cli/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
Labels: A8-looksgood

#388 Introduce support for yamux
  Cargo.lock
  substrate/network-libp2p/src/transport.rs
Labels: A8-looksgood, M4-core

#394 Refactor out disable/disconnect peer to make API more declarative
  polkadot/network/src/lib.rs
  polkadot/network/src/tests.rs
  substrate/network-libp2p/src/connection_filter.rs
  substrate/network-libp2p/src/custom_proto.rs
  substrate/network-libp2p/src/error.rs
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
  substrate/network-libp2p/src/traits.rs
  substrate/network-libp2p/src/transport.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/src/import_queue.rs
  substrate/network/src/io.rs
  substrate/network/src/lib.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
Labels: A6-mustntgrumble

#395 Add restrictions on node name length and content
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/lib.rs
Labels: A8-looksgood

#406 Fix export when starting from block 0
  polkadot/cli/src/lib.rs
Labels: A8-looksgood

#408 General multiplexing fixes
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/transport.rs
Labels: A2-insubstantial, M4-core

#396 Style fixes
  polkadot/network/src/lib.rs
  polkadot/network/src/tests.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/traits.rs
  substrate/network-libp2p/tests/tests.rs
  substrate/network/src/blocks.rs
  substrate/network/src/consensus_gossip.rs
  substrate/network/src/import_queue.rs
  substrate/network/src/io.rs
  substrate/network/src/lib.rs
  substrate/network/src/on_demand.rs
  substrate/network/src/protocol.rs
  substrate/network/src/service.rs
  substrate/network/src/specialization.rs
  substrate/network/src/sync.rs
  substrate/network/src/test/mod.rs
Labels: A8-looksgood

#410 Bump jsonrpc.
  Cargo.lock
Labels: A2-insubstantial, M6-rpcapi

#411 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: A2-insubstantial

#407 WIP: Asciidoc
  README.adoc
  doc/packages.adoc
  polkadot/api/README.adoc
  polkadot/cli/README.adoc
  polkadot/cli/doc/shell-completion.adoc
  polkadot/collator/README.adoc
  polkadot/consensus/README.adoc
  polkadot/executor/README.adoc
  polkadot/network/README.adoc
  polkadot/parachain/README.adoc
  polkadot/primitives/README.adoc
  polkadot/runtime/README.adoc
  polkadot/service/README.adoc
  polkadot/src/README.adoc
  polkadot/statement-table/README.adoc
  polkadot/transaction-pool/README.adoc
Labels: A8-looksgood

#409 Keep last finalized overlay in memory until DB commit
  substrate/state-db/src/lib.rs
  substrate/state-db/src/unfinalized.rs
Labels: A8-looksgood

#414 Add some logging if the timeouts stream ends
  substrate/network-libp2p/src/service.rs
Labels: A8-looksgood, M4-core

#393 Revert chain command
  polkadot/cli/src/cli.yml
  polkadot/cli/src/lib.rs
  substrate/client/db/src/lib.rs
  substrate/client/src/backend.rs
  substrate/client/src/client.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/light/backend.rs
  substrate/network/src/import_queue.rs
  substrate/service/src/config.rs
  substrate/state-db/src/lib.rs
  substrate/state-db/src/unfinalized.rs
Labels: A8-looksgood

#418 Subkey fix and refactor
  subkey/Cargo.toml
  subkey/README.adoc
  subkey/src/main.rs
Labels: A7-looksgoodtestsfail

#429 Better logging for public key mismatch
  substrate/network-libp2p/src/service.rs
Labels: A2-insubstantial, M4-core

#430 Prevent building invalid blocks
  Cargo.toml
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/cli/src/panic_hook.rs
  substrate/client/src/block_builder.rs
  substrate/client/src/client.rs
  substrate/client/src/error.rs
  substrate/executor/src/native_executor.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/executive/src/lib.rs
  substrate/state-machine/src/lib.rs
  substrate/test-runtime/src/system.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#435 5 random fixes (#1)
  substrate/cli/src/lib.rs
  substrate/runtime-io/without_std.rs
  substrate/state-machine/src/lib.rs
  substrate/test-runtime/src/system.rs
Labels: A8-looksgood

#431 Do not queue empty blocks set for import
  substrate/network/src/import_queue.rs
  substrate/network/src/protocol.rs
Labels: A2-insubstantial

#432 Fix memory leaks in libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
Labels: A2-insubstantial, M4-core

#391 Limit number of incoming connections
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/traits.rs
Labels: A8-looksgood

#405 Reset peers.json if the content is not loadable
  substrate/network-libp2p/src/network_state.rs
Labels: A8-looksgood, M4-core

#375 Add docker image
  .gitignore
  README.adoc
  docker/Dockerfile
  docker/build.sh
  docker/cleanup.sh
  docker/docker-compose.yml
  docker/readme-docker.adoc
  docker/version
Labels: A0-pleasereview

#433 Exit signal gets its own trait
  polkadot/cli/src/lib.rs
  polkadot/collator/src/lib.rs
  polkadot/src/main.rs
  substrate/cli/src/lib.rs
Labels: A8-looksgood

#436 Iterate over overlay to decide which keys to purge
  substrate/state-machine/src/ext.rs
  substrate/state-machine/src/lib.rs
Labels: A8-looksgood, M4-core

#440 Export ws port 9944 and add doc
  README.adoc
  docker/Dockerfile
Labels: A0-pleasereview

#427 Switch to the master branch of libp2p
  Cargo.lock
  substrate/network-libp2p/Cargo.toml
  substrate/network-libp2p/src/lib.rs
  substrate/network-libp2p/src/network_state.rs
  substrate/network-libp2p/src/service.rs
  substrate/network-libp2p/src/timeouts.rs
  substrate/network-libp2p/src/transport.rs
Labels: A8-looksgood, M4-core

#442 Update libp2p
  Cargo.lock
Labels: A2-insubstantial

#441 Fix the public key of bootnode 3
  polkadot/service/res/krummelanke.json
Labels: A2-insubstantial

#445 Update libp2p again
  Cargo.lock
Labels: A2-insubstantial

#251 DB-based blockchain data cache for light nodes
  substrate/bft/src/lib.rs
  substrate/client/db/src/cache.rs
  substrate/client/db/src/lib.rs
  substrate/client/db/src/light.rs
  substrate/client/db/src/utils.rs
  substrate/client/src/backend.rs
  substrate/client/src/blockchain.rs
  substrate/client/src/client.rs
  substrate/client/src/in_mem.rs
  substrate/client/src/light/backend.rs
  substrate/client/src/light/blockchain.rs
Labels: A0-pleasereview

#450 Version bump
  Cargo.lock
  Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/runtime/src/lib.rs
  polkadot/service/Cargo.toml
  substrate/cli/Cargo.toml
  substrate/service/Cargo.toml
  substrate/telemetry/Cargo.toml
Labels: A2-insubstantial

#345 Make contract a separate runtime module
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/src/lib.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/src/chain_spec.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/contract/Cargo.toml
  substrate/runtime/contract/src/account_db.rs
  substrate/runtime/contract/src/double_map.rs
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/gas.rs
  substrate/runtime/contract/src/genesis_config.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/contract/src/vm.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/staking/src/tests.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-looksgood

#454 Update README.adoc
  README.adoc
Labels: A2-insubstantial, A8-looksgood

#453 Fix session phase in early-exit
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/src/lib.rs
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/src/lib.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A0-pleasereview

#452 Fix up session phase backport
  Cargo.lock
  demo/cli/src/lib.rs
  demo/executor/src/lib.rs
  demo/runtime/src/lib.rs
  demo/runtime/wasm/Cargo.lock
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/src/lib.rs
  polkadot/runtime/wasm/Cargo.lock
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  polkadot/service/src/chain_spec.rs
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.compact.wasm
  substrate/executor/wasm/target/wasm32-unknown-unknown/release/runtime_test.wasm
  substrate/runtime/contract/Cargo.toml
  substrate/runtime/contract/src/account_db.rs
  substrate/runtime/contract/src/double_map.rs
  substrate/runtime/contract/src/exec.rs
  substrate/runtime/contract/src/gas.rs
  substrate/runtime/contract/src/genesis_config.rs
  substrate/runtime/contract/src/lib.rs
  substrate/runtime/contract/src/tests.rs
  substrate/runtime/contract/src/vm.rs
  substrate/runtime/council/src/lib.rs
  substrate/runtime/democracy/src/lib.rs
  substrate/runtime/executive/src/lib.rs
  substrate/runtime/primitives/src/traits.rs
  substrate/runtime/session/src/lib.rs
  substrate/runtime/staking/Cargo.toml
  substrate/runtime/staking/src/genesis_config.rs
  substrate/runtime/staking/src/lib.rs
  substrate/runtime/staking/src/mock.rs
  substrate/runtime/staking/src/tests.rs
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  substrate/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.wasm
Labels: A8-backport
