Repository paritytech/substrate, pull requests merged in 2019-12, with the labels that each got.

#4256 Economic fixes for democracy module
  bin/node/runtime/src/lib.rs
  client/finality-grandpa/src/communication/gossip.rs
  frame/democracy/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4250 Fix reimporting transactions from retracted blocks.
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/maintainer.rs
Labels: A0-pleasereview, M4-core

#4260 Fix return type in function documentation.
  client/peerset/src/peersstate.rs
Labels: A2-insubstantial

#4259 Fix warning, use unused result.
  client/finality-grandpa/src/environment.rs
Labels: A0-pleasereview, A2-insubstantial

#4257 Introduce `VestingCurrency` trait
  frame/balances/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview

#4263 Fix sc-tracing-* -> sc-transaction-
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node/cli/Cargo.toml
  client/basic-authorship/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/benches/basics.rs
  utils/frame/rpc/system/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4264 Add `swap` and `decode_len` to `DoubleMap` finishing #3749
  bin/node/runtime/src/lib.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/decl_storage.rs
Labels: A0-pleasereview

#4262 Improve error message on `can_author_with` failure
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/common/src/lib.rs
  primitives/sr-version/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4266 Fix phragmen elections
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview

#4271 interruptible test and build jobs
  .gitlab-ci.yml
Labels: M1-ci

#4273 Fix sp-session typo
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  primitives/session/Cargo.toml
  test/utils/runtime/Cargo.toml
Labels: A2-insubstantial

#4275 docs/CODEOWNERS: Add mxinden to authority discovery modules
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial

#4276 Another fix for elections-phragmen
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview

#4278 Enumeratable dispatches using unhashed index in key
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  primitives/sr-version/src/lib.rs
Labels: A2-insubstantial

#4277 Reputation changes require reason
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/network/src/legacy_proto/behaviour.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/consensus_gossip.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/src/test/mod.rs
  client/peerset/src/lib.rs
  client/peerset/tests/fuzz.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#4285 client: Introduce --sentry-nodes flag
  .maintain/sentry-node/docker-compose.yml
  bin/node/cli/src/service.rs
  client/authority-discovery/src/lib.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/network/src/config.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview

#4261 pallet-evm: weight calculation for call/create based on gas provided
  frame/evm/src/lib.rs
Labels: A0-pleasereview

#4286 Typo granpda -> grandpa
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node/cli/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/service/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  primitives/finality-grandpa/Cargo.toml
Labels: A2-insubstantial

#4289 Update exit-future and make sc-cli compile on wasm
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#4199 Use timestamp deltas in grafana-data-store
  client/grafana-data-source/src/database.rs
  client/grafana-data-source/src/lib.rs
  client/grafana-data-source/src/server.rs
  client/grafana-data-source/src/util.rs
  client/grafana-data-source/test/src/main.rs
  client/service/src/builder.rs
  client/tracing/src/lib.rs
Labels: A3-needsresolving, A7-looksgoodtestsfail

#4292 Revalidate some transactions on every block import.
  Cargo.lock
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/maintainer.rs
Labels: A0-pleasereview, M4-core

#4293 Add linear back-off for aura slot workers
  client/consensus/aura/src/lib.rs
Labels: A8-looksgood

#4175 Expose some of session module's storage as public, as well as the set_keys transaction
  frame/session/src/lib.rs
  frame/support/src/traits.rs
Labels: A5-grumble

#4291 Minor fix toml files
  bin/node/cli/Cargo.toml
  client/api/Cargo.toml
  client/transaction-pool/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/staking/reward-curve/Cargo.toml
  primitives/runtime-interface/proc-macro/Cargo.toml
  primitives/sr-api/proc-macro/Cargo.toml
Labels: A2-insubstantial, A4-awaitingci

#4290 Use balance capped to u64 for transaction payment RPC.
  frame/transaction-payment/rpc/runtime-api/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#4294 Tone down warnings when resubmitting to the pool.
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/validated_pool.rs
Labels: A0-pleasereview, M4-core

#4297 client/authority-discovery: Increase margins for interval test
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview

#4296 Move legacy_proto to protocol
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/legacy_proto.rs
  client/network/src/protocol/legacy_proto/behaviour.rs
  client/network/src/protocol/legacy_proto/handler.rs
  client/network/src/protocol/legacy_proto/tests.rs
  client/network/src/protocol/legacy_proto/upgrade.rs
Labels: A2-insubstantial

#4302 client/authority-discovery: Limit the amount of sentries per authority
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview

#4301 Change order of events emitted from transfer.
  frame/balances/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4300 Allow members of groups to change their key
  frame/membership/src/lib.rs
Labels: A0-pleasereview

#4304 Fix Contracts RPC output format.
  Cargo.lock
  frame/contracts/rpc/Cargo.toml
  frame/contracts/rpc/runtime-api/Cargo.toml
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/contracts/rpc/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#4306 Fix order of operation in membership
  frame/membership/src/lib.rs
Labels: A0-pleasereview

#4314 client/authority-discovery: Warn when specifying too many sentry nodes
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview

#4320 Merge txpool-runtime-api with txpool-api
  Cargo.lock
  Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/rpc/src/author/mod.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/error.rs
  client/transaction-pool/src/maintainer.rs
  primitives/transaction-pool/Cargo.toml
  primitives/transaction-pool/runtime-api/Cargo.toml
  primitives/transaction-pool/src/error.rs
  primitives/transaction-pool/src/lib.rs
  primitives/transaction-pool/src/pool.rs
  primitives/transaction-pool/src/runtime_api.rs
  test/utils/runtime/Cargo.toml
  test/utils/runtime/src/lib.rs
Labels: A2-insubstantial, M4-core

#4319 decl_storage: Allow storage value builder to put no value
  frame/support/procedural/src/storage/genesis_config/builder_def.rs
  frame/support/test/tests/decl_storage.rs
Labels: A0-pleasereview

#4317 Fix `check_polkadot` CI check
  .gitlab-ci.yml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, A2-insubstantial

#3757 Use header metadata in state full and refactor.
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/tests.rs
Labels: A0-pleasereview, M6-rpcapi

#4329 Remove slog-async Github
  Cargo.lock
  client/telemetry/Cargo.toml
  client/telemetry/src/async_record.rs
  client/telemetry/src/lib.rs
Labels: A0-pleasereview

#4335 sp-transaction-pool-api: make default std, remove unused sp-core dependency
  Cargo.lock
  primitives/transaction-pool/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4298 Limit number of uncles that can be provided.
  Cargo.lock
  frame/authorship/src/lib.rs
  primitives/authorship/Cargo.toml
  primitives/authorship/src/lib.rs
Labels: A0-pleasereview

#4330 Don't assume a fixed length for `endowed_accounts`
  bin/node/cli/src/chain_spec.rs
Labels: A0-pleasereview, A2-insubstantial

#4336 Fix panic in telemetry
  client/telemetry/src/async_record.rs
Labels: A2-insubstantial

#4185 Introduce prefixed storage with enumeration
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/src/light/backend.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/lib.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/instance.rs
  primitives/core/storage/src/lib.rs
  primitives/externalities/src/lib.rs
  primitives/sr-io/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  test/utils/runtime/client/src/lib.rs
  test/utils/runtime/src/genesismap.rs
Labels: A6-seemsok

#4337 Fix compilation of `sp-authorship`
  primitives/authorship/Cargo.toml
  primitives/authorship/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4321 Remove depenendcy on sc-consensus-slots
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, M4-core

#4343 Remove cycling dependency from `sp-api`
  Cargo.lock
  primitives/sr-api/Cargo.toml
  primitives/sr-api/proc-macro/Cargo.toml
  primitives/sr-api/proc-macro/src/lib.rs
  primitives/sr-api/proc-macro/src/utils.rs
  primitives/sr-api/src/lib.rs
Labels: A2-insubstantial

#4332 Fix warnings when compiling runtime.
  bin/node-template/runtime/src/template.rs
  client/tracing/src/lib.rs
  frame/assets/src/lib.rs
  frame/authorship/src/lib.rs
  frame/democracy/src/lib.rs
  frame/evm/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/im-online/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/src/dispatch.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/value.rs
  frame/support/test/tests/reserved_keyword/on_initialize.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  primitives/consensus/aura/src/inherents.rs
  primitives/core/src/crypto.rs
  primitives/sr-io/src/lib.rs
Labels: A8-looksgood, M4-core

#4348 remove unnecessary client-db dependency
  Cargo.lock
  client/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4351 remove unnecessary block-builder dependency
  Cargo.lock
  client/api/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4347 Break appcrypto dep cycle
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/keystore/Cargo.toml
  client/service/Cargo.toml
  docs/Upgrade.md
  frame/aura/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/im-online/Cargo.toml
  frame/session/Cargo.toml
  primitives/application-crypto/Cargo.toml
  primitives/application-crypto/src/ed25519.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/sr25519.rs
  primitives/application-crypto/test/Cargo.toml
  primitives/application-crypto/test/src/ed25519.rs
  primitives/application-crypto/test/src/lib.rs
  primitives/application-crypto/test/src/sr25519.rs
  primitives/authority-discovery/Cargo.toml
  primitives/consensus/aura/Cargo.toml
  primitives/consensus/babe/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/test-primitives/Cargo.toml
  test/utils/runtime/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#4350 Fix typos in identity pallet docs
  frame/identity/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, F5-documentation 📄

#4353 Fix cycle dependency in `sp-runtime-interface`
  Cargo.lock
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/proc-macro/Cargo.toml
  primitives/runtime-interface/proc-macro/src/lib.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/src/pass_by.rs
  primitives/runtime-interface/tests/ui.rs
  primitives/runtime-interface/tests/ui/no_generic_parameters.rs
  primitives/runtime-interface/tests/ui/no_generic_parameters.stderr
  primitives/runtime-interface/tests/ui/no_method_implementation.rs
  primitives/runtime-interface/tests/ui/no_method_implementation.stderr
  primitives/runtime-interface/tests/ui/pass_by_enum_with_struct.rs
  primitives/runtime-interface/tests/ui/pass_by_enum_with_struct.stderr
  primitives/runtime-interface/tests/ui/pass_by_enum_with_value_variant.rs
  primitives/runtime-interface/tests/ui/pass_by_enum_with_value_variant.stderr
  primitives/runtime-interface/tests/ui/pass_by_inner_with_two_fields.rs
  primitives/runtime-interface/tests/ui/pass_by_inner_with_two_fields.stderr
  primitives/runtime-interface/tests/ui/take_self_by_value.rs
  primitives/runtime-interface/tests/ui/take_self_by_value.stderr
Labels: A3-inprogress

#4354 Fix a bunch of low work dependency cycles
  Cargo.lock
  Cargo.toml
  client/api/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/tests.rs
  client/executor/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/tests.rs
  client/network/Cargo.toml
  client/network/src/lib.rs
  client/network/src/protocol/legacy_proto/tests.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/test/Cargo.toml
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue/buffered_link.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/test-primitives/src/lib.rs
Labels: A0-pleasereview

#4358 Fix folder names in primitives
  Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node/runtime/Cargo.toml
  client/Cargo.toml
  client/api/Cargo.toml
  client/block-builder/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/pow/Cargo.toml
  client/executor/Cargo.toml
  client/executor/runtime-test/Cargo.toml
  client/network/Cargo.toml
  client/rpc/Cargo.toml
  client/rpc/api/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/babe/Cargo.toml
  frame/contracts/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/im-online/Cargo.toml
  frame/offences/Cargo.toml
  frame/session/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/system/Cargo.toml
  primitives/api/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/benches/bench.rs
  primitives/arithmetic/fuzzer/.gitignore
  primitives/arithmetic/fuzzer/Cargo.lock
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/biguint.rs
  primitives/arithmetic/fuzzer/src/rational128.rs
  primitives/arithmetic/src/biguint.rs
  primitives/arithmetic/src/fixed64.rs
  primitives/arithmetic/src/helpers_128bit.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/arithmetic/src/rational128.rs
  primitives/arithmetic/src/traits.rs
  primitives/block-builder/Cargo.toml
  primitives/block-builder/src/lib.rs
  primitives/blockchain/Cargo.toml
  primitives/consensus/common/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/sandbox/Cargo.toml
  primitives/sandbox/src/lib.rs
  primitives/sandbox/with_std.rs
  primitives/sandbox/without_std.rs
  primitives/staking/Cargo.toml
  primitives/staking/src/lib.rs
  primitives/staking/src/offence.rs
  primitives/version/Cargo.toml
  primitives/version/src/lib.rs
  test/utils/runtime/Cargo.toml
  test/utils/transaction-factory/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4355 Fix token economics url.
  frame/staking/src/lib.rs
Labels: A2-insubstantial

#4356 Improve is_member and is_runner.
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4345 Allow referendums to begin out of order
  frame/democracy/src/lib.rs
Labels: A0-pleasereview

#4366 `decl_error!` document that the error needs to be registered
  frame/support/src/error.rs
Labels: A0-pleasereview, A2-insubstantial, F5-documentation 📄

#4375 Update rustdocs landing page
  .gitlab-ci.yml
Labels: A2-insubstantial

#4284 Extract consensus_gossip.rs and put it in its own crate
  Cargo.lock
  Cargo.toml
  bin/node-template/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/behaviour.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/service.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4381 Adding in-between variants of crate names to rename script
  .maintain/rename-crates-for-2.0.sh
Labels: A0-pleasereview, A2-insubstantial

#4162 Fix key collision for child trie
  bin/node/executor/src/lib.rs
  bin/node/testing/src/client.rs
  client/api/src/backend.rs
  client/api/src/light.rs
  client/chain-spec/src/chain_spec.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/executor/src/deprecated_host_interface.rs
  client/executor/src/integration_tests/mod.rs
  client/finality-grandpa/src/tests.rs
  client/network/src/chain.rs
  client/network/src/protocol.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/message.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/state/tests.rs
  client/src/cht.rs
  client/src/client.rs
  client/src/genesis.rs
  client/src/in_mem.rs
  client/src/lib.rs
  client/src/light/backend.rs
  client/src/light/fetcher.rs
  frame/contracts/src/account_db.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/support/procedural/src/storage/genesis_config/mod.rs
  frame/support/src/storage/child.rs
  frame/support/test/tests/instance.rs
  frame/system/src/lib.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/storage/src/lib.rs
  primitives/trie/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A8-looksgood, B2-breaksapi

#4397 babe: exponential backoff on missed blocks
  client/consensus/babe/src/lib.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview

#4396 Simplify adding new Ss58AddressFormat variant and add KulupuAccountDirect
  bin/utils/subkey/src/main.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview

#4399 Remove proposal when it is refused
  frame/collective/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4401 Identity module enhancements
  frame/identity/src/lib.rs
Labels: A0-pleasereview

#4369 Make sudo use `decl_error!`
  frame/sudo/src/lib.rs
Labels: A8-looksgood

#4388 Impl iter_prefix on doublemap
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview

#4370 Use decl_error in the treasury module
  client/transaction-pool/graph/src/error.rs
  frame/treasury/src/lib.rs
Labels: A5-grumble

#4387 Use `decl_error!` in Staking Pallet
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#4408 Fix naming of utility crate (it's a legit pallet)
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/utility/Cargo.toml
Labels: A2-insubstantial

#4377 Recover light client integration tests
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  client/service/test/src/lib.rs
Labels: A8-looksgood

#4412 Fix frame_system renaming in contruct_runtime
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/support/src/event.rs
Labels: A0-pleasereview

#4376 [client cli] generic blocknumber
  client/cli/src/lib.rs
  client/cli/src/params.rs
  frame/system/src/lib.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview

#4418 docs: fix link to babe
  client/consensus/babe/src/lib.rs
Labels: A2-insubstantial

#4389 Update Balances Pallet events to help block explorers
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
Labels: A8-looksgood

#4373 Move Bridge Pallet into FRAME
  Cargo.lock
  Cargo.toml
  frame/bridge/Cargo.toml
  frame/bridge/src/lib.rs
  frame/bridge/src/storage_proof.rs
  srml/bridge/Cargo.toml
Labels: A0-pleasereview

#4425 Minor typos in traits docs
  frame/system/src/offchain.rs
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, F5-documentation 📄

#4429 Remove incorrect assumption that runners-up were sorted by account
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, P2-asap

#4428 Fix the subkey error message
  bin/utils/subkey/src/main.rs
  client/consensus/uncles/src/lib.rs
Labels: A2-insubstantial

#4427 More `decl_error!` migrations
  frame/assets/src/lib.rs
  frame/collective/src/lib.rs
  frame/democracy/src/lib.rs
  frame/evm/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/grandpa/src/lib.rs
Labels: A0-pleasereview

#4424 pallet-evm: default implementation for FeeCalculator and ConvertAccountId and separate gas price
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B3-breaksconsensus

#4435 Add dyn for `slog::SerdeValue` in telemetry
  client/telemetry/src/async_record.rs
Labels: A2-insubstantial

#4423 RPCs for reserved peers
  client/network/src/service.rs
  client/rpc-api/src/system/error.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A8-looksgood

#4439 client: Do not set fork sync request via network-gossip
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
Labels: A0-pleasereview

#4443 grandpa: log everything under afg target
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/light_import.rs
Labels: A0-pleasereview, A2-insubstantial

#4440 grandpa: fix slow gossip test
  client/finality-grandpa/src/communication/tests.rs
Labels: A0-pleasereview, A2-insubstantial

#4446 Document TransactionStatus and fix termination conditions.
  client/rpc-api/src/author/mod.rs
  client/rpc-api/src/system/mod.rs
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/watcher.rs
  primitives/transaction-pool/src/pool.rs
Labels: A0-pleasereview, M6-rpcapi

#4451 Few extra tests for phragmen
  primitives/phragmen/src/tests.rs
Labels: A2-insubstantial

#4441 Update grafana-data-source to tokio 0.2
  Cargo.lock
  utils/grafana-data-source/Cargo.toml
  utils/grafana-data-source/src/database.rs
  utils/grafana-data-source/src/networking.rs
  utils/grafana-data-source/src/server.rs
Labels: A8-looksgood

#4421 Fix Fees in Substrate
  bin/node/executor/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-looksgood

#4459 Add new event for registering deposits.
  frame/balances/src/lib.rs
Labels: A2-insubstantial

#4448 Warn about using --rpc-external and --ws-external options
  client/cli/src/lib.rs
  client/cli/src/params.rs
Labels: A0-pleasereview

#4461 babe: remove unused slot_duration variable
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4405 Update Balances Pallet for `decl_error!`
  frame/balances/src/lib.rs
  frame/balances/src/mock.rs
  frame/balances/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#4465 Subkey add support for interactive password
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
  client/cli/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4379 Use multiple threads in integration tests
  .gitlab-ci.yml
Labels: A1-onice, A2-insubstantial

#4469 Fix warnings and make CI working again
  Cargo.lock
  client/authority-discovery/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/src/light/backend.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/test/tests/decl_storage.rs
  primitives/runtime-interface/test/src/lib.rs
  primitives/runtime/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#4466 Shared params in CLI API
  bin/node/cli/src/cli.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/cli/src/traits.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A7-looksgoodtestsfail

#4463 Migrate membership, nicks, scored-pool and session to decl_error
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/scored-pool/src/tests.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A7-looksgoodtestsfail

#4472 Add `Clone` bound to the `Origin`.
  frame/system/src/lib.rs
Labels: A0-pleasereview, M4-core

#4468 Add ProposalRejected event to Treasury
  frame/treasury/src/lib.rs
Labels: A2-insubstantial

#4471 Rename ChainSpec field
  client/chain-spec/src/chain_spec.rs
Labels: A5-grumble, M4-core

#4473 Migrate generic-asset, identity and im-online to decl_error
  frame/balances/src/lib.rs
  frame/democracy/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/generic-asset/src/tests.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/tests.rs
Labels: A0-pleasereview

#4470 Clean up definition for custom ss58 address formats
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview

#4462 Extend Utility pallet with multisig and pseudonyms
  bin/node/runtime/src/lib.rs
  frame/assets/src/lib.rs
  frame/metadata/src/lib.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/src/hash.rs
  frame/support/src/lib.rs
  frame/utility/Cargo.toml
  frame/utility/src/lib.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview

#4476 Twitter field for IdentityInfo (in a back-compat way)
  frame/identity/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview

#4486 Fix warnings in grafana module
  utils/grafana-data-source/src/lib.rs
Labels: A2-insubstantial

#4485 Change log level for DhtEvent::ValueNotFound from warn to debug
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4481 ci: increase git cloning depth to 100
  .gitlab-ci.yml
  .maintain/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#4479 Migrate election-phragmen, election contracts and authorship to decl_error
  frame/authorship/src/lib.rs
  frame/contracts/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/elections/src/tests.rs
  frame/generic-asset/src/lib.rs
Labels: A0-pleasereview

#4488 Fix replace_previous of Ready Transaction Queue.
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/ready.rs
Labels: A0-pleasereview, M4-core

#4489 Extract execution engines definitions into their own crates
  Cargo.lock
  Cargo.toml
  client/executor/Cargo.toml
  client/executor/common/Cargo.toml
  client/executor/common/src/allocator.rs
  client/executor/common/src/error.rs
  client/executor/common/src/lib.rs
  client/executor/common/src/sandbox.rs
  client/executor/common/src/wasm_runtime.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/src/wasm_utils.rs
  client/executor/wasmi/Cargo.toml
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/function_executor.rs
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/trampoline.rs
  client/executor/wasmtime/src/util.rs
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/src/pass_by.rs
  primitives/runtime-interface/src/util.rs
Labels: A0-pleasereview

#4494 Remove unnecessary unsafe.
  primitives/runtime-interface/src/impls.rs
Labels: A0-pleasereview

#4436 Use `sc_network::NetworkStateInfo` instead of implementing redundant traits
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
  client/finality-grandpa/src/communication/tests.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/service/test/src/lib.rs
Labels: A8-looksgood

#4020 Check aura slot numbers are strictly increasing
  bin/node-template/src/service.rs
  client/consensus/aura/src/lib.rs
Labels: A5-grumble, M4-core

#4503 Support loading the URI from a file in subkey
  bin/utils/subkey/src/main.rs
Labels: A0-pleasereview, A2-insubstantial

#4504 Improve subkey error reporting
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
  bin/utils/subkey/src/vanity.rs
Labels: A0-pleasereview

#4491 less dupes, cleanup
  .gitlab-ci.yml
Labels: M1-ci

#4509 Fix cli for structopt 0.3.7 and pin to that version
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/utils/chain-spec-builder/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/cli/src/traits.rs
  frame/indices/Cargo.toml
  frame/indices/src/mock.rs
Labels: A0-pleasereview

#4510 Make wasm-builder remove invalid members
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#4512 Increase metadata version to 10
  frame/metadata/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4513 Update libsecp256k1
  Cargo.lock
  client/executor/Cargo.toml
  primitives/io/Cargo.toml
Labels: A2-insubstantial

#4502 Make `MultiSigner` use compressed ECDSA public key
  primitives/core/Cargo.toml
  primitives/core/src/ecdsa.rs
  primitives/core/src/hexdisplay.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview
