Repository paritytech/substrate, pull requests merged in 2019-05, with the labels that each got.

#2437 Add reason for closing and fix multiple substreams
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview

#2424 Try run check-web-wasm for PRs
  .gitlab-ci.yml
Labels: A2-insubstantial

#2442 Macro spell fixes
  srml/support/src/event.rs
  srml/support/src/runtime.rs
Labels: A4-gotissues

#2444 Add BtreeSet with sr-std.
  core/sr-std/with_std.rs
Labels: A4-gotissues

#2421 no_global_allocator feature
  core/sr-io/Cargo.toml
  core/sr-io/without_std.rs
  core/sr-std/Cargo.toml
  core/sr-std/without_std.rs
Labels: A4-gotissues

#2270 BABE signing and verification
  Cargo.lock
  core/consensus/aura/primitives/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/primitives/Cargo.toml
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/slots/src/lib.rs
  core/consensus/slots/src/slots.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  core/inherents/src/lib.rs
  core/network/Cargo.toml
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/primitives/src/crypto.rs
  core/rpc/src/chain/error.rs
  core/rpc/src/state/tests.rs
  core/sr-io/Cargo.toml
  core/sr-primitives/src/testing.rs
  core/sr-std/Cargo.toml
  core/test-client/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/build.sh
  core/transaction-pool/graph/Cargo.toml
  node/runtime/src/lib.rs
  scripts/build.sh
  srml/babe/Cargo.toml
  srml/babe/src/lib.rs
  srml/consensus/src/lib.rs
Labels: A6-mustntgrumble, B1-releasenotes, B2-breaksapi

#2450 Change terminology used in srml-contract docs
  srml/contract/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues, M3-docs

#2453 Update CI
  .gitlab-ci.yml
Labels: M1-ci

#2438 Simplify the code of connection_keep_alive
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-looksgood

#2439 Drop connections when the handler gets disabled
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/tests/test.rs
Labels: A0-pleasereview

#2458 Use latest version of parity-codec to fix release script
  node-template/runtime/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#2460 tokio -> tokio-timer in consensus
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/consensus/common/src/error.rs
Labels: A2-insubstantial

#2468 Fix grandpa issue for InvalidViewChanges
  core/network/src/consensus_gossip.rs
Labels: A0-pleasereview

#2454 Add reputation system to network crate
  core/consensus/common/src/import_queue.rs
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/lib.rs
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#2467 Disable mDNS when passing --dev
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview

#2462 Remove NetworkService::report_handle
  core/network/src/service.rs
Labels: A2-insubstantial

#2461 Default rent allowance to max_value
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, M8-contracts

#2459 Remove the dependency on heapsize
  Cargo.lock
  core/client/Cargo.toml
  core/client/src/cht.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/primitives/Cargo.toml
  core/primitives/src/hash.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/backend.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
Labels: A0-pleasereview

#2451 optimize double map first key hash
  node/runtime/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/test/tests/final_keys.rs
Labels: B2-breaksapi

#2473 Show more information when too many addresses are reported
  core/network-libp2p/src/behaviour.rs
Labels: A2-insubstantial

#2476 Move construct_simple_protocol! to appropriate module
  core/network/src/protocol.rs
  core/network/src/specialization.rs
Labels: A2-insubstantial

#2483 Add some crate-level documentation to network-libp2p
  core/network-libp2p/src/lib.rs
Labels: A0-pleasereview, F5-documentation 📄

#2480 backport fix doublemapkey
  node/runtime/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/hashable.rs
  srml/support/test/tests/final_keys.rs
Labels: A0-pleasereview, B2-breaksapi

#2472 Quick spell check to readme
  README.adoc
Labels: A2-insubstantial, F5-documentation 📄

#2456 Clean up random seed to make a bit more flexible
  core/executor/wasm/src/lib.rs
  core/finality-grandpa/primitives/src/lib.rs
  core/primitives/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-sandbox/src/lib.rs
  core/sr-std/src/lib.rs
  core/trie/src/lib.rs
  node-template/runtime/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
  srml/support/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2487 Move hashing benches to Criterion.
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/benches/benches.rs
Labels: A0-pleasereview

#2486 v1.0 networking backports
  Cargo.lock
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/consensus/common/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/src/consensus_gossip.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/peerset/Cargo.toml
  core/service/src/lib.rs
  core/service/test/src/lib.rs
Labels: A8-backport, B2-breaksapi

#2489 Fix std/core crates
  core/sr-std/with_std.rs
  core/sr-std/without_std.rs
Labels: A2-insubstantial

#2484 added ci from master
  .gitlab-ci.yml
  scripts/build.sh
Labels: M1-ci

#2490 actually update deduct_block when paying rent
  node/runtime/src/lib.rs
  srml/contract/src/rent.rs
  srml/contract/src/tests.rs
Labels: A7-looksgoodtestsfail

#2495 ci: publish v1.0 branch to latest-v1.0 tags
  .gitlab-ci.yml
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#2499 Fix light connection issues
  core/client/src/light/call_executor.rs
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
Labels: A0-pleasereview, M4-core

#2506 Use saturating_pow for max digest interval
  core/primitives/src/changes_trie.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, M4-core

#2505 Test node template
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#2205 Remove As trait bound from Currency::Balance
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/traits.rs
Labels: A4-gotissues, B2-breaksapi

#2513 Silence the deprecated warning in generated code
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
Labels: A4-gotissues

#2415 Replace ring with ed25519-dalek in primitives
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/ed25519.rs
Labels: A0-pleasereview

#2521 Fix chain spec builder
  Cargo.lock
  Cargo.toml
  test-utils/chain-spec-builder/Cargo.lock
  test-utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#2524 Make more crates compile for WASM browser
  .gitlab-ci.yml
  Cargo.lock
Labels: A2-insubstantial

#2520 Add some benchmarks for ed25519 in substrate_primitives
  core/primitives/benches/benches.rs
Labels: A8-looksgood

#2498 Imply forced authoring on --dev
  core/cli/src/lib.rs
Labels: A0-pleasereview

#2510 Add a simple PR template
  PULL_REQUEST_TEMPLATE.md
Labels: A0-pleasereview, M3-docs

#2406 Reformat Validator Election
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A8-looksgood

#2531 core: use current_thread tokio runtime to poll network to proto channel
  core/network/src/test/mod.rs
Labels: A0-pleasereview, A2-insubstantial

#2240 Allow for customisation of chain selection systems
  core/client/src/client.rs
  core/client/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/error.rs
  core/consensus/common/src/lib.rs
  core/consensus/common/src/select_chain.rs
  core/consensus/rhd/src/service.rs
  core/consensus/slots/src/lib.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/service_integration.rs
  core/finality-grandpa/src/tests.rs
  core/service/src/chain_ops.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-api-macros/tests/runtime_calls.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
Labels: A3-needsresolving, A6-mustntgrumble, B2-breaksapi

#2440 Rewrite the PSM
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/peerset/src/lib.rs
  core/peerset/src/peersstate.rs
  core/peerset/src/slots.rs
Labels: A0-pleasereview

#2463 Allow modules to validate transaction, second attempt
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/support/src/inherent.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/origin.rs
  srml/support/src/runtime.rs
  srml/support/src/unsigned.rs
  srml/support/test/src/lib.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/instance.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2533 Fix deadlock in tests that are using with_gossip
  core/finality-grandpa/src/communication/gossip.rs
  core/network/src/protocol.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, M4-core

#2530 Don't acquire the lock unless, and only hold it for as long as, necessary
  core/finality-grandpa/src/communication/gossip.rs
Labels: A0-pleasereview

#2528 Backport: Silence the deprecated warning in generated code
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, A4-gotissues

#2523 add brief doc to some macro
  srml/support/src/lib.rs
Labels: A0-pleasereview, M3-docs

#2512 Create AuthoritiesChange digest item in correct block
  core/sr-primitives/src/traits.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, B3-breaksconsensus, M4-core

#2433 Child trie storage proof
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/fetcher.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
  core/test-client/src/lib.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#2482 Revert from alpine to phusion and include wasm build
  .dockerignore
  Dockerfile
Labels: A0-pleasereview

#2540 Fix #2535
  core/peerset/src/lib.rs
Labels: A0-pleasereview

#2497 Isolate the code of ChainSync and turn it into a state machine
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview, F6-refactor 🧹

#2537 Send GRANDPA messages without holding validator lock
  core/finality-grandpa/src/communication/gossip.rs
Labels: A8-looksgood, M4-core

#2546 Reserved peers don't occupy slots
  core/peerset/src/peersstate.rs
Labels: A0-pleasereview

#1669 Light GRANDPA import handler
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/light.rs
  core/client/src/blockchain.rs
  core/client/src/error.rs
  core/client/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/consensus_changes.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/service_integration.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/chain.rs
  core/network/src/config.rs
  core/network/src/extra_requests.rs
  core/network/src/lib.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#2545 Language adjustment: Referendums -> Referenda
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
Labels: A8-looksgood, B0-patchthis, B1-releasenotes, B2-breaksapi

#2552 contruct_runtime doc
  srml/support/src/runtime.rs
Labels: A0-pleasereview, M3-docs

#2538 Tag for wasm check job
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#2522 check line-width of only newly added lines
  .gitlab-ci.yml
  scripts/gitlab/check_line_width.sh
Labels: A0-pleasereview, A4-gotissues, M1-ci

#2561 Remove the NetworkChan from the OnDemandService
  core/network/src/on_demand.rs
  core/network/src/service.rs
  core/service/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2525 Make the behaviour in libp2p generic
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
Labels: A8-looksgood

#2565 Introduce the `Get` trait and type_parameter.
  srml/support/src/lib.rs
  srml/support/src/traits.rs
Labels: A2-insubstantial, A4-gotissues

#2550 Split SyncContext from protocol Context
  core/network/src/extra_requests.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
Labels: A0-pleasereview, B2-breaksapi

#2549 Add possibility to sign calls via cli
  subkey/README.adoc
  subkey/src/cli.yml
  subkey/src/main.rs
Labels: A0-pleasereview

#2575 Prevent divide by zero panic with checked_div
  core/cli/src/informant.rs
Labels: A0-pleasereview, M4-core

#2548 Fix over/under flow risk in OnDilution
  node/runtime/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview

#2573 Move extra_requests.rs as a submodule of sync
  core/network/src/lib.rs
  core/network/src/sync.rs
  core/network/src/sync/extra_requests.rs
Labels: A2-insubstantial

#2563 Pass topics along with events
  node/runtime/src/lib.rs
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A0-pleasereview, B2-breaksapi

#2526 Introduce Flaming Fir testnet
  README.adoc
  node/cli/res/emberic-elm.json
  node/cli/res/flaming-fir.json
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview

#2574 Fix light client startup (build_select_chain returns Result<Option>)
  core/service/src/components.rs
  core/service/src/error.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#2576 Increase tolerance for bandwidth usage in test
  core/network-libp2p/tests/test.rs
Labels: A2-insubstantial

#2039 Do not try to synchronize from light client
  core/network/src/config.rs
  core/network/src/consensus_gossip.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, M4-core

#2560 Move ProtocolMsg to service.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#2578 Add WebSocket addresses for bootnodes
  node/cli/res/flaming-fir.json
Labels: A2-insubstantial

#2470 Randomly fuzz the PSM
  Cargo.lock
  core/peerset/Cargo.toml
  core/peerset/src/lib.rs
  core/peerset/tests/fuzz.rs
Labels: A8-looksgood

#2582 fix(remove redundant import)
  core/network/src/sync/extra_requests.rs
Labels: A2-insubstantial

#2583 Default image to build wasm
  .gitlab-ci.yml
Labels: M1-ci

#2585 Generate correct serde bound for GenesisConfig
  srml/support/procedural/src/storage/transformation.rs
  srml/support/test/tests/final_keys.rs
Labels: A0-pleasereview, A4-gotissues

#2492 Init store for slots-headers
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/slots/src/aux_schema.rs
  core/consensus/slots/src/lib.rs
Labels: A0-pleasereview

#2593 dockerfile update
  .gitlab-ci.yml
  scripts/docker/Dockerfile
Labels: M1-ci

#2597 increase block gas limit
  node/runtime/src/lib.rs
  srml/contract/src/lib.rs
Labels: A0-pleasereview

#2596 Keep node information about disconnection
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/behaviour/debug_info.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
Labels: A0-pleasereview

#2503 Add tty password input
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
Labels: A3-needsresolving, A6-mustntgrumble

#2595 Add quantization test for on_dilution
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, F4-tests 🎯

#2594 Forward the result in a sudo call
  node/runtime/wasm/Cargo.lock
  srml/sudo/Cargo.toml
  srml/sudo/src/lib.rs
Labels: A0-pleasereview, A4-gotissues

#2589 node: set protocol id for flaming fir
  node/cli/res/flaming-fir.json
Labels: A0-pleasereview, A2-insubstantial

#2601 Libp2p v0.7.1 backport
  Cargo.lock
Labels: A2-insubstantial, A8-backport

#2588 Replace compile_fail doc tests with trybuild
  .gitignore
  Cargo.lock
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/tests/trybuild.rs
  core/sr-api-macros/tests/ui/adding_at_parameter.rs
  core/sr-api-macros/tests/ui/adding_at_parameter.stderr
  core/sr-api-macros/tests/ui/adding_self_parameter.rs
  core/sr-api-macros/tests/ui/adding_self_parameter.stderr
  core/sr-api-macros/tests/ui/changed_in_unknown_version.rs
  core/sr-api-macros/tests/ui/changed_in_unknown_version.stderr
  core/sr-api-macros/tests/ui/declaring_old_block.rs
  core/sr-api-macros/tests/ui/declaring_old_block.stderr
  core/sr-api-macros/tests/ui/declaring_own_block_with_different_name.rs
  core/sr-api-macros/tests/ui/declaring_own_block_with_different_name.stderr
  core/sr-api-macros/tests/ui/empty_impl_runtime_apis_call.rs
  core/sr-api-macros/tests/ui/empty_impl_runtime_apis_call.stderr
  core/sr-api-macros/tests/ui/impl_incorrect_method_signature.rs
  core/sr-api-macros/tests/ui/impl_incorrect_method_signature.stderr
  core/sr-api-macros/tests/ui/impl_two_traits_with_same_name.rs
  core/sr-api-macros/tests/ui/impl_two_traits_with_same_name.stderr
  core/sr-api-macros/tests/ui/invalid_api_version.rs
  core/sr-api-macros/tests/ui/invalid_api_version.stderr
  core/sr-api-macros/tests/ui/invalid_api_version_2.rs
  core/sr-api-macros/tests/ui/invalid_api_version_2.stderr
  core/sr-api-macros/tests/ui/invalid_api_version_3.rs
  core/sr-api-macros/tests/ui/invalid_api_version_3.stderr
  core/sr-api-macros/tests/ui/missing_block_generic_parameter.rs
  core/sr-api-macros/tests/ui/missing_block_generic_parameter.stderr
  core/sr-api-macros/tests/ui/missing_path_for_trait.rs
  core/sr-api-macros/tests/ui/missing_path_for_trait.stderr
  core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.rs
  core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A8-looksgood

#2600 Libp2p 0.7.1
  Cargo.lock
Labels: A2-insubstantial

#2598 Dockerfile optimization
  .gitlab-ci.yml
  scripts/docker/Dockerfile
Labels: A8-backport, M1-ci

#2612 fix(telemetry): remove needless `Box`
  core/telemetry/src/lib.rs
Labels: A2-insubstantial

#2610 Remove remains from metadata v0
  node/runtime/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A0-pleasereview

#2527 feat(light client): fetch block body from remote
  core/client/src/light/blockchain.rs
  core/client/src/light/fetcher.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/test-client/src/lib.rs
Labels: A0-pleasereview

#2599 Flaming fir deployment scripts
  .gitlab-ci.yml
  scripts/flamingfir-deploy.sh
Labels: A0-pleasereview

#2606 backport increase block gas limit
  srml/contract/src/lib.rs
Labels: A4-gotissues, A8-looksgood

#2607 Update to libp2p 0.8
  Cargo.lock
  core/cli/src/lib.rs
  core/consensus/common/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/config.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/peerset/Cargo.toml
Labels: A0-pleasereview

#2627 Allow warnings
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/src/lib.rs
Labels: A2-insubstantial

#2640 Fix panic in PSM when add_reserved_peer(same_peer) is called twice
  core/peerset/src/peersstate.rs
Labels: A8-looksgood

#2577 Remove the NetworkChan
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#2643 Update build script to create a table for the runtime
  node-template/runtime/wasm/build.sh
Labels: A0-pleasereview, A2-insubstantial

#2647 docs: Update Support SRML rephrasing EnumerableStorageMap comment in Rustdocs
  srml/support/src/storage/mod.rs
Labels: A4-gotissues

#2644 Backport: Update build script to create a table for the runtime
  node-template/runtime/wasm/build.sh
Labels: A0-pleasereview, A2-insubstantial

#2658 Backport: Make contract dispatchables public
  node/runtime/src/lib.rs
  srml/contract/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#2660 propagate round messages after verification
  core/finality-grandpa/src/communication/gossip.rs
Labels: A0-pleasereview

#2602 Remove `As`
  Cargo.lock
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/evaluation.rs
  core/consensus/rhd/src/lib.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/network/src/blocks.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
  core/rpc/src/chain/number.rs
  core/rpc/src/state/mod.rs
  core/service/src/chain_ops.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/changes_trie/prune.rs
  core/test-runtime/wasm/Cargo.lock
  core/transaction-pool/graph/src/pool.rs
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/aura/src/lib.rs
  srml/babe/src/lib.rs
  srml/balances/src/lib.rs
  srml/contract/src/account_db.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/rent.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/code_cache.rs
  srml/contract/src/wasm/env_def/macros.rs
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/indices/src/address.rs
  srml/indices/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2642 Remove TaskExecutor from the API of the informant
  core/cli/src/informant.rs
  node-template/src/cli.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview

#2661 Make info! string less ambiguous
  core/network-libp2p/src/behaviour.rs
Labels: A2-insubstantial

#2659 get rid of refcell, use &mut storage
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/storage/hashed/generator.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
  srml/support/src/storage/unhashed/generator.rs
Labels: A0-pleasereview, A4-gotissues

#2655 Remove dependency on parity-crypto
  .gitlab-ci.yml
  Cargo.lock
  core/keystore/Cargo.toml
  core/keystore/src/lib.rs
Labels: A0-pleasereview

#2654 fix(protobuf vulner): update to 2.6
  Cargo.lock
Labels: A2-insubstantial, B0-patchthis

#2646 docs: Update Support SRML to link to StorageDoubleMap in Rustdocs
  srml/support/procedural/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues

#2632 core: allow setting max ws rpc connections
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/rpc-servers/src/lib.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
Labels: A8-looksgood, M4-core

#2641 More extractions from the Protocol struct
  core/network/src/config.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2502 Contract restoration
  Cargo.lock
  core/state-machine/src/ext.rs
  core/state-machine/src/testing.rs
  node/runtime/src/lib.rs
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/lib.rs
  srml/contract/src/rent.rs
  srml/contract/src/tests.rs
  srml/executive/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2670 Rework the OnDemand service
  core/network/src/config.rs
  core/network/src/lib.rs
  core/network/src/on_demand.rs
  core/network/src/on_demand_layer.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2667 Make peerset ban nodes under a reputation
  core/peerset/src/lib.rs
Labels: A0-pleasereview

#2681 show rust versions
  .gitlab-ci.yml
Labels: A8-backport, B0-patchthis, M1-ci

#2685 Lower the required code threshold.
  core/rpc/src/state/tests.rs
Labels: A2-insubstantial, M4-core

#2687 Check for exact wasm blob size in RPC tests
  core/rpc/src/state/tests.rs
Labels: A0-pleasereview, A2-insubstantial

#2690 Fix doc propagation for `Call` enum
  srml/staking/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A0-pleasereview, A4-gotissues

#2676 Register previous rounds' votes with gossip service on startup
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
Labels: A0-pleasereview, M4-core

#2692 Fix not connected peers being connected peers
  core/network-libp2p/src/service_task.rs
Labels: A0-pleasereview

#2682 some prettiness
  .gitlab-ci.yml
  scripts/docker/Dockerfile
Labels: A8-backport, B0-patchthis, M1-ci

#2684 Peerset should never return Ready(None)
  core/peerset/src/lib.rs
Labels: A0-pleasereview

#2651 Silence known deprecation warnings
  core/cli/src/informant.rs
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/chain.rs
  core/network/src/test/mod.rs
  core/service/src/components.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/test-client/src/trait_tests.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
Labels: A2-insubstantial

#2680 Allow passing an optional transport to network-libp2p
  Cargo.lock
  core/network-libp2p/src/config.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/transport.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview

#2666 Remove BlockNumber <-> u64 conversions from light-client related code
  Cargo.lock
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/genesis.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/changes_trie.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/basic.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/input.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-runtime/src/system.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/system/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2701 Synchronous import queue + fix async inport queue shutdown
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/network/src/service.rs
Labels: A8-looksgood, B2-breaksapi, M4-core

#2697 Deprecate NetworkSpecialization::on_abort
  core/network/src/specialization.rs
Labels: A2-insubstantial

#2704 Update docs on `Imbalance` in the Balances module
  srml/balances/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues, M3-docs

#2686 Make RocksDB optional in client-db
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/service/Cargo.toml
Labels: A0-pleasereview

#2706 The network configuration now makes more sense
  core/network/src/config.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2603 Pass through custom authority key with --dev
  core/cli/src/lib.rs
Labels: A0-pleasereview

#2674 Fix typo in block_builder.rs
  core/client/src/block_builder/block_builder.rs
Labels: A0-pleasereview, A2-insubstantial

#2481 Transaction factory
  Cargo.lock
  core/cli/src/lib.rs
  core/cli/src/traits.rs
  core/consensus/common/src/lib.rs
  core/inherents/src/lib.rs
  core/sr-primitives/src/generic/mod.rs
  node/cli/Cargo.toml
  node/cli/src/factory_impl.rs
  node/cli/src/lib.rs
  test-utils/transaction-factory/Cargo.toml
  test-utils/transaction-factory/src/complex_mode.rs
  test-utils/transaction-factory/src/lib.rs
  test-utils/transaction-factory/src/modes.rs
  test-utils/transaction-factory/src/simple_modes.rs
Labels: A0-pleasereview, A4-gotissues

#2696 Split the send_request method in multiple requests
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
Labels: A0-pleasereview

#2702 Use $crate inside of native_executor_instance and parameter_types macros
  core/executor/src/native_executor.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues

#2708 Fix compilation
  test-utils/transaction-factory/src/lib.rs
Labels: A2-insubstantial

#2683 Rewrite sync and network layers to use futures
  Cargo.lock
  core/finality-grandpa/src/communication/mod.rs
  core/network/Cargo.toml
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/service/src/components.rs
  core/service/src/lib.rs
Labels: A8-looksgood

#2466 Introduce inherent digests
  .gitlab-ci.yml
  Cargo.lock
  Dockerfile
  core/basic-authorship/src/basic_authorship.rs
  core/client/db/src/light.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/consensus/aura/src/digest.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/digest.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/common/src/select_chain.rs
  core/consensus/slots/src/aux_schema.rs
  core/executor/src/allocator.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/on_demand.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/primitives/Cargo.toml
  core/rpc/src/chain/tests.rs
  core/rpc/src/state/tests.rs
  core/service/src/components.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-api-macros/tests/ui/invalid_api_version_2.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/generic/header.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/test-client/src/trait_tests.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  scripts/flamingfir-deploy.sh
  srml/aura/src/tests.rs
  srml/consensus/src/tests.rs
  srml/contract/src/tests.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/grandpa/src/tests.rs
  srml/system/src/lib.rs
  test-utils/transaction-factory/src/lib.rs
  test-utils/transaction-factory/src/modes.rs
Labels: A0-pleasereview, B2-breaksapi

#2714 derive codec for inherent data
  core/inherents/src/lib.rs
  node/runtime/src/lib.rs
Labels: B2-breaksapi

#2700 Limited Unbonding Chunks.
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A5-grumble

#2716 Maps are appendable too
  node/runtime/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/src/lib.rs
  srml/support/src/storage/child.rs
  srml/support/src/storage/hashed/generator.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
Labels: A0-pleasereview, A4-gotissues

#2709 core: import equivocated aura and babe blocks
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/slots/Cargo.toml
  core/consensus/slots/src/aux_schema.rs
Labels: A3-needsresolving, A8-looksgood, M4-core

#2718 Update dependencies
  Cargo.lock
Labels: A0-pleasereview

#2695 Remove InherentsPool and introduce non-propagateable transactions.
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/inherents/src/lib.rs
  core/inherents/src/pool.rs
  core/offchain/Cargo.toml
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/service/Cargo.toml
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-primitives/src/transaction_validity.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/graph/src/rotator.rs
  core/transaction-pool/src/tests.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
Labels: A8-looksgood, B2-breaksapi, M4-core
