Repository paritytech/substrate, pull requests merged in 2019-04, with the labels that each got.

#2145 Remove `execute_extrinsics_without_checks` as it will not be required
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2154 keep track storage bytes
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
Labels: A3-inprogress

#2163 Remove an unnecessary clone in aura
  core/consensus/aura/src/lib.rs
Labels: A2-insubstantial

#2164 fix backwards compatibility for aura seals
  core/consensus/aura/slots/src/lib.rs
  core/consensus/aura/src/lib.rs
Labels: A0-pleasereview

#2162 Minor logging improvements in libp2p
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A2-insubstantial

#2160 Implement support for renaming runtime api functions
  core/client/src/block_builder/api.rs
  core/client/src/call_executor.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/rpc/src/state/tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/utils.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood

#2122 new Dockerfile, new cache
  .gitlab-ci.yml
Labels: A1-onice, M1-ci

#2158 skip phantom for decl_event
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/authorities/Cargo.toml
  core/consensus/common/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/primitives/Cargo.toml
  core/inherents/Cargo.toml
  core/network/Cargo.toml
  core/offchain/Cargo.toml
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-version/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  core/util/fork-tree/Cargo.toml
  node-template/Cargo.toml
  node-template/runtime/Cargo.toml
  node-template/runtime/wasm/Cargo.lock
  node/cli/Cargo.toml
  node/executor/Cargo.toml
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/assets/Cargo.toml
  srml/aura/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/finality-tracker/Cargo.toml
  srml/grandpa/Cargo.toml
  srml/indices/Cargo.toml
  srml/metadata/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/sudo/Cargo.toml
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
  srml/support/test/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A1-onice

#2146 no_std support for substrate trie
  Cargo.lock
  Cargo.toml
  core/client/Cargo.toml
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-io/Cargo.toml
  core/sr-std/with_std.rs
  core/sr-std/without_std.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/trie/Cargo.toml
  core/trie/src/error.rs
  core/trie/src/lib.rs
  core/trie/src/node_codec.rs
  core/trie/src/trie_stream.rs
  node-template/Cargo.toml
  node/runtime/src/lib.rs
Labels: A7-looksgoodcantmerge

#2171 style(on_demand): remove needless wildcards
  core/network/src/on_demand.rs
Labels: A2-insubstantial

#2176 Aura: add a deprecated method for seal compatibility
  core/consensus/aura/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, B0-patchthis

#2180 Fix Staking Accuracy issues.
  node/runtime/src/lib.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A8-looksgood, B0-patchthis

#2179 [v1.0] aura API defaults to rejecting old seals
  core/consensus/aura/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A8-backport

#2110 Initial version of the polite-grandpa networking protocol
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/test-runtime/wasm/Cargo.lock
  node/cli/src/service.rs
Labels: A8-looksgood, B0-patchthis

#2183 ensure imbalances are properly accounted for
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2161 implement contract events
  node/runtime/src/lib.rs
  srml/contract/COMPLEXITY.md
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
  srml/support/test/tests/instance.rs
Labels: A0-pleasereview, B2-breaksapi

#2184 Replace Vec<u8> with [u8; 32] for contract storage key
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, M8-contracts

#2188 Remove redundant Ok(()) and explicitly specify StorageKey buffer type
  srml/contract/src/wasm/runtime.rs
Labels: A2-insubstantial, A8-looksgood, M8-contracts

#2178 Switch to `derive(Encode, Decode)` for `Call`
  Cargo.lock
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
Labels: A0-pleasereview, A4-gotissues

#2170 Cache changes trie config in db storage
  core/client/db/src/lib.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#2190 Fix version check for renamed runtime api methods
  core/sr-api-macros/src/decl_runtime_apis.rs
Labels: A0-pleasereview, B0-patchthis

#2193 Enable `std` feature for all dependencies in node-runtime
  node/runtime/Cargo.toml
Labels: A2-insubstantial

#2197 Emberic Elm testnet
  README.adoc
  node/cli/res/dried-danta.json
  node/cli/res/emberic-elm.json
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview, B0-patchthis

#2210 Introduce `original_storage` and `original_storage_hash`
  core/executor/src/native_executor.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
Labels: A0-pleasereview, B2-breaksapi

#2206 code cleanup
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A8-looksgood

#2211 Introduce `original_storage` and `original_storage_hash`
  core/executor/src/native_executor.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
Labels: A0-pleasereview

#2201 core: grandpa: verify commit target in justification
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#2212 Disconnect on protocol timeout
  core/network-libp2p/src/custom_proto/handler.rs
  core/peerset/src/lib.rs
Labels: B0-patchthis, M4-core

#2123 simplification of peerset api
  Cargo.lock
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/peerset/src/lib.rs
  core/peerset/src/slots.rs
Labels: A8-looksgood, M4-core

#2213 Peerset::discovered accepts many peer ids
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/peerset/src/lib.rs
Labels: A6-mustntgrumble, M4-core

#2216 Use `storage_root` of newly calculated header
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
Labels: A0-pleasereview

#2220 Fix state inconsistency between handler and behaviour
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview

#2203 Contract import/export validation
  node/runtime/src/lib.rs
  srml/contract/src/wasm/prepare.rs
Labels: A8-looksgood, B2-breaksapi, M8-contracts

#2157 Remove Clone bound on specialization in TestNetFactory
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#2139 grandpa: Voter persistence and upgrade to finality-grandpa v0.7
  Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
Labels: A8-looksgood, M4-core

#2222 update name and authors to placeholder text for node-template
  node-template/Cargo.toml
Labels: A8-looksgood

#2234 Add warning when using default protocol ID
  core/service/src/lib.rs
Labels: A8-looksgood

#2236 Throw a compile error for `on_finalise` and `on_initialise`
  node/runtime/wasm/Cargo.lock
  srml/support/src/dispatch.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, A4-gotissues

#2227 Peerset: reuse Slots data structure for discovered peers
  core/peerset/src/lib.rs
  core/peerset/src/slots.rs
Labels: A0-pleasereview, M4-core

#2247 Apply negative rating on explicit ban
  core/network/src/service.rs
  core/peerset/src/lib.rs
Labels: A0-pleasereview, B0-patchthis

#2253 docs: Fix off-chain worker execution strategy comment
  core/cli/src/params.rs
Labels: A2-insubstantial, M4-core

#2238 Throw a compile error for `on_finalise` and `on_initialise`
  srml/support/src/dispatch.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2254 Add missing docs to prevent warnings
  core/executor/src/native_executor.rs
  core/executor/src/wasm_utils.rs
Labels: A0-pleasereview

#2239 Introduce `ext_println` to contract runtime
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  srml/contract/src/lib.rs
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, B2-breaksapi, M8-contracts

#2256 Introduce `ext_println` to contract runtime
  node/cli/src/chain_spec.rs
  srml/contract/src/lib.rs
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
Labels: B2-breaksapi

#2231 Replace error-chain for client error
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/cli/src/error.rs
  core/client/Cargo.toml
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/list_storage.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/blockchain.rs
  core/client/src/call_executor.rs
  core/client/src/children.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/in_mem.rs
  core/client/src/leaves.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/consensus/aura/slots/src/lib.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/justification.rs
  core/network/src/error.rs
  core/network/src/on_demand.rs
  core/rpc/src/author/error.rs
  core/rpc/src/chain/error.rs
  core/rpc/src/state/error.rs
  core/rpc/src/state/tests.rs
  core/service/src/error.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/test-runtime/wasm/Cargo.lock
  core/transaction-pool/src/error.rs
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, A8-looksgood

#2259 Fix races in sync tests
  core/consensus/aura/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#2264 Backport to v1.0: fix races in sync tests
  core/consensus/aura/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A8-backport, B2-breaksapi

#2265 Update `template-node` to `node-template`
  node-template/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis

#2144 SRML Executive Documentation
  srml/executive/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2276 Remove unused imports/ doc comments.
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/finality-grandpa/src/environment.rs
  core/network/src/consensus_gossip.rs
  core/network/src/message.rs
  core/network/src/test/sync.rs
  node-template/runtime/src/template.rs
Labels: A2-insubstantial

#2165 Add basic BABE consensus type
  Cargo.lock
  Cargo.toml
  core/consensus/aura/slots/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/primitives/Cargo.toml
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/slots/Cargo.toml
  core/consensus/slots/src/lib.rs
  core/consensus/slots/src/slots.rs
  core/primitives/Cargo.toml
  core/primitives/src/sr25519.rs
  core/sr-api-macros/Cargo.toml
  core/sr-primitives/src/generic/digest.rs
  core/test-runtime/src/lib.rs
  node/runtime/src/lib.rs
  srml/support/procedural/Cargo.toml
  srml/support/procedural/tools/Cargo.toml
  srml/support/procedural/tools/derive/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#2249 core: grandpa: persist voter set state on authority set change
  core/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, M4-core

#2245 Disable gossip for peers running old version
  core/network/src/protocol.rs
  core/network/src/service.rs
Labels: A8-looksgood

#2279 Backport cli purge fix
  core/cli/src/lib.rs
Labels: B2-breaksapi

#2267 Remove peerset debug output test
  Cargo.lock
  core/peerset/Cargo.toml
  core/peerset/src/slots.rs
  srml/support/Cargo.toml
Labels: A0-pleasereview, A4-gotissues

#2280 bigger cache size for sccache
  .gitlab-ci.yml
Labels: M1-ci

#2229 Polite-grandpa improvements
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/periodic.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/src/lib.rs
  core/network/src/service.rs
Labels: A8-looksgood, M4-core

#2285 Fix for miscalculation of storage root
  core/sr-io/without_std.rs
  core/state-machine/src/ext.rs
Labels: A0-pleasereview, A4-gotissues

#2278 [v1.0] Backport networking fixes
  Cargo.lock
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/peerset/src/lib.rs
  core/peerset/src/slots.rs
Labels: A0-pleasereview, M4-core

#2291 Disable CORS when running in --dev
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview, M4-core

#2282 Add `StorageValue::append` and speed-up `deposit_event`
  Cargo.lock
  core/executor/wasm/Cargo.lock
  core/sr-io/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/support/Cargo.toml
  srml/support/src/storage/generator.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/unhashed/generator.rs
  srml/system/Cargo.toml
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
Labels: A4-gotissues, A7-looksgoodtestsfail

#2258 add fn debug_info to peerset
  core/peerset/src/lib.rs
  core/peerset/src/slots.rs
Labels: A0-pleasereview, M4-core

#2172 Update Documentation
  srml/balances/src/lib.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/staking/src/lib.rs
  srml/sudo/src/lib.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2074 Documentation for Aura Consensus Extension
  srml/aura/src/lib.rs
Labels: A8-looksgood, M3-docs

#2299 Fix contract child usage
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
Labels: A0-pleasereview

#2290 Use ed25519 by default for network keys
  core/cli/src/params.rs
  core/network-libp2p/src/config.rs
Labels: A0-pleasereview

#2307 Make existing docs more consistent
  srml/aura/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/contract/src/lib.rs
  srml/staking/src/lib.rs
  srml/sudo/src/lib.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A4-gotissues, A8-looksgood, M3-docs

#2311 Remove peerset debug output test (again)
  core/peerset/src/slots.rs
Labels: A0-pleasereview

#2244 grandpa: observer
  Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  node/cli/src/service.rs
Labels: A8-looksgood, M4-core

#2310 Make Documentation Examples Compile
  srml/aura/src/lib.rs
  srml/balances/src/lib.rs
  srml/consensus/src/lib.rs
  srml/executive/src/lib.rs
  srml/staking/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, F5-documentation 📄

#2323 minor typos
  srml/balances/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#2324 fix minor typos
  srml/balances/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, M3-docs

#2327 [srml-support] restrict patch version of syn
  srml/support/procedural/Cargo.toml
Labels: A2-insubstantial, A4-gotissues, M5-dependencies

#2321 Remove limitation to 256 transactions, don't construct a vector.
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
Labels: A0-pleasereview, M4-core

#2296 substrate-network-libp2p uses tokio_timer::clock::Clock
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview, M4-core

#2306 Make correct feature selection in node-template Cargo.toml
  node-template/runtime/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#2218 assert trie odd nibble padding on decoding
  core/trie/src/node_codec.rs
Labels: A0-pleasereview

#2330 contracts: Validate code before deployment
  Cargo.lock
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  srml/contract/Cargo.toml
  srml/contract/src/wasm/code_cache.rs
  srml/contract/src/wasm/prepare.rs
Labels: A0-pleasereview, B2-breaksapi

#2340 Build wasm files in doc release pipeline
  .gitlab-ci.yml
Labels: A2-insubstantial

#2198 Adjust consensus telemetry
  Cargo.lock
  core/client/src/client.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/peerset/src/lib.rs
  core/service/src/lib.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  node/cli/src/service.rs
Labels: A8-looksgood, B2-breaksapi

#2348 Add warnings about breaking changes in network
  core/network-libp2p/src/lib.rs
  core/network/src/lib.rs
Labels: A2-insubstantial

#2350 ProtocolId can now be more than 3 bytes
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/tests/test.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2033 Fix MultiSigner, simplify tests
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/genesis.rs
  core/keyring/Cargo.toml
  core/keyring/src/ed25519.rs
  core/keyring/src/sr25519.rs
  core/network/src/test/mod.rs
  core/rpc/src/author/tests.rs
  core/service/src/components.rs
  core/sr-primitives/src/lib.rs
  core/test-client/src/block_builder_ext.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, B2-breaksapi

#2349 Backport #2348
  core/network-libp2p/src/lib.rs
  core/network/src/lib.rs
Labels: A8-backport, B2-breaksapi

#2345 Backport: Check storage_key for validity
  core/executor/src/wasm_executor.rs
  core/primitives/src/storage.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
  core/trie/Cargo.toml
  core/trie/src/lib.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
Labels: A8-backport, B2-breaksapi

#2351 Use serde `derive` feature.
  Cargo.lock
  core/executor/Cargo.toml
  core/keystore/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/changes_trie.rs
  core/primitives/src/lib.rs
  core/primitives/src/storage.rs
  core/rpc/Cargo.toml
  core/rpc/src/chain/number.rs
  core/rpc/src/system/helpers.rs
  core/service/Cargo.toml
  core/service/src/chain_spec.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/generic/block.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/generic/era.rs
  core/sr-primitives/src/generic/header.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-version/Cargo.toml
  core/sr-version/src/lib.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/watcher.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node/primitives/Cargo.toml
  node/runtime/wasm/Cargo.lock
  srml/consensus/Cargo.toml
  srml/consensus/src/lib.rs
  srml/contract/Cargo.toml
  srml/contract/src/lib.rs
  srml/democracy/Cargo.toml
  srml/democracy/src/vote_threshold.rs
  srml/finality-tracker/Cargo.toml
  srml/grandpa/Cargo.toml
  srml/grandpa/src/lib.rs
  srml/metadata/Cargo.toml
  srml/metadata/src/lib.rs
  srml/support/Cargo.toml
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/test/Cargo.toml
  srml/support/test/tests/instance.rs
  srml/system/Cargo.toml
  srml/system/src/lib.rs
  srml/treasury/Cargo.toml
  srml/treasury/src/lib.rs
Labels: A4-gotissues, F6-refactor 🧹

#2343 Update to libp2p v0.7.0
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/service/test/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview

#2314 Configurable state cache size and enforce exact state cache size
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/backend.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview

#2341 decl_storage doc
  srml/support/procedural/src/lib.rs
  srml/support/src/hashable.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2147 Documentation: decl_module! macro
  Cargo.lock
  core/sr-primitives/src/traits.rs
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2353 impl twox 128 concat
  core/primitives/Cargo.toml
  core/primitives/benches/benches.rs
  srml/metadata/src/lib.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/hashable.rs
  srml/support/src/lib.rs
  srml/support/src/storage/hashed/generator.rs
Labels: B2-breaksapi

#1945 Documentation for assets module
  srml/assets/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#1947 Documentation for example module
  srml/example/src/lib.rs
Labels: A4-gotissues, M3-docs

#2269 Documentation: Treasury module
  srml/treasury/src/lib.rs
Labels: A4-gotissues

#2268 move storage maps to blake2_128
  core/client/src/client.rs
  core/client/src/light/fetcher.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/benches/benches.rs
  core/primitives/src/hashing.rs
  core/primitives/src/lib.rs
  core/rpc/src/state/tests.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
  srml/indices/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/hashable.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/child.rs
  srml/support/src/storage/hashed/generator.rs
  srml/support/src/storage/hashed/mod.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
  srml/support/src/storage/unhashed/generator.rs
  srml/support/src/storage/unhashed/mod.rs
Labels: A0-pleasereview, B2-breaksapi, P2-asap

#2289 set reasonable value for bonding_duration in chainspec staging config
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2283 Documentation for the Session Module
  srml/session/src/lib.rs
Labels: A0-pleasereview, A4-gotissues

#2356 Back port to 1.0: Move scripts to scripts folder and update readme (#2331)
  node-template/README.md
  node-template/scripts/build.sh
  node-template/scripts/init.sh
Labels: B2-breaksapi

#2358 Backport #2327: restrict patch version of syn
  srml/support/procedural/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, A8-backport, B2-breaksapi

#2360 Forward port blake2 storage support
  core/client/src/client.rs
  core/client/src/light/fetcher.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/benches/benches.rs
  core/primitives/src/hashing.rs
  core/primitives/src/lib.rs
  core/rpc/src/state/tests.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/executive/src/lib.rs
  srml/indices/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/event.rs
  srml/support/src/hashable.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/child.rs
  srml/support/src/storage/hashed/generator.rs
  srml/support/src/storage/hashed/mod.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
  srml/support/src/storage/unhashed/generator.rs
  srml/support/src/storage/unhashed/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#2361 Use balances::TotalIssuance for scaling between votes and balances
  core/sr-primitives/src/traits.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, B2-breaksapi

#2363 Backport #2362
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-backport, B2-breaksapi

#2362 Silence the spam a little bit
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A2-insubstantial

#2109 Subkey can construct and sign transfer txs
  Cargo.lock
  core/primitives/src/crypto.rs
  subkey/Cargo.toml
  subkey/src/cli.yml
  subkey/src/main.rs
Labels: A0-pleasereview

#2364 Use balances::TotalIssuance for scaling between votes and balances (#…
  core/sr-primitives/src/traits.rs
  node/runtime/src/lib.rs
Labels: A8-backport, B2-breaksapi

#2367 Subkey can construct and sign transfer txs (#2109)
  Cargo.lock
  core/primitives/src/crypto.rs
  subkey/Cargo.toml
  subkey/src/cli.yml
  subkey/src/main.rs
Labels: A8-backport, B2-breaksapi

#2370 git: allow diffing Cargo.lock
  .gitattributes
Labels: A0-pleasereview, A2-insubstantial

#2371 Update hex-literal version, simplify imports and remove unused dependencies
  Cargo.lock
  core/executor/Cargo.toml
  core/executor/src/wasm_executor.rs
  core/keyring/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/benches/benches.rs
  core/primitives/src/crypto.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/sr25519.rs
  core/rpc/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/test-runtime/Cargo.toml
  core/trie/Cargo.toml
  core/trie/src/lib.rs
  node-template/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/runtime/Cargo.toml
  srml/assets/Cargo.toml
  srml/aura/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/contract/src/tests.rs
  srml/council/Cargo.toml
  srml/council/src/motions.rs
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/finality-tracker/Cargo.toml
  srml/indices/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/sudo/Cargo.toml
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
  subkey/Cargo.toml
  subkey/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues

#2373 Remove the multiplexed networking system
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/tests/test.rs
  core/network/src/message.rs
Labels: A7-looksgoodtestsfail

#2376 Backport fix node template release script
  node-template/scripts/build.sh
  scripts/node-template-release/src/main.rs
Labels: A2-insubstantial, B2-breaksapi

#2375 Fixes node-template-release
  node-template/scripts/build.sh
  scripts/node-template-release/src/main.rs
Labels: A2-insubstantial

#2380 Allow localhost IP by default.
  core/cli/src/lib.rs
Labels: A2-insubstantial, M2-config

#2383 remove use of hidden api in support procedural
  Cargo.lock
  srml/support/procedural/Cargo.toml
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/procedural/tools/src/syn_ext.rs
Labels: A4-gotissues

#2381 Unify & enforce same interface of sr-io (std & without-std)
  core/cli/src/lib.rs
  core/executor/wasm/src/lib.rs
  core/peerset/src/lib.rs
  core/sr-io/Cargo.toml
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, M4-core

#2386 backport remove procedural keyword
  Cargo.lock
  srml/support/procedural/Cargo.toml
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/procedural/tools/src/syn_ext.rs
Labels: B2-breaksapi

#2389 Use aws image for s3-docs upload
  .gitlab-ci.yml
Labels: A2-insubstantial

#2392 Use trie_root instead of TrieDBMut to calculate default_child_trie_root
  core/trie/src/lib.rs
Labels: A0-pleasereview

#2394 Read locks once and not 2 times
  srml/balances/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues

#2387 decl_storage document hasher choice
  srml/support/procedural/src/lib.rs
Labels: A0-pleasereview

#2379 Allow multiple substreams
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview

#2397 CI update
  .gitlab-ci.yml
Labels: B9-blocker, F1-security 👮‍♀️, M1-ci

#2398 More detailed instructions for Windows Setup
  README.adoc
Labels: A0-pleasereview, A8-looksgood, M3-docs

#2402 refactor: Remove duplicate line. Show on separate lines to fix formatting
  srml/example/src/lib.rs
Labels: A4-gotissues

#2404 Fix #2403
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#2409 Split Context::send_message into multiple methods
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
Labels: A0-pleasereview, B2-breaksapi, F6-refactor 🧹

#2414 store contract keys with blake2_256
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
Labels: A0-pleasereview, B2-breaksapi

#2313 Cumulus changes version 2
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/executor/src/native_executor.rs
  core/finality-grandpa/src/tests.rs
  core/service/src/components.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
  core/test-client/Cargo.toml
  core/test-client/src/client_ext.rs
  core/test-client/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
Labels: A0-pleasereview, A4-gotissues

#2419 Simplify the network background thread future
  core/network/src/service.rs
Labels: A0-pleasereview

#2422 backport store contract keys with blake2_256 (#2414)
  node/runtime/src/lib.rs
  srml/contract/src/account_db.rs
Labels: A8-backport, B2-breaksapi

#2418 Depreate functions that spawn a thread
  Cargo.lock
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/slots/Cargo.toml
  core/consensus/slots/src/lib.rs
Labels: A0-pleasereview

#2230 contract accounting removal
  core/state-machine/src/testing.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/contract/COMPLEXITY.md
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/rent.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, B2-breaksapi

#2399 Add `pub` to functions in Contract module
  srml/contract/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues
