Repository paritytech/substrate, pull requests merged in 2019-07, with the labels that each got.

#2983 bump `smallvec 0.6.10` to fix vulnerability
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  test-utils/chain-spec-builder/Cargo.lock
Labels: A0-pleasereview

#2975 Make constants exposable in metadata
  node/runtime/src/lib.rs
  srml/authorship/src/lib.rs
  srml/democracy/src/lib.rs
  srml/metadata/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/tests/instance.rs
Labels: A0-pleasereview, A4-gotissues

#2987 typo fix in core
  core/client/src/blockchain.rs
  core/client/src/light/backend.rs
  core/consensus/babe/src/digest.rs
  core/consensus/babe/src/lib.rs
  core/executor/src/sandbox.rs
  core/inherents/src/lib.rs
  core/peerset/src/lib.rs
  core/sr-primitives/src/lib.rs
  core/sr-sandbox/src/lib.rs
  core/sr-sandbox/without_std.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/transaction-pool/graph/src/ready.rs
Labels: A4-gotissues

#2990 typo fix in without_std.rs
  core/sr-std/without_std.rs
Labels: A4-gotissues

#2992 Adds a `SpawnTaskHandle` to core service
  core/service/src/lib.rs
Labels: A0-pleasereview

#2912 Initial mechanics for 80:20 fee split
  Cargo.lock
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/support/Cargo.toml
  srml/support/src/traits.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2883 Turn storage items into parameters
  node-template/runtime/src/lib.rs
  node-template/src/chain_spec.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/contracts/src/account_db.rs
  srml/contracts/src/gas.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/rent.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/treasury/src/lib.rs
Labels: A5-grumble, B2-breaksapi

#2997 Fix test of staking without equalize feature
  srml/staking/src/tests.rs
Labels: A8-looksgood

#2995 ci: add job to test staking in srml
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#2969 srml-contract: Validate that modules do not declare oversized tables.
  node/runtime/src/lib.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/wasm/prepare.rs
Labels: B2-breaksapi

#2894 Persistent Local Storage for offchain workers.
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/offchain.rs
  core/client/db/src/utils.rs
  core/client/src/backend.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/executor/Cargo.toml
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/executor/wasm/Cargo.toml
  core/executor/wasm/src/lib.rs
  core/offchain/Cargo.toml
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/offchain/src/testing.rs
  core/primitives/src/offchain.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-io/src/offchain/http.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/lib.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#2974 Fix periodic sessions and document behavior
  node/runtime/src/lib.rs
  srml/session/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2447 Council Module Documentation
  srml/council/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2929 BABE Randomness using PreRuntime digests
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/digest.rs
  core/consensus/babe/src/lib.rs
  core/consensus/slots/src/lib.rs
  core/consensus/slots/src/slots.rs
  core/executor/wasm/Cargo.lock
  core/primitives/Cargo.toml
  core/sr-primitives/src/traits.rs
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  srml/babe/Cargo.toml
  srml/babe/src/lib.rs
  srml/contracts/src/lib.rs
  subkey/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#3007 Implement Executor for Service and SpawnHandle
  core/service/src/lib.rs
Labels: A0-pleasereview

#3006 Implement `From` module `Call` for outer `Call`
  srml/democracy/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A2-insubstantial, A7-looksgoodtestsfail

#3000 Allow where bounds on `decl_module!` and `decl_storage!`
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
  srml/support/test/tests/instance.rs
Labels: A4-gotissues, A5-grumble

#3010 Downgrade `memory-db` in `test-runtime` to fix WASM compilation
  Cargo.lock
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#3004 Can now disable the keystore
  core/cli/src/lib.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
Labels: A6-seemsok, B2-breaksapi

#2868 Build WASM binaries as part of cargo build
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  README.adoc
  core/client/src/genesis.rs
  core/executor/Cargo.toml
  core/executor/runtime-test/Cargo.toml
  core/executor/runtime-test/build.rs
  core/executor/runtime-test/src/lib.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  core/executor/wasm/Cargo.lock
  core/executor/wasm/build.sh
  core/finality-grandpa/Cargo.toml
  core/network/Cargo.toml
  core/sr-api-macros/tests/trybuild.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/build.rs
  core/test-runtime/client/Cargo.toml
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.toml
  core/test-runtime/wasm/build.sh
  core/utils/fork-tree/Cargo.toml
  core/utils/fork-tree/src/lib.rs
  core/utils/wasm-builder-runner/Cargo.toml
  core/utils/wasm-builder-runner/README.md
  core/utils/wasm-builder-runner/src/lib.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/README.md
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/README.md
  node-template/runtime/Cargo.toml
  node-template/runtime/build.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.toml
  node-template/runtime/wasm/build.sh
  node-template/runtime/wasm/src/lib.rs
  node-template/scripts/build.sh
  node-template/src/chain_spec.rs
  node-template/src/service.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/build.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/runtime/wasm/build.sh
  scripts/build.sh
  srml/executive/src/lib.rs
Labels: A0-pleasereview, A4-gotissues

#2946 Session keys buffered for a session.
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A5-grumble, B2-breaksapi

#3008 Generic keystore
  Cargo.lock
  core/consensus/babe/src/lib.rs
  core/keyring/src/ed25519.rs
  core/keyring/src/sr25519.rs
  core/keystore/src/lib.rs
  core/primitives/src/crypto.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/lib.rs
  core/primitives/src/sr25519.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/Cargo.toml
  node/cli/src/service.rs
  node/primitives/src/lib.rs
  subkey/src/main.rs
Labels: A0-pleasereview

#3017 Update trie dependencies.
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/trie/Cargo.toml
  node-template/Cargo.toml
  node/executor/Cargo.toml
  node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3019 Fix `node-template-release` and make `cargo doc` faster
  .gitlab-ci.yml
  scripts/node-template-release/src/main.rs
Labels: A0-pleasereview, A2-insubstantial

#3020 Make `wasm-builder` less spammy
  Cargo.lock
  core/executor/runtime-test/Cargo.toml
  core/executor/runtime-test/build.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/build.rs
  core/utils/wasm-builder-runner/Cargo.toml
  core/utils/wasm-builder-runner/src/lib.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/build.rs
  node/runtime/Cargo.toml
  node/runtime/build.rs
Labels: A0-pleasereview

#3025 scripts: fix Dockerfile
  Dockerfile
Labels: A0-pleasereview, A2-insubstantial

#2801 grandpa: round catchup messages
  Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/src/protocol/consensus_gossip.rs
Labels: A8-looksgood, M4-core

#3003 on_start now returns the precise elements to request
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
Labels: A0-pleasereview, B2-breaksapi

#3021 grandpa: make observer relay round messages
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/observer.rs
Labels: A0-pleasereview, M4-core

#3013 Adjust the RPC service for the WASM-browser use case
  .gitlab-ci.yml
  core/rpc-servers/Cargo.toml
  core/rpc-servers/src/lib.rs
  core/service/src/components.rs
  core/service/src/lib.rs
Labels: A0-pleasereview

#3029 Use bip39 from crates.io
  Cargo.lock
  core/primitives/Cargo.toml
  subkey/Cargo.toml
Labels: A2-insubstantial

#3016 Rewrite the network TestNet
  core/cli/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/config.rs
  core/network/src/discovery.rs
  core/network/src/service.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/network/src/transport.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview

#3030 End build when `wasm-builder` does not find a prerequisite
  Cargo.lock
  core/executor/runtime-test/build.rs
  core/test-runtime/build.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  node-template/runtime/build.rs
  node/runtime/build.rs
Labels: A0-pleasereview

#3037 Implement `SelectInitialValidators` for `()`
  srml/session/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3035 core/finality: Ref `run_grandpa_voter` instead of deprecated func in doc
  core/finality-grandpa/src/lib.rs
Labels: M3-docs, Q0-trivial

#2962 Merge Protocol and ProtocolBehaviour
  core/network/src/behaviour.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/protocol_behaviour.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#3042 README: Replace outdated `period` with `minimumPeriod`
  README.adoc
Labels: M3-docs, Q0-trivial

#3043 Make `wasm-builder` work with `cargo install`
  Cargo.lock
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#3044 Document limitations of `decl_storage!` with instancing
  srml/support/procedural/src/lib.rs
Labels: A0-pleasereview

#3031 Split the import queue in three files
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
Labels: A2-insubstantial

#3040 Fix ui tests (E0308 error)
  core/sr-api-macros/tests/ui/impl_incorrect_method_signature.stderr
  core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A7-looksgoodtestsfail

#3056 Fixed block import command error handling
  core/service/src/chain_ops.rs
Labels: A0-pleasereview

#2970 Slash and prove membership of prior sessions
  Cargo.lock
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/testing.rs
  core/trie/src/lib.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/aura/src/mock.rs
  srml/babe/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/Cargo.toml
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi

#3049 Network crate cleanups
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/behaviour.rs
  core/network/src/config.rs
  core/network/src/custom_proto/behaviour.rs
  core/network/src/custom_proto/tests.rs
  core/network/src/custom_proto/upgrade.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/protocol/specialization.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3054 Specialization::on_message now takes Vec<u8>
  core/network/src/protocol.rs
  core/network/src/protocol/specialization.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#3057 Make `RUSTFLAGS` configurable in `wasm-builder`
  Cargo.lock
  core/executor/runtime-test/Cargo.toml
  core/executor/runtime-test/build.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/build.rs
  core/utils/wasm-builder-runner/Cargo.toml
  core/utils/wasm-builder-runner/src/lib.rs
  core/utils/wasm-builder/README.md
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/build.rs
  node/runtime/Cargo.toml
  node/runtime/build.rs
Labels: A8-looksgood

#3045 Make priviledged functions explicity use `origin`
  srml/balances/src/lib.rs
  srml/contracts/src/lib.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
  srml/support/src/dispatch.rs
  srml/support/test/tests/instance.rs
  srml/support/test/tests/reserved_keyword/on_initialize.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#3055 Dispatch on-disabled digests from consensus modules
  core/consensus/aura/primitives/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/digest.rs
  core/finality-grandpa/primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/babe/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/grandpa/src/tests.rs
Labels: A8-looksgood, B2-breaksapi

#3060 Update deps.
  Cargo.lock
Labels: A2-insubstantial

#3065 Hide the Kademlia warnings when offline
  core/network/src/discovery.rs
Labels: A0-pleasereview

#2286 Documentation for the Democracy Module
  srml/democracy/src/lib.rs
  srml/democracy/src/vote_threshold.rs
Labels: A0-pleasereview, M3-docs

#3062 srml: system: prune block hash mapping
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3058 Change the import queue traits to take &mut self instead of &self
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/test-client/src/client_ext.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  test-utils/transaction-factory/src/lib.rs
Labels: A0-pleasereview

#3039 Allow sub accounts to be derived from an TypeId.
  core/sr-primitives/src/traits.rs
Labels: A8-looksgood

#3018 Introduce flag to enable sentry nodes to participate in grandpa gossip
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
  node/cli/src/service.rs
  scripts/sentry-node/docker-compose.yml
Labels: A8-looksgood

#3009 Make use of child storage for testExternalities and basicExternalities
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/testing.rs
  node/executor/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/session/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A8-looksgood

#3024 Some documentation for discovery.rs
  core/network/src/discovery.rs
Labels: A0-pleasereview

#3078 core/network: Log when ignoring genesis block announcement
  core/network/src/protocol/sync.rs
Labels: A0-pleasereview, M4-core, P7-nicetohave, Q0-trivial

#3077 scripts/sentry-node: Ensure release mode and reserved connection for A
  scripts/sentry-node/docker-compose.yml
Labels: A0-pleasereview, M3-docs

#3081 network: don't announce genesis block
  core/network/src/protocol.rs
Labels: A0-pleasereview, M4-core

#3083 Check that validator set is not empty at genesis
  node/runtime/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
Labels: A0-pleasereview

#3084 Remove unconventional unit struct
  srml/session/src/lib.rs
  srml/session/src/mock.rs
Labels: A2-insubstantial

#3089 Expose `Aura` storage and calls
  node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3048 srml-staking: Force minimum bond amount + proper cleanup.
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A8-looksgood, B2-breaksapi

#3050 Sensible locking for staking and council.
  node/runtime/src/lib.rs
  srml/elections/src/lib.rs
  srml/executive/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/traits.rs
Labels: A8-looksgood

#3087 Remove set_finality_proof_request_builder
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/config.rs
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/service/src/chain_ops.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, B2-breaksapi

#3095 node: pass stash accounts to session module config
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, M4-core

#2790 GenericAsset module
  Cargo.lock
  Cargo.toml
  srml/generic-asset/Cargo.toml
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/generic-asset/src/tests.rs
Labels: A4-gotissues, A5-grumble

#3098 Cleanup CLI and introduce `execution-all`
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview

#3103 Switch the client to new futures
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/informant.rs
  core/client/Cargo.toml
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/notifications.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/Cargo.toml
  core/network/src/on_demand_layer.rs
  core/network/src/test/mod.rs
  core/rpc/Cargo.toml
  core/rpc/src/chain/mod.rs
  core/rpc/src/state/mod.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/test-client/Cargo.toml
  core/test-client/src/lib.rs
Labels: A0-pleasereview

#3100 Switch the telemetry to new futures
  Cargo.lock
  core/service/src/lib.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  core/telemetry/src/worker.rs
  core/telemetry/src/worker/node.rs
Labels: A0-pleasereview

#3093 Convert unnecessary storage item to static.
  node-template/runtime/src/lib.rs
  node-template/src/chain_spec.rs
  node/cli/src/chain_spec.rs
  node/cli/src/factory_impl.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/aura/src/mock.rs
  srml/babe/src/lib.rs
  srml/contracts/src/tests.rs
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3105 Remove `sync::Context` trait.
  Cargo.lock
  core/network/Cargo.toml
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
Labels: A0-pleasereview

#3112 Make parameter types implementation more flexible
  node/runtime/src/lib.rs
  srml/authorship/src/lib.rs
  srml/contracts/src/lib.rs
  srml/elections/src/lib.rs
  srml/support/src/lib.rs
Labels: A0-pleasereview

#3108 Switch the peerset to new futures
  Cargo.lock
  core/network/src/custom_proto/behaviour.rs
  core/peerset/Cargo.toml
  core/peerset/src/lib.rs
  core/peerset/tests/fuzz.rs
  core/service/src/lib.rs
Labels: A0-pleasereview

#3101 Improvements to the import queue
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/block_import.rs
  core/service/src/chain_ops.rs
Labels: A8-looksgood

#3110 Logs will be saved to the job artifacts only in case of failure.
  .gitlab-ci.yml
Labels: M1-ci

#3114 srml-contracts: Update complexity.md
  srml/contracts/COMPLEXITY.md
  srml/contracts/src/exec.rs
Labels: A0-pleasereview

#3120 node: fix hardcoded block time in integration tests
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3123 WIP: Subkey release.
  .gitlab-ci.yml
Labels: A8-backport, B0-patchthis, M1-ci

#3118 core/network: Remove self mutability on put and get value
  core/network/src/service.rs
Labels: A8-looksgood, M4-core

#3116 Make mDNS part of DiscoveryBehaviour
  core/network/src/behaviour.rs
  core/network/src/discovery.rs
Labels: A0-pleasereview

#2869 client: Reorg to new best when finalizing divergent branch
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/client.rs
Labels: A0-pleasereview, M4-core

#3094 Introduce vesting offsets
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
Labels: A8-looksgood, B2-breaksapi

#2840 Some changes tries optimizations
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
Labels: A0-pleasereview, M4-core

#3115 Weight Check signed extension.
  Cargo.lock
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/transaction_validity.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  subkey/src/main.rs
Labels: A0-pleasereview

#3126 Contract storage limit
  node/runtime/src/lib.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/tests.rs
  srml/contracts/src/wasm/mod.rs
  srml/contracts/src/wasm/runtime.rs
Labels: B2-breaksapi

#3129 Consistency with the Block trait name
  core/client/db/src/storage_cache.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/lib.rs
  core/consensus/rhd/src/lib.rs
  core/consensus/slots/src/lib.rs
  core/network/src/protocol/sync.rs
Labels: A2-insubstantial

#3125 Don't allow failure for more CI stages
  .gitlab-ci.yml
Labels: A2-insubstantial

#3121 srml-contracts: Avoid unnecessary lookups during call context initialization
  node/runtime/src/lib.rs
  srml/contracts/COMPLEXITY.md
  srml/contracts/src/exec.rs
Labels: B2-breaksapi

#3135 fix and test default instance for collective
  node/runtime/src/lib.rs
  srml/collective/src/lib.rs
Labels: A0-pleasereview

#3141 Update hex-literal dependency version.
  Cargo.lock
  core/client/Cargo.toml
  srml/babe/Cargo.toml
Labels: A2-insubstantial

#3130 client: fix decode block number as u32
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/db/src/utils.rs
  core/client/src/client.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#3117 Switch the network timers to new futures
  Cargo.lock
  core/network/Cargo.toml
  core/network/src/custom_proto/behaviour.rs
  core/network/src/custom_proto/handler.rs
  core/network/src/debug_info.rs
  core/network/src/discovery.rs
  core/network/src/protocol.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#3068 srml: grandpa: Pause/resume current authority set
  core/finality-grandpa/primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/grandpa/src/tests.rs
Labels: A8-looksgood, B2-breaksapi, M4-core

#2854 Transaction Fee Multiplier
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/weights.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/executor/src/lib.rs
  node/runtime/src/impls.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/Cargo.toml
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/executive/src/mock.rs
  srml/executive/src/tests.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/support/src/traits.rs
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3138 Operational Transaction; second attempt
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/weights.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview

#3079 Introduce srml/im-online
  Cargo.lock
  Cargo.toml
  core/executor/src/wasm_executor.rs
  core/network/src/lib.rs
  core/network/src/service.rs
  core/offchain/Cargo.toml
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/offchain/src/testing.rs
  core/primitives/src/offchain.rs
  core/service/Cargo.toml
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/babe/src/lib.rs
  srml/im-online/Cargo.toml
  srml/im-online/src/lib.rs
Labels: A5-grumble, B2-breaksapi

#3147 SS58 versioning (Network IDs)
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/crypto.rs
  subkey/src/cli.yml
  subkey/src/main.rs
Labels: A8-looksgood

#3151 docs: add srml readme, clarify comment in staking
  srml/README.adoc
  srml/staking/src/lib.rs
Labels: A0-pleasereview, M3-docs

#3158 Rename ImportBlock to BlockImportParams
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/rhd/src/lib.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/test-client/src/client_ext.rs
  node/cli/src/service.rs
  test-utils/transaction-factory/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3150 Refactors the offchain worker api
  core/client/db/src/offchain.rs
  core/executor/src/wasm_executor.rs
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/offchain/src/testing.rs
  core/primitives/src/crypto.rs
  core/primitives/src/offchain.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A6-mustntgrumble, B2-breaksapi

#3162 Fix doc in srml_support
  srml/support/src/storage/hashed/generator.rs
Labels: A0-pleasereview, A2-insubstantial, M3-docs

#3160 Add a warning if network is too slow
  core/service/src/lib.rs
Labels: A0-pleasereview

#3163 Alphabetical crates order
  Cargo.toml
Labels: A2-insubstantial

#3170 Document `decl_storage!` hashers
  srml/support/procedural/src/lib.rs
Labels: A0-pleasereview

#3102 Extensible transactions (and tips)
  Cargo.lock
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/transaction_validity.rs
  core/sr-primitives/src/weights.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/src/tests.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/cli/Cargo.toml
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/runtime/src/impls.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/executive/src/mock.rs
  srml/executive/src/tests.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/im-online/src/lib.rs
  srml/indices/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/support/src/traits.rs
  srml/support/test/tests/instance.rs
  srml/support/test/tests/issue2219.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  subkey/Cargo.toml
  subkey/src/main.rs
Labels: A0-pleasereview, B2-breaksapi

#3173 Export `VOTER_SET_SIZE` and `APPROVAL_SET_SIZE` in srml elections
  srml/elections/src/lib.rs
Labels: A0-pleasereview

#3169 Run each offchain worker in a separate thread.
  core/offchain/src/lib.rs
Labels: A0-pleasereview, M4-core

#3164 sleep_until off-chain API
  core/offchain/src/api.rs
Labels: A0-pleasereview

#3176 Fix test-runtime build
  core/test-runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3180 Bkchr check all benches
  .gitlab-ci.yml
  README.adoc
  core/consensus/babe/src/tests.rs
  srml/system/benches/bench.rs
Labels: A0-pleasereview, A2-insubstantial

#3181 Fix mDNS not working
  core/network/src/discovery.rs
Labels: A0-pleasereview

#3161 Report to the PSM when a severe protocol error happens
  core/network/src/custom_proto/behaviour.rs
  core/peerset/src/lib.rs
Labels: A0-pleasereview

#3184 Switch `srml-session` keys to `decl_storage!`
  node/runtime/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/im-online/src/lib.rs
  srml/session/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/double_map.rs
  srml/support/src/lib.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/unhashed/generator.rs
  srml/support/src/storage/unhashed/mod.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/instance.rs
Labels: A0-pleasereview, B2-breaksapi

#3076 libp2p-next
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/network/Cargo.toml
  core/network/src/behaviour.rs
  core/network/src/custom_proto/behaviour.rs
  core/network/src/custom_proto/handler.rs
  core/network/src/custom_proto/tests.rs
  core/network/src/debug_info.rs
  core/network/src/discovery.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/telemetry/Cargo.toml
Labels: A8-looksgood

#3191 Make function `get` of parameter types public
  srml/support/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#2882 Staking rate targeting and specific rewards.
  Cargo.lock
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/staking/Cargo.toml
  srml/staking/src/inflation.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
  srml/timestamp/src/lib.rs
Labels: A6-seemsok, B2-breaksapi

#3188 Expose instancing in metadata
  Cargo.lock
  node/runtime/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/runtime.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/Cargo.toml
  srml/support/test/tests/instance.rs
Labels: A0-pleasereview, B2-breaksapi, B3-breaksconsensus

#3195 wasm-builder: allow default cargo nightly
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  core/utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, M0-build

#3171 Use BABE instead of AuRa in node
  Cargo.lock
  core/cli/src/params.rs
  core/client/src/genesis.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/src/lib.rs
  core/consensus/rhd/src/lib.rs
  core/consensus/rhd/src/misbehaviour_check.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/keyring/src/lib.rs
  core/keyring/src/sr25519.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/test-client/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/utils/fork-tree/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
  srml/staking/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3194 Informant cleanup
  core/cli/src/informant.rs
  core/cli/src/informant/display.rs
Labels: A0-pleasereview

#3146 Switch consensus crates to new futures
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/error.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
  core/consensus/common/src/lib.rs
  core/consensus/slots/Cargo.toml
  core/consensus/slots/src/lib.rs
  core/consensus/slots/src/slots.rs
  core/network/src/service.rs
  core/service/src/chain_ops.rs
  node/cli/Cargo.toml
  node/cli/src/service.rs
Labels: A8-looksgood, B2-breaksapi

#3199 Really fix #2652 this time
  core/cli/src/informant/display.rs
Labels: A0-pleasereview

#3197 Include padding in heap size calculation
  core/executor/src/allocator.rs
Labels: A8-looksgood

#3200 Fixed spuriously failing on_demand test
  core/network/src/protocol/on_demand.rs
Labels: A8-looksgood

#3157 Weight annotation.
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/weights.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/runtime/src/constants.rs
  node/runtime/src/impls.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/sudo/src/lib.rs
  srml/support/src/dispatch.rs
  srml/support/src/lib.rs
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  subkey/src/main.rs
Labels: A0-pleasereview, B3-breaksconsensus

#3203 srml: staking: track session index of current era start
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3177 Handle local storage race conditions better
  core/executor/runtime-test/src/lib.rs
  core/executor/src/wasm_executor.rs
  core/offchain/src/api.rs
  core/offchain/src/testing.rs
  core/primitives/src/offchain.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/lib.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3210 Use milliseconds for timestamp resolution
  core/consensus/aura/src/lib.rs
  core/consensus/slots/src/slots.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3183 WIP: Subkey docker image
  .gitlab-ci.yml
  scripts/docker/subkey.Dockerfile
  scripts/docker/substrate.Dockerfile
Labels: A8-backport, B0-patchthis, M1-ci

#3159 Import queue steps
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/common/src/import_queue/buffered_link.rs
Labels: A8-looksgood

#3211 node: Update BABE protocol parameters
  node/cli/src/service.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3140 Upgrade dependencies in Cargo.lock
  Cargo.lock
Labels: A7-looksgoodcantmerge

#3215 Fixed debug flags
  .gitlab-ci.yml
Labels: A8-backport, B0-patchthis, M1-ci

#3218 Minor cleanup in native_executor.rs
  core/client/src/genesis.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/executor/src/native_executor.rs
  node/executor/src/lib.rs
Labels: A0-pleasereview

#3206 Clean up the basic-authorship crate
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/basic-authorship/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/src/lib.rs
  core/consensus/rhd/src/lib.rs
  core/consensus/slots/src/lib.rs
  core/network/src/service.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#3217 Staking need to get events
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#3224 Remove `IncrementalInput` and fix wasm `storage_into*`
  core/executor/src/wasm_executor.rs
  core/sr-io/src/lib.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/unhashed/mod.rs
Labels: A0-pleasereview

#3207 core/consensus,node/runtime: Declare and implement authorities endpoint
  Cargo.lock
  core/consensus/common/primitives/Cargo.toml
  core/consensus/common/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
Labels: A8-looksgood, M4-core

#3236 core/network: Fix bad import %s/runtime_primitives/sr_primitives/
  Cargo.lock
  core/consensus/common/primitives/Cargo.toml
  core/network/src/custom_proto/behaviour.rs
  core/network/src/custom_proto/handler.rs
  core/network/src/custom_proto/upgrade.rs
Labels: A0-pleasereview, M4-core, Q0-trivial

#3221 Add some documentation for the client
  core/client/src/lib.rs
Labels: A0-pleasereview

#3242 Fix master
  core/client/src/lib.rs
Labels: A2-insubstantial

#3233 Allow creating a ChainSpec from a Vec<u8>
  core/service/src/chain_spec.rs
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, B2-breaksapi

#3241 srml: babe: add expected block time and epoch duration constants
  core/consensus/babe/primitives/src/lib.rs
  core/test-runtime/src/lib.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3240 Properly stop block import on error
  core/service/src/chain_ops.rs
Labels: A5-grumble

#3252 Remove unused imports introduced in #3239.
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/factory_impl.rs
Labels: A2-insubstantial

#3246 Synchronize state cache on finalization
  Cargo.lock
  core/cli/src/informant.rs
  core/client/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/client.rs
  core/state-db/src/lib.rs
  core/test-client/src/client_ext.rs
Labels: A8-looksgood, M4-core

#3251 babe: Disable unused median calculation
  core/consensus/babe/src/lib.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3258 node: update flaming fir chain spec
  node/cli/res/flaming-fir.json
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core
