Repository paritytech/substrate, pull requests merged in 2019-01, with the labels that each got.

#1339 Support custom fork choice rule
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/lib.rs
  core/network/src/test/mod.rs
  core/test-client/src/client_ext.rs
Labels: A8-looksgood

#1349 Improve ondemand request dispatch
  core/network/src/on_demand.rs
Labels: A8-looksgood, M4-core

#1353 Small update to documentation of `construct_runtime!`
  srml/support/src/runtime.rs
Labels: A2-insubstantial

#1337 Fixed ancestry search/block queue interaction
  core/network/src/sync.rs
Labels: A0-pleasereview

#1341 fix bug for revert block command
  core/cli/src/lib.rs
  core/client/db/src/lib.rs
Labels: A8-looksgood, P2-asap

#1356 log on reorganization
  Cargo.lock
  core/cli/src/informant.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
Labels: A8-looksgood

#1162 Update SRML Council: prevent excess votes/computation
  srml/council/src/seats.rs
Labels: A8-looksgood

#1187 Use primitive-types crate to unify Parity Ethereum primitives
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/authority_id.rs
  core/primitives/src/bytes.rs
  core/primitives/src/hash.rs
  core/primitives/src/hexdisplay.rs
  core/primitives/src/lib.rs
  core/primitives/src/uint.rs
Labels: A8-looksgood

#1317 Decl_storage macro : force traits.
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/storage/generator.rs
Labels: A0-pleasereview

#1355 Invulnerabiity from slashing for certain validators
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A6-mustntgrumble

#1296 Make AuthorityId generic
  core/basic-authorship/src/basic_authorship.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/error.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/common/src/offline_tracker.rs
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/src/chain.rs
  core/network/src/test/mod.rs
  core/primitives/src/authority_id.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/lib.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  node/cli/src/chain_spec.rs
  node/primitives/src/lib.rs
  srml/aura/src/mock.rs
  srml/consensus/src/lib.rs
  srml/consensus/src/mock.rs
  srml/consensus/src/tests.rs
  srml/grandpa/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A8-looksgood

#1361 Updating parking_lot dependencies to 0.7.1
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/common/Cargo.toml
  core/consensus/rhd/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/telemetry/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/aura/Cargo.toml
Labels: A2-insubstantial

#1366 Expose all authorship APIs
  core/basic-authorship/src/lib.rs
Labels: A2-insubstantial

#1345 State cache and other performance optimizations
  Cargo.lock
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/backend.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/lib.rs
  core/client/src/light/backend.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/executor/src/lib.rs
  core/executor/src/native_executor.rs
  core/executor/src/wasm_executor.rs
  core/network/src/on_demand.rs
  core/rpc/src/lib.rs
  core/rpc/src/state/mod.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview, P2-asap

#1367 Bump jsonrpc to fix hang on exit
  Cargo.lock
  core/rpc/src/author/mod.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/state/mod.rs
Labels: A0-pleasereview, M6-rpcapi

#1370 Remove unneeded Deserialize impls.
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/rpc-servers/src/lib.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/lib.rs
  core/service/src/components.rs
  core/sr-primitives/src/generic/block.rs
  core/sr-primitives/src/generic/header.rs
  core/sr-primitives/src/traits.rs
Labels: A0-pleasereview, M6-rpcapi

#1369 Some documentation for ext_ functions in Substrate Runtime API
  core/sr-io/without_std.rs
Labels: A5-grumble

#1372 drew.tupletimestamp - Add tuple macro for timestamps too, break macro out into support
  srml/session/src/lib.rs
  srml/support/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A8-looksgood

#1362 expose peer information via rpc
  core/network-libp2p/src/lib.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/rpc-servers/src/lib.rs
  core/rpc/src/system/helpers.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
Labels: A8-looksgood

#1373 Cherry updates
  core/network/src/on_demand.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/res/charred-cherry.json
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview

#1278 Updated README.adoc
  README.adoc
Labels: A3-needsresolving

#1382 Escape dashes in shell commands
  README.adoc
Labels: A2-insubstantial, M3-docs

#1383 Update ring to 0.13 and subtle to 2.0
  Cargo.lock
  core/keystore/Cargo.toml
  core/keystore/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/primitives/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#1371 Improve offline slashing calculation
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A8-looksgood, B3-breaksconsensus, M4-core

#1385 Bump version to 0.10.0 in preparation for 1.0gamma
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial

#1387 informant: display finalized height and hash
  core/cli/src/informant.rs
Labels: A8-looksgood

#1388 Ensure opaque extr serialise is same as transparent
  core/sr-primitives/src/lib.rs
  node/primitives/src/lib.rs
Labels: A7-looksgoodtestsfail

#1389 Encode block number as hex
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/number.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/lib.rs
  core/sr-primitives/src/generic/header.rs
Labels: A6-mustntgrumble, M6-rpcapi

#1379 Move double map to support module and generalize it
  srml/contract/src/account_db.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/support/src/double_map.rs
  srml/support/src/lib.rs
Labels: A5-grumble

#1380 new state api state_getKeys to expose storage keys
  core/client/db/src/storage_cache.rs
  core/client/src/client.rs
  core/client/src/light/backend.rs
  core/rpc/src/state/mod.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
Labels: A4-awaitingci

#1397 Properly log sealing and the newly created proposal hash from aura
  core/basic-authorship/src/basic_authorship.rs
  core/consensus/aura/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#1398 Upgrade the rocksdb dependency to 0.11
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/network-libp2p/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#1402 Fix serialization of extrinsics.
  core/sr-primitives/src/lib.rs
  node/primitives/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#1409 Update links, labels and process in CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: A2-insubstantial, A8-looksgood, M3-docs

#1386 Update to latest libp2p
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/node_handler.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/swarm.rs
  core/network-libp2p/src/topology.rs
  core/network-libp2p/src/transport.rs
  core/network-libp2p/tests/test.rs
  core/network/src/service.rs
Labels: A8-looksgood, M4-core

#1420 Update wabt to to not require python dependency
  Cargo.lock
  core/executor/Cargo.toml
  core/sr-sandbox/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, M5-dependencies

#1429 Document how to build substrate on Windows (#1343)
  README.adoc
Labels: A2-insubstantial

#1452 set wasmi version 0.4.3 in Cargo.toml
  core/executor/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-sandbox/Cargo.toml
Labels: A2-insubstantial

#1436 Make use of NLL in client crate
  core/client/Cargo.toml
  core/client/src/backend.rs
  core/client/src/block_builder/api.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/blockchain.rs
  core/client/src/call_executor.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/genesis.rs
  core/client/src/in_mem.rs
  core/client/src/leaves.rs
  core/client/src/lib.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/light/mod.rs
  core/client/src/runtime_api.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1446 [CI] Publish rustdoc
  .gitlab-ci.yml
Labels: M3-docs

#1447 Update libp2p-kad and libp2p-secio
  Cargo.lock
  core/network-libp2p/src/behaviour.rs
Labels: A2-insubstantial

#1357 Remove warning for large buffer
  core/network-libp2p/src/custom_proto/upgrade.rs
Labels: A2-insubstantial

#1082 Use changes tries in query_storage RPC
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/network/src/protocol.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/lib.rs
Labels: A8-looksgood

#1358 Contracts module rejig
  Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/vm/prepare.rs
  srml/contract/src/wasm/code_cache.rs
  srml/contract/src/wasm/env_def/macros.rs
  srml/contract/src/wasm/env_def/mod.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
Labels: A0-pleasereview

#1468 Allow implementation to provide AppInfo to figure out default paths
  Cargo.lock
  core/cli/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
Labels: A3-inprogress

#1472 Enable debug assertions while building tests
  .gitlab-ci.yml
Labels: A2-insubstantial, M1-ci

#1469 mark GRANDPA and consensus stuff as unstable
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/lib.rs
Labels: A2-insubstantial

#1450 Some trivial externalities added
  srml/contract/src/exec.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A6-seemsok, M8-contracts

#1485 Fix Dockerfile
  Dockerfile
Labels: A2-insubstantial

#1477 Serialize generic extrinsics
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
Labels: A0-pleasereview, M4-core

#1478 Serialize digest logs as hex
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/traits.rs
Labels: A0-pleasereview, M6-rpcapi

#1476 Don't queue messages after shutdown
  core/network-libp2p/src/custom_proto/upgrade.rs
Labels: A0-pleasereview

#1486 Put back support for WebSockets in the transport
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/transport.rs
Labels: A0-pleasereview

#1490 remove unneeded iterator bound on ordered_trie_root
  core/trie/src/lib.rs
Labels: A0-pleasereview

#1410 Sync block justifications
  core/client/src/client.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/lib.rs
Labels: A8-looksgood, M4-core

#1479 Fix revert for non finalized blocks
  core/cli/src/lib.rs
  core/client/db/src/lib.rs
  core/service/src/chain_ops.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1504 Verify that contracts cannot use float operations
  srml/contract/src/wasm/prepare.rs
Labels: A0-pleasereview, A2-insubstantial, M8-contracts

#1302 Make runtime api calls native when possible
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/src/lib.rs
  core/executor/src/native_executor.rs
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/primitives/src/lib.rs
  core/rpc/src/state/mod.rs
  core/service/src/components.rs
  core/service/test/src/lib.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/benches/bench.rs
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/utils.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/lib.rs
  core/test-client/src/lib.rs
  core/test-client/src/trait_tests.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/src/api.rs
  core/transaction-pool/src/tests.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/lib.rs
Labels: A8-looksgood

#1500 Store identification info about the remote
  core/cli/src/lib.rs
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/traits.rs
  core/service/test/src/lib.rs
Labels: A7-looksgoodtestsfail

#1506 Fix wasm allocator
  Cargo.lock
  core/executor/Cargo.toml
  core/executor/src/heap.rs
  core/executor/src/lib.rs
  core/executor/src/wasm_executor.rs
  core/sr-io/without_std.rs
Labels: A8-looksgood

#1503 Remove `gas` function from the public API
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, M8-contracts

#1508 core: revert grandpa authorities unless imported blocked is queued
  core/finality-grandpa/src/lib.rs
Labels: A8-looksgood, M4-core

#1513 a wrapper network for rebroadcasting GRANDPA messages periodically
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview

#1512 Get rid of memcpy in to_vec()
  core/sr-io/without_std.rs
Labels: A8-looksgood

#1473 Dispatch Calls to other modules
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, M8-contracts

#1520 Switch trie dependency to released versions
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/state-machine/Cargo.toml
  core/trie/Cargo.toml
  node/executor/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#1499 compact param in calls
  core/executor/wasm/Cargo.lock
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
  srml/support/src/dispatch.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A3-inprogress

#1488 Rewrite Inherent data
  Cargo.lock
  Cargo.toml
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/basic-authorship/src/lib.rs
  core/client/Cargo.toml
  core/client/src/block_builder/api.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/client.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/aura/src/slots.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/error.rs
  core/consensus/common/src/lib.rs
  core/inherents/Cargo.toml
  core/inherents/src/lib.rs
  core/network/src/test/mod.rs
  core/service/src/chain_ops.rs
  core/service/src/components.rs
  core/service/src/error.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/test-client/src/block_builder_ext.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/trie/src/node_header.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/aura/Cargo.toml
  srml/aura/src/lib.rs
  srml/aura/src/mock.rs
  srml/consensus/Cargo.toml
  srml/consensus/src/lib.rs
  srml/consensus/src/mock.rs
  srml/consensus/src/tests.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/Cargo.toml
  srml/support/src/inherent.rs
  srml/support/src/lib.rs
  srml/support/src/runtime.rs
  srml/timestamp/Cargo.toml
  srml/timestamp/src/lib.rs
Labels: B2-breaksapi, B3-breaksconsensus

#1526 Make `impl_outer_inherent` do not require `Extrinsic` to be imported
  srml/support/src/inherent.rs
Labels: A2-insubstantial

#1532 Log the clogging networking messages
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#1455 Split execute_and_import_block in client into two functions
  core/client/src/client.rs
Labels: A3-inprogress, A3-needsresolving

#1530 core: fix grandpa authorities enacts_change
  core/finality-grandpa/src/authorities.rs
Labels: A8-looksgood, M4-core

#1521 Split BlockImport and JustificationImport
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, B2-breaksapi

#1533 log when it takes a while to import forks we need from GRANDPA
  core/finality-grandpa/src/until_imported.rs
Labels: A0-pleasereview

#1535 update primitive types minor version and solve breaking changes
  Cargo.lock
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/light.rs
  core/client/src/cht.rs
  core/client/src/notifications.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/tests.rs
  core/primitives/src/hash.rs
  core/rpc/src/chain/tests.rs
  core/sr-primitives/src/generic/digest.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/graph/src/pool.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/exec.rs
Labels: A0-pleasereview, B2-breaksapi

#1538 Reduce consensus gossip spam
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/network/src/consensus_gossip.rs
Labels: A0-pleasereview, M4-core

#1531 Add missing docs to sr-primitives
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/transaction_validity.rs
Labels: A2-insubstantial, M3-docs

#1543 Adds some derives for the inherent data stuff
  core/inherents/src/lib.rs
  node/runtime/src/lib.rs
Labels: A2-insubstantial

#1523 Fix warnings in substrate
  core/cli/src/error.rs
  core/client/src/error.rs
  core/executor/src/error.rs
  core/keystore/src/lib.rs
  core/network/src/error.rs
  core/primitives/src/lib.rs
  core/service/src/error.rs
  core/sr-io/without_std.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
Labels: A2-insubstantial

#1510 Update srml-contract to Rust 2018.
  core/sr-std/src/lib.rs
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/code_cache.rs
  srml/contract/src/wasm/env_def/macros.rs
  srml/contract/src/wasm/env_def/mod.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/prepare.rs
  srml/contract/src/wasm/runtime.rs
Labels: A0-pleasereview

#1548 Migrate consensus (common, aura-primitives, aura, rhd) to 2018 edition
  core/consensus/aura/Cargo.toml
  core/consensus/aura/primitives/Cargo.toml
  core/consensus/aura/primitives/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/aura/src/slots.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/error.rs
  core/consensus/common/src/evaluation.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/rhd/Cargo.toml
  core/consensus/rhd/src/error.rs
  core/consensus/rhd/src/lib.rs
Labels: A8-looksgood

#1489 Atomic operation and locking when importing a block
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
Labels: A0-pleasereview

#1524 Optimize transaction pool pruning
  core/service/src/components.rs
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/graph/src/rotator.rs
  core/transaction-pool/src/tests.rs
Labels: A0-pleasereview, M4-core

#1544 Test syncing to all forks
  core/client/src/in_mem.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#1549 Remove TODO comment about unboxing state_machine error
  core/client/src/error.rs
Labels: A2-insubstantial

#1557 core: fix transaction-pool tests
  core/transaction-pool/graph/src/pool.rs
Labels: A0-pleasereview, A2-insubstantial

#1561 Fix inconsistency between `CheckInherentsResult::new()/default()`
  core/inherents/src/lib.rs
Labels: A2-insubstantial

#1562 Refactor `transfer()` logic outside of dispatched function #1555
  srml/balances/src/lib.rs
Labels: A0-pleasereview

#1551 Report the average network bandwidth
  Cargo.lock
  core/cli/src/informant.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/transport.rs
  core/network-libp2p/src/transport/bandwidth.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#1554 core: grandpa limits votes to 3/4 of the unfinalized chain
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, M4-core

#1368 Refactor CLI handling
  Cargo.lock
  README.adoc
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/cli/src/traits.rs
  core/network-libp2p/src/secret.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/config.rs
  node/cli/Cargo.toml
  node/cli/build.rs
  node/cli/src/lib.rs
  node/cli/src/params.rs
Labels: A0-pleasereview

#1565 Aura: Remove unused structures and adds `SlotDuration::get()`
  core/consensus/aura/primitives/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview, A2-insubstantial

#1527 Update dependencies
  Cargo.lock
  Cargo.toml
  build.rs
  core/cli/Cargo.toml
  core/client/db/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/keystore/Cargo.toml
  core/keystore/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/network/Cargo.toml
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
  core/network/src/test/sync.rs
  core/primitives/Cargo.toml
  core/service/test/Cargo.toml
  core/service/test/src/lib.rs
  core/state-db/Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/trie/Cargo.toml
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  subkey/Cargo.toml
  subkey/src/main.rs
  subkey/src/vanity.rs
Labels: A8-looksgood

#1559 don't panic in best_containing
  core/client/src/client.rs
Labels: A8-looksgood

#1563 core: send justification requests in parallel to block requests
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
Labels: A6-seemsok, M4-core

#1583 Additional externs for ecdsa recovery and keccak
  Cargo.lock
  core/executor/Cargo.toml
  core/executor/src/lib.rs
  core/executor/src/wasm_executor.rs
  core/sr-io/Cargo.toml
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/wasm/mod.rs
  srml/staking/src/lib.rs
Labels: A8-looksgood

#1586 Only request justifications from available peers
  core/network/src/sync.rs
Labels: A8-looksgood

#1598 set link-arg --export-table for wasm builds
  Cargo.lock
  core/executor/wasm/Cargo.lock
  core/executor/wasm/build.sh
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/build.sh
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/build.sh
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1593 GRANDPA: announce blocks we vote on to peers
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
Labels: A0-pleasereview, B0-patchthis

#1601 Fixed multiple blocks finalization
  core/client/db/src/lib.rs
Labels: A8-looksgood, M4-core

#1604 Download unknown but announced forks
  core/finality-grandpa/src/communication.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#1596 Fix generate node name with less then 32 characters
  core/cli/src/lib.rs
Labels: A8-looksgood

#1611 Migrate tx-graph, tx-pool and trie to the 2018 edition
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/error.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/lib.rs
  core/transaction-pool/graph/src/listener.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/graph/src/rotator.rs
  core/transaction-pool/graph/src/watcher.rs
  core/transaction-pool/src/api.rs
  core/transaction-pool/src/error.rs
  core/transaction-pool/src/lib.rs
  core/trie/Cargo.toml
  core/trie/benches/bench.rs
  core/trie/src/lib.rs
  core/trie/src/node_codec.rs
Labels: A0-pleasereview

#1589 Migrate node (cli, executor, primitives and runtime) to the 2018 edition
  node/cli/Cargo.toml
  node/cli/build.rs
  node/cli/src/chain_spec.rs
  node/cli/src/error.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.toml
  node/runtime/wasm/src/lib.rs
Labels: A0-pleasereview

#1534 Allow runtime to return transaction validation error codes
  core/client/db/src/lib.rs
  core/sr-primitives/src/transaction_validity.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/graph/src/error.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/src/tests.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
Labels: A8-looksgood, B2-breaksapi, B3-breaksconsensus, M4-core

#1595 Fix consensus error between wasm and native
  core/executor/src/heap.rs
  core/executor/src/lib.rs
  core/executor/src/wasm_executor.rs
Labels: A8-looksgood

#1621 Fixed aux modifications on light client
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
Labels: A0-pleasereview

#1620 Make --port CLI option work again
  core/network-libp2p/src/traits.rs
Labels: A0-pleasereview

#1623 Migrate state-db, state-machine, telemetry, test-client and test-runtime to the 2018 edition
  core/state-db/Cargo.toml
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/pruning.rs
  core/state-db/src/test.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/backend.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/input.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  core/test-client/Cargo.toml
  core/test-client/src/block_builder_ext.rs
  core/test-client/src/lib.rs
  core/test-client/src/trait_tests.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.toml
  core/test-runtime/wasm/src/lib.rs
Labels: A0-pleasereview

#1616 Transactional updates in the state-db
  core/client/db/src/lib.rs
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/pruning.rs
  core/state-db/src/test.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood, B9-blocker, F0-consensus, F1-panic, P0-dropeverything

#1428 Merge metadata by module
  Cargo.lock
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/metadata/src/lib.rs
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/runtime.rs
  srml/support/src/storage/generator.rs
Labels: A8-looksgood, B2-breaksapi, M6-rpcapi

#1628 Print the local node address again
  core/network-libp2p/src/service_task.rs
Labels: A8-looksgood

#1629 Backport #1628
  core/network-libp2p/src/service_task.rs
Labels: A8-backport

#1626 [backport] Transactional updates in the state-db (#1616)
  Cargo.lock
  core/client/db/src/lib.rs
  core/executor/wasm/Cargo.lock
  core/executor/wasm/build.sh
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/pruning.rs
  core/state-db/src/test.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/build.sh
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/build.sh
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-backport

#1627 Update the date
  node/cli/src/lib.rs
Labels: A2-insubstantial

#1613 update rhododendron trie-bench for parity-codec 3.0
  Cargo.lock
  core/consensus/rhd/Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/trie/Cargo.toml
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview

#1625 Support edition 2018 for storage_items macro
  srml/support/src/storage/generator.rs
Labels: A0-pleasereview, A2-insubstantial

#1591 Declare storage in contracts module
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood, B3-breaksconsensus

#1636 Check for disposed blocks when creating a state.
  Cargo.lock
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
  core/state-db/src/pruning.rs
Labels: A8-looksgood, M4-core

#1624 Transaction signing payload is hashed first
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview, B1-releasenotes, B2-breaksapi, B3-breaksconsensus

#1644 Fix minor error in chain-spec generation command in readme
  README.adoc
Labels: A2-insubstantial
