Repository paritytech/substrate, pull requests merged in 2019-02, with the labels that each got.

#1581 Allow both consensus and runtime to limit block building
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/block_builder/block_builder.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/evaluation.rs
  core/consensus/common/src/lib.rs
  core/primitives/src/storage.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/system/src/lib.rs
Labels: A8-looksgood, B3-breaksconsensus, M4-core

#1657 Fixed state-db block insertion
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
Labels: A8-looksgood

#1647 grandpa: consistent argument ordering in rebroadcast vs. network
  core/finality-grandpa/src/communication.rs
Labels: A8-looksgood, B0-patchthis

#1655 Stop authoring blocks when offline
  core/client/db/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/rpc/src/system/tests.rs
Labels: A8-looksgood, B0-patchthis

#1658 Reduce consensus spam
  Cargo.lock
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#1659 Don't panic if parameter can not be converted between node and native runtime
  Cargo.lock
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/executor/src/error.rs
  core/executor/src/native_executor.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/benches/bench.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/src/utils.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/state-machine/src/lib.rs
  core/test-client/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1660 Chore: fix Telemetry link
  README.adoc
Labels: A2-insubstantial

#1662 Intro and add an intro link to README
  README.adoc
Labels: A2-insubstantial

#1661 Add links to the README for further info
  README.adoc
Labels: A2-insubstantial

#1663 Migrate srml-support to the 2018 edition
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/support/src/double_map.rs
  srml/support/src/event.rs
  srml/support/src/hashable.rs
  srml/support/src/inherent.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
  srml/support/src/storage/mod.rs
Labels: A0-pleasereview

#1667 Fixed panic handling
  Cargo.lock
  Cargo.toml
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/executor/Cargo.toml
  core/executor/src/native_executor.rs
  core/panic-handler/Cargo.toml
  core/panic-handler/src/lib.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/ext.rs
  node/src/main.rs
Labels: A8-looksgood, B0-patchthis

#1656 Replace allocator with freeing-bump allocator
  Cargo.lock
  core/executor/Cargo.toml
  core/executor/src/allocator.rs
  core/executor/src/heap.rs
  core/executor/src/lib.rs
  core/executor/src/wasm_executor.rs
Labels: A0-pleasereview

#1675 Split substrate-finality-grandpa
  core/finality-grandpa/src/consensus_changes.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
Labels: A8-looksgood, M4-core

#1679 Convert to jsonrpc-derive, use jsonrpc-* from crates.io
  Cargo.lock
  core/rpc-servers/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/helpers.rs
  core/rpc/src/lib.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
  core/rpc/src/subscriptions.rs
  core/rpc/src/system/mod.rs
Labels: A8-looksgood, M6-rpcapi

#1612 add test for wasm runtime changes
  .gitlab-ci.yml
  scripts/gitlab/check_runtime.sh
Labels: A3-inprogress

#1666 Rename and use --max-heap-pages parameter
  core/cli/src/params.rs
  core/client/src/genesis.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/executor/src/native_executor.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/test-client/src/lib.rs
  node/executor/src/lib.rs
Labels: A0-pleasereview

#1689 Update to latest jsonrpc-derive: fixes aliases
  Cargo.lock
  core/rpc/Cargo.toml
Labels: A2-insubstantial

#1691 Lower log level of grandpa until_imported message
  core/finality-grandpa/src/until_imported.rs
  core/network/src/consensus_gossip.rs
Labels: A0-pleasereview, A2-insubstantial

#1682 Move `CODE` directly into `TestExternalities`
  core/state-machine/src/testing.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A3-needsresolving, A8-looksgood

#1665 Offline/Slashing improvements
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/aura/src/lib.rs
  srml/aura/src/tests.rs
  srml/staking/src/lib.rs
Labels: A7-looksgoodcantmerge

#1690 Add OnInitialise handler.
  core/sr-primitives/src/traits.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A0-pleasereview

#1106 Support multi-hash in multi-trie via PlainDB
  Cargo.lock
  Cargo.toml
  core/executor/wasm/Cargo.lock
  core/executor/wasm/Cargo.toml
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-runtime/Cargo.toml
  core/trie/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
Labels: A0-pleasereview

#1697 Make API backwards compatible with CC
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/client/Cargo.toml
  core/client/src/block_builder/api.rs
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/rpc/src/state/tests.rs
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/src/utils.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-version/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A7-looksgoodtestsfail

#1340 Rewrite network protocol/service to use channels
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/traits.rs
  core/network/Cargo.toml
  core/network/src/io.rs
  core/network/src/lib.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A3-inprogress

#1704 Update trie to v0.11
  Cargo.lock
  Cargo.toml
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/executor/wasm/Cargo.toml
  core/executor/wasm/build.sh
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/build.sh
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/trie/Cargo.toml
  node/executor/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.toml
  node/runtime/wasm/build.sh
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  test-utils/chain-spec-builder/Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#1705 Indices maintenance
  srml/indices/Cargo.toml
  srml/indices/src/address.rs
  srml/indices/src/lib.rs
  srml/indices/src/mock.rs
  srml/indices/src/tests.rs
Labels: A0-pleasereview

#1634 Update libp2p to v0.3
  Cargo.lock
  core/keystore/Cargo.toml
  core/keystore/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/topology.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/primitives/Cargo.toml
  core/primitives/src/ed25519.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview

#1637 Moves `node-template` into substrate repo
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  core/consensus/aura/primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/Cargo.toml
  node-template/LICENSE
  node-template/README.md
  node-template/build.rs
  node-template/build.sh
  node-template/init.sh
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.toml
  node-template/runtime/wasm/build.sh
  node-template/runtime/wasm/src/lib.rs
  node-template/src/chain_spec.rs
  node-template/src/cli.rs
  node-template/src/error.rs
  node-template/src/main.rs
  node-template/src/service.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  scripts/common.sh
  scripts/node-template-release.sh
  scripts/node-template-release/Cargo.toml
  scripts/node-template-release/src/main.rs
  srml/support/Cargo.toml
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/origin.rs
  srml/support/src/runtime.rs
Labels: A8-looksgood

#1695 Reference counted uncanonicalised overlay
  core/state-db/src/noncanonical.rs
Labels: A8-looksgood

#1711 Export `TERM` in `node-template-release.sh`
  scripts/node-template-release.sh
Labels: A2-insubstantial

#1676 Limit transaction pool size
  Cargo.lock
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/lib.rs
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/error.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/graph/src/rotator.rs
  core/transaction-pool/src/api.rs
  core/transaction-pool/src/tests.rs
Labels: A0-pleasereview, M4-core

#1694 Migrate sr-primitives, sr-sandbox, sr-std and sr-version to the 2018 edition.
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/generic/block.rs
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/generic/era.rs
  core/sr-primitives/src/generic/header.rs
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/tests.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/transaction_validity.rs
  core/sr-sandbox/Cargo.toml
  core/sr-sandbox/build.rs
  core/sr-sandbox/src/lib.rs
  core/sr-sandbox/with_std.rs
  core/sr-std/Cargo.toml
  core/sr-std/build.rs
  core/sr-std/src/lib.rs
  core/sr-version/Cargo.toml
  core/sr-version/src/lib.rs
Labels: A0-pleasereview

#1710 Migrate network, primitives and rpc to the 2018 edition
  core/basic-authorship/src/basic_authorship.rs
  core/executor/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/network/Cargo.toml
  core/network/src/blocks.rs
  core/network/src/config.rs
  core/network/src/consensus_gossip.rs
  core/network/src/error.rs
  core/network/src/lib.rs
  core/network/src/message.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/specialization.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/primitives/Cargo.toml
  core/primitives/src/authority_id.rs
  core/primitives/src/changes_trie.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/hasher.rs
  core/primitives/src/lib.rs
  core/primitives/src/sandbox.rs
  core/primitives/src/storage.rs
  core/primitives/src/uint.rs
  core/rpc/Cargo.toml
  core/rpc/src/author/error.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/chain/error.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/number.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/errors.rs
  core/rpc/src/lib.rs
  core/rpc/src/metadata.rs
  core/rpc/src/state/error.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
  core/rpc/src/subscriptions.rs
  core/rpc/src/system/error.rs
  core/rpc/src/system/tests.rs
Labels: A0-pleasereview

#1713 core: network: fix sync on testing network
  core/network/src/test/mod.rs
Labels: A0-pleasereview, M4-core

#1630 Expose block random seed and timestamp to contract ABI
  Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/COMPLEXITY.md
  srml/contract/Cargo.toml
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
Labels: A8-looksgood, B3-breaksconsensus

#1714 Check for block parent before verification.
  core/client/src/client.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/import.rs
  core/network/src/protocol.rs
  core/network/src/test/block_import.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview

#1720 Update libp2p-core to 0.3.4
  Cargo.lock
Labels: A2-insubstantial

#1718 Protect against flood of addresses
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/topology.rs
Labels: A0-pleasereview

#1719 Protect against flood of addresses
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/light.rs
  core/client/src/cht.rs
  core/client/src/notifications.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/tests.rs
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/topology.rs
  core/primitives/src/hash.rs
  core/rpc/src/chain/tests.rs
  core/sr-primitives/src/generic/digest.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/graph/src/pool.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/exec.rs
Labels: A8-backport

#1724 Backport #1723
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-backport

#1723 Fix panic in custom protocol handler
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview

#1729 Fix block justification response handling
  core/network/src/sync.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#1727 CI: label a pull request breaksapi if there are changes on the wasm source code but no changes to the spec_version
  .gitlab-ci.yml
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview

#1732 Migrate rpc-servers, serializer, service and sr-io to the 2018 edition
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/informant.rs
  core/client/Cargo.toml
  core/client/src/client.rs
  core/client/src/light/backend.rs
  core/primitives/src/lib.rs
  core/rpc-servers/Cargo.toml
  core/rpc-servers/src/lib.rs
  core/serializer/Cargo.toml
  core/serializer/src/lib.rs
  core/service/Cargo.toml
  core/service/src/chain_ops.rs
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/error.rs
  core/service/src/lib.rs
  core/service/test/Cargo.toml
  core/service/test/src/lib.rs
  core/sr-io/Cargo.toml
  core/sr-io/build.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/telemetry/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1739 Remove warning about empty list of identify addresses
  core/network-libp2p/src/behaviour.rs
Labels: A2-insubstantial

#1737 Update substrate-cli & node-template deps
  Cargo.lock
  core/cli/Cargo.toml
  node-template/Cargo.toml
Labels: A2-insubstantial

#1742 Fix issues related to Rust 2018, Macros, and node-template
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
Labels: A0-pleasereview

#1740 Fixed a bunch of warnings
  core/primitives/src/lib.rs
  core/sr-primitives/src/lib.rs
  srml/council/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/src/lib.rs
  srml/sudo/src/lib.rs
  srml/upgrade-key/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi

#1641 decouple balances from some modules
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/council/src/lib.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/event.rs
  srml/support/src/lib.rs
  srml/support/src/traits.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#1751 Reduce the spam from network misbehaviours
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-backport

#1743 CI: check spec_version and impl_version for changes
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview

#1725 Migrate smrl-treasury and srml-upgrade-key to the 2018 edition
  Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/aura/src/lib.rs
  srml/aura/src/mock.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/consensus/Cargo.toml
  srml/consensus/src/lib.rs
  srml/consensus/src/mock.rs
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/code_cache.rs
  srml/contract/src/wasm/mod.rs
  srml/contract/src/wasm/runtime.rs
  srml/support/procedural/Cargo.toml
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/Cargo.toml
  srml/support/procedural/tools/derive/Cargo.toml
  srml/support/procedural/tools/derive/src/lib.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/lib.rs
  srml/treasury/Cargo.toml
  srml/treasury/src/lib.rs
  srml/upgrade-key/Cargo.toml
  srml/upgrade-key/src/lib.rs
Labels: A8-looksgood

#1717 Unify bad signature error
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
Labels: A2-insubstantial, A3-needsresolving, A7-looksgoodcantmerge, B2-breaksapi, M4-core

#1726 Vesting schedules.
  Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node-template/src/chain_spec.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/Cargo.toml
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/staking/src/mock.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood

#1684 Replace unwrap with expect
  core/executor/src/allocator.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  core/executor/src/wasm_utils.rs
  core/executor/wasm/src/lib.rs
Labels: A8-looksgood

#1750 Reduce the spam from network misbehaviours
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview, B0-patchthis

#1754 grandpa: fix reimport of change blocks
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#1755 Migrate srml crates to the 2018 edition
  Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/Cargo.toml
  srml/council/src/lib.rs
  srml/council/src/motions.rs
  srml/council/src/seats.rs
  srml/council/src/voting.rs
  srml/democracy/Cargo.toml
  srml/democracy/src/lib.rs
  srml/democracy/src/vote_threshold.rs
  srml/example/Cargo.toml
  srml/example/src/lib.rs
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/grandpa/Cargo.toml
  srml/grandpa/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/grandpa/src/tests.rs
  srml/indices/src/lib.rs
  srml/indices/src/mock.rs
  srml/metadata/Cargo.toml
  srml/metadata/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/staking/Cargo.toml
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/sudo/Cargo.toml
  srml/sudo/src/lib.rs
  srml/system/Cargo.toml
  srml/system/src/lib.rs
  srml/timestamp/Cargo.toml
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1721 Make the discovery test more strict
  core/network-libp2p/tests/test.rs
Labels: A4-gotissues

#1757 Make `sr-api-macros` and `srml-support` renaming of crates
  Cargo.lock
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/src/utils.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/Cargo.toml
  srml/support/procedural/tools/src/lib.rs
Labels: A0-pleasereview

#1546 Adds new execution strategy nativeElseWasm
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/db/src/lib.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/lib.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/mod.rs
  core/client/src/runtime_api.rs
  core/finality-grandpa/src/tests.rs
  core/rpc/Cargo.toml
  core/rpc/src/state/mod.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-primitives/src/lib.rs
  core/state-machine/src/lib.rs
  core/test-client/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A3-needsresolving, A5-grumble

#1759 Fix infinite loop in reserved mode
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview, B0-patchthis

#1760 Backport #1759
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A8-backport

#1761 Add Proposed event
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/democracy/src/lib.rs
Labels: A0-pleasereview

#1767 Set `initialised_block` if we called `initialise_block`
  Cargo.lock
  core/client/src/call_executor.rs
Labels: A0-pleasereview

#1765 Remove wait on future in network bridge
  core/finality-grandpa/src/lib.rs
Labels: A0-pleasereview

#1600 Add standalone set head operations
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
Labels: A0-pleasereview

#1769 Add debug name in node infos
  core/network-libp2p/src/service_task.rs
Labels: A8-looksgood

#1763 EnumerableStorageMap
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/service/src/chain_spec.rs
  core/sr-primitives/src/lib.rs
  core/test-client/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/consensus/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/indices/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/lib.rs
  srml/support/src/storage/generator.rs
  srml/support/src/storage/mod.rs
  srml/system/src/lib.rs
Labels: A5-grumble, B2-breaksapi, M4-core

#1730 Introduce Ristretto signing
  Cargo.lock
  core/executor/src/wasm_executor.rs
  core/executor/wasm/src/lib.rs
  core/keyring/src/ed25519.rs
  core/keyring/src/lib.rs
  core/keyring/src/sr25519.rs
  core/primitives/Cargo.toml
  core/primitives/src/lib.rs
  core/primitives/src/sr25519.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A9-buythatmanabeer, B2-breaksapi

#1771 Backport #1769
  core/network-libp2p/src/service_task.rs
  core/network/src/io.rs
Labels: A8-backport

#1758 Migrate everything to the 2018 edition
  Cargo.lock
  Cargo.toml
  build.rs
  core/client/Cargo.toml
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/leaves.rs
  core/client/src/lib.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/slots/Cargo.toml
  core/consensus/aura/slots/src/lib.rs
  core/consensus/rhd/Cargo.toml
  core/consensus/rhd/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/benches/bench.rs
  core/sr-api-macros/src/compile_fail_tests.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/sr-version/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/src/cli.rs
  node-template/src/main.rs
  node-template/src/service.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  node/src/main.rs
Labels: A8-looksgood, B2-breaksapi

#1764 Add more naunce to the runtime CI agent
  scripts/gitlab/check_runtime.sh
Labels: A2-insubstantial, A8-looksgood

#1780 core: grandpa: collect garbage for topic
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#1784 core: cli: log milliseconds when debug/trace enabled
  core/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#1770 Added demo module to show explicit imports of macros
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
Labels: A3-inprogress

#1786 Adding vesting tests to Balances module
  node/runtime/src/lib.rs
  scripts/gitlab/check_runtime.sh
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
Labels: A0-pleasereview

#1802 Ensure config directory exists.
  core/network-libp2p/src/secret.rs
Labels: A8-looksgood

#1779 Use DB backend in test client
  Cargo.lock
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/client.rs
  core/network/src/test/sync.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/test-client/Cargo.toml
  core/test-client/src/lib.rs
Labels: A0-pleasereview

#1752 Ci wasm builds
  .gitlab-ci.yml
  scripts/gitlab/check_merge_conflict.sh
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview

#1807 Fix --import-blocks
  core/service/src/chain_ops.rs
Labels: A0-pleasereview

#1797 Migrate finality-grandpa to the 2018 edition
  Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/primitives/Cargo.toml
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/consensus_changes.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/service_integration.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood

#1812 allow build:rust:doc:release job to fail
  .gitlab-ci.yml
Labels: A2-insubstantial

#1327 Rewrite the BasiQueue using channels
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/chain_ops.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A8-looksgood

#1809 Fix linked map for trait types and Option
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/example/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/lib.rs
  srml/support/src/storage/generator.rs
  srml/support/src/storage/mod.rs
Labels: A0-pleasereview, M4-core

#1821 Improve fees module
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/contract/src/tests.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/fees/src/lib.rs
  srml/fees/src/mock.rs
  srml/staking/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/syn_ext.rs
  srml/support/src/traits.rs
  srml/treasury/src/lib.rs
Labels: A6-mustntgrumble, B2-breaksapi

#1826 Small refactoring of `network::protocol` module.
  core/network/src/protocol.rs
Labels: A8-looksgood

#1808 Import multiple authority set change blocks
  Cargo.lock
  Cargo.toml
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/Cargo.toml
  core/network/src/chain.rs
  core/network/src/protocol.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/util/fork-tree/Cargo.toml
  core/util/fork-tree/src/lib.rs
Labels: A8-looksgood, M4-core

#1811 Gossip refactoring
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, B4-breaksauthoring, B8-breakseverything

#1834 Fixed sending commit message
  core/finality-grandpa/src/communication.rs
Labels: A0-pleasereview

#1828 Fix #1825
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#1838 Fix contruct runtime macro
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/runtime.rs
Labels: A0-pleasereview

#1836 Update to libp2p v0.4
  Cargo.lock
  core/cli/src/lib.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/src/lib.rs
Labels: A0-pleasereview

#1813 SRML staking: remove 'default-features = false' from balances dev-dependency
  srml/assets/Cargo.toml
  srml/aura/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/grandpa/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/sudo/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
Labels: A6-seemsok

#1837 Fixed finalizing multiple blocks at once
  core/state-db/src/pruning.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#1847 Use BandwidthLogging struct from libp2p
  core/network-libp2p/src/transport.rs
  core/network-libp2p/src/transport/bandwidth.rs
Labels: A0-pleasereview

#1842 Limit the set of known extrinsics and blocks.
  Cargo.lock
  core/network/Cargo.toml
  core/network/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/util.rs
Labels: A0-pleasereview

#1804 Let StorageDoubleMap use borrowed key types
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/account_db.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/support/src/double_map.rs
Labels: A3-needsresolving, A4-gotissues, A8-looksgood

#1843 Add back logging when we ban a peer
  core/network/src/service.rs
Labels: A2-insubstantial

#1844 Refactor state machine to avoid repetitions
  core/client/src/call_executor.rs
  core/client/src/genesis.rs
  core/state-machine/src/lib.rs
Labels: A8-looksgood, M4-core

#1849 fix construct runtime module position bug
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/runtime.rs
Labels: A0-pleasereview

#1796 Split Substrate messages into multiple substreams
  Cargo.lock
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/topology.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/tests/test.rs
  core/network/src/message.rs
Labels: A3-inprogress

#1852 Remove blocking operations in SyncOracle implementation
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A8-looksgood

#1866 Add names to tokio threads
  core/network/src/service.rs
  node/cli/src/lib.rs
Labels: A8-looksgood

#1863 replace some encode by using_encoded
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/src/lib.rs
  srml/support/src/double_map.rs
Labels: A0-pleasereview

#1871 Prune leaves on finality
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/leaves.rs
  core/client/src/lib.rs
Labels: A0-pleasereview

#1874 Use bounded channels for network -> sync -> import
  core/consensus/common/src/import_queue.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A8-looksgood

#1879 backport some PRs to 0.10
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/state-db/src/pruning.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview, A8-backport

#1854 ci: add kubernetes helm chart and gcp deployment
  .gitlab-ci.yml
  scripts/gitlab/check_merge_conflict.sh
  scripts/gitlab/check_runtime.sh
  scripts/kubernetes/Chart.yaml
  scripts/kubernetes/README.md
  scripts/kubernetes/templates/poddisruptionbudget.yaml
  scripts/kubernetes/templates/secrets.yaml
  scripts/kubernetes/templates/service.yaml
  scripts/kubernetes/templates/serviceaccount.yaml
  scripts/kubernetes/templates/statefulset.yaml
  scripts/kubernetes/values.yaml
Labels: A0-pleasereview, A2-insubstantial

#1857 Add connected peers to protocol, use in sync provider
  core/network-libp2p/src/service_task.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
Labels: A8-looksgood

#1889 Backport: Prune leaves on finality (#1871)
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/leaves.rs
  core/client/src/lib.rs
Labels: A8-backport

#1888 CI: kubernetes deployment: fix VERSION transport between stages
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial

#1887 fix construct_runtime! macro error when no event
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/event.rs
Labels: A0-pleasereview

#1818 Remove blocking sync -> import-queue operations
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/mod.rs
Labels: A5-grumble

#1886 Telemetry improvements
  Cargo.lock
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/src/client.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/lib.rs
  core/service/src/chain_spec.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  node/cli/Cargo.toml
  node/cli/res/dried-danta.json
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview

#1898 Fixed instant finalization of genesis block on light client
  core/client/db/src/light.rs
Labels: A8-looksgood, B0-patchthis

#1894 Backport of gossip improvements to v0.10
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/test/mod.rs
Labels: A1-onice, A8-backport

#1884 Add an RPC request for the state of the network
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/topology.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/lib.rs
  core/network/src/service.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
Labels: A7-looksgoodcantmerge, M6-rpcapi

#1892 Some gossip improvements
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview, B0-patchthis

#1903 Some backports from master
  Cargo.lock
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/db/src/light.rs
  core/client/src/client.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/test/mod.rs
  core/service/src/chain_spec.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
Labels: A8-backport
