Repository paritytech/substrate, pull requests merged in 2019-10, with the labels that each got.

#3729 srml: system: add kill_prefix
  node/runtime/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3650 Prepare for asynchronous transaction validation in tx pool
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/basic-authorship/src/lib.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/rpc/api/src/author/error.rs
  core/rpc/api/src/author/mod.rs
  core/rpc/api/src/lib.rs
  core/rpc/api/src/subscriptions.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/service/src/builder.rs
  core/service/src/lib.rs
  core/service/test/Cargo.toml
  core/service/test/src/lib.rs
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/src/lib.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/validated_pool.rs
  core/transaction-pool/src/api.rs
  core/transaction-pool/src/lib.rs
  core/transaction-pool/src/tests.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/rpc/Cargo.toml
  node/rpc/src/accounts.rs
Labels: A7-looksgoodtestsfail, M4-core, M6-rpcapi

#3698 srml/authority-discovery: Abstract session key type
  Cargo.lock
  node/runtime/src/lib.rs
  srml/authority-discovery/Cargo.toml
  srml/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3732 Let `construct_runtime!` generate `ALL_MODULES` as nested tuples
  srml/sudo/src/lib.rs
  srml/support/src/runtime.rs
Labels: A0-pleasereview

#3735 grandpa: add identifier to UntilImported logging message
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/until_imported.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3676 Use EncodeLike for storages traits
  Cargo.lock
  core/primitives/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/babe/src/lib.rs
  srml/collective/src/lib.rs
  srml/contracts/src/wasm/code_cache.rs
  srml/democracy/src/lib.rs
  srml/elections-phragmen/src/lib.rs
  srml/elections/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/im-online/src/lib.rs
  srml/scored-pool/src/lib.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
  srml/support/src/lib.rs
  srml/support/src/storage/child.rs
  srml/support/src/storage/generator/double_map.rs
  srml/support/src/storage/generator/linked_map.rs
  srml/support/src/storage/generator/map.rs
  srml/support/src/storage/generator/value.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
  srml/support/src/storage/unhashed.rs
  srml/support/src/traits.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/genesisconfig.rs
  srml/support/test/tests/instance.rs
  srml/support/test/tests/system.rs
Labels: A0-pleasereview

#3733 Move offchain worker http helpers to `sr-primitives`.
  Cargo.lock
  core/sr-io/Cargo.toml
  core/sr-io/src/lib.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/offchain/http.rs
  core/sr-primitives/src/offchain/mod.rs
Labels: A2-insubstantial, M4-core

#3736 Fix quantization from OnDilution in treasury
  node/runtime/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#3658 BABE refactoring: split out verification
  core/consensus/babe/src/authorship.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/babe/src/verification.rs
Labels: A5-grumble

#3665 Optimize tree route to sync faster
  Cargo.lock
  Cargo.toml
  core/cli/Cargo.toml
  core/cli/src/informant.rs
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/header-metadata/Cargo.toml
  core/client/header-metadata/src/lib.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/blockchain.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/src/epoch_changes.rs
  core/consensus/babe/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/environment.rs
  core/network/Cargo.toml
  core/network/src/chain.rs
  core/test-runtime/client/src/lib.rs
Labels: A8-looksgood

#3744 Update README.adoc
  README.adoc
Labels: A2-insubstantial, M3-docs

#3617 Cumulative fixes to make working with consensus-pow easier
  Cargo.lock
  core/consensus/pow/primitives/Cargo.toml
  core/consensus/pow/primitives/src/lib.rs
  core/consensus/pow/src/lib.rs
  core/network/src/chain.rs
Labels: A0-pleasereview

#3740 Split off TypeId so as not to pull in sr-io
  core/primitives/src/lib.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
Labels: A2-insubstantial

#3754 Minor typo in PoW comment
  core/consensus/pow/src/lib.rs
Labels: A2-insubstantial

#3760 decouple BABE from session
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
  srml/babe/src/mock.rs
Labels: A0-pleasereview, B2-breaksapi

#3759 Utility module for doing stuff like batch calls
  Cargo.lock
  Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/utility/Cargo.toml
  srml/utility/src/lib.rs
Labels: B2-breaksapi

#3746 babe: ancient epoch tree pruning
  core/consensus/babe/src/epoch_changes.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#3764 babe: small compilation fix
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3756 Use header metadata in babe verify.
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/in_mem.rs
  core/consensus/babe/src/lib.rs
Labels: A8-looksgood

#3768 babe: prune the epoch tree on startup
  core/consensus/babe/src/lib.rs
Labels: A0-pleasereview, M4-core

#3766 srml-utility: Store errors as `DispatchError` to make the decodable
  node/runtime/src/lib.rs
  srml/utility/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3772 Make the purge-chain prompt a little nicer
  core/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3626 Fix state RPC subscriptions on light node
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/api/src/subscriptions.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/state_full.rs
  core/rpc/src/state/state_light.rs
Labels: A8-looksgood, M6-rpcapi

#3761 Alternative sysvar setup for Windows
  README.adoc
Labels: A8-looksgood

#3776 client: fix comparison of CachedHeaderMetadata in tree_route
  core/client/db/src/lib.rs
  core/client/header-metadata/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#3753 Example of how to inspect arguments in weight calculation
  srml/example/src/lib.rs
Labels: A0-pleasereview, M3-docs

#3738 gossip: save sender for kept messages
  core/network/src/protocol/consensus_gossip.rs
Labels: A0-pleasereview

#3699 Split off System random functions into a new Randomness module
  Cargo.lock
  Cargo.toml
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/contracts/Cargo.toml
  srml/contracts/src/exec.rs
  srml/executive/src/lib.rs
  srml/randomness-collective-flip/Cargo.toml
  srml/randomness-collective-flip/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3785 babe: verify slots are strictly increasing
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
Labels: A0-pleasereview, M4-core

#3743 Multi-limb arithmetic for runtime
  core/phragmen/src/lib.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/sr_arithmetic.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3793 Add `execute_with` to `TestExternalities`
  Cargo.lock
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/offchain/http.rs
  core/state-machine/src/testing.rs
  core/test-runtime/src/system.rs
  node-template/runtime/src/template.rs
  node/executor/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/tests.rs
  srml/authority-discovery/src/lib.rs
  srml/authorship/src/lib.rs
  srml/babe/src/tests.rs
  srml/balances/src/tests.rs
  srml/collective/src/lib.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/tests.rs
  srml/democracy/src/lib.rs
  srml/elections-phragmen/src/lib.rs
  srml/elections/src/mock.rs
  srml/elections/src/tests.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/tests.rs
  srml/grandpa/src/tests.rs
  srml/im-online/src/tests.rs
  srml/indices/src/tests.rs
  srml/membership/src/lib.rs
  srml/offences/src/tests.rs
  srml/randomness-collective-flip/src/lib.rs
  srml/scored-pool/src/tests.rs
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/lib.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/tests/instance.rs
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
  srml/utility/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3796 Fix semantics of ExistenceRequirement::KeepAlive.
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi

#3808 fix comments
  core/sr-primitives/src/traits.rs
  srml/system/src/lib.rs
Labels: A2-insubstantial

#3802 node: re-use testnet genesis spec for staging testnet
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3809 deps: update clap and structopt
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/execution_strategy.rs
  core/cli/src/params.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  scripts/node-template-release/Cargo.toml
  subkey/Cargo.toml
  test-utils/chain-spec-builder/Cargo.toml
Labels: A0-pleasereview, M4-core

#3814 remove staking print
  srml/staking/src/tests.rs
Labels: A2-insubstantial

#3801 Provide macro for exporting functions from wasm
  core/executor/runtime-test/src/lib.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasmi_execution.rs
  core/primitives/src/lib.rs
  core/primitives/src/testing.rs
Labels: A0-pleasereview

#3818 grandpa: fix until imported logging arg order
  core/finality-grandpa/src/until_imported.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3817 Fix asynchronous transaction rejections.
  core/rpc/api/src/subscriptions.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/transaction-pool/graph/src/pool.rs
Labels: A0-pleasereview, M6-rpcapi

#3811 chain spec builder: add generate mode for authority keys
  Cargo.lock
  core/chain-spec/src/chain_spec.rs
  test-utils/chain-spec-builder/Cargo.toml
  test-utils/chain-spec-builder/src/cli.yml
  test-utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, M4-core

#3719 WIP: Node role RPC call
  core/rpc/api/src/system/helpers.rs
  core/rpc/api/src/system/mod.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#3791 Move srml RPC extensions to separate crates
  Cargo.lock
  Cargo.toml
  core/rpc/src/state/tests.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/contracts/rpc/Cargo.toml
  srml/contracts/rpc/runtime-api/Cargo.toml
  srml/contracts/rpc/runtime-api/src/lib.rs
  srml/contracts/rpc/src/lib.rs
  srml/system/rpc/Cargo.toml
  srml/system/rpc/runtime-api/Cargo.toml
  srml/system/rpc/runtime-api/src/lib.rs
  srml/system/rpc/src/lib.rs
Labels: A3-needsresolving, A8-looksgood, M4-core

#3765 Refactor decl storage
  node/runtime/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/genesis_config/builder_def.rs
  srml/support/procedural/src/storage/genesis_config/genesis_config_def.rs
  srml/support/procedural/src/storage/genesis_config/mod.rs
  srml/support/procedural/src/storage/getters.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/instance_trait.rs
  srml/support/procedural/src/storage/metadata.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/parse.rs
  srml/support/procedural/src/storage/storage_struct.rs
  srml/support/procedural/src/storage/store_trait.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/syn_ext.rs
Labels: A0-pleasereview, B2-breaksapi

#3829 Make `wasmi_execution` public to use it from tests
  core/executor/src/error.rs
  core/executor/src/lib.rs
  core/executor/src/wasm_runtime.rs
Labels: A0-pleasereview, A2-insubstantial

#3839 Make `VersionInfo` derive `Clone`
  core/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3840 Don't panic when we try to register 2 global loggers
  core/cli/src/lib.rs
Labels: A8-looksgood

#3845 grandpa: don't expire next round messages
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/tests.rs
Labels: A8-looksgood, M4-core

#3830 Code redundancy between ext implementation and testing.
  core/executor/src/lib.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasmi_execution.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/test-runtime/src/system.rs
  node/executor/src/lib.rs
Labels: A0-pleasereview

#3842 Update CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: A2-insubstantial, M3-docs

#3853 Fix typo
  core/client/src/client.rs
Labels: A2-insubstantial

#3825 core/finality-grandpa: Minor refactorings
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
Labels: A0-pleasereview, F6-refactor 🧹, M4-core

#3831 Don't make `ServiceBuilder` require to have a finality proof provider specified
  core/service/src/builder.rs
Labels: A0-pleasereview, A2-insubstantial

#3826 Persist block announcements
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#3844 Make build work with rustc 1.37 stable and RUSTC_BOOTSTRAP=1
  core/sr-std/without_std.rs
  core/utils/wasm-builder/src/prerequisites.rs
  node/runtime/src/lib.rs
Labels: A6-seemsok, B2-breaksapi

#3401 Support block revert operation in blockchain cache
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/list_storage.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
Labels: A0-pleasereview, M4-core

#3673 grandpa: pluggable voting rules
  core/consensus/common/src/select_chain.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/voting_rule.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3799 Move sr-arithmetic to a new crate and add in a fuzzer
  Cargo.lock
  Cargo.toml
  core/sr-arithmetic/Cargo.toml
  core/sr-arithmetic/fuzzer/.gitignore
  core/sr-arithmetic/fuzzer/Cargo.toml
  core/sr-arithmetic/fuzzer/src/biguint.rs
  core/sr-arithmetic/fuzzer/src/rational128.rs
  core/sr-arithmetic/src/biguint.rs
  core/sr-arithmetic/src/fixed64.rs
  core/sr-arithmetic/src/helpers_128bit.rs
  core/sr-arithmetic/src/lib.rs
  core/sr-arithmetic/src/per_things.rs
  core/sr-arithmetic/src/rational128.rs
  core/sr-arithmetic/src/traits.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/sr_arithmetic.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/weights.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#3854 Obviate manual dependency on wasm-gc executable
  Cargo.lock
  Dockerfile
  README.adoc
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/README.md
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/scripts/init.sh
  scripts/init.sh
Labels: A0-pleasereview

#3806 It's Clippy time!
  core/client/db/src/cache/mod.rs
  core/consensus/babe/primitives/src/digest.rs
  core/consensus/babe/src/aux_schema.rs
  core/consensus/slots/src/aux_schema.rs
  core/consensus/slots/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/sr25519.rs
  core/rpc-servers/src/lib.rs
  core/service/src/chain_ops.rs
  srml/support/src/hash.rs
  srml/support/src/traits.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#3858 Clean up the wasm-builder and release 1.0.8
  Cargo.lock
  core/executor/runtime-test/build.rs
  core/test-runtime/build.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/prerequisites.rs
  node-template/runtime/build.rs
  node/runtime/build.rs
Labels: A0-pleasereview, A2-insubstantial

#3855 Change Contracts::DefaultMaxDepth from 1024 to 32
  node/runtime/src/lib.rs
  srml/contracts/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3867 Use uniform quotes
  node-template/runtime/Cargo.toml
Labels: A2-insubstantial

#3866 Fix deserialization of `Bytes`
  Cargo.lock
  core/rpc/src/state/tests.rs
Labels: A0-pleasereview, M6-rpcapi

#3870 Explicitly declare decl_storage! getters as functions
  node-template/runtime/src/template.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/babe/src/lib.rs
  srml/balances/src/lib.rs
  srml/collective/src/lib.rs
  srml/contracts/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections-phragmen/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/im-online/src/lib.rs
  srml/indices/src/lib.rs
  srml/membership/src/lib.rs
  srml/offences/src/lib.rs
  srml/randomness-collective-flip/src/lib.rs
  srml/scored-pool/src/lib.rs
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/sudo/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/parse.rs
  srml/support/src/lib.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/issue2219.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/transaction-payment/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3871 Improve logging for offchain transaction submission.
  core/offchain/src/api.rs
Labels: A0-pleasereview, M4-core

#3850 refactor map macro for more general use
  core/primitives/src/lib.rs
Labels: A0-pleasereview

#3864 Fix ambiguity about start function in sr-sandbox doc
  core/sr-sandbox/src/lib.rs
Labels: F5-documentation 📄

#3856 Price to Weight ratio as type parameter
  node/executor/src/lib.rs
  node/runtime/src/impls.rs
  node/runtime/src/lib.rs
Labels: A7-looksgoodtestsfail

#3835 cli: disable pruning on validators
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview, M4-core

#3882 Error message when changing pruning mode
  core/state-db/src/lib.rs
Labels: A0-pleasereview

#3878 Dry out Author RPC tests a bit
  core/rpc/src/author/tests.rs
Labels: A8-looksgood, M6-rpcapi

#3888 Support disabling the addition of the default bootnode
  core/cli/src/lib.rs
  core/cli/src/params.rs
Labels: A0-pleasereview, A2-insubstantial

#3832 gossip: futures 03 Receiver
  core/finality-grandpa/src/communication/mod.rs
  core/network/src/protocol/consensus_gossip.rs
Labels: A7-looksgoodcantmerge

#3892 Fix srml assets compilation with `std` feature
  srml/assets/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#3893 Wasm-builder-runner unset `CARGO_TARGET_DIR` and release 1.0.4
  Cargo.lock
  core/executor/runtime-test/Cargo.toml
  core/test-runtime/Cargo.toml
  core/utils/wasm-builder-runner/Cargo.toml
  core/utils/wasm-builder-runner/src/lib.rs
  node-template/runtime/Cargo.toml
  node/runtime/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#3857 Add an OnUnbalanced hook for contract rent payments
  node/runtime/src/lib.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/rent.rs
  srml/contracts/src/tests.rs
Labels: A6-seemsok, B2-breaksapi

#3874 Make tests work after the changes introduced in #3793
  Cargo.lock
  srml/bridge/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3891 Throw an error if a bootnode is registered with two different peer ids
  core/cli/src/lib.rs
  core/network/src/error.rs
  core/network/src/service.rs
  node-template/src/cli.rs
  node-template/src/main.rs
  node/cli/src/lib.rs
  node/src/main.rs
Labels: A0-pleasereview

#3898 Fix phragmen election to wasm
  Cargo.lock
  node/cli/src/chain_spec.rs
  node/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/testing/src/genesis.rs
  srml/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, P2-asap

#3897 Remove support for secp256k1 for network keys
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/network/Cargo.toml
  core/network/src/config.rs
  core/network/src/lib.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#3887 Split the telemetry net status report in two
  Cargo.lock
  core/cli/src/informant.rs
  core/service/Cargo.toml
  core/service/src/builder.rs
  core/service/src/lib.rs
  core/service/src/status_sinks.rs
Labels: A0-pleasereview

#3899 node: spawn grandpa voter as essential task
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, A2-insubstantial

#3903 node-template: remove unnecessary on_exit guard
  node-template/src/service.rs
Labels: A0-pleasereview, A2-insubstantial

#3823 Better Parameterisation for Fee system
  Cargo.lock
  core/sr-arithmetic/src/biguint.rs
  core/sr-arithmetic/src/fixed64.rs
  node/executor/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/constants.rs
  node/runtime/src/impls.rs
  node/runtime/src/lib.rs
  srml/system/src/lib.rs
  srml/transaction-payment/src/lib.rs
Labels: A1-onice

#3904 Bump transaction version
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
Labels: A0-pleasereview

#3906 Service builder clean-up
  core/service/src/builder.rs
  core/service/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#3800 core/finality-grandpa: Request block sync from network after import timeout
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/finality-grandpa/src/until_imported.rs
  core/network/src/protocol/sync.rs
Labels: A0-pleasereview, M4-core

#3880 Fix treasury kept and spend when emptied
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  node/testing/src/genesis.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood, P2-asap

#3910 Rename node template's runtime dependency "node-template-runtime" -> "runtime"
  node-template/Cargo.toml
  node-template/src/chain_spec.rs
  node-template/src/service.rs
Labels: A2-insubstantial

#3884 support: BuildStorage methods to take self reference
  core/chain-spec/src/chain_spec.rs
  core/sr-primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/support/procedural/src/storage/genesis_config/builder_def.rs
  srml/support/procedural/src/storage/genesis_config/mod.rs
Labels: A0-pleasereview

#3908 Bring back `SubmitSignedTransaction` trait.
  core/primitives/src/crypto.rs
  core/sr-primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
  srml/system/src/offchain.rs
Labels: A0-pleasereview, M4-core

#3917 Remove MintedForSpending (now unused)
  node/runtime/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A2-insubstantial

#3918 Add force_unstake to staking as root operation.
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview

#3916 Telemetry timeout
  core/telemetry/src/worker/node.rs
Labels: A0-pleasereview

#3905 Adds function `to_substrate_wasm_fn_return_value`
  Cargo.lock
  core/client/src/runtime_api.rs
  core/primitives/src/lib.rs
  core/primitives/src/testing.rs
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/sr-api-macros/tests/ui/impl_incorrect_method_signature.rs
  core/sr-api-macros/tests/ui/impl_incorrect_method_signature.stderr
  core/sr-api-macros/tests/ui/impl_two_traits_with_same_name.rs
  core/sr-api-macros/tests/ui/impl_two_traits_with_same_name.stderr
  core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.rs
  core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, A2-insubstantial

#3919 Correct docs.
  srml/democracy/src/lib.rs
Labels: A2-insubstantial

#3930 runtime: Account nicknames
  Cargo.lock
  Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/nicks/Cargo.toml
  srml/nicks/src/lib.rs
Labels: A0-pleasereview

#3929 Fix warnings/missing doc comments
  core/rpc-servers/src/lib.rs
Labels: A2-insubstantial

#3928 grandpa: always try to import available block justifcation
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/justification.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, M4-core

#3873 Watch existing extrinsics RPC
  Cargo.lock
  core/rpc-servers/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/api/Cargo.toml
  core/rpc/api/src/author/mod.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/validated_pool.rs
  core/transaction-pool/graph/src/watcher.rs
  node/cli/Cargo.toml
  node/rpc-client/Cargo.toml
  node/rpc/Cargo.toml
  srml/contracts/rpc/Cargo.toml
  srml/system/rpc/Cargo.toml
Labels: A7-looksgoodtestsfail, M6-rpcapi

#3931 Revert "Watch existing extrinsics RPC"
  Cargo.lock
  core/rpc-servers/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/api/Cargo.toml
  core/rpc/api/src/author/mod.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/validated_pool.rs
  core/transaction-pool/graph/src/watcher.rs
  node/cli/Cargo.toml
  node/rpc-client/Cargo.toml
  node/rpc/Cargo.toml
  srml/contracts/rpc/Cargo.toml
  srml/system/rpc/Cargo.toml
Labels: A6-revertrevert

#3932 runtime: Expose const params for nicks module
  node/runtime/src/lib.rs
  srml/nicks/src/lib.rs
Labels: A0-pleasereview

#3934 runtime: Add ability to force a name change
  node/runtime/src/lib.rs
  srml/nicks/src/lib.rs
Labels: A0-pleasereview

#3914 *: Disable authority discovery module
  Cargo.lock
  core/service/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/testing/src/genesis.rs
Labels: A0-pleasereview, A6-revertrevert, M2-config

#3938 Too many addresses for a node is now a debug! rather than warn!
  core/network/src/behaviour.rs
Labels: A2-insubstantial

#3940 Updates to elections-phragmen and some runtime docs.
  core/phragmen/src/lib.rs
  core/sr-primitives/src/weights.rs
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  node/testing/src/genesis.rs
  srml/elections-phragmen/src/lib.rs
  srml/example/src/lib.rs
  srml/staking/src/lib.rs
  srml/system/src/lib.rs
Labels: A7-looksgoodtestsfail, B2-breaksapi

#3876 RPC to query transaction fee + weight + info
  Cargo.lock
  Cargo.toml
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/weights.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
  srml/transaction-payment/Cargo.toml
  srml/transaction-payment/rpc/Cargo.toml
  srml/transaction-payment/rpc/runtime-api/Cargo.toml
  srml/transaction-payment/rpc/runtime-api/src/lib.rs
  srml/transaction-payment/rpc/src/lib.rs
  srml/transaction-payment/src/lib.rs
Labels: A8-looksgood, M6-rpcapi

#3922 Basic extrinsic pool benchmarks
  Cargo.lock
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/benches/basics.rs
  core/transaction-pool/graph/src/pool.rs
Labels: A8-looksgood

#3939 Fix a import+prune+replace case for multi-provides transactions.
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
  core/transaction-pool/src/tests.rs
Labels: A8-looksgood, M4-core

#3949 Remove footgun around session keys/handlers
  Cargo.lock
  core/application-crypto/src/ed25519.rs
  core/application-crypto/src/sr25519.rs
  core/application-crypto/src/traits.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/babe/src/lib.rs
  srml/babe/src/mock.rs
  srml/grandpa/src/lib.rs
  srml/im-online/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
Labels: A8-looksgood

#3902 Switch sr-arithmetic benchmarking to criterion
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/benches/bench.rs
  core/sr-arithmetic/Cargo.toml
  core/sr-arithmetic/benches/bench.rs
  core/sr-arithmetic/src/biguint.rs
  core/sr-arithmetic/src/lib.rs
Labels: A1-onice

#3956 grandpa: fix handling of catch-up requests
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3959 node: add sentry mode flag
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
  node-template/src/cli.rs
  node-template/src/service.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3960 Upgrade `impl-serde` to `0.2.3`
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/storage/Cargo.toml
  core/sr-version/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#3958 test-utils/chain-spec-builder: Add note to run builder in release mode
  test-utils/chain-spec-builder/Cargo.toml
  test-utils/chain-spec-builder/build.rs
  test-utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, M5-binaries, Q0-trivial

#3961 cli: fix display_role helper
  core/cli/src/lib.rs
Labels: A2-insubstantial

#3965 Make substrate-offchain compile for WASM again
  .gitlab-ci.yml
  core/offchain/Cargo.toml
  core/offchain/src/api.rs
  core/offchain/src/api/http_dummy.rs
Labels: A0-pleasereview

#3966 Fix TODO for the WASM CI build of rpc-servers
  .gitlab-ci.yml
Labels: A2-insubstantial

#3967 Remove the RPC helpers module
  core/rpc/src/helpers.rs
  core/rpc/src/lib.rs
  core/rpc/src/state/state_full.rs
Labels: A2-insubstantial

#3944 Implement contract_getStorage RPC API
  node/runtime/src/lib.rs
  srml/contracts/rpc/runtime-api/src/lib.rs
  srml/contracts/rpc/src/lib.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/lib.rs
Labels: A0-pleasereview

#3971 Fix compiling substrate-chain-spec for WASM
  .gitlab-ci.yml
  core/chain-spec/Cargo.toml
  core/chain-spec/src/extension.rs
  core/chain-spec/src/lib.rs
Labels: A2-insubstantial

#3970 retry on gitlab system failures
  .gitlab-ci.yml
Labels: A2-insubstantial, F7-optimisation ⏱, M1-ci

#3972 Increase priority of ImOnline heartbeats
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A8-looksgood, M4-core

#3834 Create opaque struct for StorageProof.
  Cargo.lock
  core/authority-discovery/src/lib.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/runtime_api.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/chain.rs
  core/network/src/protocol.rs
  core/network/src/protocol/light_dispatch.rs
  core/network/src/protocol/message.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
Labels: A0-pleasereview

#3734 grandpa: Use storage proofs for Grandpa authorities
  Cargo.lock
  core/finality-grandpa/primitives/Cargo.toml
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  node-template/runtime/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/grandpa/Cargo.toml
  srml/grandpa/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/grandpa/src/tests.rs
Labels: A8-looksgood, B0-patchthis, B2-breaksapi

#3976 Remove NetworkSpecialization::on_event
  core/network/src/protocol.rs
  core/network/src/protocol/specialization.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#3979 Expose backend to rpc builder
  core/service/src/builder.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, B2-breaksapi

#3982 Improve doc for storages in srml-support
  srml/support/src/storage/mod.rs
Labels: A2-insubstantial, M3-docs

#3950 Retire `storage_items!`
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  srml/support/src/lib.rs
  srml/support/src/storage/mod.rs
  srml/support/test/tests/decl_storage.rs
Labels: A4-gotissues
