Repository paritytech/substrate, pull requests merged in 2019-09, with the labels that each got.

#3514 Submit (& sign) extrinsics from the runtime.
  core/sr-primitives/src/generic/mod.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/src/lib.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/balances/src/lib.rs
  srml/im-online/src/lib.rs
  srml/support/src/inherent.rs
  srml/system/src/lib.rs
  srml/system/src/offchain.rs
  subkey/src/main.rs
Labels: A0-pleasereview, M4-core

#3519 Publish minimum balance from within srml-contracts API
  srml/contracts/src/exec.rs
  srml/contracts/src/wasm/mod.rs
  srml/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview

#3522 Add missing child trie rpc on_custom_message handler
  core/client/src/genesis.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/network/src/protocol.rs
  core/rpc/src/state/tests.rs
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/genesismap.rs
Labels: A0-pleasereview

#3480 Make chain && state RPCs async
  Cargo.lock
  core/client/Cargo.toml
  core/client/src/backend.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/light/mod.rs
  core/client/src/notifications.rs
  core/rpc/Cargo.toml
  core/rpc/api/src/chain/error.rs
  core/rpc/api/src/chain/mod.rs
  core/rpc/api/src/state/error.rs
  core/rpc/api/src/state/mod.rs
  core/rpc/src/chain/chain_full.rs
  core/rpc/src/chain/chain_light.rs
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/state_full.rs
  core/rpc/src/state/state_light.rs
  core/rpc/src/state/tests.rs
  core/service/src/builder.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#3525 Fix tests compilation on master and remove warnings
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/state/tests.rs
Labels: A0-pleasereview, A2-insubstantial

#3518 ci: dont run a ci build pipeline on arbitrary tag pushes
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial, M1-ci

#3122 Implement change trie for child trie.
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/client.rs
  core/client/src/light/backend.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/network/src/protocol.rs
  core/network/src/protocol/light_dispatch.rs
  core/network/src/protocol/message.rs
  core/rpc/src/state/state_full.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/input.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
Labels: A8-looksgood

#3528 Drive by docs fix re minimum_balance
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A2-insubstantial

#3531 Typo
  core/consensus/slots/src/lib.rs
  core/transaction-pool/graph/src/pool.rs
Labels: A8-looksgood, M4-core

#3529 Run `sr-api-macros` ui tests only with a stable compiler
  Cargo.lock
  core/sr-api-macros/Cargo.toml
  core/sr-api-macros/tests/trybuild.rs
Labels: A0-pleasereview, A2-insubstantial

#3530 Removed superfluous safety check
  core/client/src/client.rs
Labels: A0-pleasereview, B0-patchthis

#3536 Fix `build-only-wasm` script
  scripts/build-only-wasm.sh
Labels: A0-pleasereview, A2-insubstantial

#3549 Implement `TryInto` for outer events
  srml/support/src/event.rs
Labels: A0-pleasereview

#3433 Custom runtime module errors
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/block_builder/block_builder.rs
  core/rpc/api/src/author/error.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-primitives/src/transaction_validity.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/transaction-pool/graph/src/error.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/src/tests.rs
  node-template/runtime/src/lib.rs
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/testing/src/keyring.rs
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
  srml/contracts/src/gas.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/im-online/src/lib.rs
  srml/indices/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
  srml/sudo/src/lib.rs
  srml/support/src/dispatch.rs
  srml/support/src/error.rs
  srml/support/src/lib.rs
  srml/support/src/unsigned.rs
  srml/support/test/tests/system.rs
  srml/system/src/lib.rs
  subkey/src/main.rs
Labels: A0-pleasereview, B2-breaksapi

#3548 client: only report block import to telemetry if new best
  core/client/src/client.rs
  core/consensus/common/src/block_import.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/block_import.rs
Labels: A0-pleasereview, M4-core

#3550 srml-contracts: Fix values used for state rent
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#2933 Changes tries build cache
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_cache.rs
  core/state-machine/src/changes_trie/input.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
Labels: A0-pleasereview, M4-core

#3559 Remove dead code in Staking
  srml/staking/src/lib.rs
Labels: A2-insubstantial

#3452 core/authority-discovery: Enable authorities to discover each other
  Cargo.lock
  Cargo.toml
  core/authority-discovery/Cargo.toml
  core/authority-discovery/build.rs
  core/authority-discovery/primitives/src/lib.rs
  core/authority-discovery/src/error.rs
  core/authority-discovery/src/lib.rs
  core/authority-discovery/src/schema/dht.proto
  core/network/src/lib.rs
  core/network/src/protocol/event.rs
  core/network/src/service.rs
  core/service/Cargo.toml
  core/service/src/builder.rs
  core/service/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3562 Add transactions from retracted blocks back to the pool
  core/basic-authorship/src/basic_authorship.rs
  core/client/src/backend.rs
  core/client/src/client.rs
  core/finality-grandpa/src/until_imported.rs
  core/service/src/builder.rs
  core/service/src/lib.rs
  core/transaction-pool/graph/src/pool.rs
Labels: A0-pleasereview

#3569 Update docs for the wasm executor crate
  core/executor/src/lib.rs
  core/executor/src/native_executor.rs
  core/executor/src/wasm_executor.rs
  core/executor/src/wasm_utils.rs
  core/state-machine/src/lib.rs
Labels: A2-insubstantial, M3-docs

#3540 grandpa: don't require justification of consensus changes on full node
  core/finality-grandpa/src/import.rs
  core/network/src/protocol/sync.rs
  core/network/src/protocol/sync/extra_requests.rs
Labels: A0-pleasereview, M4-core

#3576 Handle missing finality notifications in ExtraRequests
  core/network/src/protocol/sync/extra_requests.rs
Labels: A0-pleasereview, M4-core

#3579 Add section regarding polkadot PRs.
  CONTRIBUTING.adoc
  PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial, M3-docs

#3581 Augment every task spawned by Service with `on_exit`
  .gitlab-ci.yml
  ci/check_for_exit.sh
  core/service/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#3567 First step for generating host externals out of the function definition in `sr-io`
  Cargo.lock
  Cargo.toml
  core/executor/Cargo.toml
  core/executor/src/allocator.rs
  core/executor/src/error.rs
  core/executor/src/lib.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  core/executor/src/wasm_runtimes_cache.rs
  core/executor/src/wasm_utils.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-std/without_std.rs
  core/test-runtime/src/lib.rs
  core/wasm-interface/Cargo.toml
  core/wasm-interface/src/lib.rs
  core/wasm-interface/src/wasmi_impl.rs
  node-template/src/service.rs
  srml/system/src/offchain.rs
Labels: A0-pleasereview

#3578 Don't initialize block for offchain workers.
  core/offchain/primitives/src/lib.rs
Labels: A0-pleasereview, M4-core

#3524 Cleanup of the `state-machine` crate
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/genesis.rs
  core/client/src/lib.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/light/mod.rs
  core/executor/Cargo.toml
  core/executor/src/error.rs
  core/executor/src/lib.rs
  core/executor/src/native_executor.rs
  core/executor/src/wasm_executor.rs
  core/executor/src/wasm_runtimes_cache.rs
  core/finality-grandpa/src/finality_proof.rs
  core/primitives/src/child_storage_key.rs
  core/primitives/src/lib.rs
  core/primitives/src/offchain.rs
  core/primitives/src/storage.rs
  core/primitives/src/traits.rs
  core/rpc/src/state/state_full.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-std/without_std.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/error.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/trie/src/lib.rs
  node/executor/src/lib.rs
Labels: A0-pleasereview

#3504 Never panic during execution proof check
  Cargo.lock
  core/client/Cargo.toml
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/executor/src/wasm_executor.rs
  core/network/src/config.rs
  core/network/src/test/mod.rs
  core/panic-handler/src/lib.rs
  core/rpc/api/src/author/mod.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/testing.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood, M4-core

#3595 Fixes NPoS reward, along with tests, cleanups & docs corrections
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/staking/src/inflation.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A3-inprogress, B2-breaksapi

#3594 grandpa: use periodic neighbor packet sender
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/periodic.rs
Labels: A0-pleasereview, M4-core

#3598 Switch to new proc-macro crate for implementing traits for tuples
  Cargo.lock
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/traits.rs
  srml/authorship/Cargo.toml
  srml/authorship/src/lib.rs
  srml/finality-tracker/Cargo.toml
  srml/finality-tracker/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/support/Cargo.toml
  srml/support/src/lib.rs
  srml/support/src/traits.rs
  srml/system/Cargo.toml
  srml/system/src/lib.rs
  srml/timestamp/Cargo.toml
  srml/timestamp/src/lib.rs
Labels: A7-looksgoodtestsfail

#3589 read_storage panics
  core/executor/src/wasm_executor.rs
  core/sr-io/with_std.rs
  core/test-runtime/src/lib.rs
  node/runtime/src/lib.rs
Labels: A8-looksgood

#3542 grandpa: fix race condition
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/import.rs
Labels: A0-pleasereview, M4-core

#3596 Fix tracking validator set in ImOnline
  Cargo.lock
  core/application-crypto/src/lib.rs
  core/application-crypto/src/traits.rs
  core/authority-discovery/Cargo.toml
  core/offchain/src/testing.rs
  core/primitives/src/offchain.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/testing.rs
  core/sr-primitives/src/traits.rs
  core/sr-staking-primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/aura/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/authorship/Cargo.toml
  srml/finality-tracker/Cargo.toml
  srml/im-online/Cargo.toml
  srml/im-online/src/lib.rs
  srml/im-online/src/mock.rs
  srml/im-online/src/tests.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
Labels: A8-looksgood, M4-core

#3534 Fixes for allocator + factory + misc improvements
  core/cli/src/params.rs
  core/executor/src/allocator.rs
  core/executor/src/error.rs
  node/cli/src/factory_impl.rs
  test-utils/transaction-factory/src/lib.rs
Labels: A0-pleasereview

#3609 Clean up sr-io
  Cargo.lock
  core/application-crypto/src/ed25519.rs
  core/application-crypto/src/sr25519.rs
  core/client/db/src/lib.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/genesis.rs
  core/client/src/light/fetcher.rs
  core/executor/runtime-test/Cargo.toml
  core/executor/runtime-test/src/lib.rs
  core/executor/src/wasm_executor.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/trie/src/lib.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/contracts/src/wasm/runtime.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/im-online/src/lib.rs
  srml/sudo/src/lib.rs
  srml/support/src/lib.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/instance.rs
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3613 RPC call to get all RPC methods
  Cargo.lock
  core/rpc-servers/Cargo.toml
  core/rpc-servers/src/lib.rs
  core/rpc/api/Cargo.toml
  core/service/src/builder.rs
  node/cli/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#3612 Fetching multiple remote values using single message
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/light/fetcher.rs
  core/network/src/chain.rs
  core/network/src/on_demand_layer.rs
  core/network/src/protocol.rs
  core/network/src/protocol/light_dispatch.rs
  core/network/src/protocol/message.rs
  core/rpc/src/state/state_light.rs
  core/state-machine/src/lib.rs
  core/test-client/src/lib.rs
Labels: A8-looksgood, M4-core

#3607 Send block status with announcement
  core/network/src/protocol.rs
  core/network/src/protocol/message.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
Labels: A0-pleasereview

#3619 Enable nice wasm panic messages by default
  core/sr-io/Cargo.toml
  core/sr-io/without_std.rs
  srml/aura/Cargo.toml
  srml/babe/Cargo.toml
Labels: A0-pleasereview

#3622 Fix missing `contracts` RPC on a full node.
  node/cli/src/service.rs
  node/rpc/src/lib.rs
Labels: A0-pleasereview, M4-core

#3627 Suggest `--release` compilation
  core/consensus/slots/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3630 Properly detect debug build in slots
  core/consensus/slots/Cargo.toml
  core/consensus/slots/build.rs
  core/consensus/slots/src/lib.rs
Labels: A0-pleasereview

#3634 add polkadot-v0.5 branch to the ci
  .gitlab-ci.yml
Labels: A0-pleasereview, B2-breaksapi, M1-ci

#3614 Storage tracing
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/light/backend.rs
  core/primitives/src/hexdisplay.rs
  core/primitives/src/lib.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/backend.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
Labels: A0-pleasereview

#3631 Update parity-wasm to 0.40
  Cargo.lock
  core/executor/Cargo.toml
  core/executor/src/wasm_runtimes_cache.rs
  core/sr-sandbox/Cargo.toml
  node/runtime/src/lib.rs
  srml/contracts/Cargo.toml
  srml/contracts/src/wasm/mod.rs
Labels: A0-pleasereview

#3638 From<UintAuthority> for u64
  core/sr-primitives/src/testing.rs
Labels: A2-insubstantial

#3635 Make `wasm-builder` check for `rust-lld`
  README.adoc
  core/utils/wasm-builder/src/prerequisites.rs
Labels: A0-pleasereview

#3640 Remove the no_std feature from the WASM builder
  Cargo.lock
  core/executor/runtime-test/Cargo.toml
  core/executor/runtime-test/build.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/build.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/README.md
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/build.rs
  node/runtime/Cargo.toml
  node/runtime/build.rs
  srml/contracts/Cargo.toml
Labels: A0-pleasereview

#3643 core, subkey: allow to read Polkadot, Kusama, and Dothereum address types
  core/primitives/src/crypto.rs
  subkey/src/cli.yml
  subkey/src/main.rs
Labels: A0-pleasereview, M2-config, M4-core, M5-binaries

#3364 srml-module: Phragmen election
  Cargo.lock
  Cargo.toml
  core/phragmen/benches/phragmen.rs
  core/phragmen/src/lib.rs
  core/phragmen/src/mock.rs
  core/phragmen/src/tests.rs
  node/runtime/src/lib.rs
  srml/elections-phragmen/Cargo.toml
  srml/elections-phragmen/src/lib.rs
  srml/elections/src/lib.rs
  srml/staking/src/lib.rs
  srml/support/src/traits.rs
Labels: A8-looksgood, B2-breaksapi

#3533 Force new era only if 1/3 validators is disabled.
  node/runtime/src/lib.rs
  srml/authority-discovery/src/lib.rs
  srml/im-online/src/mock.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
Labels: A8-looksgood, B2-breaksapi, M4-core

#3395 Blockchain cache pruning strategy
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/lib.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/consensus/pow/src/lib.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/network/src/test/mod.rs
Labels: A7-looksgoodcantmerge, M4-core

#3656 Use `ThreadPool::spawn_ok()` instead of `ThreadPool::spawn()`
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/cli/Cargo.toml
  core/client/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/babe/Cargo.toml
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue/basic_queue.rs
  core/consensus/pow/Cargo.toml
  core/consensus/slots/Cargo.toml
  core/finality-grandpa/Cargo.toml
  core/network/Cargo.toml
  core/offchain/Cargo.toml
  core/peerset/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/api/Cargo.toml
  core/service/Cargo.toml
  core/telemetry/Cargo.toml
  core/test-client/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  node/cli/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#3657 find best_containing even if best chain is shorter
  core/client/src/client.rs
Labels: A0-pleasereview

#3644 Make staking inflation curve configurable.
  Cargo.lock
  Cargo.toml
  core/sr-primitives/src/curve.rs
  core/sr-primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  srml/staking/Cargo.toml
  srml/staking/reward-curve/Cargo.toml
  srml/staking/reward-curve/src/lib.rs
  srml/staking/reward-curve/src/log.rs
  srml/staking/reward-curve/test/Cargo.toml
  srml/staking/reward-curve/test/src/lib.rs
  srml/staking/src/inflation.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
Labels: A0-pleasereview, B2-breaksapi

#3659 Remove unused key types sr25 and ed25
  core/application-crypto/src/ed25519.rs
  core/application-crypto/src/sr25519.rs
  core/keystore/src/lib.rs
  core/primitives/src/crypto.rs
  core/primitives/src/testing.rs
  core/rpc/src/author/tests.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/src/lib.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#3660 Only submit signed extrinsics back to pool when retracting block
  core/service/src/builder.rs
Labels: A0-pleasereview

#3666 improve justification docs
  core/sr-primitives/src/lib.rs
Labels: A2-insubstantial

#3664 Rename more things related to contract instantiation
  node/runtime/src/lib.rs
  srml/contracts/COMPLEXITY.md
  srml/contracts/src/account_db.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/tests.rs
  srml/contracts/src/wasm/mod.rs
  srml/contracts/src/wasm/runtime.rs
Labels: B2-breaksapi

#3668 Refactor reward curve
  Cargo.toml
  srml/staking/reward-curve/Cargo.toml
  srml/staking/reward-curve/src/lib.rs
  srml/staking/reward-curve/test/Cargo.toml
  srml/staking/reward-curve/tests/test.rs
Labels: A0-pleasereview, A2-insubstantial

#3583 Fixing BABE epochs to change between blocks
  Cargo.lock
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/primitives/src/digest.rs
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/aux_schema.rs
  core/consensus/babe/src/epoch_changes.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/slots/src/lib.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/mod.rs
  core/phragmen/benches/phragmen.rs
  core/service/src/chain_ops.rs
  core/service/test/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/testing.rs
  core/test-runtime/src/lib.rs
  core/utils/fork-tree/src/lib.rs
  node-template/runtime/src/lib.rs
  node-template/src/service.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/babe/Cargo.toml
  srml/babe/src/lib.rs
  srml/babe/src/mock.rs
  srml/babe/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#3610 Decouple node-executor structures from wasmi
  core/executor/src/allocator.rs
  core/executor/src/sandbox.rs
  core/executor/src/wasm_executor.rs
  node/executor/src/lib.rs
Labels: A5-grumble

#3646 Send local GRANDPA authority id to telemetry
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/lib.rs
Labels: A8-looksgood

#3655 Move `best_containing` from `Client` to `blockchain::Backend`
  core/client/src/blockchain.rs
  core/client/src/client.rs
Labels: A0-pleasereview

#3669 fix #2177: port GRANDPA node-side code to use Consensus digests
  Cargo.lock
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  node-template/runtime/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/grandpa/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3346 Add block announce validator.
  core/client/src/client.rs
  core/client/src/lib.rs
  core/consensus/common/src/block_validation.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/periodic.rs
  core/finality-grandpa/src/communication/tests.rs
  core/network/src/chain.rs
  core/network/src/config.rs
  core/network/src/protocol.rs
  core/network/src/protocol/message.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/service/src/lib.rs
Labels: A3-inprogress

#3680 Fix head not hashed
  node/runtime/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/src/storage/generator/linked_map.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/tests/final_keys.rs
Labels: B2-breaksapi, B8-breakseverything

#3681 node: update flaming fir
  node-template/src/service.rs
  node/cli/res/flaming-fir.json
  node/cli/src/service.rs
Labels: A0-pleasereview, A2-insubstantial

#3679 Document how to get head of linked map.
  srml/support/procedural/src/lib.rs
  srml/support/src/storage/generator/mod.rs
Labels: A2-insubstantial

#3456 Refactor: fixed point arithmetic for SRML.
  core/phragmen/benches/phragmen.rs
  core/phragmen/src/lib.rs
  core/phragmen/src/mock.rs
  core/phragmen/src/tests.rs
  core/sr-primitives/Cargo.toml
  core/sr-primitives/src/curve.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/sr_arithmetic.rs
  core/sr-primitives/src/weights.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
  srml/offences/src/lib.rs
  srml/staking/reward-curve/src/lib.rs
  srml/staking/src/inflation.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/lib.rs
Labels: A1-onice, B2-breaksapi

#3693 Fix Phragmen equalize loop.
  core/phragmen/src/lib.rs
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A2-insubstantial

#3690 Fix linkedmap instance head of
  node/runtime/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/test/tests/final_keys.rs
Labels: A0-pleasereview, B2-breaksapi

#3694 Random seed API for offchain workers
  core/offchain/src/api.rs
Labels: A8-looksgood, M4-core

#3691 Improve storage doc
  srml/support/procedural/src/lib.rs
  srml/support/src/storage/generator/double_map.rs
  srml/support/src/storage/generator/linked_map.rs
  srml/support/src/storage/generator/map.rs
  srml/support/src/storage/generator/value.rs
Labels: A0-pleasereview, A2-insubstantial

#3705 grandpa: send authority id to telemetry when starting new voter
  core/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3710 Make `TestOffchainExt` panic on unknown requests
  core/executor/src/wasm_executor.rs
  core/offchain/src/testing.rs
Labels: A0-pleasereview

#3711 Update libsecp256k1 dep to 0.3.0
  Cargo.lock
  core/executor/Cargo.toml
  core/sr-io/Cargo.toml
  node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3712 Support trailing commas in `decl_module`
  srml/support/src/dispatch.rs
  srml/support/src/storage/storage_items.rs
Labels: A7-looksgoodtestsfail

#3702 Refactor srml-support/storage
  srml/support/src/double_map.rs
  srml/support/src/hash.rs
  srml/support/src/hashable.rs
  srml/support/src/lib.rs
  srml/support/src/storage/generator/double_map.rs
  srml/support/src/storage/generator/linked_map.rs
  srml/support/src/storage/generator/map.rs
  srml/support/src/storage/generator/value.rs
  srml/support/src/storage/hashed.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/unhashed.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview

#3715 cli: clean up flag descriptions
  core/cli/src/params.rs
Labels: A0-pleasereview, A2-insubstantial

#3714 Comment the features used for SGX builds.
  core/sr-io/Cargo.toml
Labels: A2-insubstantial, M3-docs

#3713 docs: add security policy
  SECURITY.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs

#3633 Explicit sync API for downloading important, possibly orphaned, forks
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
Labels: A0-pleasereview

#3706 peerset: fix reserved nodes
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/peerset/src/lib.rs
  core/peerset/src/peersstate.rs
Labels: A0-pleasereview, M4-core

#3692 ChainSpec extensions
  Cargo.lock
  Cargo.toml
  core/chain-spec/Cargo.toml
  core/chain-spec/derive/Cargo.toml
  core/chain-spec/derive/src/impls.rs
  core/chain-spec/derive/src/lib.rs
  core/chain-spec/res/chain_spec.json
  core/chain-spec/res/chain_spec2.json
  core/chain-spec/src/chain_spec.rs
  core/chain-spec/src/extension.rs
  core/chain-spec/src/lib.rs
  core/cli/src/lib.rs
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/lib.rs
  core/client/src/light/mod.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/network/src/test/mod.rs
  core/service/Cargo.toml
  core/service/src/builder.rs
  core/service/src/chain_ops.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/telemetry/src/lib.rs
  core/test-client/src/lib.rs
  node-template/src/cli.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  test-utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, M4-core

#3723 core/sr-api-macros/Cargo.toml: Pin protobuf version
  Cargo.lock
  core/sr-api-macros/Cargo.toml
Labels: A0-pleasereview

#3726 Revert "core/sr-api-macros/Cargo.toml: Pin protobuf version"
  Cargo.lock
  core/sr-api-macros/Cargo.toml
Labels: A2-insubstantial

#3720 Give more information why conversion between native and runtime failed
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/executor/src/native_executor.rs
  core/primitives/src/traits.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/tests/runtime_calls.rs
  core/state-machine/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3724 srml: im-online: fix received heartbeats pruning
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
  srml/im-online/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core
