Repository paritytech/substrate, pull requests merged in 2019-08, with the labels that each got.

#3279 Extend flaming fir version details on README
  README.adoc
Labels: A0-pleasereview, A2-insubstantial

#3266 Replace the telemetry Mutex with a channel
  Cargo.lock
  core/telemetry/Cargo.toml
  core/telemetry/src/lib.rs
Labels: A8-looksgood

#3274 Telemetry connectivity issues are now WARN
  core/telemetry/src/worker/node.rs
Labels: A2-insubstantial

#3272 Fix telemetry not responding to pings
  core/telemetry/src/worker.rs
  core/telemetry/src/worker/node.rs
Labels: A0-pleasereview

#3255 srml-contracts: Deferred actions
  node/runtime/src/lib.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/tests.rs
  srml/contracts/src/wasm/mod.rs
  srml/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B2-breaksapi

#3249 Documentation and small cleanup in panic-handler
  core/executor/src/native_executor.rs
  core/panic-handler/src/lib.rs
  core/state-machine/src/ext.rs
Labels: A8-looksgood

#3273 Make staking add_reward_points_to_validator public
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#3281 Slots should not try to catch panics.
  core/consensus/slots/src/lib.rs
Labels: A8-looksgood

#3284 Fix staking
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#3286 Check the genesis hash in transactions regardless of era.
  core/client/src/client.rs
  core/finality-grandpa/src/environment.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/traits.rs
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/staking/src/tests.rs
  srml/system/src/lib.rs
  subkey/src/main.rs
  test-utils/transaction-factory/src/complex_mode.rs
  test-utils/transaction-factory/src/lib.rs
  test-utils/transaction-factory/src/simple_modes.rs
Labels: B2-breaksapi

#2815 Trie simplification.
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/src/cht.rs
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/in_mem.rs
  core/client/src/light/fetcher.rs
  core/executor/Cargo.toml
  core/executor/src/wasm_executor.rs
  core/keyring/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-io/with_std.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/backend.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/trie/Cargo.toml
  core/trie/benches/bench.rs
  core/trie/src/lib.rs
  core/trie/src/node_codec.rs
  core/trie/src/node_header.rs
  core/trie/src/trie_stream.rs
  node-template/Cargo.toml
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/executive/src/lib.rs
  srml/session/src/historical.rs
Labels: A0-pleasereview, B2-breaksapi

#3293 node: use BABE predigest data to find authorship
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/lib.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
Labels: A8-looksgood, B2-breaksapi, B3-breaksconsensus, M4-core

#3287 Switch RPCs to stable futures
  core/rpc/src/helpers.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/src/components.rs
  core/service/src/lib.rs
Labels: A0-pleasereview

#3262 srml-contracts: Minor fixes to docs.
  node/runtime/src/lib.rs
  srml/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview

#3250 Mention that in_mem::Backend doesn't work
  core/client/src/in_mem.rs
  core/client/src/lib.rs
Labels: A2-insubstantial

#3306 node: fix integration test transaction format
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3305 fix BABE randomness calculation
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, B3-breaksconsensus

#3288 Improve internal doc of inflation module
  srml/staking/src/inflation.rs
Labels: A0-pleasereview, A2-insubstantial

#3315 Rename on_demand to light_dispatch and various minor changes
  core/network/src/on_demand_layer.rs
  core/network/src/protocol.rs
  core/network/src/protocol/light_dispatch.rs
  core/network/src/service.rs
Labels: A8-looksgood

#3267 Update to schnorrkel `0.8.0`
  Cargo.lock
  core/consensus/babe/Cargo.toml
  core/consensus/babe/primitives/Cargo.toml
  core/consensus/babe/primitives/src/digest.rs
  core/consensus/babe/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/sr25519.rs
  node/runtime/src/lib.rs
  subkey/Cargo.toml
Labels: A0-pleasereview

#3319 Propagate cache when calling into runtime
  core/client/src/call_executor.rs
Labels: A0-pleasereview

#3323 Fix `linked_map` in `decl_storage!` for option values
  Cargo.lock
  srml/support/procedural/src/storage/impls.rs
  srml/support/src/lib.rs
Labels: A0-pleasereview

#3311 Remove leaves tracking from light backend
  core/client/db/src/light.rs
Labels: A2-insubstantial, M4-core

#3321 Handle telemetry socket errors
  core/telemetry/src/worker/node.rs
Labels: A0-pleasereview

#3312 Remove support for mplex
  core/network/src/lib.rs
  core/network/src/transport.rs
Labels: A3-inprogress

#3165 Make Verifier::verify mutable
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/import_queue/basic_queue.rs
  core/finality-grandpa/src/light_import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3313 Rename CustomProto to LegacyProto
  core/network/src/legacy_proto/behaviour.rs
  core/network/src/legacy_proto/handler.rs
  core/network/src/legacy_proto/mod.rs
  core/network/src/legacy_proto/tests.rs
  core/network/src/legacy_proto/upgrade.rs
  core/network/src/lib.rs
  core/network/src/protocol.rs
Labels: A8-looksgood

#3327 Derive CompactAs for Perbill/mill/U128
  core/sr-primitives/src/lib.rs
  node/runtime/src/lib.rs
Labels: A2-insubstantial

#3331 More tests and some cleanup
  core/cli/src/lib.rs
  core/keystore/src/lib.rs
  core/primitives/src/testing.rs
  core/primitives/src/traits.rs
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
Labels: A0-pleasereview

#3333 Make `DefaultByte` implement `Send + Sync`
  node/runtime/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
Labels: A0-pleasereview

#3317 Set uncles inherent
  Cargo.lock
  Cargo.toml
  core/client/src/client.rs
  core/client/src/lib.rs
  core/consensus/babe/Cargo.toml
  core/consensus/babe/src/lib.rs
  core/consensus/uncles/Cargo.toml
  core/consensus/uncles/src/lib.rs
  node/runtime/src/lib.rs
  srml/authorship/Cargo.toml
  srml/authorship/src/lib.rs
  srml/finality-tracker/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#3332 Fix for network test failing randomly
  core/network/src/protocol.rs
  core/network/src/protocol/sync.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#3328 Reintroduce mplex (revert #3312)
  core/network/src/lib.rs
  core/network/src/transport.rs
Labels: A0-pleasereview

#3334 Clean up CLI interface
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#3285 Switch offchain workers to new futures
  Cargo.lock
  core/offchain/Cargo.toml
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/service/src/components.rs
Labels: A7-looksgoodtestsfail

#3229 add post_dispatch
  core/sr-primitives/src/generic/checked_extrinsic.rs
  core/sr-primitives/src/generic/unchecked_extrinsic.rs
  core/sr-primitives/src/traits.rs
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/system/src/lib.rs
Labels: A3-inprogress, B2-breaksapi

#3298 grandpa: track multiple live rounds in voter set state
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, M4-core

#3337 Adds `author_rotateKeys` RPC
  Cargo.lock
  core/primitives/src/crypto.rs
  core/rpc/Cargo.toml
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/rpc/src/state/tests.rs
  core/service/Cargo.toml
  core/service/src/components.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  node/primitives/Cargo.toml
Labels: A0-pleasereview

#3338 Make `--dev` to `--alice` again
  core/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3257 srml-contracts: Refactor away some duplication in runtime functions.
  node/runtime/src/lib.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/wasm/runtime.rs
Labels: A7-looksgoodtestsfail, B2-breaksapi

#3185 Child storage tests and genesis fix.
  Cargo.lock
  core/client/db/src/lib.rs
  core/client/db/src/storage_cache.rs
  core/client/src/genesis.rs
  core/client/src/light/backend.rs
  core/executor/src/wasm_executor.rs
  core/service/src/chain_spec.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/state-machine/src/backend.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/testing.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-runtime/client/Cargo.toml
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/genesismap.rs
  core/test-runtime/src/system.rs
  node-template/runtime/src/template.rs
  node/cli/res/flaming-fir.json
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/mock.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/membership/src/lib.rs
  srml/session/src/historical.rs
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/storage_items.rs
  srml/support/test/tests/final_keys.rs
  srml/support/test/tests/instance.rs
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#3238 Service various cleanups
  core/cli/src/lib.rs
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/factory_impl.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
Labels: A8-looksgood, B2-breaksapi

#3342 Remove Decode trait bound.
  core/sr-primitives/src/traits.rs
Labels: A8-looksgood

#3345 Fixed all warnings
  core/cli/src/execution_strategy.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/src/genesis.rs
Labels: A2-insubstantial

#3349 remove unneeded as_ref call
  core/trie/src/node_codec.rs
Labels: A2-insubstantial

#3350 grandpa: fix --no-grandpa flag breaking block production
  core/finality-grandpa/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, A2-insubstantial

#3343 Introduce AppVerify
  core/sr-primitives/src/traits.rs
Labels: A0-pleasereview

#3347 grandpa: fix catch up test
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, M4-core

#2850 Check for warnings
  .gitlab-ci.yml
Labels: A7-looksgoodcantmerge, B0-patchthis, M1-ci

#3348 Adds `--no-validator` CLI flag
  core/cli/src/lib.rs
  core/executor/src/error.rs
  core/executor/src/native_executor.rs
  core/executor/src/wasm_executor.rs
  core/executor/src/wasm_runtimes_cache.rs
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/offchain/src/testing.rs
  core/primitives/src/offchain.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/state-machine/src/lib.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3351 node: Reintroduce `--validator` cli flag
  core/cli/src/lib.rs
  core/cli/src/params.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3356 node: setup disabled grandpa properly
  core/finality-grandpa/src/lib.rs
  core/network/src/protocol/consensus_gossip.rs
  node/cli/src/service.rs
Labels: A8-looksgood, M4-core

#3325 Add a small ban when we get disconnected from a node
  core/network/src/legacy_proto/behaviour.rs
Labels: A0-pleasereview

#3359 Switch AuRa to dynamic keystore lookup
  Cargo.lock
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  node-template/src/service.rs
Labels: A0-pleasereview

#3357 Scale trait and move to u32 blocknumbers
  core/basic-authorship/Cargo.toml
  core/cli/Cargo.toml
  core/client/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/babe/Cargo.toml
  core/consensus/babe/src/lib.rs
  core/consensus/common/Cargo.toml
  core/consensus/slots/Cargo.toml
  core/finality-grandpa/Cargo.toml
  core/network/Cargo.toml
  core/offchain/Cargo.toml
  core/peerset/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-primitives/src/traits.rs
  core/telemetry/Cargo.toml
  core/test-client/Cargo.toml
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
  srml/authorship/src/lib.rs
  srml/membership/src/lib.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3358 Refactor parse_and_execute
  core/cli/src/lib.rs
  node-template/src/cli.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview

#3309 Rewrite the GrandPa observer work future
  core/finality-grandpa/src/observer.rs
Labels: A0-pleasereview

#3366 document that session key generation stores keys
  core/service/src/components.rs
  core/service/src/lib.rs
  core/session/src/lib.rs
Labels: A2-insubstantial

#3369 Make `--alice` etc implicitly enable `--validator`
  core/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#3368 Remove unneeded cruft
  srml/democracy/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A2-insubstantial

#3353 node: exit on GRANDPA voter or BABE authoring error
  core/cli/src/error.rs
  core/finality-grandpa/src/lib.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  node-template/src/cli.rs
  node-template/src/main.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/src/main.rs
Labels: A0-pleasereview, M4-core

#3360 Remove enumerate_trie_root in favour of ordered_trie_root #2382
  core/executor/runtime-test/src/lib.rs
  core/executor/src/wasm_executor.rs
  core/sr-io/src/lib.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/src/system.rs
  srml/system/src/lib.rs
Labels: A6-mustntgrumble

#3367 downgrade log-level of malformed packets to debug
  core/network/src/legacy_proto/upgrade.rs
Labels: A0-pleasereview

#3320 srml-contracts: Contract calls/instantiations to return exit statuses
  core/sr-sandbox/src/lib.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/contracts/COMPLEXITY.md
  srml/contracts/src/exec.rs
  srml/contracts/src/lib.rs
  srml/contracts/src/tests.rs
  srml/contracts/src/wasm/mod.rs
  srml/contracts/src/wasm/prepare.rs
  srml/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B2-breaksapi

#3372 Remark is trivial and doesn't deserve such a big weight
  srml/system/src/lib.rs
Labels: A2-insubstantial

#3374 Era change can be forced on and forced off
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#3371 Add code owners file
  CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial

#3375 subkey network default works
  subkey/src/main.rs
Labels: A0-pleasereview

#3376 core/network: Surface peerset's `set_priority_group` in NetworkService
  core/network/src/config.rs
  core/network/src/service.rs
Labels: A0-pleasereview, M4-core, Q2-easy

#3355 More robust state pinning
  core/client/db/src/lib.rs
  core/state-db/src/lib.rs
  core/state-db/src/noncanonical.rs
Labels: A8-looksgood

#3225 Add transaction pool to Aura and Babe import queue
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/service/src/chain_ops.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A8-looksgood

#3388 Replace config field with default value (srml/im-online)
  core/network/src/protocol/light_dispatch.rs
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  srml/contracts/src/tests.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview

#3379 Make sure that `srml-collective` does not initialize `Members` twice
  srml/collective/src/lib.rs
  srml/membership/src/lib.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview

#3402 Minor typo fix. bu -> by
  core/rpc/src/subscriptions.rs
Labels: A2-insubstantial, M3-docs

#3397 Remove usage of loop_fn in the GRANDPA tests
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview

#3377 consensus: refactor aura and babe proposer
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/slots/Cargo.toml
  core/consensus/slots/src/lib.rs
Labels: A0-pleasereview, M4-core

#3393 Rewrite the GRANDPA voter to not use a loop
  core/finality-grandpa/src/lib.rs
Labels: A0-pleasereview

#3394 Transition the transaction-pool to new futures
  Cargo.lock
  core/rpc/src/author/mod.rs
  core/rpc/src/author/tests.rs
  core/service/src/lib.rs
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/watcher.rs
Labels: A0-pleasereview

#3405 add some docs for consensus-gossip
  core/network/src/protocol/consensus_gossip.rs
Labels: A0-pleasereview

#3408 Update to libp2p 0.12
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/network/Cargo.toml
  core/network/src/behaviour.rs
  core/network/src/discovery.rs
  core/network/src/lib.rs
  core/network/src/protocol/event.rs
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/telemetry/Cargo.toml
Labels: A0-pleasereview

#3409 Bad spelling
  srml/support/src/dispatch.rs
Labels: A2-insubstantial

#3410 sync: fix peer common number on block announce
  core/network/src/protocol/sync.rs
Labels: A0-pleasereview, M4-core

#3412 remove weighting and staking dependency in BABE
  Cargo.lock
  node/runtime/src/lib.rs
  srml/babe/Cargo.toml
  srml/babe/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#3414 im-online: use new session keys (not upcoming session)
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi, M4-core

#3413 session: add handler for genesis session
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  srml/aura/Cargo.toml
  srml/aura/src/lib.rs
  srml/babe/src/lib.rs
  srml/grandpa/Cargo.toml
  srml/grandpa/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/im-online/src/lib.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
Labels: A8-looksgood, B2-breaksapi, M4-core

#3301 Fix light client synchronization on master
  CODEOWNERS
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/light_import.rs
  core/network/src/protocol/sync/extra_requests.rs
  core/service/src/chain_spec.rs
  core/service/test/src/lib.rs
  core/utils/fork-tree/src/lib.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
  srml/support/test/tests/genesisconfig.rs
Labels: A0-pleasereview, B2-breaksapi, B3-breaksconsensus, M4-core

#3416 Reject transactions with no `provides` tags.
  core/transaction-pool/graph/src/error.rs
  core/transaction-pool/graph/src/pool.rs
Labels: A0-pleasereview, M4-core

#3418 Verify signature and session index during apply phase of im-online.
  core/sr-primitives/src/traits.rs
  node/runtime/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A8-looksgood, M4-core

#3411 Allow slashing only on current era
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#3420 Respect heap_pages parameter.
  core/executor/src/wasm_runtimes_cache.rs
  core/test-runtime/src/lib.rs
Labels: A8-looksgood

#3380 babe: Introduce secondary slots (Aurababeous)
  Cargo.lock
  core/consensus/aura/src/lib.rs
  core/consensus/babe/primitives/src/digest.rs
  core/consensus/babe/primitives/src/lib.rs
  core/consensus/babe/src/lib.rs
  core/consensus/babe/src/tests.rs
  core/consensus/slots/src/lib.rs
  core/test-runtime/src/lib.rs
  node/cli/src/service.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
Labels: A9-buythatmanabeer, B2-breaksapi, M4-core

#3423 node: update flaming fir chain spec
  node/cli/res/flaming-fir.json
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3424 node: update flaming fir
  node/cli/res/flaming-fir.json
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview, M4-core

#3425 Move checks for renamed functions to `__check_reserved_function_names`
  srml/support/src/dispatch.rs
  srml/support/test/tests/reserved_keyword/on_initialize.rs
  srml/support/test/tests/reserved_keyword/on_initialize.stderr
Labels: A8-looksgood

#3426 Implements `FindAuthor<u32>` for `srml-aura`
  core/consensus/aura/primitives/src/lib.rs
  srml/aura/src/lib.rs
Labels: A0-pleasereview

#3392 Proper loser handling in approval election.
  Cargo.lock
  node/runtime/src/lib.rs
  srml/elections/src/lib.rs
Labels: A7-looksgoodtestsfail

#3430 Signed transactions now have affinity with runtime versions
  Cargo.lock
  core/sr-version/src/lib.rs
  core/test-runtime/src/lib.rs
  node-template/runtime/src/lib.rs
  node-template/runtime/src/template.rs
  node/runtime/src/lib.rs
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/authorship/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/collective/src/lib.rs
  srml/contracts/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/finality-tracker/src/lib.rs
  srml/generic-asset/src/lib.rs
  srml/generic-asset/src/mock.rs
  srml/grandpa/src/mock.rs
  srml/indices/src/mock.rs
  srml/membership/src/lib.rs
  srml/offences/src/mock.rs
  srml/session/src/mock.rs
  srml/staking/src/mock.rs
  srml/support/src/traits.rs
  srml/system/Cargo.toml
  srml/system/benches/bench.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3432 client: refuse to import blocks that revert finality
  Cargo.lock
  core/client/Cargo.toml
  core/client/src/client.rs
Labels: A0-pleasereview, M4-core

#3422 Make node-template in sync with node.
  Cargo.lock
  node-template/Cargo.toml
  node-template/README.md
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/src/chain_spec.rs
  node-template/src/service.rs
  node/cli/src/factory_impl.rs
  node/cli/src/service.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  subkey/src/main.rs
  test-utils/transaction-factory/src/complex_mode.rs
  test-utils/transaction-factory/src/lib.rs
  test-utils/transaction-factory/src/simple_modes.rs
Labels: A0-pleasereview

#3381 Introduce srml/scored-pool
  Cargo.lock
  Cargo.toml
  core/sr-std/src/lib.rs
  node/runtime/src/lib.rs
  srml/scored-pool/Cargo.toml
  srml/scored-pool/src/lib.rs
  srml/scored-pool/src/mock.rs
  srml/scored-pool/src/tests.rs
Labels: A0-pleasereview

#3436 Do not call externalities without `Ext` being set
  Cargo.lock
  core/executor/src/wasm_executor.rs
  core/sr-io/with_std.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#3437 grandpa: fix finalization race condition
  core/finality-grandpa/src/environment.rs
  core/network/src/protocol/sync/extra_requests.rs
Labels: A0-pleasereview, M4-core

#3403 Value lifetime is returned from blockchain cache
  core/client/db/src/cache/list_cache.rs
  core/client/db/src/cache/mod.rs
  core/client/db/src/light.rs
  core/client/src/blockchain.rs
  core/consensus/aura/src/lib.rs
  core/consensus/babe/src/lib.rs
Labels: A8-looksgood, M4-core

#3440 Update trie crate to hashbrown usage.
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/trie/Cargo.toml
  node-template/Cargo.toml
  node/executor/Cargo.toml
  node/runtime/src/lib.rs
Labels: A0-pleasereview

#3441 grandpa: don't recreate SharedVoterSetState
  core/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, M4-core

#3385 srml/authority-discovery: Introduce srml module to sign and verify
  Cargo.lock
  Cargo.toml
  core/authority-discovery/primitives/Cargo.toml
  core/authority-discovery/primitives/src/lib.rs
  core/consensus/common/primitives/src/lib.rs
  core/state-machine/src/testing.rs
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/testing/src/genesis.rs
  srml/authority-discovery/Cargo.toml
  srml/authority-discovery/src/lib.rs
Labels: B2-breaksapi

#3446 pay out slashes to the treasury
  node/runtime/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#3444 sync: don't return on fork tree revert
  core/network/src/protocol/sync/extra_requests.rs
Labels: A8-looksgood, M4-core

#3448 Update soketto to version 0.2.3
  Cargo.lock
Labels: A2-insubstantial

#3449 aura: keystore is required for authoring
  core/consensus/aura/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3417 srml-contracts: Apply contract removals immediately
  node/runtime/src/lib.rs
  srml/contracts/src/account_db.rs
  srml/contracts/src/exec.rs
  srml/contracts/src/tests.rs
  srml/contracts/src/wasm/runtime.rs
Labels: B2-breaksapi

#3455 typo
  srml/im-online/src/lib.rs
Labels: A2-insubstantial

#3451 Improve instantiable module doc
  srml/support/src/dispatch.rs
Labels: A0-pleasereview, M3-docs

#3453 grandpa: validate honest out of scope catch ups are for the previous set
  core/finality-grandpa/src/communication/gossip.rs
Labels: A0-pleasereview, M4-core

#3450 construct_runtime: Avoid ignore not generic Event for instantiable modules.
  srml/support/src/runtime.rs
Labels: A0-pleasereview

#3458 Fix cargo description for authority discovery primitives
  core/authority-discovery/primitives/Cargo.toml
Labels: A2-insubstantial

#3464 Remove MakePayment and introduce SignedExtension docs/examples
  Cargo.lock
  core/sr-primitives/src/traits.rs
  srml/balances/src/lib.rs
  srml/contracts/src/lib.rs
  srml/example/Cargo.toml
  srml/example/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#3460 grandpa: observer doesn't send catch up messages
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/communication/tests.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/observer.rs
  core/finality-grandpa/src/tests.rs
Labels: A8-looksgood, M4-core

#3468 Fix linkemap swap
  node/runtime/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/src/lib.rs
Labels: A0-pleasereview

#3463 Pluralise newHead RPC subscription
  core/rpc/src/chain/mod.rs
  core/rpc/src/chain/tests.rs
Labels: A2-insubstantial, M6-rpcapi

#3474 Show the available key management RPC calls in README
  README.adoc
  core/cli/src/params.rs
Labels: A0-pleasereview

#3472 GRANDPA links set IDs to sessions.
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/communication/mod.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/light_import.rs
  node/runtime/src/lib.rs
  srml/babe/src/lib.rs
  srml/grandpa/src/lib.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
  srml/staking/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3467 Decl_storage: improve error msg on wrong closure signature
  srml/support/procedural/src/storage/transformation.rs
Labels: A0-pleasereview, A2-insubstantial

#3469 Fixed digest in execution proof check
  core/client/src/light/call_executor.rs
  core/test-runtime/src/system.rs
Labels: A0-pleasereview, M4-core

#3459 Clean runtime constants
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/staking/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A2-insubstantial

#3475 Allow root to force transfers
  node/runtime/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#3471 Custom deserialize impl for ApisVec
  core/rpc/src/state/tests.rs
  core/sr-version/src/lib.rs
Labels: A0-pleasereview, M6-rpcapi

#3481 Fix typo in readme
  README.adoc
Labels: A0-pleasereview, A2-insubstantial

#3486 Init blockchain cache on restart
  core/client/db/src/cache/mod.rs
  core/client/db/src/light.rs
Labels: A0-pleasereview, M4-core

#3484 Make `node-template-release` create a workspace
  scripts/node-template-release/src/main.rs
Labels: A0-pleasereview

#3454 Introduce capabilities filtering for off-chain runtime calls.
  Cargo.lock
  core/client/src/client.rs
  core/offchain/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/lib.rs
  core/primitives/src/offchain.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, M4-core

#3490 Improve `insert_key` error message on unsupported key type
  core/rpc/src/author/error.rs
Labels: A0-pleasereview, A2-insubstantial

#3382 Service factory refactor
  Cargo.lock
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/service_integration.rs
  core/rpc-servers/Cargo.toml
  core/rpc/Cargo.toml
  core/service/src/builder.rs
  core/service/src/chain_ops.rs
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  node-template/src/cli.rs
  node-template/src/main.rs
  node-template/src/service.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/rpc-client/Cargo.toml
  node/rpc/Cargo.toml
  test-utils/transaction-factory/src/complex_mode.rs
  test-utils/transaction-factory/src/lib.rs
  test-utils/transaction-factory/src/simple_modes.rs
Labels: A0-pleasereview, B2-breaksapi

#3487 Make sure that `on_before_session_ending` is called
  node/runtime/src/lib.rs
  srml/session/src/lib.rs
  srml/session/src/mock.rs
Labels: A0-pleasereview, B2-breaksapi

#3491 Fixed uncle pruning
  node/runtime/src/lib.rs
  srml/authorship/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3493 Require the `SelectChain` trait for the `SelectChain` associated type
  core/service/src/lib.rs
Labels: A0-pleasereview

#3495 Bump `multistream-select` to fix flaky tests
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#3071 Use optimized append and len storage methods in SRML.
  Cargo.lock
  node/runtime/src/lib.rs
  srml/democracy/src/lib.rs
  srml/elections/src/lib.rs
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/lib.rs
  srml/support/src/storage/hashed/generator.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/storage_items.rs
  srml/support/src/traits.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#3494 Eradicate native_equivalent
  Cargo.lock
  core/client/src/genesis.rs
  core/executor/src/native_executor.rs
  core/rpc/Cargo.toml
  core/rpc/src/state/tests.rs
  core/test-runtime/client/src/lib.rs
  core/test-runtime/src/genesismap.rs
  node-template/src/service.rs
  node/executor/src/lib.rs
Labels: A0-pleasereview

#3488 Some tweaks to offchain HTTP workers
  core/offchain/src/api/http.rs
  core/offchain/src/api/timestamp.rs
Labels: A8-looksgood, M4-core

#3500 im-online: use generic crypto
  Cargo.lock
  core/application-crypto/src/traits.rs
  core/consensus/aura/primitives/src/lib.rs
  core/rpc/src/author/mod.rs
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  srml/authority-discovery/Cargo.toml
  srml/authority-discovery/src/lib.rs
  srml/im-online/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#3499 grandpa: only send catch-up requests to authorities
  core/finality-grandpa/src/communication/gossip.rs
  core/finality-grandpa/src/communication/tests.rs
Labels: A0-pleasereview, M4-core

#3505 node: spawn babe epoch pruning in light client
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#3508 node: update flaming fir
  node/cli/res/flaming-fir.json
  node/cli/src/service.rs
  node/runtime/src/constants.rs
  node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#3507 CheckEra affects longevity of transactions
  node/runtime/src/lib.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, M4-core

#3501 Codeowners, pt.2
  CODEOWNERS
Labels: A2-insubstantial

#3509 readme: update working flaming fir node commit hash
  README.adoc
Labels: A2-insubstantial

#3404 Use ranged changes trie configuration in CT functions
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/fetcher.rs
  core/primitives/src/changes_trie.rs
  core/state-machine/src/changes_trie/build.rs
  core/state-machine/src/changes_trie/build_iterator.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/prune.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/changes_trie/surface_iterator.rs
  core/state-machine/src/lib.rs
Labels: A8-looksgood, M4-core

#3510 Make it easier to just rebuild the WASM files
  Cargo.lock
  README.adoc
  core/executor/runtime-test/build.rs
  core/test-runtime/build.rs
  core/utils/wasm-builder-runner/Cargo.toml
  core/utils/wasm-builder-runner/src/lib.rs
  core/utils/wasm-builder/Cargo.toml
  core/utils/wasm-builder/src/lib.rs
  core/utils/wasm-builder/src/wasm_project.rs
  node-template/runtime/build.rs
  node/runtime/build.rs
  scripts/build-only-wasm.sh
Labels: A0-pleasereview

#3498 Decouple Phragmen from Staking.
  Cargo.lock
  core/phragmen/Cargo.toml
  core/phragmen/src/lib.rs
  core/sr-primitives/src/lib.rs
  node/runtime/src/lib.rs
  srml/staking/Cargo.toml
  srml/staking/src/benches.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview
