Repository paritytech/substrate, pull requests merged in 2019-03, with the labels that each got.

#1900 Update parity-codec/-derive to 3.1
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/consensus/aura/Cargo.toml
  core/consensus/common/Cargo.toml
  core/consensus/rhd/Cargo.toml
  core/executor/Cargo.toml
  core/executor/wasm/Cargo.lock
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/primitives/Cargo.toml
  core/inherents/Cargo.toml
  core/network/Cargo.toml
  core/primitives/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/sr-io/Cargo.toml
  core/sr-primitives/Cargo.toml
  core/sr-version/Cargo.toml
  core/state-db/Cargo.toml
  core/state-machine/Cargo.toml
  core/test-client/Cargo.toml
  core/test-runtime/Cargo.toml
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/transaction-pool/Cargo.toml
  core/transaction-pool/graph/Cargo.toml
  core/util/fork-tree/Cargo.toml
  core/util/fork-tree/src/lib.rs
  node-template/Cargo.toml
  node-template/runtime/Cargo.toml
  node-template/runtime/wasm/Cargo.lock
  node/cli/Cargo.toml
  node/executor/Cargo.toml
  node/primitives/Cargo.toml
  node/runtime/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/Cargo.toml
  srml/aura/Cargo.toml
  srml/balances/Cargo.toml
  srml/consensus/Cargo.toml
  srml/contract/Cargo.toml
  srml/council/Cargo.toml
  srml/democracy/Cargo.toml
  srml/example/Cargo.toml
  srml/executive/Cargo.toml
  srml/fees/Cargo.toml
  srml/grandpa/Cargo.toml
  srml/indices/Cargo.toml
  srml/metadata/Cargo.toml
  srml/session/Cargo.toml
  srml/staking/Cargo.toml
  srml/sudo/Cargo.toml
  srml/support/Cargo.toml
  srml/system/Cargo.toml
  srml/timestamp/Cargo.toml
  srml/treasury/Cargo.toml
  srml/upgrade-key/Cargo.toml
Labels: A0-pleasereview, A4-gotissues

#1906 Address review comments in #1884
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
Labels: A0-pleasereview

#1891 Bump libp2p to 0.4.2
  Cargo.lock
Labels: A2-insubstantial

#1782 Stash/controller model for staking
  Cargo.lock
  core/network-libp2p/tests/test.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/aura/Cargo.toml
  srml/aura/src/lib.rs
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
  srml/democracy/src/lib.rs
  srml/executive/src/lib.rs
  srml/fees/src/lib.rs
  srml/fees/src/mock.rs
  srml/session/src/lib.rs
  srml/staking/Staking.md
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi

#1858 Refactor Sync status updates into a stream of updates
  Cargo.lock
  core/cli/src/informant.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/rpc/Cargo.toml
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
  core/service/test/src/lib.rs
Labels: A6-mustntgrumble

#1914 improve storage build type checking
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/src/voting.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1916 Get rid of wildcard imports
  core/cli/src/informant.rs
  core/cli/src/lib.rs
  core/client/src/client.rs
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/service/src/lib.rs
Labels: A8-looksgood

#1920 remove unused code
  core/cli/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/procedural/src/storage/transformation.rs
  srml/system/src/lib.rs
Labels: A0-pleasereview

#1911 Clean up session key rotation
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/session/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1619 Offline fallback for GRANDPA
  Cargo.lock
  Cargo.toml
  core/client/src/client.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/Cargo.toml
  core/finality-grandpa/primitives/src/lib.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/aux_schema.rs
  core/finality-grandpa/src/consensus_changes.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/sync.rs
  core/network/src/test/block_import.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/util/fork-tree/src/lib.rs
  node/cli/src/service.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/finality-tracker/Cargo.toml
  srml/finality-tracker/src/lib.rs
  srml/grandpa/Cargo.toml
  srml/grandpa/src/lib.rs
  srml/grandpa/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#1925 Add even more diagnostic messages
  core/network/src/service.rs
Labels: A2-insubstantial

#1931 Delete unused import in finaly-tracker module
  Cargo.lock
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/finality-tracker/Cargo.toml
  srml/finality-tracker/src/lib.rs
Labels: A4-gotissues, B2-breaksapi

#1930 Extract specific transaction pool errors.
  core/rpc/src/author/error.rs
Labels: A0-pleasereview, M6-rpcapi

#1933 Make subkey support Sr25519 crypto
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/sr25519.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  subkey/Cargo.toml
  subkey/src/cli.yml
  subkey/src/main.rs
  subkey/src/vanity.rs
Labels: A0-pleasereview

#1944 Don't mark peers sending expired messages as useless
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
Labels: A0-pleasereview

#1946 docs: Update Readme with example of how to run tests only for a single package
  README.adoc
Labels: A0-pleasereview, M3-docs

#1934 Fix old connections not being reused
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#1954 Update rw-stream-sink
  Cargo.lock
Labels: A2-insubstantial

#1950 Remove the error type from the network-libp2p crate
  core/network-libp2p/src/error.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network/src/error.rs
  core/network/src/service.rs
Labels: A0-pleasereview

#1961 make sr-api-macros doc compile with current stable
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
Labels: A0-pleasereview

#1948 Add timeouts for initialization and opening
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-looksgood

#1965 Cleanup rustdoc
  srml/staking/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/dispatch.rs
Labels: A2-insubstantial, A4-gotissues

#1959 Add network state to system.interval telemetry
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/informant.rs
Labels: A5-grumble

#1964 Remove dialing without a PeerId
  core/network-libp2p/src/service_task.rs
Labels: A0-pleasereview

#1972 More documentation improvements
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/procedural/tools/src/lib.rs
  srml/support/src/dispatch.rs
Labels: A2-insubstantial, A4-gotissues

#1976 Add a warning when banning or dropping reserved peers
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#1982 Make use of `assimilate_storage` for `GenesisConfig`
  core/service/src/chain_spec.rs
  core/sr-primitives/src/lib.rs
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/runtime.rs
Labels: A8-looksgood

#1915 Phragmén Validator Election
  core/sr-primitives/src/lib.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/Staking.md
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A3-needsresolving, A4-gotissues, B2-breaksapi

#1977 Import blocks with bad justification
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/test/block_import.rs
Labels: A0-pleasereview

#1996 fix grandpa test
  core/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial

#1975 improve modules doc generation by support macros
  srml/support/src/dispatch.rs
  srml/support/src/event.rs
Labels: A0-pleasereview, A4-gotissues

#1926 Prerequisites for `validate_block` in Cumulus
  Cargo.lock
  core/executor/src/wasm_executor.rs
  core/sr-api-macros/benches/bench.rs
  core/sr-io/Cargo.toml
  core/sr-io/without_std.rs
  core/state-machine/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
  srml/support/src/storage/mod.rs
  srml/system/src/lib.rs
Labels: A3-needsresolving, A4-gotissues

#2000 Remove warning and make `__PhantomItem` unconstructable
  srml/support/src/dispatch.rs
Labels: A0-pleasereview, A4-gotissues

#1875 Add exponential search for ancestor search
  core/network/src/sync.rs
  core/network/src/test/sync.rs
Labels: A8-looksgood

#1927 Documentation for the timestamp module
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, A5-grumble, M3-docs

#2007 Refactor test
  core/network/src/test/sync.rs
Labels: A2-insubstantial

#2008 Crypto fixes/improvements
  Cargo.lock
  README.adoc
  core/cli/src/lib.rs
  core/keyring/src/ed25519.rs
  core/keyring/src/sr25519.rs
  core/primitives/src/crypto.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/sr25519.rs
  node-template/src/chain_spec.rs
  node/cli/src/chain_spec.rs
Labels: A0-pleasereview

#2009 Add a 16MiB hard limit to Substrate packets
  core/network-libp2p/src/custom_proto/upgrade.rs
Labels: A8-looksgood

#1997 Add grandpa telemetry (+ other minor improvements)
  CONTRIBUTING.adoc
  Cargo.lock
  core/basic-authorship/Cargo.toml
  core/basic-authorship/src/basic_authorship.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/db/src/storage_cache.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/environment.rs
  core/finality-grandpa/src/finality_proof.rs
  core/finality-grandpa/src/lib.rs
  core/inherents/src/lib.rs
  core/network/src/consensus_gossip.rs
  core/primitives/src/sandbox.rs
  core/sr-api-macros/src/decl_runtime_apis.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-api-macros/src/lib.rs
  core/sr-api-macros/src/utils.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/sr-sandbox/src/lib.rs
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/metadata/src/lib.rs
  srml/support/src/dispatch.rs
  srml/support/src/double_map.rs
  srml/support/src/event.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview

#2015 Fixes for new Schnorrkel API
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/sr25519.rs
  subkey/Cargo.toml
Labels: A2-insubstantial

#2027 Update environmental version
  Cargo.lock
  core/sr-io/Cargo.toml
  core/sr-io/with_std.rs
Labels: A0-pleasereview, A2-insubstantial, A4-gotissues

#2020 Updated link for example module in template
  node-template/runtime/src/template.rs
Labels: A2-insubstantial

#2024 Remove unnecessary restrictions in executive module
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
Labels: A4-gotissues

#2030 fix indexing event breakage
  core/test-runtime/wasm/Cargo.lock
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/executive/src/lib.rs
  srml/support/src/event.rs
Labels: A0-pleasereview

#2018 Remove upgrade-key module from SRML
  Cargo.lock
  Cargo.toml
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/upgrade-key/Cargo.toml
  srml/upgrade-key/src/lib.rs
  test-utils/chain-spec-builder/Cargo.lock
  test-utils/chain-spec-builder/src/cli.yml
  test-utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#2032 Expose keyring accounts in CLI
  Cargo.lock
  README.adoc
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/keyring/Cargo.toml
  core/keyring/src/ed25519.rs
Labels: A8-looksgood

#1827 Delegation voting
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/democracy/src/lib.rs
Labels: B2-breaksapi

#1971 libp2p-0.5.0
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/config.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/secret.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/src/traits.rs
  core/network-libp2p/src/transport.rs
  core/network-libp2p/tests/test.rs
  core/network/src/config.rs
  core/network/src/lib.rs
  core/network/src/service.rs
  core/service/test/src/lib.rs
Labels: B1-releasenotes, M2-config, M4-core, M5-dependencies

#2005 Remove support for multiple network protocols
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/src/on_demand.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A0-pleasereview

#2038 Minor gossip changes
  core/finality-grandpa/src/communication.rs
  core/finality-grandpa/src/lib.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/consensus_gossip.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
Labels: A8-looksgood, M4-core

#2040 Fix grandpa aux schema migration
  core/finality-grandpa/src/aux_schema.rs
Labels: A8-looksgood, M4-core

#2046 Fix lazy initialisation bug for parametizability
  Cargo.lock
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/Cargo.toml
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/lib.rs
Labels: A8-looksgood

#2044 remove aura inherent-checking compatibility shim
  core/client/src/block_builder/api.rs
  core/consensus/aura/src/lib.rs
Labels: A0-pleasereview, A8-looksgood

#2026 Replace the incorrect `commit` keyword with `rev`
  Cargo.lock
  core/primitives/Cargo.toml
  subkey/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, A7-looksgoodtestsfail

#2041 Start the handler init timer only when the connection is established
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A8-looksgood

#2047 Account for pending insertions when pruning
  core/state-db/src/pruning.rs
Labels: A0-pleasereview

#2048 Introduce safe types for handling imbalances
  Cargo.lock
  Cargo.toml
  core/keyring/src/ed25519.rs
  core/keyring/src/sr25519.rs
  core/keystore/src/lib.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/sr25519.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/src/chain_spec.rs
  node-template/src/service.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/executor/Cargo.toml
  node/executor/src/lib.rs
  node/primitives/src/lib.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/balances/src/mock.rs
  srml/balances/src/tests.rs
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/executive/Cargo.toml
  srml/executive/src/lib.rs
  srml/fees/Cargo.toml
  srml/fees/src/lib.rs
  srml/fees/src/mock.rs
  srml/fees/src/tests.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
  srml/treasury/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#2057 Show the remote PeerId in the handler's logs
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A0-pleasereview

#2067 Keep peer info up to date
  core/network/src/protocol.rs
  core/network/src/sync.rs
Labels: A0-pleasereview

#2056 Rebuild, add a couple of tests and fix theoretical issue
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
Labels: A8-looksgood

#2042 Add a substrate-peerset crate
  Cargo.lock
  Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/custom_proto/handler.rs
  core/network-libp2p/src/custom_proto/mod.rs
  core/network-libp2p/src/custom_proto/topology.rs
  core/network-libp2p/src/custom_proto/upgrade.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/Cargo.toml
  core/network/src/service.rs
  core/peerset/Cargo.toml
  core/peerset/src/lib.rs
  core/rpc/src/system/tests.rs
Labels: A0-pleasereview

#2072 Fix #1777
  core/network-libp2p/tests/test.rs
Labels: A2-insubstantial

#2062 Make AuRa generic over cryptography
  .gitignore
  core/consensus/aura/src/lib.rs
  core/primitives/src/sr25519.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A4-gotissues

#2079 Don't sync on top of pruned blocks
  core/client/db/src/lib.rs
  core/client/src/backend.rs
  core/client/src/client.rs
  core/client/src/light/blockchain.rs
  core/network/src/sync.rs
Labels: A0-pleasereview

#2002 switch contract storage to child trie
  core/state-machine/src/testing.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/src/template.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/assets/src/lib.rs
  srml/aura/src/mock.rs
  srml/balances/src/mock.rs
  srml/consensus/src/mock.rs
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/council/src/lib.rs
  srml/democracy/src/lib.rs
  srml/example/src/lib.rs
  srml/grandpa/src/mock.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/support/src/storage/mod.rs
  srml/system/src/lib.rs
  srml/timestamp/src/lib.rs
  srml/treasury/src/lib.rs
Labels: A4-gotissues

#2087 Fix #2073
  core/network-libp2p/src/behaviour.rs
Labels: A2-insubstantial

#2086 Fix handling of justifications
  core/consensus/common/src/import_queue.rs
  core/finality-grandpa/src/authorities.rs
  core/finality-grandpa/src/import.rs
  core/network/src/sync.rs
  core/util/fork-tree/src/lib.rs
Labels: A8-looksgood, M4-core

#2078 Self-Vote for Staking (among others.)
  Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/executor/src/lib.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/consensus/src/lib.rs
  srml/session/Cargo.toml
  srml/session/src/lib.rs
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
Labels: A3-inprogress, A4-gotissues, B2-breaksapi

#2090 Fix up the offline validator API to accept controller
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#2077 Replace NodeIndex with PeerId everywhere
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/consensus/common/src/import_queue.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/network-libp2p/tests/test.rs
  core/network/src/blocks.rs
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/on_demand.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/specialization.rs
  core/network/src/sync.rs
  core/network/src/test/block_import.rs
  core/network/src/test/mod.rs
  core/network/src/test/sync.rs
  core/rpc/src/system/helpers.rs
  core/rpc/src/system/mod.rs
  core/rpc/src/system/tests.rs
Labels: A8-looksgood, B2-breaksapi, M6-rpcapi

#2037 expose linked map info to metadata
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/metadata/src/lib.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
Labels: A4-gotissues, B2-breaksapi

#2095 Version bump
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial

#2092 Rename ensure_free_balance_is to make_free_balance_be
  srml/balances/src/lib.rs
  srml/contract/src/account_db.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
Labels: A2-insubstantial, A4-gotissues

#2097 Reduce grandpa interval for substrate node
  node/cli/src/service.rs
Labels: A2-insubstantial

#2089 Don't print dozens of the times the handler init warning
  core/network-libp2p/src/custom_proto/handler.rs
Labels: A2-insubstantial

#2102 Properly distinguish in/out connections in the PSM
  core/peerset/src/lib.rs
Labels: A0-pleasereview

#2103 Fix hardcoded values in the PSM config
  core/network-libp2p/src/service_task.rs
Labels: A2-insubstantial

#2101 Always accept incoming connections
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#2100 Directly connect if notice that ban has expired
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview

#2104 CLI option to enable authoring when offline
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/consensus/aura/src/lib.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
  node-template/src/service.rs
  node/cli/src/service.rs
Labels: A0-pleasereview

#2107 Forgot to handle Banned in inject_connected
  core/network-libp2p/src/custom_proto/behaviour.rs
Labels: A0-pleasereview, A2-insubstantial

#2055 impl MakePayment for balances instances
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
Labels: A7-looksgoodcantmerge

#2105 core: cli flag to disable grandpa
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/service/src/config.rs
  core/service/test/src/lib.rs
  node/cli/src/service.rs
Labels: A0-pleasereview, M4-core

#2096 bond_extra should be authorised only from stash
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/src/lib.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#1942 Initial: Offchain Workers
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/client/src/block_builder/block_builder.rs
  core/client/src/call_executor.rs
  core/client/src/client.rs
  core/client/src/genesis.rs
  core/client/src/light/call_executor.rs
  core/client/src/runtime_api.rs
  core/executor/src/wasm_executor.rs
  core/finality-grandpa/src/tests.rs
  core/inherents/src/lib.rs
  core/inherents/src/pool.rs
  core/offchain/Cargo.toml
  core/offchain/primitives/Cargo.toml
  core/offchain/primitives/src/lib.rs
  core/offchain/src/api.rs
  core/offchain/src/lib.rs
  core/primitives/src/lib.rs
  core/rpc/src/state/mod.rs
  core/rpc/src/state/tests.rs
  core/service/Cargo.toml
  core/service/src/chain_spec.rs
  core/service/src/components.rs
  core/service/src/config.rs
  core/service/src/lib.rs
  core/service/test/src/lib.rs
  core/sr-api-macros/src/impl_runtime_apis.rs
  core/sr-io/with_std.rs
  core/sr-io/without_std.rs
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/state-machine/src/basic.rs
  core/state-machine/src/ext.rs
  core/state-machine/src/lib.rs
  core/state-machine/src/overlayed_changes.rs
  core/state-machine/src/testing.rs
  core/test-client/src/lib.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/src/system.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/example/src/lib.rs
  srml/executive/src/lib.rs
  srml/support/src/dispatch.rs
  srml/system/src/lib.rs
  srml/timestamp/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi, M4-core

#2098 srml: consensus: kill storage
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/consensus/src/lib.rs
  srml/consensus/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#2060 fix macro internal use with $crate
  srml/support/src/dispatch.rs
  srml/support/src/runtime.rs
  srml/support/test/tests/instance.rs
Labels: A4-gotissues, A8-looksgood

#2118 Fix offchain-worker-execution default value
  core/cli/src/params.rs
Labels: A8-looksgood

#2115 Replace Overflow-Prone Operations in Staking with Saturating Arithmetic
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview

#2088 Improvements to system_networkState
  Cargo.lock
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/custom_proto/behaviour.rs
  core/network-libp2p/src/lib.rs
  core/network-libp2p/src/service_task.rs
  core/peerset/src/lib.rs
  core/rpc/src/system/tests.rs
Labels: A7-looksgoodcantmerge

#2059 improve decl storage doc
  srml/support/procedural/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#1943 Documentation for balances module
  srml/balances/src/lib.rs
  srml/contract/src/lib.rs
  srml/support/src/traits.rs
Labels: A4-gotissues, A6-mustntgrumble, M3-docs

#2119 Update AccountId to use sr25519 in node-template
  node-template/runtime/src/lib.rs
  node-template/src/chain_spec.rs
Labels: A0-pleasereview, A2-insubstantial

#2124 Introduce `ReservableCurrency` Trait in Balances Module
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/balances/src/tests.rs
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
  srml/staking/src/tests.rs
  srml/support/src/traits.rs
  srml/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2125 core: network: reduce log level of peer drop messages
  core/network/src/service.rs
Labels: A0-pleasereview, A2-insubstantial

#2126 Use NativeWhenPossible for offchain worker.
  core/cli/src/params.rs
Labels: A0-pleasereview

#2128 Fix subtle indices bug
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/balances/src/lib.rs
  srml/indices/src/address.rs
Labels: A2-insubstantial, B2-breaksapi

#1995 Make some txpool logs a bit more compact
  Cargo.lock
  core/basic-authorship/src/basic_authorship.rs
  core/sr-primitives/src/lib.rs
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/pool.rs
  node-template/runtime/src/lib.rs
Labels: A4-gotissues, A8-looksgood, M4-core

#2081 Decouple contract from balances
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/contract/Cargo.toml
  srml/contract/src/account_db.rs
  srml/contract/src/exec.rs
  srml/contract/src/gas.rs
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
  srml/contract/src/wasm/runtime.rs
  srml/support/src/traits.rs
Labels: A0-pleasereview

#1999 Documentation for system module
  srml/system/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2132 Ensure timestamp config makes sense.
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/src/chain_spec.rs
  node/cli/src/chain_spec.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/aura/src/lib.rs
  srml/aura/src/mock.rs
  srml/session/src/lib.rs
  srml/staking/src/mock.rs
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2135 Track peers in network-libp2p
  core/network-libp2p/src/service_task.rs
Labels: A8-looksgood

#1918 storage doublemap in decl_storage
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/example/src/lib.rs
  srml/metadata/src/lib.rs
  srml/support/procedural/src/lib.rs
  srml/support/procedural/src/storage/impls.rs
  srml/support/procedural/src/storage/mod.rs
  srml/support/procedural/src/storage/transformation.rs
  srml/support/src/double_map.rs
  srml/support/src/hashable.rs
  srml/support/src/lib.rs
  srml/support/src/metadata.rs
  srml/support/src/storage/generator.rs
  srml/support/src/storage/mod.rs
  srml/support/src/storage/unhashed/generator.rs
  srml/support/src/storage/unhashed/mod.rs
  srml/support/test/tests/instance.rs
Labels: A7-looksgoodcantmerge, B2-breaksapi

#2130 Use prefixed keys for trie node.
  Cargo.lock
  core/client/Cargo.toml
  core/client/db/Cargo.toml
  core/client/db/src/lib.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/fetcher.rs
  core/executor/wasm/Cargo.lock
  core/primitives/Cargo.toml
  core/sr-io/Cargo.toml
  core/state-db/src/lib.rs
  core/state-db/src/test.rs
  core/state-machine/Cargo.toml
  core/state-machine/src/backend.rs
  core/state-machine/src/changes_trie/changes_iterator.rs
  core/state-machine/src/changes_trie/mod.rs
  core/state-machine/src/changes_trie/storage.rs
  core/state-machine/src/proving_backend.rs
  core/state-machine/src/trie_backend.rs
  core/state-machine/src/trie_backend_essence.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  core/trie/Cargo.toml
  core/trie/src/lib.rs
  node-template/Cargo.toml
  node-template/runtime/wasm/Cargo.lock
  node/executor/Cargo.toml
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A0-pleasereview, A4-gotissues, B2-breaksapi

#2136 Fix a race conditon in the pool when transactions are imported during pruning.
  Cargo.lock
  core/transaction-pool/graph/Cargo.toml
  core/transaction-pool/graph/src/base_pool.rs
  core/transaction-pool/graph/src/future.rs
  core/transaction-pool/graph/src/pool.rs
  core/transaction-pool/graph/src/ready.rs
Labels: A8-looksgood, M4-core

#2117 allow trailling comma in decl_event
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/support/src/event.rs
Labels: A6-mustntgrumble, A7-looksgoodcantmerge

#2140 fixed some typo
  srml/balances/src/lib.rs
Labels: A4-gotissues

#2045 Documentation for Contract Module
  srml/contract/src/lib.rs
  srml/contract/src/tests.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2108 Refactor DigestItem
  .gitignore
  Cargo.lock
  core/consensus/aura/primitives/Cargo.toml
  core/consensus/aura/primitives/src/lib.rs
  core/consensus/aura/src/lib.rs
  core/finality-grandpa/src/lib.rs
  core/network/src/consensus_gossip.rs
  core/network/src/lib.rs
  core/network/src/message.rs
  core/network/src/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mod.rs
  core/primitives/src/crypto.rs
  core/primitives/src/ed25519.rs
  core/service/src/lib.rs
  core/sr-primitives/src/generic/digest.rs
  core/sr-primitives/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/wasm/Cargo.lock
  node-template/src/service.rs
  node/cli/src/service.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A8-looksgood, B2-breaksapi

#2141 Use a context prefix for SS58 hash
  core/primitives/src/crypto.rs
  core/primitives/src/ed25519.rs
  core/primitives/src/sr25519.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
Labels: A7-looksgoodtestsfail

#2137 Proxy voting
  core/primitives/src/crypto.rs
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/src/seats.rs
  srml/democracy/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2134 Extended Balance Type for Staking's Election
  core/sr-primitives/src/lib.rs
  core/sr-primitives/src/traits.rs
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/src/lib.rs
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/phragmen.rs
  srml/staking/src/tests.rs
  srml/support/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#2017 Add documentation to the Sudo module
  srml/sudo/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#1412 Move authorities interface from Core to consensus
  Cargo.lock
  README.adoc
  core/client/db/Cargo.toml
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/error.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/client/src/light/call_executor.rs
  core/client/src/light/fetcher.rs
  core/client/src/runtime_api.rs
  core/consensus/aura/Cargo.toml
  core/consensus/aura/src/lib.rs
  core/consensus/authorities/Cargo.toml
  core/consensus/authorities/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/error.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/import.rs
  core/finality-grandpa/src/tests.rs
  core/network/src/chain.rs
  core/rpc/src/state/tests.rs
  core/service/test/src/lib.rs
  core/sr-api-macros/tests/decl_and_impl.rs
  core/test-client/src/client_ext.rs
  core/test-runtime/Cargo.toml
  core/test-runtime/src/lib.rs
  core/test-runtime/wasm/Cargo.lock
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node-template/runtime/Cargo.toml
  node-template/runtime/src/lib.rs
  node-template/runtime/wasm/Cargo.lock
  node-template/src/service.rs
  node/runtime/Cargo.toml
  node/runtime/src/lib.rs
  node/runtime/wasm/Cargo.lock
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/council/src/seats.rs
Labels: A0-pleasereview, A4-gotissues, B2-breaksapi

#2043 Documentation for consensus module
  srml/consensus/src/lib.rs
  srml/consensus/src/tests.rs
  srml/session/src/lib.rs
Labels: A0-pleasereview, A4-gotissues, M3-docs

#2151 Fix compile errors in test suite
  core/test-runtime/wasm/target/wasm32-unknown-unknown/release/substrate_test_runtime.compact.wasm
  node/runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm
  srml/consensus/src/tests.rs
Labels: A4-gotissues

#2150 Use libp2p 0.6.0 instead of a custom branch
  Cargo.lock
  core/consensus/common/Cargo.toml
  core/network-libp2p/Cargo.toml
  core/network-libp2p/src/behaviour.rs
  core/peerset/Cargo.toml
Labels: A2-insubstantial

#2153 Add support for mDNS
  core/cli/src/lib.rs
  core/cli/src/params.rs
  core/network-libp2p/src/behaviour.rs
  core/network-libp2p/src/config.rs
  core/network-libp2p/src/service_task.rs
  core/service/test/src/lib.rs
Labels: A0-pleasereview, A3-inprogress

#2152 Use [u8; 4] for well known cache keys
  core/client/db/Cargo.toml
  core/client/db/src/cache/mod.rs
  core/client/db/src/lib.rs
  core/client/db/src/light.rs
  core/client/src/backend.rs
  core/client/src/blockchain.rs
  core/client/src/client.rs
  core/client/src/in_mem.rs
  core/client/src/light/backend.rs
  core/client/src/light/blockchain.rs
  core/consensus/aura/src/lib.rs
  core/consensus/common/src/block_import.rs
  core/consensus/common/src/import_queue.rs
  core/consensus/common/src/lib.rs
  core/finality-grandpa/src/import.rs
Labels: A0-pleasereview
