Repository paritytech/substrate, pull requests merged in 2020-06, with the labels that each got.

#6171 Add a Substrate networking Grafana dashboard template
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
Labels: A0-pleasereview, B1-clientnoteworthy

#6170 Update import metrics and add verification time
  client/network/test/src/block_import.rs
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/metrics.rs
Labels: A0-pleasereview

#6187 Update proposer metrics only on successfull block
  client/basic-authorship/src/basic_authorship.rs
Labels: A2-insubstantial, B0-silent

#6207 Fix Rustdoc Build
  bin/node/testing/src/bench.rs
  client/cli/src/lib.rs
  client/consensus/slots/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  primitives/runtime/src/offchain/storage_lock.rs
Labels: B0-silent, B2-breaksapi

#6205 impl FindAuthor<T::AuthorityId> for Aura
  frame/aura/src/lib.rs
Labels: B0-silent, B2-breaksapi

#6213 Remove ReportHandle
  client/network/src/lib.rs
Labels: A2-insubstantial, B0-silent

#6191 pallet-evm ensure gas_price + Storage getter
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: B0-silent, B2-breaksapi

#6185 Allow ExistentialDeposit = 0
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/support/src/traits.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#6173 Accept new Phragmén solutions if they are epsilon better + Better pre-inclusion checks.
  bin/node/runtime/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/phragmen/fuzzer/src/common.rs
  primitives/phragmen/fuzzer/src/equalize.rs
  primitives/phragmen/src/lib.rs
  primitives/phragmen/src/reduce.rs
  primitives/phragmen/src/tests.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6176 refactor CI
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#6156 Generalised proxies
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/network/test/src/block_import.rs
  frame/balances/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/proxying.rs
  frame/democracy/src/types.rs
  frame/elections/src/lib.rs
  frame/elections/src/tests.rs
  frame/proxy/Cargo.toml
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
  frame/support/src/traits.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#6217 Do not invalidate first tx of the block if initialization is too heavy
  client/basic-authorship/src/basic_authorship.rs
Labels: A6-mustntgrumble, B0-silent

#6227 Fix ms display in log files
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6228 Make dev profile faster by compiling deps with opt-level=3
  Cargo.toml
Labels: A0-pleasereview, B0-silent

#6229 Fix libp2p features
  Cargo.lock
  Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/telemetry/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent

#6231 Split tx pool and offchain notification handling
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent

#6233 Add run_full_node, run_light_node and print_node_infos to the API
  client/cli/src/runner.rs
Labels: B0-silent

#6238 The link to getting-started was obsolete.
  README.md
Labels: A2-insubstantial, B0-silent, F5-documentation 📄

#6208 Use Subscription Manager from `jsonrpc-pubsub`
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-api/src/lib.rs
  client/rpc-api/src/subscriptions.rs
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/chain_light.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/chain/tests.rs
  client/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/state/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  frame/contracts/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#6249 Fix peerset not filtering incoming connections in reserved-only
  client/peerset/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#6232 Fix service tests not calling update_chain
  client/network/src/service.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6252 Revert "Use Subscription Manager from `jsonrpc-pubsub`"
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-api/src/lib.rs
  client/rpc-api/src/subscriptions.rs
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/chain_light.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/chain/tests.rs
  client/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/state/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  frame/contracts/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A2-insubstantial, B0-silent, B2-breaksapi, M4-core

#6255 impl_opaque_keys should allow doc comments
  primitives/runtime/src/traits.rs
Labels: B0-silent

#6234 Use number of downloaded blocks for test
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview

#6251 Sentry nodes and validator nodes also imply reserved
  client/network/src/service.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#6253 Remove pre-simple-payout code from staking
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#6245 Rename all the election operations
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  docs/CODEOWNERS
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/staking/Cargo.toml
  frame/staking/fuzzer/Cargo.lock
  frame/staking/fuzzer/Cargo.toml
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  primitives/arithmetic/src/rational128.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/benches/phragmen.rs
  primitives/npos-elections/compact/Cargo.toml
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/compact/src/staked.rs
  primitives/npos-elections/fuzzer/.gitignore
  primitives/npos-elections/fuzzer/Cargo.lock
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/src/balance_solution.rs
  primitives/npos-elections/fuzzer/src/common.rs
  primitives/npos-elections/fuzzer/src/reduce.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/node.rs
  primitives/npos-elections/src/reduce.rs
  primitives/npos-elections/src/tests.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#6123 Make transaction pool prune transactions only of canonical blocks
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/api/src/backend.rs
  client/api/src/client.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_new_block.rs
  client/finality-grandpa/src/until_imported.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/transaction-pool/graph/benches/basics.rs
  client/transaction-pool/graph/src/lib.rs
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
  primitives/blockchain/Cargo.toml
  primitives/blockchain/src/header_metadata.rs
  primitives/transaction-pool/Cargo.toml
  primitives/transaction-pool/src/pool.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/transaction-pool/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A3-needsresolving, B1-clientnoteworthy

#6236 Allow "anonymous" proxied accounts
  bin/node/runtime/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/proxy/Cargo.toml
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#6214 Enable fixed point u128
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  frame/balances/src/tests.rs
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/fixed_point.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#6246 Fix the metered unbounded sender/recievers
  client/rpc/src/system/tests.rs
  client/service/src/client/client.rs
  client/service/src/status_sinks.rs
  primitives/utils/src/metrics.rs
  primitives/utils/src/mpsc.rs
Labels: A8-mergeoncegreen, B0-silent

#6276 Fix transaction pruning in tx-pool
  Cargo.lock
  bin/node/cli/src/service.rs
  client/api/src/client.rs
  client/basic-authorship/src/basic_authorship.rs
  client/consensus/manual-seal/src/lib.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  primitives/transaction-pool/src/pool.rs
Labels: A8-mergeoncegreen, B0-silent

#6277 client/api: fix possible deadlock when comparing with itself
  client/api/src/in_mem.rs
Labels: A8-mergeoncegreen, B0-silent

#6267 Make all features explicit
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/utils.rs
  client/executor/runtime-test/src/lib.rs
  client/service/Cargo.toml
  client/transaction-pool/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#6254 Use Subscription Manager from `jsonrpc-pubsub`: The Sequel
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-api/src/lib.rs
  client/rpc-api/src/subscriptions.rs
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/chain_light.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/chain/tests.rs
  client/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/state/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  frame/contracts/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A8-mergeoncegreen, B2-breaksapi

#6283 Temporary and Heavy Weights for Society Pallet
  frame/society/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#6282 Weights for Indices Pallet
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/indices/Cargo.toml
  frame/indices/src/benchmarking.rs
  frame/indices/src/lib.rs
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/tests.rs
  frame/utility/src/benchmarking.rs
Labels: A0-pleasereview, B2-breaksapi

#6293 Fix typo: eror -> error
  client/db/src/parity_db.rs
Labels: B0-silent

#6291 Fix typo: PRORITY -> PRIORITY
  frame/support/src/traits.rs
Labels: B0-silent, B2-breaksapi

#6288 Fix transaction pool & network issues
  client/network/src/protocol.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview, B0-silent

#6178 Use `sign_with` for signing grandpa's outgoing message
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  primitives/finality-grandpa/src/lib.rs
Labels: A5-grumble, B0-silent

#6258 Revalidation tweak & logging for transaction pool
  client/basic-authorship/src/basic_authorship.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
Labels: A8-mergeoncegreen, B0-silent

#6174 Allow adding a prefix to the informant
  Cargo.lock
  client/cli/src/runner.rs
  client/informant/Cargo.toml
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/network/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#6308 Transaction pool added missed comment
  client/transaction-pool/src/revalidation.rs
Labels: A2-insubstantial, B0-silent

#6247 Add a test for lots of nodes connecting at the same time
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent

#6307 Introduce frozen indices.
  bin/node/runtime/src/lib.rs
  frame/indices/src/benchmarking.rs
  frame/indices/src/lib.rs
  frame/indices/src/tests.rs
Labels: A8-mergeoncegreen, B1-runtimenoteworthy, B2-breaksapi, runtime-migration

#6235 new crate sc-light
  Cargo.lock
  Cargo.toml
  client/light/Cargo.toml
  client/light/src/backend.rs
  client/light/src/blockchain.rs
  client/light/src/call_executor.rs
  client/light/src/fetcher.rs
  client/light/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/test/Cargo.toml
  client/service/test/src/client/light.rs
  test-utils/client/Cargo.toml
  test-utils/client/src/lib.rs
  test-utils/runtime/client/Cargo.toml
  test-utils/runtime/client/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#6310 Fix ui tests for latest rust stable
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
Labels: A2-insubstantial, B0-silent

#6313 Expose chain_spec and service in node-template
  bin/node-template/node/src/lib.rs
Labels: B0-silent

#6314 Reduce the lots_of_incoming_peers_works test load
  client/network/src/service/tests.rs
Labels: A2-insubstantial, B0-silent

#6302 Fix nits in rpc error display.
  client/rpc-api/src/author/error.rs
  client/transaction-pool/src/api.rs
  primitives/runtime/src/transaction_validity.rs
Labels: A8-mergeoncegreen

#6237 "OR gate" for EnsureOrigin
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/staking/src/lib.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6223 New CI image
  .gitlab-ci.yml
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent, M1-ci

#6221 Add a feature to create automatically a random temporary directory for base path & remove `Clone`
  Cargo.lock
  bin/node/cli/src/cli.rs
  bin/node/cli/tests/temp_base_path_works.rs
  bin/node/inspect/src/cli.rs
  client/cli/Cargo.toml
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
  client/cli/src/commands/import_blocks_cmd.rs
  client/cli/src/commands/mod.rs
  client/cli/src/commands/purge_chain_cmd.rs
  client/cli/src/commands/revert_cmd.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/database_params.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/keystore_params.rs
  client/cli/src/params/mod.rs
  client/cli/src/params/network_params.rs
  client/cli/src/params/node_key_params.rs
  client/cli/src/params/offchain_worker_params.rs
  client/cli/src/params/pruning_params.rs
  client/cli/src/params/shared_params.rs
  client/cli/src/params/transaction_pool_params.rs
  client/cli/src/runner.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A3-inprogress

#6320 Find the alive incoming entry on disconnect of an `Incoming` peer.
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A8-mergeoncegreen, B0-silent

#6327 Impl Debug and Display for Ss58AddressFormat when compiled with std
  primitives/core/src/crypto.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6325 transaction-pool: expose blocking api for tx submission
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  primitives/transaction-pool/src/pool.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low, D2-breaksapi, M4-core

#6322 Pruned and resubmitted metrics in transaction pool
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/metrics.rs
Labels: A0-pleasereview, B0-silent

#6336 Enable wasmtime on node-template
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6296 Adds support for storage parameter types
  frame/support/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6338 Basic documentation for Scheduler pallet
  frame/scheduler/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, C1-low

#6326 Fix check-line-width CI script
  .maintain/gitlab/check_line_width.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6180 client: use appropriate ExecutionContext for initial sync / regular import
  client/cli/src/arg_enums.rs
  client/cli/src/commands/mod.rs
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
  client/service/src/client/client.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6341 Fix transaction pool event sending
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#6340 Deprecate FunctionOf and remove its users
  frame/contracts/src/lib.rs
  frame/evm/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  frame/utility/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi, B3-apinoteworthy, C1-low

#6330 Add events for balance reserve and unreserve functions
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/staking/src/tests.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6333 Update contributing guide with new label policy
  docs/CONTRIBUTING.adoc
  docs/PULL_REQUEST_TEMPLATE.md
Labels: A0-pleasereview, B0-silent, C1-low

#6323 add extend_lock for StorageLock
  primitives/runtime/src/offchain/storage_lock.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6279 pallet-evm add get(fn) to AccountStorages
  frame/evm/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi, D2-breaksapi

#6348 Add IPC support
  Cargo.lock
  client/cli/src/commands/mod.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: B0-silent, C1-low

#6363 expose constants in pallet_recovery trait
  frame/recovery/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, B2-breaksapi, C1-low

#6356 Impl integrity test for runtime
  Cargo.lock
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/construct_runtime.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, C1-low

#6220 historical slashing w ocw w adhoc tree creation
  client/db/src/lib.rs
  frame/session/Cargo.toml
  frame/session/src/historical/mod.rs
  frame/session/src/historical/offchain.rs
  frame/session/src/historical/onchain.rs
  frame/session/src/historical/shared.rs
  primitives/core/src/offchain/storage.rs
  primitives/core/src/offchain/testing.rs
  primitives/state-machine/src/testing.rs
Labels: A8-mergeoncegreen, B2-breaksapi, D2-breaksapi

#6361 [CI] Auto-label new PRs according to draft status
  .github/workflows/auto-label-prs.yml
Labels: A2-insubstantial, B0-silent, C1-low

#6332 Split the service initialisation up into seperate functions
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/informant/Cargo.toml
  client/informant/src/lib.rs
  client/offchain/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/service/src/task_manager.rs
  client/transaction-pool/src/lib.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/utils/Cargo.toml
  primitives/utils/src/lib.rs
  primitives/utils/src/status_sinks.rs
Labels: A6-seemsok, B5-clientnoteworthy, C1-low

#6365 [CI] Add label enforcement
  .gitlab-ci.yml
  .maintain/gitlab/check_labels.sh
  .maintain/gitlab/lib.sh
Labels: B0-silent, C1-low

#6368 vesting: Force Vested Transfer
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, B7-runtimenoteworthy, C1-low

#6370 client/authority-discovery: Don't add own address to priority group
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#6344 .gitlab-ci.yml: Run promtool on Prometheus alerting rules
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6369 Use /dns/ instead of /dns4/
  .maintain/sentry-node/docker-compose.yml
  bin/node/cli/res/flaming-fir.json
  client/network/src/discovery.rs
  client/network/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6300 add system_dryRun
  Cargo.lock
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  utils/frame/rpc/system/Cargo.toml
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy

#6281 Fix how BlockAttributes are encoded by LightClientHandler
  client/network/src/block_requests.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol/message.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6375 Allow Sudo to do anything
  .maintain/gitlab/check_runtime.sh
  docs/CONTRIBUTING.adoc
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6319 Stored call in multisig
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi, D9-needsaudit👮

#6334 Fix the broken weight multiplier update function
  Cargo.lock
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests.rs
  frame/system/src/lib.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/src/fixed_point.rs
Labels: A8-mergeoncegreen, B2-breaksapi, B5-clientnoteworthy, C3-medium, D1-runtime-migration

#6383 Restrict remove_proxies to only default (most permissive) values
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D9-needsaudit👮

#6377 Remove penalty on duplicate Status message
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#6384 `decl_module!` print better error on duplicate reserved keyword
  frame/support/src/dispatch.rs
  frame/support/test/tests/decl_module_ui.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr
Labels: A0-pleasereview, B0-silent, C1-low

#6385 Fix FixedPointNumber: zero is not positive.
  primitives/arithmetic/src/fixed_point.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6364 Allow empty values in the storage
  Cargo.lock
  frame/executive/src/lib.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/testing.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/lib.rs
  test-utils/runtime/Cargo.toml
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D3-breaksconsensus

#6349 Pallet: Atomic Swap
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/atomic-swap/Cargo.toml
  frame/atomic-swap/src/lib.rs
  frame/atomic-swap/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, B7-runtimenoteworthy, C1-low

#6381 Runtime interface to add support for tracing from wasm
  Cargo.lock
  bin/node/runtime/Cargo.toml
  client/executor/Cargo.toml
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/tracing/Cargo.toml
  primitives/tracing/src/lib.rs
  primitives/tracing/src/proxy.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low

#6399 Update s3 artifact url
  .maintain/flamingfir-deploy.sh
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6080 Increase network buffer sizes even more
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6407 Fix cargo unleash check for the atomic-swap pallet
  frame/atomic-swap/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6225 Babe VRF Signing in keystore
  Cargo.lock
  client/consensus/babe/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/tests.rs
  client/keystore/Cargo.toml
  client/keystore/src/lib.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/core/src/vrf.rs
Labels: A6-seemsok, B0-silent, C1-low

#6412 Update `libp2p-ping`.
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6411 Remove --legacy-network-protocol CLI flag
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6417 Scale and increase validator count
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6420 Expose Constants from Proxy Pallet
  frame/proxy/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6343 .maintain/monitoring: Add alerting rule tests
  .gitlab-ci.yml
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#6410 [CI] Label PRs if polkadot companion build fails
  .github/workflows/polkadot-companion-labels.yml
Labels: B0-silent, C1-low

#6416 Print bad mandatory error
  frame/system/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#6429 Track last blocks in informant display
  client/informant/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6434 Simple Docs for Atomic Swap Pallet
  frame/atomic-swap/src/lib.rs
Labels: A0-pleasereview

#6430 More descriptive error message when invalid slot duration is used
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6408 Root origin use no filter by default. Scheduler and Democracy dispatch without asserting BaseCallFilter
  frame/democracy/src/tests.rs
  frame/scheduler/src/lib.rs
  frame/support/src/origin.rs
  frame/system/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low, D9-needsaudit👮

#6431 Allow decl-module to have a where clause with trailing comma
  frame/support/src/dispatch.rs
  frame/support/test/tests/system.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6425 .gitlab-ci.yml: Use promtool from paritytech/tools:latest image
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6424 Update sync chain info on own block import
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6414 client/authority-discovery: Compare PeerIds and not Multihashes
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#6438 Add propagated transactions counter to network
  client/network/src/protocol.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low

#6441 add interruptible to kubernetes jobs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6445 Avoid multisig reentrancy
  frame/multisig/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D9-needsaudit👮

#6451 Fix Babe secondary plain slots claiming
  client/consensus/babe/src/authorship.rs
  client/keystore/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C7-high

#6405 Add Whitelist to DB Tracking in Benchmarks Pipeline
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/db/src/bench.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  primitives/externalities/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/read_only.rs
Labels: A3-inprogress

#6444 sp-npos-elections should not depend on itself
  Cargo.lock
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6447 [CI] Don't autolabel insubstantial PRs 'pleasereview'
  .github/workflows/auto-label-prs.yml
Labels: A2-insubstantial, B0-silent, C1-low

#6440 Change term "extrinsic" to "transaction" in network/service
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6446 node: spawn block authoring and grandpa voter as blocking tasks
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/service/src/lib.rs
  client/service/src/task_manager.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6421 pallet-atomic-swap: generialized swap action
  bin/node/runtime/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/atomic-swap/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6435 Fix issues with `Operational` transactions validity and prioritization.
  frame/system/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6456 `pallet-staking`: Expose missing consts
  frame/staking/src/lib.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6463 fix pallet-collective events docs
  frame/collective/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#6470 [CI] Don't tag PRs on polkadot companion job cancels
  .github/workflows/polkadot-companion-labels.yml
Labels: A2-insubstantial, B0-silent, C1-low

#6475 Add regression analysis to DB Tracking
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A3-inprogress

#6460 network: remove unused variable
  client/network/src/protocol/sync.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6458 Avoid panic on dropping a `sc_network::service::out_events::Receiver`.
  client/network/src/service/out_events.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6454 Optimize offchain worker api by re-using http-client
  Cargo.lock
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/api/http.rs
  client/offchain/src/api/http_dummy.rs
  client/offchain/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6476 Remove lingering runtime upgrades
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/migration.rs
  frame/indices/src/lib.rs
  frame/multisig/src/lib.rs
  frame/staking/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D1-runtime-migration

#6400 impl Debug for sc_service::Configuration
  client/chain-spec/src/lib.rs
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/db/src/lib.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/src/task_manager.rs
  client/service/test/src/lib.rs
  primitives/database/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6484 Fix `sp-api` handling of multiple arguments
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6457 Fix the browser node and ensure it doesn't colour the informant output
  Cargo.lock
  client/cli/src/config.rs
  client/informant/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/offline_tracker.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6487 Bound some missing bound for elevated trait
  frame/balances/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6480 `pallet-scheduler`: Check that `when` is not in the past
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#6472 client/network/service: Add primary dimension to connection metrics
  client/network/src/service.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6436 Ensure the listen addresses are consistent with the transport
  client/network/src/error.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#6382 pallet-contracts: migrate to nested storage transaction mechanism
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/restoration.wat
  frame/contracts/src/account_db.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi, C1-low

#6478 seal: Refactor ext_gas_price
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6464 seal: Remove ext_dispatch_call and ext_get_runtime_storage
  bin/node/runtime/src/lib.rs
  frame/contracts/fixtures/dispatch_call.wat
  frame/contracts/fixtures/dispatch_call_then_trap.wat
  frame/contracts/fixtures/get_runtime_storage.wat
  frame/contracts/fixtures/restoration.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low

#6374 Generic Normalize impl for arithmetic and npos-elections
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/normalize.rs
  primitives/arithmetic/fuzzer/src/per_thing_rational.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/arithmetic/src/traits.rs
  primitives/npos-elections/benches/phragmen.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/tests.rs
  primitives/runtime/src/lib.rs
  test-utils/src/lib.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#6474 Extract frame_system SignedExtensions into separate files.
  frame/system/src/extensions/check_genesis.rs
  frame/system/src/extensions/check_mortality.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/extensions/check_spec_version.rs
  frame/system/src/extensions/check_tx_version.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/extensions/mod.rs
  frame/system/src/lib.rs
  frame/system/src/mock.rs
  frame/system/src/offchain.rs
  frame/system/src/tests.rs
  frame/system/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6461 Allow where clause in benchmarking
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6495 client: fix print of slot duration on startup
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6386 Add DB Read/Write Tracking to Benchmarking Pipeline
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/db/src/bench.rs
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  primitives/externalities/src/lib.rs
  primitives/runtime-interface/src/impls.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/read_only.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6489 Update CODEOWNERS
  docs/CODEOWNERS
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#6485 Panic on invalid unsigned election solution.
  frame/staking/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6502 Import hex_literal into runtime only for benchmarks.
  bin/node/runtime/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6473 .maintain/sentry-node: Remove UI and update Prometheus target
  .maintain/sentry-node/docker-compose.yml
  .maintain/sentry-node/prometheus/prometheus.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6496 Staking Payout Creates Controller
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low
