Repository paritytech/substrate, pull requests merged in 2020-11, with the labels that each got.

#7123 Add ss58 registration details for Stafi
  ss58-registry.json
Labels: A2-insubstantial, A3-stale, B0-silent, C1-low

#7476 Fix Session Benchmarks
  frame/staking/src/benchmarking.rs
  frame/staking/src/testing_utils.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7278 Introduce storage types, to builds abstraction on storage (to be used in pallet attribute macro)
  frame/support/src/hash.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/mod.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7483 Update MILLISECS_PER_BLOCK comments
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/constants.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7480 Fix `on_runtime_upgrade` weight recording
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#7388 Made correction in sp-tracing macros to use level parameter #7348
  primitives/tracing/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7485 Remove development TODO from public doc comment
  frame/system/src/offchain.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7486 add synesthesia network
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7484 Exclude basic-authorship-proposer from the continuous tasks alert
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#7078 Allow BabeConsensusDataProvider fork existing chain
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/node/runtime/Cargo.toml
  client/api/src/execution_extensions.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/consensus/babe.rs
  client/executor/src/native_executor.rs
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7454 grandpa: store the authority id that is used for voting per round
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
  primitives/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7496 Prevent publishing of pallet_contracts for now
  frame/contracts/Cargo.toml
  frame/contracts/common/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/contracts/rpc/runtime-api/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7145 CI: markdown link checker
  .github/workflows/md-link-check.yml
  .github/workflows/mlc_config.json
  .maintain/chaostest/README.md
  .maintain/gitlab/check_line_width.sh
  README.md
  bin/node-template/README.md
  client/block-builder/README.md
  client/block-builder/src/lib.rs
  client/chain-spec/README.md
  client/chain-spec/src/lib.rs
  client/consensus/babe/README.md
  client/consensus/babe/src/lib.rs
  docs/PULL_REQUEST_TEMPLATE.md
  docs/SECURITY.md
  frame/balances/README.md
  frame/balances/src/lib.rs
  frame/benchmarking/README.md
  frame/example-offchain-worker/README.md
  frame/example-offchain-worker/src/lib.rs
  frame/example/README.md
  frame/example/src/lib.rs
  frame/society/README.md
  frame/staking/README.md
  frame/staking/src/lib.rs
  frame/timestamp/README.md
  primitives/allocator/README.md
  primitives/api/README.md
  primitives/npos-elections/README.md
  primitives/runtime-interface/README.md
  primitives/runtime-interface/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7499 Make the maximum block size configurable
  client/basic-authorship/src/basic_authorship.rs
  primitives/consensus/common/src/evaluation.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7487 Write pallet_evm README
  frame/evm/README.md
  frame/evm/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7507 Run polkadot companion tests with correct feature enabled
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#7361 contracts: Add automated weights for wasm instructions
  Cargo.lock
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_contracts.rs
  frame/contracts/Cargo.toml
  frame/contracts/proc-macro/Cargo.toml
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/benchmarking/sandbox.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weight_info.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7500 Remove development TODO from public doc comment
  frame/system/src/offchain.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7497 Remove pallet balances subtrait/elevatedtrait as not needed
  frame/balances/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7511 Fix comments of indices pallet events
  frame/indices/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7515 Skip slot lenience on first block in BABE
  client/consensus/babe/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7186 slots: incrementally backoff claiming slots if finality lags behind
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7489 Export app-crypto specific keystore functions
  client/keystore/src/local.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7520 Update doc for the --chain flag
  client/cli/src/params/shared_params.rs
Labels: A2-insubstantial, B0-silent, C1-low, I5-documentation 📄

#7527 contracts: Add missing instruction to the `Schedule`
  frame/contracts/src/schedule.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7525 Don't log with colors when we are writing to a tty
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/cli/src/logging.rs
  client/informant/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7534 MemoryId -> u32
  client/executor/wasmtime/src/host.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7538 Enable local addresses in DHT when chain type == `Local` | `Development`
  client/cli/src/params/network_params.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7539 Update tiny-bip39 to v0.8
  Cargo.lock
  primitives/core/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7528 Make LocalCallExecutor public
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7541 Fix some weirdness in `offchain_worker`
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B0-silent, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7464 Use inbound peerslot slots when a substream is received, rather than a connection
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7508 *: Update to libp2p v0.30.0
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/request_responses.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7544 Make ClientConfig Public
  client/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7550 sc-basic-authorship: remove useless dependencies
  Cargo.lock
  client/basic-authorship/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7543 Add slashing events to elections-phragmen.
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7549 Remove necessity to pass ConsensusEngineId when registering notifications protocol
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip.rs
  client/network/src/gossip/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/protocol/message.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7551 sc-cli: replace bip39 with tiny-bip39
  Cargo.lock
  client/cli/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7552 Add extra docs to on_initialize
  frame/support/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7380 More Extensible Multiaddress Format
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/bench.rs
  bin/node/testing/src/keyring.rs
  frame/indices/src/address.rs
  frame/indices/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/multiaddress.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7565 Fix weight template to remove ugliness in rust doc
  .maintain/frame-weight-template.hbs
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A2-insubstantial, B0-silent, C1-low

#7553 Cargo.lock: Run cargo update
  Cargo.lock
  bin/node/bench/src/tempdb.rs
  bin/node/testing/src/bench.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7509 .github: Add dependabot config and thus enable dependabot
  .github/dependabot.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7542 Thread-local parameter_types for testing.
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/elections/src/tests.rs
  frame/membership/src/lib.rs
  frame/staking/src/mock.rs
  frame/support/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7573 pallet-evm: move to Frontier (Part IV)
  Cargo.lock
  Cargo.toml
  docs/CODEOWNERS
  frame/evm/Cargo.toml
  frame/evm/README.md
  frame/evm/src/backend.rs
  frame/evm/src/lib.rs
  frame/evm/src/precompiles.rs
  frame/evm/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7546 grandpa: remove light-client specific block import pipeline
  .maintain/monitoring/grafana-dashboards/substrate-dashboard.json
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/consensus_changes.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/network/build.rs
  client/network/src/behaviour.rs
  client/network/src/chain.rs
  client/network/src/config.rs
  client/network/src/finality_requests.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/src/schema.rs
  client/network/src/schema/finality.v1.proto
  client/network/src/service.rs
  client/network/src/service/metrics.rs
  client/network/src/service/tests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/import_queue/buffered_link.rs
  primitives/consensus/common/src/lib.rs
  primitives/consensus/common/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7545 client/authority-discovery: Publish and query on exponential interval
  .maintain/gitlab/check_polkadot_companion_build.sh
  client/authority-discovery/src/interval.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/network/src/discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7582 sc-network: update some dependencies
  Cargo.lock
  client/network/Cargo.toml
  client/network/src/protocol/generic_proto/handler.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7580 Bump linregress and do some other cleanups
  Cargo.lock
  Cargo.toml
  frame/benchmarking/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7532 Wasm-builder 3.0
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/build.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/build.rs
  bin/node/runtime/src/lib.rs
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/build.rs
  client/executor/runtime-test/src/lib.rs
  docs/README.adoc
  frame/support/test/tests/construct_runtime_ui.rs
  frame/support/test/tests/decl_module_ui.rs
  frame/support/test/tests/decl_storage_ui.rs
  frame/support/test/tests/derive_no_bound_ui.rs
  frame/support/test/tests/reserved_keyword.rs
  primitives/api/test/tests/trybuild.rs
  primitives/runtime-interface/test-wasm-deprecated/Cargo.toml
  primitives/runtime-interface/test-wasm-deprecated/build.rs
  primitives/runtime-interface/test-wasm-deprecated/src/lib.rs
  primitives/runtime-interface/test-wasm/Cargo.toml
  primitives/runtime-interface/test-wasm/build.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/tests/ui.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/build.rs
  test-utils/runtime/src/lib.rs
  utils/wasm-builder-runner/Cargo.toml
  utils/wasm-builder-runner/README.md
  utils/wasm-builder-runner/src/lib.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/builder.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7482 contracts: Add `salt` argument to contract instantiation
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/fixtures/call_return_code.wat
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/destroy_and_transfer.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/fixtures/instantiate_return_code.wat
  frame/contracts/fixtures/restoration.wat
  frame/contracts/fixtures/self_destruct.wat
  frame/contracts/fixtures/self_destructing_constructor.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/fixtures/transfer_return_code.wat
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/benchmarking/sandbox.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, B5-clientnoteworthy, C1-low, D2-breaksapi

#7590 */Cargo.toml: Remove unused dependencies
  Cargo.lock
  client/api/Cargo.toml
  client/authority-discovery/Cargo.toml
  primitives/blockchain/Cargo.toml
  primitives/panic-handler/Cargo.toml
  primitives/runtime/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7591 Publish docs each time test and build are successful on master
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7595 node-template: add aura to light block import pipeline
  bin/node-template/node/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7594 Fix notifications sometimes not being sent
  client/network/src/protocol/generic_proto/handler.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7600 remove std feature flags for assert macros
  frame/support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7516 Add small header cache
  client/db/src/lib.rs
  client/service/src/client/client.rs
  primitives/blockchain/src/backend.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7604 Inform sync explicitly about new best block
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  primitives/consensus/common/src/import_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7608 Remove `RpcMetrics` weirdness
  client/rpc-servers/src/middleware.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7606 Upgrade to libp2p-0.31.
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/lib.rs
  client/network/src/light_client_handler.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  frame/support/procedural/tools/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C3-medium, D2-breaksapi

#7615 Add Key Subcommand to node-template
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7614 Forward storage changes in manual seal
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7472 chore/error: remove from str conversion and add deprecation notificat…
  Cargo.lock
  client/api/Cargo.toml
  client/api/src/light.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/cli/src/error.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  client/db/src/lib.rs
  client/executor/common/Cargo.toml
  client/executor/common/src/error.rs
  client/executor/common/src/lib.rs
  client/executor/common/src/util.rs
  client/executor/src/integration_tests/mod.rs
  client/light/src/call_executor.rs
  client/light/src/fetcher.rs
  client/network/src/light_client_handler.rs
  client/network/src/on_demand_layer.rs
  client/rpc/src/state/state_full.rs
  client/service/Cargo.toml
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/wasm_override.rs
  client/service/src/error.rs
  client/state-db/Cargo.toml
  client/sync-state-rpc/Cargo.toml
  client/sync-state-rpc/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/error.rs
  client/transaction-pool/src/error.rs
  primitives/api/Cargo.toml
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.rs
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.stderr
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.rs
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
  primitives/blockchain/Cargo.toml
  primitives/blockchain/src/backend.rs
  primitives/blockchain/src/error.rs
  primitives/consensus/common/src/error.rs
  primitives/state-machine/src/error.rs
  primitives/transaction-pool/Cargo.toml
  primitives/transaction-pool/src/error.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7601 network: don't force send block announcements
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7607 Change TRACING_SET to static
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  primitives/io/src/lib.rs
Labels: B0-silent, C1-low

#7624 sc-network: Log outgoing notifications too
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7620 `sudo_as` Returns a Result
  frame/sudo/src/lib.rs
  frame/sudo/src/tests.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7633 Fix wrong value put for pending_opening
  client/network/src/protocol/generic_proto/handler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7631 resolve unresolved error nits of #7617
  Cargo.lock
  client/consensus/slots/src/lib.rs
  client/executor/common/src/error.rs
  client/executor/src/integration_tests/mod.rs
  client/transaction-pool/graph/src/error.rs
  primitives/allocator/Cargo.toml
  primitives/allocator/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7638 Fix bad state transition with DisabledPendingEnable+OpenDesiredByRemote
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7636 Renames of `Trait` to `Config` in README.md, weight templates and few minor ones
  .maintain/frame-weight-template.hbs
  bin/node-template/README.md
  frame/assets/README.md
  frame/atomic-swap/README.md
  frame/aura/README.md
  frame/balances/README.md
  frame/benchmarking/src/tests.rs
  frame/contracts/README.md
  frame/democracy/README.md
  frame/elections-phragmen/README.md
  frame/example-offchain-worker/README.md
  frame/example/README.md
  frame/identity/README.md
  frame/im-online/README.md
  frame/multisig/README.md
  frame/nicks/README.md
  frame/offences/benchmarking/src/lib.rs
  frame/proxy/README.md
  frame/randomness-collective-flip/README.md
  frame/recovery/README.md
  frame/scheduler/README.md
  frame/scored-pool/README.md
  frame/session/README.md
  frame/session/src/historical/offchain.rs
  frame/session/src/historical/onchain.rs
  frame/society/README.md
  frame/staking/README.md
  frame/sudo/README.md
  frame/system/README.md
  frame/timestamp/README.md
  frame/transaction-payment/README.md
  frame/treasury/README.md
  frame/utility/README.md
  frame/vesting/README.md
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7639 Fix CI Link Check
  frame/assets/README.md
  frame/atomic-swap/README.md
  frame/aura/README.md
  frame/balances/README.md
  frame/contracts/README.md
  frame/democracy/README.md
  frame/elections-phragmen/README.md
  frame/example-offchain-worker/README.md
  frame/example/README.md
  frame/identity/README.md
  frame/im-online/README.md
  frame/multisig/README.md
  frame/nicks/README.md
  frame/proxy/README.md
  frame/recovery/README.md
  frame/scheduler/README.md
  frame/scored-pool/README.md
  frame/session/README.md
  frame/society/README.md
  frame/staking/README.md
  frame/sudo/README.md
  frame/system/README.md
  frame/timestamp/README.md
  frame/treasury/README.md
  frame/utility/README.md
  frame/vesting/README.md
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi
