Repository paritytech/substrate, pull requests merged in 2020-01, with the labels that each got.

#4516 Refactor Client consumers to use only chain info where needed
  bin/node/cli/src/service.rs
  client/cli/src/informant.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/network/src/chain.rs
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  client/src/client.rs
  client/src/light/fetcher.rs
  primitives/api/test/benches/bench.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/client/src/trait_tests.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview

#4514 Insert key via node RPC for subkey
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
  bin/utils/subkey/src/rpc.rs
Labels: A0-pleasereview

#4522 Update libp2p to fix build
  Cargo.lock
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview

#4520 Check for invalid modules when registering a pallet in construct_runtime
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/elections/src/mock.rs
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/construct_runtime/parse.rs
Labels: A0-pleasereview

#4519 Typo fix: ServerToWorkerMsg -> ServiceToWorkerMsg
  client/network/src/service.rs
Labels: A2-insubstantial

#4518 Update flamingfir spec for new testnet
  bin/node/cli/res/flaming-fir.json
Labels: A0-pleasereview

#4526 Make sure docs given to `decl_module!` are passed to the module struct
  frame/support/src/dispatch.rs
  frame/support/test/src/lib.rs
  frame/support/test/tests/system.rs
Labels: A0-pleasereview, A2-insubstantial

#4521 Fix `period` of offchain transactions.
  bin/node/runtime/src/lib.rs
  primitives/runtime/src/generic/era.rs
Labels: A0-pleasereview, M4-core

#4490 triggers srml-contracts-waterfall ci
  .gitlab-ci.yml
Labels: M1-ci

#4487 client/authority-discovery: Limit number of connections to authorities
  .maintain/sentry-node/docker-compose.yml
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/addr_cache.rs
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A0-pleasereview

#4483 Update to new kvdb/trie/memdb versions
  Cargo.lock
  bin/node/cli/Cargo.toml
  client/Cargo.toml
  client/api/Cargo.toml
  client/db/Cargo.toml
  client/db/src/cache/list_storage.rs
  client/db/src/cache/mod.rs
  client/db/src/children.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/utils.rs
  client/src/leaves.rs
  primitives/state-machine/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: A0-pleasereview

#4344 *: Register network event stream for authority discovery
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#4530 Fix expect text in sp-io
  primitives/io/src/lib.rs
Labels: A2-insubstantial

#4539 client: hack around fork blocks deserialization issue
  client/api/src/client.rs
  client/src/client.rs
Labels: A0-pleasereview, M4-core

#4541 Remove jimpo from CODEOWNERS
  docs/CODEOWNERS
Labels: A2-insubstantial

#4536 client: helper to create standalone client without service
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, M4-core

#4535 client: allow reverting finalized blocks
  client/api/src/backend.rs
  client/db/src/lib.rs
  client/src/client.rs
  client/src/in_mem.rs
  client/src/leaves.rs
  client/src/light/backend.rs
Labels: A0-pleasereview, M4-core

#4544 client: add a block blacklist extension
  bin/node/cli/res/flaming-fir.json
  bin/node/cli/src/chain_spec.rs
  client/api/src/client.rs
  client/db/src/lib.rs
  client/service/src/builder.rs
  client/src/client.rs
  client/src/lib.rs
  client/src/light/mod.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, M4-core

#4546 typo: lead -> leave
  client/src/client.rs
Labels: A2-insubstantial

#4549 Fix error message
  client/network/src/protocol/sync.rs
Labels: A2-insubstantial

#4554 `decl_event` support trailing comma in args
  frame/support/src/event.rs
Labels: A0-pleasereview, A2-insubstantial

#4553 do not chill indirectly-slashed nominators
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#4556 Expose load_spec
  client/cli/src/lib.rs
Labels: A0-pleasereview

#4552 client/network-gossip: Remove `GossipEngine::abort` method
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A8-looksgood

#4394 Add a `browser-utils` crate
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/browser-demo/build.sh
  bin/node/cli/browser-demo/index.html
  bin/node/cli/src/browser.rs
  client/cli/src/lib.rs
  client/keystore/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
Labels: A3-needsresolving, A7-looksgoodtestsfail, B2-breaksapi

#4560 Fix Request::new documentation
  primitives/runtime/src/offchain/http.rs
Labels: A2-insubstantial

#4525 Memory and I/O stats for backend database(s)
  Cargo.lock
  client/Cargo.toml
  client/api/Cargo.toml
  client/api/src/backend.rs
  client/api/src/client.rs
  client/api/src/light.rs
  client/cli/src/informant.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/light.rs
  client/service/src/builder.rs
  client/src/client.rs
  client/src/in_mem.rs
  client/src/light/backend.rs
  client/src/light/blockchain.rs
  utils/browser/Cargo.toml
Labels: A0-pleasereview

#4563 grandpa: guarantee that vote limit is never lower than vote base
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/environment.rs
Labels: A0-pleasereview, M4-core

#4566 Use single map and `remove_all` for `EventTopics`
  frame/system/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4565 txpool: unify client generic name
  client/transaction-pool/src/api.rs
Labels: A2-insubstantial

#4568 Bump runtime version
  bin/node/runtime/src/lib.rs
Labels: A2-insubstantial

#4570 Keystore fix default path
  client/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4550 Wasm executor should provide stubs for unknown externs (wasmi)
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A5-grumble

#4575 Update `per_thing` docs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, A2-insubstantial

#4374 Introduce rebond
  bin/node/runtime/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A8-looksgood

#4577 Add missing weights for Identity module.
  frame/identity/src/lib.rs
Labels: A0-pleasereview

#4480 Add tipping into treasury
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A8-looksgood

#4581 Update getting started link
  README.md
Labels: A0-pleasereview, A2-insubstantial

#4578 Add an extra test to check rebond is a FIFO
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#4414 Prioritize new blocks over old forks when syncing
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
Labels: A8-looksgood

#4383 Update networking code to libp2p 0.14
  Cargo.lock
  bin/node/cli/src/service.rs
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network-gossip/src/lib.rs
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/debug_info.rs
  client/network/src/discovery.rs
  client/network/src/on_demand_layer.rs
  client/network/src/protocol.rs
  client/network/src/protocol/legacy_proto/behaviour.rs
  client/network/src/protocol/legacy_proto/handler.rs
  client/network/src/protocol/legacy_proto/tests.rs
  client/network/src/protocol/legacy_proto/upgrade.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/src/utils.rs
  client/network/test/Cargo.toml
  client/network/test/src/lib.rs
  client/peerset/Cargo.toml
  client/service/src/lib.rs
  client/telemetry/Cargo.toml
  client/telemetry/src/lib.rs
  client/telemetry/src/worker.rs
  client/telemetry/src/worker/node.rs
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A1-onice, A8-looksgood

#4569 Build wasmtime support by default
  bin/node/cli/Cargo.toml
Labels: A0-pleasereview

#4542 Clean-ups in the network-gossip crate
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/src/protocol.rs
Labels: A0-pleasereview

#4579 Fix race on light client when header is read during import
  client/api/src/light.rs
  client/db/src/light.rs
  client/src/cht.rs
  client/src/in_mem.rs
  client/src/light/blockchain.rs
  client/src/light/fetcher.rs
Labels: A0-pleasereview

#4584 Fix some entries in CODEOWNERS
  docs/CODEOWNERS
Labels: A2-insubstantial

#4585 Introduce `OnReapAccount`
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/balances/src/mock.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/identity/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/staking/src/mock.rs
  frame/support/src/traits.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
Labels: A8-looksgood

#4200 Add documentation to SubmitSignedTransaction and actually make it work
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/Cargo.toml
  bin/node/executor/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/keyring.rs
  client/offchain/src/lib.rs
  client/rpc/src/state/tests.rs
  client/service/src/builder.rs
  frame/authorship/src/lib.rs
  frame/babe/src/tests.rs
  frame/contracts/src/tests.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/im-online/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/system/src/lib.rs
  frame/system/src/offchain.rs
  primitives/core/src/offchain/mod.rs
  primitives/offchain/src/lib.rs
  primitives/runtime/src/traits.rs
  primitives/transaction-pool/src/pool.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, M4-core

#4170 Society pallet
  Cargo.lock
  Cargo.toml
  frame/society/Cargo.toml
  frame/society/src/lib.rs
  frame/society/src/mock.rs
  frame/society/src/tests.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview

#4588 Fix pallet-society on master
  frame/society/src/mock.rs
Labels: A0-pleasereview, A2-insubstantial

#4576 Modify doublemap syntax
  frame/evm/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/im-online/src/lib.rs
  frame/offences/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/src/lib.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/instance.rs
  frame/utility/src/lib.rs
  utils/frame/rpc/support/src/lib.rs
Labels: A0-pleasereview

#4592 Fix runners-up candidacy submission check in council
  bin/node/runtime/src/lib.rs
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview

#4596 Remove now unused `lang_items` feature in IO primitives
  primitives/io/src/lib.rs
Labels: A0-pleasereview

#4603 Refactor some tests in tx-pool
  client/transaction-pool/src/maintainer.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-pleasereview

#4602 Avoid one timer in light strorage for Wasm
  client/db/src/light.rs
Labels: A0-pleasereview

#4598 Add test files I forgot to commit with #4520
  frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.rs
  frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.rs
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.stderr
Labels: A0-pleasereview, A2-insubstantial

#4571 Add test for cli keystore path generation
  client/chain-spec/src/chain_spec.rs
  client/cli/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  primitives/runtime/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview

#4606 Improve PaysFee trait and dispatch info logic in utility module
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
  frame/example/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/weights.rs
  frame/utility/src/lib.rs
Labels: A8-looksgood

#4557 Fixed state pinning in state-db
  client/state-db/src/noncanonical.rs
Labels: A8-looksgood

#4562 State-db I/o metrics
  client/api/src/client.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/stats.rs
  client/db/src/storage_cache.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/stats.rs
Labels: A0-pleasereview

#4583 Allow node to add externalities extensions
  client/api/src/execution_extensions.rs
  client/service/src/builder.rs
Labels: A7-looksgoodcantmerge, A7-looksgoodtestsfail

#4555 Add translate function for storage prefixed map.
  frame/support/src/storage/mod.rs
Labels: A8-looksgood

#4608 Disable equalize, avoiding consensus issue
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
Labels: A8-looksgood

#4531 A Social Account Recovery Pallet
  Cargo.lock
  Cargo.toml
  frame/recovery/Cargo.toml
  frame/recovery/src/lib.rs
  frame/recovery/src/mock.rs
  frame/recovery/src/tests.rs
Labels: A7-looksgoodtestsfail

#4158 custom weight function wrapper
  frame/staking/src/lib.rs
  frame/staking/src/slashing.rs
  frame/support/src/weights.rs
Labels: A7-looksgoodtestsfail

#4617 Take `genesis_storage` by ref
  client/chain-spec/src/chain_spec.rs
  client/db/src/lib.rs
  client/src/client.rs
  client/src/lib.rs
  client/src/light/mod.rs
  frame/staking/src/lib.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4615 Add trivial EnsureFounder verifier to society
  frame/society/src/lib.rs
  frame/society/src/mock.rs
  frame/society/src/tests.rs
Labels: A8-looksgood

#4447 Update the service to std futures
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node-template/src/cli.rs
  bin/node-template/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/service.rs
  client/cli/Cargo.toml
  client/cli/src/informant.rs
  client/cli/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/lib.rs
  client/service/src/status_sinks.rs
  client/service/test/Cargo.toml
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A7-looksgoodcantmerge, A7-looksgoodtestsfail

#4619 Do not issue empty remote read request + fix rr-related trace on full node
  client/network/src/protocol.rs
  client/rpc/src/state/state_light.rs
Labels: A8-looksgood, M4-core

#4622 Add `pallet-society` and `pallet-recovery` to substrate node
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview

#4618 Make offchain worker calls more future proof.
  client/offchain/src/lib.rs
Labels: A8-looksgood, M4-core

#4625 network: add logging for extra requests
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/extra_requests.rs
Labels: A2-insubstantial, A8-looksgood

#4621 Add more logging to the network
  client/network/src/service.rs
Labels: A0-pleasereview

#4628 Return early when fees/balances/values are zero
  frame/balances/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-looksgood

#4221 fix some discrepancies in generic-asset
  frame/generic-asset/src/lib.rs
Labels: A7-looksgoodcantmerge

#4630 Make Proposer instantiation potentially async.
  bin/node/cli/src/service.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview

#4634 Use default in-memory keystore for commands that don't use keystore
  bin/node/cli/src/cli.rs
  client/cli/src/lib.rs
Labels: A0-pleasereview

#4643 Getting configuration from commands
  bin/node/cli/src/cli.rs
  client/cli/src/lib.rs
Labels: A8-looksgood

#4640 Rename basic-authority to basic-authorship
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node-template/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/basic-authorship/Cargo.toml
  client/basic-authorship/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#4635 grandpa: generic voting rule for backing off from best block
  Cargo.lock
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/voting_rule.rs
Labels: A0-pleasereview, M4-core

#4644 Make the sync_cycle_from_offline_to_syncing_to_offline test non flaky
  client/network/test/src/sync.rs
Labels: A0-pleasereview

#3201 Allow updating configuration of changes tries
  Cargo.lock
  client/api/src/backend.rs
  client/api/src/light.rs
  client/authority-discovery/src/tests.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/db/Cargo.toml
  client/db/src/cache/list_cache.rs
  client/db/src/cache/list_storage.rs
  client/db/src/cache/mod.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/finality-grandpa/src/tests.rs
  client/network/src/protocol/light_dispatch.rs
  client/rpc/src/state/tests.rs
  client/src/call_executor.rs
  client/src/client.rs
  client/src/genesis.rs
  client/src/in_mem.rs
  client/src/light/backend.rs
  client/src/light/call_executor.rs
  client/src/light/fetcher.rs
  frame/system/src/lib.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/blockchain/src/backend.rs
  primitives/blockchain/src/error.rs
  primitives/core/src/changes_trie.rs
  primitives/core/src/lib.rs
  primitives/runtime/src/generic/digest.rs
  primitives/runtime/src/generic/mod.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/changes_trie/mod.rs
  primitives/state-machine/src/changes_trie/prune.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/testing.rs
  test-utils/runtime/client/src/block_builder_ext.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A8-looksgood, B2-breaksapi, M4-core

#4654 Add typedefs for storage types
  client/api/src/backend.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/src/in_mem.rs
  client/src/light/backend.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/changes_trie/build_cache.rs
  primitives/state-machine/src/changes_trie/input.rs
  primitives/state-machine/src/changes_trie/mod.rs
  primitives/state-machine/src/changes_trie/storage.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
Labels: A0-pleasereview

#4657 Add some extra traces to basic-authorship
  client/basic-authorship/src/basic_authorship.rs
  client/transaction-pool/graph/src/validated_pool.rs
Labels: A2-insubstantial

#4653 CODEOWNERS: Add myself to pow and EVM module
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial

#4631 client/finality-grandpa: Reintegrate periodic neighbor packet worker
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview

#4659 grandpa: bump finality-grandpa crate to v0.10.3
  Cargo.lock
  client/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, M4-core

#4646 Expose proof generation and verifying api.
  Cargo.lock
  primitives/state-machine/Cargo.toml
  primitives/trie/Cargo.toml
  primitives/trie/src/lib.rs
  test-utils/runtime/Cargo.toml
Labels: A0-pleasereview

#4658 Drive by fix of doc of `Value`.
  primitives/wasm-interface/src/lib.rs
Labels: A2-insubstantial, M3-docs

#4661 client/finality-grandpa: Reintegrate gossip validator report stream
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
Labels: A8-looksgood

#4668 `sp-runtime-interface` add table about FFI types
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/src/pass_by.rs
Labels: A0-pleasereview

#4671 Add rules and unfounding to society.
  frame/democracy/src/lib.rs
  frame/society/src/lib.rs
  frame/society/src/tests.rs
Labels: A0-pleasereview

#4673 Make use of `cfg(doc)` in `sp-runtime-interface`
  primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
  primitives/runtime-interface/src/host.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/src/wasm.rs
Labels: A0-pleasereview, A2-insubstantial

#4680 Move DummySpecialization to sc-network
  client/network/src/protocol/specialization.rs
  client/network/test/src/lib.rs
Labels: A8-looksgood

#4681 keep nominations after getting kicked with zero slash
  frame/staking/src/lib.rs
  frame/staking/src/migration.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
Labels: A6-mustntgrumble

#4675 deprecate chain_status field of network handshake
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
Labels: A0-pleasereview

#4684 client/finality-grandpa/communication: Add doc comment for PeerReport
  client/finality-grandpa/src/communication/gossip.rs
Labels: A8-looksgood, M3-docs

#4677 ci: increase retention for logs of tests to 144 hours
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#4609 Pallet session new API
  bin/node/runtime/src/lib.rs
  frame/authority-discovery/src/lib.rs
  frame/babe/src/mock.rs
  frame/im-online/src/mock.rs
  frame/session/src/historical.rs
  frame/session/src/lib.rs
  frame/session/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#4667 Only support ECDSA compressed public keys
  primitives/core/src/ecdsa.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview

#4690 Call enable_all() when building tokio runtime
  bin/node/cli/src/cli.rs
Labels: A0-pleasereview

#4683 Make debug builds more usable
  Cargo.lock
  bin/node-template/runtime/build.rs
  bin/node/cli/src/cli.rs
  bin/node/runtime/build.rs
  client/cli/src/execution_strategy.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/executor/runtime-test/build.rs
  primitives/runtime-interface/test-wasm/build.rs
  test-utils/runtime/build.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#4693 grandpa: reduce allocations when verifying multiple messages
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/justification.rs
Labels: A0-pleasereview, M4-core

#4688 Pass an executor through the Configuration
  bin/node-template/src/cli.rs
  bin/node/cli/src/cli.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/error.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview

#4698 Fix some doc deadlinks
  client/consensus/slots/src/lib.rs
  client/src/lib.rs
Labels: A2-insubstantial

#4699 Couple of improvements on node-template
  bin/node-template/runtime/build.rs
  bin/node-template/src/main.rs
Labels: A0-pleasereview

#4700 grandpa: filter some telemetry events on larger voter sets
  client/finality-grandpa/src/communication/mod.rs
Labels: A0-pleasereview, M4-core

#4703 Support `u128`/`i128` in runtime interface
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview

#4706 client/authority-discovery/Cargo.toml: Update dependency
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview

#4705 More cleanups in node-template
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node-template/src/chain_spec.rs
Labels: A0-pleasereview

#4701 fixes trigger-contracts-ci job to actually depend on build-linux-subs…
  .gitlab-ci.yml
Labels: M1-ci

#4712 make NotificationStream event naming consistent
  client/network-gossip/src/bridge.rs
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
Labels: A0-pleasereview

#4714 Update soketto to v0.3.2
  Cargo.lock
Labels: A8-looksgood

#4715 Add fool protection and comment construct_block
  bin/node/executor/tests/common.rs
Labels: A0-pleasereview

#4652 Default fork choice value and intermediates for block import parameters
  bin/node/cli/src/service.rs
  bin/node/transaction-factory/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/pow/src/lib.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/tests.rs
  client/network/test/src/lib.rs
  client/src/client.rs
  primitives/blockchain/src/error.rs
  primitives/consensus/common/src/block_import.rs
  test-utils/client/src/client_ext.rs
Labels: A6-mustntgrumble

#4691 client/finality-grandpa: Make round_communication use bounded channel
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview

#4721 Expose `Error` in metadata for `pallet-utility`
  frame/utility/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4670 Refactor and test spec block rules
  bin/node/testing/src/client.rs
  client/block-builder/src/lib.rs
  client/src/block_rules.rs
  client/src/client.rs
  client/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-pleasereview

#4727 Expose recovery module errors in metadata
  frame/recovery/src/lib.rs
Labels: A0-pleasereview

#4629 Refactor tx-pool maintenance and other high-level api
  bin/node-template/src/service.rs
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/graph/benches/basics.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/maintainer.rs
  client/transaction-pool/src/tests.rs
  primitives/transaction-pool/src/pool.rs
Labels: A0-pleasereview

#4726 Deposit event on `frame-system::set_code`
  frame/system/src/lib.rs
Labels: A0-pleasereview

#4645 Async/await in transaction-graph
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/src/lib.rs
  primitives/transaction-pool/src/pool.rs
Labels: A8-looksgood

#4720 Introduces `author_hasKey` and `author_hasSessionKeys` rpc endpoints
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/keystore/src/lib.rs
  client/rpc-api/src/author/error.rs
  client/rpc-api/src/author/mod.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  primitives/application-crypto/src/ed25519.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/sr25519.rs
  primitives/application-crypto/src/traits.rs
  primitives/core/src/crypto.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/offchain/src/lib.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  primitives/session/Cargo.toml
  primitives/session/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview

#4731 Improve decl storage parsing
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/tools/derive/src/lib.rs
  frame/support/procedural/tools/src/syn_ext.rs
Labels: A0-pleasereview

#4730 Cursed implementation of allowing missing imports on wasmtime
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview

#4143 Manual Seal
  .maintain/rename-crates-for-2.0.sh
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/browser.rs
  bin/node/cli/src/cli.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/error.rs
  client/consensus/manual-seal/src/finalize_block.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/rpc.rs
  client/consensus/manual-seal/src/seal_new_block.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing.rs
  client/transaction-pool/src/tests.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/block_import.rs
  primitives/inherents/src/lib.rs
Labels: A0-pleasereview, M4-core

#4582 Remove references to frame_consensus from docs
  frame/aura/src/lib.rs
  frame/session/src/lib.rs
  frame/sudo/src/lib.rs
Labels: A0-pleasereview

#4733 pallet-contracts: Refactor and comment `rent` module.
  bin/node/runtime/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
Labels: A0-pleasereview

#4741 ci: fix runtime version check
  .maintain/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#4739 Remove default hasher
  frame/assets/src/lib.rs
  frame/babe/src/lib.rs
  frame/balances/src/lib.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/evm/src/lib.rs
  frame/example/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/historical.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/frame/rpc/support/src/lib.rs
Labels: A0-pleasereview

#4736 Fix quadratic iterations over transaction pool
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/future.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  primitives/transaction-pool/src/pool.rs
Labels: A0-pleasereview

#4732 Upgrade to libp2p 0.15
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/protocol/legacy_proto/handler.rs
  client/network/src/protocol/legacy_proto/upgrade.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/network/test/src/lib.rs
  client/peerset/Cargo.toml
  client/service/src/builder.rs
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview

#4737 WASM runtime switch to import memory
  Cargo.lock
  bin/node-template/runtime/build.rs
  bin/node/runtime/build.rs
  client/executor/runtime-test/build.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/integration_tests/sandbox.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  primitives/runtime-interface/test-wasm/build.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/build.rs
  test-utils/runtime/src/lib.rs
  utils/wasm-builder-runner/Cargo.toml
  utils/wasm-builder-runner/src/lib.rs
Labels: A0-pleasereview

#4746 Update yamux to version 0.4.1
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#4745 Make sure destroy_state is called in case of errors.
  client/src/call_executor.rs
Labels: A0-pleasereview, M4-core

#4747 Print extrinsic failed error always, not just on import
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, A2-insubstantial

#4749 Display `has_api_with` results if invalid version of Offchain Workers is detected.
  Cargo.lock
  client/offchain/src/lib.rs
Labels: A2-insubstantial, M4-core

#4672 Update bridge pallet to work with the (almost) lastest master
  frame/bridge/Cargo.toml
  frame/bridge/src/lib.rs
  frame/bridge/src/storage_proof.rs
Labels: A0-pleasereview

#4757 Don't run dev light client as validator
  client/cli/src/lib.rs
  client/cli/src/params.rs
Labels: A2-insubstantial, A8-looksgood

#4752 [Maybe controversial?] Add diagnostics to tasks
  Cargo.lock
  bin/node-template/src/service.rs
  bin/node/cli/src/service.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue/basic_queue.rs
Labels: A0-pleasereview

#4762 Chores: clean up indentation problems
  client/api/src/light.rs
  client/consensus/aura/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/rpc/src/state/state_light.rs
  client/service/src/builder.rs
  client/transaction-pool/graph/benches/basics.rs
  frame/contracts/src/wasm/prepare.rs
  primitives/arithmetic/benches/bench.rs
  primitives/core/benches/bench.rs
  primitives/phragmen/benches/phragmen.rs
  primitives/runtime/src/generic/era.rs
  primitives/state-machine/src/stats.rs
Labels: A2-insubstantial

#4760 LinkedMap doesn't implement StoragePrefixedMap
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/test/tests/final_keys.rs
Labels: A0-pleasereview, F2-bug 🐜

#4759 Revamp some of the weights
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/identity/src/lib.rs
  frame/nicks/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/weights.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4763 Order network dependencies alphabetically
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
Labels: A2-insubstantial

#4756 Add `get_global` for `Sandbox`
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/executor/common/src/sandbox.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/integration_tests/sandbox.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/function_executor.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/runtime.rs
  primitives/core/src/sandbox.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/impls.rs
  primitives/runtime/Cargo.toml
  primitives/sandbox/Cargo.toml
  primitives/sandbox/src/lib.rs
  primitives/sandbox/with_std.rs
  primitives/sandbox/without_std.rs
  primitives/wasm-interface/Cargo.toml
  primitives/wasm-interface/src/lib.rs
Labels: A3-inprogress, B2-breaksapi

#4772 RPC calls should execute with configured strategy
  client/rpc/src/state/state_full.rs
Labels: A0-pleasereview, A2-insubstantial

#4770 Identity should bound additional fields
  bin/node/runtime/src/lib.rs
  frame/identity/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4766 client/finality-grandpa/src/observer: Poll NetworkBridge
  client/finality-grandpa/src/observer.rs
Labels: A0-pleasereview

#4768 Fix warnings.
  bin/node-template/src/cli.rs
  bin/node-template/src/service.rs
  bin/node/cli/src/cli.rs
  client/finality-grandpa/src/lib.rs
  client/network/test/src/lib.rs
Labels: A2-insubstantial, M4-core

#4692 CLI API refactoring and improvement
  Cargo.lock
  bin/node-template/Cargo.toml
  bin/node-template/src/chain_spec.rs
  bin/node-template/src/cli.rs
  bin/node-template/src/command.rs
  bin/node-template/src/main.rs
  bin/node-template/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/bin/main.rs
  bin/node/cli/build.rs
  bin/node/cli/src/browser.rs
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/lib.rs
  bin/node/cli/src/service.rs
  bin/utils/chain-spec-builder/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/cli/src/node_key.rs
  client/cli/src/params.rs
  client/cli/src/runtime.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  primitives/keyring/src/sr25519.rs
  utils/browser/src/lib.rs
Labels: A5-grumble

#4779 Remove notices regarding wasm file in check_runtime.sh
  .maintain/gitlab/check_runtime.sh
Labels: A2-insubstantial, M1-ci
