Repository paritytech/substrate, pull requests merged in 2020-10, with the labels that each got.

#7235 Update Treasury Config to use Propotion of Council Members
  bin/node/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7196 Fix weight for inner call with new origin
  frame/multisig/src/lib.rs
  frame/proxy/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#7236 Remove runtime registered extensions after execution
  client/api/src/execution_extensions.rs
  primitives/externalities/src/extensions.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/testing.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7214 permit setting treasury pallet initial funding through genesis
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7243 Fix executive test
  frame/executive/src/lib.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  primitives/runtime/src/testing.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7246 Remove hack around secondary connections handshakes
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7248 Fix typo cranelift_wasm
  client/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7249 client/cli: Update to fdlimit 0.2.1
  Cargo.lock
  client/cli/Cargo.toml
  client/service/test/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7215 Fix offchain election to respect the weight
  .gitignore
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/system/src/extensions/check_weight.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high, D1-audited👍

#6958 Split block announce processing into two parts
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/test/src/sync.rs
  primitives/consensus/common/src/block_validation.rs
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low

#7258 Rename `TRANSACTION_VERSION` to `EXTRINSIC_VERSION`
  primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#7250 .maintain/monitoring: Add alert when continuous task ends
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#7263 Update ss58 registry for Dock network
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7226 SystemOrigin trait
  frame/support/src/origin.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7271 Rework `InspectState`
  bin/node/bench/src/import.rs
  primitives/state-machine/src/read_only.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7272 client: improve log formatting
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7242 Drop system cache for trie benchmarks
  bin/node/bench/src/trie.rs
  bin/node/testing/src/bench.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6860 reschedule
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
Labels: B3-apinoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7274 Reset flaming fir network
  bin/node/cli/res/flaming-fir.json
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7277 bump-allocator: document & poison
  Cargo.lock
  primitives/allocator/src/freeing_bump.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6896 Refactor CurrencyToVote
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/elections-phragmen/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/support/src/traits.rs
  primitives/npos-elections/src/helpers.rs
Labels: B5-clientnoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7279 add ss58 id for nodle
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7017 seal: Add automated weights for contract API calls
  Cargo.lock
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_contracts.rs
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/benchmarks/dummy.wat
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/event_size.wat
  frame/contracts/src/benchmarking.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weight_info.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7281 Fixes logging of target names with dashes
  Cargo.lock
  client/cli/src/lib.rs
  client/tracing/Cargo.toml
  primitives/io/Cargo.toml
  primitives/runtime-interface/test/Cargo.toml
  primitives/tracing/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#7283 Release new version of wasm-builder-runner
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node/runtime/Cargo.toml
  client/executor/runtime-test/Cargo.toml
  primitives/runtime-interface/test-wasm-deprecated/Cargo.toml
  primitives/runtime-interface/test-wasm/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/wasm-builder-runner/Cargo.toml
  utils/wasm-builder-runner/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7289 Update ss58-registry.json about Darwinia Network
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7247 sc-network: expose `add_to_priority_group` and `remove_from_priority_…
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7284 Allow `schedule_after(0, ...)` to work
  frame/scheduler/src/lib.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low

#7261 Implements require_transactional
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/transactional.rs
  frame/support/src/lib.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/storage_transaction.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7299 Fixes bug in wasm-builder with cargo publish
  Cargo.lock
  bin/node-template/runtime/build.rs
  bin/node/runtime/build.rs
  client/executor/runtime-test/build.rs
  primitives/runtime-interface/test-wasm-deprecated/build.rs
  primitives/runtime-interface/test-wasm/build.rs
  test-utils/runtime/build.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7308 Add profiling targets to tracing_subscriber
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7315 Add an system_syncState RPC method
  client/rpc-api/src/system/helpers.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7318 Make `run_node_until_exit` take a future
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  client/cli/src/runner.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7320 Adjust ss58-registry websites to conform to schema
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7108 Change image in simnet CI jobs from parity/chaostools to paritypr/simnet
  .gitlab-ci.yml
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#7324 Allow where clause in `decl_error!`
  frame/support/src/error.rs
  frame/support/test/tests/instance.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7053 babe: make secondary slot randomness available on-chain
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/digests.rs
Labels: B3-apinoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7225 Add missing fields to the light sync state
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/cli/Cargo.toml
  client/cli/src/commands/build_sync_spec_cmd.rs
  client/cli/src/commands/mod.rs
  client/consensus/babe/src/aux_schema.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/lib.rs
  client/service/src/chain_ops/build_sync_spec.rs
  client/service/src/chain_ops/mod.rs
  client/service/test/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  client/sync-state-rpc/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7330 Update token info about ChainX.
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7228 frame: remove finality-tracker
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/src/bench.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  frame/finality-tracker/Cargo.toml
  frame/finality-tracker/README.md
  frame/finality-tracker/src/lib.rs
  frame/grandpa/Cargo.toml
  frame/grandpa/src/lib.rs
  primitives/finality-tracker/Cargo.toml
  primitives/finality-tracker/README.md
  primitives/finality-tracker/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, A3-inprogress, B0-silent, C1-low, D2-breaksapi

#7322 sync: only restart peers not doing finality related requests
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7076 No longer actively open legacy substreams
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
Labels: A1-onice, B5-clientnoteworthy, C3-medium

#7307 consensus: prioritize finality work over block import in queue
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue/basic_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7338 [CI] Remove 'Monitor gitlab pipeline status'
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/check-gitlab-pipeline.yml
  .maintain/github/check_gitlab_pipeline.sh
Labels: A2-insubstantial, B0-silent, C1-low

#7344 Adds support for inspecting a hex encoded public key
  client/cli/src/commands/generate.rs
  client/cli/src/commands/inspect_key.rs
  client/cli/src/commands/key.rs
  client/cli/src/commands/mod.rs
  client/cli/src/commands/utils.rs
  primitives/application-crypto/src/lib.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7233 Constant Weight Signature in Benchmarking CLI
  bin/node/runtime/src/weights/frame_system.rs
  bin/node/runtime/src/weights/pallet_timestamp.rs
  bin/node/runtime/src/weights/pallet_treasury.rs
  bin/node/runtime/src/weights/pallet_utility.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/default_weights.rs
  frame/system/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/timestamp/src/default_weights.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/default_weights.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/default_weights.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7342 Make `queryStorage` and `storagePairs` unsafe RPC functions
  client/rpc-api/src/state/error.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/tests.rs
  client/service/src/builder.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C3-medium

#7350 Move `IsSubType` and write some docs for the trait
  frame/example/src/lib.rs
  frame/proxy/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/inherent.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7280 Derive no bound macros (to be also used in pallet macro)
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/clone_no_bound.rs
  frame/support/procedural/src/debug_no_bound.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/partial_eq_no_bound.rs
  frame/support/src/lib.rs
  frame/support/test/tests/derive_no_bound.rs
  frame/support/test/tests/derive_no_bound_ui.rs
  frame/support/test/tests/derive_no_bound_ui/clone.rs
  frame/support/test/tests/derive_no_bound_ui/clone.stderr
  frame/support/test/tests/derive_no_bound_ui/debug.rs
  frame/support/test/tests/derive_no_bound_ui/debug.stderr
  frame/support/test/tests/derive_no_bound_ui/eq.rs
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  frame/support/test/tests/derive_no_bound_ui/partial_eq.rs
  frame/support/test/tests/derive_no_bound_ui/partial_eq.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7351 Make `wasm-builder` print the rustc version
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/prerequisites.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7359 grandpa: remove duplicate function to fetch local authority id
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7358 client/network: Remove option to disable yamux flow control
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7306 *: Bump async-std to v1.6.5
  Cargo.lock
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/gossip.rs
  client/network/src/gossip/tests.rs
  client/service/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, A1-needsburnin, B3-apinoteworthy, C1-low

#7355 Fix logging from inside the WASM runtime
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/src/debug.rs
  primitives/tracing/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7089 Runtime worker threads
  Cargo.lock
  Cargo.toml
  client/executor/Cargo.toml
  client/executor/common/src/error.rs
  client/executor/common/src/wasm_runtime.rs
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  frame/example-parallel/Cargo.toml
  frame/example-parallel/src/lib.rs
  frame/example-parallel/src/tests.rs
  primitives/core/src/traits.rs
  primitives/externalities/src/extensions.rs
  primitives/io/src/lib.rs
  primitives/runtime-interface/src/lib.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/testing.rs
  primitives/tasks/Cargo.toml
  primitives/tasks/README.md
  primitives/tasks/src/async_externalities.rs
  primitives/tasks/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#7356 client/network: Allow configuring Kademlia's disjoint query paths
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7328 Add node name to the log lines
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/bench/src/construct.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/cli/Cargo.toml
  client/cli/proc-macro/Cargo.toml
  client/cli/proc-macro/src/lib.rs
  client/cli/src/lib.rs
  client/cli/src/logging.rs
  client/consensus/manual-seal/src/lib.rs
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/service/Cargo.toml
  client/service/src/task_manager/mod.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7369 client/network: Remove original_request in block request events
  client/network/src/behaviour.rs
  client/network/src/block_requests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7371 Make `decl_runtime_apis!` fail on methods with default implementation
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/test/tests/ui/no_default_implementation.rs
  primitives/api/test/tests/ui/no_default_implementation.stderr
Labels: A0-pleasereview, B0-silent, C1-low

#7352 client/network: Make NetworkService::set_priority_group async
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B2-breaksapi, B3-apinoteworthy, C1-low

#7373 Small fix for log line prefix
  client/cli/src/lib.rs
  client/cli/src/logging.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7370 Improve `mock_impl_runtime_apis!`
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.rs
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.stderr
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.rs
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7376 build: add nix shell
  shell.nix
Labels: A0-pleasereview, B0-silent, C1-low

#7381 Make Substrate compile with latest nightly
  client/cli/src/commands/export_blocks_cmd.rs
  client/finality-grandpa/src/voting_rule.rs
  client/informant/src/display.rs
  client/network/src/light_client_handler.rs
  client/service/src/chain_ops/export_blocks.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/src/client/client.rs
  client/service/src/metrics.rs
  client/transaction-pool/src/lib.rs
  frame/aura/src/lib.rs
  frame/babe/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/contracts/src/wasm/runtime.rs
  frame/example-offchain-worker/src/lib.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/benchmarking.rs
  frame/grandpa/src/lib.rs
  frame/im-online/src/lib.rs
  frame/offences/benchmarking/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/offchain.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/lib.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/npos-elections/src/mock.rs
  shell.nix
  test-utils/client/src/client_ext.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7385 fix darwin for nix shell
  shell.nix
Labels: A0-pleasereview, B0-silent, C1-low

#7384 Fix wrong outgoing calculation in election
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high, D2-breaksapi

#7368 client/authority-discovery: Remove sentry node logic
  bin/node/cli/src/service.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/service.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7395 Make benchmarks compile with latest nightly
  frame/balances/src/benchmarking.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/democracy/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/vesting/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7321 grandpa: fix early enactment of forced changes
  client/finality-grandpa/src/authorities.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7372 grandpa: don't send equivocation reports for local identities
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7317 WASM Local-blob override
  Cargo.lock
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/client/mod.rs
  client/service/src/client/wasm_override.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7394 Don't slash all outgoing members.
  bin/node/runtime/src/weights/pallet_elections_phragmen.rs
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C3-medium, D2-breaksapi

#7396 Fix doc for ChangeMember trait
  frame/support/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7428 Add keccak512 hash
  primitives/core/src/hashing.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7431 Fix typo in toml
  client/service/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7390 Use Handlebars Template for Benchmark CLI Output
  .maintain/frame-weight-template.hbs
  Cargo.lock
  frame/benchmarking/README.md
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/template.hbs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7436 improve error handling in cli
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/commands/insert.rs
  client/cli/src/commands/utils.rs
  client/cli/src/commands/verify.rs
  client/cli/src/error.rs
  client/cli/src/lib.rs
  frame/offences/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7188 Implement batch_all and update Utility pallet for weight refunds
  bin/node/runtime/src/weights/pallet_utility.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/default_weights.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7443 pallet-treasury: remove non-existing dispatchables in docs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7442 Add Totem ss58 address
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7445 Use `storage::exists` host function instead of ::get.
  frame/support/src/storage/unhashed.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D2-breaksapi

#7447 Fix benchmarks template whitespaces
  .maintain/frame-weight-template.hbs
  frame/democracy/src/weights.rs
  frame/system/src/weights.rs
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7446 WIP: error rework, for polkadot convenience
  Cargo.lock
  client/api/src/call_executor.rs
  client/api/src/cht.rs
  primitives/blockchain/Cargo.toml
  primitives/blockchain/src/error.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/error.rs
  primitives/consensus/common/src/evaluation.rs
  primitives/core/Cargo.toml
  primitives/core/src/ed25519.rs
  primitives/core/src/traits.rs
  primitives/database/src/error.rs
  primitives/inherents/Cargo.toml
  primitives/inherents/src/lib.rs
  primitives/runtime/src/transaction_validity.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7448 Allow multiple bounds to be specified at decl_error!
  frame/support/src/error.rs
  frame/support/test/tests/instance.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7450 add Sync + Send + 'static to Box<dyn Error> bound
  client/cli/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7457 Print an error if an unregistered notifications protocol is used
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7459 Transfer code ownership of /frame/contracts/
  docs/CODEOWNERS
Labels: A0-pleasereview, B0-silent, C1-low

#7159 Replace bitmask with bitflags
  Cargo.lock
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/contracts/src/rent.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/executive/src/lib.rs
  frame/support/Cargo.toml
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7409 contracts: Refactor the runtime API in order to simplify node integration
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/common/Cargo.toml
  frame/contracts/common/src/lib.rs
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C3-medium, D2-breaksapi

#7451 Make sure pallet versions are set at genesis
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/dispatch.rs
  frame/support/src/genesis_config.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/test/tests/pallet_version.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6912 decouple transaction payment and currency
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/executive/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-payment/src/payment.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7469 Update CI chaos tag to simnet
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7465 Make authority discovery configurable
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7471 Add constant constructor to AccountId32
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7468 contracts: Rework contracts_call RPC
  frame/contracts/rpc/src/lib.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D2-breaksapi

#7393 docs/CONTRIBUTING: Update Polkadot pull request process documentation
  docs/CONTRIBUTING.adoc
Labels: A0-pleasereview, B0-silent, C1-low

#7341 Update to libp2p-0.29.
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/request_responses.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/worker.rs
  primitives/consensus/common/Cargo.toml
  primitives/core/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C3-medium
