Repository paritytech/substrate, pull requests merged in 2020-05, with the labels that each got.

#5848 New weights using i7 machine
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#5870 Remove Old Migration Code
  frame/democracy/src/lib.rs
  frame/indices/src/lib.rs
  frame/offences/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#5875 Another state machine test
  primitives/state-machine/src/lib.rs
Labels: A0-pleasereview

#5874 Fix clippy warnings in generated runtime api code
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5869 `node-bench` no-op block import
  bin/node-template/runtime/src/lib.rs
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/bench.rs
Labels: A8-mergeoncegreen

#5879 Fix `sync` logging
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
Labels: A2-insubstantial, B0-silent

#5878 Report tasks panics in metrics
  client/service/src/task_manager.rs
Labels: A0-pleasereview, B0-silent

#5822 Update wasmtime
  Cargo.lock
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A3-inprogress, B0-silent

#5868 Use header cache when creating state.
  client/db/src/lib.rs
  client/service/src/client/client.rs
  client/service/src/client/mod.rs
  primitives/blockchain/src/header_metadata.rs
Labels: A0-pleasereview, B0-silent

#5882 Update chain spec for flaming fir 7
  bin/node/cli/res/flaming-fir.json
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5860 Expose that `BasicQueue` expects blocking spawn
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/network/src/service/tests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/service/src/task_manager.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
Labels: A0-pleasereview, A3-needsresolving, B0-silent

#5876 Correct BABE randomness by calculating InOut bytes directly in pallet
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/verification.rs
  frame/babe/Cargo.toml
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/vrf/Cargo.toml
  primitives/consensus/vrf/src/schnorrkel.rs
Labels: A0-pleasereview, B2-breaksapi

#5884 Refactor weight constants, Update to remove redundant overhead
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/support/src/weights.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A7-needspolkadotpr, B2-breaksapi

#5375 Expose GRANDPA round state through RPC
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/report.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#5886 Help finish phragmen benchmarks
  bin/node/runtime/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/benchmarking.rs
Labels: A0-pleasereview, B2-breaksapi

#5892 Fix Reduce Equalise order in offhchain phragmen
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/tests.rs
  primitives/phragmen/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#5890 Remove tx factory
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/factory_impl.rs
  bin/node/cli/src/lib.rs
  bin/node/cli/tests/factory.rs
  bin/node/transaction-factory/Cargo.toml
  bin/node/transaction-factory/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5896 Remove BABE dependency in network
  Cargo.lock
  client/network/Cargo.toml
Labels: A2-insubstantial, B0-silent

#5889 Use `storage::append` in the implementation of the storage types
  Cargo.lock
  frame/benchmark/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/value.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/decl_storage.rs
  frame/system/src/lib.rs
  primitives/core/src/testing.rs
  primitives/io/src/lib.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/storage/src/lib.rs
  primitives/wasm-interface/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#5898 Remove extra backtick in comments
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, B0-silent

#5899 Fix staking fuzzer + make it check in ci.
  .gitlab-ci.yml
  frame/staking/Cargo.toml
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/testing_utils.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, M1-ci

#5894 Validate block bodies when syncing
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, B0-silent

#5893 Add repository metadata to grandpa-rpc-crate
  .gitlab-ci.yml
  client/finality-grandpa/rpc/Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, M0-build

#5901 client/authority-discovery: Do not double encode signature
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
  primitives/core/src/traits.rs
Labels: A8-mergeoncegreen, B0-silent

#5729 client: Replace `unsafe_rpc_expose` with an `RpcMethods` enum
  client/cli/src/arg_enums.rs
  client/cli/src/commands/mod.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, M6-rpcapi

#5861 Update GRANDPA authorities set in light storage when GRANDPA set changes
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/light_import.rs
Labels: A0-pleasereview, B0-silent

#5851 Benchmarks for offences pallet.
  Cargo.lock
  frame/babe/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/offences/benchmarking/Cargo.toml
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/staking/src/lib.rs
  primitives/staking/src/offence.rs
Labels: A8-mergeoncegreen, B2-breaksapi, M4-core

#5748 client/network-gossip/bridge: Use bounded channel
  Cargo.lock
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
Labels: A8-mergeoncegreen, B0-silent

#5917 Fix wrong task name
  client/service/src/builder.rs
Labels: A2-insubstantial, B0-silent

#5918 Improve error message when essential task failed
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5924 Add state trace on append
  primitives/state-machine/src/ext.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent

#5925 Fix saturating_mul for negatives
  primitives/arithmetic/src/traits.rs
Labels: A0-pleasereview, B0-silent

#3868 grandpa: report equivocations
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/primitives/Cargo.toml
  bin/node/primitives/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/keyring.rs
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  frame/grandpa/Cargo.toml
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/session/Cargo.toml
  frame/session/src/historical.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  primitives/core/src/lib.rs
  primitives/finality-grandpa/Cargo.toml
  primitives/finality-grandpa/src/lib.rs
  primitives/session/Cargo.toml
  primitives/session/src/lib.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A3-inprogress, B2-breaksapi

#5922 Make `Digest` support `StorageAppend`
  client/finality-grandpa/src/light_import.rs
  frame/support/src/storage/mod.rs
  frame/system/src/lib.rs
  primitives/runtime/src/generic/digest.rs
Labels: A0-pleasereview, B1-runtimenoteworthy

#5928 Fix docs
  client/block-builder/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/transaction-payment/src/lib.rs
  primitives/consensus/common/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/phragmen/src/reduce.rs
  primitives/runtime/src/traits.rs
  primitives/state-machine/src/overlayed_changes.rs
  utils/fork-tree/src/lib.rs
  utils/wasm-builder-runner/src/lib.rs
Labels: B2-breaksapi

#5932 Unify format of state-trace logs
  primitives/state-machine/src/ext.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5907 Extend Schedule Pallet for Root Scheduling/Canceling
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/scheduler/Cargo.toml
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5935 Revert "Update wasmtime (#5822)"
  Cargo.lock
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A2-insubstantial, B0-silent

#5929 Use header cache for blockchain cache
  client/db/src/cache/mod.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  primitives/blockchain/src/header_metadata.rs
Labels: A8-mergeoncegreen, B0-silent

#5937 Change to Vec to VecDeque in network behaviour
  client/network/src/behaviour.rs
Labels: A0-pleasereview

#5916 Merge Substrate master before checking Polkadot companion
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview, B0-silent, M1-ci

#5934 Relase `wasm-builder` and `wasm-builder-runner`
  Cargo.lock
  utils/wasm-builder-runner/Cargo.toml
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5888 Update System Weights
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5897 Fix and add benchs for democracy pallet
  frame/democracy/src/benchmarking.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5945 Disconnect node after sync request cancelled
  client/network/src/behaviour.rs
Labels: A0-pleasereview

#5942 Make sure `config_mut` returns a mutable reference
  client/cli/src/runner.rs
Labels: A2-insubstantial, B0-silent

#5944 Remove "simple declaration of the `Module` type" comments
  frame/identity/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A2-insubstantial, B0-silent, B2-breaksapi

#5950 Bump wasmtime again
  Cargo.lock
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent

#5960 Expose BlockHashCount on system metadata constants
  frame/system/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B2-breaksapi

#5959 Add database type for import benchmarks
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  bin/node/testing/src/bench.rs
Labels: A8-mergeoncegreen

#5946 weight adjustments for identity and timestamp pallets
  bin/node/executor/tests/basic.rs
  frame/identity/src/lib.rs
  frame/timestamp/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5939 Refactor network transactions handling
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#5952 Fix very wrong staking test
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi, F4-tests 🎯

#5962 Don't repeatedly lookup keys in `babe_epochAuthorship` rpc function
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, B0-silent, M4-core

#5968 hotfix Docker release
  .gitlab-ci.yml
Labels: F2-bug 🐜, M1-ci

#5969 Properly log when we discard a sync response
  client/network/src/block_requests.rs
Labels: A2-insubstantial, B0-silent

#5965 Add crypto identifier to RuntimeAppPublic
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/traits.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
Labels: A4-awaitingci

#5967 Small fix to block response completion reporting
  client/network/src/block_requests.rs
Labels: A2-insubstantial, B0-silent

#5970 Minor update on example-offchain-worker code and comment
  frame/example-offchain-worker/src/lib.rs
  frame/system/src/offchain.rs
Labels: A2-insubstantial, B0-silent, B2-breaksapi, F5-documentation 📄

#5971 Update initialize tests for latest rust stable
  frame/support/test/tests/reserved_keyword/on_initialize.stderr
  primitives/api/test/tests/ui/empty_impl_runtime_apis_call.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
  primitives/runtime-interface/test/src/lib.rs
  primitives/runtime-interface/tests/ui/pass_by_enum_with_struct.stderr
  primitives/runtime-interface/tests/ui/pass_by_enum_with_value_variant.stderr
  primitives/runtime-interface/tests/ui/pass_by_inner_with_two_fields.stderr
Labels: A0-pleasereview, A2-insubstantial, B0-silent, B2-breaksapi

#5982 Allow passing multiple --log CLI options
  client/cli/src/commands/mod.rs
  client/cli/src/config.rs
  client/cli/src/params/shared_params.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#5975 Optimize `decode_len`
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/value.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/decl_storage.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#5954 Split Operational and Normal weight
  bin/node/runtime/src/impls.rs
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5983 client/finality-granpda/until_imported: Rework pinning
  client/finality-grandpa/src/until_imported.rs
Labels: A0-pleasereview, B0-silent

#5972 grandpa: update to finality-grandpa v0.12.3
  Cargo.lock
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  frame/grandpa/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, B2-breaksapi

#5953 grandpa: missing equivocation reporting nits
  bin/node/primitives/src/lib.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/finality-grandpa/src/lib.rs
  primitives/session/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, M4-core

#5949 Make elections-phragmen weighable and secure.
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/support/src/lib.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#5987 Update and pin the node-browser-testing wasm-bindgen version
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
Labels: B0-silent

#5974 babe: minor rpc nits
  client/consensus/babe/rpc/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5981 Do not fetch every block body from transaction pool
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/validated_pool.rs
Labels: A0-pleasereview, B0-silent

#5984 Restore the reputation penalty for timeouts
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
Labels: A8-mergeoncegreen, B0-silent

#5909 Spawn the network worker with spawn_blocking
  client/cli/src/runner.rs
  client/service/src/builder.rs
Labels: A8-mergeoncegreen, B0-silent

#5993 client/network: Remove default Kademlia DHT in favor of per protocol DHT
  client/network/src/discovery.rs
  client/network/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#6000 Turn an error! into a debug!
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A2-insubstantial, B0-silent

#5997 Fix minor typos in im-online documentation
  frame/im-online/src/lib.rs
Labels: B2-breaksapi

#6003 Only send last finalized block to telemetry
  client/service/src/client/client.rs
Labels: A0-pleasereview, B0-silent

#5994 Fix gitlab line-width CI check
  .maintain/gitlab/check_line_width.sh
Labels: A8-mergeoncegreen

#5992 Monitor transactions rejected from the pool as invalid
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/metrics.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5999 Give more meaningful error on missing feature when opening a db
  client/db/src/utils.rs
Labels: A2-insubstantial, B0-silent

#6011 Add CRYPTO_ID to AppKey
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/traits.rs
Labels: A0-pleasereview, B0-silent

#5996 Add mitigation for the state inconsistency issue
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
Labels: A0-pleasereview, B0-silent

#5988 Fix minor clippy lints in grandpa
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/until_imported.rs
Labels: A0-pleasereview

#6012 Handle clap errors manually and don't reset `SIGPIPE`
  bin/node/cli/src/command.rs
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6014 Convert `Public` to `CryptoTypePublicPair`
  primitives/application-crypto/src/ed25519.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/sr25519.rs
  primitives/authority-discovery/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
Labels: A8-mergeoncegreen, B0-silent

#6013 Fix potential state mismatch in behaviour.rs
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent

#6007 Properly handle different block content in benches
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  bin/node/testing/src/bench.rs
Labels: A8-mergeoncegreen, B0-silent

#5963 Add tests to Sudo Pallet
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/sudo/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#6019 Improve `BadProof` docs
  primitives/runtime/src/transaction_validity.rs
Labels: A2-insubstantial, B0-silent

#6018 Fix escaping of the wasm file path
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A5-grumble, B0-silent

#6020 ci: fix merge on polkadot companion job
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, M1-ci

#6016 [CI] Fix a few issues with .gitlab-ci.yml
  .gitlab-ci.yml
Labels: B0-silent, M1-ci

#6021 Fix RPC tests for machines with a high number of cores
  Cargo.lock
  client/rpc/Cargo.toml
  client/rpc/src/author/tests.rs
  client/rpc/src/chain/tests.rs
  client/rpc/src/lib.rs
  client/rpc/src/state/tests.rs
  client/rpc/src/testing.rs
Labels: A0-pleasereview, B0-silent

#5802 Collective weights
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/collective/src/benchmarking.rs
  frame/collective/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6034 Don't log the yamux errors by default
  client/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent

#6035 Add Slashing Spans to Staking Benchmarks
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
Labels: B2-breaksapi

#5979 Add ‘transaction_version’ to the signed transaction
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/src/service.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/keyring.rs
  bin/utils/subkey/src/main.rs
  frame/system/src/lib.rs
Labels: B0-silent, B2-breaksapi

#5964 Update Staking Weights
  frame/babe/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  frame/support/src/traits.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6017 bump kvdb-* versions
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/tempdb.rs
  client/api/Cargo.toml
  client/db/Cargo.toml
  primitives/database/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent

#5828 Democracy weight
  Cargo.lock
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/lib.rs
  frame/democracy/Cargo.toml
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/decoders.rs
  frame/democracy/src/tests/migration.rs
  frame/democracy/src/tests/preimage.rs
  frame/democracy/src/tests/public_proposals.rs
Labels: A8-mergeoncegreen, B1-apinoteworthy, B1-runtimenoteworthy, B2-breaksapi

#6028 Fix lots of small nits in sc-network
  client/network/src/behaviour.rs
  client/network/src/block_requests.rs
  client/network/src/debug_info.rs
  client/network/src/discovery.rs
  client/network/src/light_client_handler.rs
  client/network/src/on_demand_layer.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/blocks.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent

#5930 Put some graphics in the README?
  README.md
  docs/media/sub.gif
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, M3-docs

#5845 Benchmarks for elections-phragmen pallet
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/support/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  primitives/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#6008 Use `sign_with` in consensus
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  primitives/application-crypto/src/lib.rs
  primitives/consensus/common/src/error.rs
  primitives/core/Cargo.toml
  primitives/core/src/traits.rs
Labels: A0-pleasereview, B0-silent

#6029 Added RuntimePublic for ecdsa public key.
  client/keystore/src/lib.rs
  primitives/application-crypto/src/ecdsa.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/test/src/ecdsa.rs
  primitives/application-crypto/test/src/lib.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/io/src/batch_verifier.rs
  primitives/io/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy, M4-core

#6025 Meter block import results via prometheus
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/Cargo.toml
  client/consensus/pow/src/lib.rs
  client/network/src/service/tests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/lib.rs
  primitives/consensus/common/src/metrics.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#6039 Remove on_block_imported
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6054 Aura fix: make sure the key exists locally
  client/consensus/aura/src/lib.rs
Labels: A0-pleasereview

#6053 Remove file accounts.scale
  frame/system/src/accounts.scale
Labels: A0-pleasereview, B0-silent

#6043 Fail test on warnings
  .gitlab-ci.yml
  primitives/api/test/tests/ui/declaring_old_block.rs
  primitives/api/test/tests/ui/declaring_old_block.stderr
  primitives/api/test/tests/ui/declaring_own_block_with_different_name.rs
  primitives/api/test/tests/ui/declaring_own_block_with_different_name.stderr
  primitives/api/test/tests/ui/impl_two_traits_with_same_name.rs
  primitives/api/test/tests/ui/impl_two_traits_with_same_name.stderr
  primitives/api/test/tests/ui/mock_only_one_block_type.rs
  primitives/api/test/tests/ui/mock_only_one_block_type.stderr
  primitives/api/test/tests/ui/mock_only_one_self_type.rs
  primitives/api/test/tests/ui/mock_only_one_self_type.stderr
Labels: A8-mergeoncegreen, F8-enhancement 🎁, M1-ci

#5976 grandpa: minor cleanup for gossip round start instant
  client/finality-grandpa/src/communication/gossip.rs
Labels: A0-pleasereview, B0-silent, M4-core

#6058 Updates the license badge
  README.md
Labels: A0-pleasereview

#6055 Fix parallel code execution in wasmtime
  Cargo.lock
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/Cargo.toml
Labels: A0-pleasereview, B0-silent

#6047 Print an error if we discover our own network identity
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent

#6056 Refactor EVM operations to module functions
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6065 Make decl_storage generated code respect clippy
  frame/support/procedural/src/storage/genesis_config/builder_def.rs
  frame/support/procedural/src/storage/storage_struct.rs
Labels: A0-pleasereview, B0-silent

#6024 Include post dispatch corrected weight in extrinsic events
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  primitives/runtime/src/generic/checked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6064 Upgrade to libp2p v0.19 - Changes the default PeerId representation
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/src/params/network_params.rs
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B1-clientnoteworthy

#6068 Make GrandpaBlockImport public
  client/finality-grandpa/src/lib.rs
Labels: B0-silent

#6070 service: fix RPC unsafe exposed address detection
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, M4-core

#6072 Clean a number of imports in /frame
  frame/aura/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/authorship/Cargo.toml
  frame/babe/Cargo.toml
  frame/balances/Cargo.toml
  frame/benchmarking/Cargo.toml
  frame/executive/Cargo.toml
  frame/offences/benchmarking/Cargo.toml
  frame/session/Cargo.toml
  frame/session/benchmarking/Cargo.toml
  frame/society/Cargo.toml
  frame/support/test/Cargo.toml
  frame/system/Cargo.toml
  frame/system/benchmarking/Cargo.toml
  frame/vesting/Cargo.toml
Labels: A2-insubstantial, B0-silent, B2-breaksapi

#6077 Detect obsolete block responses
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent

#5989 Refactor OverlayedChanges
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/testing.rs
Labels: A0-pleasereview, A1-onice, B0-silent

#6081 Bump wasmtime version
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
Labels: A2-insubstantial, B0-silent

#6074 Refactor resource and error handling in wasm
  client/executor/common/src/sandbox.rs
Labels: A8-mergeoncegreen, B0-silent

#6067 Maximum extrinsic weight limit
  bin/node-template/pallets/template/src/mock.rs
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/assets/src/lib.rs
  frame/aura/src/mock.rs
  frame/authority-discovery/src/lib.rs
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/benchmarking/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/example-offchain-worker/src/tests.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/generic-asset/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/identity/src/lib.rs
  frame/im-online/src/mock.rs
  frame/indices/src/mock.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/mock.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/recovery/src/mock.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/mock.rs
  frame/sudo/src/mock.rs
  frame/system/benches/bench.rs
  frame/system/benchmarking/src/mock.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
  frame/utility/src/tests.rs
  frame/vesting/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B1-runtimenoteworthy, B2-breaksapi, M4-core

#6091 Turn a SmallVec into VecDeque for performances
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
Labels: A0-pleasereview, B0-silent

#6086 evm: allow setting pre-defined accounts in genesis
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#6076 Allow fee calculation to happen off-chain
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/tests.rs
  frame/executive/src/lib.rs
  frame/support/Cargo.toml
  frame/support/src/weights.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6098 Handle piping error for commands that output to stdout
  .gitignore
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
Labels: A0-pleasereview, B0-silent

#6089 Allow operational recovery path if on_initialize use fullblock.
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/preimage.rs
Labels: A0-pleasereview, B1-apinoteworthy, B1-runtimenoteworthy, B2-breaksapi

#6099 Further optimize network poll
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent

#6082 Add notes about safe uses of twox
  frame/assets/src/lib.rs
  frame/babe/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#6069 babe: treat epoch_authorship RPC method as unsafe
  Cargo.lock
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/rpc-api/src/policy.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#5961 Offences Weight for OnInitialize
  bin/node/runtime/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  primitives/staking/src/offence.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#6046 Keep `BlockWeight` in Storage
  bin/node/runtime/src/impls.rs
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#6090 clarify docs on query_info and partial_fee
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, M3-docs

#6095 .maintain/monitoring: Add an initial set of Prometheus alerting rules
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent

#6101 Add Keccak hasher
  primitives/core/src/hasher.rs
  primitives/core/src/lib.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A6-mustntgrumble, A8-mergeoncegreen

#5877 Implement FixedPoint trait.
  Cargo.lock
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests.rs
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.lock
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/fixed.rs
  primitives/arithmetic/src/fixed.rs
  primitives/arithmetic/src/fixed128.rs
  primitives/arithmetic/src/fixed64.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#6107 chore(client): remove the unnecessary clap dep
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/error.rs
Labels: B0-silent

#6109 Make pallet-membership dispatchables public
  bin/node/runtime/src/lib.rs
  frame/membership/src/lib.rs
Labels: B0-silent, B2-breaksapi

#6111 Add a note about the deprecation of register_notifications_protocol
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent

#6038 Fix some flaky offchain HTTP tests
  client/offchain/src/api/http.rs
  client/offchain/src/api/timestamp.rs
Labels: A0-pleasereview, B0-silent, F4-tests 🎯

#5816 Add JSON format to import blocks and set it as default
  bin/node/cli/tests/check_block_works.rs
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/export_import_flow.rs
  bin/node/cli/tests/import_export_and_revert_work.rs
  bin/node/cli/tests/inspect_works.rs
  bin/node/cli/tests/purge_chain_works.rs
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  client/cli/src/commands/import_blocks_cmd.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#6114 Put democracy max votes into metadata
  frame/democracy/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, B2-breaksapi

#6108 Don't clone values when calculating storage root
  client/api/src/in_mem.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/service/src/client/light/backend.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B0-silent

#6032 First draft of offchain phragmen weights
  .gitlab-ci.yml
  Cargo.lock
  frame/staking/Cargo.toml
  frame/staking/fuzzer/Cargo.toml
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/support/src/lib.rs
  primitives/phragmen/compact/src/lib.rs
  primitives/phragmen/src/tests.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#6120 Fix default base path on windows
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/config.rs
Labels: A0-pleasereview, B0-silent

#6119 Benchmarks sanity checks
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/read_only.rs
Labels: A0-pleasereview, B0-silent

#6118 Events and better log for staking.
  frame/staking/src/lib.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/tests.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, B2-breaksapi
