Repository paritytech/substrate, pull requests merged in 2020-04, with the labels that each got.

#5435 Reset benchmarks by removing post-genesis changes
  Cargo.lock
  client/db/src/bench.rs
  client/service/src/lib.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A8-mergeoncegreen

#5412 Introduce scheduler and use it for the democracy dispatch queue
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/democracy/Cargo.toml
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/cancellation.rs
  frame/democracy/src/tests/preimage.rs
  frame/democracy/src/tests/voting.rs
  frame/elections-phragmen/Cargo.toml
  frame/scheduler/Cargo.toml
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5430 Remove DiscoveryNetBehaviour trait
  client/network/src/behaviour.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent

#5490 A few missing emojies
  bin/node/cli/src/browser.rs
  client/cli/src/commands/runcmd.rs
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/service.rs
  client/telemetry/src/worker/node.rs
  utils/prometheus/src/lib.rs
Labels: A2-insubstantial

#5487 babe: restore epoch changes migration code
  client/consensus/babe/src/aux_schema.rs
  client/consensus/epochs/src/lib.rs
  client/consensus/epochs/src/migration.rs
Labels: A0-pleasereview, A8-backport, B0-silent, M4-core

#5472 Switch to new light client protocol
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/on_demand_layer.rs
  client/network/src/protocol.rs
  client/network/src/protocol/light_client_handler.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5168 State metrics possible changes
  client/api/src/client.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/stats.rs
  client/db/src/storage_cache.rs
  client/src/call_executor.rs
  client/src/light/backend.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/stats.rs
  primitives/state-machine/src/trie_backend.rs
Labels: A0-pleasereview

#5494 ci: divide cache between branches
  .gitlab-ci.yml
Labels: M1-ci

#5493 Use saturating sub in basic authorship
  client/basic-authorship/src/basic_authorship.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5507 cli: fix milliseconds formatting on logs
  client/cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, M4-core

#5498 More emojies and spaces
  bin/node/cli/src/browser.rs
  client/cli/src/commands/runcmd.rs
  client/finality-grandpa/src/authorities.rs
  client/informant/src/display.rs
  client/network/src/protocol/sync.rs
  client/service/src/lib.rs
  client/telemetry/src/worker/node.rs
Labels: A2-insubstantial

#5495 Remove unused dependency on safe-mix
  Cargo.lock
  bin/node-template/pallets/template/Cargo.toml
Labels: A2-insubstantial

#5503 Add a sub_libp2p_notifications_queues_size Prometheus metric
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
  utils/prometheus/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5512 Improve warning about notifications queue and remove spurious triggers
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
Labels: A0-pleasereview

#5508 Companion PR ci sed issue.
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview

#5510 Fix `payout_nominator` benchmarks
  frame/staking/src/benchmarking.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent

#5509 Run Runtime Benchmarks on Block One
  frame/benchmarking/src/lib.rs
  frame/example/Cargo.toml
  frame/example/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#5477 Use custom runner for import benchmarks
  Cargo.lock
  Cargo.toml
  bin/node/bench/Cargo.toml
  bin/node/bench/src/core.rs
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/benches/import.rs
Labels: A0-pleasereview

#5429 ci: check_polkadot: check for companion
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview, M1-ci

#5458 Make Dispatchable return the actual weight consumed
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/weights.rs
  frame/utility/src/lib.rs
  primitives/runtime/src/generic/checked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi

#5505 prepopulate CARGO_HOME caches
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#5520 Split the Roles in three types
  bin/node-template/node/src/service.rs
  bin/node/cli/src/browser.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/inspect/src/command.rs
  client/authority-discovery/src/lib.rs
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/import_blocks_cmd.rs
  client/cli/src/commands/revert_cmd.rs
  client/cli/src/commands/runcmd.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/network_configuration_params.rs
  client/cli/src/params/pruning_params.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/light_client_handler.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/peerset/src/lib.rs
  client/peerset/tests/fuzz.rs
  client/rpc-api/src/system/helpers.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, B1-apinoteworthy, B2-breaksapi

#5519 support: add lateness trait
  frame/babe/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, M4-core

#5521 EnsureOrigin is a frame abstraction - it should be in frame_support
  frame/collective/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/traits.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, B2-breaksapi

#5406 Simple Staking Payouts
  Cargo.lock
  frame/staking/Cargo.toml
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5414 Additional Metrics collected and exposed via prometheus
  Cargo.lock
  Cargo.toml
  client/Cargo.toml
  client/api/Cargo.toml
  client/api/src/client.rs
  client/api/src/notifications.rs
  client/authority-discovery/src/tests.rs
  client/cli/Cargo.toml
  client/cli/src/runtime.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
  client/network/Cargo.toml
  client/network/src/on_demand_layer.rs
  client/network/src/service.rs
  client/offchain/Cargo.toml
  client/offchain/src/api/http.rs
  client/peerset/Cargo.toml
  client/peerset/src/lib.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/mod.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/service/src/status_sinks.rs
  client/service/src/task_manager.rs
  client/src/client.rs
  client/src/in_mem.rs
  client/src/leaves.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/graph/src/watcher.rs
  client/transaction-pool/src/revalidation.rs
  primitives/blockchain/src/backend.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/import_queue/buffered_link.rs
  primitives/transaction-pool/Cargo.toml
  primitives/transaction-pool/src/pool.rs
  primitives/utils/Cargo.toml
  primitives/utils/src/lib.rs
  primitives/utils/src/metrics.rs
  primitives/utils/src/mpsc.rs
  utils/prometheus/Cargo.toml
  utils/prometheus/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5524 Fix non-linux build of sc-client
  client/service/Cargo.toml
  client/service/src/metrics.rs
Labels: A0-pleasereview, B0-silent, F2-bug 🐜, M0-build

#5523 Fix Benchmarks to enable batch run
  frame/democracy/src/benchmarking.rs
  frame/staking/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5515 Mandatory dispatch class
  bin/node/executor/tests/basic.rs
  client/basic-authorship/src/basic_authorship.rs
  frame/authorship/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  primitives/runtime/src/generic/checked_extrinsic.rs
  primitives/runtime/src/traits.rs
  primitives/runtime/src/transaction_validity.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5522 Sort members in elections-phragmen genesis
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, F2-bug 🐜

#5057 Make verbosity level mandatory with telemetry opt
  bin/node-template/README.md
  client/cli/src/commands/runcmd.rs
  docs/README.adoc
Labels: A0-pleasereview, B1-clientnoteworthy, B2-breaksapi

#5533 Revert "prepopulate CARGO_HOME caches"
  .gitlab-ci.yml
Labels: A0-pleasereview, F2-bug 🐜, M1-ci

#5537 Update Externalities docs
  primitives/externalities/src/lib.rs
Labels: A2-insubstantial, B0-silent

#5535 Prometheus Metrics: Turn notifications_total counter into notifications_sizes histogram
  client/network/src/service.rs
  utils/prometheus/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#5544 Remove myself from txpool code owning.
  docs/CODEOWNERS
Labels: A2-insubstantial

#5546 change (ci): merge check warnings into test linux job
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#5527 Generate Unit Tests for Benchmarks
  .gitlab-ci.yml
  Cargo.lock
  frame/balances/src/benchmarking.rs
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/tests.rs
  frame/example/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/im-online/src/benchmarking.rs
  frame/session/benchmarking/Cargo.toml
  frame/session/benchmarking/src/lib.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/mock.rs
  frame/session/src/tests.rs
  frame/staking/src/benchmarking.rs
  frame/support/src/lib.rs
  frame/system/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/tests.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/tests.rs
  frame/vesting/src/benchmarking.rs
  primitives/state-machine/src/in_memory_backend.rs
Labels: A8-mergeoncegreen, B1-runtimenoteworthy, B2-breaksapi

#5411 Benchmark Offences Pallet
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/im-online/src/lib.rs
  frame/offences/Cargo.toml
  frame/offences/benchmarking/Cargo.toml
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/staking/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5556 More emoji
  client/consensus/babe/src/aux_schema.rs
  client/consensus/slots/src/lib.rs
  client/finality-grandpa/src/aux_schema.rs
  client/network/src/service.rs
Labels: A2-insubstantial

#5558 Make `application-crypto` `std` feature internal
  primitives/application-crypto/src/lib.rs
  primitives/phragmen/src/reduce.rs
Labels: A2-insubstantial, B0-silent

#5548 Fix compilation of service metrics on Windows
  client/service/src/metrics.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5469 sc-consensus-manual-seal uses Finalizer trait for finalization instead of Backend.
  client/consensus/manual-seal/src/finalize_block.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_new_block.rs
Labels: A0-pleasereview

#5564 babe, grandpa: restrict info logging during initial sync
  client/consensus/babe/src/lib.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
Labels: A0-pleasereview, B0-silent, M4-core

#5278 libp2p-next
  Cargo.lock
  Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/debug_info.rs
  client/network/src/discovery.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/block_requests.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/light_client_handler.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A8-mergeoncegreen

#5540 Refactor SignedExtension
  frame/balances/src/tests.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  frame/support/src/dispatch.rs
  frame/support/src/metadata.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
  primitives/runtime/src/generic/checked_extrinsic.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#5571 Add more Prometheus metrics
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent

#5563 Unsigned Validation best practices
  bin/node/runtime/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/example-offchain-worker/src/tests.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  primitives/runtime/src/transaction_validity.rs
Labels: A0-pleasereview, B1-apinoteworthy, B1-runtimenoteworthy, B2-breaksapi, M4-core

#5572 Remove flakiness from transaction pool tests (again)
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A2-insubstantial

#5551 Add verify block to benchmark tests
  frame/balances/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/utils.rs
  frame/collective/src/benchmarking.rs
  frame/collective/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5560 Fix #5516
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5577 Don't always recompile the node binary on `cargo run`
  utils/build-script-utils/src/git.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5567 Reuse wasmtime instances, the PR
  Cargo.lock
  client/executor/common/Cargo.toml
  client/executor/common/src/lib.rs
  client/executor/common/src/util.rs
  client/executor/wasmi/Cargo.toml
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5578 Update .editorconfig
  .editorconfig
Labels: A2-insubstantial

#5576 Add new RPC method to get the chain type
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node/cli/src/chain_spec.rs
  bin/utils/chain-spec-builder/Cargo.toml
  bin/utils/chain-spec-builder/src/main.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/rpc-api/Cargo.toml
  client/rpc-api/src/system/helpers.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  primitives/chain-spec/Cargo.toml
  primitives/chain-spec/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5589 Don't fail the build when no git is found
  utils/build-script-utils/src/version.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5337 Move contracts wasm test code into separate files
  frame/contracts/src/tests.rs
  frame/contracts/tests/caller_contract.wat
  frame/contracts/tests/check_default_rent_allowance.wat
  frame/contracts/tests/crypto_hashes.wat
  frame/contracts/tests/destroy_and_transfer.wat
  frame/contracts/tests/dispatch_call.wat
  frame/contracts/tests/dispatch_call_then_trap.wat
  frame/contracts/tests/drain.wat
  frame/contracts/tests/get_runtime_storage.wat
  frame/contracts/tests/restoration.wat
  frame/contracts/tests/return_from_start_fn.wat
  frame/contracts/tests/return_with_data.wat
  frame/contracts/tests/run_out_of_gas.wat
  frame/contracts/tests/self_destruct.wat
  frame/contracts/tests/self_destructing_constructor.wat
  frame/contracts/tests/set_rent.wat
  frame/contracts/tests/storage_size.wat
Labels: A0-pleasereview, A2-insubstantial, B0-silent, B2-breaksapi

#5562 client/authority-discovery: Terminate when network does
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A5-grumble, B0-silent

#5585 Fix benchmarks: set cache_size to higher value
  bin/node/testing/src/bench.rs
  client/db/src/lib.rs
  client/db/src/utils.rs
Labels: A2-insubstantial

#5575 Report local force-closing connections to Prometheus
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent

#5586 Benchmarks now use in-memory db & cache
  Cargo.lock
  client/db/Cargo.toml
  client/db/src/bench.rs
Labels: A8-mergeoncegreen, B0-silent

#5534 Collection of enhancement for staking/phragmen.
  bin/node/cli/src/factory_impl.rs
  bin/node/cli/src/service.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/keyring.rs
  bin/utils/subkey/src/main.rs
  frame/executive/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5580 Forcing-aware offchain Phragmén.
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5460 CI: Release - monitor gitlab pipeline
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/check-gitlab-pipeline.yml
  .maintain/github/check_gitlab_pipeline.sh
Labels: A8-mergeoncegreen, B0-silent, M1-ci

#5602 Update to libp2p 0.18
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent

#5597 Add metrics for the events in the network output channels
  client/network/src/service.rs
  client/network/src/service/out_events.rs
Labels: A8-mergeoncegreen

#5591 Post-condition checking for some pallets
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#5584 Introduce weight refund
  bin/node/executor/tests/basic.rs
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#5608 Make sure we poll authority event stream until all events are processed
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5609 Disable `wasm-timer` in `no_std`
  primitives/timestamp/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5613 Fix the browser node and update demo script
  bin/node/cli/browser-demo/README.md
  bin/node/cli/browser-demo/build.sh
  utils/browser/src/lib.rs
Labels: A2-insubstantial, B0-silent

#5553 Remove HashMap<EngineId, ...> from consensus-gossip
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, B0-silent

#5618 Fix native version text on startup
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  client/cli/Cargo.toml
  client/cli/src/runner.rs
Labels: A0-pleasereview, B2-breaksapi

#5604 More robust sync
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview

#5617 Benchmarks profile mode
  bin/node/bench/src/core.rs
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
Labels: A0-pleasereview, B0-silent

#5614 Introduce `Fixed128` from ORML to `sp_arithmetic`
  Cargo.lock
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/src/fixed128.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/lib.rs
Labels: A8-mergeoncegreen

#5627 Bump trie-db
  Cargo.lock
  primitives/state-machine/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: A2-insubstantial

#5626 Give names to channels
  bin/node/cli/src/service.rs
  client/network-gossip/src/lib.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B2-breaksapi

#5583 Phragmen solution should submit for current era and be checked against current era
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5624 Add tests for weight refund
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5321 .maintain/sentry-node: Add monitoring to docker-compose stack
  .maintain/monitoring/grafana-dashboards/README_dashboard.md
  .maintain/monitoring/grafana-dashboards/substrate-dashboard.json
  .maintain/sentry-node/docker-compose.yml
  .maintain/sentry-node/grafana/provisioning/dashboards/dashboards.yml
  .maintain/sentry-node/grafana/provisioning/datasources/datasource.yml
  .maintain/sentry-node/prometheus/prometheus.yml
Labels: A0-pleasereview, B0-silent, M0-build

#5634 Adding Process.toml for processbot
  Process.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, F9-meta 📦, M1-ci

#5635 `decl_runtime_apis!` - check that a method without `changed_in` exists
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/ui/changed_in_no_default_method.rs
  primitives/api/test/tests/ui/changed_in_no_default_method.stderr
Labels: A0-pleasereview, B0-silent

#5619 Report tasks metrics to Prometheus
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/task_manager.rs
  client/service/src/task_manager/prometheus_future.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#5549 New database trait
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/testing/Cargo.toml
  bin/node/testing/src/bench.rs
  client/Cargo.toml
  client/cli/src/arg_enums.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/mod.rs
  client/cli/src/commands/purge_chain_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/shared_params.rs
  client/consensus/slots/src/lib.rs
  client/db/Cargo.toml
  client/db/src/cache/list_storage.rs
  client/db/src/cache/mod.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/children.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/offchain.rs
  client/db/src/parity_db.rs
  client/db/src/subdb.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  client/src/client.rs
  client/src/leaves.rs
  frame/support/src/traits.rs
  primitives/blockchain/src/backend.rs
  primitives/database/Cargo.toml
  primitives/database/src/kvdb.rs
  primitives/database/src/lib.rs
  primitives/database/src/mem.rs
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A8-mergeoncegreen, B2-breaksapi

#5646 Removed subdb dependency
  Cargo.lock
  client/db/Cargo.toml
Labels: A2-insubstantial

#5504 Implement iter for doublemap
  frame/recovery/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/support/src/hash.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B1-apinoteworthy, B2-breaksapi

#5651 client: avoid spamming telemetry on initial sync
  Cargo.lock
  client/Cargo.toml
  client/src/client.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#5650 Remove the tokio thread name
  client/cli/src/runner.rs
Labels: A2-insubstantial, B0-silent

#5644 Temporarily increase notifications buffer size
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent

#5653 stop using CARGO_HOME cache until the bug resolves
  .gitlab-ci.yml
Labels: M1-ci

#5632 client/authority-discovery: Increase request counter per request
  client/authority-discovery/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#5045 Use a Kademlia instance per `ProtocolId`.
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#5658 Get rid of some dependencies
  Cargo.lock
  client/state-db/Cargo.toml
Labels: A8-mergeoncegreen

#5659 Upgrade sysinfo to `0.13.3`
  Cargo.lock
  client/service/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent

#5616 Trie integrated benchmark
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/core.rs
  bin/node/bench/src/generator.rs
  bin/node/bench/src/main.rs
  bin/node/bench/src/state_sizes.rs
  bin/node/bench/src/tempdb.rs
  bin/node/bench/src/trie.rs
Labels: A8-mergeoncegreen

#5636 Several tweaks to networking Prometheus metrics
  client/network/src/service.rs
  client/network/src/service/out_events.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#5631 client/authority-discovery: Rework error handling
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A0-pleasereview, B0-silent

#5643 Add alternative RPC methods to system_networkState
  client/network/src/service.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5568 client/authority-discovery: Allow to be run by sentry node
  .maintain/sentry-node/docker-compose.yml
  bin/node/cli/src/service.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5668 Update parity-util-mem
  Cargo.lock
  client/cli/Cargo.toml
  client/db/Cargo.toml
  client/informant/Cargo.toml
  client/service/Cargo.toml
  client/state-db/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  primitives/core/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/test-primitives/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: A2-insubstantial

#5023 Batch signature verification
  Cargo.lock
  bin/node/runtime/src/lib.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/src/bench.rs
  client/transaction-pool/src/testing/pool.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/sr25519.rs
  primitives/externalities/src/extensions.rs
  primitives/externalities/src/lib.rs
  primitives/io/Cargo.toml
  primitives/io/src/batch_verifier.rs
  primitives/io/src/lib.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/testing.rs
Labels: A0-pleasereview, B2-breaksapi

#5671 Add performance tracing to validate_transaction
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  frame/executive/src/lib.rs
  frame/support/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi, M4-core

#5660 Adjustments to Kademlia-related metrics
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5452 Clean Phragmén Equlise API
  Cargo.lock
  Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  primitives/phragmen/Cargo.toml
  primitives/phragmen/benches/phragmen.rs
  primitives/phragmen/compact/src/staked.rs
  primitives/phragmen/fuzzer/Cargo.toml
  primitives/phragmen/fuzzer/src/common.rs
  primitives/phragmen/fuzzer/src/equalize.rs
  primitives/phragmen/fuzzer/src/reduce.rs
  primitives/phragmen/src/helpers.rs
  primitives/phragmen/src/lib.rs
  primitives/phragmen/src/mock.rs
  primitives/phragmen/src/tests.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#5677 Listen on ipv6 addesses by default as well
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#5673 Migration for `pallet-transaction-payment` transitioning to u64 weights
  Cargo.lock
  frame/support/src/storage/migration.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/src/fixed64.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5675 remove rustdocs script
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#5656 emit TipClosed event on success tip payout
  bin/node/runtime/src/lib.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: B2-breaksapi

#5657 Add prometheus registry to transaction pool, with couple of initial metrics
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/metrics.rs
  client/transaction-pool/src/testing/pool.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A8-mergeoncegreen

#5582 Transaction versioning in the RuntimeVersion
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/executor/Cargo.toml
  client/executor/src/wasm_runtime.rs
  client/rpc/src/state/tests.rs
  frame/system/src/lib.rs
  primitives/api/src/lib.rs
  primitives/core/src/hashing.rs
  primitives/sr-api/proc-macro/src/lib.rs
  primitives/version/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-patchthis, B1-runtimenoteworthy, B2-breaksapi

#5640 Fix weight refund to use proper adjustment factor
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5661 Make network_config_path an Option
  client/cli/src/commands/mod.rs
  client/cli/src/config.rs
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: B0-silent, B2-breaksapi

#5687 Revert listening on IPv6 by default
  client/cli/src/params/network_params.rs
Labels: A2-insubstantial, B0-silent

#5689 Force libp2p 0.18.1
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A2-insubstantial, B0-silent

#5676 subkey: compute and inspect a moduleid
  bin/utils/subkey/README.adoc
  bin/utils/subkey/src/main.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#5679 Refactor misleading log in discovery
  client/network/src/discovery.rs
Labels: A2-insubstantial, B0-silent

#5497 Revise docs on randomness
  frame/babe/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
Labels: A6-mustntgrumble, B2-breaksapi

#5233 Allow to expose a subset of unsafe RPCs
  client/cli/src/commands/mod.rs
  client/cli/src/commands/runcmd.rs
  client/cli/src/config.rs
  client/rpc-api/src/author/error.rs
  client/rpc-api/src/lib.rs
  client/rpc-api/src/offchain/error.rs
  client/rpc-api/src/policy.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/lib.rs
  client/rpc/src/offchain/mod.rs
  client/rpc/src/offchain/tests.rs
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, M6-rpcapi

#5697 Pass max-total to RewardRemainder on end_era
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B1-apinoteworthy, B1-runtimenoteworthy, B2-breaksapi

#5700 Update codeowners: removing thiolliere.
  docs/CODEOWNERS
Labels: A2-insubstantial, B0-silent

#5701 Move around definitions in sc_network
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
Labels: A2-insubstantial, B0-silent

#5698 Improve tracing
  Cargo.lock
  Cargo.toml
  client/tracing/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/support/Cargo.toml
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/tracing/Cargo.toml
  primitives/tracing/src/lib.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi

#4887 Add a crate to test the in-browser light client.
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  bin/node/browser-testing/Cargo.toml
  bin/node/browser-testing/src/lib.rs
  bin/node/browser-testing/webdriver.json
  bin/node/cli/src/browser.rs
Labels: A8-mergeoncegreen

#5699 Implement `try_mutate` for storage value and storage double map
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/src/storage/generator/value.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#5649 Add RPC function state_getProof, resolves #1110
  client/rpc-api/src/state/helpers.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
Labels: A5-grumble, M6-rpcapi

#5669 client/network-gossip: Move sink IO outside of state_machine
  Cargo.lock
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent

#5665 Pass an encoded Roles as the notifications protocols handshakes
  client/network/src/behaviour.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
Labels: A8-mergeoncegreen, B0-silent

#5707 client/authority-discovery: Add metric exposing priority group size
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5182 Offchain signing
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/example-offchain-worker/src/tests.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/system/src/lib.rs
  frame/system/src/offchain.rs
  primitives/application-crypto/src/lib.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
Labels: A8-mergeoncegreen, B2-breaksapi

#5717 Require `fn` token in `decl_storage` `get`
  frame/democracy/src/lib.rs
  frame/offences/src/lib.rs
  frame/society/src/lib.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/src/lib.rs
Labels: A2-insubstantial, B1-runtimenoteworthy, B2-breaksapi

#5725 Remove TaskManagerBuilder
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/task_manager.rs
Labels: A3-inprogress, B0-silent

#5716 Fix warning reported in out_events when Registry is None
  client/network/src/service/out_events.rs
Labels: A0-pleasereview, B0-silent

#5686 Migrate away from `SimpleDispatchInfo`
  bin/node-template/pallets/template/src/lib.rs
  frame/assets/src/lib.rs
  frame/authorship/src/lib.rs
  frame/benchmark/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/evm/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/metadata.rs
  frame/support/src/weights.rs
  frame/support/test/tests/decl_error.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/reserved_keyword/on_initialize.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#5726 Send a status message on block announce handshake
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
Labels: A8-mergeoncegreen, B0-silent

#5718 Add a protocol that answers finality proofs
  client/network/build.rs
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
  client/network/src/protocol/finality_requests.rs
  client/network/src/protocol/schema/finality.v1.proto
  client/network/src/service.rs
Labels: A8-mergeoncegreen, B0-silent

#5734 Enable yamux flow control by default
  client/cli/src/params/network_params.rs
Labels: A2-insubstantial, B0-silent

#5733 enum Pays for PaysFee
  bin/node/executor/tests/basic.rs
  frame/balances/src/tests.rs
  frame/contracts/src/tests.rs
  frame/evm/src/lib.rs
  frame/example/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy, B2-breaksapi

#5737 Make `version_is_full` test work without `.git` being available
  bin/node/cli/tests/version.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5728 Fix the browser tests by not relying on Flaming Fir
  bin/node/browser-testing/src/lib.rs
  bin/node/cli/src/browser.rs
Labels: B0-silent

#5742 slots: fix slot lenience methods
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, M4-core

#5735 network: Only insert global addresses into the DHT.
  Cargo.lock
  client/cli/src/params/network_params.rs
  client/network/Cargo.toml
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/test/src/lib.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy

#5714 client/network-gossip/state_machine: Reduce indentation level
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A8-mergeoncegreen, B0-silent

#5703 Assign DB weights for node runtime
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
Labels: A2-insubstantial

#5739 Fix leak in stream notifications
  Cargo.lock
  client/api/Cargo.toml
  client/api/src/notifications.rs
  client/src/client.rs
Labels: A8-mergeoncegreen, B1-clientnoteworthy, B2-breaksapi

#5745 Full block import benchmark
  bin/node/bench/Cargo.toml
  bin/node/bench/src/core.rs
  bin/node/bench/src/import.rs
  bin/node/bench/src/main.rs
  primitives/io/src/batch_verifier.rs
Labels: A8-mergeoncegreen

#5746 Make GrandpaJustification::decode_and_verify_finalizes public
  client/finality-grandpa/src/justification.rs
Labels: A0-pleasereview, B0-silent

#5754 Fix error in browser demo readme
  bin/node/cli/browser-demo/README.md
Labels: A2-insubstantial, B0-silent

#5741 Allow missing functions when checking the new runtime's version
  Cargo.lock
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/construct_runtime_ui.rs
  frame/support/test/tests/reserved_keyword.rs
  frame/system/src/lib.rs
  primitives/core/src/traits.rs
  primitives/io/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/state-machine/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5610 Regression testing and readability additions for reward curve log2
  frame/staking/reward-curve/src/lib.rs
  frame/staking/reward-curve/src/log.rs
Labels: A8-mergeoncegreen, B0-silent, B2-breaksapi

#5750 Document crypto key identifiers
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, A8-mergeoncegreen, F5-documentation 📄
