Repository paritytech/substrate, pull requests merged in 2020-07, with the labels that each got.

#6547 Update to make cargo-deny happy
  .gitlab-ci.yml
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#6537 pallet-evm: customizable chain id
  frame/evm/src/backend.rs
  frame/evm/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#6545 Fix runtime benchmarks CI
  .gitlab-ci.yml
  frame/identity/src/lib.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6510 Fix mocking multiple http calls in the same function call
  client/executor/src/integration_tests/mod.rs
  frame/example-offchain-worker/src/tests.rs
  primitives/core/src/offchain/testing.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6426 .maintain/monitoring/alerting-rules: Adjust transaction queue size alert
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#6536 [CI] Fix auto-label-issues.yml
  .github/workflows/auto-label-issues.yml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6525 [CI] Add Github Action to notify devops of PRs labelled with A1-needsburnin
  .github/workflows/burnin-label-notification.yml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6471 Restrict `Protected` to some heap types.
  Cargo.lock
  client/cli/src/params/keystore_params.rs
  client/keystore/src/lib.rs
  client/service/src/config.rs
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6543 Remove `ServiceBuilderCommand` and implement the chain ops as standalone functions instead.
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  client/cli/Cargo.toml
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
  client/cli/src/commands/import_blocks_cmd.rs
  client/cli/src/commands/purge_chain_cmd.rs
  client/cli/src/commands/revert_cmd.rs
  client/cli/src/runner.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/chain_ops/check_block.rs
  client/service/src/chain_ops/export_blocks.rs
  client/service/src/chain_ops/export_raw_state.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/src/chain_ops/mod.rs
  client/service/src/chain_ops/revert_chain.rs
  client/service/src/lib.rs
Labels: A7-needspolkadotpr, A8-mergeoncegreen, B0-silent, C1-low

#6548 Drop the tokio runtime before the task_manager
  client/cli/src/runner.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6550 Update SubstrateCli to return String
  .maintain/gitlab/check_polkadot_companion_build.sh
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  primitives/panic-handler/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6387 Allow specify schedule dispatch origin
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/collective/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/scheduler/Cargo.toml
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/metadata.rs
  frame/support/src/origin.rs
  frame/support/src/traits.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/system.rs
  frame/system/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#6553 Move `create_inherents` into the block-builder
  Cargo.lock
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/Cargo.toml
  client/block-builder/src/lib.rs
  frame/support/src/storage/mod.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6552 client/network: Remove unused Result returned by NetworkWorker
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6555 New testing helpers
  Cargo.lock
  test-utils/client/Cargo.toml
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6565 Remove polkadot companion detection from branch name
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6561 primitives: use generic Header in testing runtime
  client/db/src/cache/list_cache.rs
  client/db/src/cache/list_entry.rs
  frame/finality-tracker/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  primitives/runtime/src/testing.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6568 Remove polkadot companion detection from branch name
  docs/CONTRIBUTING.adoc
Labels: A0-pleasereview, B0-silent, C1-low

#6566 Make the encoded-Call Vec<u8> explicitly so in metadata
  frame/multisig/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low

#6574 ci: fix merge on polkadot companion job
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#6493 pallet-evm: return Ok(()) when EVM execution fails
  frame/evm/src/lib.rs
  frame/evm/src/tests.rs
Labels: A7-needspolkadotpr, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#6362 babe: report equivocations
  Cargo.lock
  bin/node/cli/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/aux_schema.rs
  frame/babe/Cargo.toml
  frame/babe/src/benchmarking.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/im-online/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/offences/src/tests.rs
  frame/session/benchmarking/Cargo.toml
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/lib.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/slots/Cargo.toml
  primitives/consensus/slots/src/lib.rs
  primitives/core/src/lib.rs
  primitives/session/src/lib.rs
  primitives/staking/src/offence.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low

#6567 Benchmarks Writer CLI
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6576 Don't require module name in inherents
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/example/src/lib.rs
  frame/grandpa/src/equivocation.rs
  frame/proxy/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/inherent.rs
  frame/support/test/tests/construct_runtime_ui/params_in_invalid_module.rs
  frame/support/test/tests/construct_runtime_ui/params_in_invalid_module.stderr
Labels: A3-needsresolving, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low

#6581 Derive `RuntimeDebug` for `Runtime`
  frame/support/procedural/src/construct_runtime/mod.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6589 Fix ui tests in CI
  Cargo.lock
  frame/support/Cargo.toml
  frame/transaction-payment/Cargo.toml
  primitives/state-machine/Cargo.toml
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6533 Use async/await in build_network_future
  Cargo.lock
  client/informant/Cargo.toml
  client/informant/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  primitives/utils/src/status_sinks.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6500 decl_module! macro: use 'frame_system' instead of `system` as default ident
  bin/node-template/pallets/template/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/assets/src/lib.rs
  frame/contracts/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/evm/src/lib.rs
  frame/example/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/weights.rs
  frame/support/test/tests/construct_runtime_ui/missing_system_module.stderr
  frame/support/test/tests/instance.rs
  frame/timestamp/src/lib.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A7-needspolkadotpr, A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6584 Upgrade `kvdb-*`, `trie-db` and `memory-db`
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/api/Cargo.toml
  client/cli/Cargo.toml
  client/db/Cargo.toml
  client/informant/Cargo.toml
  client/service/Cargo.toml
  client/state-db/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  frame/support/Cargo.toml
  primitives/core/Cargo.toml
  primitives/database/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/test-primitives/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#6556 client/network: Rename DebugInfoBehaviour to PeerInfoBehaviour
  client/network/src/behaviour.rs
  client/network/src/lib.rs
  client/network/src/peer_info.rs
Labels: A7-needspolkadotpr, A8-mergeoncegreen, B0-silent, C1-low

#6564 Add log rotation
  Cargo.lock
  bin/node/bench/src/main.rs
  client/cli/Cargo.toml
  client/cli/src/config.rs
  client/cli/src/error.rs
  client/cli/src/lib.rs
  client/cli/src/logger.rs
  client/cli/src/params/shared_params.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6593 Send Status message on all newly-opened legacy substreams
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#6559 *: Update to libp2p v0.21.1
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/block_requests.rs
  client/network/src/discovery.rs
  client/network/src/finality_requests.rs
  client/network/src/light_client_handler.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, A1-needsburnin, B5-clientnoteworthy, C1-low

#6546 Fix build when with-kvdb-rocksdb is disabled.
  client/db/src/utils.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6598 Make evm errors public
  frame/evm/src/lib.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6592 Improved send_transaction helper to return an error in case of error
  Cargo.lock
  test-utils/client/Cargo.toml
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6619 Rename `CheckEra` to `CheckMortality`
  frame/system/src/extensions/check_mortality.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low

#6614 Add an authority_discovery_known_authorities_count metric
  client/authority-discovery/src/addr_cache.rs
  client/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6339 Clean exit when no space left on device
  Cargo.lock
  client/api/src/leaves.rs
  client/db/src/cache/mod.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/children.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/offchain.rs
  client/db/src/parity_db.rs
  client/db/src/utils.rs
  primitives/blockchain/Cargo.toml
  primitives/blockchain/src/error.rs
  primitives/database/src/error.rs
  primitives/database/src/kvdb.rs
  primitives/database/src/lib.rs
  primitives/database/src/mem.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6573 seal: Rework contracts API
  Cargo.lock
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/COMPLEXITY.md
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/check_default_rent_allowance.wat
  frame/contracts/fixtures/crypto_hashes.wat
  frame/contracts/fixtures/destroy_and_transfer.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/fixtures/restoration.wat
  frame/contracts/fixtures/return_from_start_fn.wat
  frame/contracts/fixtures/return_with_data.wat
  frame/contracts/fixtures/self_destruct.wat
  frame/contracts/fixtures/self_destructing_constructor.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/fixtures/storage_size.wat
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low

#6611 Simplify a few chain components creation APIs related to the service
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/api/src/execution_extensions.rs
  client/api/src/in_mem.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/finality-grandpa/src/lib.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/transaction-pool/src/lib.rs
  primitives/consensus/common/Cargo.toml
  primitives/core/src/tasks.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A7-needspolkadotpr, B0-silent, C1-low

#6620 Make `init_logging` more easily usable
  bin/node/bench/src/main.rs
  client/cli/src/config.rs
  client/cli/src/logger.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6622 add ios to cfg gates in client/service
  client/service/Cargo.toml
  client/service/src/metrics.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6560 Node template love
  bin/node-template/README.md
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6602 change ss58 format for SubstraTEE from 44 to 13 and add ChainX
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6628 Deduplicate some dependencies
  Cargo.lock
  client/network/Cargo.toml
  client/service/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6627 Revert "Add log rotation (#6564)"
  Cargo.lock
  bin/node/bench/src/main.rs
  client/cli/Cargo.toml
  client/cli/src/config.rs
  client/cli/src/error.rs
  client/cli/src/lib.rs
  client/cli/src/params/shared_params.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6623 seal: Prevent contracts from going below subsistence
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6630 Remove warning about networking taking a lot of time
  client/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6621 Add FromStr for AccountId32
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6626 Clarify some host interfaces
  primitives/io/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6638 Remove duplicate comments about testing setup.
  frame/assets/src/lib.rs
  frame/atomic-swap/src/tests.rs
  frame/benchmarking/src/tests.rs
  frame/evm/src/tests.rs
  frame/generic-asset/src/mock.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/recovery/src/mock.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/society/src/mock.rs
  frame/sudo/src/mock.rs
  frame/vesting/src/lib.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6616 Make signature batching use specialized methods
  frame/executive/src/lib.rs
  primitives/io/src/batch_verifier.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D6-newhostfunctions

#6636 Check that `serde` is present in `sc-chain-spec-derive`
  client/chain-spec/derive/src/impls.rs
  client/chain-spec/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6646 ci: add deployment of polkadot prometheus rules
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6590 Implement apply_state flag and allow fetching return data and used gas
  Cargo.lock
  frame/evm/Cargo.toml
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6652 Remove legacy Clogged event
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6650 Fix two minor warnings
  frame/babe/src/benchmarking.rs
  primitives/finality-grandpa/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6578 allow to specify schedule time as a relative value
  bin/node/runtime/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#5938 Move the legacy protocol handshake to the legacy substream
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6631 [CI] Fix check_polkadot_companion_status.sh
  .maintain/gitlab/check_polkadot_companion_status.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6663 sc-offchain: upgrade hyper-rustls to 0.18
  Cargo.lock
  client/offchain/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6645 Support Component-less Runtime Benchmarks
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#6570 Remove polkadot companion detection from url anywhere
  .gitlab-ci.yml
  .maintain/gitlab/check_polkadot_companion_build.sh
  .maintain/gitlab/check_polkadot_companion_status.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6666 The telemetry should not be initialized if no telemetry has been provided
  client/service/src/builder.rs
  client/telemetry/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6670 Staking: fix inline comment.
  frame/staking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6597 Regression test to ensure we don't break deterministic builds in wasm
  .gitlab-ci.yml
Labels: A2-insubstantial, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#6649 Update the substrate-networking Grafana dashboard with latest changes
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
Labels: A2-insubstantial, B5-clientnoteworthy, C1-low

#6647 client/service/metrics: Rework metric HELP texts
  client/service/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6648 .maintain/monitoring/alerting-rules: Remove HighCPUUsage alert
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#6667 identity: Don't let subs be re-registered
  frame/assets/src/lib.rs
  frame/aura/src/mock.rs
  frame/authority-discovery/src/lib.rs
  frame/authorship/src/lib.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/evm/src/tests.rs
  frame/example-offchain-worker/src/tests.rs
  frame/example/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/mock.rs
  frame/system/benchmarking/src/mock.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#6671 Treasury burning can be directed
  bin/node/runtime/src/lib.rs
  frame/society/src/lib.rs
  frame/support/src/traits.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6640 Switch to bounded mpsc for txpool import notification stream
  Cargo.lock
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  primitives/transaction-pool/Cargo.toml
  primitives/transaction-pool/src/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6656 grandpa: report equivocations with unsigned extrinsics
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/keyring.rs
  bin/utils/subkey/src/main.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
  frame/grandpa/Cargo.toml
  frame/grandpa/src/benchmarking.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
  primitives/finality-grandpa/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6675 Tiny change: change unknown-commit to unknown to make parsing easier
  bin/node/cli/tests/version.rs
  utils/build-script-utils/src/version.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6673 bump sysinfo for ios
  Cargo.lock
  client/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#6633 Fix tx-payment integrity-test
  frame/support/src/dispatch.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#6688 fix check polkadot companion status check
  .maintain/gitlab/check_polkadot_companion_status.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6676 Fix compilation problems due to ed25519-dalek 1.0.0-pre.4
  Cargo.lock
  primitives/core/Cargo.toml
  primitives/core/src/ed25519.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6684 More app-friendly event description
  bin/node-template/pallets/template/src/lib.rs
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/balances/src/lib.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/evm/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/src/lib.rs
  frame/proxy/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6690 Update libp2p to 0.22.
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: B0-silent, C3-medium

#6694 Add try_mutate_exists to StorageDoubleMap
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, B3-apinoteworthy, C1-low, D2-breaksapi

#6697 Add ECDSA verifying/signing benchmarks
  primitives/core/benches/bench.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6698 Add sync_legacy_requests_received metric
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6682 Remove dead link to out-of-date style guide
  docs/CONTRIBUTING.adoc
  docs/STYLE_GUIDE.md
Labels: A5-grumble, A7-needspolkadotpr, B0-silent, C1-low

#6606 "cargo test" jobs optimization
  .gitlab-ci.yml
  frame/support/test/tests/decl_module_ui.rs
  frame/support/test/tests/decl_storage_ui.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6693 Properly filter out duplicate voters in elections.
  frame/staking/src/tests.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#6580 pallet-swap-action: Change `BalanceSwapAction` signature
  frame/atomic-swap/src/lib.rs
  frame/atomic-swap/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6695 make impl_outer_origin default to use frame_system
  frame/im-online/src/mock.rs
  frame/support/src/metadata.rs
  frame/support/src/origin.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6701 Removing staging resources from node template README
  bin/node-template/README.md
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6654 Graceful shutdown for the task manager
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/runner.rs
  client/service/Cargo.toml
  client/service/src/config.rs
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C3-medium

#6703 Reset flaming fir network
  bin/node/cli/res/flaming-fir.json
Labels: A2-insubstantial, B0-silent, C1-low, D0-patchthis

#6679 Tracing values
  client/executor/src/integration_tests/mod.rs
  client/tracing/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6708 Update to latest sysinfo prevents leaking fd-handlers
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/metrics.rs
Labels: A1-needsburnin, A2-insubstantial, B5-clientnoteworthy, C3-medium

#6662 Update wasmtime to (almost) lastest master
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, A1-needsburnin, B5-clientnoteworthy, C3-medium

#6557 Remove the service builder
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low

#6569 Better handling of stable-only build
  Cargo.lock
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/command.rs
  bin/node-template/runtime/build.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/build.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/bench.rs
  bin/node/testing/src/genesis.rs
  client/executor/runtime-test/build.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/network/Cargo.toml
  frame/support/test/Cargo.toml
  frame/system/src/tests.rs
  primitives/runtime-interface/test-wasm-deprecated/build.rs
  primitives/runtime-interface/test-wasm-deprecated/src/lib.rs
  primitives/runtime-interface/test-wasm/build.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
  test-utils/runtime/build.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/wasm-builder-runner/src/lib.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, A8-mergeoncegreen, B3-apinoteworthy, C1-low, D2-breaksapi

#6710 Remove clear_on_drop from browser util crate
  Cargo.lock
  utils/browser/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6713 Add 4 as address type of ss58 for Katal Chain
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#5793 [CI]Chaostest suite initiation
  .gitlab-ci.yml
  .maintain/chaostest/.eslintignore
  .maintain/chaostest/.eslintrc.json
  .maintain/chaostest/.gitignore
  .maintain/chaostest/README.md
  .maintain/chaostest/bin/run
  .maintain/chaostest/bin/run.cmd
  .maintain/chaostest/package-lock.json
  .maintain/chaostest/package.json
  .maintain/chaostest/src/commands/clean/index.js
  .maintain/chaostest/src/commands/singlenodeheight/index.js
  .maintain/chaostest/src/commands/spawn/index.js
  .maintain/chaostest/src/config/README.md
  .maintain/chaostest/src/config/index.js
  .maintain/chaostest/src/hypervisor/chainApi/api.js
  .maintain/chaostest/src/hypervisor/chainApi/index.js
  .maintain/chaostest/src/hypervisor/deployment/deployment.js
  .maintain/chaostest/src/hypervisor/deployment/index.js
  .maintain/chaostest/src/hypervisor/index.js
  .maintain/chaostest/src/hypervisor/modules/chainApi.js
  .maintain/chaostest/src/hypervisor/modules/k8s.js
  .maintain/chaostest/src/index.js
  .maintain/chaostest/src/utils/exit.js
  .maintain/chaostest/src/utils/index.js
  .maintain/chaostest/src/utils/logger.js
  .maintain/chaostest/src/utils/wait.js
Labels: A6-seemsok, A8-mergeoncegreen, B0-silent, C1-low

#6659 Support using system storage directly for EVM balance and nonce
  frame/evm/src/backend.rs
  frame/evm/src/lib.rs
  frame/evm/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6721 Augmented node template docs
  bin/node-template/README.md
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/pallets/template/src/mock.rs
  bin/node-template/pallets/template/src/tests.rs
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6722 Switching from git back to released versions for wasmtime, fix cargo-unleash
  Cargo.lock
  client/cli/src/lib.rs
  client/executor/wasmtime/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6728 Prepping for release of rc5 – River Dolphin
  docs/CHANGELOG.md
Labels: A2-insubstantial, B0-silent, C1-low

#6725 grandpa: allow noting that the set has stalled
  client/finality-grandpa/src/authorities.rs
  frame/grandpa/src/benchmarking.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6726 Name all the tasks!
  Cargo.lock
  bin/node/bench/src/txpool.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/api/src/lib.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/light/src/call_executor.rs
  client/light/src/fetcher.rs
  client/light/src/lib.rs
  client/network/src/service/tests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/lib.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/lib.rs
  client/service/src/task_manager/mod.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  primitives/core/src/tasks.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/externalities/src/extensions.rs
  primitives/io/src/batch_verifier.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/testing.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low

#6665 Add the Substrate Service Tasks dashboard
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A0-pleasereview, B0-silent, C1-low

#6719 seal: Fail instantiate if new contract is below subsistence threshold
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#6711 Remove Unpin requirement for Slots
  client/consensus/slots/src/slots.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6681 pallet-evm: add support for tuple-based precompile declarations
  Cargo.lock
  frame/evm/Cargo.toml
  frame/evm/src/lib.rs
  frame/evm/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6744 prometheus: don't use protobuf feature
  Cargo.lock
  primitives/utils/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, dependencies

#6737 Revert change to which node-template Block type is used.
  bin/node-template/node/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6738 Various small improvements to service construction.
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node/bench/src/txpool.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/src/lib.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/finality-grandpa/src/finality_proof.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6748 Remove unused node template deps
  Cargo.lock
  bin/node-template/README.md
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#6740 Replace Process.toml with json
  Process.json
  Process.toml
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#6715 seal: Add benchmarks for dispatchables
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/benchmarks/dummy.wat
  frame/contracts/src/benchmarking.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6755 client/network: Adjust wording
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6692 Add a back-pressure-friendly alternative to NetworkService::write_notifications 🎉
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6754 Cleanup our sort usage
  client/authority-discovery/src/addr_cache.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  frame/collective/src/lib.rs
  frame/contracts/src/wasm/runtime.rs
  frame/staking/src/lib.rs
  frame/support/src/traits.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/arithmetic/src/lib.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6749 Allow `PostDispatchInfo` to disable fees
  frame/contracts/src/gas.rs
  frame/contracts/src/tests.rs
  frame/sudo/src/lib.rs
  frame/support/src/weights.rs
  frame/system/src/extensions/check_weight.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6750 benchmarks! macro: factorize instance usage.
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#6549 client/network: Add peers to DHT only if protocols match
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low

#6745 Add `memory-tracker` feature to `sp-trie` to fix wasm panic
  Cargo.lock
  bin/node/cli/Cargo.toml
  primitives/trie/Cargo.toml
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#5526 support custom ss58addressformat in from_ss58check_with_version
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6761 Add a `DefaultQueue` type alias to remove the need to use `sp_api::TransactionFor`
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6767 Ignore flaky test
  client/network/src/service/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6764 Add "✅ Successfully mined block" log message
  client/consensus/pow/src/lib.rs
Labels: B0-silent, C1-low

#6743 pallet-evm: add builtin support for the four basic Ethereum precompiles
  Cargo.lock
  frame/evm/Cargo.toml
  frame/evm/src/lib.rs
  frame/evm/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6768 Rename task name to stick to the default naming scheme
  client/rpc/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6563 BABE slot and epoch event notifications
  Cargo.lock
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6610 Update Balances Pallet to use `WeightInfo`
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_balances.rs
  frame/balances/src/benchmarking.rs
  frame/balances/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6769 Fix graceful shutdown skipped if future ends with error
  client/cli/src/runner.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6775 Fix dead link
  frame/staking/reward-curve/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6301 Allow blacklisting blocks from being finalized again after block revert
  Cargo.lock
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/light/src/backend.rs
  client/service/src/chain_ops/revert_chain.rs
  client/service/src/client/block_rules.rs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6780 Order delta before calculating the storage root
  primitives/trie/src/lib.rs
  primitives/trie/test-res/invalid-delta-order
  primitives/trie/test-res/proof
  primitives/trie/test-res/storage_root
  primitives/trie/test-res/valid-delta-order
Labels: A0-pleasereview, B0-silent, C1-low

#6781 Don't close inbound notifications substreams immediately
  client/network/src/lib.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
Labels: A0-pleasereview, B0-silent, C3-medium
