Repository paritytech/substrate, pull requests merged in 2020-02, with the labels that each got.

#4792 Increase transaction pool default limits
  client/basic-authorship/src/basic_authorship.rs
  client/cli/src/params.rs
  client/transaction-pool/graph/src/validated_pool.rs
Labels: A0-pleasereview

#4789 Update prost-build dependency
  Cargo.lock
  client/authority-discovery/Cargo.toml
Labels: A2-insubstantial

#4797 Remove warning about connecting to non-Substrate nodes
  client/network/src/behaviour.rs
Labels: A2-insubstantial

#4784 fork-tree: add support for find_node_mut_where
  utils/fork-tree/src/lib.rs
Labels: A8-looksgood

#4802 Don't attempt to upgrade balances module on chain start
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/balances/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, P2-asap

#4809 block_import: switch to Box<dyn Any> for intermediates representation
  client/consensus/pow/src/lib.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/error.rs
Labels: A0-pleasereview

#4815 Fix call to backend in child_storage_hash
  primitives/state-machine/src/ext.rs
Labels: A0-pleasereview

#4718 add state_getKeysPaged
  client/rpc-api/src/state/error.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/src/client.rs
Labels: A8-looksgood

#4791 Added GetCallMetadata for extrinsic calls.
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B1-runtimenoteworthy

#4819 Fix flaky messed signature test
  primitives/core/src/sr25519.rs
Labels: A2-insubstantial, B0-silent

#4817 Bump `parking_lot`
  Cargo.lock
  client/Cargo.toml
  client/api/Cargo.toml
  client/basic-authorship/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/consensus/slots/Cargo.toml
  client/db/Cargo.toml
  client/executor/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/keystore/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/state-db/Cargo.toml
  client/telemetry/Cargo.toml
  client/tracing/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  frame/aura/Cargo.toml
  frame/babe/Cargo.toml
  primitives/blockchain/Cargo.toml
  primitives/consensus/common/Cargo.toml
  primitives/core/Cargo.toml
  primitives/inherents/Cargo.toml
  primitives/state-machine/Cargo.toml
  test-utils/runtime/transaction-pool/Cargo.toml
  utils/grafana-data-source/Cargo.toml
Labels: A2-insubstantial, B0-silent

#4821 pallet-evm: log created address
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#4829 Fix missing overrides of NetworkBehaviour
  client/network/src/debug_info.rs
  client/network/src/discovery.rs
  client/network/src/protocol.rs
  client/network/src/protocol/legacy_proto/tests.rs
Labels: A0-pleasereview, B0-silent

#4831 Remove support for secio
  client/network/src/transport.rs
Labels: A0-pleasereview

#4830 Print an error if listener is closed
  client/network/src/discovery.rs
Labels: A2-insubstantial, B0-silent

#4833 Avoid losing values in intermediate take
  primitives/consensus/common/src/block_import.rs
Labels: A0-pleasereview, B0-silent

#4823 Get rid of in-substrate usages of `core_intrinsics` feature
  primitives/application-crypto/Cargo.toml
  primitives/io/src/lib.rs
  primitives/sandbox/src/lib.rs
  primitives/std/src/lib.rs
  primitives/std/without_std.rs
Labels: A0-pleasereview, B0-silent

#4803 Additional RPC for dumping all main storage key pairs under a prefix
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/src/client.rs
Labels: A0-pleasereview

#4825 executor: Simplify the SandboxCapabilities interface
  client/executor/common/src/sandbox.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/function_executor.rs
Labels: A0-pleasereview, B0-silent

#4813 grandpa: bump version to v0.11.1
  client/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, M4-core

#4835 node: disable grandpa automatic finality fallback
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, M4-core

#4832 Join verifications in batch async/await verification
  client/transaction-pool/graph/src/pool.rs
Labels: A0-pleasereview

#4811 Node template folders restructuring
  .maintain/node-template-release/src/main.rs
  Cargo.lock
  Cargo.toml
  bin/node-template/Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/node/build.rs
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/main.rs
  bin/node-template/node/src/service.rs
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/pallets/template/src/mock.rs
  bin/node-template/pallets/template/src/tests.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4841 Fixed a few warnings
  client/cli/src/node_key.rs
  client/network/src/behaviour.rs
  frame/authority-discovery/src/lib.rs
  frame/executive/src/lib.rs
Labels: A2-insubstantial, B0-silent

#4837 Fix memory leak in runtime interface
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/pass_by.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4840 Fix broken factory by adding keystore back.
  bin/node/cli/src/command.rs
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4812 CLI improvements & fixes
  .gitlab-ci.yml
  .maintain/check_for_exit.sh
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/cli/src/runtime.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/error.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: B1-apinoteworthy

#4838 Allocator improvements/clean ups
  primitives/allocator/src/freeing_bump.rs
Labels: A0-pleasereview, B0-silent

#4836 ci: enable build for pre-tags
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, M1-ci

#4785 Refactor epoch changes to a separate crate
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
  client/consensus/epochs/Cargo.toml
  client/consensus/epochs/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/babe/src/lib.rs
Labels: A0-pleasereview

#4807 babe: pass epoch data via intermediates
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4848 Easier with threads in tests
  client/finality-grandpa/src/tests.rs
Labels: B0-silent

#4845 Enable trace timings logs for transaction factory
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
Labels: A0-pleasereview, B0-silent

#4822 Subsystems memory tracking: 1. Transaction pool
  Cargo.lock
  client/Cargo.toml
  client/api/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/informant.rs
  client/db/Cargo.toml
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/future.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  frame/system/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/changes_trie.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/generic/block.rs
  primitives/runtime/src/generic/digest.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  primitives/test-primitives/Cargo.toml
  primitives/test-primitives/src/lib.rs
  primitives/transaction-pool/src/pool.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B1-clientnoteworthy

#4843 pow: re-add support for algorithms where only linear verification is possible
  client/consensus/pow/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4850 Move tracing cli args to `ImportParams`
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#4851 Fix CLI setup again
  bin/node/cli/src/command.rs
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/purge_chain_works.rs
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
Labels: A0-pleasereview, B0-silent

#4856 Implement From<DispatchError> for '&static str
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#4844 WIP: Test: does cargo update work?
  Cargo.lock
  primitives/core/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: B0-silent

#4847 Rename StorageMap::exists to ::contains_key (Resolves #4839)
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/collective/src/lib.rs
  frame/contracts/src/account_db.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/offences/src/lib.rs
  frame/recovery/src/lib.rs
  frame/recovery/src/tests.rs
  frame/scored-pool/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/linked_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/instance.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4863 Alter usage collection a bit
  client/db/src/lib.rs
  client/db/src/light.rs
Labels: A0-pleasereview

#4818 Create Benchmarking Setup for Identity Pallet #4695
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/db/Cargo.toml
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/lib.rs
  client/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/overlayed_changes.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#4864 Fix vesting logic
  bin/node/runtime/src/lib.rs
  frame/support/src/traits.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4561 Fix timer panics in the wasm light client
  Cargo.lock
  Cargo.toml
  bin/node/cli/browser-demo/index.html
  bin/node/cli/src/browser.rs
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/cli/src/runtime.rs
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/slots/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/periodic.rs
  client/informant/Cargo.toml
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/state_machine.rs
  client/network/Cargo.toml
  client/network/src/debug_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/legacy_proto/behaviour.rs
  client/network/src/protocol/legacy_proto/handler.rs
  client/network/src/protocol/legacy_proto/tests.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/network/test/src/sync.rs
  client/offchain/Cargo.toml
  client/peerset/Cargo.toml
  client/peerset/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/telemetry/Cargo.toml
  client/telemetry/src/lib.rs
  client/telemetry/src/worker.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/future.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/rotator.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  primitives/consensus/common/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/timestamp/src/lib.rs
  primitives/transaction-pool/src/pool.rs
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
  utils/grafana-data-source/Cargo.toml
  utils/grafana-data-source/test/Cargo.toml
Labels: A1-onice

#4875 Don't expose `Benchmarking` host functions by default
  bin/node/executor/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#4871 Add timing trace for import block.
  client/src/client.rs
Labels: A0-pleasereview, B0-silent

#4855 Refactor and document allocator
  primitives/allocator/src/freeing_bump.rs
Labels: A0-pleasereview, B0-silent

#4804 Avoid challenging those that can't be suspended anyway
  frame/society/src/lib.rs
  frame/society/src/tests.rs
Labels: A0-pleasereview

#4854 Add trait to get module and call names.
  bin/node/runtime/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent

#4805 Fix runtime interface tests on Windows
  primitives/runtime-interface/test-wasm/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#4866 Update primitive-types crate
  Cargo.lock
  frame/evm/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/core/Cargo.toml
  primitives/runtime-interface/Cargo.toml
Labels: A2-insubstantial, B0-silent

#4878 Run offchain workers at hash, not number.
  client/db/src/utils.rs
  client/offchain/src/lib.rs
  client/service/src/builder.rs
  primitives/blockchain/src/backend.rs
Labels: A0-pleasereview, M4-core

#4858 Change prefixed trie iterator to be limited to prefix. BREAKING
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#4882 Add support for json output in subkey
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/main.rs
Labels: B0-silent

#4886 impl Randomness trait for Babe and remove unused RandomBeacon trait
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  frame/support/src/traits.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview

#4828 Pause Kademlia if too many connections
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent

#4870 Refactor tx factory 1
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/factory_impl.rs
  bin/node/transaction-factory/src/complex_mode.rs
  bin/node/transaction-factory/src/lib.rs
  bin/node/transaction-factory/src/modes.rs
  bin/node/transaction-factory/src/simple_modes.rs
Labels: A0-pleasereview, B0-silent

#4893 pallet-evm: optional nonce parameter
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#4889 Increase the reputation penality for being offline
  client/peerset/src/lib.rs
Labels: A0-pleasereview

#4891 Benchmark Timestamp Pallet
  bin/node/runtime/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/timestamp/Cargo.toml
  frame/timestamp/src/benchmarking.rs
  frame/timestamp/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent

#4892 Add command-line flag to enable yamux flow control.
  Cargo.lock
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/network/Cargo.toml
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview

#4894 Do not allow zero Existential Deposit when using Balances
  frame/balances/src/lib.rs
  frame/balances/src/mock.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/lib.rs
  frame/elections/src/mock.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/identity/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/society/src/lib.rs
  frame/society/src/mock.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#3520 network: Use "one shot" protocol handler.
  Cargo.lock
  client/network/Cargo.toml
  client/network/build.rs
  client/network/src/behaviour.rs
  client/network/src/protocol.rs
  client/network/src/protocol/block_requests.rs
  client/network/src/protocol/light_client_handler.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/schema/api.v1.proto
  client/network/src/protocol/schema/light.v1.proto
  client/network/src/service.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#4879 Benchmark the Balances Pallet
  bin/node/runtime/src/lib.rs
  frame/balances/src/benchmarking.rs
  frame/balances/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4767 client/network-gossip: Integrate GossipEngine tasks into Future impl
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, B0-silent

#4896 add some more docs on PreRuntime digests
  primitives/runtime/src/generic/digest.rs
Labels: A2-insubstantial, B0-silent

#4905 Add sr25519 bench
  primitives/core/benches/bench.rs
  primitives/core/src/lib.rs
  primitives/core/src/tests.rs
Labels: A2-insubstantial

#4906 Fix chain-spec and make sure it does not breaks again
  bin/node/cli/src/chain_spec.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#4865 Full block import benchmark
  Cargo.lock
  bin/node/runtime/src/lib.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/benches/import.rs
  bin/node/testing/src/client.rs
  bin/node/testing/src/genesis.rs
  client/api/src/client.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  primitives/keyring/src/sr25519.rs
Labels: A0-pleasereview, B0-silent

#4904 Per-things trait.
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/transaction-factory/src/lib.rs
  client/src/cht.rs
  client/src/leaves.rs
  client/src/light/fetcher.rs
  client/transaction-pool/src/lib.rs
  frame/assets/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/balances/src/lib.rs
  frame/contracts/src/gas.rs
  frame/elections-phragmen/src/lib.rs
  frame/example/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/slashing.rs
  frame/support/src/traits.rs
  frame/system/benches/bench.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/lib.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/arithmetic/src/traits.rs
  primitives/phragmen/src/lib.rs
  primitives/phragmen/src/mock.rs
  primitives/phragmen/src/tests.rs
  primitives/runtime/src/curve.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4686 executor: Migrate wasmtime backend to a high-level API
  Cargo.lock
  client/executor/common/src/wasm_runtime.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/function_executor.rs
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/state_holder.rs
  client/executor/wasmtime/src/trampoline.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview

#4918 Fix benchmarks on master
  Cargo.lock
  bin/node/testing/Cargo.toml
Labels: A2-insubstantial

#4907 pallet-evm: add support for transaction-level create2
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/evm/Cargo.toml
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#4922 pallet-evm: refactor duplicate code in call/create/create2
  bin/node/runtime/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4903 Adds a test to ensure that we clear the heap between calls into runtime
  client/executor/common/src/wasm_runtime.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent

#4883 Allow to distinguish out of gas from other traps
  bin/node/runtime/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi, M8-contracts

#4740 Adds fork-awareness and finalization notifications to transaction pool watchers.
  Cargo.lock
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_new_block.rs
  client/rpc-api/Cargo.toml
  client/service/src/builder.rs
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/graph/benches/basics.rs
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/graph/src/watcher.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  primitives/blockchain/src/header_metadata.rs
  primitives/transaction-pool/src/pool.rs
  test-utils/runtime/transaction-pool/Cargo.toml
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B1-clientnoteworthy, M4-core, M6-rpcapi

#4930 Remove rename for finalized event and add some docs.
  primitives/transaction-pool/src/pool.rs
Labels: A0-pleasereview, B1-apinoteworthy, M6-rpcapi

#4937 Remove default expansion from `construct_runtime!`
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/lib.rs
  frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.rs
  frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.stderr
  frame/support/test/tests/construct_runtime_ui/double_module_parts.rs
  frame/support/test/tests/construct_runtime_ui/double_module_parts_default.rs
  frame/support/test/tests/construct_runtime_ui/double_module_parts_default.stderr
  frame/support/test/tests/construct_runtime_ui/generics_in_invalid_module.rs
  frame/support/test/tests/construct_runtime_ui/invalid_module_details_keyword.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.rs
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_token_after_module.stderr
  frame/support/test/tests/construct_runtime_ui/missing_event_generic_on_module_with_instance.rs
  frame/support/test/tests/construct_runtime_ui/missing_origin_generic_on_module_with_instance.rs
  frame/support/test/tests/construct_runtime_ui/params_in_invalid_module.rs
Labels: A0-pleasereview, B1-runtimenoteworthy

#4936 Refactor BlockImportParams to be non_exhaustive
  bin/node/cli/src/service.rs
  bin/node/testing/benches/import.rs
  bin/node/transaction-factory/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_new_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/tests.rs
  client/network/test/src/lib.rs
  primitives/consensus/common/src/block_import.rs
  test-utils/client/src/client_ext.rs
Labels: A0-pleasereview, B2-breaksapi

#4929 Fix import queue thread pool shutdown
  client/cli/src/runtime.rs
  client/consensus/babe/src/tests.rs
  client/network/test/src/lib.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/import_queue/buffered_link.rs
Labels: A0-pleasereview, B0-silent

#4928 Update libp2p to 0.16
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/debug_info.rs
  client/network/src/discovery.rs
  client/network/src/protocol.rs
  client/network/src/protocol/block_requests.rs
  client/network/src/protocol/legacy_proto/behaviour.rs
  client/network/src/protocol/legacy_proto/handler.rs
  client/network/src/protocol/legacy_proto/tests.rs
  client/network/src/protocol/light_client_handler.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/peerset/src/peersstate.rs
  client/peerset/tests/fuzz.rs
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent

#4941 Update import benchmark parameters
  bin/node/testing/benches/import.rs
Labels: A2-insubstantial

#4945 Database & keyring generation for benchmarks optimised
  bin/node/testing/benches/import.rs
Labels: A2-insubstantial, B0-silent

#4781 Revalidation queue for transaction pool
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/src/lib.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4946 Add passthrough weight to Sudo
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/weights.rs
Labels: A0-pleasereview, B2-breaksapi

#4729 Adds babe rpc support
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/keystore/src/lib.rs
  client/service/src/builder.rs
  frame/babe/src/lib.rs
  primitives/consensus/babe/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: B1-clientnoteworthy, B2-breaksapi, M4-core, M6-rpcapi

#4951 Fix potential panics related to time
  client/network/src/protocol/legacy_proto/behaviour.rs
  client/peerset/src/lib.rs
Labels: A0-pleasereview, B0-silent

#4953 Utility/Recovery passthrough always pays a fee.
  bin/node/runtime/src/lib.rs
  frame/recovery/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#4860 offchain: Upgrade hyper to 0.13, which uses tokio 0.2
  Cargo.lock
  client/network/Cargo.toml
  client/offchain/Cargo.toml
  client/offchain/src/api/http.rs
  client/service/Cargo.toml
  utils/grafana-data-source/Cargo.toml
  utils/grafana-data-source/src/lib.rs
  utils/grafana-data-source/src/server.rs
Labels: A0-pleasereview, B0-silent

#4955 Reusable bench-db & bench-keyring
  Cargo.lock
  bin/node/testing/Cargo.toml
  bin/node/testing/benches/import.rs
  bin/node/testing/src/bench.rs
  bin/node/testing/src/lib.rs
Labels: A2-insubstantial, B0-silent

#4960 Make GenesisSource thread-safe
  client/chain-spec/src/chain_spec.rs
Labels: A8-looksgood, B0-silent

#4968 Remove direct yamux dependency.
  Cargo.lock
  client/network/Cargo.toml
  client/network/src/transport.rs
Labels: A0-pleasereview

#4957 sync: process empty response for justification requests
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/extra_requests.rs
Labels: A0-pleasereview, B0-patchthis, B1-clientnoteworthy, M4-core

#4967 Fix flaky finalisation test
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview

#4966 Use a single version of once_cell
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  frame/support/Cargo.toml
  primitives/core/Cargo.toml
Labels: A2-insubstantial, A7-looksgoodcantmerge, B0-silent, M5-dependencies

#4880 Re-enable networking on wasm
  bin/node/cli/Cargo.toml
  client/network/src/protocol/light_client_handler.rs
  client/network/src/transport.rs
  client/telemetry/src/worker.rs
Labels: A7-looksgoodcantmerge

#4697 Inspection extension to node CLI
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/lib.rs
  bin/node/inspect/Cargo.toml
  bin/node/inspect/src/cli.rs
  bin/node/inspect/src/lib.rs
  client/service/src/config.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
Labels: A7-looksgoodcantmerge, M4-core

#4950 Fix description of --no-private-ipv4
  client/cli/src/params.rs
  client/network/src/config.rs
Labels: A2-insubstantial, A7-looksgoodcantmerge

#4973 [In Progress] Remove deprecated api
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/network/src/protocol/specialization.rs
Labels: A3-inprogress

#4916 Build block without checking signatures
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/rpc/src/state/tests.rs
  client/service/src/lib.rs
  frame/executive/src/lib.rs
  frame/im-online/src/tests.rs
  primitives/block-builder/src/lib.rs
  primitives/runtime/src/generic/mod.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A7-looksgoodcantmerge, B1-clientnoteworthy, B2-breaksapi

#4977 Consolidate frame benchmarking into a frame crate
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/executor/Cargo.toml
  bin/node/executor/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/service/src/chain_ops.rs
  frame/balances/Cargo.toml
  frame/balances/src/benchmarking.rs
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/lib.rs
  frame/identity/Cargo.toml
  frame/identity/src/benchmarking.rs
  frame/timestamp/Cargo.toml
  frame/timestamp/src/benchmarking.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A7-looksgoodcantmerge, B0-silent

#4932 Rename remaining occurences of SRML to FRAME
  bin/node-template/README.md
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/pallets/template/src/mock.rs
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/constants.rs
  docs/CONTRIBUTING.adoc
  docs/README.adoc
  frame/assets/src/lib.rs
  frame/authorship/Cargo.toml
  frame/authorship/src/lib.rs
  frame/babe/src/lib.rs
  frame/balances/src/lib.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/finality-tracker/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/generic-asset/src/mock.rs
  frame/identity/src/lib.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/recovery/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/session/src/historical.rs
  frame/session/src/lib.rs
  frame/society/src/mock.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
  primitives/finality-tracker/src/lib.rs
  primitives/phragmen/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A8-looksgood

#4982 Wasm benchmark import per block size
  bin/node/testing/benches/import.rs
Labels: A2-insubstantial, A4-awaitingci, B0-silent

#4981 Introduce Prometheus metric endpoint replacing Grafana endpoint
  Cargo.lock
  Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/cli/src/params.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/error.rs
  client/service/test/src/lib.rs
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  utils/grafana-data-source/src/database.rs
  utils/grafana-data-source/src/lib.rs
  utils/grafana-data-source/src/server.rs
  utils/grafana-data-source/src/types.rs
  utils/grafana-data-source/test/Cargo.toml
  utils/grafana-data-source/test/src/main.rs
  utils/prometheus/Cargo.toml
  utils/prometheus/README.md
  utils/prometheus/src/lib.rs
  utils/prometheus/src/networking.rs
Labels: A0-pleasereview, B1-clientnoteworthy

#4985 Re-export PeerId from the peerset API
  client/peerset/src/lib.rs
Labels: A2-insubstantial, B0-silent

#4983 Cleanup the exports of sc-network
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/tests.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/network_state.rs
  client/network/src/protocol/light_dispatch.rs
  client/network/src/protocol/specialization.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/blocks.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/peerset/src/lib.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B1-apinoteworthy

#4991 docs/CODEOWNERS: Add mxinden to /utils/prometheus/
  docs/CODEOWNERS
Labels: A2-insubstantial

#4988 Log kademlia errors when get/put record fails.
  client/network/src/discovery.rs
Labels: A0-pleasereview

#4995 Speedup import benchmark
  bin/node/testing/benches/import.rs
Labels: A2-insubstantial

#4999 Remove using a network message in the chain_ops (?!?!)
  client/service/src/chain_ops.rs
Labels: A0-pleasereview

#4996 babe: fix deprecated function in transcript
  client/consensus/babe/src/authorship.rs
Labels: A0-pleasereview, B0-silent

#4976 fixes sc_transaction_pool::testing::fork_aware_finalization
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview

#4987 `vesting_balance` returns `Option`
  bin/node/runtime/src/lib.rs
  frame/support/src/traits.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#5001 Clean up the public API of sc-network-gossip
  Cargo.lock
  client/finality-grandpa/src/communication/tests.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
Labels: A2-insubstantial, B0-silent

#4989 Offchain Workers: Example Pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/example-offchain-worker/Cargo.toml
  frame/example-offchain-worker/src/lib.rs
  frame/example-offchain-worker/src/tests.rs
  frame/executive/src/lib.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
  primitives/core/src/offchain/testing.rs
  primitives/runtime/src/offchain/mod.rs
Labels: A8-looksgood, M4-core

#4998 Unsigned transactions should also note weight
  Cargo.lock
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
Labels: A8-looksgood, B0-silent, B2-breaksapi

#4993 Remove deprecated API
  bin/node/cli/src/service.rs
  client/block-builder/src/lib.rs
  client/consensus/babe/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/lib.rs
  primitives/block-builder/src/lib.rs
  primitives/blockchain/src/error.rs
Labels: A8-looksgood, B2-breaksapi

#4962 Benchmark macro
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/balances/src/benchmarking.rs
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/timestamp/src/benchmarking.rs
Labels: A0-pleasereview, A4-clasignoffneeded

#5012 CI: Add example CI job template to .gitlab-ci.yml
  .gitlab-ci.yml
Labels: B0-silent, M1-ci, M3-docs

#5003 Un-deprecate ValidateUnsigned
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
  frame/support/src/unsigned.rs
  primitives/runtime/src/generic/checked_extrinsic.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, M4-core

#5005 babe: directly use append_u64 in transcript instead of to_le_bytes
  client/consensus/babe/src/authorship.rs
Labels: A0-pleasereview, B0-silent

#4958 aura: remove unneeded SlotDuration struct and rename digest -> digests
  bin/node-template/node/src/service.rs
  client/consensus/aura/src/digests.rs
  client/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5017 Make sure we use libp2p 0.16.1
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A2-insubstantial, B0-silent

#5011 node, node-template: disable GRANDPA observer
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B2-breaksapi, M4-core

#4909 Open one substream for each notifications protocol
  Cargo.lock
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network/Cargo.toml
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade.rs
  client/network/src/protocol/generic_proto/upgrade/collec.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B1-apinoteworthy, B1-clientnoteworthy

#5004 Wait for RPC server to cleanup on shutdown
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent

#5014 Removes use of sc_client::Client from sc_consensus_babe
  bin/node/cli/src/service.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
Labels: A0-pleasereview

#5009 Add gitlab job for publishing draft releases
  .gitlab-ci.yml
  scripts/gitlab/lib.sh
  scripts/gitlab/publish_draft_release.sh
Labels: A3-inprogress, B0-silent, M1-ci

#4665 Remove `NetworkSpecialization`
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/authority-discovery/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/lib.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/specialization.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  client/service/src/chain_ops.rs
  client/service/src/lib.rs
Labels: A4-awaitingci

#5019 Update the documentation for `secp256k1_ecdsa_recover*`
  primitives/io/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#5035 Add storage root recalculation time to benchmarks
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, B0-silent

#5020 adding unleash to ci
  .gitlab-ci.yml
  Cargo.lock
  bin/node/testing/Cargo.toml
  bin/node/testing/src/bench.rs
  client/authority-discovery/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  primitives/runtime-interface/test-wasm/Cargo.toml
  primitives/test-primitives/Cargo.toml
  test-utils/client/Cargo.toml
  test-utils/runtime/Cargo.toml
  test-utils/runtime/client/Cargo.toml
  test-utils/runtime/transaction-pool/Cargo.toml
Labels: A4-awaitingci

#5043 Fix: CI failing for some CLI tests
  bin/node/cli/tests/check_block_works.rs
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/import_export_and_revert_work.rs
  bin/node/cli/tests/inspect_works.rs
  bin/node/cli/tests/purge_chain_works.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/revert_cmd.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/mod.rs
  client/cli/src/params/pruning_params.rs
Labels: A8-looksgood, B0-silent, F4-tests 🎯

#5046 aura: remove unused tx pool
  bin/node-template/node/src/service.rs
  client/consensus/aura/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, B2-breaksapi, M4-core

#5021 Extend rust nightly detection in `wasm-builder`
  utils/wasm-builder/README.md
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A8-looksgood, B0-silent

#5033 Add steps setting to benchmarking CLI
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A8-looksgood, B0-silent

#5025 Remove indices from node-template
  Cargo.lock
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/indices/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#5051 Fix documentation for "BlockBuilder::push_trusted"
  client/block-builder/src/lib.rs
Labels: A2-insubstantial, B0-silent, F5-documentation 📄

#5054 do not check unleash on every PR, only master and tags
  .gitlab-ci.yml
  .maintain/gitlab/check_signed.sh
  .maintain/gitlab/lib.sh
  .maintain/gitlab/publish_draft_release.sh
Labels: A2-insubstantial, A4-awaitingci, M1-ci

#5052 Sync: validate block responses for required data
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A8-looksgood, B0-silent, F0-consensus ☠️

#5031 Make these chainspecs fields private
  client/chain-spec/src/chain_spec.rs
Labels: A2-insubstantial, A8-looksgood, B0-silent

#5059 Fix dockerfile
  .maintain/Dockerfile
Labels: A8-looksgood, B0-silent

#5053 Adds documentation for `wipe` and `commit`
  primitives/externalities/src/lib.rs
  primitives/state-machine/src/basic.rs
Labels: A2-insubstantial, A8-looksgood, B0-silent

#4992 Fix the issue with `trybuild`'s `ui` tests
  Cargo.lock
  primitives/runtime-interface/Cargo.toml
Labels: A3-needsresolving, B9-blocker, F2-bug 🐜, M1-ci

#5062 Activate publishing of draft releases...
  .maintain/gitlab/lib.sh
  .maintain/gitlab/publish_draft_release.sh
Labels: A2-insubstantial, A8-looksgood, M1-ci

#5041 Fix/div by zero
  bin/node/runtime/src/lib.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/tests.rs
Labels: A8-looksgood, B0-silent, B2-breaksapi

#5065 Fix revalidation not revalidating multiple times
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A8-looksgood, B0-silent

#5030 removes use of sc_client::Client from sc_finality_grandpa
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/api/src/backend.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/light_import.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/src/client.rs
  client/src/lib.rs
Labels: A0-pleasereview, A5-grumble, A7-looksgoodcantmerge

#5038 Remove deprecated host functions
  client/executor/src/deprecated_host_interface.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_utils.rs
  primitives/io/src/lib.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
  primitives/wasm-interface/src/lib.rs
Labels: A8-looksgood, B0-silent
