Repository paritytech/substrate, pull requests merged in 2020-12, with the labels that each got.

#7641 Fix cargo clippy warning in peerset.
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
  client/peerset/tests/fuzz.rs
  primitives/utils/src/mpsc.rs
  primitives/utils/src/status_sinks.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7635 remove unused deps pulled by parity-util-mem
  Cargo.lock
  Cargo.toml
  frame/support/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7626 minor fix and improvements on localkeystore
  client/keystore/src/local.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7649 Remove a stray error file.
  client/transaction-pool/graph/src/error.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7616 fork-tree: fix tree rebalancing
  client/finality-grandpa/src/authorities.rs
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7656 Use unreleased trybuild to fix CI
  Cargo.lock
  frame/support/test/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7655 Show reputation changes when dropping peer
  client/peerset/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7646 Remove sc_network::NetworkService::register_notifications_protocol and partially refactor Grandpa tests
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/README.md
  client/network/src/lib.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7658 *: Update to libp2p v0.31.2
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7659 Refactor `StorageInstance` trait to be usable more easily
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7654 Update ss58 registry for Phala network
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7378 Changed map to filter map so that Phragmen ignores empty voters
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7474 RPC to allow setting the log filter
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/shared_params.rs
  client/executor/Cargo.toml
  client/rpc-api/src/system/mod.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  client/tracing/src/logging.rs
  primitives/tracing/Cargo.toml
  utils/browser/src/lib.rs
Labels: B5-clientnoteworthy, C1-low

#7653 Use block requests to check if block responses are correct
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/extra_requests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7666 Don't panic on a sink error
  client/rpc/src/author/mod.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7152 Features needed for reserve-backed stablecoins
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/assets/Cargo.toml
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/assets/src/weights.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7652 Add Standard Error to Weight Template
  .maintain/frame-weight-template.hbs
  utils/frame/benchmarking-cli/src/template.hbs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7672 Adds support for tuples in runtime-interface
  Cargo.lock
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7677 Fix two potential connection poisonings
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7680 Fix #7629
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7627 Bump regex dep
  primitives/core/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7683 Make sure the companion CI test fails on any error
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview, B0-silent, C1-low

#7682 Implement more convertion trait on `NumberOrHex`
  primitives/rpc/src/number.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7694 client: remove duplicate implementation of block_status
  client/service/src/client/client.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7697 Pin md link checker's version
  .github/allowed-actions.js
  .github/workflows/md-link-check.yml
  .github/workflows/mlc_config.json
Labels: A0-pleasereview, A3-needsresolving, B0-silent, C1-low

#7519 Remove waterfall CI trigger
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7688 add an upgrade_keys method for pallet-session
  frame/session/src/lib.rs
  frame/session/src/mock.rs
  frame/session/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7671 Allow capping the amount of work performed when deleting a child trie
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/light/src/backend.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/support/src/storage/child.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/read_only.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/tasks/src/async_externalities.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, B5-clientnoteworthy, C1-low, D2-breaksapi, D6-newhostfunctions

#7698 Fix panic in case of a missing model
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7676 Pallet-name-service tests
  frame/name-service/src/tests.rs
Labels: D2-breaksapi

#7628 Expand remote keystore interface to allow for hybrid mode
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  client/cli/src/commands/insert.rs
  client/cli/src/config.rs
  client/cli/src/params/keystore_params.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  primitives/application-crypto/test/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/vrf.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low

#7695 fork-tree: expose silent failures of is_descendent_of
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7312 Merkle Mountain Range pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  frame/merkle-mountain-range/Cargo.toml
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/merkle-mountain-range/src/default_weights.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/mmr.rs
  frame/merkle-mountain-range/src/mmr/mod.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/mmr/utils.rs
  frame/merkle-mountain-range/src/mock.rs
  frame/merkle-mountain-range/src/primitives.rs
  frame/merkle-mountain-range/src/tests.rs
  primitives/core/src/offchain/testing.rs
  primitives/runtime/src/offchain/storage.rs
  primitives/runtime/src/offchain/storage_lock.rs
Labels: A0-pleasereview, B3-apinoteworthy, C3-medium, D2-breaksapi

#7703 frame/staking/README: Fix broken link
  frame/staking/README.md
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7696 *: Update to libp2p v0.32.0
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7708 *: Update to libp2p v0.32.2
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7547 kilt&polimec ss58 prefix
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7710 Fix docs
  bin/node/browser-testing/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/authority-discovery/src/service.rs
  client/authority-discovery/src/worker.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/commands/utils.rs
  client/cli/src/config.rs
  client/finality-grandpa/src/lib.rs
  client/network/src/gossip.rs
  client/service/src/client/mod.rs
  client/telemetry/src/async_record.rs
  frame/contracts/src/schedule.rs
  frame/example/src/lib.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/proxy/src/lib.rs
  frame/session/src/historical/onchain.rs
  frame/staking/src/lib.rs
  frame/staking/src/slashing.rs
  frame/support/src/traits.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/lib.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/balancing.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/reduce.rs
  test-utils/runtime/src/lib.rs
  utils/prometheus/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7709 Update md link checker
  .github/allowed-actions.js
  .github/workflows/md-link-check.yml
  .github/workflows/mlc_config.json
Labels: A0-pleasereview, A3-needsresolving, B0-silent, C1-low

#7701 Fix PerThing::from_percent.
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7669 Support Multiple Instances with Benchmarks
  Cargo.lock
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7531 Add keccak-512 to host functions.
  primitives/core/src/hashing.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D6-newhostfunctions

#7721 Allow runtime_debug! where sp_io is not there
  frame/support/src/debug.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7716 Fix polkadot benchmarks for remark.
  frame/system/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7718 Prevent dust in staking by disallowing cheap bond_extra
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7726 Default block announce validation should reject additional data
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  primitives/consensus/common/src/block_validation.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7728 Fix wrong order of values in log line
  client/network/src/protocol/sync.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7732 Fix polkadot companion test
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#7725 remove duplicate accounts in chain-spec.
  bin/node/cli/src/chain_spec.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7661 Participating in Council Governance is Free for First Time Voters and Successful Closing
  frame/collective/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7727 Leave some header related info for inspection
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7741 CI: buildah to build images
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7745 optimize arithmetic cargo path
  primitives/arithmetic/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7729 optimize runtime-interface cargo path
  primitives/runtime-interface/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7751 delete primitives in Cargo in primitives
  primitives/api/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/application-crypto/Cargo.toml
  primitives/consensus/common/Cargo.toml
  primitives/io/Cargo.toml
  primitives/npos-elections/Cargo.toml
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7752 delete client in Cargo in client
  client/basic-authorship/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/network/test/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7749 prevent too many genesis council members
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7733 Update common block in sync after importing blocks of a peer, please read UPDATE
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  primitives/consensus/common/src/import_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7761 Remove unnecessary parameter from sync
  client/network/src/protocol/sync.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7743 Improve `InvalidTransaction::AncientBirthBlock` doc comment
  primitives/runtime/src/transaction_validity.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7764 Switch back to the crates.io release of trybuild
  Cargo.lock
  frame/support/test/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7747 contracts: No longer put delta keys back after a failed restoration
  frame/contracts/src/rent.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7722 Fix UI Tests
  .maintain/gitlab/check_polkadot_companion_build.sh
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  frame/support/test/tests/derive_no_bound_ui/clone.stderr
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi, Q5-substantial

#7767 update substrate to sc in docs
  docs/Structure.adoc
Labels: A2-insubstantial, B0-silent, C1-low

#7719 Allow Staking tests to run with session length other than 1
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7754 optimize biguint div closure
  primitives/arithmetic/src/biguint.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7714 Make it possible to calculate the storage root as often as you want
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/contracts/src/tests.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/merkle-mountain-range/src/tests.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7773 Typo fix: eror => error
  primitives/database/src/kvdb.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7774 Adds `try_get` for `StorageMap` and `StorageDoubleMap`
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7776 Add account prefix for Valiu
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7769 Feat support weight test
  frame/support/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7789 add a `current_epoch` to BabeApi
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  primitives/consensus/babe/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#7784 Fix testing for number of slashing spans.
  frame/staking/src/tests.rs
Labels: B0-silent, C1-low, D2-breaksapi

#7793 add a slot-duration getter to babe config
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7775 Fix base-path handling in `key insert`
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  bin/utils/subkey/src/lib.rs
  client/cli/src/commands/insert.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/commands/key.rs
  client/cli/src/commands/mod.rs
  client/cli/src/config.rs
  client/cli/src/error.rs
  client/cli/src/lib.rs
  client/cli/src/params/keystore_params.rs
  client/keystore/src/local.rs
  client/service/src/config.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7802 Lazily evaluate error string
  bin/node-template/node/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7762 contracts: Change `define_env!` to expect a `Result<T, DispatchError>` for every function
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7807 Hex Balance deserialize for contracts_call RPC
  frame/contracts/rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7803 Don't allow Self Proxies
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7753 Allow council to slash treasury tip
  frame/bounties/src/benchmarking.rs
  frame/tips/README.md
  frame/tips/src/benchmarking.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
  frame/tips/src/weights.rs
  frame/treasury/src/benchmarking.rs
Labels: B7-runtimenoteworthy, C1-low, D2-breaksapi

#7795 Add CLI argument to disable log color output
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/params/shared_params.rs
  client/rpc/src/system/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7809 Use Path instead of Ident for Benchmarking `add_benchmark!`
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7808 Add proper `commit_all` to `TestExternalities`
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/testing.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low
