Repository paritytech/substrate, pull requests merged in 2020-09, with the labels that each got.

#6995 fix pallet-evm features
  frame/evm/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6948 Move subcommands from sc-cli to nodes
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  client/cli/src/commands/mod.rs
  client/cli/src/runner.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low

#6998 ci: deploy alerting rules: fix run on changes
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#6964 *: Update to Prometheus v0.10.0
  Cargo.lock
  primitives/utils/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6979 Ensure that handshake is sent back even in case of back-pressure
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#6788 frame/authority-discovery: Have authorities() return both current and next
  client/authority-discovery/src/worker.rs
  frame/authority-discovery/src/lib.rs
  primitives/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6975 Stop sending messages on legacy substream altogether
  client/finality-grandpa/src/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
Labels: A1-needsburnin, A1-onice, B0-silent, C1-low

#7010 manual seal is now consensus agnostic
  Cargo.lock
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/consensus.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/error.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/rpc.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6970 grandpa: report metrics on prevotes and precommits cast
  client/finality-grandpa/src/environment.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7021 Fix compact npos solution edge count calculation
  primitives/npos-elections/compact/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6986 Refactor & detach network metrics.
  client/informant/src/lib.rs
  client/network/src/network_state.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7014 Node template complete import pipeline
  bin/node-template/node/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7018 client/authority-discovery: Throttle DHT requests
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A1-needsburnin, B0-silent, C1-low

#6990 Update Nicks docs to clarify that it is not production-ready
  frame/nicks/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6962 Ignore wasm_gc for debug build.
  docs/README.adoc
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7043 Make `--file` optional for `generate-node-key`
  bin/utils/subkey/src/lib.rs
  client/cli/src/commands/generate_node_key.rs
  client/cli/src/commands/key.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7042 Downgrade wabt = 0.9.1
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/testing/Cargo.toml
  client/executor/Cargo.toml
  primitives/sandbox/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7029 Add metadata shadows to multisig pallet
  frame/multisig/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7026 Fix broken link to democracy pallet.
  frame/sudo/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7047 Revert "Fix broken link to democracy pallet."
  frame/sudo/README.md
Labels: A6-revertrevert, B0-silent, C1-low

#7038 Update the service tasks Grafana dashboard
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A2-insubstantial, B5-clientnoteworthy, C1-low

#6981 babe, grandpa: waive fees on valid equivocation report
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi, D9-needsaudit👮

#7049 Clarify Nicks docs
  frame/nicks/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7051 Improves EVM gas price check
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7050 Change wabt to wat
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/basic.rs
  bin/node/testing/Cargo.toml
  client/executor/Cargo.toml
  client/executor/src/integration_tests/sandbox.rs
  primitives/sandbox/Cargo.toml
  primitives/sandbox/with_std.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6714 Add Dock network id for address generation
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7034 Partial fix for transaction priority
  frame/support/src/weights.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/extensions/check_weight.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7056 What happens if we remove wat?
  Cargo.lock
  bin/node/testing/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6961 Make SlashingSpans Public
  frame/staking/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7059 client/authority-discovery/src/service: Improve docs
  client/authority-discovery/src/service.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#7063 [CI] Increase poll interval in the 'Check Polkadot Companion and Label' workflow
  .github/workflows/polkadot-companion-labels.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7027 Remove unused code in off-chain worker example
  frame/example-offchain-worker/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7061 Disambiguate `BlockNumber` type in `decl_module`
  frame/support/src/dispatch.rs
  frame/support/test/src/lib.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/decl_storage_ui/config_duplicate.rs
  frame/support/test/tests/decl_storage_ui/config_get_duplicate.rs
  frame/support/test/tests/decl_storage_ui/get_duplicate.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/support/test/tests/reserved_keyword/on_initialize.rs
  frame/support/test/tests/storage_transaction.rs
  frame/support/test/tests/system.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7068 Implement `FromStr` for `Ss58AddressFormat`
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6996 Set reserved nodes with offchain worker.
  Cargo.lock
  Cargo.toml
  client/network/src/service.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/peerset/src/lib.rs
  client/service/src/builder.rs
  frame/im-online/src/benchmarking.rs
  frame/im-online/src/tests.rs
  frame/node-authorization/Cargo.toml
  frame/node-authorization/src/lib.rs
  primitives/core/src/lib.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/offchain/testing.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7080 Rename `TRIGGER_WASM_BUILD` to `FORCE_WASM_BUILD`
  docs/README.adoc
  utils/wasm-builder-runner/src/lib.rs
  utils/wasm-builder/README.md
  utils/wasm-builder/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7062 Make decoding of `compact<perthing>` saturating instead of invalid
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B2-breaksapi, B3-apinoteworthy, C1-low, D2-breaksapi

#6934 state_machine no_std witness externalities
  Cargo.lock
  primitives/externalities/Cargo.toml
  primitives/externalities/src/extensions.rs
  primitives/externalities/src/lib.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/changes_trie/mod.rs
  primitives/state-machine/src/error.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/changeset.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/stats.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7052 Support hex encoded secret key for `--node-key`
  client/cli/src/params/node_key_params.rs
  client/network/src/config.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6999 Add a `build-sync-spec` subcommand and remove the CHT roots from the light sync state.
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  client/chain-spec/src/chain_spec.rs
  client/cli/src/commands/build_sync_spec_cmd.rs
  client/cli/src/commands/mod.rs
  client/service/src/chain_ops/build_sync_spec.rs
  client/service/src/chain_ops/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7086 Fix build sync spec
  client/cli/src/commands/build_sync_spec_cmd.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#5923 Fail docs on warnings
  .gitlab-ci.yml
  client/cli/src/arg_enums.rs
  client/cli/src/config.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/subdb.rs
  client/db/src/utils.rs
  client/network/src/lib.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/balances/src/lib.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/evm/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/src/lib.rs
  frame/proxy/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/dispatch.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A1-onice, B0-silent, C1-low, D2-breaksapi

#7084 Fix `storage::read`
  primitives/io/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#7091 Add fuzzer for the compact custom codec implementation from PR #6720
  Cargo.lock
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/src/compact.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#7058 add instantiable support for treasury pallet
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7039 grandpa-rpc don't share subscription manager, only executor
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6984 pallet-collective: allow customized default vote
  bin/node/runtime/src/lib.rs
  frame/collective/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7077 Upgrade to libp2p-0.28.
  Cargo.lock
  Cargo.toml
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/block_requests.rs
  client/network/src/discovery.rs
  client/network/src/finality_requests.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C3-medium

#7073 pow: support uniform tie breaking in fork choice
  client/consensus/pow/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7075 Allow remotes to not open a legacy substream
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/message.rs
  client/rpc-api/src/system/helpers.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#7102 Use diener for Polkadot companion prs
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#7106 Update ui tests for rust 1.46.0
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
Labels: A2-insubstantial, B0-silent, C1-low

#7104 client/network: Expose number of entries per Kademlia bucket
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7105 Improve error output of wasm-builder when wasm ins't installed
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/prerequisites.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6982 Add ss58 address for Dark network
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low

#5470 Frame-support storage: make iterations and translate consistent
  frame/support/src/dispatch.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi, D5-nicetohaveaudit⚠️

#7110 fix js dependancy alert, bumping bl version
  .maintain/chaostest/package-lock.json
Labels: A0-pleasereview, B0-silent, C1-low

#7112 Make `transactional` attribute less scope dependent
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/transactional.rs
  frame/support/procedural/tools/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7020 Add SS58 Registry
  ss58-registry.json
Labels: A0-pleasereview, B0-silent, C1-low

#7007 Move Staking Weights to T::WeightInfo
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/default_weights.rs
  frame/staking/src/lib.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C3-medium, D2-breaksapi

#7118 Send import notification always for re-orgs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7103 WeightInfo for Vesting Pallet
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_vesting.rs
  frame/atomic-swap/src/tests.rs
  frame/babe/src/mock.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/evm/src/tests.rs
  frame/example/src/lib.rs
  frame/executive/src/lib.rs
  frame/generic-asset/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/identity/src/lib.rs
  frame/indices/src/mock.rs
  frame/multisig/src/tests.rs
  frame/nicks/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/proxy/src/tests.rs
  frame/recovery/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/mock.rs
  frame/support/src/traits.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
  frame/utility/src/tests.rs
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/default_weights.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7122 Add benchmarking pipeline to node-template
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6825 Use tracing-based subscriber logging
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/main.rs
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc-client/src/main.rs
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker/tests.rs
  client/cli/Cargo.toml
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/Cargo.toml
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/executor/Cargo.toml
  client/executor/src/integration_tests/mod.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/tests.rs
  client/informant/Cargo.toml
  client/light/Cargo.toml
  client/network/Cargo.toml
  client/network/src/light_client_handler.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/test/Cargo.toml
  client/network/test/src/sync.rs
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/test/Cargo.toml
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  client/state-db/Cargo.toml
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/tests.rs
  frame/example/src/lib.rs
  frame/scored-pool/src/tests.rs
  frame/staking/Cargo.toml
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/sudo/src/tests.rs
  frame/support/src/storage/mod.rs
  frame/support/test/tests/decl_storage.rs
  primitives/consensus/slots/Cargo.toml
  primitives/tracing/Cargo.toml
  primitives/tracing/src/lib.rs
  utils/frame/rpc/system/Cargo.toml
  utils/frame/rpc/system/src/lib.rs
Labels: A1-onice, A3-needsresolving, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7126 Typo in error text
  primitives/runtime/src/transaction_validity.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7131 fix the new staking weight in substrate-node
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_staking.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7132 Remove warning about deprecated PeerIds
  client/network/src/config.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7130 Fix db initialization for light client
  client/db/src/parity_db.rs
  client/db/src/utils.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7107 WeightInfo for Identity Pallet
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_identity.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/default_weights.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7135 Make sure we update the `Cargo.lock` in the polkadot companion
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#6916 Tracing for wasm with bridging to native
  .gitlab-ci.yml
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/runtime/Cargo.toml
  client/executor/Cargo.toml
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/build.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/service/Cargo.toml
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  client/transaction-pool/src/api.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/support/src/debug.rs
  frame/support/src/dispatch.rs
  frame/support/test/Cargo.toml
  primitives/arithmetic/src/biguint.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/npos-elections/src/reduce.rs
  primitives/runtime-interface/proc-macro/src/lib.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/mod.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/std/src/lib.rs
  primitives/tracing/Cargo.toml
  primitives/tracing/src/lib.rs
  primitives/tracing/src/proxy.rs
  primitives/tracing/src/types.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7137 WeightInfo for Pallet Indices
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_indices.rs
  frame/indices/src/benchmarking.rs
  frame/indices/src/default_weights.rs
  frame/indices/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi, D5-nicetohaveaudit⚠️

#7060 pow: replace the thread-base mining loop with a future-based mining worker
  Cargo.lock
  client/consensus/pow/Cargo.toml
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#5715 Bounties
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_treasury.rs
  frame/treasury/Cargo.toml
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/default_weights.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A3-inprogress, B7-runtimenoteworthy, C1-low, D1-audited👍, D2-breaksapi

#7142 Update SS58 configuration for Bifrost
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7088 Prometheus metrics for RPC calls
  Cargo.lock
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc-servers/src/middleware.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7138 WeightInfo for Scheduler
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_scheduler.rs
  frame/democracy/src/tests.rs
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/default_weights.rs
  frame/scheduler/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6215 grandpa-rpc: use FinalityProofProvider to check finality for rpc
  Cargo.lock
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/rpc/src/finality.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7160 Rename subkey's `inspect-key` to `inspect`
  bin/utils/subkey/src/lib.rs
Labels: A2-insubstantial, B5-clientnoteworthy, C1-low

#7157 Bump jsonrpc-* dependencies to v15
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/browser-testing/Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-api/src/chain/mod.rs
  client/rpc-api/src/state/mod.rs
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C3-medium, D2-breaksapi

#7136 WeightInfo for Session Pallet
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_session.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
  frame/session/benchmarking/src/lib.rs
  frame/session/src/default_weights.rs
  frame/session/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7156 Remove Generic Asset Pallet
  Cargo.lock
  Cargo.toml
  frame/generic-asset/Cargo.toml
  frame/generic-asset/README.md
  frame/generic-asset/src/lib.rs
  frame/generic-asset/src/mock.rs
  frame/generic-asset/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7158 Add MathChain SS58 address type
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7162 Link todo to issue
  frame/scheduler/src/benchmarking.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7155 Add `WeightInfo` to Babe and Grandpa Pallet
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/default_weights.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/default_weights.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7154 WeightInfo for Multisig Pallet
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_multisig.rs
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/default_weights.rs
  frame/multisig/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7048 evm: Add executor logs to execute_evm response
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7121 Docs for Frame Benchmarking
  Cargo.lock
  Cargo.toml
  frame/benchmark/Cargo.toml
  frame/benchmark/README.md
  frame/benchmark/src/benchmarking.rs
  frame/benchmark/src/lib.rs
  frame/benchmarking/README.md
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7167 Do not panic while panicking
  primitives/runtime/src/lib.rs
  primitives/std/with_std.rs
  primitives/std/without_std.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7165 client/network/src/transport: Use libp2p upgrade builder
  client/network/src/transport.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7174 Fix warning in full-crypto build
  primitives/core/src/sr25519.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7161 Update elections-phragmen weight to WeightInfo
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_elections_phragmen.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/default_weights.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#6969 Allow pallet in construct_runtime to have fixed index
  Cargo.lock
  frame/metadata/Cargo.toml
  frame/metadata/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/event.rs
  frame/support/src/metadata.rs
  frame/support/src/origin.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/construct_runtime_ui/conflicting_index.rs
  frame/support/test/tests/construct_runtime_ui/conflicting_index.stderr
  frame/support/test/tests/construct_runtime_ui/conflicting_index_2.rs
  frame/support/test/tests/construct_runtime_ui/conflicting_index_2.stderr
  frame/support/test/tests/construct_runtime_ui/more_than_256_modules.rs
  frame/support/test/tests/construct_runtime_ui/more_than_256_modules.stderr
  frame/support/test/tests/system.rs
Labels: A8-mergeoncegreen, B2-breaksapi, B3-apinoteworthy, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7164 u32 Refcounts, plus migration
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  frame/executive/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D1-runtime-migration, D2-breaksapi, D9-needsaudit👮

#6685 PhragMMS election.
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/consensus/babe/src/authorship.rs
  frame/elections-phragmen/src/lib.rs
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/biguint.rs
  primitives/arithmetic/fuzzer/src/multiply_by_rational.rs
  primitives/arithmetic/fuzzer/src/normalize.rs
  primitives/arithmetic/src/biguint.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/rational.rs
  primitives/npos-elections/benches/phragmen.rs
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/src/balance_solution.rs
  primitives/npos-elections/fuzzer/src/common.rs
  primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
  primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
  primitives/npos-elections/fuzzer/src/reduce.rs
  primitives/npos-elections/src/balancing.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/tests.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D1-audited👍, D2-breaksapi

#7192 Fix vanity command by taking the network into account
  client/cli/src/commands/utils.rs
  client/cli/src/commands/vanity.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7180 Update networking Prometheus dashboard
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
Labels: A2-insubstantial, B0-silent, C1-low

#7199 fix typo: bitfrost -> bifrost
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7201 Add doc for auto-generated code
  utils/wasm-builder-runner/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7204 Ensure that all new packages released with unleash have paritytech:core-devs as owners
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7207 Add more metrics to the import queue
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7111 Introduce `cancel_proposal` to rid us of those pesky proposals
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/pallet_democracy.rs
  frame/benchmarking/src/utils.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/default_weight.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/external_proposing.rs
  frame/democracy/src/tests/public_proposals.rs
  frame/staking/src/benchmarking.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D0-transaction-version, D2-breaksapi, D5-nicetohaveaudit⚠️

#7205 Move proxies migration
  Cargo.lock
  frame/proxy/Cargo.toml
  frame/proxy/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D1-runtime-migration

#7216 Make private member of ecdsa `Public` and `Signature` tuple structs as
  primitives/core/src/ecdsa.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7227 Tidy some CLI stuff.
  bin/node/cli/src/browser.rs
  client/cli/src/runner.rs
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7211 client/network: Stop sending noise legacy handshake
  client/network/src/transport.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7230 No longer display the legacy representation of the PeerId
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7195 GeekCash reserve SS58 address id 19
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7234 Fix Treasury Benchmark Setup
  frame/treasury/src/benchmarking.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7232 .maintain/monitoring: Normalize alerting rules
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#7238 Fix compilation with environmental on latest nightly
  Cargo.lock
  primitives/externalities/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7239 client: remove stale file
  client/cli/src/logger.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7241 client: fix log filters
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7229 WIP: remove deprecated only/except clauses
  .gitlab-ci.yml
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#7237 Improve Payout Benchmarks in Staking
  bin/node/runtime/src/lib.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7245 pallet-evm: fix backend timestamp
  frame/evm/src/backend.rs
Labels: A0-pleasereview, B0-silent, C1-low
