Repository paritytech/substrate, pull requests merged in 2020-08, with the labels that each got.

#6784 client/network: Expose DHT query duration to Prometheus
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6792 Fix transaction payment runtime api
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#6794 client/network: Fix wrong metric help text
  client/network/src/service.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6773 seal: Fix and improve error reporting
  frame/contracts/fixtures/call_return_code.wat
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/destroy_and_transfer.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/fixtures/instantiate_return_code.wat
  frame/contracts/fixtures/ok_trap_revert.wat
  frame/contracts/fixtures/self_destructing_constructor.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/fixtures/transfer_return_code.wat
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6785 Improve Benchmark Writer: Remove Unused Components, Remove Multiply by Zero, Files Split by Pallet
  Cargo.lock
  Process.json
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6782 Add integrity test for slash defer duration
  frame/staking/src/lib.rs
Labels: A1-onice, B0-silent, C1-low, D2-breaksapi

#6799 Convert rogue spaces to tabs
  bin/node/bench/src/core.rs
  bin/node/bench/src/txpool.rs
  bin/node/browser-testing/src/lib.rs
  client/proposer-metrics/src/lib.rs
  client/service/test/src/client/light.rs
  frame/contracts/src/benchmarking.rs
  frame/staking/src/tests.rs
  primitives/consensus/common/src/metrics.rs
  primitives/core/src/sr25519.rs
  primitives/runtime/src/offchain/storage_lock.rs
  utils/fork-tree/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6747 Add details to legacy requests
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6800 Add ss58 address for Subsocial network
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6704 Add mutate_exists to StorageDoubleMap.
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6783 pallet-democracy use of weightinfo
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_democracy.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/default_weight.rs
  frame/democracy/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6807 Use DNS hostnames for flaming fir bootnodes
  bin/node/cli/res/flaming-fir.json
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D0-patchthis

#6820 Fix warning being printed by authority-discovery
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6813 Better default balances weights
  frame/balances/src/default_weight.rs
  frame/balances/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6812 Remove generation of instance trait by decl_storage.
  frame/support/procedural/src/storage/genesis_config/mod.rs
  frame/support/procedural/src/storage/instance_trait.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/traits.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/instance.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6793 Successful `note_imminent_preimage` is free
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/preimage.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi, D9-needsaudit👮

#6822 service: remove collection of system/process metrics
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6826 Fix legacy substream fallback not working
  client/network/src/protocol/generic_proto/handler/group.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6823 grandpa: never overwrite current rounds voter state
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6808 Add RPC Builder to Substrate Node Template
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/lib.rs
  bin/node-template/node/src/main.rs
  bin/node-template/node/src/rpc.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A5-grumble, B0-silent, C1-low

#6833 Delay network startup to after complete initialization
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6829 De-alias frame_system in node template runtime
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6771 Allow task manager to have children
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  docs/CHANGELOG.md
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6836 De-alias pallets in node template runtime
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6828 grandpa: fix enacting forced changes with no delay
  client/finality-grandpa/src/authorities.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6838 Renamed add_children to add_child since it adds only one child
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6824 Revalidate transactions only on latest best block
  bin/node/cli/src/service.rs
  client/api/src/client.rs
  client/basic-authorship/src/basic_authorship.rs
  client/consensus/manual-seal/src/lib.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
  primitives/transaction-pool/src/pool.rs
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6850 Fix `wait_for_blocks` counting blocks that didn't go through consensus
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6837 pallet-evm: move gas price check to execute_evm
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6861 Update pinned wasm-bindgen dependency
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/browser-demo/README.md
  bin/node/cli/browser-demo/build.sh
Labels: A0-pleasereview, B0-silent, C1-low

#5732 Add Subscription RPC for Grandpa Finality
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/notification.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/notification.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/rpc-api/src/lib.rs
  client/rpc-api/src/metadata.rs
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/testing.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6864 Remove minimum_validator_count stale const
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6798 seal: Change prefix and module name from "ext_" to "seal_" for contract callable functions
  Cargo.lock
  bin/node/executor/tests/basic.rs
  frame/contracts/COMPLEXITY.md
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/call_return_code.wat
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/check_default_rent_allowance.wat
  frame/contracts/fixtures/crypto_hashes.wat
  frame/contracts/fixtures/destroy_and_transfer.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/fixtures/instantiate_return_code.wat
  frame/contracts/fixtures/ok_trap_revert.wat
  frame/contracts/fixtures/restoration.wat
  frame/contracts/fixtures/return_from_start_fn.wat
  frame/contracts/fixtures/return_with_data.wat
  frame/contracts/fixtures/self_destruct.wat
  frame/contracts/fixtures/self_destructing_constructor.wat
  frame/contracts/fixtures/set_empty_storage.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/fixtures/storage_size.wat
  frame/contracts/fixtures/transfer_return_code.wat
  frame/contracts/src/benchmarking.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#6867 grandpa: log errors and grandpa unexpected conclusion
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6720 Custom Codec Implenetation for NPoS Election
  frame/staking/src/lib.rs
  primitives/arithmetic/fuzzer/src/per_thing_rational.rs
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/codec.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/compact/src/staked.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6847 state_getSize RPC for storage maps
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/state/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6398 Block packet size limit
  client/network/src/block_requests.rs
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#6759 Move to upstream wasmtime, refactor globals snapshot
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, A1-needsburnin, B5-clientnoteworthy, C3-medium

#6872 grandpa: change some logging from trace to debug
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/import.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#6873 Fix wrong staking doc about transaction payment.
  frame/staking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6878 docs: convert code of conduct to markdown
  docs/CODE_OF_CONDUCT.md
Labels: A2-insubstantial, B0-silent, C1-low

#6758 Add Phala Network SS58 address type
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6879 docs: fix references to code of conduct document
  README.md
  docs/README.adoc
Labels: A2-insubstantial, B0-silent, C1-low

#6876 Fuse the import queue receiver
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/import_queue/buffered_link.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6763 Implement 'transactional' annotation for runtime functions.
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/transactional.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/test/tests/storage_transaction.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#6779 Add a warning if users pass --sentry or --sentry-nodes
  client/network/src/service.rs
Labels: B0-silent, C1-low

#6786 pallet-evm: fix wrong logic in mutate_account_basic
  frame/evm/src/lib.rs
  frame/evm/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6672 Implement tracing::Event handling & parent_id for spans and events
  Cargo.lock
  bin/node/cli/Cargo.toml
  client/cli/src/lib.rs
  client/executor/Cargo.toml
  client/executor/src/integration_tests/mod.rs
  client/service/Cargo.toml
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/tracing/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6651 Add async test helper to timeout and provide a task_executor automatically
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  test-utils/Cargo.toml
  test-utils/derive/Cargo.toml
  test-utils/derive/src/lib.rs
  test-utils/src/lib.rs
  test-utils/test-crate/Cargo.toml
  test-utils/test-crate/src/main.rs
  test-utils/tests/basic.rs
  test-utils/tests/ui.rs
  test-utils/tests/ui/missing-func-parameter.rs
  test-utils/tests/ui/missing-func-parameter.stderr
  test-utils/tests/ui/too-many-func-parameters.rs
  test-utils/tests/ui/too-many-func-parameters.stderr
Labels: A0-pleasereview, A1-onice, B0-silent, C1-low

#6760 client/authority-discovery: Introduce AuthorityDiscoveryService
  bin/node/cli/src/service.rs
  client/authority-discovery/build.rs
  client/authority-discovery/src/addr_cache.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/service.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/authority-discovery/src/worker/schema/dht.proto
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6883 Make `HexDisplay` useable in `no_std`
  primitives/core/src/hexdisplay.rs
  primitives/core/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6858 pallet-evm: avoid double fee payment
  frame/evm/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6875 add runtime migrations to release notes/changelog
  .maintain/gitlab/generate_changelog.sh
Labels: A0-pleasereview, B0-silent, C1-low

#6881 network: don't log re-discovered addresses
  client/network/src/discovery.rs
  client/network/src/protocol.rs
  client/network/src/protocol/util.rs
  client/network/src/utils.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6886 More renaming to move away from phragmen.
  Cargo.lock
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/codec.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6887 Crystalin add evm log
  frame/evm/src/backend.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6870 Update to libp2p-0.23.
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/informant/src/display.rs
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/lib.rs
  client/network/src/network_state.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: B0-silent, C3-medium

#6897 client/authority-discovery: Revert query interval change
  client/authority-discovery/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6846 RpcHandlers Refactorings
  Cargo.lock
  bin/node/cli/src/service.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/task_manager/mod.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D0-patchthis, D2-breaksapi

#6899 Don't take the origin in `can_set_code`
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6803 Add a DirectedGossip struct
  client/network/Cargo.toml
  client/network/src/gossip.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6862 babe, aura, pow: only call check_inherents if authoring version is compatible
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/pow/src/lib.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6900 pow: add access to pre-digest for algorithm verifiers
  client/consensus/pow/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D2-breaksapi

#6906 Derive Clone for AlwaysCanAuthor, NeverCanAuthor, CanAuthorWithNativeVersion
  primitives/consensus/common/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6895 Add support for sourced metrics.
  client/network/src/service.rs
  utils/prometheus/src/lib.rs
  utils/prometheus/src/sourced.rs
Labels: B0-silent, C1-low

#6907 Import `IterableStorage*` traits by `decl_storage!`
  frame/support/procedural/src/storage/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6903 Distribute the network future polling time more evenly
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#6857 Combine default values used at initialization in a trait
  client/cli/src/commands/mod.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6915 babe: handle error when checking/reporting equivocations
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6815 Dynamic Benchmarking DB Whitelist
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/db/src/bench.rs
  frame/balances/src/benchmarking.rs
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/utils.rs
  frame/collective/src/benchmarking.rs
  frame/indices/src/benchmarking.rs
  frame/proxy/src/benchmarking.rs
  frame/staking/src/benchmarking.rs
  frame/system/benchmarking/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/utility/src/benchmarking.rs
  frame/vesting/src/benchmarking.rs
  primitives/externalities/src/lib.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/impls.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/read_only.rs
  primitives/storage/Cargo.toml
  primitives/storage/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#6909 Clean shutdown for subcommands
  client/cli/src/runner.rs
Labels: A3-inprogress, B0-silent, C1-low

#6709 Remove the legacy requests-answering protocols
  client/network/src/protocol.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6891 *: Update to next libp2p version 0.24.0
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B3-apinoteworthy, B5-clientnoteworthy, C1-low

#6821 Wait for all notifications protocols to be open before reporting opening
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/legacy.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6941 Make Ss58AddressFormat display less expressive
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6933 client/authority-discovery: Append PeerId to Multiaddr at most once
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6943 Expose pallet-indices Deposit to metadata
  frame/indices/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6894 Add a `LightSyncState` field to the chain spec
  Cargo.lock
  client/api/src/in_mem.rs
  client/api/src/light.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/db/src/light.rs
  client/service/src/chain_ops/build_spec.rs
  client/service/src/chain_ops/mod.rs
  client/service/test/src/client/light.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#6944 Dynamically generate CHT roots on a full client
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/api/src/light.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/light/src/blockchain.rs
  client/service/src/chain_ops/build_spec.rs
  client/service/test/src/client/light.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6929 Enable verification logic when executing benchmarks
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/utils.rs
  frame/staking/src/benchmarking.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#6935 grandpa: always create and send justification if there are any subscribers
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/notification.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/notification.rs
  client/finality-grandpa/src/observer.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6946 .maintain/monitoring/alerting-rules: Add fd alert
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#6905 Fix benchmark read/write key tracker for keys in child storages.
  client/db/src/bench.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6947 client/authority-discovery: Limit number of addresses per authority
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6942 ShiftNrg reserve SS58 address id 23
  primitives/core/src/crypto.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#6950 Update tracing attribute in cargo.lock
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#6957 Fix unwraps and other issues with benchmarks
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6959 Remove implementation of `Randomness for ()`
  frame/society/src/mock.rs
  frame/support/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6954 Fix staking fuzzer.
  frame/staking/fuzzer/src/submit_solution.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6953 Enforce that ProtocolId is a string
  client/network/src/behaviour.rs
  client/network/src/block_requests.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/finality_requests.rs
  client/network/src/gossip/tests.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6832 Support Staking Payout to Any Account
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D2-breaksapi, D9-needsaudit👮

#6939 Better prime election.
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, B0-silent, C3-medium, D2-breaksapi, D9-needsaudit👮

#6965 Fix benchmark database wipe for child tries.
  client/db/src/bench.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#6634 Implement request-responses protocols
  Cargo.lock
  client/cli/src/params/network_params.rs
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/error.rs
  client/network/src/lib.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#6789 add generated weight info for pallet-collective
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/weights/mod.rs
  bin/node/runtime/src/weights/pallet_collective.rs
  frame/collective/src/benchmarking.rs
  frame/collective/src/default_weight.rs
  frame/collective/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D2-breaksapi

#6967 client/*: Treat protocol name as str and not [u8]
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler/group.rs
  client/network/src/protocol/generic_proto/handler/notif_in.rs
  client/network/src/protocol/generic_proto/handler/notif_out.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B2-breaksapi, B3-apinoteworthy, C1-low

#6963 update kvdb-rocksdb to 0.9.1 and rocksdb to 6.11.4
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, dependencies

#6977 Use AsyncReadExt::read_exact, not just read
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6956 client/cli/src/config: Warn on low file descriptor limit
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/config.rs
  client/service/test/Cargo.toml
Labels: A1-onice, B0-silent, C1-low

#6955 Update substrate bip39 version.
  Cargo.lock
  primitives/core/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6989 Inverting events set and changed in nicks pallet
  frame/nicks/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#6987 Silence the error about non-registered protocols
  client/network/src/protocol.rs
Labels: A2-insubstantial, B0-silent, C1-low

#6992 Change browser-demo build.sh to use python 3 again
  bin/node/cli/browser-demo/build.sh
Labels: A2-insubstantial, B0-silent, C1-low
