Repository paritytech/substrate, pull requests merged in 2021-11, with the labels that each got.

#10081 Strip out control codes from the logged messages
  Cargo.lock
  client/tracing/src/logging/event_format.rs
  client/tracing/src/logging/mod.rs
  primitives/panic-handler/Cargo.toml
  primitives/panic-handler/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10138 Fix transaction pool rejection
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10137 Speed up big chainspec json(~1.5 GB) load
  Cargo.lock
  client/chain-spec/Cargo.toml
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10036 introduce remote-tests for pallet-bags-list
  Cargo.lock
  Cargo.toml
  frame/bags-list/remote-tests/Cargo.toml
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/sanity_check.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/staking/src/pallet/impls.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D2-notlive 💤

#10141 don't panic if already migrated
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9875 Hashing proc macro utils
  Cargo.lock
  Cargo.toml
  client/executor/Cargo.toml
  client/executor/src/wasm_runtime.rs
  frame/support/Cargo.toml
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  primitives/core/Cargo.toml
  primitives/core/hashing/Cargo.toml
  primitives/core/hashing/proc-macro/Cargo.toml
  primitives/core/hashing/proc-macro/src/impls.rs
  primitives/core/hashing/proc-macro/src/lib.rs
  primitives/core/hashing/src/lib.rs
  primitives/core/src/hashing.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10154 Spelling
  docs/STYLE_GUIDE.md
  frame/babe/src/lib.rs
  frame/multisig/src/lib.rs
  primitives/state-machine/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10134 Better error for when origin filter prevent the call to be dispatched
  frame/contracts/src/exec.rs
  frame/multisig/src/tests.rs
  frame/proxy/src/tests.rs
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/test/tests/system.rs
  frame/system/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10148 add missing version to dependencies
  frame/bags-list/remote-tests/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10151 Bump parity-db
  Cargo.lock
  client/db/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10140 Add a `trie_root_hash` variant for chain specs genesis
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10142 Update CI image to the latest rustc
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_call_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.stderr
  frame/support/test/tests/pallet_ui/hooks_invalid_item.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#10132 Handle doc on type_value item in pallet macro
  frame/support/procedural/src/pallet/expand/type_value.rs
  frame/support/procedural/src/pallet/parse/type_value.rs
  frame/support/test/tests/pallet.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10155 Update node-template `construct_runtime!` syntax
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9934 implement dispatch_as
  bin/node/runtime/src/lib.rs
  frame/contracts/src/tests.rs
  frame/proxy/src/tests.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/utility/src/weights.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#10091 rm broken rustdoc-header.html
  .gitlab-ci.yml
  .maintain/rustdoc-header.html
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌

#10188 sc-finality-grandpa-warp-sync: Remove left-over Cargo.toml
  client/finality-grandpa-warp-sync/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10191 Remove unnecessary allocations when crossing WASM FFI boundary
  primitives/runtime-interface/src/impls.rs
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10205 Adds block production time in logs
  client/basic-authorship/src/basic_authorship.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9239 Fast sync child trie support.
  client/api/src/backend.rs
  client/api/src/lib.rs
  client/api/src/proof_provider.rs
  client/consensus/common/src/block_import.rs
  client/network/src/protocol/sync/state.rs
  client/network/src/schema/api.v1.proto
  client/network/src/state_request_handler.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/client/client.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/trie_backend.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10183 put `TryInto` and `TryFrom` in `sp_std::prelude`
  frame/assets/src/lib.rs
  frame/aura/src/lib.rs
  frame/authority-discovery/src/lib.rs
  frame/babe/src/lib.rs
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/remote-tests/src/sanity_check.rs
  frame/benchmarking/src/analysis.rs
  frame/contracts/rpc/src/lib.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/wasm/mod.rs
  frame/democracy/src/conviction.rs
  frame/democracy/src/tests/lock_voting.rs
  frame/democracy/src/vote.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/multisig/src/benchmarking.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/reward-curve/src/log.rs
  frame/staking/reward-fn/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/mod.rs
  frame/system/src/offchain.rs
  frame/transaction-payment/rpc/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/tests.rs
  primitives/std/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
  utils/frame/frame-utilities-cli/src/pallet_id.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10204 Add serde support for `Slot` type
  Cargo.lock
  primitives/consensus/slots/Cargo.toml
  primitives/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10211 Speedup block import command
  client/service/src/chain_ops/import_blocks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10173 Refactor `sp-sandbox`; make sure both sandbox executors are always tested
  Cargo.lock
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/integration_tests/sandbox.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/sandbox.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  primitives/sandbox/src/embedded_executor.rs
  primitives/sandbox/src/host_executor.rs
  primitives/sandbox/src/lib.rs
Labels: A0-pleasereview, I4-tests 🎯, I6-refactor 🧹, B0-silent, C1-low 📌, D3-trivial 🧸

#10220 Offchain-worker: Accessing time is not HTTP
  primitives/core/src/offchain/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10198 Fix polkadot companion label CI check
  .github/workflows/polkadot-companion-labels.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10217 Remove the RPC client example
  Cargo.lock
  Cargo.toml
  bin/node/rpc-client/Cargo.toml
  bin/node/rpc-client/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10221 frame_support::pallet_prelude: Add scale_info::TypeInfo
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
  frame/gilt/src/lib.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10149 Bump `wasmtime` to 0.31.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10218 Bump parity-db
  Cargo.lock
  client/db/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10104 Add a block production benchmark
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/benches/block_production.rs
Labels: A0-pleasereview, I4-tests 🎯, B0-silent, C1-low 📌, D3-trivial 🧸

#10192 new remote-ext mode `OfflineOrElseOnline`
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10225 Move SS58 wiki -> docs links
  bin/utils/subkey/README.md
  client/cli/src/commands/run_cmd.rs
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10224 upgrade ss58-registry with additional networks.
  Cargo.lock
  primitives/core/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10226 Upgrade wasm builder
  utils/wasm-builder/src/prerequisites.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10179 use CountedMap in pallet-bags-list
  bin/node/runtime/src/lib.rs
  frame/bags-list/Cargo.toml
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/migrations.rs
  frame/bags-list/src/tests.rs
  frame/support/src/storage/types/counted_map.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9884 CI: build docs with deps
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10167 Intend to reactivate cargo-unleash check
  .gitlab-ci.yml
  Cargo.lock
  client/allocator/Cargo.toml
  client/api/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/basic-authorship/Cargo.toml
  client/beefy/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/common/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/consensus/pow/Cargo.toml
  client/executor/Cargo.toml
  client/executor/common/Cargo.toml
  client/executor/wasmi/Cargo.toml
  client/executor/wasmtime/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/offchain/Cargo.toml
  client/proposer-metrics/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/service/Cargo.toml
  client/service/test/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/utils/Cargo.toml
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/primitives/Cargo.toml
  frame/beefy/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/beefy/Cargo.toml
  primitives/core/Cargo.toml
  primitives/debug-derive/Cargo.toml
  primitives/maybe-compressed-blob/Cargo.toml
  primitives/panic-handler/Cargo.toml
  primitives/serializer/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/storage/Cargo.toml
  utils/frame/generate-bags/Cargo.toml
  utils/frame/generate-bags/node-runtime/Cargo.toml
  utils/prometheus/Cargo.toml
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10229 expose substrate-cli service
  bin/node/cli/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10022 Upgrade jsonrpsee to v0.4.1
  Cargo.lock
  bin/node/cli/Cargo.toml
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/sanity_check.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#10196 Add group name in task metrics
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/basic-authorship/src/basic_authorship.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/executor/src/native_executor.rs
  client/offchain/src/lib.rs
  client/rpc/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
  primitives/io/src/batch_verifier.rs
  primitives/tasks/src/lib.rs
  test-utils/test-runner/src/client.rs
Labels: A0-pleasereview, E5-breaksapi, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10156 Warn about usage of pallet collective set members call.
  frame/collective/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10206 tuple to struct event variants
  bin/node/executor/tests/fees.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/sudo/src/tests.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
  utils/frame/remote-externalities/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#10245 jsonrpsee: add `rpc handlers` back
  bin/node/test-runner-example/src/lib.rs
  client/rpc/src/testing.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  frame/bags-list/remote-tests/src/sanity_check.rs
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview

#10250 Update requirement for pwasm-utils
  client/executor/common/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10261 Fix cargo unleash check
  utils/frame/remote-externalities/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10178 rework `staking::reap_stash`
  frame/staking/src/benchmarking.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10263 Keystore: Store files with permission 600 on unix
  client/keystore/src/local.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10184 Add field names to pallet `Event` variants
  frame/contracts/src/exec.rs
  frame/proxy/src/tests.rs
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10248 client/service: refactor group param of spawn into an Enum
  client/service/src/task_manager/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9993 Add field names to pallet Event variants
  bin/node/executor/tests/basic.rs
  frame/assets/src/benchmarking.rs
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/atomic-swap/src/lib.rs
  frame/bags-list/src/lib.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/collective/src/benchmarking.rs
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/examples/basic/src/lib.rs
  frame/examples/offchain-worker/src/lib.rs
  frame/gilt/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/lottery/src/lib.rs
  frame/membership/src/lib.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
  frame/nicks/src/lib.rs
  frame/node-authorization/src/lib.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/offences/src/tests.rs
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10268 Forward wasmer-sandbox feature to sp-sandbox
  Cargo.lock
  bin/node/runtime/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10278 Cli: Introduce `--detailed-log-output` flag
  client/cli/src/config.rs
  client/cli/src/params/shared_params.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10280 Vesting: Fix `post_migration` check
  frame/vesting/src/migrations.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10277 Update staking `InsufficientBond` erorr doc.
  frame/staking/src/pallet/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9878 pallet-session: Migrate the historical part to the new pallet macro
  frame/session/benchmarking/src/lib.rs
  frame/session/src/historical/mod.rs
  frame/session/src/historical/offchain.rs
  frame/session/src/lib.rs
  frame/session/src/migrations/mod.rs
  frame/session/src/migrations/v1.rs
  frame/session/src/tests.rs
  frame/staking/src/mock.rs
Labels: A0-pleasereview, B3-apinoteworthy, E1-runtimemigration, C1-low 📌, D5-nicetohaveaudit ⚠️

#10259 authority-discovery: Support multiple authority ids per peer id
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/service.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10294 Offchain testing: Fix reading response
  primitives/core/src/offchain/testing.rs
  primitives/runtime/src/offchain/http.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10281 Check if BEEFY authority is in current set
  client/beefy/src/round.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10201 Offence implementations can disable offenders independently from slashing
  frame/offences/src/lib.rs
  frame/offences/src/migration.rs
  frame/offences/src/mock.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  primitives/staking/src/offence.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#10302 Fix Weight Handlebar Template
  .maintain/frame-weight-template.hbs
  frame/identity/src/weights.rs
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10284 Set current dir at check_wasm_toolchain_installed at wasm-builder
  utils/wasm-builder/src/prerequisites.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10304 jsonrpsee: fallback to random port in case the specified port failed
  client/rpc-servers/src/lib.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#10291 Clear WASM linear memory on other OSes besides Linux too when using fast instance reuse
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10125 Make authorship soft deadline configurable.
  client/basic-authorship/src/basic_authorship.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#10187 Migrate all doc to new pallet macro
  bin/node-template/pallets/template/src/lib.rs
  frame/assets/README.md
  frame/assets/src/lib.rs
  frame/assets/src/mock.rs
  frame/collective/src/tests.rs
  frame/democracy/src/lib.rs
  frame/im-online/README.md
  frame/im-online/src/lib.rs
  frame/lottery/src/lib.rs
  frame/nicks/src/lib.rs
  frame/node-authorization/src/lib.rs
  frame/randomness-collective-flip/README.md
  frame/randomness-collective-flip/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scored-pool/README.md
  frame/scored-pool/src/lib.rs
  frame/staking/README.md
  frame/staking/src/lib.rs
  frame/sudo/README.md
  frame/sudo/src/lib.rs
  frame/system/README.md
  frame/timestamp/README.md
  frame/timestamp/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10127 Moving `pallet-asset-tx-payment` from cumulus to substrate
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/src/keyring.rs
  frame/transaction-payment/asset-tx-payment/Cargo.toml
  frame/transaction-payment/asset-tx-payment/README.md
  frame/transaction-payment/asset-tx-payment/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/payment.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10303 Don't generate the consensusEngine field in chain specs
  client/chain-spec/res/chain_spec.json
  client/chain-spec/res/chain_spec2.json
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10305 Offchain worker: Enable http2 and improve logging
  Cargo.lock
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/api/http.rs
  client/offchain/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10316 Add prometheus metrics for block authorship
  client/basic-authorship/src/basic_authorship.rs
  client/proposer-metrics/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10314 Taskmanager: Remove `clean_shutdown`
  client/cli/src/runner.rs
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10257 tuple to struct event variants
  frame/recovery/src/lib.rs
  frame/session/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10271 use proper intra doc link
  frame/support/procedural/src/construct_runtime/expand/origin.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10329 Fix some doc link
  client/consensus/pow/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/telemetry/src/lib.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/beefy-mmr/primitives/src/lib.rs
  frame/beefy-mmr/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/contracts/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/executive/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/weak_bounded_vec.rs
  frame/support/src/traits/misc.rs
  frame/system/src/lib.rs
  primitives/beefy/src/commitment.rs
  primitives/npos-elections/solution-type/src/lib.rs
  primitives/npos-elections/src/assignments.rs
  primitives/sandbox/src/lib.rs
  utils/frame/generate-bags/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10285 fix chain subscription: less boiler plate
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/helpers.rs
  client/rpc/src/chain/mod.rs
Labels: A0-pleasereview

#10313 Fix WASM executor without instance reuse; cleanups and refactoring
  client/executor/wasmtime/build.rs
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview, I2-bug 🐜, I6-refactor 🧹, B0-silent, C1-low 📌, D3-trivial 🧸

#10323 frame-benchmarking: Fix `min-square` for `--steps=1`
  frame/benchmarking/src/analysis.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10345 Put back consensus_engine, only accept its absence
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10342 fix inner comment
  frame/contracts/src/storage.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10343 Remove some unused code files
  client/network/src/gossip.rs
  client/network/src/gossip/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10338 [ci] Add ssh token for publishing gh-pages
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10363 [ci] Fix publish-rustdoc job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10311 Introduce temporary GitLab & GHA benchmarking jobs
  .github/workflows/bench_gh_gl.yaml
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10355 Derive Debug for CrateVersion and StorageVersion
  frame/support/src/traits/metadata.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10364 [ci] Fix publish-rustdoc
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10366 Stabilize "seal1" `seal_call`
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#10367 Enable wasmtime for aarch64 as well
  bin/node/cli/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10348 Don't send ForceClose repeatedly in send_sync_notification
  client/network/src/protocol/notifications/handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10035 Bump libp2p to 0.40.0
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/generate_node_key.rs
  client/cli/src/commands/inspect_node_key.rs
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/bitswap.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10369 REAL fix for `min-square` for `--steps=1 --repeats=1` (#10323)
  frame/benchmarking/src/analysis.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10328 `BEEFY` add tests for rounds
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/src/gossip.rs
  client/beefy/src/gossip_tests.rs
  client/beefy/src/keystore.rs
  client/beefy/src/keystore_tests.rs
  client/beefy/src/round.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10373 remove base weight annotations
  frame/balances/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10374 Update W3F URL links
  frame/staking/src/slashing.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10377 Reduce the execution time of some tests
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10344 Remove invalid link without fixing them
  client/network/src/block_request_handler.rs
  client/network/src/light_client_requests/handler.rs
  client/network/src/service.rs
  client/network/src/state_request_handler.rs
  client/service/src/client/mod.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10368 Tips Benchmarking to be Runtime Agnostic
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/lib.rs
  frame/tips/src/benchmarking.rs
  frame/tips/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10352 Add `vote` and `seconded` events to Democracy pallet.
  frame/democracy/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10324 Add runtime-benchmarks for frame-benchmarking
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node/runtime/Cargo.toml
  frame/assets/Cargo.toml
  frame/babe/Cargo.toml
  frame/bags-list/Cargo.toml
  frame/balances/Cargo.toml
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/baseline.rs
  frame/bounties/Cargo.toml
  frame/collective/Cargo.toml
  frame/contracts/Cargo.toml
  frame/democracy/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/examples/basic/Cargo.toml
  frame/gilt/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/identity/Cargo.toml
  frame/im-online/Cargo.toml
  frame/indices/Cargo.toml
  frame/lottery/Cargo.toml
  frame/membership/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/multisig/Cargo.toml
  frame/proxy/Cargo.toml
  frame/scheduler/Cargo.toml
  frame/staking/Cargo.toml
  frame/timestamp/Cargo.toml
  frame/tips/Cargo.toml
  frame/transaction-storage/Cargo.toml
  frame/treasury/Cargo.toml
  frame/uniques/Cargo.toml
  frame/utility/Cargo.toml
  frame/vesting/Cargo.toml
Labels: A1-onice, B0-silent, C1-low 📌, D3-trivial 🧸

#10296 Add pallet names to Events
  bin/node/executor/tests/basic.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/society/src/lib.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-storage/src/benchmarking.rs
  frame/transaction-storage/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
