Repository paritytech/substrate, pull requests merged in 2021-05, with the labels that each got.

#8673 Add future transactions accessor to `ValidatedPool`
  client/transaction-pool/graph/src/validated_pool.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8710 Put BoundedVec in pallet prelude
  frame/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8663 Upgrade authorship pallet to Frame-v2
  frame/authorship/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8664 Fixed typos in upgrade readme.
  docs/Upgrading-2.0-to-3.0.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8614 Refactor election solution trimming for efficiency
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/compact/src/index_assignment.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/assignments.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#8414 Remove Offence delay
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/lib.rs
  frame/offences/src/migration.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  primitives/staking/src/offence.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8687 Make custom on runtime upgrade prior to pallet ones
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8290 Multi-phase elections solution resubmission
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D1-audited 👍

#8704 Add a JSON-RPC layer for reserved nodes
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/service.rs
  client/peerset/src/lib.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#8526 Rework inherent data client side
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/bench/src/construct.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/Cargo.toml
  client/consensus/pow/src/lib.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  client/consensus/uncles/Cargo.toml
  client/consensus/uncles/src/lib.rs
  client/service/src/client/client.rs
  client/service/src/lib.rs
  frame/authorship/Cargo.toml
  frame/authorship/src/lib.rs
  frame/executive/src/lib.rs
  frame/support/src/inherent.rs
  frame/support/src/lib.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/instance.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/timestamp/src/lib.rs
  primitives/authorship/Cargo.toml
  primitives/authorship/src/lib.rs
  primitives/consensus/aura/Cargo.toml
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/inherents.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/inherents/Cargo.toml
  primitives/inherents/src/client_side.rs
  primitives/inherents/src/lib.rs
  primitives/timestamp/Cargo.toml
  primitives/timestamp/src/lib.rs
  test-utils/runtime/src/system.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8717 Fix too generous error detection in behaviour.rs
  client/network/src/protocol/notifications/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8697 Update Identity pallet to Frame V2
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8712 Add some builder functions for NonDefaultSetConfig
  client/network/src/config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8707 Improve `BoundedVec` API
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8718 primitives: remove random_seed from BlockBuilder API
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/rpc/src/state/tests.rs
  primitives/block-builder/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#8727 impl BoundedEncodedLen for BoundedVec
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8721 Set max log level when changing the log directives via RPC
  client/rpc/src/system/tests.rs
  client/tracing/src/logging/directives.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8720 implement BoundedEncodedLen
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/traits.rs
  frame/support/src/traits/max_encoded_len.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8711 add test for pallet store trait
  frame/support/test/tests/pallet.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8730 Makes system migrations public
  frame/system/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#8731 Let the clone wars begin!
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
  client/cli/src/commands/generate.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/commands/purge_chain_cmd.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/commands/sign.rs
  client/cli/src/commands/vanity.rs
  client/cli/src/commands/verify.rs
  client/cli/src/params/database_params.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/keystore_params.rs
  client/cli/src/params/mod.rs
  client/cli/src/params/network_params.rs
  client/cli/src/params/node_key_params.rs
  client/cli/src/params/offchain_worker_params.rs
  client/cli/src/params/pruning_params.rs
  client/cli/src/params/shared_params.rs
  client/cli/src/params/transaction_pool_params.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#7780 RPC to trace execution of specified block
  Cargo.lock
  client/rpc-api/Cargo.toml
  client/rpc-api/src/state/mod.rs
  client/rpc-servers/src/lib.rs
  client/rpc/Cargo.toml
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/rpc/src/system/mod.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  client/tracing/Cargo.toml
  client/tracing/src/block/mod.rs
  client/tracing/src/lib.rs
  client/tracing/src/logging/mod.rs
  primitives/rpc/Cargo.toml
  primitives/rpc/src/lib.rs
  primitives/rpc/src/tracing.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/tracing/Cargo.toml
  primitives/tracing/README.md
  primitives/tracing/src/lib.rs
  primitives/tracing/src/types.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-breaksapi, D3-trivial 🧸, E5-breaksapi

#8732 Fix panic in election-provider offchain worker.
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8714 Migrate pallet-im-online to pallet attribute macro.
  frame/im-online/src/benchmarking.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8738 remove patract ss58version for it's useless now
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8723 Migrate pallet-nicks to pallet attribute macro.
  frame/nicks/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8736 Add a readme about feature metered for sp-utils
  primitives/utils/README.md
  primitives/utils/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8533 Added client function to delete a recent block
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/api/src/leaves.rs
  client/db/src/lib.rs
  client/light/src/backend.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8739 Make some alerting rules warning instead of critical
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8744 derive Encode and Decode for BigUint
  primitives/arithmetic/src/biguint.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8746 BoundedVec MaxEncodedLen microoptimization
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8342 [B0-silent] Add ss58 prefix for equilibrium
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8745 Add `BoundedBTreeMap` to `frame_support::storage`
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8682 Allow fallback names for protocols
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/protocol/notifications.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/protocol/notifications/upgrade.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/transactions.rs
  client/network/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8753 Fix the calculation of the time until the next slot
  client/consensus/slots/src/slots.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8737 `#[derive(MaxEncodedLen)]`
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/max_encoded_len.rs
  frame/support/src/traits.rs
  frame/support/test/tests/max_encoded_len.rs
  frame/support/test/tests/max_encoded_len_ui.rs
  frame/support/test/tests/max_encoded_len_ui/not_encode.rs
  frame/support/test/tests/max_encoded_len_ui/not_encode.stderr
  frame/support/test/tests/max_encoded_len_ui/not_mel.rs
  frame/support/test/tests/max_encoded_len_ui/not_mel.stderr
  frame/support/test/tests/max_encoded_len_ui/union.rs
  frame/support/test/tests/max_encoded_len_ui/union.stderr
  frame/support/test/tests/max_encoded_len_ui/unsupported_variant.rs
  frame/support/test/tests/max_encoded_len_ui/unsupported_variant.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8749 Relax `BoundedVec` trait restrictions
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/value.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8760 Fix Spelling in Colletive
  frame/collective/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8765 Remove unneeded trait bounds
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  test-utils/runtime/client/src/block_builder_ext.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/client/src/trait_tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8768 Two bugfixes to authority-discovery
  client/authority-discovery/src/worker/addr_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8750 Add `BoundedBTreeSet`
  frame/support/src/storage/bounded_btree_set.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8726 Add arithmetic dispatch errors.
  frame/assets/README.md
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/democracy/src/lib.rs
  frame/lottery/src/lib.rs
  frame/recovery/src/lib.rs
  frame/support/src/traits/tokens/fungible/balanced.rs
  frame/support/src/traits/tokens/fungibles/balanced.rs
  frame/support/src/traits/tokens/misc.rs
  primitives/runtime/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#8771 Increase the number of external IPs in cache
  client/network/src/discovery.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8766 Update pallet macro migrations.
  frame/babe/src/lib.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
  frame/nicks/src/lib.rs
  frame/timestamp/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#8778 Don't remove addresses from known_external_addresses
  client/network/src/discovery.rs
  client/network/src/utils.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8787 Revert Changes: InspectKeyCmd back to InspectCmd where appropriate
  bin/node/cli/src/cli.rs
  bin/node/inspect/src/cli.rs
  bin/node/inspect/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, Q0-trivial

#8734 frame system: add event util functions for tests.
  frame/assets/src/benchmarking.rs
  frame/assets/src/tests.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_reentrancy.rs
  frame/bounties/src/benchmarking.rs
  frame/collective/src/benchmarking.rs
  frame/democracy/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/multisig/src/tests.rs
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/tests.rs
  frame/sudo/src/tests.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/utility/src/benchmarking.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8762 Migrate pallet-lottery to pallet attribute macro
  bin/node/runtime/src/lib.rs
  frame/lottery/src/benchmarking.rs
  frame/lottery/src/lib.rs
  frame/lottery/src/mock.rs
  frame/lottery/src/tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8789 Update environmental crate
  Cargo.lock
  primitives/externalities/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8761 Migrate pallet-recovery to pallet attribute macro
  frame/recovery/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8688 Embed runtime version as a custom section
  Cargo.lock
  Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/executor/Cargo.toml
  client/executor/common/Cargo.toml
  client/executor/common/src/runtime_blob/runtime_blob.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  frame/system/src/tests.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/core/src/traits.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/state-machine/src/lib.rs
  primitives/version/Cargo.toml
  primitives/version/proc-macro/Cargo.toml
  primitives/version/proc-macro/src/decl_runtime_version.rs
  primitives/version/proc-macro/src/lib.rs
  primitives/version/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, B5-clientnoteworthy, B7-runtimenoteworthy, C7-high ❗️, D3-trivial 🧸

#8788 Remove grandpa `StoredPendingChange` shim
  frame/grandpa/src/lib.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8763 Migrate pallet-offences to pallet attribute macro
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8792 [rpc]: implement system API
  Cargo.lock
  client/rpc-api/src/system/error.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/mod.rs
  client/service/src/builder.rs
Labels: A0-pleasereview

#8791 Maintain fork_targets
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8797 add state RPC API (without subscriptions)
  client/rpc-api/src/state/error.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/service/src/builder.rs
Labels: A0-pleasereview

#8773 contracts: Move `Schedule` from Storage to `Config`
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  bin/utils/chain-spec-builder/src/main.rs
  frame/contracts/CHANGELOG.md
  frame/contracts/README.md
  frame/contracts/common/src/lib.rs
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/debug_message_invalid_utf8.wat
  frame/contracts/fixtures/debug_message_logging_disabled.wat
  frame/contracts/fixtures/debug_message_works.wat
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤, E1-runtimemigration

#8798 Fix warning: trait objects without an explicit dyn are deprecated
  client/chain-spec/src/extension.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8802 [rpc]: enable all unsafe calls
  client/rpc/src/state/mod.rs
  client/service/src/builder.rs
Labels: A0-pleasereview

#8635 Implement StorageNMap
  frame/metadata/src/lib.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/procedural/src/storage/genesis_config/builder_def.rs
  frame/support/procedural/src/storage/genesis_config/genesis_config_def.rs
  frame/support/procedural/src/storage/genesis_config/mod.rs
  frame/support/procedural/src/storage/getters.rs
  frame/support/procedural/src/storage/instance_trait.rs
  frame/support/procedural/src/storage/metadata.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/key.rs
  frame/support/src/storage/types/mod.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_compatibility_instance.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/storage_not_storage_type.stderr
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8804 [rpc] regard when param.one() failed as no params.
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/mod.rs
Labels: A0-pleasereview

#8805 [rpc] add offchain API
  client/rpc/src/author/mod.rs
  client/rpc/src/offchain/mod.rs
  client/rpc/src/state/state_full.rs
  client/service/src/builder.rs
Labels: A0-pleasereview

#8807 Add more debug_assert to networking
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8811 Small improvement to network log line
  client/network/src/protocol/notifications/behaviour.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8818 frame/session/benchmarking: fix invalid feature declaration
  frame/session/benchmarking/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8820 Add names to offchain worker threads
  client/offchain/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8817 Improve match statement
  client/db/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8816 Use StorageNMap for Approvals in assets pallet
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
  frame/support/src/storage/types/key.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8812 Extends ChildStateBackend and ChildStateAPI with ReadProofs
  client/rpc-api/src/child_state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8735 Allow to specify some max number of values for storages in pallet macro.
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/pallet_struct.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/src/storage/storage_info.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/hash.rs
  frame/support/src/lib.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/key.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/mod.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/storage.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/duplicate_store_attr.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8830 Add Debug to token traits `AssetId` and `Balance`
  frame/support/src/traits/tokens/misc.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8809 [clippy] Fix clippy issues for crate sp-core
  primitives/core/benches/bench.rs
  primitives/core/src/changes_trie.rs
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/lib.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/offchain/storage.rs
  primitives/core/src/offchain/testing.rs
  primitives/core/src/sr25519.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8769 Migrate pallet-scheduler to pallet attribute macro
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8845 Emit wasm sections only when compiling to wasm
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/version/proc-macro/src/decl_runtime_version.rs
  primitives/version/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8828 Ensure election offchain workers don't overlap
  bin/node/cli/src/chain_spec.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  primitives/runtime/src/offchain/storage_lock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D9-needsaudit 👮

#8838 Add CryptoStore::ecdsa_sign_prehashed()
  client/keystore/src/local.rs
  primitives/core/src/ecdsa.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8751 Allow to name the generic for storages in `#[pallet::storage]`
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_invalid_first_generic.stderr
  frame/support/test/tests/pallet_ui/storage_not_storage_type.stderr
  frame/support/test/tests/pallet_ui/storage_value_duplicate_named_generic.rs
  frame/support/test/tests/pallet_ui/storage_value_duplicate_named_generic.stderr
  frame/support/test/tests/pallet_ui/storage_value_generic_named_and_unnamed.rs
  frame/support/test/tests/pallet_ui/storage_value_generic_named_and_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_value_no_generic.stderr
  frame/support/test/tests/pallet_ui/storage_value_unexpected_named_generic.rs
  frame/support/test/tests/pallet_ui/storage_value_unexpected_named_generic.stderr
  frame/support/test/tests/pallet_ui/storage_wrong_item.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8855 Make wasmtime the default when the feature is enabled
  client/cli/src/arg_enums.rs
  client/cli/src/params/import_params.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#8856 Improve `impl_opaque_keys!`
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8851 Improve pallet macro error message by deriving codec with no bound for `Call` enum
  frame/support/Cargo.toml
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8860 Fix transaction payment fee/tip unbalanceds
  frame/transaction-payment/src/lib.rs
  frame/transaction-payment/src/payment.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#8832 Update the Grafana dashboards
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8863 Update decimals & website for Karura
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8780 contracts: Add `seal_rent_status`
  bin/node/runtime/Cargo.toml
  frame/contracts/Cargo.toml
  frame/contracts/README.md
  frame/contracts/fixtures/debug_message_invalid_utf8.wat
  frame/contracts/fixtures/debug_message_logging_disabled.wat
  frame/contracts/fixtures/debug_message_works.wat
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8831 add trigger for monitoring job in cloud-infra repository
  .gitlab-ci.yml
Labels: B0-silent, C1-low 📌

#8853 Make hooks and call attributes optional in pallet macro
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/inconsistent_instance_1.stderr
  frame/support/test/tests/pallet_ui/inconsistent_instance_2.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8872 contracts: Fix `__unstable__` feature
  frame/contracts/src/wasm/env_def/macros.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8741 Pallet-Multisig to framev2
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8876 Fix doc for CryptoStore::ecdsa_sign_prehashed()
  primitives/core/src/lib.rs
  primitives/keystore/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8877 Add ExternalitiesExt for TestExternalities
  primitives/state-machine/src/testing.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8795 grandpa: fix warp sync proof on missing data
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa-warp-sync/src/proof.rs
  client/finality-grandpa/src/authorities.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8881 Aura improvements
  bin/node-template/node/src/service.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8874 Remove now unneeded empty hooks and calls #8873
  bin/node-template/pallets/template/src/lib.rs
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/aura/src/lib.rs
  frame/authority-discovery/src/lib.rs
  frame/balances/src/lib.rs
  frame/example-parallel/src/lib.rs
  frame/identity/src/lib.rs
  frame/indices/src/lib.rs
  frame/nicks/src/lib.rs
  frame/offences/src/lib.rs
  frame/proxy/src/lib.rs
  frame/recovery/src/lib.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8892 Default 2048 heap pages
  client/executor/src/native_executor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8901 Make sure nodes don't hammer each other even when reserved
  client/network/src/protocol/notifications/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8898 Introduce `code_substitute`
  bin/node/testing/src/client.rs
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/client/mod.rs
  client/service/src/client/wasm_substitutes.rs
  client/service/test/src/client/mod.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C7-high ❗️, D3-trivial 🧸

#8889 make remote-ext work with ws and safe RPCs
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8897 Removes unnecessary blank impl for Backend
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/light/src/backend.rs
  client/service/src/client/call_executor.rs
  client/service/test/src/client/mod.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/trie_backend.rs
Labels: A6-seemsok, B0-silent, C1-low 📌, D3-trivial 🧸

#8904 Fix stderr in new Rust nightly
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A3-inprogress, A7-needspolkadotpr, B0-silent, C1-low 📌

#8905 Fix build job
  .maintain/node-template-release.sh
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌

#8879 contracts: Fix some minor bugs around instantiation
  frame/contracts/CHANGELOG.md
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8900 Convert Into to From to make clippy happy
  frame/support/src/origin.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8903 add an absolute measure of election score on-chain as a parameter
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C7-high ❗️, D5-nicetohaveaudit ⚠️

#8796 grandpa: enable light clients to participate in gossip
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/config.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌

#8910 Revert "Fix stderr in new Rust nightly"
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8724 Migrate pallet-grandpa to attribute macros
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/testing/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/grandpa/src/benchmarking.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/migrations.rs
  frame/grandpa/src/migrations/v3_1.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8882 Add Basilisk ss58
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8706 Manta Network ss58 address registration
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8844 Convert impl_key_prefix_for to proc macro
  frame/support/procedural/src/key_prefix.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/storage/types/key.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8748 Remove NetworkStatusSinks
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/informant/Cargo.toml
  client/informant/src/lib.rs
  client/network/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌

#8927 CI: fix simnet trigger
  .gitlab-ci.yml
  .maintain/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8887 More sc-service config reexports
  client/api/src/execution_extensions.rs
  client/service/src/config.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8918 Emergency mode for elections.
  Cargo.lock
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8930 Fix check runtime CI
  .maintain/gitlab/check_runtime.sh
  frame/contracts/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8793 Simple `MaxBoundedLen` Implementations
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/assets/Cargo.toml
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
  frame/balances/Cargo.toml
  frame/balances/src/lib.rs
  frame/proxy/Cargo.toml
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
  frame/sudo/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/test/tests/max_encoded_len_ui/not_encode.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  max-encoded-len/Cargo.toml
  max-encoded-len/derive/Cargo.toml
  max-encoded-len/derive/src/lib.rs
  max-encoded-len/src/lib.rs
  max-encoded-len/tests/max_encoded_len.rs
  max-encoded-len/tests/max_encoded_len_ui.rs
  max-encoded-len/tests/max_encoded_len_ui/list_list_item.rs
  max-encoded-len/tests/max_encoded_len_ui/list_list_item.stderr
  max-encoded-len/tests/max_encoded_len_ui/literal_list_item.rs
  max-encoded-len/tests/max_encoded_len_ui/literal_list_item.stderr
  max-encoded-len/tests/max_encoded_len_ui/name_value_attr.rs
  max-encoded-len/tests/max_encoded_len_ui/name_value_attr.stderr
  max-encoded-len/tests/max_encoded_len_ui/name_value_list_item.rs
  max-encoded-len/tests/max_encoded_len_ui/name_value_list_item.stderr
  max-encoded-len/tests/max_encoded_len_ui/no_path_list_items.rs
  max-encoded-len/tests/max_encoded_len_ui/no_path_list_items.stderr
  max-encoded-len/tests/max_encoded_len_ui/not_encode.rs
  max-encoded-len/tests/max_encoded_len_ui/not_encode.stderr
  max-encoded-len/tests/max_encoded_len_ui/not_mel.rs
  max-encoded-len/tests/max_encoded_len_ui/not_mel.stderr
  max-encoded-len/tests/max_encoded_len_ui/path_attr.rs
  max-encoded-len/tests/max_encoded_len_ui/path_attr.stderr
  max-encoded-len/tests/max_encoded_len_ui/two_path_list_items.rs
  max-encoded-len/tests/max_encoded_len_ui/two_path_list_items.stderr
  max-encoded-len/tests/max_encoded_len_ui/union.rs
  max-encoded-len/tests/max_encoded_len_ui/union.stderr
  max-encoded-len/tests/max_encoded_len_ui/unsupported_variant.rs
  max-encoded-len/tests/max_encoded_len_ui/unsupported_variant.stderr
  primitives/application-crypto/Cargo.toml
  primitives/application-crypto/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8935 Remove duplicate `Issued`/`Burned` events in Assets pallet
  frame/assets/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8938 weather -> whether
  frame/support/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8916 make remote ext use batch ws-client
  Cargo.lock
  primitives/storage/src/lib.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8924 Make `Schedule` fields public to allow for customization
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8942 Session key should be settable at genesis even for non-endowed accounts
  frame/session/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8825 Migrate pallet-scored-pool to pallet attribute macro
  frame/scored-pool/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/scored-pool/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤, E1-runtimemigration

#8852 Use correct CreateInherentDataProviders impl for manual seal
  bin/node/test-runner-example/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8932 Refactor BlockRequestHandler
  client/network/src/block_request_handler.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#8956 Optimize `next_storage_key`
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/overlayed_changes/changeset.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8961 Add deserialize for TransactionValidityError in std.
  primitives/runtime/src/transaction_validity.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤
