Repository paritytech/substrate, pull requests merged in 2021-03, with the labels that each got.

#8233 babe: make plan_config_change callable by root
  frame/babe/src/default_weights.rs
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8230 Fix state mismatch in case of bad handshake
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8232 contracts: Use unstable sort for topics
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8228 Make Benchmark Output Analysis Function Configurable
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/system/src/weights.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8239 Add benchmark to node-template pallet-template
  Cargo.lock
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/benchmarking.rs
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/timestamp/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8211 Fix tests in phragmen election pallet
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8199 Add some migration helper to help migrating pallet changing pallet prefix
  frame/support/src/storage/migration.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8245 Move AuRa digest from client to primitives
  client/consensus/aura/src/lib.rs
  primitives/consensus/aura/src/digests.rs
  primitives/consensus/aura/src/lib.rs
  primitives/consensus/babe/src/digests.rs
  primitives/runtime/src/generic/digest.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8244 Make `ExecuteBlock::execute_block` return the final block header
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/executive/README.md
  frame/executive/src/lib.rs
  frame/support/src/traits.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8241 Allow pallet::call to return `DispatchResult`
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/procedural/src/pallet/parse/helper.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/call_invalid_return.rs
  frame/support/test/tests/pallet_ui/call_invalid_return.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8243 Add migration logs to pallet v2
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/procedural/src/pallet/parse/hooks.rs
  frame/support/src/dispatch.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8256 Do not return the `Header` from `execute_block`
  frame/executive/src/lib.rs
  frame/support/src/traits.rs
  test-utils/runtime/src/system.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8221 Self-sufficient account ref-counting
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  frame/executive/src/lib.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D1-runtime-migration, D2-breaksapi, D9-needsaudit👮

#8249 Update minor yanked dependencies
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#7833 babe: introduce a request-answering mechanic
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, A3-stale, A7-needspolkadotpr, B0-silent, C1-low

#8272 Fix warnings related to panic and assert
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  client/tracing/src/logging/mod.rs
  frame/democracy/src/tests.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/offences/benchmarking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8277 Fix doc build with --all-features
  .maintain/frame-weight-template.hbs
  bin/node-template/pallets/template/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/network/src/config.rs
  client/network/src/light_client_requests/handler.rs
  client/tracing/src/logging/layers/prefix_layer.rs
  frame/assets/src/weights.rs
  frame/bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/example/Cargo.toml
  frame/executive/Cargo.toml
  frame/gilt/Cargo.toml
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/multisig/src/weights.rs
  frame/proxy/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/support/src/traits.rs
  frame/support/test/Cargo.toml
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/treasury/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  primitives/io/src/lib.rs
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8255 AuRa improvements
  bin/node-template/node/src/service.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8275 Do not use `Option` to wrap `GenesisConfig` fields
  bin/node-template/node/src/chain_spec.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/testing/src/genesis.rs
  frame/collective/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/example/src/lib.rs
  frame/support/src/genesis_config.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8105 refactor(remote ext): use jsonrpsee
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: B0-silent, C1-low, D2-breaksapi

#8276 pallet macros: Improve emitted rustdoc
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/config.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/call.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#8282 Clippy arithmetic new
  primitives/arithmetic/src/biguint.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/core/src/changes_trie.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/hashing.rs
  primitives/core/src/offchain/mod.rs
  primitives/tracing/src/types.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8299 Introduce IgnoredIssuance into Gilts
  bin/node/runtime/src/lib.rs
  frame/gilt/src/lib.rs
  frame/gilt/src/mock.rs
  frame/gilt/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi, D9-needsaudit👮

#8302 update jsonrpsee to remove `allow(dead_code)`
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8260 Decrease the peer reputation on invalid block requests
  client/network/src/block_request_handler.rs
  client/network/src/gossip/tests.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8295 Simplify client/consensus/babe/src/authorship.rs a bit
  client/consensus/babe/src/authorship.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8300 Fix typo in generated docs
  frame/support/procedural/src/pallet/expand/genesis_config.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8280 Introduce new concept of "slot portion for proposing"
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8294 Update to latest proc-macro-crate version
  Cargo.lock
  client/chain-spec/derive/Cargo.toml
  client/chain-spec/derive/src/impls.rs
  client/tracing/proc-macro/Cargo.toml
  client/tracing/proc-macro/src/lib.rs
  frame/staking/reward-curve/Cargo.toml
  frame/staking/reward-curve/src/lib.rs
  frame/support/procedural/tools/Cargo.toml
  frame/support/procedural/tools/src/lib.rs
  primitives/api/proc-macro/Cargo.toml
  primitives/api/proc-macro/src/utils.rs
  primitives/npos-elections/compact/Cargo.toml
  primitives/npos-elections/compact/src/lib.rs
  primitives/runtime-interface/proc-macro/Cargo.toml
  primitives/runtime-interface/proc-macro/src/utils.rs
  test-utils/derive/Cargo.toml
  test-utils/derive/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8072 Return babe configuration information in the babe api epoch functions
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  client/consensus/babe/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#8309 Revert "Decrease the peer reputation on invalid block requests (#8260)"
  client/network/src/block_request_handler.rs
  client/network/src/gossip/tests.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, A6-revertrevert, B0-silent, C1-low

#8307 CI: return docs jobs
  .gitlab-ci.yml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8137 Custom RPC for Merkle Mountain Range pallet
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/bench.rs
  client/api/src/execution_extensions.rs
  client/executor/src/integration_tests/mod.rs
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/example-offchain-worker/src/tests.rs
  frame/im-online/src/tests.rs
  frame/merkle-mountain-range/primitives/src/lib.rs
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/tests.rs
  frame/session/src/historical/offchain.rs
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/tests.rs
  primitives/core/src/lib.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/offchain/testing.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/offchain/http.rs
  primitives/runtime/src/offchain/storage.rs
  primitives/runtime/src/offchain/storage_lock.rs
  test-utils/client/Cargo.toml
  test-utils/client/src/lib.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D2-breaksapi

#8180 more clear randomness API for BABE
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/randomness.rs
  frame/babe/src/tests.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/lottery/Cargo.toml
  frame/lottery/src/lib.rs
  frame/lottery/src/mock.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/society/Cargo.toml
  frame/society/src/lib.rs
  frame/society/src/mock.rs
  frame/support/src/traits.rs
  frame/support/test/Cargo.toml
  frame/support/test/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D2-breaksapi

#8160 Implement PJR checker
  Cargo.lock
  frame/staking/src/lib.rs
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/src/common.rs
  primitives/npos-elections/fuzzer/src/phragmen_pjr.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/pjr.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8322 Fix doc build
  frame/support/test/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, I5-documentation 📄

#8143 Rework telemetry to replace the use of tracing with an object we pass around
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/bench/src/construct.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/browser.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  bin/node/inspect/src/command.rs
  bin/node/testing/src/bench.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/cli/src/arg_enums.rs
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/slots/src/lib.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/config.rs
  client/service/src/error.rs
  client/service/src/metrics.rs
  client/service/src/task_manager/tests.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  client/telemetry/Cargo.toml
  client/telemetry/src/error.rs
  client/telemetry/src/layer.rs
  client/telemetry/src/lib.rs
  client/telemetry/src/node.rs
  client/tracing/Cargo.toml
  client/tracing/src/lib.rs
  client/tracing/src/logging/event_format.rs
  client/tracing/src/logging/mod.rs
  test-utils/client/src/lib.rs
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B2-breaksapi, B5-clientnoteworthy, C1-low

#8296 Finish removing support for legacy network protocol
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade.rs
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8168 pallet-staking: add RewardDestination::None for explictly not receiving rewards
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#8209 Add on_idle hook
  frame/executive/src/lib.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#8330 Fix #8306
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8333 Convert timestamp to unit type wrapper
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/pow/src/lib.rs
  frame/aura/Cargo.toml
  frame/aura/src/lib.rs
  frame/babe/Cargo.toml
  frame/babe/src/lib.rs
  frame/support/src/traits.rs
  frame/timestamp/src/lib.rs
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/babe/src/inherents.rs
  primitives/std/with_std.rs
  primitives/std/without_std.rs
  primitives/timestamp/Cargo.toml
  primitives/timestamp/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8325 Do not ban peers for sending multiple valid requests
  client/network/src/block_request_handler.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8231 contracts: Expose rent parameter to contracts
  frame/contracts/CHANGELOG.md
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#8242 im-online: use EstimateNextSessionRotation to get better estimates of session progress
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/staking/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D2-breaksapi

#8341 remove whitespaces in executive
  frame/executive/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#8346 Derive common classes for `IfDisconnected`.
  client/network/src/request_responses.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8335 Remove useless sr-api
  primitives/sr-api/proc-macro/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8355 Don't log to debug for every failed extrinsic.
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8353 Add more relaxed pallet-name parsing
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8339 Don't log so many stkaing events on genesis block
  frame/election-provider-multi-phase/src/lib.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8324 Support pallet::storage conditional compilation
  .gitlab-ci.yml
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/expand/store_trait.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/procedural/src/pallet/parse/event.rs
  frame/support/procedural/src/pallet/parse/helper.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/procedural/src/pallet/parse/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/src/lib.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet.rs
Labels: A5-grumble, B0-silent, C1-low, D2-breaksapi

#8236 NPoS Challenge Mode
  primitives/npos-elections/fuzzer/src/phragmen_pjr.rs
  primitives/npos-elections/src/pjr.rs
Labels: A5-grumble, B0-silent, C1-low, D2-breaksapi

#8327 staking: Flexible generation of reward curve and associated tweaks
  .gitignore
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/contracts/src/tests.rs
  frame/gilt/src/lib.rs
  frame/gilt/src/mock.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/mock.rs
  frame/im-online/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/lib.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/support/src/weights.rs
  primitives/arithmetic/fuzzer/src/per_thing_rational.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/pjr.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B2-breaksapi, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8369 alerting-rules: ContinuousTaskEnded alert shouldn't drop unspecified labels
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#8374 Document a pub item
  frame/staking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8371 Update diener to enable polkadot companions that use new crates
  .maintain/gitlab/check_polkadot_companion_build.sh
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#8360 Release missing 3.0 crates: pallet-node-authorization sc-finality-grandpa-warp-sync
  Cargo.lock
  frame/node-authorization/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8351 Update ss58-registry.json
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#8345 [CI] Require D*-audit labels for any runtime changes
  .github/workflows/check-labels.yml
  .maintain/common/lib.sh
  .maintain/github/check_labels.sh
  .maintain/gitlab/check_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8380 Fix CI benchmark check
  frame/contracts/src/wasm/prepare.rs
Labels: A2-insubstantial, B0-silent, C1-low, D1-audited👍, D2-breaksapi

#8314 Improve complexity of CompactAssignments::unique_targets
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/codec.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D5-nicetohaveaudit⚠️

#8365 Migrate pallet-proxy to pallet attribute macro
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi, D5-nicetohaveaudit⚠️

#8387 [CI] Fix check-labels.yml
  .github/workflows/check-labels.yml
Labels: A0-pleasereview, B0-silent, C1-low

#8388 Add D1-trivial label
  .maintain/github/check_labels.sh
Labels: A0-pleasereview, B0-silent, C1-low

#8310 Migrate pallet-babe to pallet attribute macro.
  frame/babe/src/benchmarking.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/randomness.rs
  frame/babe/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi, D5-nicetohaveaudit⚠️

#7640 Storing multiple Justifications per block
  client/api/src/backend.rs
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/rpc.rs
  client/consensus/pow/src/lib.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/lib.rs
  client/db/src/upgrade.rs
  client/finality-grandpa-warp-sync/src/proof.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/tests.rs
  client/light/src/backend.rs
  client/light/src/blockchain.rs
  client/network/src/behaviour.rs
  client/network/src/block_request_handler.rs
  client/network/src/gossip/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/rpc/src/chain/chain_light.rs
  client/rpc/src/chain/tests.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  primitives/blockchain/src/backend.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/runtime/src/generic/block.rs
  primitives/runtime/src/lib.rs
  test-utils/client/src/client_ext.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D2-breaksapi, D5-nicetohaveaudit⚠️

#8386 Aura and Slots refactoring
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  primitives/consensus/aura/Cargo.toml
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/aura/src/lib.rs
  primitives/consensus/babe/src/inherents.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/common/src/lib.rs
  primitives/timestamp/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D1-audited👍, D2-breaksapi

#8385 Fast CompactAssignment search
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/staking/src/offchain_election.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi, D5-nicetohaveaudit⚠️

#8389 Improve logging in network gossip
  Cargo.lock
  client/network-gossip/Cargo.toml
  client/network-gossip/src/state_machine.rs
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#8265 Storage chains: indexing, renewals and reference counting
  client/api/src/backend.rs
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/api/src/leaves.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/parity_db.rs
  client/db/src/utils.rs
  client/light/src/backend.rs
  client/light/src/blockchain.rs
  client/network/src/bitswap.rs
  client/service/src/client/client.rs
  primitives/blockchain/src/backend.rs
  primitives/database/Cargo.toml
  primitives/database/src/kvdb.rs
  primitives/database/src/lib.rs
  primitives/database/src/mem.rs
  primitives/externalities/src/lib.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D1-trivial, D6-newhostfunctions

#8396 doc(frame): [nitpicks]
  frame/collective/README.md
  frame/contracts/src/lib.rs
Labels: B0-silent, C1-low, D1-trivial, D2-breaksapi

#8399 Better description for assert in frame-session genesis
  frame/session/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D1-trivial, D2-breaksapi

#8332 Compute yearly inflation on-chain allowing to change x_ideal according to number of slots.
  Cargo.lock
  Cargo.toml
  frame/staking/reward-fn/Cargo.toml
  frame/staking/reward-fn/src/lib.rs
  frame/staking/reward-fn/tests/test.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi, D9-needsaudit👮

#8402 Make on-chain curve work for no_std
  frame/staking/reward-fn/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D1-trivial, D2-breaksapi

#8406 Flush stream after we try to send data - always (for rococo)
  Cargo.lock
  client/network/src/protocol/generic_proto/handler.rs
Labels: A0-pleasereview

#8113 Decouple Staking and Election - Part 2.1: Unleash Multi Phase
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/election-provider-support/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/Cargo.toml
  frame/staking/fuzzer/.gitignore
  frame/staking/fuzzer/Cargo.lock
  frame/staking/fuzzer/Cargo.toml
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, C7-high, D0-transaction-version, D1-runtime-migration, D2-breaksapi, D9-needsaudit👮

#8407 Implement PartialEq for DispatchError.
  primitives/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D1-trivial, D2-breaksapi

#8403 contracts: Use the log crate to output contract generated messages
  frame/contracts/README.md
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-trivial, D2-breaksapi

#8415 Rename GenericProto to Notifications
  client/network/src/protocol.rs
  client/network/src/protocol/notifications.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/protocol/notifications/upgrade.rs
  client/network/src/protocol/notifications/upgrade/collec.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8404 CI: address the bug with .env
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#8417 CI: fix env file location
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#8416 Optimize the peerset a bit
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8422 Refactor NotifsHandler::poll
  client/network/src/protocol/notifications/handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8418 contracts: Update `deduct_block` when a contract is exempted from paying rent
  frame/contracts/src/rent.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#8432 Fix CI for new labels
  .maintain/github/check_labels.sh
  .maintain/gitlab/check_runtime.sh
  docs/CONTRIBUTING.adoc
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8425 Fungibles trait and impl for Assets pallet
  bin/node/runtime/src/lib.rs
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/staking/reward-fn/src/lib.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8397 Improve remote-externalities
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/test_data/proxy_test
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8329 Expose block number in seal_random
  frame/contracts/CHANGELOG.md
  frame/contracts/src/exec.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤, E5-breaksapi

#8305 Add tracing logic in pallet macro for hooks and dispatchables
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/lib.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#8437 Improve doc
  frame/aura/src/lib.rs
  frame/contracts/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/proxy/src/lib.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/sudo/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8359 contracts: Reduce the API surface
  bin/node/cli/src/chain_spec.rs
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/CHANGELOG.md
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤, E5-breaksapi

#8439 grandpa: speed up tests
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  client/network/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8442 Remove outdated comment in pallet asset
  frame/assets/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#7665 test runner
  Cargo.lock
  Cargo.toml
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  client/executor/src/native_executor.rs
  frame/babe/src/tests.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/host_functions.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
  test-utils/test-runner/src/utils.rs
Labels: A0-pleasereview, A3-needsresolving, B0-silent, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#8326 Migrate pallet-utility to pallet attribute macro.
  frame/utility/src/benchmarking.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#8412 update README.adoc
  bin/utils/subkey/README.adoc
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8445 Make candidate intake in society configurable
  bin/node/runtime/src/lib.rs
  frame/society/src/lib.rs
  frame/society/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8440 Migrate pallet-vesting to pallet attribute macro.
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8398 Check `unreserve` and `transfer` returnvalues in debug code
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/bounties/src/lib.rs
  frame/democracy/src/lib.rs
  frame/identity/src/lib.rs
  frame/lottery/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/society/src/lib.rs
  frame/support/src/storage/generator/mod.rs
  frame/tips/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#8420 Update to libp2p-0.36
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/transport.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/transport.rs
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#8449 Use Debug for genesis mismatch message
  client/network/src/protocol.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8368 Make the number of nominations configurable
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/lib.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/Cargo.toml
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E5-breaksapi

#8450 Fix local variable names conflict in pallet call expansion
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/dispatch.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8455 Remove redundant libp2p dependency from test runner
  Cargo.lock
  test-utils/test-runner/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8452 Upgrade pallet atomic swap
  frame/atomic-swap/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8460 Change companion check order
  .maintain/gitlab/check_polkadot_companion_status.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌, Q2-easy

#8448 Migrate `pallet-sudo` to `pallet!`
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/sudo/src/tests.rs
  frame/support/procedural/src/pallet/expand/call.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8464 Fix companion check
  .maintain/gitlab/check_polkadot_companion_status.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8467 Add NetworkService::add_known_address
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8468 Fix &mut self -> &self in add_known_address
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8435 Repot frame_support::traits; introduce some new currency stuff
  frame/assets/src/lib.rs
  frame/balances/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/filter.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/members.rs
  frame/support/src/traits/metadata.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/randomness.rs
  frame/support/src/traits/schedule.rs
  frame/support/src/traits/storage.rs
  frame/support/src/traits/stored_map.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/tokens/currency/lockable.rs
  frame/support/src/traits/tokens/currency/reservable.rs
  frame/support/src/traits/tokens/fungible.rs
  frame/support/src/traits/tokens/fungible/balanced.rs
  frame/support/src/traits/tokens/fungible/imbalance.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/support/src/traits/tokens/fungibles/balanced.rs
  frame/support/src/traits/tokens/fungibles/imbalance.rs
  frame/support/src/traits/tokens/imbalance.rs
  frame/support/src/traits/tokens/imbalance/on_unbalanced.rs
  frame/support/src/traits/tokens/imbalance/signed_imbalance.rs
  frame/support/src/traits/tokens/imbalance/split_two_ways.rs
  frame/support/src/traits/tokens/misc.rs
  frame/support/src/traits/validation.rs
  frame/support/src/traits/voting.rs
  frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.stderr
  frame/system/src/lib.rs
  frame/transaction-payment/src/payment.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8461 Use `async_trait` in sc-consensus-slots
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8458 [pallet-staking] Refund unused weight for `payout_stakers`
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8447 make types within `generate_solution_type` macro explicit
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  primitives/npos-elections/compact/Cargo.toml
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/compact/tests/ui/fail/missing_accuracy.rs
  primitives/npos-elections/compact/tests/ui/fail/missing_accuracy.stderr
  primitives/npos-elections/compact/tests/ui/fail/missing_target.rs
  primitives/npos-elections/compact/tests/ui/fail/missing_target.stderr
  primitives/npos-elections/compact/tests/ui/fail/missing_voter.rs
  primitives/npos-elections/compact/tests/ui/fail/missing_voter.stderr
  primitives/npos-elections/compact/tests/ui/fail/no_annotations.rs
  primitives/npos-elections/compact/tests/ui/fail/no_annotations.stderr
  primitives/npos-elections/compact/tests/ui/fail/swap_voter_target.rs
  primitives/npos-elections/compact/tests/ui/fail/swap_voter_target.stderr
  primitives/npos-elections/fuzzer/src/compact.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8454 Implement `fungible::*` for Balances
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/assets/src/extra_mutator.rs
  frame/assets/src/functions.rs
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/impl_stored_map.rs
  frame/assets/src/lib.rs
  frame/assets/src/mock.rs
  frame/assets/src/tests.rs
  frame/assets/src/types.rs
  frame/balances/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/tokens/fungible.rs
  frame/support/src/traits/tokens/fungible/balanced.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/support/src/traits/tokens/fungibles/balanced.rs
  frame/support/src/traits/tokens/misc.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8463 Bring back the on_finalize weight of staking.
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8480 Use pathbuf for remote externalities
  Cargo.lock
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8301 Benchmarking pallet-example
  Cargo.lock
  frame/elections-phragmen/src/lib.rs
  frame/example/Cargo.toml
  frame/example/src/benchmarking.rs
  frame/example/src/lib.rs
  frame/example/src/tests.rs
  frame/example/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤, E5-breaksapi

#8474 Prepare UI tests for Rust 1.51 & new CI image
  frame/support/test/tests/construct_runtime_ui/missing_system_module.stderr
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  frame/support/test/tests/pallet_ui/hooks_invalid_item.stderr
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8065 Add Social Network
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8473 Enhancement on Substrate Node Template
  .maintain/node-template-release.sh
  .maintain/node-template-release/Cargo.toml
  Cargo.lock
  bin/node-template/.editorconfig
  bin/node-template/README.md
  bin/node-template/docker-compose.yml
  bin/node-template/docs/rust-setup.md
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node-template/scripts/docker_run.sh
  bin/node-template/scripts/init.sh
  docs/node-template-release.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8486 Get rid of `test-helpers` feature in sc-consensus-babe
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8489 client: fix justifications migration
  client/db/src/lib.rs
  client/db/src/upgrade.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8497 Fix sync restart for peers that provide block justifications
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8495 Duplicate logging to stdout
  client/tracing/src/logging/event_format.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8465 Migrate `pallet-indices` to `pallet!`
  frame/indices/src/benchmarking.rs
  frame/indices/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#8459 Fixed sync skipping some block announcements
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low 📌

#8506 Expose pallet_session::key_owner()
  frame/session/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸
