Repository paritytech/substrate, pull requests merged in 2021-02, with the labels that each got.

#8013 chore: fix typos
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8009 Fix tracing spans are not being forwarded to spawned task
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8017 make AllModules public
  frame/support/procedural/src/construct_runtime/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7895 client/network: Use request response for light client requests
  client/network/src/behaviour.rs
  client/network/src/block_request_handler.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/light_client_handler.rs
  client/network/src/light_client_requests.rs
  client/network/src/light_client_requests/handler.rs
  client/network/src/light_client_requests/sender.rs
  client/network/src/on_demand_layer.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A3-inprogress, B0-silent, C1-low

#8019 relax translate closure to FnMut
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8012 Remove outdated Grafana information
  .maintain/monitoring/grafana-dashboards/README_dashboard.md
  .maintain/monitoring/grafana-dashboards/substrate-dashboard.json
Labels: A2-insubstantial, B0-silent, C1-low

#8014 contracts: Emit event on contract termination
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8022 Fix tracing tests
  client/tracing/src/lib.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8018 contracts: Improve documentation
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8020 Convert AURA to new pallet macro
  frame/aura/Cargo.toml
  frame/aura/src/lib.rs
  frame/aura/src/mock.rs
  frame/aura/src/tests.rs
  primitives/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7127 Decouple the session validators from im-online
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/aura/src/lib.rs
  frame/authority-discovery/src/lib.rs
  frame/babe/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/im-online/Cargo.toml
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/src/historical/mod.rs
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/staking/src/mock.rs
  frame/support/Cargo.toml
  frame/support/src/traits.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B3-apinoteworthy, C1-low, D1-audited👍, D2-breaksapi

#8030 Better formatting for doc comments
  primitives/debug-derive/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8008 Add a send_request function to NetworkService
  client/network/src/behaviour.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B2-breaksapi, B5-clientnoteworthy, C1-low

#7963 Storage chains: serve transactions over IPFS/bitswap
  Cargo.lock
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/cli/src/params/network_params.rs
  client/db/src/lib.rs
  client/db/src/utils.rs
  client/light/src/blockchain.rs
  client/network/Cargo.toml
  client/network/build.rs
  client/network/src/behaviour.rs
  client/network/src/bitswap.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/schema.rs
  client/network/src/schema/bitswap.v1.2.0.proto
  client/network/src/service.rs
  client/service/src/client/client.rs
  primitives/blockchain/src/backend.rs
  primitives/database/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8032 Improve log line
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8034 Export `IfDisconnected` in public module.
  client/network/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8035 frame-system: Index type 'MaybeSerializeDeserialize' bound.
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8003 contracts: Make ChainExtension trait generic over the runtime
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#8023 AURA: Switch to `CurrentSlot` instead of `LastTimestamp`
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  frame/aura/Cargo.toml
  frame/aura/src/lib.rs
  frame/aura/src/migrations.rs
  frame/aura/src/mock.rs
  frame/aura/src/tests.rs
  primitives/consensus/aura/src/inherents.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7935 contracts: Charge rent for code storage
  bin/node/executor/tests/basic.rs
  frame/contracts/README.md
  frame/contracts/fixtures/instantiate_return_code.wat
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7984 Migrate assets pallet to new macros
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#8041 babe, grandpa: cleanup stale equivocation reports
  bin/node/runtime/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8049 move some pallet test to use construct_runtime
  Cargo.lock
  frame/identity/src/tests.rs
  frame/im-online/src/mock.rs
  frame/lottery/Cargo.toml
  frame/lottery/src/mock.rs
  frame/membership/src/lib.rs
  frame/merkle-mountain-range/src/mock.rs
  frame/multisig/src/tests.rs
  frame/nicks/src/lib.rs
  frame/node-authorization/src/lib.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8051 Migrate more pallet tests to construct_runtime
  frame/bounties/src/tests.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8015 Update dependencies for next update
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker/addr_cache.rs
  client/db/Cargo.toml
  client/db/src/storage_cache.rs
  client/executor/Cargo.toml
  client/finality-grandpa-warp-sync/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network/Cargo.toml
  client/network/src/protocol/sync/extra_requests.rs
  client/service/Cargo.toml
  client/telemetry/Cargo.toml
  frame/benchmarking/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/support/Cargo.toml
  primitives/keyring/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/utils/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/build-script-utils/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D2-breaksapi

#8048 transaction-pool: drop unpropagable txs if local node cant author blocks
  bin/node-template/node/src/service.rs
  bin/node/bench/src/txpool.rs
  bin/node/cli/src/service.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/offchain/src/lib.rs
  client/rpc-api/src/author/error.rs
  client/rpc/src/author/tests.rs
  client/service/src/lib.rs
  client/transaction-pool/graph/benches/basics.rs
  client/transaction-pool/graph/src/lib.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/testing/pool.rs
  primitives/transaction-pool/src/error.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D0-patchthis

#8037 Fix some problems with `prove_warp_sync`
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa/src/finality_proof.rs
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low

#8056 CheckSpecVersion reference fix
  frame/example/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8047 contracts: Remove ConfigCache
  bin/node/executor/tests/basic.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8039 Extend SS58 network identifiers
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  ss58-registry.json
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low, D5-nicetohaveaudit⚠️

#8059 Use construct_runtime in tests
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/tests.rs
  frame/example-offchain-worker/src/tests.rs
  frame/example-parallel/Cargo.toml
  frame/example-parallel/src/tests.rs
  frame/example/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/fuzzer/Cargo.toml
  frame/staking/fuzzer/src/mock.rs
  frame/system/benches/bench.rs
  frame/system/benchmarking/src/mock.rs
  frame/system/src/extensions/check_mortality.rs
  frame/system/src/mock.rs
  frame/system/src/offchain.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8068 Remove backwards-compatibility networking hack
  client/finality-grandpa/src/lib.rs
  client/network/src/protocol.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8082 Switch to latest `impl-trait-for-tuples`
  Cargo.lock
  client/chain-spec/Cargo.toml
  frame/authorship/Cargo.toml
  frame/session/Cargo.toml
  frame/session/src/lib.rs
  frame/support/Cargo.toml
  frame/system/Cargo.toml
  frame/timestamp/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/wasm-interface/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8064 Add Crust Network SS58 Address
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#8061 add SS58 address for Ares
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#8080 Replace last usages of `<() as PalletInfo>` in substrate
  frame/collective/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/society/src/mock.rs
  frame/support/src/dispatch.rs
  frame/support/src/event.rs
  frame/support/src/lib.rs
  frame/support/src/metadata.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/src/weights.rs
  frame/support/test/src/lib.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/support/test/tests/storage_transaction.rs
  frame/transaction-payment/src/lib.rs
  frame/utility/src/tests.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8090 Remove PalletInfo impl for ()
  frame/support/src/traits.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#8057 WasmExecutor takes a cache directory
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/src/runtime.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D2-breaksapi

#8050 Add Aventus ss58 address
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A0-pleasereview, B0-silent, C1-low

#8088 sc-network: switch on default features for libp2p on non-wasm-builds
  client/network/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#8091 pallet macro: easier syntax for `#[pallet::pallet]` with `struct Pallet<T>(_)`
  bin/node-template/pallets/template/src/lib.rs
  frame/assets/src/lib.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_ui/hooks_invalid_item.rs
  frame/support/test/tests/pallet_ui/type_value_error_in_block.rs
  frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.rs
  frame/support/test/tests/pallet_ui/type_value_invalid_item.rs
  frame/support/test/tests/pallet_ui/type_value_no_return.rs
  frame/support/test/tests/pallet_version.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#8094 Pallet attribute macro migrate guidelines minor fixes
  frame/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8073 Switch to use `diener patch` for companion build
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low

#7936 Migrate pallet-balances to pallet attribute macro
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#8076 babe, grandpa: set longevity for equivocation report transactions
  bin/node/runtime/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8078 Migrate pallet-timestamp to pallet attribute macro.
  frame/timestamp/src/benchmarking.rs
  frame/timestamp/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#8097 Use log level error to report telemetry
  client/telemetry/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8099 [CI] Move check_labels to github actions
  .github/workflows/check-labels.yml
  .gitlab-ci.yml
  .maintain/common/lib.sh
  .maintain/github/check_labels.sh
  .maintain/gitlab/check_signed.sh
  .maintain/gitlab/generate_changelog.sh
  .maintain/gitlab/publish_draft_release.sh
Labels: A0-pleasereview, B0-silent, C1-low

#8109 Update sc-finality-grandp-warp-sync to 0.9.0 and remove 'publish = false'
  Cargo.lock
  bin/node/cli/Cargo.toml
  client/finality-grandpa-warp-sync/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8079 Remove all code related to sentry nodes
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/pruning_params.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/network/src/behaviour.rs
  client/network/src/block_request_handler.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/protocol/message.rs
  client/network/src/service.rs
  client/rpc-api/src/system/helpers.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8118 Fix Diagram Formatting in Frame System Limits
  frame/system/src/limits.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8114 Simplify runtime api error handling
  bin/node/executor/tests/common.rs
  client/api/src/call_executor.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/pow/src/lib.rs
  client/executor/common/src/error.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/light/src/call_executor.rs
  client/offchain/src/lib.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/error.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/api/test/tests/ui/mock_only_error_associated_type.rs
  primitives/api/test/tests/ui/mock_only_error_associated_type.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.rs
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
  primitives/blockchain/src/error.rs
  primitives/core/src/traits.rs
  primitives/session/src/lib.rs
  primitives/state-machine/src/lib.rs
  test-utils/runtime/client/src/block_builder_ext.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8122 CI: temporarily allow cargo deny to fail
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#8127 Update Grafana dashboards
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A0-pleasereview, B0-silent, C1-low

#8101 grandpa: make the VotingRule API async
  Cargo.lock
  bin/node/runtime/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/voting_rule.rs
  frame/grandpa/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8104 Create a macro which automates creation of benchmark test suites.
  frame/assets/src/benchmarking.rs
  frame/balances/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
  frame/bounties/src/benchmarking.rs
  frame/collective/src/benchmarking.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/democracy/src/benchmarking.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/example/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/im-online/src/benchmarking.rs
  frame/indices/src/benchmarking.rs
  frame/lottery/src/benchmarking.rs
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/multisig/src/benchmarking.rs
  frame/offences/benchmarking/src/lib.rs
  frame/proxy/src/benchmarking.rs
  frame/scheduler/src/benchmarking.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/system/benchmarking/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/tips/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/utility/src/benchmarking.rs
  frame/vesting/src/benchmarking.rs
Labels: A5-grumble, A7-needspolkadotpr, B3-apinoteworthy, C1-low

#8087 Move dust collection hook to outside of account mutate
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8134 fix deprecated usage of panic
  frame/executive/src/lib.rs
  frame/staking/reward-curve/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/core/src/hashing.rs
  primitives/inherents/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8124 Remove inherent in pallet-babe
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/lib.rs
  frame/babe/Cargo.toml
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  primitives/consensus/babe/src/inherents.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low

#8043 Fix telemetry span not entering properly attempt 3
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/cli/tests/telemetry.rs
  bin/node/cli/tests/websocket_server.rs
  client/cli/src/config.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8149 Unbreak browser test CI
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#8116 Benchmark macro: Allow multiple bounds in where
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8152 Make it clear in CLI that paritydb is experimental
  client/cli/src/arg_enums.rs
  client/cli/src/params/database_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#8110 Extract transactions handling from protocol.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/transactions.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8156 Remove `OnSlot` associated type
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8159 Fix warning in rustdoc job
  .gitlab-ci.yml
  client/api/src/in_mem.rs
  client/cli/src/arg_enums.rs
  client/finality-grandpa-warp-sync/src/lib.rs
  frame/system/src/limits.rs
  primitives/state-machine/src/ext.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8142 CI: test and update ci image, codeowners
  .gitlab-ci.yml
  .maintain/flamingfir-deploy.sh
  .maintain/gitlab/check_polkadot_companion_build.sh
  docs/CODEOWNERS
Labels: A0-pleasereview, B0-silent, C1-low

#8038 Migration testing runtime API/Bot
  .gitignore
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/service/src/task_manager/mod.rs
  client/state-db/src/lib.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/support/Cargo.toml
  frame/support/src/traits.rs
  frame/try-runtime/Cargo.toml
  frame/try-runtime/src/lib.rs
  primitives/core/src/hexdisplay.rs
  primitives/state-machine/src/testing.rs
  primitives/storage/src/lib.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/proxy_test
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8155 Ensure we spawn the block import worker as an essential task
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/service/src/task_manager/mod.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/core/src/testing.rs
  primitives/core/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8141 Update to libp2p-0.35.1
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#8086 contracts: Consider contract size in weights
  bin/node/runtime/src/lib.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8125 Allow `transfer_keep_alive` to transfer all free balance
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8138 Migrate examples to use pallet macro
  frame/balances/src/weights.rs
  frame/benchmarking/src/lib.rs
  frame/example-offchain-worker/src/lib.rs
  frame/example-parallel/src/lib.rs
  frame/example-parallel/src/tests.rs
  frame/example/src/lib.rs
  frame/support/src/lib.rs
  frame/system/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8163 Make keystore return `None` when a key doesn't exist
  bin/node/cli/src/service.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/keystore/src/lib.rs
  client/keystore/src/local.rs
  primitives/finality-grandpa/src/lib.rs
  primitives/io/src/lib.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8157 contracts: Convert to framev2 macros
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8170 Fix: stash account reaped when ledger.active == ED
  frame/staking/reward-curve/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  test-utils/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8174 Bump thread_local
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8166 Return number of keys removed when calling `storage_kill` on child trie
  frame/contracts/src/storage.rs
  frame/support/src/storage/child.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/read_only.rs
  primitives/state-machine/src/testing.rs
  primitives/tasks/src/async_externalities.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8177 Make Regex in ss58codec and secret phrase crypto static (#8117)
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7517 Add a Prometheus alert on no incoming connection
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low, Z3-stale

#8182 Bump lru dependency
  Cargo.lock
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  primitives/blockchain/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7909 Decouple Staking and Election - Part 2 Unsigned Phase
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
  frame/babe/Cargo.toml
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/grandpa/Cargo.toml
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/Cargo.toml
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/Cargo.toml
  frame/session/benchmarking/src/mock.rs
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/staking/Cargo.toml
  frame/staking/fuzzer/Cargo.toml
  frame/staking/fuzzer/src/mock.rs
  frame/staking/fuzzer/src/submit_solution.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
  frame/support/src/traits.rs
Labels: A7-needspolkadotpr, B0-silent, C3-medium, D1-audited👍, D2-breaksapi

#8184 Remove suicide from frame_system weights
  frame/system/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8165 Reserve ss58 prefix 48 for Neatcoin
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8188 Make `on_slot` return the block with the post header
  client/consensus/aura/src/lib.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/common/src/block_import.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8112 [multisig, insubstantial] WeightTooLow -> MaxWeightTooLow
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8192 Re-export weights for eleciton.
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8181 Add some debug_asserts for #8171
  client/network/src/transactions.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8198 Display nicer inspect results.
  bin/node/inspect/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8185 Move proof generation to the type system level
  Cargo.lock
  bin/node/bench/src/construct.rs
  bin/node/cli/src/service.rs
  client/basic-authorship/README.md
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/block-builder/Cargo.toml
  client/block-builder/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
  client/consensus/slots/src/lib.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/service/src/client/client.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8148 grandpa: rewrite warp sync proof generation
  Cargo.lock
  bin/node/cli/src/service.rs
  client/finality-grandpa-warp-sync/Cargo.toml
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa-warp-sync/src/proof.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8058 Add ss58 prefix for HydraDX
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#8194 allow to write pre and post runtime upgrade in pallet macro
  bin/node-template/pallets/template/Cargo.toml
  bin/node/runtime/Cargo.toml
  frame/assets/Cargo.toml
  frame/atomic-swap/Cargo.toml
  frame/aura/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/authorship/Cargo.toml
  frame/babe/Cargo.toml
  frame/balances/Cargo.toml
  frame/bounties/Cargo.toml
  frame/collective/Cargo.toml
  frame/contracts/Cargo.toml
  frame/democracy/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/elections/Cargo.toml
  frame/example-offchain-worker/Cargo.toml
  frame/example-parallel/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/identity/Cargo.toml
  frame/im-online/Cargo.toml
  frame/indices/Cargo.toml
  frame/lottery/Cargo.toml
  frame/membership/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/multisig/Cargo.toml
  frame/nicks/Cargo.toml
  frame/node-authorization/Cargo.toml
  frame/offences/Cargo.toml
  frame/proxy/Cargo.toml
  frame/randomness-collective-flip/Cargo.toml
  frame/recovery/Cargo.toml
  frame/scheduler/Cargo.toml
  frame/scored-pool/Cargo.toml
  frame/session/Cargo.toml
  frame/society/Cargo.toml
  frame/staking/Cargo.toml
  frame/sudo/Cargo.toml
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/system/Cargo.toml
  frame/timestamp/Cargo.toml
  frame/tips/Cargo.toml
  frame/transaction-payment/Cargo.toml
  frame/treasury/Cargo.toml
  frame/utility/Cargo.toml
  frame/vesting/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8203 Add an is_finished boolean to the grandpa warp sync response
  client/finality-grandpa-warp-sync/src/proof.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#8200 Fix networking debug_asserts
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low

#8190 pallet macro broke `benchmarks_instance`, fix by introducing `benchmarks_instance_pallet`
  frame/balances/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8206 Frame Benchmarking v3.1.0 released
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/runtime/Cargo.toml
  frame/assets/Cargo.toml
  frame/babe/Cargo.toml
  frame/balances/Cargo.toml
  frame/benchmarking/Cargo.toml
  frame/bounties/Cargo.toml
  frame/collective/Cargo.toml
  frame/contracts/Cargo.toml
  frame/democracy/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/example/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/identity/Cargo.toml
  frame/im-online/Cargo.toml
  frame/indices/Cargo.toml
  frame/lottery/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/multisig/Cargo.toml
  frame/offences/benchmarking/Cargo.toml
  frame/proxy/Cargo.toml
  frame/scheduler/Cargo.toml
  frame/session/benchmarking/Cargo.toml
  frame/staking/Cargo.toml
  frame/system/benchmarking/Cargo.toml
  frame/timestamp/Cargo.toml
  frame/tips/Cargo.toml
  frame/treasury/Cargo.toml
  frame/utility/Cargo.toml
  frame/vesting/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#8178 chore: fix typos for contract
  frame/contracts/src/wasm/runtime.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8212 Fix transactions not being propagated to authorities
  client/network/src/transactions.rs
Labels: A2-insubstantial, B0-silent, C1-low

#8123 Better identifier and logging for runtime upgrades
  Cargo.lock
  bin/node/cli/src/command.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  primitives/storage/src/lib.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/proxy_test
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#8214 Fix ignored error in benchmark tests
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B3-apinoteworthy, C1-low, D2-breaksapi

#8139 Gilts Pallet
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/gilt/Cargo.toml
  frame/gilt/README.md
  frame/gilt/src/benchmarking.rs
  frame/gilt/src/lib.rs
  frame/gilt/src/mock.rs
  frame/gilt/src/tests.rs
  frame/gilt/src/weights.rs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D9-needsaudit👮

#8120 emit event on remark
  frame/system/benchmarking/src/lib.rs
  frame/system/src/lib.rs
  frame/system/src/weights.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, B7-runtimenoteworthy, C1-low, D2-breaksapi

#8186 grandpa: maintain invariants when evaluating aggregated voting rules
  client/finality-grandpa/src/voting_rule.rs
Labels: A0-pleasereview, B0-silent, C1-low
