Repository paritytech/substrate, pull requests merged in 2021-07, with the labels that each got.

#9244 Enable colored help in CLI
  client/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9245 Display Reward amount
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8953 Do not call `initialize_block` before any runtime api
  bin/node-template/runtime/src/lib.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  client/api/src/call_executor.rs
  client/light/src/call_executor.rs
  client/rpc/src/state/tests.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  client/transaction-pool/src/api.rs
  frame/executive/src/lib.rs
  frame/merkle-mountain-range/primitives/src/lib.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/consensus/aura/src/lib.rs
  primitives/offchain/src/lib.rs
  primitives/transaction-pool/src/runtime_api.rs
  primitives/version/src/lib.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9238 Implement `iter_keys` function for all types of storage maps
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9117 Implement `InspectEnumerable` for Uniques
  frame/support/src/traits/tokens/nonfungible.rs
  frame/support/src/traits/tokens/nonfungibles.rs
  frame/uniques/src/impl_nonfungibles.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9222 add simnet tests
  simnet_tests/README.md
  simnet_tests/configs/default_local_testnet.toml
  simnet_tests/run_tests.sh
  simnet_tests/tests/long/002-loadtest.feature
  simnet_tests/tests/quick/001-smoketest.feature
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9259 Mmr RPC
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/src/lib.rs
Labels: A0-pleasereview

#9256 fix prometheus log message terminology
  utils/prometheus/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9260 Fix rpc names for the System RPCs
  client/rpc/src/system/mod.rs
Labels: A0-pleasereview

#9261 Add contracts RPC
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  frame/contracts/rpc/Cargo.toml
  frame/contracts/rpc/src/lib.rs
Labels: A0-pleasereview

#9265 Cleanup service
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview

#9266 Remove RpcHandlers and associated machinery
  bin/node/cli/src/browser.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/test-runner/src/node.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview

#9250 Add `Chilled` event to staking chill extrinsics
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9270 Less duplication in test code
  client/transaction-pool/graph/src/base_pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9246 pallet macro: always generate storage info on pallet struct
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/storage/storage_info.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/lib.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits.rs
  frame/support/src/traits/storage.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9262 Bump linregress due to security vulnerability
  Cargo.lock
  frame/benchmarking/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9263 bump a bunch of deps in parity-common
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/browser-testing/Cargo.toml
  bin/node/browser-testing/src/lib.rs
  bin/node/cli/src/browser.rs
  client/api/Cargo.toml
  client/db/Cargo.toml
  client/informant/Cargo.toml
  client/service/Cargo.toml
  client/state-db/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  frame/support/Cargo.toml
  max-encoded-len/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/core/Cargo.toml
  primitives/database/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/test-primitives/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9278 Remove myself from code owners
  docs/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9279 Authority_discovery: expose assimilate_storage with GenesisBuild
  frame/authority-discovery/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9274 Fix storage info for decl_storage
  frame/support/procedural/src/storage/storage_info.rs
  frame/support/test/tests/decl_storage.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9280 Fix Staking Version in Genesis
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9283 Remove incorrect debug assertion in state-db
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9271 Removed score and compute from set_emergency_election_result
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9277 Add function for embedding the runtime version in a wasm blob
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/src/wasm_runtime.rs
  primitives/version/Cargo.toml
  primitives/version/src/embed.rs
  primitives/version/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9288 build: fix nix shell
  shell.nix
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#9281 change reference module to pallet
  frame/assets/README.md
  frame/assets/src/lib.rs
  frame/aura/README.md
  frame/system/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9289 fix link
  frame/support/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9258 Docs only changes
  client/transaction-pool/README.md
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/watcher.rs
  primitives/transaction-storage-proof/README.md
  primitives/transaction-storage-proof/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9254 Add heiko, parallel to ss58 registry
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9287 clean up staking docs, remove EraElectionStatus references
  frame/staking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#9291 Allow the allocator to track the heap changes.
  client/allocator/Cargo.toml
  client/allocator/src/freeing_bump.rs
  client/executor/wasmtime/src/instance_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9209 move BlockNumberProvider
  frame/system/src/lib.rs
  primitives/runtime/src/offchain/storage_lock.rs
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9100 Paged keys rpc for child storage.
  client/api/src/backend.rs
  client/rpc-api/src/child_state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9069 PVF: NaN canonicalization & deteriministic stack
  Cargo.lock
  client/executor/common/src/runtime_blob/runtime_blob.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/test-guard-page-skip.wat
  client/executor/wasmtime/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9295 Clean up sc-allocator
  Cargo.lock
  client/allocator/Cargo.toml
  client/allocator/src/error.rs
  client/allocator/src/freeing_bump.rs
  client/executor/runtime-test/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9294 Keep current block randomness in state
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9272 [ci] Activate stale bot
  .github/stale.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9305 Update stale.yml to bother about pull-requests only
  .github/stale.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9090 Include `StorageInfo` in Benchmarking Pipeline
  .maintain/frame-weight-template.hbs
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/db/src/bench.rs
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits/storage.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/pallet.rs
  frame/timestamp/src/benchmarking.rs
  primitives/externalities/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/read_only.rs
  primitives/storage/src/lib.rs
  primitives/tasks/src/async_externalities.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/template.hbs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low 📌, D2-breaksapi, D2-notlive 💤

#9168 Ensure data size of identity pallet is bounded
  frame/identity/Cargo.toml
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
  frame/identity/src/types.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9309 make submit_unsigned into DispatchClass::Operational
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9286 Make election benchmarks more *memory-aware*
  bin/node/runtime/src/lib.rs
  client/allocator/src/freeing_bump.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/election-provider-support/src/lib.rs
  frame/staking/src/lib.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D2-notlive 💤

#9322 impl state_getChildReadProof and childstate_getKeysPaged
  client/rpc/src/state/mod.rs
Labels: A0-pleasereview

#9307 Remove impl_outer_ macros
  frame/support/src/dispatch.rs
  frame/support/src/event.rs
  frame/support/src/genesis_config.rs
  frame/support/src/inherent.rs
  frame/support/src/lib.rs
  frame/support/src/origin.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/unsigned.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#9275 Store election snapshot in a more memory-friendly way.
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9302 Update test-runner api
  Cargo.lock
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  client/cli/src/runner.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/host_functions.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
  test-utils/test-runner/src/utils.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9197 Migrate `pallet-treasury` to the new pallet attribute macro
  bin/node/executor/tests/basic.rs
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/tests.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
  frame/treasury/Cargo.toml
  frame/treasury/README.md
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#9323 pallet-collective: Do not vote `aye` with `propose`
  frame/collective/src/benchmarking.rs
  frame/collective/src/lib.rs
  frame/collective/src/weights.rs
  frame/treasury/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9325 Check for duplicate members in genesis of pallet-membership & pallet-collective
  frame/collective/src/lib.rs
  frame/membership/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9314 Fix docs on `generate_storage_alias!`.
  frame/support/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9331 Integrate with mh-start-with-module
  Cargo.lock
  client/rpc-servers/src/lib.rs
Labels: A3-inprogress

#9342 Upgrade remote-externalities to use jsonrpsee v0.3
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#9282 Impl InherentDataProviderExt for more tuples
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9321 Reduce shared state cache contention
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9181 Migrate `pallet-mmr` to the new pallet attribute macro
  frame/merkle-mountain-range/Cargo.toml
  frame/merkle-mountain-range/primitives/Cargo.toml
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/mmr.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/mmr/utils.rs
  frame/merkle-mountain-range/src/mock.rs
  frame/merkle-mountain-range/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#9353 contracts: Fix benchmarks generating too many locals
  frame/contracts/src/benchmarking/code.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9351 Fix invalid link in doc
  client/executor/common/src/runtime_blob/globals_snapshot.rs
  client/executor/wasmtime/src/runtime.rs
  client/network/src/config.rs
  client/network/src/light_client_requests/handler.rs
  client/network/src/light_client_requests/sender.rs
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/lib.rs
  test-utils/test-runner/src/client.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9225 Emit error when Config part is imported but without the std feature
  Cargo.lock
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/procedural/src/dummy_part_checker.rs
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/test/Cargo.toml
  frame/support/test/pallet/Cargo.toml
  frame/support/test/pallet/src/lib.rs
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.rs
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9362 Replace DB assertion with error
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9171 Storage chains sync
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/cli/src/arg_enums.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/lib.rs
  client/light/src/backend.rs
  client/network/src/block_request_handler.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/blocks.rs
  client/network/src/schema/api.v1.proto
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/builder.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9368 Generate storage info for treasury pallet
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9367 Add missing #[pallet::constant] annotations to pallets
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/authorship/src/lib.rs
  frame/balances/src/lib.rs
  frame/democracy/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/gilt/src/lib.rs
  frame/im-online/src/lib.rs
  frame/lottery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/treasury/src/lib.rs
  frame/uniques/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9337 change moonbeam to secp256k1
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9364 Remove the Kubernetes Helm chart
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/README.md
  .maintain/kubernetes/templates/poddisruptionbudget.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/statefulset.yaml
  .maintain/kubernetes/values.yaml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8982 Add a `rustfmt.toml`
  rustfmt.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9384 Remove `IncRefError`, `DecRefError` and `StoredMapError`
  frame/assets/src/impl_stored_map.rs
  frame/assets/src/lib.rs
  frame/balances/src/lib.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/stored_map.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9315 include dispatch result in the Executed event
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#9076 Balance to Asset Balance Conversion
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/assets/src/types.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/fungible/imbalance.rs
  frame/support/src/traits/tokens/fungibles/imbalance.rs
  frame/support/src/traits/tokens/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#9341 CI: fix docs pub
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9399 Fix custom on runtime upgrade not being called
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9328 Suggestions for #9081 (Store voters in unsorted bags)
  bin/node/runtime/voter-bags/src/main.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/mock/voter_bags.rs
  frame/staking/src/tests.rs
  frame/staking/src/voter_bags.rs
Labels: A0-pleasereview, A7-needspolkadotpr

#9406 Run cargo +nightly fmt
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9343 Benchmarking also benchmark for decoding the call
  frame/benchmarking/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/lottery/src/weights.rs
  frame/system/src/weights.rs
  frame/utility/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9412 add CheckedRem
  primitives/arithmetic/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8509 Add Zeitgeist ss58 prefix 73 reservation
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9395 Estimate call fee
  bin/node/runtime/src/lib.rs
  client/network/src/request_responses.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#9416 example typo
  frame/support/procedural/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9400 Staking refactor. Change *_or() to *_or_else()
  frame/staking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9107 State machine local child root cache.
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9427 Clarify Prometheus exporter options
  client/cli/src/commands/run_cmd.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9426 Don't return misleading result with PostInfo in proxy-pallet
  client/network/src/request_responses.rs
  frame/proxy/src/lib.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9429 Simplify returnvalue creation
  frame/proxy/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9173 clippy fixes
  client/chain-spec/derive/src/impls.rs
  frame/staking/reward-curve/src/lib.rs
  frame/staking/reward-curve/src/log.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/utils/src/mpsc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9436 post rustfmt whitespace fixup
  bin/node-template/node/src/command.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/common.rs
  bin/node/runtime/src/lib.rs
  client/cli/src/commands/run_cmd.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/light.rs
  client/executor/runtime-test/src/lib.rs
  client/finality-grandpa/src/lib.rs
  client/network/src/discovery.rs
  client/network/src/request_responses.rs
  client/service/src/client/client.rs
  frame/staking/reward-curve/src/lib.rs
  primitives/npos-elections/src/balancing.rs
  primitives/runtime-interface/test-wasm-deprecated/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9313 Add methods to PrefixIterator to support iterating from a specific key
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9441 More readable CLI help for --sync option
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9443 nix: IDEs like rust-src
  shell.nix
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9444 Update trybuild to get better normalization
  Cargo.lock
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  primitives/api/test/Cargo.toml
  primitives/npos-elections/compact/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9393 Make allocator limit available for the runtime
  client/allocator/src/freeing_bump.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9411 use can_dec_provider to check when transfer allow death
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
Labels: B7-runtimenoteworthy, C3-medium 📣, D9-needsaudit 👮

#9445 Remove invalid and unneeded codec implementation.
  frame/identity/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9165 Move `PalletVersion` away from the crate version
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/migrations/v3.rs
  frame/elections-phragmen/src/migrations/v4.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/migrations.rs
  frame/grandpa/src/migrations/v4.rs
  frame/offences/src/migration.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/pallet_struct.rs
  frame/support/procedural/src/pallet_version.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/migrations.rs
  frame/support/src/traits.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/metadata.rs
  frame/support/test/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_version.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#9410 pallet-staking: Reorg migration, pallet and pallet impls
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9432 Round robin on_idle execution
  frame/support/src/traits/hooks.rs
  frame/support/test/tests/pallet_ui/hooks_invalid_item.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9438 Add nonfungibles::Create Trait & Implement for Uniques
  frame/support/src/traits/tokens/nonfungibles.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9452 Improve `state` related logs to use a more uniform format
  client/api/src/call_executor.rs
  client/light/src/call_executor.rs
  client/light/src/fetcher.rs
  client/light/src/lib.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9456 build: nix-shell: use mozilla/nixpkgs-mozilla repo
  shell.nix
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9457 cargo build --all-features --all-targets should compile
  primitives/npos-elections/benches/phragmen.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9462 Add some important events to batch & staking to ensure ease of analysis
  frame/contracts/src/exec.rs
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  frame/utility/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸
