Repository paritytech/substrate, pull requests merged in 2021-06, with the labels that each got.

#8801 Allow usage of path in construct_runtime!
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/procedural/src/construct_runtime/expand/event.rs
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/construct_runtime/expand/mod.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/construct_runtime_ui/empty_pallet_path.rs
  frame/support/test/tests/construct_runtime_ui/empty_pallet_path.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_details.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8947 Reduce cargo doc warnings
  client/authority-discovery/src/worker.rs
  client/basic-authorship/src/basic_authorship.rs
  client/consensus/common/src/shared_data.rs
  client/consensus/slots/src/lib.rs
  client/network/src/config.rs
  client/network/src/light_client_requests/sender.rs
  client/network/src/service.rs
  frame/contracts/rpc/src/lib.rs
  primitives/npos-elections/compact/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8913 Update wasmtime to 0.27
  Cargo.lock
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#8971 Spellling corrections (no code changes)
  client/rpc-api/src/child_state/mod.rs
  client/service/src/builder.rs
  client/telemetry/src/lib.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  docs/CHANGELOG.md
  docs/Upgrading-2.0-to-3.0.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8973 Dependabot use correct label
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8960 Inject hashed prefix for remote-ext
  frame/system/src/offchain.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D2-notlive 💤

#8958 Use `SpawnTaskHandle`s for spawning tasks in the tx pool
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8980 Do not spend time on verifying the signatures before calling Runtime
  client/executor/wasmtime/src/instance_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8983 Revert "Use `SpawnTaskHandle`s for spawning tasks in the tx pool
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8813 Uniques: An economically-secure basic-featured NFT pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/types/nmap.rs
  frame/uniques/Cargo.toml
  frame/uniques/README.md
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/mock.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/types.rs
  frame/uniques/src/weights.rs
  primitives/arithmetic/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8985 Update WeakBoundedVec's remove and swap_remove
  frame/support/src/storage/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8986 Convert another instance of Into impl to From in the macros
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/src/origin.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8987 Also fix `BoundedVec` remove API
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8995 Transactionpool: Make `ready_at` return earlier
  client/consensus/manual-seal/src/lib.rs
  client/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8806 Discard notifications if we have failed to parse handshake
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8824 Migrate pallet-democracy to pallet attribute macro
  bin/node/runtime/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/decoders.rs
Labels: B0-silent, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8996 Add ecdsa::Pair::verify_prehashed()
  primitives/core/src/ecdsa.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8993 Non-fungible token traits
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/nonfungible.rs
  frame/support/src/traits/tokens/nonfungibles.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/types.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9007 Removes unused import
  frame/democracy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9009 Add Call Filter That Prevents Nested `batch_all`
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/utility/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#8963 Transaction pool: Ensure that we prune transactions properly
  client/transaction-pool/graph/benches/basics.rs
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium 📣

#8970 genesis election provider
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/Cargo.toml
  frame/session/benchmarking/src/mock.rs
  frame/session/src/historical/mod.rs
  frame/session/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D2-notlive 💤

#8624 Storage chain: Runtime module
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/api/src/lib.rs
  client/db/src/lib.rs
  client/light/src/blockchain.rs
  client/service/Cargo.toml
  client/service/src/client/client.rs
  frame/benchmarking/src/lib.rs
  frame/transaction-storage/Cargo.toml
  frame/transaction-storage/README.md
  frame/transaction-storage/src/benchmarking.rs
  frame/transaction-storage/src/lib.rs
  frame/transaction-storage/src/mock.rs
  frame/transaction-storage/src/tests.rs
  frame/transaction-storage/src/weights.rs
  primitives/blockchain/src/backend.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/transaction-storage-proof/Cargo.toml
  primitives/transaction-storage-proof/README.md
  primitives/transaction-storage-proof/src/lib.rs
  primitives/trie/src/storage_proof.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E4-newhostfunctions

#9014 afg: more useful error message
  client/finality-grandpa/src/import.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#7778 Named reserve
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/assets/src/mock.rs
  frame/atomic-swap/src/tests.rs
  frame/babe/src/mock.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/bounties/src/tests.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/example/src/tests.rs
  frame/executive/src/lib.rs
  frame/gilt/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/identity/src/tests.rs
  frame/indices/src/mock.rs
  frame/lottery/src/mock.rs
  frame/multisig/src/tests.rs
  frame/nicks/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/proxy/src/tests.rs
  frame/recovery/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/mock.rs
  frame/support/src/traits.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/tokens/currency/reservable.rs
  frame/tips/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
  frame/uniques/src/mock.rs
  frame/utility/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A3-needsresolving, A3-stale, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E5-breaksapi

#8955 update ss58 type to u16
  bin/node/runtime/src/lib.rs
  frame/system/src/lib.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#9021 Fixed build for some tests
  frame/transaction-storage/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9024 Bump parity-db
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8698 consensus: handle justification sync for blocks authored locally
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
  client/consensus/slots/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9030 arithmetic: fix PerThing pow
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8997 jsonrpsee: register_async_method
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/system/mod.rs
Labels: A0-pleasereview

#8574 Compact proof utilities in sp_trie.
  client/db/src/bench.rs
  primitives/state-machine/src/lib.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/error.rs
  primitives/trie/src/lib.rs
  primitives/trie/src/storage_proof.rs
  primitives/trie/src/trie_codec.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9017 Don't include nominators that back no one in the snapshot.
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9034 jsonrpsee use facade crate
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#9025 Periodically call `Peerset::alloc_slots` on all sets
  client/peerset/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8909 contracts: Add new `seal_call` that offers new features
  Cargo.lock
  frame/contracts/CHANGELOG.md
  frame/contracts/Cargo.toml
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#9042 fix unreserve_all_named
  frame/balances/src/tests.rs
  frame/support/src/traits/tokens/currency/reservable.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9043 Delete legacy runtime metadata macros
  frame/support/src/lib.rs
  frame/support/src/metadata.rs
Labels: A2-insubstantial, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8890 `rpc-http-threads` cli arg
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/rpc-servers/src/lib.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  test-utils/test-runner/src/utils.rs
  utils/browser/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9040 Emit `Bonded` event when rebonding
  frame/staking/src/lib.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9036 deps(jsonrpsee): update to 0.2.0 to avoid alpha
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low 📌

#9041 Small doc updates to `election-provider-multi-phase`
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D2-notlive 💤

#8484 Misc telemetry polish
  client/telemetry/src/lib.rs
  client/telemetry/src/node.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9044 Put the validate_unsigned implementation inside the pallet definition for babe and grandpa
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8990 Use pallet names to name enum variants
  bin/node-template/node/src/chain_spec.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/executor/tests/basic.rs
  bin/node/testing/src/genesis.rs
  frame/assets/src/tests.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/bounties/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/tests.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/example/src/tests.rs
  frame/offences/src/tests.rs
  frame/staking/src/mock.rs
  frame/sudo/src/tests.rs
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/procedural/src/construct_runtime/expand/event.rs
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/tips/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-storage/src/mock.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9026 Stop sending network_state to telemetry
  client/service/src/metrics.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#8946 READY Update simnet tests to v5
  .gitlab-ci.yml
  .maintain/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9053 Make pallet::event respect clippy
  frame/support/procedural/src/pallet/expand/event.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8859 [jsonrpsee] State subscriptions
  client/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8966 [try-runtime-cli] Offchain worker support
  Cargo.lock
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/executor/tests/basic.rs
  frame/executive/src/lib.rs
  primitives/state-machine/src/testing.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/lib.rs
  utils/frame/try-runtime/cli/src/parse.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9065 [rpc]: fix nit in system_properties
  client/rpc/src/system/mod.rs
Labels: A0-pleasereview

#9073 bump jsonrpsee
  Cargo.lock
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/offchain/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/system/mod.rs
Labels: A0-pleasereview

#8943 Migrate ProfilingLayer to tracing registry API
  Cargo.lock
  client/executor/Cargo.toml
  client/tracing/Cargo.toml
  client/tracing/src/block/mod.rs
  client/tracing/src/lib.rs
  client/tracing/src/logging/mod.rs
  primitives/tracing/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9075 grandpa: ignore justifications from other consensus engines
  client/finality-grandpa/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9020 Don't connect to reserved nodes if they're banned
  client/peerset/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9082 Try fix ui tests
  frame/support/test/Cargo.toml
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  primitives/api/proc-macro/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
  primitives/npos-elections/compact/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9018 Implement `transfer_all` in Balances Pallet
  frame/balances/src/benchmarking.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#9074 Transaction pool: Remove futures-diagnose and thread pool
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9083 Migrate pallet-staking to pallet attribute macro
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#9049 pallet-offences: Switch to partition_point
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9084 disable unused schnorrkel feature
  Cargo.lock
  primitives/core/Cargo.toml
  primitives/keystore/Cargo.toml
  primitives/keystore/src/vrf.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9078 Make All FRAME Extrinsics Public
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/balances/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/example/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/identity/src/lib.rs
  frame/indices/src/lib.rs
  frame/lottery/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/proxy/src/lib.rs
  frame/recovery/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/sudo/src/lib.rs
  frame/support/src/lib.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/transaction-storage/src/lib.rs
  frame/uniques/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9059 Fixes in Assets Pallet
  bin/node/runtime/src/lib.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/assets/src/weights.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D1-audited 👍

#8819 im-online: send heartbeats at a random period
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/support/src/traits/validation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9028 Adds moonbeam, moonriver to ss58 registry
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9050 Allow additional trait bounds for `#[pallet::constant]`
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/test/tests/pallet_ui.rs
  frame/support/test/tests/pallet_ui/pass/trait_constant_valid_bounds.rs
  frame/support/test/tests/pallet_ui/trait_constant_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/trait_constant_invalid_bound_lifetime.rs
  frame/support/test/tests/pallet_ui/trait_constant_invalid_bound_lifetime.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9062 remove Default from AssetId trait bound
  frame/support/src/traits/tokens/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9093 Add function to test whether function is exported in wasm blob
  client/executor/common/src/runtime_blob/runtime_blob.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9094 Make find_proxy public.
  frame/proxy/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#9095 pallet-authorship: Fixing some nitpicks
  frame/authorship/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9063 fix ordering of `get_npos_voters` weight arguments
  frame/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9016 Allow renaming storage item prefixes
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/duplicate_storage_prefix.rs
  frame/support/test/tests/pallet_ui/duplicate_storage_prefix.stderr
  frame/support/test/tests/pallet_ui/storage_invalid_attribute.rs
  frame/support/test/tests/pallet_ui/storage_invalid_attribute.stderr
  frame/support/test/tests/pallet_ui/storage_invalid_rename_value.rs
  frame/support/test/tests/pallet_ui/storage_invalid_rename_value.stderr
  frame/support/test/tests/pallet_ui/storage_multiple_getters.rs
  frame/support/test/tests/pallet_ui/storage_multiple_getters.stderr
  frame/support/test/tests/pallet_ui/storage_multiple_renames.rs
  frame/support/test/tests/pallet_ui/storage_multiple_renames.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9061 Migrate pallet-randomness-collective-flip to pallet attribute macro
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/src/tests.rs
  frame/randomness-collective-flip/Cargo.toml
  frame/randomness-collective-flip/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9096 Improve construct_runtime doc
  frame/support/procedural/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8912 staking/election: prolonged era and emergency mode for governance submission.
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/Cargo.toml
  frame/session/benchmarking/src/mock.rs
  frame/session/src/historical/mod.rs
  frame/session/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D9-needsaudit 👮

#9108 Improve variable name
  frame/staking/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9104 Execute system integrity_test
  frame/support/procedural/src/construct_runtime/mod.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8998 Decommit instance memory after a runtime call on Linux
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/common/src/wasm_runtime.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/linux.rs
  client/executor/src/integration_tests/linux/smaps.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#9011 Test restoring zeroed data
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9106 Frame `remove_all` with size limit.
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/executor/runtime-test/src/lib.rs
  client/light/src/backend.rs
  frame/contracts/src/storage.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/im-online/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/slashing.rs
  frame/staking/src/testing_utils.rs
  frame/support/src/lib.rs
  frame/support/src/storage/child.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/migration.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/unhashed.rs
  frame/system/src/lib.rs
  frame/uniques/src/lib.rs
  primitives/externalities/src/lib.rs
  primitives/io/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/read_only.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/tasks/src/async_externalities.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-breaksapi, D3-trivial 🧸, E5-breaksapi

#9114 fix: CARGO_TARGET_DIR_freeze
  utils/wasm-builder/src/prerequisites.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8949 Emit error when construct_runtime imports a non-existent pallet part
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/aura/src/mock.rs
  frame/authority-discovery/src/lib.rs
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/contracts/src/tests.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/mock.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/procedural/src/construct_runtime/expand/event.rs
  frame/support/procedural/src/construct_runtime/expand/inherent.rs
  frame/support/procedural/src/construct_runtime/expand/mod.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/procedural/src/construct_runtime/expand/unsigned.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/dummy_part_checker.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/procedural/src/pallet/expand/inherent.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/procedural/src/pallet/expand/origin.rs
  frame/support/procedural/src/pallet/expand/validate_unsigned.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/construct_runtime_ui/undefined_call_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_call_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8920 Add Control to Growth of the Staking Pallet
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D9-needsaudit 👮, E1-runtimemigration

#9122 Do not run pallet_ui test with conditional-storage feature
  frame/support/test/tests/pallet_ui.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9127 grandpa: cleanup sync bounds
  Cargo.lock
  client/finality-grandpa-warp-sync/Cargo.toml
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  client/finality-grandpa/src/voting_rule.rs
  frame/grandpa/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#9088 Migrate pallet-elections to pallet attribute macro
  frame/elections/src/lib.rs
  frame/elections/src/mock.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9126 Make New Staking Counter Backwards Compatible with CountedMap
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9124 Avoid running some test 2 times when unneeded
  .gitlab-ci.yml
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet_ui.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9132 Aura: Skip initialize block & remove cache
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  primitives/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9019 Make it possible to override maximum payload of RPC
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/executor/src/native_executor.rs
  client/rpc-servers/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  client/tracing/src/block/mod.rs
  test-utils/test-runner/src/utils.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#9136 fix build for jsonrpsee http client
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr

#9102 double the allocator limit
  primitives/allocator/src/freeing_bump.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8933 Use a better data structure for SignedSubmissions instead of Vec
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  primitives/npos-elections/compact/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9139 [rpc]: port light client subscriptions
  Cargo.lock
  bin/node/cli/src/service.rs
  client/rpc-api/src/chain/error.rs
  client/rpc-api/src/state/error.rs
  client/rpc/Cargo.toml
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/chain_light.rs
  client/rpc/src/chain/helpers.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview

#9141 feat: add http server
  Cargo.lock
  client/service/src/lib.rs
Labels: A0-pleasereview

#9142 cli: update to tokio 1
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/runner.rs
  client/rpc/Cargo.toml
  test-utils/Cargo.toml
  test-utils/test-runner/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
Labels: A0-pleasereview

#9143 [rpc servers crate]: move jsonrpsee servers from service
  Cargo.lock
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview

#9131 grandpa: restrict grandpa gossip
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/environment.rs
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9145 babe: add comments to block weight and expose block_weight function
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  primitives/consensus/babe/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9138 slots: slot lenience must take into account block proposal portion
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9128 make SelectChain async
  Cargo.lock
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/longest_chain.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/slots.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/network/test/src/lib.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  primitives/api/test/Cargo.toml
  primitives/api/test/tests/runtime_calls.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/select_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9148 New Weights for All Pallets
  frame/assets/src/weights.rs
  frame/balances/src/weights.rs
  frame/bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/proxy/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9157 fix some failing ui tests
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  max-encoded-len/tests/max_encoded_len_ui/union.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9159 add aliases to match the old RPC API
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/mod.rs
Labels: A0-pleasereview, A7-needspolkadotpr

#9154 grandpa: don't use block_on in Environment::report_equivocation
  client/finality-grandpa/src/environment.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9153 add helper for block_at
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8884 Fast sync
  Cargo.lock
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/api/src/lib.rs
  client/api/src/proof_provider.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/src/arg_enums.rs
  client/cli/src/params/network_params.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/worker.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/light.rs
  client/db/src/storage_cache.rs
  client/db/src/utils.rs
  client/finality-grandpa/src/import.rs
  client/informant/src/display.rs
  client/light/src/backend.rs
  client/network/src/behaviour.rs
  client/network/src/chain.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/state.rs
  client/network/src/schema/api.v1.proto
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/state_request_handler.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  primitives/blockchain/src/backend.rs
  primitives/blockchain/src/error.rs
  primitives/consensus/common/src/block_import.rs
  primitives/consensus/common/src/import_queue.rs
  primitives/consensus/common/src/import_queue/basic_queue.rs
  primitives/consensus/common/src/lib.rs
  primitives/runtime/src/generic/block.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9167 Fix allocator waste assessment in docs
  primitives/allocator/src/freeing_bump.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#9156 Add dummy Debug instance to authority discovery service.
  client/authority-discovery/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9172 Add `substrate-rpc-subscription` to exceptions in alert
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9077 try-runtime-cli: Add execute-block subcommand
  Cargo.lock
  frame/election-provider-multi-phase/src/lib.rs
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9178 consensus: remove offline tracker
  primitives/consensus/common/src/lib.rs
  primitives/consensus/common/src/offline_tracker.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9179 grandpa: fix broken line breaks in logging
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#8623 Add PolkaFoundry, PolkaSmith SS58 address
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, BD0-await-business-review, C1-low 📌, D3-trivial 🧸

#9149 Remove Unused `AccountIndex`
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9161 node-template: remove redundant types from runtime
  bin/node-template/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9184 Fix typo
  frame/support/procedural/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9182 Fixed typo in comment
  frame/uniques/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9176 Less slices
  client/executor/common/src/sandbox.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/generic/mod.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/changes_trie/build.rs
  primitives/state-machine/src/changes_trie/prune.rs
  primitives/state-machine/src/ext.rs
  primitives/trie/src/lib.rs
  primitives/trie/src/node_codec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9119 Result<Option<>> rather than Option<Option<>>
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/example-offchain-worker/src/lib.rs
  frame/im-online/src/lib.rs
  frame/session/src/historical/offchain.rs
  primitives/runtime/src/offchain/storage.rs
  primitives/runtime/src/offchain/storage_lock.rs
  primitives/trie/Cargo.toml
Labels: A0-pleasereview, A6-mustntgrumble, B7-runtimenoteworthy, C1-low 📌, D2-breaksapi, D5-nicetohaveaudit ⚠️

#9150 Fix alert about delay between best and finalized block
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9103 Add extra RPC modules (grandpa)
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/node.rs
Labels: A3-inprogress

#9056 Transaction Pool docs
  .editorconfig
  client/transaction-pool/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9188 Fix to support u32::MAX
  primitives/runtime/src/random_number_generator.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9196 Use MAX associated const
  bin/node/runtime/src/impls.rs
  client/consensus/aura/src/lib.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/informant/src/display.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
  client/network/src/service/tests.rs
  client/peerset/src/peersstate.rs
  client/peerset/tests/fuzz.rs
  client/rpc/src/chain/mod.rs
  client/service/src/chain_ops/import_blocks.rs
  client/service/test/src/client/mod.rs
  client/transaction-pool/graph/src/ready.rs
  frame/assets/src/tests.rs
  frame/babe/src/mock.rs
  frame/balances/src/tests.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/wasm/runtime.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/tests/decoders.rs
  frame/democracy/src/tests/preimage.rs
  frame/democracy/src/tests/public_proposals.rs
  frame/example/src/tests.rs
  frame/grandpa/src/mock.rs
  frame/staking/reward-curve/src/lib.rs
  frame/staking/reward-curve/src/log.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/support/src/traits/voting.rs
  frame/support/src/weights.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
  primitives/allocator/src/freeing_bump.rs
  primitives/arithmetic/fuzzer/src/multiply_by_rational.rs
  primitives/arithmetic/src/biguint.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/rational.rs
  primitives/core/src/hash.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/uint.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/tests.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime/src/curve.rs
  primitives/runtime/src/generic/era.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/random_number_generator.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9067 Add OriginTrail Parachain to SS58 Registry
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9198 Remove RandomNumberGenerator
  primitives/runtime/src/lib.rs
  primitives/runtime/src/random_number_generator.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9199 Use MIN associated const
  client/network/src/protocol/sync.rs
  client/network/src/state_request_handler.rs
  client/peerset/src/lib.rs
  client/peerset/tests/fuzz.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9087 Migrate `pallet-transaction-payment` to new pallet attribute macro
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/executive/src/lib.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/README.md
  frame/transaction-payment/rpc/Cargo.toml
  frame/transaction-payment/rpc/README.md
  frame/transaction-payment/rpc/runtime-api/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/README.md
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-payment/src/payment.rs
  frame/transaction-payment/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8976 contracts: Remove weight pre charging
  frame/contracts/CHANGELOG.md
  frame/contracts/fixtures/dummy.wat
  frame/contracts/fixtures/instantiate_return_code.wat
  frame/contracts/fixtures/ok_trap_revert.wat
  frame/contracts/fixtures/restoration.wat
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#9200 add functionality to stop the jsonrpc servers
  Cargo.lock
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#9147 Support NMap in generate_storage_alias
  frame/support/src/lib.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/types/key.rs
  frame/support/src/storage/types/nmap.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#7910 Decouple Staking and Election - Part 3: Signed Phase
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  primitives/npos-elections/compact/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D9-needsaudit 👮

#9205 change balance pallet reference link
  frame/balances/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9215 move set_emergency_election_result before submit
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9193 Improve Staking Limits
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C3-medium 📣, D9-needsaudit 👮

#9219 Add public accessor for tip amount
  frame/transaction-payment/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9224 Change reference trait to config
  frame/assets/README.md
  frame/atomic-swap/README.md
  frame/aura/README.md
  frame/democracy/README.md
  frame/elections-phragmen/README.md
  frame/example/README.md
  frame/identity/README.md
  frame/im-online/README.md
  frame/multisig/README.md
  frame/nicks/README.md
  frame/proxy/README.md
  frame/recovery/README.md
  frame/scheduler/README.md
  frame/scored-pool/README.md
  frame/session/README.md
  frame/society/README.md
  frame/staking/README.md
  frame/sudo/README.md
  frame/system/README.md
  frame/timestamp/README.md
  frame/utility/README.md
  frame/vesting/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9217 Remove `txpool` as an export of `sc_transaction_pool`, exporting the used components instead.
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/testing/pool.rs
Labels: A0-pleasereview, A2-insubstantial, A7-needspolkadotpr, B5-clientnoteworthy, C1-low 📌

#9190 SyncState RPCs
  Cargo.lock
  bin/node-template/node/src/rpc.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/rpc/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  client/sync-state-rpc/src/lib.rs
  frame/transaction-payment/rpc/Cargo.toml
  frame/transaction-payment/rpc/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#9231 [jsonrpsee] kill jsonrpc in rpc-api
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/rpc.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/src/lib.rs
  client/rpc-api/Cargo.toml
  client/rpc-api/src/author/error.rs
  client/rpc-api/src/author/mod.rs
  client/rpc-api/src/chain/error.rs
  client/rpc-api/src/chain/mod.rs
  client/rpc-api/src/child_state/mod.rs
  client/rpc-api/src/errors.rs
  client/rpc-api/src/helpers.rs
  client/rpc-api/src/lib.rs
  client/rpc-api/src/metadata.rs
  client/rpc-api/src/offchain/error.rs
  client/rpc-api/src/offchain/mod.rs
  client/rpc-api/src/policy.rs
  client/rpc-api/src/state/error.rs
  client/rpc-api/src/state/mod.rs
  client/rpc-api/src/system/error.rs
  client/rpc-api/src/system/mod.rs
  client/rpc/src/lib.rs
  client/rpc/src/system/mod.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/lib.rs
  test-utils/test-runner/src/node.rs
  utils/frame/rpc/support/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview

#9232 Wire up SyncState and TransactionPayment RPCs
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
Labels: A0-pleasereview

#9123 Prep for Altair - Add ss58 prefix
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, BD0-await-business-review, C1-low 📌, D3-trivial 🧸

#9234 pallet-vesting: Move `tests` module and create `mock` module
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/lib.rs
  frame/vesting/src/mock.rs
  frame/vesting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9241 Make a few things for staking miner
  frame/election-provider-multi-phase/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤
