Repository paritytech/substrate, pull requests merged in 2021-04, with the labels that each got.

#8392 grandpa: always store justification for the latest finalized block
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa-warp-sync/src/proof.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8478 Add ChildTriePrefixIterator and methods
  frame/support/src/storage/migration.rs
  frame/support/src/storage/mod.rs
  frame/tips/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8510 Add a feedback when response is successfully sent
  client/finality-grandpa-warp-sync/src/lib.rs
  client/network/src/block_request_handler.rs
  client/network/src/light_client_requests/handler.rs
  client/network/src/request_responses.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8487 tests for assets pallet
  frame/assets/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8515 Make `SetCode::set_code` return a result
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8514 Another tweak to GrandPa warp sync
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa-warp-sync/src/proof.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8356 update wasmtime to 0.24.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low 📌, E5-breaksapi

#8518 Fixes `storage_hash` caching issue and enables better caching for Cumulus
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌

#8524 Pin jsonrpsee
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8523 Properly declare errors in pallets that use decl_module
  frame/lottery/src/lib.rs
  frame/membership/src/lib.rs
  frame/tips/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8494 Fixed restoring state-db journals on startup
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#8521 Use `log::error!` for bad mandatory
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/system/src/extensions/check_weight.rs
  primitives/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8502 Add nominators option to chain-spec-builder
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/utils/chain-spec-builder/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8492 Adjust number of slots in sync requests channel
  client/network/src/block_request_handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8529 Clean up log levels in sc_network
  client/network/src/light_client_requests/handler.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/service.rs
  client/network/src/transactions.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8528 Add some trivial improvements to primitives runtime
  primitives/runtime/src/curve.rs
  primitives/runtime/src/generic/digest.rs
  primitives/runtime/src/generic/era.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/multiaddress.rs
  primitives/runtime/src/offchain/storage_lock.rs
  primitives/runtime/src/traits.rs
  primitives/runtime/src/transaction_validity.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#8491 add more notes on changing epoch duration
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8535 Revert storage cache optimization
  client/db/src/storage_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8482 Don't report confusing unsupported protocol errors
  client/network/src/service.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8540 Require `FullCodec` on frame_system::Call
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8532 Add `check --features try-runtime` CI job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8538 Fix account ref-counting in session
  frame/session/src/lib.rs
  frame/session/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#8394 Opt-out from fast instance reuse and foundation for other refactorings
  Cargo.lock
  client/executor/common/Cargo.toml
  client/executor/common/src/lib.rs
  client/executor/common/src/runtime_blob/data_segments_snapshot.rs
  client/executor/common/src/runtime_blob/globals_snapshot.rs
  client/executor/common/src/runtime_blob/mod.rs
  client/executor/common/src/runtime_blob/runtime_blob.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview, A1-needsburnin, A7-needspolkadotpr, B0-silent, C1-low 📌

#8548 Bump codec.
  Cargo.lock
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8539 Remove node-runtime dependency from node-rpc.
  Cargo.lock
  bin/node/rpc/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8552 Let's put up monthly pre-release tags
  .github/workflows/monthly-tag.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8554 Fix monthly tags
  .github/workflows/monthly-tag.yml
  .maintain/gitlab/generate_changelog.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8557 Fix monthly tags #2
  .github/workflows/monthly-tag.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8553 Drain blocks on peer disconnect
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8485 Clean test runner up
  Cargo.lock
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
  test-utils/test-runner/src/utils.rs
Labels: A2-insubstantial, A3-needsresolving, A7-needspolkadotpr, B0-silent, C1-low 📌

#8555 Add an INDEX to the Instance trait
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/instances.rs
  frame/support/procedural/src/storage/instance_trait.rs
  frame/support/src/instances.rs
  frame/support/src/traits/storage.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#8549 Support code blobs compressed with zstd
  Cargo.lock
  Cargo.toml
  client/executor/Cargo.toml
  client/executor/src/wasm_runtime.rs
  primitives/maybe-compressed-blob/Cargo.toml
  primitives/maybe-compressed-blob/README.md
  primitives/maybe-compressed-blob/src/lib.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/builder.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#8541 Add more asserts and debug_asserts
  frame/balances/src/benchmarking.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/bounties/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/executive/src/lib.rs
  frame/recovery/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/tests.rs
  frame/tips/src/benchmarking.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8559 Add PoV Tracking to Benchmarking Pipeline
  client/db/src/bench.rs
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  primitives/externalities/src/lib.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#8542 Add DefaultNoBound
  frame/support/procedural/src/default_no_bound.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
  frame/support/test/tests/derive_no_bound.rs
  frame/support/test/tests/derive_no_bound_ui/default.rs
  frame/support/test/tests/derive_no_bound_ui/default.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8560 remove real-overseer from polkadot compilation flags
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8575 Check every minute whether authority-discovery key has changed
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8519 Introduce `node-bench-regression-guard` to Substrate's pipeline
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8576 Allow lossless matching for Origin
  frame/support/src/origin.rs
  frame/support/src/traits/dispatch.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8577 Disallow failure for `node-bench-regression-guard` job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8477 `ModuleId` to `PalletId` - part of #8372
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/lib.rs
  frame/elections/src/mock.rs
  frame/lottery/src/lib.rs
  frame/lottery/src/mock.rs
  frame/society/src/lib.rs
  frame/society/src/mock.rs
  frame/support/src/lib.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
  primitives/runtime/src/lib.rs
  utils/frame/frame-utilities-cli/Cargo.toml
  utils/frame/frame-utilities-cli/src/lib.rs
  utils/frame/frame-utilities-cli/src/pallet_id.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8579 Backing/GetBacking: Abstraction over pluralistic origins for XCM.
  frame/collective/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8572 Add trivial improvements to transaction pool
  client/transaction-pool/graph/src/base_pool.rs
  client/transaction-pool/graph/src/future.rs
  client/transaction-pool/graph/src/listener.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  client/transaction-pool/graph/src/rotator.rs
  client/transaction-pool/graph/src/tracked_map.rs
  client/transaction-pool/graph/src/validated_pool.rs
  client/transaction-pool/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8581 clean arithmetic and unify names with the new api
  Cargo.lock
  bin/node/runtime/src/impls.rs
  frame/contracts/proc-macro/src/lib.rs
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/src/biguint.rs
  primitives/arithmetic/src/fixed_point.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8578 Cap the warp sync proof by size, not by fragments
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa-warp-sync/src/proof.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8571 Benchmark Transfer PoV Size with Increasing Numbers of Users
  frame/balances/src/benchmarking.rs
  frame/balances/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8589 Purify `Contains`, add `IsInVec`, `All` and `SortedMembers`
  frame/democracy/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/membership/src/lib.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/members.rs
  frame/system/src/lib.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#7723 Benchmarks for name service pallet
  frame/name-service/src/benchmarking.rs
Labels: A0-pleasereview, E5-breaksapi

#8594 Fix `parameter_types!` macro
  frame/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8602 Fix buggy string comparison in OCW pallet example
  frame/example-offchain-worker/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8598 #8597 Update features resolver wasm build
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#8606 Pallet macro support `frame_system::Config` with args
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/test/tests/pallet.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8493 WIP: fix Simnet trigger
  .gitlab-ci.yml
  .maintain/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8173 Ensure inherent are first
  Cargo.lock
  frame/authorship/src/lib.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/inherent.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/inherent_check_inner_span.stderr
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/timestamp/src/lib.rs
  primitives/inherents/src/lib.rs
  primitives/runtime/src/testing.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#8591 Fix for #8586 WithdrawReasons type change from i8 to u8
  frame/support/src/traits/tokens/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8587 Change assert(is_err()) to assert_noop to check state consistency on errors
  frame/contracts/src/exec.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/tests/decoders.rs
  frame/democracy/src/tests/external_proposing.rs
  frame/democracy/src/tests/public_proposals.rs
  frame/democracy/src/tests/voting.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8451 contracts: Add RPC that allows instantiating of a contract
  Cargo.lock
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/CHANGELOG.md
  frame/contracts/common/Cargo.toml
  frame/contracts/common/src/lib.rs
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#8580 BoundedVec for AccountLocks
  frame/collective/src/lib.rs
  frame/democracy/src/tests.rs
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8601 expose set_timestamp for runtime benchmarks
  frame/timestamp/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8317 Trim compact solution for length during preparation
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D1-audited 👍, E5-breaksapi

#8616 build: update shell.nix
  shell.nix
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#8261 Add Sora network SS58 Address
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-breaksapi, D3-trivial 🧸

#8609 Make non-validators listen on /ws by default
  client/cli/src/config.rs
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#8618 Increase metric only if actually publishing
  client/authority-discovery/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8599 Fix debug_assertion failing in authority discovery
  client/authority-discovery/src/worker/addr_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8588 Introduce a "dynamic" block size limit for proposing
  bin/node/bench/src/construct.rs
  bin/node/cli/src/service.rs
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/block-builder/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  client/db/src/bench.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/consensus/common/src/evaluation.rs
  primitives/consensus/common/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8534 Properly close notification substreams
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8556 BoundedVec + Shims for Append/DecodeLength
  frame/collective/src/lib.rs
  frame/democracy/src/tests.rs
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/value.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8483 Make pallet Assets instantiable
  frame/assets/src/benchmarking.rs
  frame/assets/src/extra_mutator.rs
  frame/assets/src/functions.rs
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/impl_stored_map.rs
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8628 Remove `serde` requirement from FRAME macros
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node/runtime/Cargo.toml
  frame/assets/Cargo.toml
  frame/atomic-swap/Cargo.toml
  frame/aura/Cargo.toml
  frame/authority-discovery/Cargo.toml
  frame/babe/Cargo.toml
  frame/balances/Cargo.toml
  frame/bounties/Cargo.toml
  frame/collective/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/elections/Cargo.toml
  frame/example-offchain-worker/Cargo.toml
  frame/example/Cargo.toml
  frame/executive/Cargo.toml
  frame/gilt/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/identity/Cargo.toml
  frame/im-online/Cargo.toml
  frame/indices/Cargo.toml
  frame/membership/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/multisig/Cargo.toml
  frame/nicks/Cargo.toml
  frame/node-authorization/Cargo.toml
  frame/proxy/Cargo.toml
  frame/recovery/Cargo.toml
  frame/scheduler/Cargo.toml
  frame/scored-pool/Cargo.toml
  frame/session/Cargo.toml
  frame/society/Cargo.toml
  frame/staking/src/lib.rs
  frame/sudo/Cargo.toml
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/procedural/src/storage/genesis_config/mod.rs
  frame/support/src/genesis_config.rs
  frame/timestamp/Cargo.toml
  frame/treasury/src/lib.rs
  frame/utility/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#8633 CI updates
  .gitlab-ci.yml
  .maintain/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8631 Fix doc and dyn usage
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  primitives/externalities/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8620 Authority Discovery to FRAME v2
  frame/authority-discovery/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8596 Add benchmarks for pallet-membership
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/im-online/src/weights.rs
  frame/membership/Cargo.toml
  frame/membership/src/lib.rs
  frame/membership/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8625 Update to libp2p 0.37
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/utils.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8630 Make pallet macro generate accessor to PalletInfo information on pallet placeholder
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/metadata.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/support/test/tests/system.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#8637 Update dependencies of pallet_contracts
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/common/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/contracts/rpc/runtime-api/Cargo.toml
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/prepare.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8639 client: remove time unit from block time loaded message
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#8642 Enable --no-private-ipv4 by default for live chains
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#8643 Authority-discovery no longer publishes non-global IP addresses
  Cargo.lock
  bin/node/cli/src/service.rs
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#8646 Revert "Properly close notification substreams (#8534)"
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8644 [frame util/remote ext]: update jsonrpsee to 0.2.0-alpha.5
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#8656 contracts: Allow () -> (i32) for backwards compatibility
  frame/contracts/src/wasm/prepare.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8659 Off-chain indexing is independent from workers
  client/cli/src/params/offchain_worker_params.rs
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8647 impl Zero and One for fixed point numbers
  Cargo.lock
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/src/fixed_point.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8044 migrate pallet-elections-phragmen to attribute macros
  Cargo.lock
  bin/node/runtime/Cargo.toml
  frame/elections-phragmen/CHANGELOG.md
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/migrations/mod.rs
  frame/elections-phragmen/src/migrations/v3.rs
  frame/elections-phragmen/src/migrations/v4.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#8655 Use host max log level when initializing the `RuntimeLogger`
  primitives/core/src/lib.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/runtime_logger.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E4-newhostfunctions

#8653 Simplify some Option / Result / ? operator patterns
  .maintain/node-template-release/src/main.rs
  client/api/src/cht.rs
  client/api/src/in_mem.rs
  client/api/src/notifications.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/verification.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/utils.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/light/src/fetcher.rs
  client/offchain/src/api/http.rs
  client/peerset/src/peersstate.rs
  client/rpc/src/state/state_light.rs
  client/service/src/client/client.rs
  client/service/src/lib.rs
  client/state-db/src/noncanonical.rs
  client/telemetry/src/lib.rs
  client/tracing/src/lib.rs
  client/transaction-pool/graph/src/pool.rs
  client/transaction-pool/graph/src/ready.rs
  frame/assets/src/functions.rs
  frame/authorship/src/lib.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/rent.rs
  frame/democracy/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/storage/generator/value.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/consensus/common/src/block_import.rs
  utils/frame/rpc/system/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#8665 Add BoundedVec to Treasury Pallet
  bin/node/runtime/src/lib.rs
  frame/bounties/src/tests.rs
  frame/tips/src/tests.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
  frame/treasury/src/weights.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#8670 Upgrade `cargo_metadata` to 0.13.1
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8675 Introduce macro for building Contains impl based on a match
  frame/support/src/traits/members.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#8676 Update dead link in comment
  frame/staking/src/slashing.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#8266 Support sending and receiving multiple Justifications
  client/network/src/block_request_handler.rs
  client/network/src/light_client_requests/sender.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/blocks.rs
  client/network/src/schema/api.v1.proto
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8585 grandpa-rpc: allow proving finality of blocks from latest authority set
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/finality_proof.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8691 Remove unneeded `Ord` bound from All, Contains supports tuples
  frame/support/src/traits/members.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#8690 Bump `jsonrpsee` to `alpha.6` release
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#8694 [Companion] Update Cargo.toml subkey version, readme to reflect new output
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/README.adoc
  bin/utils/subkey/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E3-dependencies, I5-documentation 📄

#8684 Fix reliance on non-empty NodeInfo::endpoints
  client/network/src/peer_info.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#8674 subkey: display SS58 encoding of public key
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/README.adoc
  bin/utils/subkey/src/lib.rs
  client/cli/src/commands/utils.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸
