Repository paritytech/substrate, pull requests merged in 2021-08, with the labels that each got.

#9373 Refactor Benchmarks for Less Wasm Memory Usage
  .gitlab-ci.yml
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  frame/staking/src/weights.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤, E5-breaksapi

#9227 Warp sync part I
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/runtime/src/lib.rs
  client/cli/src/arg_enums.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/common/src/block_import.rs
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/epochs/src/lib.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/db/src/cache/list_cache.rs
  client/db/src/changes_tries_storage.rs
  client/db/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/warp_proof.rs
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/network/Cargo.toml
  client/network/README.md
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/protocol/sync/warp.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/warp_request_handler.rs
  client/network/test/src/lib.rs
  client/rpc/src/state/tests.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/finality-grandpa/src/lib.rs
  test-utils/runtime/src/lib.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9473 Add rustfmt skip to default frame benchmarking template
  utils/frame/benchmarking-cli/src/template.hbs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9474 CI: stop publishing to crates.io until unleash is fixed
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9308 Limit the maximum number of wasm memory pages a runtime can have
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9461 #9386: copy rustfmt.toml to node-template
  .maintain/node-template-release/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9476 Add a matrix chat badge to the README
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9414 aura, babe: don't allow disabled validators to build blocks
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/aura/src/lib.rs
  frame/aura/src/mock.rs
  frame/aura/src/tests.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/session/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/validation.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9483 Use correct `ExecutionContext` for `check_inherents`
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/service/src/client/client.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9477 Explicitly support memory size changing in between allocations
  client/allocator/src/error.rs
  client/allocator/src/freeing_bump.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9489 Refactor codec implementation for header
  primitives/runtime/src/generic/header.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9487 crate missing dependency when compiled on its own with std
  frame/support/procedural/tools/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9485 Fix benchmarking macro for pallet with instance and where clause
  frame/babe/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/tests_instance.rs
  frame/grandpa/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9492 Removing wasm unused import warnings
  primitives/authorship/src/lib.rs
  primitives/npos-elections/src/assignments.rs
  utils/prometheus/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9491 Decouples light-sync state from chain spec
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  bin/node/rpc/src/lib.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/derive/src/impls.rs
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/extension.rs
  client/chain-spec/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  client/sync-state-rpc/src/lib.rs
  test-utils/test-runner/src/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9501 companion_build: enable runtime-benchmarks feature
  .maintain/gitlab/check_polkadot_companion_build.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9502 Remove pallet-democracy unused errors and events
  frame/democracy/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9494 Implement GetDispatchInfo for ()
  frame/support/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9504 Storage chain fixes + guide
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/network/src/block_request_handler.rs
  frame/transaction-storage/README.md
  primitives/transaction-storage-proof/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9506 Fix error message for private Event enum
  frame/support/procedural/src/pallet/parse/event.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9418 Improve call, and usage in pallet utility
  bin/node/runtime/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/identity/Cargo.toml
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9471 FRAME Weights with Storage Metadata
  .maintain/frame-weight-template.hbs
  client/db/Cargo.toml
  client/db/src/bench.rs
  client/finality-grandpa/Cargo.toml
  client/network/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  frame/assets/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/utils.rs
  frame/bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/proxy/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/Cargo.toml
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9515 Expose UnsafeRpcError
  client/rpc-api/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9512 Support test-runner to submit unsigned_extrinsic
  bin/node/test-runner-example/src/lib.rs
  test-utils/test-runner/src/node.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9518 Ignore `jsonrpc-*` in dependabot
  .github/dependabot.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9519 Clarify how `ApiId` is being generated
  primitives/version/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9508 Fix staking `rebond` weight refund
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9500 DatabaseSource::Auto
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/tempdb.rs
  bin/node/testing/src/bench.rs
  client/cli/src/arg_enums.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/purge_chain_cmd.rs
  client/cli/src/config.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/parity_db.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  primitives/database/src/lib.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/utils.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#9526 Consistently use `I::from(Self::get())` in `parameter_types!`
  frame/support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9528 Remove unused pdqselect dependency from `sc-consensus-babe`
  Cargo.lock
  client/consensus/babe/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9498 Refactor `sc_executor::RuntimeInfo` trait into 2 parts
  bin/node/executor/benches/bench.rs
  client/api/src/call_executor.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/light/src/call_executor.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/client/wasm_override.rs
  client/service/src/client/wasm_substitutes.rs
  client/service/test/src/client/light.rs
  primitives/consensus/common/src/lib.rs
  primitives/version/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9531 Make `UncheckedExtrinsic` encode more readable
  primitives/runtime/src/generic/mod.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9521 Remove dependency on substrate-prometheus-endpoint that is no longer required
  Cargo.lock
  primitives/consensus/common/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9442 Multi-Block Election part 0: preparation and some cleanup.
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/solution-type/Cargo.toml
  primitives/npos-elections/solution-type/src/codec.rs
  primitives/npos-elections/solution-type/src/from_assignment_helpers.rs
  primitives/npos-elections/solution-type/src/index_assignment.rs
  primitives/npos-elections/solution-type/src/lib.rs
  primitives/npos-elections/solution-type/src/single_page.rs
  primitives/npos-elections/solution-type/tests/ui/fail/missing_accuracy.rs
  primitives/npos-elections/solution-type/tests/ui/fail/missing_accuracy.stderr
  primitives/npos-elections/solution-type/tests/ui/fail/missing_target.rs
  primitives/npos-elections/solution-type/tests/ui/fail/missing_target.stderr
  primitives/npos-elections/solution-type/tests/ui/fail/missing_voter.rs
  primitives/npos-elections/solution-type/tests/ui/fail/missing_voter.stderr
  primitives/npos-elections/solution-type/tests/ui/fail/no_annotations.rs
  primitives/npos-elections/solution-type/tests/ui/fail/no_annotations.stderr
  primitives/npos-elections/solution-type/tests/ui/fail/swap_voter_target.rs
  primitives/npos-elections/solution-type/tests/ui/fail/swap_voter_target.stderr
  primitives/npos-elections/solution-type/tests/ui/fail/wrong_page.rs
  primitives/npos-elections/solution-type/tests/ui/fail/wrong_page.stderr
  primitives/npos-elections/src/assignments.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/tests.rs
  primitives/npos-elections/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9544 Improve rust docs for migration::{remove_storage_prefix, take_storage_item}
  frame/support/src/storage/migration.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9550 Stabilize `seal_debug_message`
  frame/contracts/CHANGELOG.md
  frame/contracts/fixtures/debug_message_invalid_utf8.wat
  frame/contracts/fixtures/debug_message_logging_disabled.wat
  frame/contracts/fixtures/debug_message_works.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/support/src/storage/migration.rs
  primitives/npos-elections/solution-type/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#9557 Upgrade hyper to 0.14.11
  Cargo.lock
  Cargo.toml
  client/offchain/Cargo.toml
  client/offchain/src/api/http.rs
  test-utils/Cargo.toml
  utils/prometheus/Cargo.toml
  utils/prometheus/src/lib.rs
  utils/prometheus/src/networking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9554 Fix issue with Light client remote call of validate_transaction
  client/transaction-pool/src/api.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9391 RUSTSEC-2021-0076 bump libsecp256k1
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/executor/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/bitswap.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/ecdsa.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  test-utils/test-runner/src/host_functions.rs
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, E4-newhostfunctions, D3-trivial 🧸

#9562 Simplify `NativeExecutionDispatch` and remove the `native_executor_instance!` macro
  bin/node-template/node/src/service.rs
  bin/node/executor/src/lib.rs
  bin/node/executor/tests/common.rs
  bin/node/test-runner-example/src/lib.rs
  client/executor/src/native_executor.rs
  client/service/test/src/client/mod.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/system.rs
  test-utils/test-runner/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#9571 Fix prometheus after hyper 14 upgrade
  utils/prometheus/Cargo.toml
  utils/prometheus/src/lib.rs
  utils/prometheus/src/networking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9525 Make choosing an executor (native/wasm) an explicit part of service construction
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/src/lib.rs
  bin/node/executor/tests/common.rs
  bin/node/inspect/Cargo.toml
  bin/node/inspect/src/command.rs
  bin/node/test-runner-example/src/lib.rs
  bin/node/testing/src/bench.rs
  bin/node/testing/src/client.rs
  client/consensus/babe/src/tests.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/system.rs
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9573 upgrade simnet tests to v8
  .gitlab-ci.yml
  .maintain/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9569 remove the uselsss weight return type from election provider API
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9517 Custom Benchmark Errors and Override
  frame/benchmarking/src/analysis.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/utils.rs
  frame/collective/src/benchmarking.rs
  frame/democracy/src/benchmarking.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/weights.rs
  frame/im-online/src/benchmarking.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#5920 Integrate Wasmer into Substrate sandbox environment
  .gitlab-ci.yml
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/common/Cargo.toml
  client/executor/common/src/lib.rs
  client/executor/common/src/sandbox.rs
  client/executor/common/src/util.rs
  client/executor/wasmi/Cargo.toml
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/state_holder.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview, B3-apinoteworthy, B5-clientnoteworthy, C1-low 📌

#9582 Do not implement () for Contains
  frame/support/src/traits/members.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9588 Show storage info in the raw benchmark output.
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9599 Change unhandled Kademlia events from warn to debug
  client/network/src/discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9593 Display warning on try-runtime spec_name mismatch
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9539 continue in pow loop instead of returning
  client/consensus/pow/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9603 Remove spurious debug_assert!
  client/service/src/builder.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9202 pallet-vesting: Support multiple, merge-able vesting schedules
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/support/src/traits/tokens/currency/lockable.rs
  frame/vesting/Cargo.toml
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/lib.rs
  frame/vesting/src/migrations.rs
  frame/vesting/src/mock.rs
  frame/vesting/src/tests.rs
  frame/vesting/src/vesting_info.rs
  frame/vesting/src/weights.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C3-medium 📣, D1-audited 👍

#9248 [ss58 prefix 13] rebranding SubstraTEE to integritee
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9614 Fix spelling
  frame/uniques/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, C1-low 📌, D3-trivial 🧸

#9615 Remove useless borrow
  client/executor/common/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9611 Fetch runtime code from storage cache when using proofing backend
  client/api/src/cht.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/light/src/backend.rs
  client/service/src/client/call_executor.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/trie_backend.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9610 Run tests for the wasmer sandbox
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9358 Better RPC prometheus metrics.
  client/rpc-servers/src/lib.rs
  client/rpc-servers/src/middleware.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#9617 Fix `state_subscribeRuntimeVersion` for parachains
  client/rpc/src/state/state_full.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#9546 pallet-proxy: emit events on proxy added.
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9592 Remove dependency on sandboxing host functions
  Cargo.lock
  frame/contracts/src/weights.rs
  primitives/sandbox/Cargo.toml
  primitives/sandbox/embedded_executor.rs
  primitives/sandbox/host_executor.rs
  primitives/sandbox/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#9646 improve decode for UncheckedExtrinsic
  primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9428 Generate storage info for pallet authority_discovery
  bin/node/runtime/src/lib.rs
  frame/authority-discovery/src/lib.rs
  primitives/application-crypto/src/lib.rs
  primitives/consensus/slots/src/lib.rs
Labels: A0-pleasereview, E5-breaksapi, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#9642 Add methods param for RPC `state_traceBlock`
  client/rpc-api/src/state/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/state_light.rs
  client/tracing/src/block/mod.rs
  primitives/rpc/src/tracing.rs
Labels: A8-mergeoncegreen, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9652 Fix compilation issue of `pallet_contracts`
  frame/contracts/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#9649 Fix clippy warnings
  primitives/api/proc-macro/src/decl_runtime_apis.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9653 Fix tracker repeat writes
  client/db/src/bench.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸
