Repository paritytech/substrate, pull requests merged in 2021-10, with the labels that each got.

#9792 Add build with docker section to README
  docs/README.adoc
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9860 Test each benchmark case in own #[test]
  bin/node-template/pallets/template/src/benchmarking.rs
  frame/assets/src/benchmarking.rs
  frame/babe/src/benchmarking.rs
  frame/bags-list/src/benchmarks.rs
  frame/balances/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests_instance.rs
  frame/bounties/src/benchmarking.rs
  frame/collective/src/benchmarking.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/example/src/benchmarking.rs
  frame/gilt/src/benchmarking.rs
  frame/grandpa/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/im-online/src/benchmarking.rs
  frame/indices/src/benchmarking.rs
  frame/lottery/src/benchmarking.rs
  frame/membership/src/lib.rs
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/multisig/src/benchmarking.rs
  frame/offences/benchmarking/src/lib.rs
  frame/proxy/Cargo.toml
  frame/proxy/src/benchmarking.rs
  frame/scheduler/src/benchmarking.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/system/benchmarking/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/tips/src/benchmarking.rs
  frame/transaction-storage/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/uniques/src/benchmarking.rs
  frame/utility/src/benchmarking.rs
  frame/vesting/src/benchmarking.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#9806 Clean up sc-peerset
  client/network/src/config.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/transactions.rs
  client/peerset/Cargo.toml
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9805 Add SS58 prefix for Automata
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9789 Quickly skip invalid transactions during block authorship.
  bin/node/bench/src/construct.rs
  client/basic-authorship/src/basic_authorship.rs
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/graph/Cargo.toml
  client/transaction-pool/src/graph/base_pool.rs
  client/transaction-pool/src/graph/ready.rs
  client/transaction-pool/src/graph/validated_pool.rs
  client/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#9914 Implement core::fmt::Debug for BoundedVec
  frame/support/src/storage/bounded_vec.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9915 Downstream `node-template` pull
  .maintain/node-template-release/Cargo.lock
  bin/node-template/README.md
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/shell.nix
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9919 rm `.maintain` lock
  .gitignore
  .maintain/node-template-release/Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9920 Ensure BeforeBestBlockBy voting rule accounts for base
  client/finality-grandpa/src/voting_rule.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#9694 add clippy to CI
  .cargo/config.toml
  .gitignore
  .gitlab-ci.yml
  client/executor/src/wasm_runtime.rs
  client/network/src/block_request_handler.rs
  client/network/src/state_request_handler.rs
  frame/support/src/traits/metadata.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9927 Small quoting comment fix for heartbeat storage
  frame/im-online/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9926 Do not propagate host RUSTFLAGS when checking for WASM toolchain
  utils/wasm-builder/src/prerequisites.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#9663 Introduce block authorship soft deadline
  Cargo.lock
  client/basic-authorship/src/basic_authorship.rs
  client/service/test/Cargo.toml
  client/service/test/src/client/mod.rs
  primitives/keyring/src/sr25519.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#9808 chore: refresh of the substrate_builder image
  .dockerignore
  .maintain/Dockerfile
  docker/README.md
  docker/build.sh
  docker/substrate_builder.Dockerfile
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9909 Require crypto scheme for `insert-key`
  client/cli/src/commands/insert_key.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9924 Remove incorrect sanity check
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9898 don't read events in elections anymore.
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9931 Improved file not found error message
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9935 Contributor doc tweak
  docs/CONTRIBUTING.adoc
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9933 Speed up timestamp generation when logging
  Cargo.lock
  client/tracing/Cargo.toml
  client/tracing/benches/bench.rs
  client/tracing/src/logging/directives.rs
  client/tracing/src/logging/event_format.rs
  client/tracing/src/logging/fast_local_time.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#9936 Update multiple dependencies
  Cargo.lock
  client/cli/Cargo.toml
  client/network/Cargo.toml
  client/tracing/Cargo.toml
  primitives/core/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9937 Remove `IgnoredIssuance` from metadata constants
  frame/gilt/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#9938 `--dev` implies `--tmp`
  client/cli/src/commands/run_cmd.rs
Labels: A2-insubstantial, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#9946 remove dep on unmaintained difference crate
  Cargo.lock
  bin/node/cli/Cargo.toml
  frame/contracts/Cargo.toml
  frame/support/Cargo.toml
  frame/support/test/Cargo.toml
  primitives/state-machine/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10112 contracts: Fix account counter isn't persisted
  frame/contracts/src/exec.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#9684 Removal of light client from substrate
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/cli/tests/database_role_subdir_migration.rs
  client/light/src/blockchain.rs
  client/light/src/fetcher.rs
  client/light/src/lib.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_light.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/client/light.rs
  client/service/src/client/mod.rs
  client/service/src/lib.rs
  client/service/test/src/client/db.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, C3-medium 📣, D2-breaksapi

#9691 Add Baseline FRAME Benchmarks
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/baseline.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/weights.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10121 pallet-utility: Fix possible mismatch between native/wasm
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10107 Fix query_info and query_fee_details functions for unsigned extrinsics
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#9681 Automatic pallet parts in construct_runtime
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/match_and_insert.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/procedural/src/pallet/expand/tt_default_parts.rs
  frame/support/src/lib.rs
  frame/support/test/compile_pass/Cargo.toml
  frame/support/test/compile_pass/src/lib.rs
  frame/support/test/tests/construct_runtime_ui/both_use_and_excluded_parts.rs
  frame/support/test/tests/construct_runtime_ui/both_use_and_excluded_parts.stderr
  frame/support/test/tests/construct_runtime_ui/duplicate_exclude.rs
  frame/support/test/tests/construct_runtime_ui/duplicate_exclude.stderr
  frame/support/test/tests/construct_runtime_ui/exclude_missspell.rs
  frame/support/test/tests/construct_runtime_ui/exclude_missspell.stderr
  frame/support/test/tests/construct_runtime_ui/exclude_undefined_part.rs
  frame/support/test/tests/construct_runtime_ui/exclude_undefined_part.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_details.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_token_after_module.stderr
  frame/support/test/tests/construct_runtime_ui/old_unsupported_pallet_decl.rs
  frame/support/test/tests/construct_runtime_ui/old_unsupported_pallet_decl.stderr
  frame/support/test/tests/construct_runtime_ui/use_undefined_part.rs
  frame/support/test/tests/construct_runtime_ui/use_undefined_part.stderr
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10087 Offchain-worker: Make it possible to disable http support
  Cargo.lock
  client/api/src/execution_extensions.rs
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/api/http.rs
  client/offchain/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  primitives/core/src/offchain/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#9851 Fuzzer for Pallet Bags List
  Cargo.lock
  Cargo.toml
  frame/bags-list/Cargo.toml
  frame/bags-list/fuzzer/.gitignore
  frame/bags-list/fuzzer/Cargo.toml
  frame/bags-list/fuzzer/src/main.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤
