Repository paritytech/substrate, pull requests merged in 2021-12, with the labels that each got.

#10043 Fix order of hook execution
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10398 Format cargo.toml & upgrade 2021
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  frame/transaction-payment/asset-tx-payment/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10395 Integrate jsonrpsee metrics
  Cargo.lock
  Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc-servers/src/middleware.rs
  client/service/src/lib.rs
Labels: A0-pleasereview

#10307 Make BEEFY payload extensible
  Cargo.lock
  client/beefy/src/gossip.rs
  client/beefy/src/notification.rs
  client/beefy/src/round.rs
  client/beefy/src/worker.rs
  primitives/beefy/Cargo.toml
  primitives/beefy/src/commitment.rs
  primitives/beefy/src/lib.rs
  primitives/beefy/src/witness.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10379 Move EnsureOneOf into the dispatch.rs, make an interface more general
  bin/node/runtime/src/lib.rs
  frame/identity/src/tests.rs
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A1-onice, B0-silent, C1-low 📌, D3-trivial 🧸

#10347 Minimum commission for validators
  frame/staking/src/benchmarking.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍, E6-transactionversion

#10388 Account for transaction priority when enforcing limits
  client/transaction-pool/src/graph/base_pool.rs
  client/transaction-pool/src/graph/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10231 Fix pallet bags list and doc
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/src/benchmarks.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/election-provider-support/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/testing_utils.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10380 wasm-override: Support checking `spec_name`
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  primitives/runtime/src/runtime_string.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10412 Fix cumulus companion checks
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10419 No longer include :code and :heappages in execution proofs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10409 Optimize encoded-size of `SignedCommitment`
  primitives/beefy/src/commitment.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10372 allow try-runtime and `TestExternalities` to report PoV size
  Cargo.lock
  primitives/runtime/Cargo.toml
  primitives/runtime/src/lib.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/testing.rs
  primitives/storage/src/lib.rs
  primitives/trie/src/storage_proof.rs
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/test_data/proxy_test.top
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#10317 Authentication of PeerIds in authority discovery records
  client/authority-discovery/README.md
  client/authority-discovery/build.rs
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/schema/dht-v1.proto
  client/authority-discovery/src/worker/schema/dht-v2.proto
  client/authority-discovery/src/worker/schema/tests.rs
  client/authority-discovery/src/worker/tests.rs
  client/keystore/src/local.rs
  client/network/src/lib.rs
  client/network/src/service.rs
  client/network/src/service/signature.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10425 allow tip value of 1
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10414 Add baseline benchmark for sr25519 verification
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/baseline.rs
  frame/benchmarking/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10428 Minor documentation update for `AuxStore` and `BlockImportParams.auxiliary`
  client/api/src/backend.rs
  client/consensus/common/src/block_import.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10233 Used CountedStorageMap in pallet-staking
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/support/src/storage/types/counted_map.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10082 contracts: Add storage deposits
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/common/Cargo.toml
  frame/contracts/common/src/lib.rs
  frame/contracts/fixtures/destroy_and_transfer.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/fixtures/multi_store.wat
  frame/contracts/fixtures/store.wat
  frame/contracts/rpc/runtime-api/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D2-notlive 💤

#10438 Clean up `pallet-contracts` documentation
  frame/contracts/CHANGELOG.md
  frame/contracts/COMPLEXITY.md
  frame/contracts/README.md
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10444 grandpa: allow authority set hard forks to be forced
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/warp_proof.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10309 Add child-bounties pallet.
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/Cargo.toml
  frame/child-bounties/README.md
  frame/child-bounties/src/benchmarking.rs
  frame/child-bounties/src/lib.rs
  frame/child-bounties/src/tests.rs
  frame/child-bounties/src/weights.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#9829 Add extrinsic to improve position in a bag of bags-list
  frame/bags-list/src/benchmarks.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/mock.rs
  frame/bags-list/src/tests.rs
  frame/bags-list/src/weights.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍, E6-transactionversion

#10413 Introduce CheckNonZeroSender
  bin/node/cli/src/service.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  bin/node/test-runner-example/src/lib.rs
  bin/node/testing/src/keyring.rs
  frame/system/src/extensions/check_non_zero_sender.rs
  frame/system/src/extensions/mod.rs
  frame/system/src/lib.rs
  primitives/runtime/src/transaction_validity.rs
  test-utils/test-runner/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮, E10-client-update-first 👀

#10337 Fixed logic of the storage migration to triple reference counting.
  frame/system/src/lib.rs
  frame/system/src/migrations/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10431 Improve pallet asset doc
  frame/assets/src/types.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#10452 Run contract benchmarks
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#9543 Remove Prometheus metrics prefix
  client/api/src/notifications.rs
  client/authority-discovery/src/worker.rs
  client/beefy/src/metrics.rs
  client/cli/src/commands/run_cmd.rs
  client/consensus/common/src/metrics.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/until_imported.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/protocol.rs
  client/network/src/service/metrics.rs
  client/network/src/service/out_events.rs
  client/network/src/transactions.rs
  client/proposer-metrics/src/lib.rs
  client/rpc-servers/src/lib.rs
  client/rpc-servers/src/middleware.rs
  client/service/src/config.rs
  client/service/src/metrics.rs
  client/service/src/task_manager/mod.rs
  client/transaction-pool/src/metrics.rs
  client/utils/src/metrics.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10455 Rename some missed metrics
  client/proposer-metrics/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10443 Bounties - reset curator deposit when curator unassigns themself.
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D9-needsaudit 👮

#10177 Make wasm runtime cache size configurable
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/cli/src/service.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/common.rs
  bin/node/inspect/src/command.rs
  bin/node/testing/src/bench.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/executor/Cargo.toml
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  client/service/src/config.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/runtime-interface/test/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/system.rs
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/utils.rs
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10457 Prometheus: Use correct chain id
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10460 BEEFY update CODEOWNERS
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10454 Automatically unsubscribe storage listeners when they're dropped (RCP node memory leak fix)
  client/api/src/notifications.rs
Labels: A0-pleasereview, I2-bug 🐜, I7-footprint 👣, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10448 Fix contract instantiation weight
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10119 expose ecdsa_sign_prehashed in sp-io
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, E4-newhostfunctions, D3-trivial 🧸

#10474 Make Preimage WeightInfo public
  frame/preimage/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10470 frame-system weights: Remove `set_changes_trie_config`.
  frame/system/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10464 Beefy: update CODEOWNERS
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10394 Statically register host WASM functions
  Cargo.lock
  client/allocator/Cargo.toml
  client/executor/Cargo.toml
  client/executor/common/Cargo.toml
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/Cargo.toml
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
  frame/benchmarking/Cargo.toml
  primitives/core/Cargo.toml
  primitives/io/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/runtime-interface/src/impls.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/src/pass_by.rs
  primitives/runtime-interface/test-wasm-deprecated/Cargo.toml
  primitives/runtime-interface/test-wasm/Cargo.toml
  primitives/runtime-interface/test/Cargo.toml
  primitives/runtime-interface/test/src/lib.rs
  primitives/sandbox/Cargo.toml
  primitives/tasks/Cargo.toml
  primitives/wasm-interface/Cargo.toml
  primitives/wasm-interface/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/Cargo.toml
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/host_functions.rs
Labels: A0-pleasereview, I6-refactor 🧹, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10471 Prepare code for rust 1.57
  Cargo.lock
  frame/support/test/Cargo.toml
  frame/support/test/tests/derive_no_bound_ui/clone.stderr
  frame/support/test/tests/derive_no_bound_ui/eq.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  frame/support/test/tests/reserved_keyword/on_initialize.stderr
  primitives/api/test/Cargo.toml
  primitives/npos-elections/solution-type/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10482 Remove cargo unleash CI job
  .gitlab-ci.yml
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  frame/support/test/tests/reserved_keyword.rs
  frame/support/test/tests/reserved_keyword/on_initialize.rs
  frame/support/test/tests/reserved_keyword/on_initialize.stderr
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10483 rpc-author: Downgrade the logging level of some logs
  client/rpc/src/author/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10485 Fix update_lock
  frame/assets/src/lib.rs
  frame/balances/src/lib.rs
  frame/session/src/lib.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#10481 Emit `ContractReverted` error when revert flag is set
  frame/contracts/common/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10486 sp-version: Add some more docs.
  primitives/version/Cargo.toml
  primitives/version/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10492 Fix link to grafana dashboard
  .maintain/monitoring/grafana-dashboards/README_dashboard.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#10387 Deny warning when building doc
  .gitlab-ci.yml
  primitives/beefy/src/commitment.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10475 move generics of election trait to associated types
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10488 Async block import params
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10440 Add logger configuration hook
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/executor/src/integration_tests/mod.rs
  client/service/src/config.rs
  client/tracing/src/lib.rs
  client/tracing/src/logging/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10501 Use intra doc in network-gossip
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10506 Remove offchain workers ownership.
  docs/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low 📌

#9940 Add ClassAccount storage to unique pallet
  Cargo.lock
  frame/uniques/Cargo.toml
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/migration.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
Labels: A0-pleasereview, B5-clientnoteworthy, E1-runtimemigration, C1-low 📌, D3-trivial 🧸

#10466 Alter BEEFY primitives to prepare for potential BLS integration
  client/beefy/src/notification.rs
  client/beefy/src/worker.rs
  primitives/beefy/src/commitment.rs
  primitives/beefy/src/lib.rs
  primitives/beefy/src/witness.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10509 SlotDuration: Always fetch the slot duration from the runtime
  Cargo.lock
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  primitives/consensus/aura/src/lib.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/common/src/lib.rs
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10526 contracts: serialize `CodeUploadReturnValue` deposit as hex
  frame/contracts/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10531 Use `exists` host function for child tries
  frame/support/src/storage/child.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10524 add `iter_from` to `CountedMap`
  frame/support/src/storage/types/counted_map.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10521 Customizable ink address
  bin/node/runtime/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#10550 chain-spec: Make chain spec writing deterministic
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10541 Improve SS58 related errors
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10555 Add beefy-gadget-rpc tests
  Cargo.lock
  client/beefy/rpc/Cargo.toml
  client/beefy/rpc/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10545 Make check-dependent-* jobs only be executed in PRs
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10565 Tweak to pallet-nicks
  frame/nicks/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10556 Fix Places where AccountId Uses Default
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10558 node-template README persistent db
  bin/node-template/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10529 Expose Uniques helper functions and DestroyWitness fields
  frame/uniques/src/functions.rs
  frame/uniques/src/types.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸
