Repository paritytech/substrate, pull requests merged in 2021-01, with the labels that each got.

#7813 Remove some unecessary bound in transaction-payment
  frame/transaction-payment/rpc/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7815 Fix ss58check test when executed with other tests
  primitives/core/src/ecdsa.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7816 Cleanup some warnings
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/tests.rs
  client/service/src/client/client.rs
  client/transaction-pool/graph/src/validated_pool.rs
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7548 contracts: Allow runtime authors to define a chain extension
  bin/node/runtime/src/lib.rs
  frame/contracts/fixtures/chain_extension.wat
  frame/contracts/fixtures/set_rent.wat
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7759 *: Update to libp2p v0.33.0
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/test/Cargo.toml
  client/offchain/src/api.rs
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#7740 contracts: Lazy storage removal
  bin/node/runtime/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7823 Fix the upgrade helper provided by decl_storage
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7825 rename HEADER files so that they are consistent with LICENSE filenames
  HEADER-APACHE2
  HEADER-GPL3
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7818 contracts: Prevent contracts from allocating a too large buffer
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7821 Improve error message on where clause on pallet error
  frame/support/procedural/src/pallet/parse/error.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/error_where_clause.rs
  frame/support/test/tests/pallet_ui/error_where_clause.stderr
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7826 Feat sp keystore
  primitives/keystore/src/lib.rs
  primitives/keystore/src/vrf.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7828 minor typo fix
  client/api/src/cht.rs
  client/consensus/aura/src/lib.rs
  client/service/src/client/client.rs
  frame/support/src/weights.rs
  primitives/externalities/src/extensions.rs
  primitives/state-machine/src/changes_trie/build_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7221 Participation Lottery Pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/lottery/Cargo.toml
  frame/lottery/src/benchmarking.rs
  frame/lottery/src/lib.rs
  frame/lottery/src/mock.rs
  frame/lottery/src/tests.rs
  frame/lottery/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7478 client/network: Use request response for block requests
  .maintain/sentry-node/docker-compose.yml
  Cargo.lock
  client/network/src/behaviour.rs
  client/network/src/block_request_handler.rs
  client/network/src/block_requests.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/lib.rs
  client/network/src/light_client_handler.rs
  client/network/src/protocol.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
  client/network/src/service/tests.rs
  client/network/test/Cargo.toml
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A3-inprogress, B0-silent, C1-low

#7822 fix : remove `_{ }` syntax from benchmark macro
  frame/assets/src/benchmarking.rs
  frame/babe/src/benchmarking.rs
  frame/balances/src/benchmarking.rs
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/bounties/src/benchmarking.rs
  frame/collective/src/benchmarking.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/democracy/src/benchmarking.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/example/src/lib.rs
  frame/grandpa/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/im-online/src/benchmarking.rs
  frame/indices/src/benchmarking.rs
  frame/merkle-mountain-range/src/benchmarking.rs
  frame/multisig/src/benchmarking.rs
  frame/offences/benchmarking/src/lib.rs
  frame/proxy/src/benchmarking.rs
  frame/scheduler/src/benchmarking.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/system/benchmarking/src/lib.rs
  frame/timestamp/src/benchmarking.rs
  frame/tips/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/utility/src/benchmarking.rs
  frame/vesting/src/benchmarking.rs
Labels: B7-runtimenoteworthy, C1-low, D2-breaksapi

#7830 Improve spans of pallet macro
  Cargo.lock
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/constants.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/genesis_build.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/expand/store_trait.rs
  frame/support/procedural/src/pallet/expand/type_value.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/procedural/src/pallet/parse/error.rs
  frame/support/procedural/src/pallet/parse/event.rs
  frame/support/procedural/src/pallet/parse/genesis_build.rs
  frame/support/procedural/src/pallet/parse/hooks.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/procedural/src/pallet/parse/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/procedural/src/pallet/parse/type_value.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr
  frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.rs
  frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7837 Fix master build
  frame/lottery/src/benchmarking.rs
  frame/lottery/src/lib.rs
  frame/lottery/src/mock.rs
  frame/lottery/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7829 babe: expose next epoch data
  bin/node/runtime/src/lib.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A7-needspolkadotpr, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7819 contracts: Add configurable per-storage item cost
  bin/node/runtime/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7831 upgrade a few dependencies
  .gitlab-ci.yml
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  client/api/Cargo.toml
  client/basic-authorship/Cargo.toml
  client/chain-spec/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/epochs/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/consensus/pow/Cargo.toml
  client/consensus/slots/Cargo.toml
  client/db/Cargo.toml
  client/executor/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/informant/Cargo.toml
  client/keystore/Cargo.toml
  client/light/Cargo.toml
  client/network/test/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/service/test/Cargo.toml
  client/state-db/Cargo.toml
  client/telemetry/Cargo.toml
  client/tracing/Cargo.toml
  client/transaction-pool/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  frame/aura/Cargo.toml
  frame/authorship/Cargo.toml
  frame/session/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/system/Cargo.toml
  frame/system/benches/bench.rs
  frame/timestamp/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/blockchain/Cargo.toml
  primitives/consensus/common/Cargo.toml
  primitives/core/Cargo.toml
  primitives/database/Cargo.toml
  primitives/inherents/Cargo.toml
  primitives/io/Cargo.toml
  primitives/keystore/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/test-primitives/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/trie/Cargo.toml
  primitives/wasm-interface/Cargo.toml
  test-utils/runtime/Cargo.toml
  test-utils/runtime/transaction-pool/Cargo.toml
  utils/browser/Cargo.toml
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7841 CI: remove squash and fix buildah push
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7838 Fix incorrect use of syn::exports
  Cargo.lock
  client/chain-spec/derive/Cargo.toml
  client/cli/proc-macro/Cargo.toml
  client/executor/Cargo.toml
  client/executor/src/integration_tests/mod.rs
  client/executor/src/integration_tests/sandbox.rs
  frame/staking/reward-curve/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/tools/Cargo.toml
  frame/support/procedural/tools/derive/Cargo.toml
  primitives/api/proc-macro/Cargo.toml
  primitives/debug-derive/Cargo.toml
  primitives/npos-elections/compact/Cargo.toml
  primitives/runtime-interface/proc-macro/Cargo.toml
  test-utils/derive/Cargo.toml
Labels: A2-insubstantial, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7845 Subkey should not import the entire world.
  Cargo.lock
  bin/utils/subkey/Cargo.toml
  bin/utils/subkey/src/lib.rs
  bin/utils/subkey/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7700 Rework priority groups, take 2
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/src/params/network_params.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/light_client_handler.rs
  client/network/src/network_state.rs
  client/network/src/protocol.rs
  client/network/src/protocol/event.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
  client/peerset/tests/fuzz.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7843 Better Handle Dead Accounts in Balances
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/weights.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7834 bump fs-swap
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#7651 UniArts reserve SS58 address id 38
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7854 Update to futures 0.3.9
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  bin/node/cli/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/basic-authorship/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/consensus/slots/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/informant/Cargo.toml
  client/keystore/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/test/Cargo.toml
  client/offchain/Cargo.toml
  client/offchain/src/api/timestamp.rs
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/transaction-pool/graph/Cargo.toml
  primitives/blockchain/Cargo.toml
  primitives/consensus/common/Cargo.toml
  primitives/utils/Cargo.toml
  test-utils/client/Cargo.toml
  test-utils/runtime/client/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#7849 Store dispatch info of calls locally in weight calculation
  frame/multisig/src/lib.rs
  frame/recovery/src/lib.rs
  frame/sudo/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7853 client/network: Re-enable light_client_handler.rs unit tests
  client/network/src/light_client_handler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7851 Fix max log level
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7859 Fix missing network for uniarts
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7847 contracts: Collect rent for the first block during deployment
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7867 Bump cargo-unleash to latest alpha release
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7866 Add Prometheus alerts if unbounded channels are too large
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#7872 babe: initialize next authorities on genesis
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#7877 Update serde and parity-multiaddr, to fix master CI
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#7862 Add ss58 version prefix for CORD (from Dhiway)
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7871 network-gossip: add metric for number of local messages
  Cargo.lock
  client/finality-grandpa/src/communication/mod.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7889 Clean-up pass in network/src/protocol.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7879 contracts: Don't read the previous value when overwriting a storage item
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/weights.rs
  frame/support/src/storage/child.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7848 Fix clear prefix check to avoid erasing child trie roots.
  primitives/state-machine/src/ext.rs
  primitives/storage/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#7887 CI: test and deploy prometheus alerts streamlined
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7892 pallet_authority_discovery: introduce current_authorities and next_authorities methods
  frame/authority-discovery/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7878 make helper error types generics
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  client/cli/src/runner.rs
Labels: A0-pleasereview, B0-silent, B2-breaksapi, C1-low

#7692 Add payment_queryFeeDetails RPC
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-payment/src/types.rs
  primitives/rpc/src/number.rs
Labels: B0-silent, C1-low, D1-audited👍, D2-breaksapi

#7885 contracts: Fix possible overflow in storage size calculation
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7870 contracts: Cap the surcharge reward by the amount of rent that way payed by a contract
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/rent.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7886 Update the Grafana dashboards
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A2-insubstantial, B0-silent, C1-low

#7897 Log target before prefix for more consistent logging
  client/tracing/src/logging.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7900 contracts: Fix failing benchmark test
  frame/contracts/src/benchmarking/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7899 CI: trigger simnet master and wait for status
  .gitlab-ci.yml
  .maintain/chaostest/.eslintignore
  .maintain/chaostest/.eslintrc.json
  .maintain/chaostest/.gitignore
  .maintain/chaostest/README.md
  .maintain/chaostest/bin/run
  .maintain/chaostest/bin/run.cmd
  .maintain/chaostest/package-lock.json
  .maintain/chaostest/package.json
  .maintain/chaostest/src/commands/clean/index.js
  .maintain/chaostest/src/commands/singlenodeheight/index.js
  .maintain/chaostest/src/commands/spawn/index.js
  .maintain/chaostest/src/config/README.md
  .maintain/chaostest/src/config/index.js
  .maintain/chaostest/src/hypervisor/chainApi/api.js
  .maintain/chaostest/src/hypervisor/chainApi/index.js
  .maintain/chaostest/src/hypervisor/deployment/deployment.js
  .maintain/chaostest/src/hypervisor/deployment/index.js
  .maintain/chaostest/src/hypervisor/index.js
  .maintain/chaostest/src/hypervisor/modules/chainApi.js
  .maintain/chaostest/src/hypervisor/modules/k8s.js
  .maintain/chaostest/src/index.js
  .maintain/chaostest/src/utils/exit.js
  .maintain/chaostest/src/utils/index.js
  .maintain/chaostest/src/utils/logger.js
  .maintain/chaostest/src/utils/wait.js
  .maintain/flamingfir-deploy.sh
Labels: A0-pleasereview, B0-silent, C1-low

#7868 Storage chains part 1
  bin/node/testing/src/bench.rs
  client/cli/src/config.rs
  client/cli/src/params/database_params.rs
  client/cli/src/params/pruning_params.rs
  client/db/src/lib.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, B5-clientnoteworthy, C1-low

#7901 tests: fix UI test so we can update CI image
  .maintain/gitlab/check_polkadot_companion_build.sh
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr
  primitives/api/test/tests/ui/mock_only_one_error_type.stderr
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low, D2-breaksapi

#7888 *: Update to libp2p v0.34.0
  Cargo.lock
  bin/node/browser-testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/src/protocol/generic_proto/upgrade/legacy.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  primitives/consensus/common/Cargo.toml
  utils/browser/Cargo.toml
Labels: B0-silent, C1-low

#7904 Fix bad debug_assert
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7905 Fix decl_storage provided template to migrate to `pallet!`
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7863 improve benchmarking error output
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  primitives/runtime/src/runtime_string.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7906 Fix not restoring non-poisoned state
  client/network/src/protocol/generic_proto/behaviour.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7902 Add Test for Variable Components in Benchmarking
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7907 fix cargo fmt
  bin/node-template/pallets/template/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7785 Add ss58 version prefix for Patract/Jupiter (from PatractHubs)
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7363 Introduces account existence providers reference counting
  .maintain/gitlab/check_polkadot_companion_build.sh
  .maintain/gitlab/check_polkadot_companion_status.sh
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  frame/assets/src/lib.rs
  frame/babe/src/mock.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/proxy/src/tests.rs
  frame/recovery/src/lib.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/historical/mod.rs
  frame/session/src/historical/offchain.rs
  frame/session/src/lib.rs
  frame/session/src/mock.rs
  frame/session/src/tests.rs
  frame/staking/fuzzer/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/support/src/traits.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  frame/utility/src/tests.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7912 fix clippy str.clone error
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7916 Allow configuring Yamux window size
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/src/transport.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7908 Decouple Stkaing and Election - Part1: Support traits
  Cargo.lock
  Cargo.toml
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  primitives/election-providers/Cargo.toml
  primitives/election-providers/src/lib.rs
  primitives/election-providers/src/onchain.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/benches/phragmen.rs
  primitives/npos-elections/compact/src/assignment.rs
  primitives/npos-elections/compact/src/lib.rs
  primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
  primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
  primitives/npos-elections/fuzzer/src/reduce.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#7913 Feat suppert procedural
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/procedural/src/pallet/parse/event.rs
  frame/support/procedural/src/pallet/parse/extra_constants.rs
  frame/support/procedural/src/pallet/parse/helper.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/procedural/src/pallet/parse/origin.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/procedural/src/pallet/parse/type_value.rs
  frame/support/procedural/src/pallet_version.rs
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7921 Expose BountyUpdatePeriod.
  frame/bounties/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7918 Add ss58 version prefix for Litentry Network
  primitives/core/src/crypto.rs
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7917 Address review comments of #7916
  client/network/src/config.rs
  client/network/src/transport.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7919 Update details for the Polymesh network
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7923 Update ss58 registry for Robonomics
  ss58-registry.json
Labels: A2-insubstantial, B0-silent, C1-low

#7920 babe: log block and slot number on verification
  client/consensus/babe/src/verification.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7925 Add explicit limits to notifications sizes and adjust yamux buffer size
  client/finality-grandpa/src/lib.rs
  client/network/src/config.rs
  client/network/src/gossip/tests.rs
  client/network/src/protocol.rs
  client/network/src/protocol/generic_proto/behaviour.rs
  client/network/src/protocol/generic_proto/handler.rs
  client/network/src/protocol/generic_proto/tests.rs
  client/network/src/protocol/generic_proto/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/transport.rs
  client/network/test/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#7346 Freeze Assets and Asset Metadata
  bin/node/runtime/src/lib.rs
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/assets/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7931 Increase UnboundedChannelVeryLarge threshold from 5k to 15k
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
Labels: A0-pleasereview, B0-silent, C1-low

#7903 Sync: Propagate block announcement data
  Cargo.lock
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/Cargo.toml
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/network/src/service.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7932 Disable Nagle algorithm
  client/network/src/transport.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7898 Migrate frame-system to pallet attribute macro
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/contracts/src/tests.rs
  frame/executive/src/lib.rs
  frame/session/benchmarking/src/lib.rs
  frame/system/src/extensions/check_mortality.rs
  frame/system/src/extensions/check_nonce.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/lib.rs
  frame/system/src/limits.rs
  frame/system/src/offchain.rs
  frame/system/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B3-apinoteworthy, C1-low, D1-runtime-migration, D2-breaksapi

#7463 Telemetry per node
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/browser-demo/build.sh
  bin/node/cli/src/browser.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  client/cli/Cargo.toml
  client/cli/src/commands/insert_key.rs
  client/cli/src/config.rs
  client/cli/src/error.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/network/Cargo.toml
  client/network/src/network_state.rs
  client/network/src/request_responses.rs
  client/rpc/src/system/mod.rs
  client/rpc/src/system/tests.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/src/task_manager/mod.rs
  client/service/src/task_manager/tests.rs
  client/service/test/src/lib.rs
  client/telemetry/Cargo.toml
  client/telemetry/README.md
  client/telemetry/src/async_record.rs
  client/telemetry/src/endpoints.rs
  client/telemetry/src/layer.rs
  client/telemetry/src/lib.rs
  client/telemetry/src/node.rs
  client/telemetry/src/transport.rs
  client/telemetry/src/worker.rs
  client/telemetry/src/worker/node.rs
  client/tracing/Cargo.toml
  client/tracing/proc-macro/Cargo.toml
  client/tracing/proc-macro/src/lib.rs
  client/tracing/src/lib.rs
  client/tracing/src/logging/directives.rs
  client/tracing/src/logging/event_format.rs
  client/tracing/src/logging/layers/console_log.rs
  client/tracing/src/logging/layers/mod.rs
  client/tracing/src/logging/layers/prefix_layer.rs
  client/tracing/src/logging/mod.rs
  utils/browser/Cargo.toml
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, B2-breaksapi, C3-medium, D2-breaksapi

#7930 Allow validators to block and kick their nominator set.
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi, D5-nicetohaveaudit⚠️

#7040 Fix elections-phragmen and proxy issue
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/collective/src/lib.rs
  frame/elections-phragmen/CHANGELOG.md
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/migrations_3_0_0.rs
  frame/elections-phragmen/src/weights.rs
  frame/support/src/traits.rs
Labels: A1-onice, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low, D0-transaction-version, D1-audited👍, D1-runtime-migration, D2-breaksapi

#7943 .maintain: Replace sentry-node with local-docker-test-network
  .maintain/local-docker-test-network/docker-compose.yml
  .maintain/local-docker-test-network/grafana/provisioning/dashboards/dashboards.yml
  .maintain/local-docker-test-network/grafana/provisioning/datasources/datasource.yml
  .maintain/local-docker-test-network/prometheus/prometheus.yml
Labels: A0-pleasereview, B0-silent, C1-low

#7933 Attempt to remove the `where` bounds in arithmetic.
  frame/staking/src/lib.rs
  frame/staking/src/offchain_election.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/election-providers/src/onchain.rs
  primitives/npos-elections/benches/phragmen.rs
  primitives/npos-elections/src/helpers.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7948 Minor contributor docs update
  docs/CONTRIBUTING.adoc
Labels: A2-insubstantial, B0-silent, C1-low

#7940 Make offchain indexing work
  Cargo.lock
  client/api/src/call_executor.rs
  client/db/src/lib.rs
  client/db/src/offchain.rs
  client/executor/src/integration_tests/mod.rs
  client/light/src/call_executor.rs
  client/offchain/Cargo.toml
  client/offchain/src/lib.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/test/src/client/light.rs
  client/service/test/src/client/mod.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/core/src/offchain/storage.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/testing.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/frame/benchmarking-cli/src/command.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7711 Grandpa warp sync request-response protocol
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  client/finality-grandpa-warp-sync/Cargo.toml
  client/finality-grandpa-warp-sync/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
Labels: A0-pleasereview, A3-inprogress, B0-silent, C1-low

#7339 Cleaner GRANDPA RPC API for proving finality
  bin/node/cli/src/service.rs
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/rpc/src/finality.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low

#7290 Allow transaction for offchain indexing
  client/api/src/backend.rs
  client/db/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/offchain/storage.rs
  primitives/core/src/offchain/testing.rs
  primitives/offchain/src/lib.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/changeset.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/overlayed_changes/offchain.rs
  primitives/state-machine/src/testing.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low, D2-breaksapi

#7961 Enable sync mode for parity-db
  client/db/src/parity_db.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7967 Very minor typo in the docs
  frame/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7969 Remove hidden item `__NonExhaustive` in syn crate
  frame/support/procedural/src/pallet/parse/helper.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7968 Detect conflicting module names in `construct_runtime!`
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/test/tests/construct_runtime_ui/conflicting_module_name.rs
  frame/support/test/tests/construct_runtime_ui/conflicting_module_name.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7922 pallet minor doc improvment
  frame/support/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7950 Make pallets use construct_runtime
  frame/assets/Cargo.toml
  frame/assets/src/lib.rs
  frame/collective/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/inherent.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_compatibility_instance.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_version.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/system/src/lib.rs
  frame/system/src/mocking.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7957 client/network/req-resp: Prevent request id collision
  client/network/src/request_responses.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7974 Use construct_runtime for some more pallet
  Cargo.lock
  frame/atomic-swap/src/tests.rs
  frame/aura/src/mock.rs
  frame/authority-discovery/src/lib.rs
  frame/authorship/Cargo.toml
  frame/authorship/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7975 Migrate some more pallets to construct_runtime
  frame/babe/src/mock.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/indices/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7955 Pallet proc macro doc improvements
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/call_missing_weight.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7977 Refuse to start substrate without providing an explicit chain
  bin/node/cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7958 client/network: Report reputation changes via response
  client/finality-grandpa-warp-sync/src/lib.rs
  client/network/src/behaviour.rs
  client/network/src/block_request_handler.rs
  client/network/src/config.rs
  client/network/src/request_responses.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7981 Migrate pallet-template to pallet attribute macro
  bin/node-template/pallets/template/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7985 Fix Network trait implementation not doing what it's supposed to do
  client/network-gossip/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7986 Make pallet use construct_runtime in tests instead of impl_*
  Cargo.lock
  frame/randomness-collective-flip/Cargo.toml
  frame/randomness-collective-flip/src/lib.rs
  frame/recovery/src/mock.rs
  frame/scheduler/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/session/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/sudo/src/mock.rs
  frame/sudo/src/tests.rs
  frame/timestamp/src/lib.rs
  frame/tips/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
  frame/utility/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7988 Rewrite the async code in `BasicQueue`
  primitives/consensus/common/src/import_queue/basic_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7953 grandpa: remove runtime checks in prove_finality
  bin/node/cli/src/service.rs
  client/finality-grandpa/src/finality_proof.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7982 Ensure transactional with ? works in frame v2
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/storage_transaction.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#7993 Increase maximum size of transaction notifications
  client/network/src/protocol.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7991 Let mock in pallet-template use construct_runtime
  Cargo.lock
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/mock.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7990 Fix state cache for cumulus
  client/db/src/storage_cache.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7891 Merkle Mountain Range pallet improvements
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/merkle-mountain-range/Cargo.toml
  frame/merkle-mountain-range/primitives/Cargo.toml
  frame/merkle-mountain-range/primitives/src/lib.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/mmr.rs
  frame/merkle-mountain-range/src/mmr/mod.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/mock.rs
  frame/merkle-mountain-range/src/tests.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low, D2-breaksapi

#7997 Introduce a `Slot` type
  Cargo.lock
  bin/node/cli/src/service.rs
  bin/node/runtime/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/digests.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/migration.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
  client/consensus/epochs/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/slots/src/aux_schema.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  frame/aura/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
  primitives/consensus/aura/Cargo.toml
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/babe/src/inherents.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/slots/Cargo.toml
  primitives/consensus/slots/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#7941 Clarify and expand ProvideInherent docs
  primitives/inherents/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#7996 Introduce sc_peerset::DropReason
  client/network/src/protocol/generic_proto/behaviour.rs
  client/peerset/src/lib.rs
  client/peerset/tests/fuzz.rs
Labels: A0-pleasereview, B0-silent, C1-low

#7934 Doc fixes for sc-telemetry & API struct rename
  client/cli/src/config.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/task_manager/mod.rs
  client/telemetry/README.md
  client/telemetry/src/endpoints.rs
  client/telemetry/src/layer.rs
  client/telemetry/src/lib.rs
  client/tracing/src/logging/directives.rs
  client/tracing/src/logging/layers/prefix_layer.rs
  client/tracing/src/logging/mod.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#7951 Fix telemetry span not entering properly & enter span in sc-cli
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/cli/src/config.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/task_manager/mod.rs
  client/service/test/src/lib.rs
  client/telemetry/src/lib.rs
  utils/browser/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8002 Test is_inherent_required
  frame/support/src/inherent.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#8006 Sync: Fix issue of not freeing a block announcement slot
  client/network/src/protocol/sync.rs
  client/network/test/src/sync.rs
  primitives/consensus/common/src/block_validation.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low

#8007 CI: return flaming fir deployment
  .gitlab-ci.yml
  .maintain/flamingfir-deploy.sh
Labels: A0-pleasereview, B0-silent, C1-low
