Repository paritytech/substrate, pull requests merged in 2022-03, with the labels that each got.

#10935 Clean up todo items for `extra_constant` renaming.
  frame/transaction-payment/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10953 Update new whitelist pallet to new primitive versions
  frame/whitelist/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10954 sp-trie: Switch to thiserror and some other small cleanups
  Cargo.lock
  primitives/trie/Cargo.toml
  primitives/trie/src/error.rs
  primitives/trie/src/node_codec.rs
  primitives/trie/src/storage_proof.rs
  primitives/trie/src/trie_codec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10670 Only maintain at most 1 `UnlockChunk` per era
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/support/src/storage/bounded_vec.rs
Labels: A8-mergeoncegreen, A7-needspolkadotpr, B0-silent, C1-low 📌, D1-audited 👍

#10958 staking: Expose `MaxUnlockingChunks` in metadata as a const
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10968 Add pr-custom-review config
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10955 Revise how staking configurations are set
  frame/staking/src/benchmarking.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: E5-breaksapi, B0-silent, C1-low 📌, D3-trivial 🧸

#10945 [EPM pallet]: remove `number of signed submissions`
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-multi-phase/src/weights.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#10779 Refactored block body database scheme
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/testing/src/bench.rs
  client/cli/src/config.rs
  client/cli/src/params/database_params.rs
  client/db/src/lib.rs
  client/db/src/parity_db.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10975 Deprecate "paritydb-experimental" CLI in favour or "paritydb"
  client/cli/src/arg_enums.rs
  client/cli/src/config.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10971 [contracts] Stabilize "seal0" `is_contract` and `caller_is_origin`
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#10073 Trie version migration pallet
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/sanity_check.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/state-trie-migration/Cargo.toml
  frame/state-trie-migration/src/lib.rs
  frame/state-trie-migration/src/weights.rs
  frame/support/src/traits/misc.rs
  primitives/core/src/lib.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/storage/src/lib.rs
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#10974 BEEFY and GRANDPA protocol names should use full genesis hash
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10980 Move weight constants to own mod
  frame/support/src/weights.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10940 add block usage logs to system pallet
  frame/system/src/lib.rs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10915 Fix the undeterministic storage proof recorded for the same execution
  client/executor/src/native_executor.rs
  client/offchain/src/api/http.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/trie/src/storage_proof.rs
  primitives/trie/src/trie_stream.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10896 Minor Uniques pallet improvements and XCM v3 preparations
  bin/node/runtime/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/members.rs
  frame/support/src/traits/tokens/nonfungible.rs
  frame/support/src/traits/tokens/nonfungibles.rs
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/mock.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, E6-transactionversion, D3-trivial 🧸

#10983 election provider support: Update some test only types
  frame/election-provider-support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10991 Feedback from @XLC for Referenda Pallet
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
  frame/referenda/src/types.rs
  frame/support/src/traits/schedule.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10997 Make bags-list generic over node value and instantiable
  bin/node/runtime/src/lib.rs
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/src/benchmarks.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/mock.rs
  frame/bags-list/src/tests.rs
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11003 sc-finality-grandpa: use the #[from] attriute to remove boilerplate code
  client/finality-grandpa/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11006 sp-core: `full_crypto` doesn't imply `std`
  primitives/core/Cargo.toml
  primitives/core/src/ecdsa.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11011 Remove unused `parent_hash` in `OverlayedChanges::into_storage_changes`
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/testing.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11015 sp-api: Don't be dirty
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11017 Update clap to the latest version
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/build.rs
  bin/node/inspect/Cargo.toml
  bin/utils/chain-spec-builder/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/arg_enums.rs
  client/cli/src/lib.rs
  client/cli/src/params/import_params.rs
  primitives/npos-elections/fuzzer/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/frame-utilities-cli/Cargo.toml
  utils/frame/generate-bags/node-runtime/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11008 Move scripts used in CI to the new location
  .github/workflows/check-labels.yml
  .github/workflows/monthly-tag.yml
  .gitignore
  .gitlab-ci.yml
  docs/CODEOWNERS
  docs/node-template-release.md
  scripts/ci/common/lib.sh
  scripts/ci/deny.toml
  scripts/ci/docker/subkey.Dockerfile
  scripts/ci/docker/substrate.Dockerfile
  scripts/ci/github/check_labels.sh
  scripts/ci/github/generate_changelog.sh
  scripts/ci/gitlab/check_runtime.sh
  scripts/ci/gitlab/check_signed.sh
  scripts/ci/gitlab/ensure-deps.sh
  scripts/ci/gitlab/publish_draft_release.sh
  scripts/ci/gitlab/skip_if_draft.sh
  scripts/ci/monitoring/alerting-rules/alerting-rule-tests.yaml
  scripts/ci/monitoring/alerting-rules/alerting-rules.yaml
  scripts/ci/monitoring/grafana-dashboards/README_dashboard.md
  scripts/ci/monitoring/grafana-dashboards/substrate-networking.json
  scripts/ci/monitoring/grafana-dashboards/substrate-service-tasks.json
  scripts/ci/node-template-release.sh
  scripts/ci/node-template-release/Cargo.toml
  scripts/ci/node-template-release/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11016 Move `sp-npos-elections-solution-type` to `frame-election-provider-support`
  Cargo.lock
  Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/solution-type/Cargo.toml
  frame/election-provider-support/solution-type/fuzzer/Cargo.toml
  frame/election-provider-support/solution-type/fuzzer/src/compact.rs
  frame/election-provider-support/solution-type/src/codec.rs
  frame/election-provider-support/solution-type/src/from_assignment_helpers.rs
  frame/election-provider-support/solution-type/src/index_assignment.rs
  frame/election-provider-support/solution-type/src/lib.rs
  frame/election-provider-support/solution-type/src/mock.rs
  frame/election-provider-support/solution-type/src/single_page.rs
  frame/election-provider-support/solution-type/src/tests.rs
  frame/election-provider-support/solution-type/tests/ui/fail/missing_accuracy.rs
  frame/election-provider-support/solution-type/tests/ui/fail/missing_accuracy.stderr
  frame/election-provider-support/solution-type/tests/ui/fail/missing_target.rs
  frame/election-provider-support/solution-type/tests/ui/fail/missing_target.stderr
  frame/election-provider-support/solution-type/tests/ui/fail/missing_voter.rs
  frame/election-provider-support/solution-type/tests/ui/fail/missing_voter.stderr
  frame/election-provider-support/solution-type/tests/ui/fail/no_annotations.rs
  frame/election-provider-support/solution-type/tests/ui/fail/no_annotations.stderr
  frame/election-provider-support/solution-type/tests/ui/fail/swap_voter_target.rs
  frame/election-provider-support/solution-type/tests/ui/fail/swap_voter_target.stderr
  frame/election-provider-support/solution-type/tests/ui/fail/wrong_attribute.rs
  frame/election-provider-support/solution-type/tests/ui/fail/wrong_attribute.stderr
  frame/election-provider-support/src/lib.rs
  frame/staking/src/lib.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11028 shell.nix: Update to a newer nightly
  shell.nix
Labels: A2-insubstantial, B0-silent, C1-low 📌

#11030 use `inner` for nested types in nomination pools
  bin/node/runtime/src/lib.rs
  frame/nomination-pools/benchmarking/Cargo.toml
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
Labels: A3-inprogress

#11033 nomination-pools: update benches for new account format
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
Labels: A0-pleasereview

#11004 Additional `benchmark-storage` flags
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/record.rs
  utils/frame/benchmarking-cli/src/storage/template.rs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#11042 Better sanity checks for nomination pools
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/staking/src/pallet/impls.rs
  primitives/staking/src/lib.rs
Labels: A0-pleasereview

#10981 State migration rpc
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  frame/state-trie-migration/Cargo.toml
  frame/state-trie-migration/src/lib.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/trie_backend_essence.rs
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/README.md
  utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11050 More changes to nomination pools
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
  frame/support/src/storage/bounded_btree_map.rs
Labels: A0-pleasereview

#11040 Prevent possible rocksdb-corruption by running benchmark-storage
  client/db/src/lib.rs
  client/db/src/parity_db.rs
  primitives/database/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#11031 Moving `NposSolution` to frame
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-support/solution-type/Cargo.toml
  frame/election-provider-support/solution-type/fuzzer/Cargo.toml
  frame/election-provider-support/solution-type/src/codec.rs
  frame/election-provider-support/solution-type/src/lib.rs
  frame/election-provider-support/solution-type/src/single_page.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/traits.rs
  frame/staking/src/pallet/mod.rs
  primitives/npos-elections/src/assignments.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10977 Add execution overhead benchmarking
  Cargo.lock
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/command_helper.rs
  bin/node/cli/src/lib.rs
  bin/node/cli/tests/benchmark_overhead_works.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/overhead/bench.rs
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
  utils/frame/benchmarking-cli/src/overhead/mod.rs
  utils/frame/benchmarking-cli/src/overhead/template.rs
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/post_processing/mod.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/record.rs
  utils/frame/benchmarking-cli/src/storage/template.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#11012 sc-rpc-api: Remove unused error variants
  client/rpc-api/src/author/error.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10905 Allow `pallet-election-provider` to accept smaller solutions as well
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-support/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D9-needsaudit 👮

#11057 fix sibmit benchmark in election-multi-phase pallet
  frame/election-provider-multi-phase/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11059 Use Lowercase
  utils/frame/try-runtime/cli/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11060 Expose `ToOwned`
  primitives/std/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11064 some additional utils for state-trie-migration
  bin/node/runtime/src/lib.rs
  frame/state-trie-migration/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10956 Incorporate the new electing/electable naming into the code
  bin/node/runtime/src/lib.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11061 Add github issue form templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌

#11074 sc-consensus-aura: Remove obsolete dependency
  Cargo.lock
  client/consensus/aura/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#11077 pallet-whitelist: add sp-api/std to std feature to fix compile error
  frame/whitelist/Cargo.toml
  frame/whitelist/src/benchmarking.rs
  frame/whitelist/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11078 add `MaxEncodedLen` trait to Time::Moment
  frame/support/src/traits/misc.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11075 pallet-macro: Ensure that building with `missing_docs` works
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/test/Cargo.toml
  frame/support/test/pallet/src/lib.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11072 import-blocks: Do not read `stdin` to memory
  client/cli/src/commands/import_blocks_cmd.rs
  client/service/src/chain_ops/import_blocks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11084 Don't ban peers for small duplicate requests
  client/network/src/block_request_handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10939 Add `dev_getBlockStats` RPC
  Cargo.lock
  bin/node/rpc/src/lib.rs
  client/rpc-api/Cargo.toml
  client/rpc-api/src/dev/error.rs
  client/rpc-api/src/dev/mod.rs
  client/rpc-api/src/lib.rs
  client/rpc/src/dev/mod.rs
  client/rpc/src/dev/tests.rs
  client/rpc/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11081 Do not upgrade db_version on metadata reading failure.
  Cargo.lock
  client/db/Cargo.toml
  client/db/src/parity_db.rs
  client/db/src/utils.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11086 warp-sync: Return an error when trying to enable it for archive nodes.
  client/network/src/config.rs
  client/service/src/builder.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10821 Store validator self-vote in bags-list, and allow them to be trimmed for election
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/session/src/migrations/v1.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#11102 Fix `generate_storage_alias!`
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#10242 Allow pallet error enum variants to contain fields
  client/block-builder/src/lib.rs
  client/rpc/src/state/tests.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/tests.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/scheduler/src/mock.rs
  frame/sudo/src/mock.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/parse/error.rs
  frame/support/procedural/src/pallet_error.rs
  frame/support/procedural/src/tt_macro.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/error.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.rs
  frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.stderr
  frame/support/test/tests/origin.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.rs
  frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.stderr
  frame/support/test/tests/pallet_ui/error_no_fieldless.stderr
  frame/support/test/tests/pallet_ui/pass/error_nested_types.rs
  frame/utility/src/tests.rs
  primitives/block-builder/src/lib.rs
  primitives/runtime/src/legacy.rs
  primitives/runtime/src/legacy/byte_sized_error.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E10-client-update-first 👀

#11107 Add extra WASM heap pages when precompiling the runtime blob
  client/executor/benches/bench.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
Labels: A0-pleasereview, I2-bug 🐜, I4-tests 🎯, B0-silent, C1-low 📌, D3-trivial 🧸

#11089 pallet-referenda: make the pallet instantiable
  frame/referenda/src/branch.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/types.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11091 Add `benchmark-block` command
  Cargo.lock
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/block/bench.rs
  utils/frame/benchmarking-cli/src/block/cmd.rs
  utils/frame/benchmarking-cli/src/block/mod.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11014 Improve Bounties and Child Bounties Deposit Logic
  bin/node/runtime/src/lib.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/child-bounties/src/lib.rs
  frame/child-bounties/src/tests.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11088 pallet-conviction-voting: make the pallet instantiable
  frame/conviction-voting/src/conviction.rs
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/tests.rs
  frame/conviction-voting/src/types.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10882 Implement Lean BEEFY
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/src/gossip.rs
  client/beefy/src/lib.rs
  client/beefy/src/metrics.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  frame/beefy/src/lib.rs
  primitives/beefy/Cargo.toml
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D2-notlive 💤

#11117 Remove unneeded code
  frame/whitelist/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10988 Add a bounded fallback on failed elections
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/grandpa/src/mock.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/mock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#11125 Remove Misleading Sentence About `StorageDoubleMap`
  frame/support/src/storage/mod.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#9730 add notes and warnings to ProvideInherent docs
  frame/support/src/inherent.rs
  primitives/inherents/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, D2-notlive 💤

#10894 Bump `tokio` to 1.17.0
  Cargo.lock
  bin/node/cli/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/service/Cargo.toml
  client/service/test/Cargo.toml
  test-utils/Cargo.toml
  test-utils/test-crate/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11100 `bond_extra` for nomination pools
  frame/bags-list/src/benchmarks.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview

#11119 Spellcheck HBS templates and add test
  bin/node/cli/tests/benchmark_storage_works.rs
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11097 Unignore test
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11137 Fix Phragmen benchmark
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11103 Enforce `MaxEncodedLen` impl for `NposSolution`
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/solution-type/src/single_page.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/mock.rs
  frame/election-provider-support/src/tests.rs
  primitives/npos-elections/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11147 frame-support: Rename tests to express what they are doing
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/weak_bounded_vec.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11104 add iter-from for bags-list
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/tests.rs
  frame/election-provider-support/src/lib.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️
