Repository paritytech/substrate, pull requests merged in 2022-07, with the labels that each got.

#11774 [ci] Remove polkadot-companion-labels GHA
  .github/workflows/polkadot-companion-labels.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11771 [contracts] Fixed the bug with transfer value for delegate call
  frame/contracts/src/exec.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11763 Fix clearing queued blocks in the sync module
  client/network/sync/src/blocks.rs
  client/network/sync/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11594 pallet-mmr: handle forks without collisions in offchain storage
  frame/beefy-mmr/src/tests.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/mmr/utils.rs
  frame/merkle-mountain-range/src/tests.rs
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11798 expose grandpa BeforeBestBlockBy voting rule
  client/finality-grandpa/src/voting_rule.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#11807 Un-deprecate Transactional Macro
  frame/nomination-pools/src/lib.rs
  frame/support/procedural/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11811 Backport #11807
  frame/nomination-pools/src/lib.rs
  frame/support/procedural/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11815 sync: Fixed clearing subsequent ranges
  client/network/sync/src/blocks.rs
  client/network/sync/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11786 CLI flag to configure tx ban duration
  bin/node/cli/benches/transaction_pool.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/transaction_pool_params.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/graph/rotator.rs
  client/transaction-pool/src/graph/validated_pool.rs
Labels: B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#11787 Upgrade libp2p to 0.46.1
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/request_responses.rs
  client/network/src/transport.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/transport.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11790 prep council election pallet for being dissolved
  Cargo.lock
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍, E6-transactionversion

#11746 Fix nomination pools unbonding logic
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/nomination-pools/test-staking/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#11816 contracts: Composable `ChainExtension`
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/chain_extension.wat
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11844 [ci] fix job `cancel-pipeline`
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11841 Speed up `rusty-cachier-notify` job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11829 [ci] improvments to make pipeline faster
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11817 Fixed sync target detection
  client/network/sync/src/lib.rs
  client/service/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11851 Ignore boot and reserved nodes with peer ID the same as in local node itself
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11766 removed evaluation.rs
  client/basic-authorship/src/basic_authorship.rs
  primitives/consensus/common/src/evaluation.rs
  primitives/consensus/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11805 assert noop hints when storage has been mutated
  frame/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11795 arrange node-template service
  bin/node-template/node/src/service.rs
  client/consensus/slots/src/aux_schema.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11775 Expose and link trie migration weights
  frame/state-trie-migration/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11854 Disable the interest cache
  Cargo.lock
  client/tracing/Cargo.toml
  client/tracing/src/logging/mod.rs
  primitives/io/Cargo.toml
  primitives/runtime-interface/test/Cargo.toml
  primitives/tracing/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11850 Don't download artifacts into the `rusty-cachier-notify` job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11865 Cleanup light client leftovers
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/network/src/config.rs
  client/network/src/protocol/message.rs
  client/network/src/service.rs
  client/network/src/transactions.rs
  client/rpc-api/src/system/helpers.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11678 Sassafras consensus - Prototype #1
  Cargo.lock
  Cargo.toml
  bin/node-sassafras/.editorconfig
  bin/node-sassafras/node/Cargo.toml
  bin/node-sassafras/node/build.rs
  bin/node-sassafras/node/src/chain_spec.rs
  bin/node-sassafras/node/src/cli.rs
  bin/node-sassafras/node/src/command.rs
  bin/node-sassafras/node/src/main.rs
  bin/node-sassafras/node/src/rpc.rs
  bin/node-sassafras/node/src/service.rs
  bin/node-sassafras/runtime/Cargo.toml
  bin/node-sassafras/runtime/build.rs
  bin/node-sassafras/runtime/src/lib.rs
  client/consensus/sassafras/Cargo.toml
  client/consensus/sassafras/src/authorship.rs
  client/consensus/sassafras/src/aux_schema.rs
  client/consensus/sassafras/src/lib.rs
  client/consensus/sassafras/src/verification.rs
  client/consensus/slots/src/lib.rs
  frame/sassafras/Cargo.toml
  frame/sassafras/README.md
  frame/sassafras/src/lib.rs
  primitives/consensus/sassafras/Cargo.toml
  primitives/consensus/sassafras/src/digests.rs
  primitives/consensus/sassafras/src/inherents.rs
  primitives/consensus/sassafras/src/lib.rs
  primitives/consensus/vrf/src/schnorrkel.rs
  primitives/core/src/crypto.rs
  primitives/keystore/src/vrf.rs
Labels: I8-enhancement 🎁, B0-silent, C1-low 📌, D2-notlive 💤

#11679 Stop RPC servers on drop
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11885 [ci] Generate rustdocs without dependencies
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11840 pallet-mmr: fix batch proof failures
  Cargo.lock
  frame/merkle-mountain-range/Cargo.toml
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/mmr/utils.rs
  frame/merkle-mountain-range/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11872 Clarify wrong bootnode peer ID error message
  client/network/src/service.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌

#11849 Fix for 'note_applied_extrinsic' - consider also actual pays_fee
  frame/support/src/weights.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11877 pallet-assets: Update docs
  frame/assets/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11899 Fixing conflict for PR 11596
  frame/tips/src/lib.rs
Labels: A0-pleasereview

#11894 Fix typo in limits.rs
  frame/system/src/limits.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#11901 [ci] fix node-bench-regression-guard job
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11895 Remove unused leaves-set fields
  client/api/src/leaves.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11770 Add era to `Unbonded` event
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
  frame/nomination-pools/test-staking/src/lib.rs
Labels: A0-pleasereview, A3-needsresolving, B0-silent, C1-low 📌, D3-trivial 🧸

#11897 remove FunctionOf
  frame/support/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11874 contracts: Allow `ChainExtension::call()` to access `&mut self`
  frame/contracts/fixtures/chain_extension.wat
  frame/contracts/fixtures/chain_extension_temp_storage.wat
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11900 Pruned duplicated dependencies
  Cargo.lock
  client/beefy/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/ecdsa.rs
  primitives/io/Cargo.toml
  primitives/keyring/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11914 Fix typos
  frame/transaction-payment/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11831 Rpc for pending rewards
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/nomination-pools/runtime-api/Cargo.toml
  frame/nomination-pools/runtime-api/README.md
  frame/nomination-pools/runtime-api/src/lib.rs
  frame/nomination-pools/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11873 [ci] remove cargo-check-nixos job
  scripts/ci/gitlab/pipeline/test.yml
  shell.nix
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11823 Properly defer slashes
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#11920 [ci] Return production image
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11918 Make New Storage Layer Truly Default
  frame/nomination-pools/src/tests.rs
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#11926 Remove `retain_mut` crate
  Cargo.lock
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/graph/validated_pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11924 Fix slashing migration to v10
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#11929 Backport #11924: Fix slashing migration to v10
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌, D9-needsaudit 👮

#11747 Enrich the sync log on handling the block request
  client/network/sync/src/block_request_handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11523 Prevent double allocation of the payload when calling `sp_io::storage::get`
  Cargo.lock
  client/allocator/src/freeing_bump.rs
  client/allocator/src/lib.rs
  client/executor/common/src/wasm_runtime.rs
  client/executor/src/native_executor.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/runtime.rs
  frame/support/src/storage/unhashed.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/pass_by.rs
  primitives/runtime-interface/test-wasm/Cargo.toml
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview, I7-optimisation ⏱, I7-footprint 👣, B0-silent, C1-low 📌, D3-trivial 🧸

#11932 construct_runtime!: Support parsing `struct Runtime`
  bin/node-template/runtime/src/lib.rs
  frame/balances/src/tests_local.rs
  frame/support/procedural/src/construct_runtime/parse.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11692 feat: add propose method for SimpleSlotWorker
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11917 Require Alliance Initialisation Before Joining
  frame/alliance/src/lib.rs
  frame/alliance/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11931 Integrate automatic update of substrate-node-template
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11909 Always allocate slots for reserved nodes
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11821 Lean BEEFY to Full BEEFY - don't skip (older) mandatory blocks and import justifications
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/rpc/src/lib.rs
  client/beefy/rpc/src/notification.rs
  client/beefy/src/error.rs
  client/beefy/src/import.rs
  client/beefy/src/justification.rs
  client/beefy/src/lib.rs
  client/beefy/src/metrics.rs
  client/beefy/src/notification.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/network/test/src/lib.rs
  primitives/beefy/src/commitment.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11690 Add Event to Pallet Asset-Tx-Payment
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11825 Network sync refactoring (part 5)
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11827 feat: generalize ConsensusDataProvider for manual-seal
  client/consensus/manual-seal/src/consensus.rs
  client/consensus/manual-seal/src/consensus/aura.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11796 Auto-incremental CollectionId
  Cargo.lock
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D1-audited 👍, E6-transactionversion
