Repository paritytech/substrate, pull requests merged in 2022-06, with the labels that each got.

#11563 Do not require Ord for pallet_offences::Config::IdentificationTuple
  frame/offences/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11548 Ranked Collective pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/ranked-collective/Cargo.toml
  frame/ranked-collective/README.md
  frame/ranked-collective/src/benchmarking.rs
  frame/ranked-collective/src/lib.rs
  frame/ranked-collective/src/tests.rs
  frame/ranked-collective/src/weights.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/types.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/src/dispatch.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/voting.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11564 Introduce set function into storage maps
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11567 Introduce `SubmitOrigin` to Referenda pallet config
  bin/node/runtime/src/lib.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11560 Don't limit `test-linux-stable-int` job output
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11570 Helper macro for `Morph` impls
  frame/ranked-collective/src/tests.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/misc.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11572 `rusty-cachier` pipeline impovements and fixes
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11468 aura: export change_authorities and initialize_authorities
  frame/aura/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11578 Reduce call size of Referenda pallet
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
  frame/support/procedural/src/construct_runtime/expand/call.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#11582 wasm-builder: Rerun the build if the generated file changed
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11588 Expose ValidatedTransaction from transaction pool
  client/transaction-pool/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11590 Remove `#[pallet::without_storage_info]` for pallet-remark
  frame/remark/src/lib.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#11583 Add host info to weight templates
  .maintain/frame-weight-template.hbs
  Cargo.lock
  frame/system/src/weights.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
  utils/frame/benchmarking-cli/src/overhead/template.rs
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/pallet/mod.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
  utils/frame/benchmarking-cli/src/shared/mod.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/template.rs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11545 Expose Benchmarking Component Ranges
  .maintain/frame-weight-template.hbs
  frame/identity/src/weights.rs
  frame/system/src/weights.rs
  scripts/run_all_benchmarks.sh
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11575 make era public
  frame/system/src/extensions/check_mortality.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11602 MEL for Ranked Collective
  frame/ranked-collective/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11600 Fix one-by-off in `BoundedSlice::try_from`
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11593 Remove a max supply record on collection's destruction
  frame/uniques/src/functions.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#11616 Implement more IntoIter traits for bounded types
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11591 Remove `without_storage_info` for membership pallet
  frame/membership/src/lib.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#11611 Improve docs on `--keep-blocks` CLI parameter and related data structures
  client/cli/src/params/pruning_params.rs
  client/db/src/lib.rs
  client/network/test/src/lib.rs
  client/service/src/config.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11525 Improve inspection and generation of node keys
  bin/utils/subkey/src/lib.rs
  client/cli/src/commands/generate_node_key.rs
  client/cli/src/commands/inspect_node_key.rs
  client/cli/src/commands/key.rs
Labels: A0-pleasereview, I8-enhancement 🎁, B0-silent, C1-low 📌

#11629 Better transaction pool error
  client/transaction-pool/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11635 Backport 11593
  frame/uniques/src/functions.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#11617 Use BoundedVec in aura pallet
  frame/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11112 pallet alliance
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/alliance/Cargo.toml
  frame/alliance/README.md
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/alliance/src/mock.rs
  frame/alliance/src/tests.rs
  frame/alliance/src/types.rs
  frame/alliance/src/weights.rs
  frame/collective/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11555 Add fixed u64
  primitives/arithmetic/src/fixed_point.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11643 Remove storage `MaxValues` limits
  frame/assets/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/balances/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11620 Added an event for cancel_proposal
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/public_proposals.rs
Labels: A5-grumble, B0-silent, C1-low 📌, D3-trivial 🧸

#11623 pallet-grandpa: Improve/Clarify docs of `note_stalled`
  frame/grandpa/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11651 pallet uniques: fix broken docs link
  frame/uniques/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#11584 Implement MaxEncodedLen on pallet-beefy
  frame/beefy-mmr/src/mock.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  primitives/runtime/src/bounded/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#11655 Implement PartialOrd and Ord on BoundedSlice and WeakBoundedVec
  primitives/runtime/src/bounded/bounded_btree_map.rs
  primitives/runtime/src/bounded/bounded_btree_set.rs
  primitives/runtime/src/bounded/bounded_vec.rs
  primitives/runtime/src/bounded/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11659 Properly implement Debug on bounded types
  primitives/runtime/src/bounded/bounded_btree_map.rs
  primitives/runtime/src/bounded/bounded_btree_set.rs
  primitives/runtime/src/bounded/bounded_vec.rs
  primitives/runtime/src/bounded/weak_bounded_vec.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#11653 remove flaky rpc subscription tests
  client/beefy/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#11599 Add `TypeInfo` for `TransactionValidityError`
  primitives/runtime/src/transaction_validity.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11624 wasm-builder: Fix constant re-running of `build.rs` scripts.
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11656 Increment subkey version to 2.0.2
  Cargo.lock
  bin/utils/subkey/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11302 grandpa: fix creation of justification with equivocating precommits in commit
  Cargo.lock
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/tests.rs
  frame/grandpa/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11537 Make it possible to disable RocksDB completely
  bin/node/cli/Cargo.toml
  bin/node/testing/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/arg_enums.rs
  client/cli/src/config.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/utils.rs
  client/service/Cargo.toml
  test-utils/client/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#11625 Include the chain specs instead of trying to open them by path
  client/beefy/src/tests.rs
  client/finality-grandpa/src/communication/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11668 Remove `without_storage_info` from pallet `transaction-storage`
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/transaction-storage/Cargo.toml
  frame/transaction-storage/src/benchmarking.rs
  frame/transaction-storage/src/lib.rs
  frame/transaction-storage/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11498 combine iteratons and tolerance in sp-npos-elections API
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/weights.rs
  primitives/npos-elections/README.md
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/src/common.rs
  primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
  primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
  primitives/npos-elections/src/balancing.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11618 Add Event to Pallet Transaction Payment
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  bin/node/bench/src/import.rs
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/basic.rs
  bin/node/runtime/src/lib.rs
  client/db/src/parity_db.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/executive/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11610 Remove `without_storage_info` for the authorship pallet
  frame/authorship/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11631 MEL: Origin, Referenda, ConvictionVoting
  Cargo.lock
  frame/collective/src/lib.rs
  frame/conviction-voting/Cargo.toml
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/types.rs
  frame/conviction-voting/src/vote.rs
  frame/ranked-collective/src/lib.rs
  frame/referenda/Cargo.toml
  frame/referenda/src/lib.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/schedule.rs
  frame/support/src/traits/voting.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/origin.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  primitives/core/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A3-inprogress, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11598 Remove multiply_by_rational
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/arithmetic/fuzzer/src/multiply_by_rational_with_rounding.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/helpers_128bit.rs
  primitives/arithmetic/src/rational.rs
  primitives/npos-elections/src/phragmen.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11682 Upgrade to libp2p 0.45.1
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker/schema/dht-v2.proto
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/lib.rs
  client/telemetry/src/node.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11697 backport: Upgrade to libp2p 0.45.1 (#11682)
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/worker/schema/dht-v2.proto
  client/network/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/service.rs
  client/network/sync/Cargo.toml
  client/telemetry/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#11688 chore: reducing codec times
  client/basic-authorship/src/basic_authorship.rs
  primitives/consensus/common/src/evaluation.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11698 chore: reduce uxt encode times
  frame/executive/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11702 Simplified code using existing APIs
  client/executor/wasmtime/src/host.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11704 `storage-alias`: Check that prefix is not an underscore
  frame/support/procedural/src/storage_alias.rs
  frame/support/test/tests/storage_alias_ui.rs
  frame/support/test/tests/storage_alias_ui/checks_for_valid_storage_type.rs
  frame/support/test/tests/storage_alias_ui/checks_for_valid_storage_type.stderr
  frame/support/test/tests/storage_alias_ui/forbid_underscore_as_prefix.rs
  frame/support/test/tests/storage_alias_ui/forbid_underscore_as_prefix.stderr
  frame/support/test/tests/storage_alias_ui/prefix_must_be_an_ident.rs
  frame/support/test/tests/storage_alias_ui/prefix_must_be_an_ident.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11707 Update syn and fix compilation
  Cargo.lock
  client/chain-spec/derive/Cargo.toml
  client/tracing/proc-macro/Cargo.toml
  frame/contracts/proc-macro/Cargo.toml
  frame/election-provider-support/solution-type/Cargo.toml
  frame/staking/reward-curve/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/tools/Cargo.toml
  frame/support/procedural/tools/derive/Cargo.toml
  frame/support/procedural/tools/src/syn_ext.rs
  primitives/api/proc-macro/Cargo.toml
  primitives/core/hashing/proc-macro/Cargo.toml
  primitives/debug-derive/Cargo.toml
  primitives/runtime-interface/proc-macro/Cargo.toml
  primitives/version/proc-macro/Cargo.toml
  test-utils/derive/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#11693 check-dependent-cumulus should only be executed for PRs
  scripts/ci/gitlab/pipeline/build.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11694 Pump the gossip engine while waiting for the BEEFY runtime pallet (memory leak fix)
  client/beefy/src/worker.rs
  client/network-gossip/src/bridge.rs
Labels: A0-pleasereview, I2-bug 🐜, I7-footprint 👣, B5-clientnoteworthy, C3-medium 📣, D3-trivial 🧸

#11713 Implement Serialize/Deserialize on WeakBoundedVec
  primitives/runtime/src/bounded/weak_bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11724 Fix typo in weights.rs
  frame/support/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11726 WrapperOpaque: Use `decode_all` to decode from the `Vec<u8>`
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11696 contracts: Reduce size of deletion queue depth
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11725 epochs: don't use gap when there's at least one genesis epoch imported
  client/consensus/epochs/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11406 pallet-beefy-mmr: add API for BEEFY Authority Sets
  Cargo.lock
  frame/beefy-mmr/primitives/Cargo.toml
  frame/beefy-mmr/primitives/src/lib.rs
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy-mmr/src/tests.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  primitives/beefy/src/lib.rs
  primitives/beefy/src/mmr.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#11473 make pallet-tips & pallet-bounties instantiable
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/tips/src/benchmarking.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11740 Explain why `rusty-cachier` is put first
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11720 Bump `wasmtime` to 0.38.0 and `zstd` to 0.11.2
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/runtime.rs
  frame/state-trie-migration/Cargo.toml
  primitives/maybe-compressed-blob/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/wasm-interface/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#11094 Avoid a duplicate block request when syncing from a fork
  client/consensus/common/src/import_queue.rs
  client/network/sync/src/blocks.rs
  client/network/sync/src/lib.rs
Labels: A6-seemsok, B0-silent, C1-low 📌, D3-trivial 🧸

#11666 Democracy.fast_track not allowed with zero voting period
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/fast_tracking.rs
Labels: A0-pleasereview, B3-apinoteworthy, C3-medium 📣, D1-audited 👍

#11722 Prevent unsoundness in environments with broken `madvise(MADV_DONTNEED)`
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11754 Refund weight in `system::fillBlock`
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/fees.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11748 nomination-pools fix
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11755 backport #11754 to release branch
  Cargo.lock
  bin/node/executor/Cargo.toml
  bin/node/executor/tests/fees.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️
