Repository paritytech/substrate, pull requests merged in 2022-02, with the labels that each got.

#10765 derive MaxEncodedLen for `MultiSignature`
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10768 Add `MaxEncodedLen` to `implement_fixed!`
  primitives/arithmetic/src/fixed_point.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10760 More Referenda Patches
  frame/conviction-voting/src/benchmarking.rs
  frame/conviction-voting/src/conviction.rs
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/types.rs
  frame/conviction-voting/src/vote.rs
  frame/referenda/src/branch.rs
  frame/referenda/src/lib.rs
Labels: A0-pleasereview

#10739 Enable download of future forks
  client/network/src/protocol/sync.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview, B0-silent, C3-medium 📣, D3-trivial 🧸

#10775 wasm-builder: Fall back to `release` profile for unknown profiles
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10642 Substrate alerts rules update
  .maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
  .maintain/monitoring/alerting-rules/alerting-rules.yaml
  .maintain/monitoring/grafana-dashboards/substrate-networking.json
  .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10771 bench-cli: Support `JSON` output
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/command.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, E5-breaksapi, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10776 Introduce ModuleError struct
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/elections-phragmen/src/lib.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/src/error.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10790 Release `sp-keyring`
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/testing/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/indices/Cargo.toml
  primitives/keyring/Cargo.toml
  test-utils/client/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10731 [jsonrpsee]: enable custom RPC subscription ID generatation
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/rpc/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/cli/src/config.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc/Cargo.toml
  client/rpc/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A3-inprogress

#10782 Make `offences` benchmark runnable
  frame/offences/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10789 contracts: `is_contract(address)` and `caller_is_origin()` are added to API
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10799 maybe_total_supply in pallet-assets
  frame/assets/src/functions.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10195 Referenda and Conviction Voting pallets
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/conviction-voting/Cargo.toml
  frame/conviction-voting/README.md
  frame/conviction-voting/src/benchmarking.rs
  frame/conviction-voting/src/conviction.rs
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/tests.rs
  frame/conviction-voting/src/types.rs
  frame/conviction-voting/src/vote.rs
  frame/conviction-voting/src/weights.rs
  frame/democracy/src/lib.rs
  frame/referenda/Cargo.toml
  frame/referenda/README.md
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/branch.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
  frame/referenda/src/types.rs
  frame/referenda/src/weights.rs
  frame/scheduler/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/schedule.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/voting.rs
  frame/support/test/tests/system.rs
  frame/system/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10801 More efficient WASM instance memory decommit on macos
  client/executor/wasmtime/src/instance_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10773 make inner field of pallet_identity::IdentityFields pub
  frame/identity/src/types.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10729 Corrected description of clear_attribute extrinsic
  frame/uniques/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10617 `seal_delegate_call` api function (support for library contracts)
  frame/contracts/fixtures/delegate_call.wat
  frame/contracts/fixtures/delegate_call_lib.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10819 fixed regression in inline docs
  frame/nicks/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10822 try-runtime-cli: Add to docs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10828 `--dev` implies `--tmp`
  bin/node-template/README.md
  frame/contracts/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10830 Add db params for export-state CLI command
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10826 Allow `SetBalance` to handle error when trying to kill acount with reference counter.
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10829 UncheckedExtrinsic: Harden decode and clarify `EXTRINSIC_FORMAT_VERSION`
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10786 pallet-staking: Add extrinsic `force_apply_min_commission`
  frame/staking/src/benchmarking.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/traits/stored_map.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10690 Upgradable contracts using `set_code` function
  frame/contracts/fixtures/new_set_code_hash_contract.wat
  frame/contracts/fixtures/set_code_hash.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10563 Separate wasmi and wasmer sandbox implementations into their own modules
  client/executor/common/src/error.rs
  client/executor/common/src/sandbox.rs
  client/executor/common/src/sandbox/wasmer_backend.rs
  client/executor/common/src/sandbox/wasmi_backend.rs
  client/executor/common/src/util.rs
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/src/host.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10838 Show Network ID when creating and inspecting
  client/cli/src/commands/utils.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10839 Reduce overhead of generating network event metrics
  client/network/src/service/out_events.rs
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10841 Allow trailing comma in map macro
  primitives/std/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10845 build-script-utils: allow reading the git commit hash from env var
  utils/build-script-utils/src/version.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10844 Don't create DB leaves when syncing historic blocks
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10846 Fixed broken link in Uniques Frame README
  frame/uniques/README.md
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10853 subkey: Support `--version` cli command
  bin/utils/subkey/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10837 wasm-builder: Support latest nightly
  Cargo.lock
  bin/node/runtime/Cargo.toml
  primitives/keyring/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10796 contracts: Fix `seal_call` weights
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10855 Enable the `parking_lot` feature for `tokio`
  bin/node/cli/Cargo.toml
  client/cli/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/service/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10858 [ci] fix publish-rustdocs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10854 Fix beefy mock ecdsa keys
  frame/beefy-mmr/src/mock.rs
  frame/beefy-mmr/src/tests.rs
  frame/beefy/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10832 Mark sync_state_genSyncSpec JSON-RPC as safe
  Cargo.lock
  bin/node/rpc/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  client/sync-state-rpc/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10859 Reduce CPU overhead of gossip
  Cargo.lock
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/state_machine.rs
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10835 sp-core-hashing: use the `digest::Digest` trait to handle the hashing function uniformly
  Cargo.lock
  primitives/api/proc-macro/Cargo.toml
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/core/Cargo.toml
  primitives/core/hashing/Cargo.toml
  primitives/core/hashing/src/lib.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10865 Use qualified syntax for `retain_mut`
  client/consensus/babe/src/lib.rs
  client/transaction-pool/src/graph/validated_pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10834 refactor election score
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  primitives/arithmetic/src/lib.rs
  primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
  primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10863 contracts: Don't round to kilobyte for code size based weight
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10867 Tidy Democracy
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/delegation.rs
  frame/democracy/src/vote.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10869 sc-executor: Improve logging
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10843 Track allowed requests for state/warp sync
  client/network/src/protocol/sync.rs
Labels: A0-pleasereview, I7-optimisation ⏱, B0-silent, C1-low 📌, D3-trivial 🧸

#10876 Slots: Ensure that a race betwen finalized and best number is taken care off
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10879 Remove old lock file
  primitives/npos-elections/fuzzer/Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10884 Introduce `BoundedVec::iter_mut`
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10886 Slots: Log total proposing duration as milliseconds
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10890 staking: Clarify reward calc docs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, I5-documentation 📄, B0-silent, C1-low 📌, D2-notlive 💤

#10893 tracing: Adds `init_for_tests`
  primitives/tracing/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10899 [EPM pallet]: make submissions types public
  frame/election-provider-multi-phase/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10877 contracts: Allow stack height metering to be disabled
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10895 Rename Uniques Error::Unknown to something more sensible
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10878 consensus-slots: cleanup SlotDuration config
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/consensus/aura.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/consensus/timestamp.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/aura/src/lib.rs
  primitives/consensus/babe/src/inherents.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/common/src/lib.rs
  primitives/consensus/slots/Cargo.toml
  primitives/consensus/slots/src/lib.rs
  primitives/timestamp/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10883 Replace libsecp256k1 with k256 in FRAME related code
  Cargo.lock
  Cargo.toml
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10748 Clean obsolete BABE's weight data
  client/api/src/backend.rs
  client/api/src/client.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/service/src/client/client.rs
  primitives/blockchain/src/header_metadata.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10908 Factor DB weights out into their own files
  frame/support/src/weights.rs
  frame/support/src/weights/paritydb_weights.rs
  frame/support/src/weights/rocksdb_weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10891 Get rid of unnecessary use of `async-std` in non-test code
  Cargo.lock
  client/network/Cargo.toml
  utils/prometheus/Cargo.toml
  utils/prometheus/src/lib.rs
  utils/prometheus/src/networking.rs
Labels: A0-pleasereview, I6-refactor 🧹, B0-silent, C1-low 📌, D3-trivial 🧸

#10346 No longer generate specs with consensus_engine field
  client/chain-spec/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10920 sc-cli: Fix bugs after switching to clap3
  client/cli/src/arg_enums.rs
  client/cli/src/params/network_params.rs
  client/cli/src/params/shared_params.rs
  client/network/src/config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10897 Storage benchmarking
  Cargo.lock
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  client/cli/src/arg_enums.rs
  client/cli/src/params/database_params.rs
  client/cli/src/params/pruning_params.rs
  client/cli/src/params/shared_params.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/mod.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/record.rs
  utils/frame/benchmarking-cli/src/storage/template.rs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
  utils/frame/benchmarking-cli/src/storage/write.rs
  utils/frame/benchmarking-cli/src/writer.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10909 Integrate try-runtime into substrate node template
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10936 Docs Corrections
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10708 #10576: generic utility to unsubscribe from broadcast upon drop of the rx-side.
  Cargo.lock
  client/api/src/client.rs
  client/api/src/notifications.rs
  client/api/src/notifications/registry.rs
  client/api/src/notifications/tests.rs
  client/rpc/src/state/state_full.rs
  client/service/src/client/client.rs
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/tests/pool.rs
  client/utils/Cargo.toml
  client/utils/src/id_sequence.rs
  client/utils/src/lib.rs
  client/utils/src/notification.rs
  client/utils/src/notification/registry.rs
  client/utils/src/notification/tests.rs
  client/utils/src/pubsub.rs
  client/utils/src/pubsub/tests.rs
  client/utils/src/pubsub/tests/normal_operation.rs
  client/utils/src/pubsub/tests/panicking_registry.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10947 Bring back MaxNominations as a metadata constant
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸
