Repository paritytech/substrate, pull requests merged in 2022-09, with the labels that each got.

#12145 Uniques: Reset approved account after transfer
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/tests.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#11997 Alliance pallet: add force_set_members instead of init_members function
  bin/node/runtime/src/impls.rs
  frame/alliance/README.md
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/alliance/src/mock.rs
  frame/alliance/src/tests.rs
  frame/alliance/src/types.rs
  frame/alliance/src/weights.rs
Labels: A3-inprogress, B3-apinoteworthy, E5-breaksapi, C1-low 📌, D5-nicetohaveaudit ⚠️, D2-breaksapi

#10174 Runtime State Test + Integration with `try-runtime`
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/bags-list/fuzzer/src/main.rs
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/remote-tests/src/try_state.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/mock.rs
  frame/beefy-mmr/Cargo.toml
  frame/beefy/Cargo.toml
  frame/election-provider-support/src/lib.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/nomination-pools/Cargo.toml
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/remark/Cargo.toml
  frame/staking/src/migrations.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/try_runtime.rs
  frame/system/src/lib.rs
  frame/transaction-storage/Cargo.toml
  frame/try-runtime/Cargo.toml
  frame/try-runtime/src/lib.rs
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#12069 Name the score of the election in election finalized event
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11980 statedb: allow longer state pruning history
  client/db/src/lib.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
  client/state-db/src/pruning.rs
  client/state-db/src/test.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12163 Add `StorageNoopGuard`
  frame/support/src/lib.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/storage_noop_guard.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12147 Do not drop the `task_manager` for benchmarking stuff
  bin/node/cli/src/command.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/shared_params.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12174 Alliance pallet: fix func name, fix migration weights
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/alliance/src/migration.rs
  frame/alliance/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12157 Remove RefTimeWeight
  .maintain/frame-weight-template.hbs
  frame/alliance/src/weights.rs
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/weights.rs
  frame/conviction-voting/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/election-provider-support/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/examples/basic/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/node-authorization/src/weights.rs
  frame/nomination-pools/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/ranked-collective/src/weights.rs
  frame/recovery/src/weights.rs
  frame/referenda/src/weights.rs
  frame/remark/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/state-trie-migration/src/weights.rs
  frame/support/src/lib.rs
  frame/support/src/weights.rs
  frame/support/src/weights/weight_v2.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_compatibility_instance.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  frame/whitelist/src/weights.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12159 Add benchmarking support for digest items
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  utils/frame/benchmarking-cli/src/extrinsic/bench.rs
  utils/frame/benchmarking-cli/src/extrinsic/cmd.rs
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12136 Emit events for inter contract calls
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12172 Use custom type for ProtocolName
  client/beefy/src/lib.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/common/src/config.rs
  client/network/common/src/protocol.rs
  client/network/common/src/protocol/event.rs
  client/network/common/src/request_responses.rs
  client/network/common/src/service.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/error.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/transactions.rs
  client/network/test/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12048 `try-runtime`::`follow-chain` - execute all blocks
  Cargo.lock
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11959 beefy: initialize voter from genesis and fix initial sync
  client/beefy/src/import.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12175 Doc only typo fixes
  frame/assets/src/types.rs
  frame/support/src/traits/metadata.rs
  frame/support/src/traits/tokens/fungibles/approvals.rs
  frame/support/src/traits/tokens/fungibles/balanced.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12177 Impl transaction-payment GenesisConfig with NextFeeMultplier support
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12179 Alliance pallet: split force_set_members call
  bin/node/runtime/src/impls.rs
  frame/alliance/README.md
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/alliance/src/mock.rs
  frame/alliance/src/tests.rs
  frame/alliance/src/types.rs
  frame/alliance/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11760 Fetch Babe configuration from runtime state
  bin/node/cli/src/service.rs
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/migration.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/consensus.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/consensus/timestamp.rs
  frame/babe/src/lib.rs
  primitives/consensus/babe/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#12154 [Fix] Make sure pool metadata is removed on pool dissolve
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
Labels: A0-pleasereview, I2-bug 🐜, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#12167 `try-runtime`::`follow-chain` - keep connection
  bin/node/cli/tests/common.rs
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#12143 Uniques: Small fix in docs
  frame/uniques/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12058 staking: avoid proportional slashing leak dust into chunks that should not be slashed
  frame/nomination-pools/test-staking/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
  primitives/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#12192 Update contract weights
  frame/contracts/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12203 Move Get and bounded types to sp-core
  primitives/core/src/bounded.rs
  primitives/core/src/bounded/bounded_btree_map.rs
  primitives/core/src/bounded/bounded_btree_set.rs
  primitives/core/src/bounded/bounded_vec.rs
  primitives/core/src/bounded/weak_bounded_vec.rs
  primitives/core/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12204 Add `--header` to `benchmark overhead + storage`
  utils/frame/benchmarking-cli/src/overhead/README.md
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
  utils/frame/benchmarking-cli/src/overhead/template.rs
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/shared/README.md
  utils/frame/benchmarking-cli/src/storage/README.md
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/template.rs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#12183 Remove Ord impl for Weights V2 and add comparison fns
  frame/babe/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/wasm/mod.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/examples/basic/src/tests.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/multisig/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
  frame/support/src/weights/paritydb_weights.rs
  frame/support/src/weights/rocksdb_weights.rs
  frame/support/src/weights/weight_v2.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/limits.rs
  frame/whitelist/src/lib.rs
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12170 pallet-identity: Be more paranoid ;)
  frame/alliance/src/mock.rs
  frame/benchmarking/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍, E6-transactionversion

#12096 Upgrade wasmtime to 0.40.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/runtime.rs
  frame/contracts/src/weights.rs
  primitives/wasm-interface/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12036 Use parameter_types instead of thread_local for test-setup
  frame/assets/src/mock.rs
  frame/aura/src/mock.rs
  frame/bounties/src/tests.rs
  frame/child-bounties/src/tests.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/executive/src/lib.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/merkle-mountain-range/src/mock.rs
  frame/merkle-mountain-range/src/tests.rs
  frame/offences/src/mock.rs
  frame/scheduler/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/scored-pool/src/tests.rs
  frame/session/src/historical/mod.rs
  frame/session/src/historical/offchain.rs
  frame/session/src/mock.rs
  frame/session/src/tests.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/support/src/lib.rs
  frame/support/test/tests/construct_runtime.rs
  frame/system/src/mock.rs
  frame/system/src/tests.rs
  frame/timestamp/src/mock.rs
  frame/tips/src/tests.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#11904 Fully remove `rusty-cachier` from the `node-bench-regression-guard` job
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11996 Removing without_storage_info from scored-pool pallet.
  frame/scored-pool/src/lib.rs
  frame/scored-pool/src/mock.rs
  frame/scored-pool/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12220 Update ss58-registry
  Cargo.lock
  primitives/core/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12229 construct_runtime: Fix generation of types behind features
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12201 Remove native call
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/fees.rs
  client/api/src/call_executor.rs
  client/api/src/execution_extensions.rs
  client/executor/src/native_executor.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/core/src/lib.rs
  primitives/core/src/traits.rs
  primitives/state-machine/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12002 Fuzz testing for nomination pools
  Cargo.lock
  frame/nomination-pools/Cargo.toml
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/support/src/traits/misc.rs
  primitives/runtime/src/lib.rs
  utils/frame/benchmarking-cli/src/machine/hardware.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12222 Add `ConstFeeMultiplier` to the transaction payment pallet
  bin/node-template/runtime/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12233 Don't run `cargo-check-benches` for `master` based downstream staging pipelines
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12245 Expose some of the staking miner types over metadata
  frame/election-provider-multi-phase/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12208 extract some grandpa types to Primitives crate
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/until_imported.rs
  frame/transaction-payment/rpc/src/lib.rs
  primitives/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12247 Update README
  README.md
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌

#11738 add inspect trait for asset roles
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/tests.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/support/src/traits/tokens/fungibles/roles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12242 Move bitswap to its own crate
  Cargo.lock
  Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/bitswap/build.rs
  client/network/bitswap/src/lib.rs
  client/network/bitswap/src/schema.rs
  client/network/bitswap/src/schema/bitswap.v1.2.0.proto
  client/network/src/behaviour.rs
  client/network/src/bitswap.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12232 benches: disable caching per default
  utils/frame/benchmarking-cli/src/block/cmd.rs
  utils/frame/benchmarking-cli/src/extrinsic/cmd.rs
  utils/frame/benchmarking-cli/src/overhead/cmd.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12246 Make `BasePath::new_temp_dir` return the same path for the program lifetime
  Cargo.lock
  client/service/Cargo.toml
  client/service/src/config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12213 Remove CanAuthorWith trait
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  primitives/consensus/common/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#12178 Nfts: Multiple approvals
  bin/node/runtime/src/lib.rs
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/functions.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#12265 fix sp-weight std
  primitives/runtime/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12253 Clean up the logging output
  client/tracing/src/logging/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12234 Bump wasm-instrument
  Cargo.lock
  client/executor/common/Cargo.toml
  frame/contracts/Cargo.toml
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12262 Include Bitswap into request response protocols
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12270 Use `--locked` for Cargo in CI everywhere
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12273 Expose tracks as a constant.
  bin/node/runtime/src/lib.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12274 client/beefy: fix voter initialization corner-case
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12241 Multisig: Fix tests and re-introduce reserve logic
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
Labels: A3-inprogress, B7-runtimenoteworthy, C1-low 📌

#12281 Fix warp sync
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/lib.rs
  client/consensus/common/src/block_import.rs
  client/consensus/pow/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12205 Add special tag to exclude runtime storage items from benchmarking
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/storage.rs
  frame/support/test/tests/pallet_ui/storage_invalid_attribute.stderr
  frame/system/src/lib.rs
  primitives/storage/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12034 [Feature] Part 1: add TargetList for validator ranking
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/voter_bags.rs
  frame/babe/src/mock.rs
  frame/bags-list/remote-tests/src/lib.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/bags-list/remote-tests/src/try_state.rs
  frame/grandpa/src/mock.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  utils/frame/generate-bags/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D5-nicetohaveaudit ⚠️

#12290 [Fix] Benchmark issue in staking
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12185 support upgrade hooks to directly pass data
  frame/bags-list/src/migrations.rs
  frame/executive/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/staking/src/migrations.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/storage/storage_noop_guard.rs
  frame/support/src/traits.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/try_runtime.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12186 contracts: Use `WeakBoundedVec` for instrumented code
  bin/node/runtime/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12297 Fix CI
  frame/bags-list/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/migrations.rs
  frame/uniques/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12301 Fix `cargo-check-benches` job's `rules:`
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12309 [ci] Revert cancel-pipeline job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12311 try-runtime: rename spec check flag
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12300 Import target block body during warp sync
  client/network/common/src/sync.rs
  client/network/common/src/sync/warp.rs
  client/network/src/protocol.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/state.rs
  client/network/sync/src/warp.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12261 rpc: Implement `chainSpec` RPC API
  Cargo.lock
  Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/rpc-servers/src/lib.rs
  client/rpc-spec-v2/Cargo.toml
  client/rpc-spec-v2/README.md
  client/rpc-spec-v2/src/chain_spec/api.rs
  client/rpc-spec-v2/src/chain_spec/chain_spec.rs
  client/rpc-spec-v2/src/chain_spec/mod.rs
  client/rpc-spec-v2/src/chain_spec/tests.rs
  client/rpc-spec-v2/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#12254 Use temporary db for benchmarking
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12230 Bound staking storage items
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#12215 Introduce 'BlockImportParams::insert_intermediate' method
  bin/node/cli/src/service.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/common/src/block_import.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12317 Bump `wasmtime` to 1.0.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  primitives/wasm-interface/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12286 Format templates and fix `--steps` default value
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/pallet/mod.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12083 Make automatic storage deposits resistant against changing deposit prices
  bin/node/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/contracts/fixtures/create_storage_and_call.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/prepare.rs
  frame/support/src/traits/tokens/currency.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D2-notlive 💤

#12148 Pallet safe mode tests
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  frame/remark/src/tests.rs
  frame/safe-mode/Cargo.toml
  frame/safe-mode/src/benchmarking.rs
  frame/safe-mode/src/lib.rs
  frame/safe-mode/src/mock.rs
  frame/safe-mode/src/tests.rs
  frame/safe-mode/src/weights.rs
Labels: A0-pleasereview, A3-needsresolving, B0-silent, C1-low 📌

#12259 Tests for `pallet-tx-pause`
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/tx-pause/Cargo.toml
  frame/tx-pause/src/benchmarking.rs
  frame/tx-pause/src/lib.rs
  frame/tx-pause/src/mock.rs
  frame/tx-pause/src/tests.rs
  frame/tx-pause/src/weights.rs
Labels: A3-needsresolving, B0-silent, C1-low 📌

#12321 pallet-utility: Disallow none origin
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12271 Migrate remaining old decl_* macros to the new pallet attribute macros
  Cargo.lock
  client/rpc/src/dev/tests.rs
  client/service/test/src/client/mod.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/tests_instance.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12283 Rename anonymous to pure proxy
  docs/CHANGELOG.md
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
  frame/proxy/src/weights.rs
Labels: E5-breaksapi, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12223 Nfts: Fix Auto-Increment
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/functions.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12129 Fast Unstake Pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/fast-unstake/Cargo.toml
  frame/fast-unstake/src/benchmarking.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/types.rs
  frame/fast-unstake/src/weights.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12332 bench: Use `_` instead of `::` in auto-generated file names
  frame/benchmarking/README.md
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12319 [Feature] Sequential migration execution for try-runtime
  frame/executive/src/lib.rs
  frame/support/src/traits/hooks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12340 [Fix] parameter_types! dead code errors
  frame/support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12224 Independence of Slot-based algorithms from system Timestamp
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/slots/Cargo.toml
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  primitives/timestamp/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12322 Const impls of base arithmetics for `Weights` with `u64`
  primitives/weights/src/weight_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12168 [Uniques V2] Tips
  bin/node/runtime/src/lib.rs
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/buy_sell.rs
  frame/nfts/src/features/mod.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12329 Add base-weight to `System::Extrinsic*` events
  bin/node/executor/tests/basic.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/lib.rs
  frame/system/src/mock.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12330 Undo removing migration checks
  frame/staking/src/migrations.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12106 Allow specifying immediate finalize for `manual-seal`
  client/consensus/manual-seal/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D2-notlive 💤

#12349 Removed OuterCall alias & doc fixes
  frame/alliance/src/lib.rs
  frame/collective/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/multisig/src/benchmarking.rs
  frame/ranked-collective/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12344 [Enhancement] Remove optional Pool subscription from fast-unstake
  Cargo.lock
  frame/fast-unstake/Cargo.toml
  frame/fast-unstake/src/benchmarking.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11983 Remove discarded blocks and states from database by default
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/testing/src/bench.rs
  client/cli/src/config.rs
  client/cli/src/params/pruning_params.rs
  client/db/benches/state_access.rs
  client/db/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#12352 re-export weight file for fast-unstsake pallet
  frame/fast-unstake/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12264 Move transactions protocol to its own crate
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/beefy/Cargo.toml
  client/beefy/src/lib.rs
  client/cli/Cargo.toml
  client/cli/src/params/network_params.rs
  client/finality-grandpa/src/lib.rs
  client/network/common/Cargo.toml
  client/network/common/src/config.rs
  client/network/common/src/error.rs
  client/network/common/src/lib.rs
  client/network/common/src/service.rs
  client/network/common/src/utils.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/lib.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/network/transactions/Cargo.toml
  client/network/transactions/src/config.rs
  client/network/transactions/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/error.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, A1-onice, B0-silent, C1-low 📌

#12353 export more types from fast-untsake 🤦‍♂️
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12363 Fix compilation on 1.66 nightly
  primitives/state-machine/src/trie_backend_essence.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12360 Relax Slots-based engines from Epochs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/slots/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12342 Pallet staking events to named enum
  frame/nomination-pools/test-staking/src/lib.rs
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12366 [Feature] Add deposit to fast-unstake
  bin/node/runtime/src/lib.rs
  frame/fast-unstake/src/benchmarking.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/types.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12356 Add missing CountedStorageMap in pallet::storage error info
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/test/tests/pallet_ui/storage_not_storage_type.stderr
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12277 Add storage size component to weights
  frame/alliance/src/lib.rs
  frame/babe/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/examples/basic/src/tests.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/tests.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  frame/system/src/limits.rs
  frame/transaction-payment/src/types.rs
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-pleasereview, E5-breaksapi, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E6-transactionversion

#12351 pallet-utility: Only disallow the `None` origin
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#12373 Account for missing `HistoryDepth` in staking migration V12
  frame/staking/src/migrations.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12361 Support running the pallet benchmarks analysis without running the benchmarks
  frame/benchmarking/src/utils.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12379 fix: typo in AllPalletsWithSystem deprecated msg
  frame/support/procedural/src/construct_runtime/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11943 New Pallet: Root offences
  Cargo.lock
  Cargo.toml
  frame/nomination-pools/src/lib.rs
  frame/root-offences/Cargo.toml
  frame/root-offences/README.md
  frame/root-offences/src/lib.rs
  frame/root-offences/src/mock.rs
  frame/root-offences/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12362 bounding staking: `BoundedElectionProvider` trait
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  primitives/npos-elections/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12382 BEEFY: impl `TypeInfo` for `SignedCommitment`
  primitives/beefy/src/commitment.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12313 [Feature] Add a migration that drains and refunds stored calls
  Cargo.lock
  frame/multisig/Cargo.toml
  frame/multisig/src/lib.rs
  frame/multisig/src/migrations.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, E1-runtimemigration

#12383 Properly set the max proof size weight on defaults and tests
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests_composite.rs
  frame/balances/src/tests_local.rs
  frame/balances/src/tests_reentrancy.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/elections-phragmen/src/lib.rs
  frame/executive/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/scheduler/src/mock.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/limits.rs
  frame/system/src/mock.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12388 Carry over where clauses defined in Config to Call and Hook
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12385 unsafe_pruning flag removed
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12072 Remove multisig's Calls
  Cargo.lock
  frame/multisig/Cargo.toml
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/migrations.rs
  frame/multisig/src/tests.rs
Labels: A0-pleasereview, E1-runtimemigration, D9-needsaudit 👮, E6-transactionversion

#12324 pallet-mmr: generate historical proofs
  bin/node/runtime/src/lib.rs
  client/beefy/src/tests.rs
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/tests.rs
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
