Repository paritytech/substrate, pull requests merged in 2022-10, with the labels that each got.

#12358 Remove contracts RPCs
  Cargo.lock
  Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/primitives/Cargo.toml
  frame/contracts/primitives/README.md
  frame/contracts/primitives/src/lib.rs
  frame/contracts/rpc/Cargo.toml
  frame/contracts/rpc/README.md
  frame/contracts/rpc/runtime-api/README.md
  frame/contracts/rpc/src/lib.rs
  frame/contracts/runtime-api/Cargo.toml
  frame/contracts/runtime-api/README.md
  frame/contracts/runtime-api/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A1-onice, B5-clientnoteworthy, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12124 Beefy on-demand justifications as a custom RequestResponse protocol
  client/beefy/rpc/src/lib.rs
  client/beefy/src/communication/gossip.rs
  client/beefy/src/communication/mod.rs
  client/beefy/src/communication/notification.rs
  client/beefy/src/communication/peers.rs
  client/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/beefy/src/communication/request_response/mod.rs
  client/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/beefy/src/import.rs
  client/beefy/src/lib.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/network/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12396 Fix `Weight::is_zero`
  primitives/weights/src/weight_v2.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12402 Remove unnecessary Clone trait bounds on CountedStorageMap
  frame/support/src/storage/types/counted_map.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12406 docs/CODEOWNERS: add @acatangiu as MMR code owner
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#12408 Add @koute to `docs/CODEOWNERS` and update stale paths
  docs/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#12393 BEEFY: Simplify hashing for pallet-beefy-mmr
  Cargo.lock
  frame/beefy-mmr/primitives/Cargo.toml
  frame/beefy-mmr/primitives/src/lib.rs
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12414 client/beefy: small code improvements
  client/beefy/src/communication/mod.rs
  client/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/beefy/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12416 [Fix] Rename VoterBagsList -> VoterList to match pdot
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12418 Use saturating add for alliance::disband witness data
  frame/alliance/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12419 Bump prost to 0.11+
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/network/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/sync/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, E3-dependencies

#12327 Improved election pallet testing
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12285 [Uniques V2] Atomic NFTs swap
  bin/node/runtime/src/lib.rs
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/atomic_swap.rs
  frame/nfts/src/features/mod.rs
  frame/nfts/src/functions.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12421 Adapt `pallet-contracts` to WeightV2
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/contracts/primitives/Cargo.toml
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12423 MMR: impl `TypeInfo` for some structures
  Cargo.lock
  client/beefy/rpc/src/lib.rs
  client/beefy/src/worker.rs
  primitives/beefy/src/mmr.rs
  primitives/merkle-mountain-range/Cargo.toml
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12372 Don't send back empty proofs if light request fails
  client/network/light/src/light_client_requests/handler.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#12397 Implement `Clone` and `Default` for `Config`
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12312 update kvdb & co
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/tempdb.rs
  bin/node/inspect/src/lib.rs
  client/db/Cargo.toml
  client/db/src/upgrade.rs
  client/informant/Cargo.toml
  client/service/Cargo.toml
  client/state-db/Cargo.toml
  client/transaction-pool/Cargo.toml
  frame/support/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/uint.rs
  primitives/database/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/storage/Cargo.toml
  primitives/test-primitives/Cargo.toml
  primitives/trie/Cargo.toml
  primitives/version/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, E3-dependencies, D3-trivial 🧸

#12429 contracts: Adapt dry-run runtime APIs to WeightV2
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/runtime-api/Cargo.toml
  frame/contracts/runtime-api/README.md
  frame/contracts/runtime-api/src/lib.rs
  frame/contracts/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12428 Add pluggable BEEFY payload constructors
  Cargo.lock
  client/beefy/rpc/src/lib.rs
  client/beefy/src/communication/gossip.rs
  client/beefy/src/justification.rs
  client/beefy/src/lib.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  primitives/beefy/Cargo.toml
  primitives/beefy/src/commitment.rs
  primitives/beefy/src/lib.rs
  primitives/beefy/src/mmr.rs
  primitives/beefy/src/payload.rs
  primitives/beefy/src/witness.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12425 reverts for polkadot 0.9.30
  frame/alliance/src/lib.rs
  frame/babe/src/tests.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/examples/basic/src/tests.rs
  frame/executive/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  frame/transaction-payment/src/types.rs
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-pleasereview, A6-revertrevert, B0-silent, C1-low 📌, D3-trivial 🧸

#12282 Maximum value for `MultiplierUpdate`
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12334 macro stubs for all pallet:: macros to improve documentation visibility and discovery + revamp of pallet macro documentation
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview, Q2-easy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12426 Upgrade pin-project
  Cargo.lock
  client/network/Cargo.toml
  client/network/transactions/Cargo.toml
  client/service/Cargo.toml
  client/telemetry/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12386 Extend the lower bounds of some of the benchmarks to also include `0`
  frame/alliance/src/benchmarking.rs
  frame/benchmarking/src/baseline.rs
  frame/bounties/src/benchmarking.rs
  frame/collective/src/benchmarking.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/examples/basic/src/benchmarking.rs
  frame/gilt/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/ranked-collective/src/benchmarking.rs
  frame/staking/src/benchmarking.rs
  frame/system/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12299 BEEFY: Define a `BeefyVerify` trait for signatures
  Cargo.lock
  client/beefy/src/keystore.rs
  frame/beefy-mmr/src/lib.rs
  primitives/beefy/Cargo.toml
  primitives/beefy/src/lib.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12452 Fix ranked voting math comment
  frame/ranked-collective/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12447 Remove "to_block" field from BlockRequests
  client/network/common/src/sync/message.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/schema/api.v1.proto
  client/network/sync/src/warp.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12109 Vesting pallet - make WithdrawReasons configurable
  bin/node/runtime/src/lib.rs
  frame/vesting/README.md
  frame/vesting/src/lib.rs
  frame/vesting/src/mock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#12441 Move block announcement protocol config out of `Protocol`
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/Cargo.toml
  client/network/common/src/config.rs
  client/network/common/src/protocol.rs
  client/network/common/src/protocol/event.rs
  client/network/common/src/protocol/role.rs
  client/network/common/src/sync/message.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/message.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/sync/src/lib.rs
  client/network/test/src/lib.rs
  client/network/transactions/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12449 Dont ignore errors in pallet benchmarking
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12440 Update UI tests for Rust 1.64
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr
  frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_call_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr
  frame/support/test/tests/derive_no_bound_ui/debug.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12467 Some prototyping on top of #12436
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/staking/src/pallet/mod.rs
Labels: A3-inprogress

#12472 Fix flaky service test
  client/network/common/src/config.rs
  client/network/src/service/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12473 Rename `from_components` to `from_parts`
  frame/contracts/src/gas.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/system/src/limits.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12455 Avoid Unstable Sort
  .cargo/config.toml
  bin/node/bench/src/core.rs
  client/rpc-servers/src/lib.rs
  frame/benchmarking/src/analysis.rs
  frame/contracts/src/wasm/runtime.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/examples/basic/src/benchmarking.rs
  primitives/npos-elections/fuzzer/src/common.rs
  utils/frame/benchmarking-cli/src/shared/stats.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12305 Finalized block event triggers tx maintanance
  Cargo.lock
  client/consensus/manual-seal/src/lib.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/api/Cargo.toml
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/benches/basics.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/enactment_state.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/tests.rs
  client/transaction-pool/tests/pool.rs
  primitives/blockchain/src/header_metadata.rs
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12371 WIP safe mode and tx pause {continued}
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  frame/safe-mode/Cargo.toml
  frame/safe-mode/src/benchmarking.rs
  frame/safe-mode/src/lib.rs
  frame/safe-mode/src/mock.rs
  frame/safe-mode/src/tests.rs
  frame/safe-mode/src/weights.rs
  frame/tx-pause/Cargo.toml
  frame/tx-pause/src/benchmarking.rs
  frame/tx-pause/src/lib.rs
  frame/tx-pause/src/mock.rs
  frame/tx-pause/src/tests.rs
  frame/tx-pause/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12481 tx-pool: failing tests fixed
  client/transaction-pool/tests/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12438 Clarify the "direction" field of block requests
  client/network/sync/src/schema/api.v1.proto
Labels: A2-insubstantial, B0-silent, C1-low 📌

#12471 BlockId::Number refactor: trivial changes to BlockId::Hash
  client/consensus/aura/src/lib.rs
  client/db/benches/state_access.rs
  test-utils/runtime/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12456 Dont use benchmark range on constant functions
  frame/examples/basic/src/benchmarking.rs
  frame/examples/basic/src/lib.rs
  frame/examples/basic/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12462 Punish peers for duplicate GRANDPA neighbor messages
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12480 Introduce mockable `ChainSync` object for testing
  Cargo.lock
  client/network/common/src/sync.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/src/service/chainsync_tests.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/lib.rs
  client/network/sync/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12345 pallet-mmr: RPC API and Runtime API work with block numbers
  bin/node/rpc/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/beefy/src/lib.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/tests.rs
  primitives/beefy/src/mmr.rs
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, D2-notlive 💤, D2-breaksapi

#12486 Enable the `wasmtime`-based WASM executor by default
  client/cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12490 Trivial BlockId::Number => Hash
  primitives/api/test/benches/bench.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12488 BlockId removal: refactor: Backend::state_at
  bin/node/bench/src/import.rs
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/db/benches/state_access.rs
  client/db/src/lib.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/blockchain/src/backend.rs
  utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12491 Try-runtime CLI fix weight decoding
  Cargo.lock
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12479 contracts: Export fn code_hash
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12498 pallet-mmr: fix offchain db for sync from zero
  frame/beefy-mmr/src/tests.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
  frame/merkle-mountain-range/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12505 Fix: typo
  README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12256 Upgrade libp2p to 0.49.0
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/tests.rs
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/service.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/offchain/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#12453 Execute try-state at end of each test to ensure pallet data integrity
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12503 implement storage decode length for BTreeSet
  frame/support/src/storage/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12434 Decrease default --out-peers from 25 to 15
  client/cli/src/params/network_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#12466 Prepare for latest clippy (nightly 09-10-2022)
  client/api/src/in_mem.rs
  client/consensus/slots/src/lib.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/network/sync/src/lib.rs
  client/state-db/src/pruning.rs
  client/transaction-pool/src/graph/pool.rs
  frame/transaction-payment/src/lib.rs
  primitives/runtime/src/generic/era.rs
  primitives/runtime/src/offchain/storage_lock.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/trie/src/recorder.rs
  test-utils/runtime/client/src/lib.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12516 derive Serialize/Deserialize for BeefyAuthoritySet
  Cargo.lock
  primitives/beefy/Cargo.toml
  primitives/beefy/src/mmr.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12510 BlockId removal: refactor: StorageProvider
  client/api/src/backend.rs
  client/cli/src/commands/export_state_cmd.rs
  client/finality-grandpa/src/import.rs
  client/rpc/src/state/state_full.rs
  client/service/src/chain_ops/export_raw_state.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  utils/frame/benchmarking-cli/src/block/bench.rs
  utils/frame/benchmarking-cli/src/block/cmd.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12367 [Uniques V2] Feature flags
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/nfts/Cargo.toml
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/atomic_swap.rs
  frame/nfts/src/features/buy_sell.rs
  frame/nfts/src/features/lock.rs
  frame/nfts/src/features/mod.rs
  frame/nfts/src/features/settings.rs
  frame/nfts/src/functions.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/macros.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/nonfungible_v2.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12521 Use `ArgAction::Set` for enable-offchain-indexing flag
  client/cli/src/params/offchain_worker_params.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12212 frame/utils: introduce `substrate-rpc-client` crate for RPC utils
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/tests/common.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/bags-list/remote-tests/src/try_state.rs
  frame/state-trie-migration/src/lib.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
  utils/frame/rpc/client/Cargo.toml
  utils/frame/rpc/client/src/lib.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12519 BlockId removal: refactor: ProofProvider
  client/api/src/proof_provider.rs
  client/network/light/src/light_client_requests/handler.rs
  client/network/sync/src/state_request_handler.rs
  client/rpc/src/state/state_full.rs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12465 registrar: Avoid freebies in provide_judgement
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/identity/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#12237 EPM: allow duplicate submissions
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/migrations.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
Labels: A0-pleasereview, B0-silent, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#12341 CI check against Rust feature bleed
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/runtime/Cargo.toml
  frame/executive/Cargo.toml
  frame/support/procedural/src/pallet/expand/genesis_build.rs
  frame/try-runtime/Cargo.toml
  frame/try-runtime/src/lib.rs
  scripts/ci/gitlab/pipeline/check.yml
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12526 contracts: Decrease the interation count on slow benchmarks
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12528 BlockId removal: refactor: Finalizer
  client/api/src/backend.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/src/finalize_block.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/warp_proof.rs
  client/network/sync/src/lib.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/rpc/src/chain/tests.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  test-utils/client/src/client_ext.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12437 [Uniques V2] Refactor roles
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/lock.rs
  frame/nfts/src/features/mod.rs
  frame/nfts/src/features/roles.rs
  frame/nfts/src/functions.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#12532 some suggestions
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview

#12535 BlockId removal: refactor: BlockImportOperation+Bknd::finalize_block
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/beefy/src/worker.rs
  client/db/src/lib.rs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12524 Remove multiple DHTs support from `Discovery`
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12482 Force base weights to be the minimum only when the intercept is negative
  .maintain/frame-weight-template.hbs
  frame/assets/src/weights.rs
  frame/benchmarking/src/analysis.rs
  frame/uniques/src/weights.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12515 Add `DefensiveTruncateFrom`
  frame/beefy/src/lib.rs
  frame/preimage/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  primitives/core/src/bounded/bounded_vec.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12517 Refactor service tests in `sc-network`
  client/network/src/service.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/src/service/tests/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12114 Actually fix major sync detection
  client/informant/src/display.rs
  client/network/Cargo.toml
  client/network/common/src/service.rs
  client/network/common/src/sync.rs
  client/network/src/service.rs
  client/network/sync/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12541 BlockId removal: refactor: Backend::begin_state_operation
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/db/benches/state_access.rs
  client/db/src/lib.rs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12546 Use headers on weight templates
  .maintain/frame-weight-template.hbs
  scripts/run_all_benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12542 Make `NetworkService` callable for `ChainSync`
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/service/mock.rs
  client/network/sync/src/service/mod.rs
  client/network/sync/src/service/network.rs
  client/network/sync/src/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12545 Use genesis hash- and fork ID-based protocol name for Kademlia
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12553 Normalize keystore type and its usage across tests
  Cargo.lock
  client/beefy/src/tests.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12552 Update template pallet to latest enum syntax
  bin/node-template/pallets/template/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12376 feat: generalize some functions in sp-trie
  client/rpc/src/state/state_full.rs
  client/service/src/client/client.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/trie/src/lib.rs
  primitives/trie/src/storage_proof.rs
  primitives/trie/src/trie_codec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12457 Make Multisig Pallet Bounded
  bin/node/runtime/src/lib.rs
  frame/multisig/src/benchmarking.rs
  frame/multisig/src/lib.rs
  frame/multisig/src/tests.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12494 Fix error during build: failed to run custom build command for sc-net…
  client/network/bitswap/build.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12547 Pallet Assets: move is frozen to asset status
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/migration.rs
  frame/assets/src/types.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12558 Update `pallet-multisig` benches
  frame/multisig/src/lib.rs
  frame/multisig/src/weights.rs
  frame/transaction-payment/src/lib.rs
  frame/utility/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12557 [ci] cargo-check-benches against different base branches
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12571 Fix typo in `membership` docs
  frame/membership/README.md
  frame/membership/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12348 replaced println with log Closes #12338
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12492 Aura: Adds some compatibility mode to support old chains
  bin/node-template/node/src/service.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/service/src/client/client.rs
  primitives/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12506 Utility: add more tests for batch/batchAll/forceBatch
  Cargo.lock
  frame/utility/Cargo.toml
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12573 Treat near-zero intercept values as zero when calculating weights
  frame/benchmarking/src/analysis.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12424 [Enhancement] Convert fast-unstake to use StakingInterface, decouplin…
  bin/node/runtime/src/lib.rs
  frame/fast-unstake/Cargo.toml
  frame/fast-unstake/src/benchmarking.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/types.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  primitives/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12407 nomination-pools: allow pool-ids to be reused
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12280 WIP: Replace `wasm-gc` with `wasm-opt`
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12585 Use `minimum_nominator_bond` instead of `nominator_bond`
  frame/nomination-pools/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12551 BlockId removal: refactor: Backend::append_justification
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/beefy/src/worker.rs
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12584 Gov2 Documentation Typos
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/vote.rs
  frame/ranked-collective/src/lib.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/types.rs
  frame/whitelist/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12590 Added test for Client::block
  client/service/test/src/client/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12593 client/beefy: fix incorrect BEEFY justifications import test
  client/beefy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤
