Repository paritytech/substrate, pull requests merged in 2022-12, with the labels that each got.

#12818 Referendum alarm, test
  frame/referenda/src/lib.rs
  frame/referenda/src/tests.rs
Labels: A0-pleasereview

#12808 Bounties use SpendOrigin
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/lib.rs
  frame/bounties/src/tests.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12749 Reduce provisioner work
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/benchmarking.rs
  bin/node/bench/src/construct.rs
  bin/node/cli/src/benchmarking.rs
  bin/node/cli/src/service.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/src/consensus/timestamp.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  primitives/authorship/src/lib.rs
  primitives/consensus/aura/src/inherents.rs
  primitives/consensus/babe/src/inherents.rs
  primitives/inherents/src/client_side.rs
  primitives/inherents/src/lib.rs
  primitives/timestamp/src/lib.rs
  primitives/transaction-storage-proof/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#12815 Fix quantization in referenda alarm
  frame/referenda/src/lib.rs
  frame/referenda/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12829 Add `Weightless` benchmark bailing
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/utils.rs
  frame/bounties/src/benchmarking.rs
  frame/child-bounties/src/benchmarking.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12813 API for registering inactive funds
  frame/balances/src/lib.rs
  frame/balances/src/migration.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/tokens/fungible.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12832 Tweak to active total migrations
  frame/balances/src/migration.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11776 [WIP][Society] Adding benchmarking to the v2.
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/society/Cargo.toml
  frame/society/src/benchmarking.rs
  frame/society/src/lib.rs
  frame/society/src/migrations.rs
  frame/society/src/mock.rs
  frame/society/src/tests.rs
  frame/society/src/weights.rs
  frame/system/src/lib.rs
Labels: A3-stale

#12365 frame-executive: Reject invalid inherents in the executive
  frame/executive/src/lib.rs
  frame/support/src/dispatch.rs
  frame/system/src/extensions/check_weight.rs
  primitives/runtime/src/transaction_validity.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#12646 Upgrade tokio to 1.22.0 and replace async-std with tokio
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/tests/telemetry.rs
  bin/node/cli/tests/websocket_server.rs
  client/beefy/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/beefy/src/aux_schema.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/cli/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/src/tests.rs
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/src/tests.rs
  client/merkle-mountain-range/Cargo.toml
  client/merkle-mountain-range/src/lib.rs
  client/merkle-mountain-range/src/offchain_mmr.rs
  client/merkle-mountain-range/src/test_utils.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/service.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/src/service/tests/service.rs
  client/network/src/transport.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/service/network.rs
  client/network/sync/src/tests.rs
  client/network/test/Cargo.toml
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/offchain/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-spec-v2/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/test/Cargo.toml
  client/service/test/src/lib.rs
  client/telemetry/Cargo.toml
  client/telemetry/src/transport.rs
  frame/state-trie-migration/Cargo.toml
  test-utils/Cargo.toml
  test-utils/test-crate/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/client/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12610 Non-Interactive Staking
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/Cargo.toml
  bin/node/testing/src/genesis.rs
  frame/gilt/src/benchmarking.rs
  frame/gilt/src/lib.rs
  frame/gilt/src/tests.rs
  frame/nis/Cargo.toml
  frame/nis/README.md
  frame/nis/src/benchmarking.rs
  frame/nis/src/lib.rs
  frame/nis/src/mock.rs
  frame/nis/src/tests.rs
  frame/nis/src/weights.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/tokens/currency/reservable.rs
  frame/support/src/traits/tokens/fungible.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12840 pallet-balances: Fix inactive funds migration
  frame/balances/src/lib.rs
  frame/balances/src/migration.rs
  frame/executive/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12562 client/beefy: add some bounds on enqueued votes
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12842 OpenGov: Abstentions
  frame/conviction-voting/src/tests.rs
  frame/conviction-voting/src/types.rs
  frame/conviction-voting/src/vote.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12848 Add `with_weight` extrinsic
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12806 [contracts] Add per local weight for function call
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12800 contracts: Add `instantiation_nonce` API
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12837 Rename some crates for publishing to crates.io
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/merkle-mountain-range/Cargo.toml
  frame/bags-list/remote-tests/Cargo.toml
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/primitives/Cargo.toml
  frame/beefy/Cargo.toml
  frame/state-trie-migration/Cargo.toml
  primitives/beefy/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A2-insubstantial, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#12834 Whitelist pallet preimage provider upgrade
  bin/node/runtime/src/lib.rs
  frame/whitelist/src/benchmarking.rs
  frame/whitelist/src/lib.rs
  frame/whitelist/src/mock.rs
  frame/whitelist/src/tests.rs
  frame/whitelist/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12795 Remove `mem_info` and references to `parity-util-mem`
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/tempdb.rs
  bin/node/cli/Cargo.toml
  client/api/src/client.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  client/informant/Cargo.toml
  client/informant/src/lib.rs
  client/service/Cargo.toml
  client/service/src/builder.rs
  client/service/src/metrics.rs
  client/state-db/Cargo.toml
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
  client/state-db/src/pruning.rs
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/graph/base_pool.rs
  client/transaction-pool/src/graph/future.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/graph/ready.rs
  client/transaction-pool/src/graph/tracked_map.rs
  client/transaction-pool/src/graph/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/tests/pool.rs
  frame/support/Cargo.toml
  frame/system/src/lib.rs
  primitives/database/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/runtime/src/generic/block.rs
  primitives/runtime/src/generic/digest.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  primitives/runtime/src/transaction_validity.rs
  primitives/test-primitives/Cargo.toml
  primitives/test-primitives/src/lib.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/lib.rs
  scripts/ci/deny.toml
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12822 Mmr persist state
  Cargo.lock
  client/merkle-mountain-range/Cargo.toml
  client/merkle-mountain-range/src/aux_schema.rs
  client/merkle-mountain-range/src/lib.rs
  client/merkle-mountain-range/src/offchain_mmr.rs
  client/merkle-mountain-range/src/test_utils.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12866 Referenda benchmark assert fix
  frame/referenda/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12768 Implement crate publishing on CI
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/inspect/Cargo.toml
  bin/node/primitives/Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/testing/Cargo.toml
  client/merkle-mountain-range/rpc/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/sync/Cargo.toml
  client/network/transactions/Cargo.toml
  client/sync-state-rpc/Cargo.toml
  frame/bags-list/Cargo.toml
  frame/bags-list/fuzzer/Cargo.toml
  frame/bags-list/remote-tests/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/fast-unstake/Cargo.toml
  frame/lottery/Cargo.toml
  frame/nomination-pools/benchmarking/Cargo.toml
  frame/nomination-pools/test-staking/Cargo.toml
  frame/preimage/Cargo.toml
  frame/root-testing/Cargo.toml
  frame/staking/Cargo.toml
  frame/state-trie-migration/Cargo.toml
  frame/transaction-payment/asset-tx-payment/Cargo.toml
  frame/try-runtime/Cargo.toml
  frame/whitelist/Cargo.toml
  primitives/beefy/Cargo.toml
  primitives/weights/Cargo.toml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
  scripts/ci/node-template-release/Cargo.toml
  test-utils/Cargo.toml
  test-utils/client/Cargo.toml
  test-utils/derive/Cargo.toml
  utils/frame/generate-bags/Cargo.toml
  utils/frame/generate-bags/node-runtime/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/client/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12675 zombienet: warp-sync integration test added
  .gitlab-ci.yml
  scripts/ci/docker/subkey.Dockerfile
  scripts/ci/docker/substrate.Dockerfile
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet/0000-block-building/block-building.toml
  zombienet/0000-block-building/block-building.zndsl
  zombienet/0000-block-building/transaction-gets-finalized.js
  zombienet/0001-basic-warp-sync/README.md
  zombienet/0001-basic-warp-sync/chain-spec.json
  zombienet/0001-basic-warp-sync/generate-warp-sync-database.toml
  zombienet/0001-basic-warp-sync/test-warp-sync.toml
  zombienet/0001-basic-warp-sync/test-warp-sync.zndsl
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12798 Move LockableCurrency trait to fungibles::Lockable and deprecate LockableCurrency
  bin/node/runtime/src/lib.rs
  frame/balances/README.md
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/contracts/src/tests.rs
  frame/conviction-voting/src/benchmarking.rs
  frame/conviction-voting/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/executive/src/lib.rs
  frame/referenda/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/support/src/traits.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/tokens/currency/lockable.rs
  frame/support/src/traits/tokens/fungible.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/support/src/traits/tokens/fungibles/lockable.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12782 [pallet-assets] add asset_exists(id: AssetId) function
  frame/assets/src/impl_fungibles.rs
  frame/support/src/traits/tokens/fungibles.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#12868 Introduce sensible weight constants
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  docs/Upgrading-2.0-to-3.0.md
  frame/babe/src/default_weights.rs
  frame/contracts/src/tests.rs
  frame/democracy/src/tests.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/default_weights.rs
  frame/lottery/src/weights.rs
  frame/merkle-mountain-range/src/default_weights.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/mock.rs
  frame/staking/src/mock.rs
  frame/staking/src/tests.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
  frame/support/src/weights/paritydb_weights.rs
  frame/support/src/weights/rocksdb_weights.rs
  frame/system/src/limits.rs
  primitives/weights/src/lib.rs
  utils/frame/benchmarking-cli/src/block/bench.rs
  utils/frame/benchmarking-cli/src/overhead/README.md
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/storage/README.md
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12876 Checkout to the branch HEAD explicitly in `build-linux-substrate`
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12819 cli: Improve pruning documentation
  client/cli/src/params/pruning_params.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12882 Revert "Move LockableCurrency trait to fungibles::Lockable and deprecate LockableCurrency"
  bin/node/runtime/src/lib.rs
  frame/balances/README.md
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/contracts/src/tests.rs
  frame/conviction-voting/src/benchmarking.rs
  frame/conviction-voting/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/executive/src/lib.rs
  frame/referenda/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/support/src/traits.rs
  frame/support/src/traits/tokens/currency.rs
  frame/support/src/traits/tokens/currency/lockable.rs
  frame/support/src/traits/tokens/fungible.rs
  frame/support/src/traits/tokens/fungibles.rs
  frame/support/src/traits/tokens/fungibles/lockable.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12885 Don't indefinitely block on shutting down Tokio
  client/cli/src/runner.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12485 General Message Queue Pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/message-queue/Cargo.toml
  frame/message-queue/src/benchmarking.rs
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/message-queue/src/weights.rs
  frame/scheduler/Cargo.toml
  frame/scheduler/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/messages.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  primitives/core/src/bounded/bounded_vec.rs
  primitives/weights/src/weight_meter.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#12764 Move import queue out of `sc-network`
  Cargo.lock
  client/consensus/common/Cargo.toml
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/common/src/import_queue/buffered_link.rs
  client/consensus/common/src/import_queue/mock.rs
  client/network/common/src/sync.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/lib.rs
  client/network/sync/src/mock.rs
  client/network/sync/src/service/chain_sync.rs
  client/network/sync/src/service/mock.rs
  client/network/sync/src/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
  client/service/src/chain_ops/import_blocks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12886 Trace response payload in default `jsonrpsee` middleware
  client/rpc-servers/src/middleware.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12897 Ensure that we inform all tasks to stop before starting the 60 seconds shutdown
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/runner.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12826 Safe desired targets call
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12900 Fix typo
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12870 ValidateUnsigned: Improve docs.
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12663 rpc server with HTTP/WS on the same socket
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/beefy/rpc/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/lib.rs
  client/merkle-mountain-range/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc-servers/src/middleware.rs
  client/rpc-spec-v2/Cargo.toml
  client/rpc-spec-v2/src/chain_spec/tests.rs
  client/rpc/Cargo.toml
  client/rpc/src/author/tests.rs
  client/rpc/src/chain/tests.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/tests.rs
  client/rpc/src/system/tests.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/rpc/client/Cargo.toml
  utils/frame/rpc/client/src/lib.rs
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12895 `pallet-message-queue`: Fix license
  frame/message-queue/src/benchmarking.rs
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12902 Fix state-db race
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B0-silent, C7-high ❗️, D3-trivial 🧸

#12420 Remove implicit approval chilling upon slash.
  frame/election-provider-multi-phase/src/lib.rs
  frame/offences/benchmarking/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#12905 pallet-contracts migration pre-upgrade fix for v8
  frame/contracts/src/migration.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12912 Use custom environment for publishing crates
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#12845 [contracts] Add debug buffer limit + enforcement
  bin/node/runtime/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12919 [NFTs] Implement missed methods to set the attributes from other pallets
  bin/node/runtime/src/lib.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/support/src/lib.rs
  frame/support/src/traits/tokens/misc.rs
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12899 Fixup some wrong dependencies
  Cargo.lock
  frame/assets/Cargo.toml
  frame/assets/src/lib.rs
  frame/bags-list/src/lib.rs
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/src/lib.rs
  frame/fast-unstake/Cargo.toml
  frame/nomination-pools/Cargo.toml
  frame/nomination-pools/benchmarking/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/pallet/impls.rs
  frame/transaction-payment/asset-tx-payment/Cargo.toml
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  primitives/core/src/lib.rs
  primitives/staking/Cargo.toml
  primitives/staking/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12914 add numerator and denominator to Rational128 Debug impl
  primitives/arithmetic/src/rational.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12927 Fix state-db pinning
  client/db/src/lib.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12922 [ci] add job switcher
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12875 Use LOG_TARGET in consensus related crates
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/aux_schema.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
  client/consensus/slots/src/lib.rs
  client/consensus/slots/src/slots.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/aux_schema.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/until_imported.rs
  frame/aura/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/migrations/v4.rs
Labels: A0-pleasereview, B0-silent, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12889 Staking: store last `min-active-bond` on-chain
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12537 Try-runtime Revamp and Facelift
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/command.rs
  bin/node-template/runtime/src/lib.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  bin/node/runtime/src/lib.rs
  frame/bags-list/remote-tests/src/migration.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/bags-list/remote-tests/src/try_state.rs
  frame/executive/Cargo.toml
  frame/executive/src/lib.rs
  frame/staking/Cargo.toml
  frame/staking/src/pallet/impls.rs
  frame/state-trie-migration/src/lib.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/try_runtime.rs
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/try-runtime/src/lib.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
  primitives/storage/src/lib.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/test_data/proxy_test
  utils/frame/remote-externalities/test_data/proxy_test.top
  utils/frame/rpc/client/src/lib.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/create_snapshot.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/mod.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12920 documentation: add BEEFY 'spec'
  client/beefy/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12894 Warn on missing `pallet::call_index`
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/test/tests/pallet_ui.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.rs
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/call_missing_index.rs
  frame/support/test/tests/pallet_ui/call_missing_index.stderr
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12934 Increase timeout for crates publishing job
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#12937 Node template isn't licensed, remove left-over GPL header
  bin/node-template/node/src/benchmarking.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12931 improve ocw validator/collator CLI description
  client/cli/src/arg_enums.rs
  client/cli/src/params/offchain_worker_params.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12816 Set WASM_BUILD_WORKSPACE_HINT before starting CI jobs
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#12941 Clean up tests from `runtime.block_on()` and moving around `Runtime` and `Handle`
  client/beefy/src/aux_schema.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/src/tests.rs
  client/network-gossip/src/bridge.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/src/service/tests/service.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12949 Fix missing block number issue on forced canonicalization
  client/db/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12952 Defensive traits: Ensure doc tests are also working without `debug_assertions`
  frame/support/src/traits/misc.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12960 Authority discovery: Log when we found addresses for an authority
  client/authority-discovery/src/worker/addr_cache.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12721 `frame_support::storage`: Add `StorageStreamIter`
  frame/support/src/storage/mod.rs
  frame/support/src/storage/stream_iter.rs
  frame/support/src/storage/unhashed.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12962 *: update `rand` to v0.8.5
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/api/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/beefy/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/chain-spec/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/slots/Cargo.toml
  client/db/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/informant/Cargo.toml
  client/merkle-mountain-range/Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/offchain/Cargo.toml
  client/peerset/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/service/test/Cargo.toml
  client/state-db/Cargo.toml
  client/sysinfo/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/node.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/src/mock.rs
  frame/election-provider-support/src/tests.rs
  frame/session/benchmarking/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/benches/bench.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/slots/Cargo.toml
  primitives/core/Cargo.toml
  primitives/io/Cargo.toml
  primitives/npos-elections/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/lib.rs
  primitives/timestamp/Cargo.toml
  primitives/weights/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/generate-bags/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
  utils/prometheus/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12965 ed25519: Don't panic for invalid signature
  Cargo.lock
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12874 `BlockId` removal: refactor: `HeaderBackend::header`
  bin/node/bench/src/construct.rs
  bin/node/cli/src/service.rs
  bin/node/inspect/src/lib.rs
  client/api/src/in_mem.rs
  client/authority-discovery/src/worker/tests.rs
  client/basic-authorship/README.md
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/beefy/src/lib.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/common/src/longest_chain.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/consensus/timestamp.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/db/src/lib.rs
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/import.rs
  client/finality-grandpa/src/justification.rs
  client/finality-grandpa/src/tests.rs
  client/finality-grandpa/src/voting_rule.rs
  client/finality-grandpa/src/warp_proof.rs
  client/merkle-mountain-range/src/test_utils.rs
  client/network/src/protocol.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/sync/src/block_request_handler.rs
  client/network/sync/src/lib.rs
  client/network/test/src/block_import.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/offchain/src/lib.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/dev/mod.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  client/sync-state-rpc/src/lib.rs
  client/tracing/src/block/mod.rs
  client/transaction-pool/benches/basics.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/tests.rs
  primitives/blockchain/src/backend.rs
  primitives/session/src/lib.rs
  test-utils/runtime/client/src/trait_tests.rs
  test-utils/runtime/transaction-pool/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#12950 Remove hardcoded crate versions from tests
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/pallet_instance.rs
Labels: A2-insubstantial, I4-tests 🎯, B0-silent, C1-low 📌, D2-notlive 💤

#12981 BlockId removal: refactor: HeaderBackend::status
  client/api/src/in_mem.rs
  client/authority-discovery/src/worker/tests.rs
  client/consensus/babe/src/lib.rs
  client/db/src/lib.rs
  client/finality-grandpa/src/import.rs
  client/merkle-mountain-range/src/test_utils.rs
  client/service/src/client/client.rs
  primitives/blockchain/src/backend.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12990 no need for deadline
  frame/dex/src/benchmarking.rs
  frame/dex/src/lib.rs
  frame/dex/src/tests.rs
Labels: A0-pleasereview

#12307 Add CallbackHandle to pallet-assets
  bin/node/runtime/src/lib.rs
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/mock.rs
  frame/assets/src/tests.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#12989 Scheduler: remove empty agenda on cancel
  frame/scheduler/src/benchmarking.rs
  frame/scheduler/src/lib.rs
  frame/scheduler/src/migration.rs
  frame/scheduler/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12991 fix kitchen sink
  bin/node/runtime/src/lib.rs
  frame/dex/src/mock.rs
Labels: A0-pleasereview

#12992 txpool: TestApi best_block fix
  client/transaction-pool/tests/pool.rs
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12996 Make migration public
  frame/scheduler/src/migration.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12998 add BenchmarkHelper for second instance
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview

#12999 Mmr client gadget - support pallet reset
  client/merkle-mountain-range/src/aux_schema.rs
  client/merkle-mountain-range/src/lib.rs
  client/merkle-mountain-range/src/offchain_mmr.rs
  client/merkle-mountain-range/src/test_utils.rs
  frame/merkle-mountain-range/src/mmr/storage.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13002 Change crates publishing to be scheduled
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#12997 [NFTs] Add the new `owner` param to mint() method
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/support/src/traits/tokens/nonfungible_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#13007 [contracts] stabilize `[seal0] take_storage`
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12957 [contracts] Remove stack height limiter wasm instrumentation
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/prepare.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13001 Alliance: remove unused func from weight trait
  frame/alliance/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12973 txpool: don't validate block transactions if the pool is empty
  client/transaction-pool/src/graph/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12963 Fix fast-unstake for accounts with slashing
  frame/fast-unstake/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13012 less indirection
  frame/dex/src/benchmarking.rs
  frame/dex/src/lib.rs
Labels: A0-pleasereview

#12971 Runtime diagnostics for leaked messages in unbounded channels
  Cargo.lock
  client/api/src/notifications.rs
  client/beefy/rpc/src/lib.rs
  client/beefy/src/lib.rs
  client/beefy/src/tests.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/common/src/import_queue/buffered_link.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/periodic.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/observer.rs
  client/finality-grandpa/src/until_imported.rs
  client/network/src/service.rs
  client/network/src/service/out_events.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/service/network.rs
  client/network/transactions/Cargo.toml
  client/network/transactions/src/lib.rs
  client/offchain/src/api/http.rs
  client/peerset/src/lib.rs
  client/rpc/src/system/tests.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/task_manager/mod.rs
  client/telemetry/Cargo.toml
  client/telemetry/src/lib.rs
  client/transaction-pool/src/graph/watcher.rs
  client/transaction-pool/src/revalidation.rs
  client/utils/src/mpsc.rs
  client/utils/src/notification.rs
  client/utils/src/notification/tests.rs
  client/utils/src/pubsub.rs
  client/utils/src/pubsub/tests/normal_operation.rs
  client/utils/src/pubsub/tests/panicking_registry.rs
  client/utils/src/status_sinks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13010 Ignore empty authority changes
  frame/aura/src/lib.rs
  frame/babe/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11727 babe: allow skipping over empty epochs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D1-audited 👍

#13018 Allow StakingAdmin to set `min_commission`
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/root-offences/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/staking/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D3-trivial 🧸

#13017 Make CLI state pruning optional again
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/remember_state_pruning_works.rs
  client/cli/src/params/pruning_params.rs
Labels: A0-pleasereview, B0-silent, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#13020 Runtime diagnostics for leaked messages in unbounded channels (part 2)
  Cargo.lock
  client/network/Cargo.toml
  client/network/src/service/out_events.rs
  client/utils/Cargo.toml
  client/utils/src/mpsc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13009 Improve inactive fund tracking
  bin/node/executor/tests/basic.rs
  frame/balances/src/migration.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13022 Print "stalled" task on shutdown
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/runner.rs
  client/service/src/lib.rs
  client/service/src/task_manager/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12967 Add ensure-ops family methods
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#13025 Derive `Debug` on `SyncStatus`
  client/network/common/src/sync.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13029 Enable `zstd` for `rusty-cachier`
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13030 Unpin `ci-linux` and use the latest `production` tag as before
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12539 try-runtime: add cli option --export-proof
  Cargo.lock
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸
