Repository paritytech/substrate, pull requests merged in 2022-05, with the labels that each got.

#11329 Uniques: fix typo in README.md
  frame/uniques/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11336 add conceret types for runtime
  Cargo.lock
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview

#11325 sc-network: update cid v0.6.0 => v0.8.4
  Cargo.lock
  client/network/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11342 Update Pallet Bags List to use `ListError`
  frame/bags-list/fuzzer/src/main.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/tests.rs
  frame/election-provider-support/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11313 Update docs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11337 [contracts] stabilize `seal_code_hash`, `seal_set_code_hash` and `seal_own_code_hash`
  frame/contracts/fixtures/set_code_hash.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, A7-needspolkadotpr, C1-low 📌, D3-trivial 🧸

#11335 BEEFY voter bugfixes
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11346 sc-network: Do not return error on peer id only reserved nodes
  client/network/src/protocol.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10635 Update MMR Runtime API with functionality to generate MMR proof for a series of leaf indices
  bin/node/runtime/src/lib.rs
  client/beefy/src/tests.rs
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/merkle-mountain-range/src/lib.rs
  frame/merkle-mountain-range/src/mmr/mmr.rs
  frame/merkle-mountain-range/src/mmr/mod.rs
  frame/merkle-mountain-range/src/tests.rs
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11311 Customize check-dependent-* for release engineering
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11113 babe: only process vrf on module finalization
  Cargo.lock
  frame/babe/src/lib.rs
  frame/babe/src/randomness.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/vrf/Cargo.toml
  primitives/consensus/vrf/src/schnorrkel.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11358 [ci] fix cargo-check-nixos for nightly pipeline
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11148 Add force_batch to utility pallet
  frame/utility/src/benchmarking.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/utility/src/weights.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#11351 Backfill missing TOML features
  frame/beefy-mmr/Cargo.toml
  frame/benchmarking/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/benchmarking/Cargo.toml
  frame/executive/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/remark/Cargo.toml
  frame/session/benchmarking/Cargo.toml
  frame/transaction-storage/Cargo.toml
  frame/uniques/Cargo.toml
  frame/utility/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/core/hashing/Cargo.toml
  primitives/keystore/Cargo.toml
  primitives/test-primitives/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11349 Add event tests to Nomination Pools
  frame/nomination-pools/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10995 Remove the `--unsafe-pruning` CLI-argument (step 1)
  Cargo.lock
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/cli/tests/benchmark_block_works.rs
  bin/node/cli/tests/check_block_works.rs
  bin/node/cli/tests/export_import_flow.rs
  bin/node/cli/tests/inspect_works.rs
  bin/node/testing/src/bench.rs
  client/api/src/backend.rs
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/pruning_params.rs
  client/db/src/lib.rs
  client/db/src/upgrade.rs
  client/db/src/utils.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/config.rs
  client/service/test/src/client/mod.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#11371 Break the Client reference cycle
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  client/consensus/babe/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11049 Parity-db `Change` missing implementation.
  Cargo.lock
  client/db/Cargo.toml
  client/db/src/parity_db.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11353 allow defensive operations to take a proof
  frame/bags-list/src/list/mod.rs
  frame/staking/src/slashing.rs
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11379 fix: read WS address from substrate output
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  bin/node/cli/tests/temp_base_path_works.rs
Labels: A0-pleasereview

#11378 [contracts] stabilize `seal_contains_storage`(v`seal0`) and `seal_set_storage` (v.`seal1`)
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#11228 Refactory of Fork-Tree data structure
  client/finality-grandpa/src/authorities.rs
  utils/fork-tree/src/lib.rs
Labels: B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11375 sc-consensus-slots: rename `client` -> `select_chain`
  client/consensus/slots/src/slots.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11395 jsonrpc http server: expose health endpoint
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/sync-state-rpc/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11391 Only read storage after origin check
  frame/nomination-pools/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11396 backport: jsonrpc http server: expose health endpoint (#11395)
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/lib.rs
  client/rpc/Cargo.toml
  client/service/Cargo.toml
  client/sync-state-rpc/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌, D3-trivial 🧸

#11394 Whitelist Transactional key
  frame/benchmarking/src/lib.rs
  frame/nomination-pools/src/weights.rs
  frame/support/src/storage/transactional.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11403 Make clippy happy on latest nightly
  bin/utils/chain-spec-builder/src/main.rs
  client/service/src/error.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#11323 [Tests] [pallet-timestamp] Add tests for OnTimestampSet.
  frame/timestamp/src/benchmarking.rs
  frame/timestamp/src/lib.rs
  frame/timestamp/src/mock.rs
  frame/timestamp/src/tests.rs
Labels: A6-seemsok, B0-silent, C1-low 📌, D3-trivial 🧸

#11411 make pool roles optional
  Cargo.lock
  frame/nomination-pools/Cargo.toml
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/src/tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D5-nicetohaveaudit ⚠️

#11383 chore(client/executor): remove unused error InvalidCode and improve docs
  client/executor/common/src/error.rs
  client/executor/src/wasm_runtime.rs
  frame/executive/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11314 serde::{Serialize, Deserialize} for BoundedVec
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11404 Make sure the commit hash is always of the same length in `impl_version`
  utils/build-script-utils/src/version.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11389 Use 'Items' and 'Collections' in uniques pallet
  bin/node/runtime/src/lib.rs
  frame/support/src/traits/tokens/misc.rs
  frame/support/src/traits/tokens/nonfungible.rs
  frame/support/src/traits/tokens/nonfungibles.rs
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/migration.rs
  frame/uniques/src/mock.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/types.rs
  frame/uniques/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11432 Remove `#![allow(deprecated)]` that was fixed
  client/consensus/babe/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11428 More `benchmark machine` args
  bin/node/cli/tests/benchmark_machine_works.rs
  client/sysinfo/src/sysinfo.rs
  utils/frame/benchmarking-cli/src/machine/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11430 Migrate abandoned `prettytable-rs` to `comfy-table`
  Cargo.lock
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/machine/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11377 Add MinPointsToBalance to nomination pools
  bin/node/runtime/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11408 frame_support::pallet_prelude: reexport StorageVersion
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/elections-phragmen/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/membership/src/lib.rs
  frame/session/src/historical/mod.rs
  frame/session/src/lib.rs
  frame/session/src/tests.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/tips/src/lib.rs
  frame/tips/src/tests.rs
  frame/vesting/src/lib.rs
  frame/vesting/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11434 Remove unnecessary RPC boxing
  client/beefy/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/state/state_full.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10719 Explicitly note that existing `AccountIdConversion` is truncating and add fallible `try_into...`
  frame/bounties/src/lib.rs
  frame/child-bounties/src/lib.rs
  frame/lottery/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/society/src/lib.rs
  frame/tips/src/lib.rs
  frame/treasury/src/lib.rs
  primitives/runtime/src/traits.rs
  utils/frame/frame-utilities-cli/src/pallet_id.rs
Labels: E5-breaksapi, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, D2-breaksapi

#11387 generate_storage_alias: Rewrite as proc macro attribute
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/migrations.rs
  frame/contracts/src/migration.rs
  frame/elections-phragmen/src/migrations/v3.rs
  frame/offences/src/migration.rs
  frame/staking/src/migrations.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage_alias.rs
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/weak_bounded_vec.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/system/src/migrations/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11433 Prune some duplicated dependencies in the dependency graph
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/tempdb.rs
  bin/node/bench/src/trie.rs
  client/authority-discovery/Cargo.toml
  client/db/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/sync/Cargo.toml
  client/offchain/Cargo.toml
  client/offchain/src/api/http.rs
Labels: A6-seemsok, B0-silent, C1-low 📌, D3-trivial 🧸

#11429 Return a successful response on repeated small block request
  client/network/sync/src/block_request_handler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11443 fix: regression of `sync_state_genSyncSpec` #11435 (#11437)
  client/sync-state-rpc/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌, D3-trivial 🧸

#11442 [ci] Adjust job order in pipeline test stage with Gitlab DAG
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11441 Allow to set the max supply for collection
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11450 Disable check-dependent-cumulus
  scripts/ci/gitlab/pipeline/build.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11457 trie: Optimize `keys` function
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11448 add GHA support to dependabot
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11422 Make fields of `EraRewardPoints` public
  frame/staking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11436 add missing events to elections fallback
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11455 Fix artifacts after Uniques renames
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11357 Add Score to Bags List
  bin/node/runtime/src/lib.rs
  frame/bags-list/fuzzer/src/main.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/migrations.rs
  frame/bags-list/src/tests.rs
  frame/election-provider-support/src/lib.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#11486 [contracts] Stabilize `seal_ecdsa_recover` and `seal_ecdsa_to_eth_address` functions
  frame/contracts/fixtures/ecdsa_recover.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#11459 RPC: Mark storage methods as `blocking`
  client/rpc-api/src/chain/mod.rs
  client/rpc-api/src/child_state/mod.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11488 InMemoryBackend: Make it generic over the key hasher
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/lib.rs
  primitives/trie/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11469 Unify rpc api and implementation name
  bin/node-template/node/src/rpc.rs
  bin/node/rpc/src/lib.rs
  client/beefy/rpc/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/rpc/src/state/mod.rs
  client/sync-state-rpc/src/lib.rs
  frame/contracts/rpc/src/lib.rs
  frame/merkle-mountain-range/rpc/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
  utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11461 rpc servers CLI: add `--max--subscriptions--per--connection` + fix a few bugs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11492 Make `--dev` listen by default on `/ip4/0.0.0.0/tcp/30333`
  client/cli/src/params/network_params.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11502 Fix State Trie Migration Benchmarks
  frame/state-trie-migration/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11487 Use API for pr-custom-review
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11381 Introduce #[pallet::call_index] attribute to dispatchables
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/call_conflicting_indices.rs
  frame/support/test/tests/pallet_ui/call_conflicting_indices.stderr
  frame/support/test/tests/pallet_ui/call_invalid_attr.rs
  frame/support/test/tests/pallet_ui/call_invalid_attr.stderr
  frame/support/test/tests/pallet_ui/call_invalid_index.rs
  frame/support/test/tests/pallet_ui/call_invalid_index.stderr
  frame/support/test/tests/pallet_ui/call_multiple_call_index.rs
  frame/support/test/tests/pallet_ui/call_multiple_call_index.stderr
Labels: A3-inprogress, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11493 Create Script to Run All Benchmarks
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/conviction-voting/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/nomination-pools/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/recovery/src/weights.rs
  frame/referenda/src/weights.rs
  frame/remark/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/support/src/weights.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  frame/whitelist/src/weights.rs
  scripts/run_all_benchmarks.sh
  utils/frame/benchmarking-cli/src/overhead/weights.hbs
  utils/frame/benchmarking-cli/src/storage/weights.hbs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#11482 Adjust maximum memory pages hard limit for the pooling instantiation strategy
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11454 Optimize offchain worker memory usage a bit.
  client/allocator/src/freeing_bump.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/support/src/storage/types/nmap.rs
  primitives/npos-elections/src/assignments.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11511 CI adjust job `check-dependent-polkadot` rules
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11202 Contracts pallet: removal on idle
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11500 Fix Babe revert when last finalized block is a leaf
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
Labels: A0-pleasereview, I2-bug 🐜, B0-silent, C1-low 📌

#11246 Document benchmarking CLI
  frame/benchmarking/README.md
  utils/frame/benchmarking-cli/README.md
  utils/frame/benchmarking-cli/src/block/README.md
  utils/frame/benchmarking-cli/src/machine/README.md
  utils/frame/benchmarking-cli/src/overhead/README.md
  utils/frame/benchmarking-cli/src/overhead/bench.rs
  utils/frame/benchmarking-cli/src/pallet/README.md
  utils/frame/benchmarking-cli/src/shared/README.md
  utils/frame/benchmarking-cli/src/storage/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11415 Introduce `WeightToFee` trait instead of `WeightToFeePolynomial` and make `WeightToFeePolynomial` implement it instead
  Cargo.lock
  bin/node/executor/tests/fees.rs
  bin/node/runtime/src/impls.rs
  frame/executive/src/lib.rs
  frame/support/src/weights.rs
  frame/transaction-payment/Cargo.toml
  frame/transaction-payment/asset-tx-payment/Cargo.toml
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11476 Fix node lookup on fork-tree after a warp-sync
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11521 Test for the fork-tree post-order DFS traversal requirement
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11431 Storage Layer for All FRAME Extrinsics
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/conviction-voting/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/nomination-pools/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/recovery/src/weights.rs
  frame/referenda/src/weights.rs
  frame/remark/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/state-trie-migration/src/weights.rs
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/dispatch.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/transactional.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/storage_layers.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/lib.rs
  frame/utility/src/tests.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  frame/whitelist/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11507 CI: github no longer checks whitelisted actions this way
  .github/allowed-actions.js
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11531 Fork-Tree import requires post-order DFS traversal
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11535 Fork-Tree import requires post-order DFS traversal (#11531)
  utils/fork-tree/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#11519 Fixed pruning docs
  client/cli/src/params/pruning_params.rs
  client/state-db/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11536 [contracts] Fix broken links in README.md
  frame/contracts/README.md
Labels: A0-pleasereview, I5-documentation 📄, Q0-trivial, B0-silent, C1-low 📌, D3-trivial 🧸

#11490 Safe and sane multi-item storage removal
  Cargo.lock
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/storage_cache.rs
  frame/bags-list/src/list/mod.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/storage.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/im-online/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/slashing.rs
  frame/staking/src/testing_utils.rs
  frame/support/src/lib.rs
  frame/support/src/storage/child.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/migration.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/unhashed.rs
  frame/system/src/lib.rs
  frame/uniques/src/functions.rs
  primitives/externalities/src/lib.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/runtime-interface/Cargo.toml
  primitives/runtime-interface/src/impls.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/overlayed_changes/changeset.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/read_only.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/tasks/src/async_externalities.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C3-medium 📣, E4-newhostfunctions, D5-nicetohaveaudit ⚠️

#11512 sp-core: impl serde for some offchain types
  primitives/core/src/offchain/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11124 Several tweaks needed for Governance 2.0
  Cargo.lock
  bin/node/runtime/src/lib.rs
  docs/Upgrading-2.0-to-3.0.md
  frame/bounties/src/tests.rs
  frame/child-bounties/src/tests.rs
  frame/conviction-voting/src/tests.rs
  frame/conviction-voting/src/types.rs
  frame/identity/src/tests.rs
  frame/referenda/Cargo.toml
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
  frame/referenda/src/types.rs
  frame/scheduler/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/tests.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/voting.rs
  frame/system/src/lib.rs
  frame/tips/src/tests.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
  frame/treasury/src/weights.rs
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/helpers_128bit.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/arithmetic/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#11534 change impl FnOnce() to generic type + trait bound
  frame/support/src/storage/transactional.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11546 Clean up `#[transactional]`
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/test/tests/storage_transaction.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11554 Add `rusty-cachier notify` job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11556 Fix CI after `rusty-cachier` introduction
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11558 Introduce `EnsureOrigin::try_successul_origin`
  frame/collective/src/lib.rs
  frame/society/src/lib.rs
  frame/support/src/traits/dispatch.rs
  frame/system/src/lib.rs
  frame/treasury/src/tests.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11547 Sync: Improve major sync detection
  client/network/sync/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11559 Fix clippy on master
  primitives/arithmetic/src/helpers_128bit.rs
  primitives/arithmetic/src/per_things.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11529 Fix link in node-template README
  bin/node-template/README.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#11562 Short circuit `Treasury::Spend` benchmark for `NeverEnsureOrigin`
  frame/treasury/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
