Repository paritytech/substrate, pull requests merged in 2022-08, with the labels that each got.

#11942 remove unused staking trait bound
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11945 Add and implement MaxEncodedLen to token traits
  frame/support/src/traits/tokens/misc.rs
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11952 Remove `remove_member_wrong_refund` from `phragmen` WeightInfo
  frame/elections-phragmen/src/weights.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#11957 Update the link to the runtime versioning topic
  bin/node-template/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11951 fix(rpc middleware): fix `is_error` bug
  client/rpc-servers/src/middleware.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11890 benchmarking f32 step calculation
  bin/node/cli/tests/benchmark_pallet_works.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11961 [ci] chores: remove cargo install nextest
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11930 Rename `node-runtime` to `node-kitchensink-runtime`
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/bench/src/import.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/cli/src/benchmarking.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  bin/node/executor/Cargo.toml
  bin/node/executor/benches/bench.rs
  bin/node/executor/src/lib.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/common.rs
  bin/node/executor/tests/fees.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/Cargo.toml
  bin/node/testing/Cargo.toml
  bin/node/testing/src/bench.rs
  bin/node/testing/src/client.rs
  bin/node/testing/src/genesis.rs
  bin/node/testing/src/keyring.rs
  bin/utils/subkey/src/main.rs
  docs/README.adoc
  scripts/ci/gitlab/pipeline/test.yml
  utils/frame/generate-bags/node-runtime/Cargo.toml
  utils/frame/generate-bags/node-runtime/src/main.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11939 rpc: Update jsonrpsee v0.15.1
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/rpc/Cargo.toml
  client/beefy/rpc/Cargo.toml
  client/beefy/rpc/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/lib.rs
  client/rpc-api/Cargo.toml
  client/rpc-servers/Cargo.toml
  client/rpc-servers/src/middleware.rs
  client/rpc/Cargo.toml
  client/rpc/src/author/mod.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/chain/mod.rs
  client/rpc/src/dev/tests.rs
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  client/sync-state-rpc/Cargo.toml
  frame/contracts/rpc/Cargo.toml
  frame/merkle-mountain-range/rpc/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/support/Cargo.toml
  utils/frame/rpc/system/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#11956 offences: make fn slash_fraction non-static
  frame/babe/src/equivocation.rs
  frame/grandpa/src/equivocation.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
  primitives/staking/src/offence.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11716 Revert non-best block
  client/api/src/backend.rs
  client/api/src/leaves.rs
  client/db/src/lib.rs
  client/service/src/chain_ops/revert_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11966 Fix docs urls
  README.md
  bin/node-template/README.md
  bin/node-template/docs/rust-setup.md
  bin/node-template/pallets/template/src/lib.rs
  client/rpc-api/src/state/mod.rs
  frame/examples/basic/src/benchmarking.rs
  frame/examples/basic/src/lib.rs
  frame/remark/src/tests.rs
  frame/sudo/README.md
  frame/sudo/src/lib.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits/misc.rs
  primitives/runtime/src/bounded/bounded_vec.rs
  primitives/runtime/src/bounded/weak_bounded_vec.rs
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌, D3-trivial 🧸

#11968 nit improvements to pallet template
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/pallets/template/src/mock.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#11802 Update node-template's docker-compose.yml
  bin/node-template/docker-compose.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#11962 Beefy: use VersionedFinalityProof instead of SignedCommitment
  client/beefy/rpc/src/lib.rs
  client/beefy/rpc/src/notification.rs
  client/beefy/src/import.rs
  client/beefy/src/justification.rs
  client/beefy/src/lib.rs
  client/beefy/src/notification.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11941 Prevent duplicated leaves in the backend
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#11938 Change on-the-wire protocol names to include genesis hash & fork id
  Cargo.lock
  client/network/common/src/request_responses.rs
  client/network/light/Cargo.toml
  client/network/light/src/light_client_requests.rs
  client/network/light/src/light_client_requests/handler.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/src/transactions.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/block_request_handler.rs
  client/network/sync/src/state_request_handler.rs
  client/network/sync/src/warp_request_handler.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#11982 `sync` protocol now can have negotiated fallback name
  client/network/src/protocol.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌

#11979 system_syncState: Always return highest block
  client/rpc-api/src/system/helpers.rs
  client/rpc/src/system/tests.rs
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11934 Rename --pruning and --keep-blocks to be more similar to one another
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/testing/src/bench.rs
  client/cli/src/commands/chain_info_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/pruning_params.rs
  client/db/src/lib.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  client/state-db/src/lib.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D2-notlive 💤

#11985 pallet-contracts: Fix 16bit func_id
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11989 chore(contracts): fix typos and sort trait impls
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11991 contracts: Apply depth limit when decoding
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11993 Restore `wasmtime`'s default stack size limit to 1MB
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
Labels: A0-pleasereview, I2-bug 🐜, B0-silent, C1-low 📌, D3-trivial 🧸

#11998 Add `BoundedVec::sort_by_key`
  primitives/runtime/src/bounded/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11819 Transaction payment runtime api: query call info and fee details
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#11927 transactional: Wrap `pallet::calls` directly in storage layers
  frame/state-trie-migration/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/src/dispatch.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/storage_layers.rs
  frame/transaction-storage/src/lib.rs
  primitives/state-machine/src/basic.rs
  primitives/state-machine/src/overlayed_changes/changeset.rs
  primitives/state-machine/src/overlayed_changes/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#12000 chore: improve runtime executor docs and remove unused error
  Cargo.lock
  client/executor/common/Cargo.toml
  client/executor/common/src/error.rs
  client/executor/src/native_executor.rs
  primitives/runtime-interface/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12010 Fix broken links in `polkadot --help`
  client/cli/src/commands/run_cmd.rs
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌

#11947 add decode with depth limit to opaque types
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#11994 Use correct length for Pallet and Storage prefix when calculating `KeyLenOf`
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11869 Add map and try_map methods to BoundedBTreeMap
  primitives/runtime/src/bounded/bounded_btree_map.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12008 [ci] Improve cancel-pipeline job
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12016 better benchmark log
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11950 feat(rpc middleware): use custom time buckets
  client/rpc-servers/src/middleware.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12013 Add `defer`
  primitives/core/src/defer.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11779 Runtime API versioning
  primitives/api/proc-macro/src/common.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/lib.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/api/test/tests/trybuild.rs
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/impl_missing_version.rs
  primitives/api/test/tests/ui/impl_missing_version.stderr
  primitives/api/test/tests/ui/invalid_api_version_1.rs
  primitives/api/test/tests/ui/invalid_api_version_1.stderr
  primitives/api/test/tests/ui/invalid_api_version_2.stderr
  primitives/api/test/tests/ui/invalid_api_version_3.stderr
  primitives/api/test/tests/ui/invalid_api_version_4.rs
  primitives/api/test/tests/ui/invalid_api_version_4.stderr
  primitives/api/test/tests/ui/method_ver_lower_than_trait_ver.rs
  primitives/api/test/tests/ui/method_ver_lower_than_trait_ver.stderr
  primitives/api/test/tests/ui/missing_versioned_method.rs
  primitives/api/test/tests/ui/missing_versioned_method.stderr
  primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.rs
  primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.stderr
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.rs
  primitives/api/test/tests/ui/mock_advanced_block_id_by_value.stderr
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.rs
  primitives/api/test/tests/ui/mock_advanced_missing_blockid.stderr
  primitives/api/test/tests/ui/mock_only_self_reference.stderr
  primitives/api/test/tests/ui/positive_cases/default_impls.rs
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A3-inprogress, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#12022 Fix Gov V2 Benchmarks
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12026 Add Benchmarking Instance to Pallets
  frame/bags-list/src/benchmarks.rs
  frame/conviction-voting/src/benchmarking.rs
  frame/referenda/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11908 make MAX_VOTERS and MAX_CANDIDATES in elections-phragmen configurable. Fix: #11092
  bin/node/runtime/src/lib.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12028 Further Improve Gov V2 Stuff
  frame/conviction-voting/src/types.rs
  frame/ranked-collective/src/lib.rs
  frame/ranked-collective/src/tests.rs
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/mock.rs
  frame/support/src/traits/voting.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#11813 Proposal: Flatten `AllPallets` and similar types
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/migrations.rs
  frame/support/src/traits.rs
  frame/support/src/traits/filter.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/members.rs
  frame/support/src/traits/metadata.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/storage.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/hooks_invalid_item.stderr
Labels: A0-pleasereview, B3-apinoteworthy, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#11781 swap ed25519-dalek for ed25519-zebra
  Cargo.lock
  Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/ed25519.rs
  primitives/io/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12025 Always wipe DB state after benchmark
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12037 Fix Origins Used in Runtime Benchmarks
  frame/benchmarking/src/lib.rs
  frame/bounties/src/benchmarking.rs
  frame/democracy/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/scheduler/src/benchmarking.rs
  frame/staking/Cargo.toml
  frame/tips/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#12021 benchmark-cli: add child tree support
  bin/node/cli/tests/benchmark_storage_works.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12005 Fix leaf block removal in the backend
  client/api/src/leaves.rs
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12032 contracts: Make chain extension state types public
  frame/contracts/src/chain_extension.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#11670 Replace `T::AccountId` with `<T::Lookup as StaticLookup>::Source`
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/bags-list/src/benchmarks.rs
  frame/bags-list/src/lib.rs
  frame/balances/src/benchmarking.rs
  frame/balances/src/lib.rs
  frame/bounties/src/benchmarking.rs
  frame/bounties/src/lib.rs
  frame/child-bounties/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/conviction-voting/src/benchmarking.rs
  frame/conviction-voting/src/lib.rs
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/lib.rs
  frame/indices/src/benchmarking.rs
  frame/indices/src/lib.rs
  frame/indices/src/tests.rs
  frame/membership/src/lib.rs
  frame/nicks/src/lib.rs
  frame/node-authorization/src/lib.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/proxy/src/benchmarking.rs
  frame/proxy/src/lib.rs
  frame/ranked-collective/src/benchmarking.rs
  frame/ranked-collective/src/lib.rs
  frame/recovery/src/benchmarking.rs
  frame/recovery/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/testing_utils.rs
  frame/sudo/src/lib.rs
  frame/tips/src/benchmarking.rs
  frame/tips/src/lib.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/lib.rs
  frame/vesting/src/benchmarking.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview, E5-breaksapi, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E6-transactionversion, D2-breaksapi

#11407 Introduce trie level cache and remove state cache
  Cargo.lock
  bin/node/bench/src/generator.rs
  bin/node/bench/src/trie.rs
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/testing/src/bench.rs
  client/api/src/backend.rs
  client/basic-authorship/src/basic_authorship.rs
  client/cli/src/commands/chain_info_cmd.rs
  client/cli/src/config.rs
  client/cli/src/params/import_params.rs
  client/db/Cargo.toml
  client/db/benches/state_access.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/record_stats_state.rs
  client/rpc-api/src/dev/error.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/config.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  frame/session/src/historical/mod.rs
  primitives/api/Cargo.toml
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/in_memory_backend.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/proving_backend.rs
  primitives/state-machine/src/read_only.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/transaction-storage-proof/src/lib.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/cache/mod.rs
  primitives/trie/src/cache/shared_cache.rs
  primitives/trie/src/error.rs
  primitives/trie/src/lib.rs
  primitives/trie/src/node_codec.rs
  primitives/trie/src/recorder.rs
  primitives/trie/src/storage_proof.rs
  primitives/trie/src/trie_codec.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12066 Fix broken link to web3 foundation research
  frame/staking/reward-curve/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12015 chore(executor): make allow_missing_host_functions could be configurable
  client/consensus/manual-seal/src/consensus/timestamp.rs
  client/executor/src/native_executor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12068 Fix benchmarks and adds CI to test them
  client/allocator/src/freeing_bump.rs
  frame/democracy/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/offences/benchmarking/src/lib.rs
  frame/proxy/src/benchmarking.rs
  scripts/ci/gitlab/pipeline/test.yml
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12059 Revert "Auto-incremental CollectionId"
  Cargo.lock
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/tests.rs
  frame/uniques/src/weights.rs
Labels: A0-pleasereview, A6-revertrevert, B7-runtimenoteworthy, C1-low 📌, E6-transactionversion, D3-trivial 🧸

#12074 Make Whitelist WeightInfo Pub
  frame/whitelist/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12076 chore(frame/system): fix comment typo `SS85` -> `SS58`
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11888 [contracts] `define_env!` re-write as a proc macro
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12006 Network sync refactoring (part 7)
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/error.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/common/Cargo.toml
  client/network/common/src/config.rs
  client/network/src/config.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/offchain/Cargo.toml
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/rpc/Cargo.toml
  client/rpc/src/system/tests.rs
  client/service/src/config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11889 Sassafras consensus - Prototype 2.1
  Cargo.lock
  bin/node-sassafras/node/Cargo.toml
  bin/node-sassafras/node/src/chain_spec.rs
  bin/node-sassafras/node/src/cli.rs
  bin/node-sassafras/node/src/command.rs
  bin/node-sassafras/node/src/service.rs
  bin/node-sassafras/runtime/Cargo.toml
  bin/node-sassafras/runtime/src/lib.rs
  client/consensus/sassafras/src/authorship.rs
  client/consensus/sassafras/src/aux_schema.rs
  client/consensus/sassafras/src/block_import.rs
  client/consensus/sassafras/src/lib.rs
  client/consensus/sassafras/src/verification.rs
  frame/sassafras/Cargo.toml
  frame/sassafras/src/benchmarking.rs
  frame/sassafras/src/lib.rs
  frame/sassafras/src/mock.rs
  frame/sassafras/src/session.rs
  frame/sassafras/src/tests.rs
  primitives/consensus/sassafras/src/digests.rs
  primitives/consensus/sassafras/src/lib.rs
  primitives/consensus/sassafras/src/vrf.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12075 Print bootnode mismatch message as `warning`
  client/network/src/service.rs
  primitives/trie/src/cache/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#11963 Test bench components with more values
  frame/benchmarking/README.md
  frame/benchmarking/src/lib.rs
  frame/benchmarking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11257 Implement ResultQuery
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/src/lib.rs
  frame/support/src/storage/types/mod.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_ui/storage_result_query_missing_generics.rs
  frame/support/test/tests/pallet_ui/storage_result_query_missing_generics.stderr
  frame/support/test/tests/pallet_ui/storage_result_query_multiple_type_args.rs
  frame/support/test/tests/pallet_ui/storage_result_query_multiple_type_args.stderr
  frame/support/test/tests/pallet_ui/storage_result_query_no_defined_pallet_error.rs
  frame/support/test/tests/pallet_ui/storage_result_query_no_defined_pallet_error.stderr
  frame/support/test/tests/pallet_ui/storage_result_query_parenthesized_generics.rs
  frame/support/test/tests/pallet_ui/storage_result_query_parenthesized_generics.stderr
  frame/support/test/tests/pallet_ui/storage_result_query_wrong_generic_kind.rs
  frame/support/test/tests/pallet_ui/storage_result_query_wrong_generic_kind.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#11818 Allow construct_runtime to take cfg attributes for pallets
  Cargo.lock
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/procedural/src/construct_runtime/expand/event.rs
  frame/support/procedural/src/construct_runtime/expand/inherent.rs
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/procedural/src/construct_runtime/expand/unsigned.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/test/tests/construct_runtime_ui/feature_gated_system_pallet.rs
  frame/support/test/tests/construct_runtime_ui/feature_gated_system_pallet.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_meta_literal.rs
  frame/support/test/tests/construct_runtime_ui/invalid_meta_literal.stderr
  frame/support/test/tests/construct_runtime_ui/unsupported_meta_structure.rs
  frame/support/test/tests/construct_runtime_ui/unsupported_meta_structure.stderr
  frame/support/test/tests/construct_runtime_ui/unsupported_pallet_attr.rs
  frame/support/test/tests/construct_runtime_ui/unsupported_pallet_attr.stderr
  frame/support/test/tests/pallet.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#12110 clone not required as copy.
  frame/support/procedural/src/pallet/parse/storage.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12107 Fix `wasm_export_functions` when using a return statement
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  primitives/core/src/testing.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12100 pin gha versions
  .github/workflows/auto-label-issues.yml
  .github/workflows/auto-label-prs.yml
  .github/workflows/md-link-check.yml
  .github/workflows/monthly-tag.yml
  .github/workflows/release-tagging.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, E3-dependencies

#11995 add negative tests
  frame/alliance/src/tests.rs
Labels: A0-pleasereview

#12089 `try-runtime` - support all state versions
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
  utils/frame/try-runtime/cli/src/parse.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12095 Fix nomination pools pending rewards RPC
  bin/node/runtime/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D2-notlive 💤

#12121 Additional constraints for NotificationSender
  client/network/common/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12102 Make `NetworkService::add_reserved_peer()` accept `MultiaddrWithPeerId`
  client/finality-grandpa/src/communication/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
  client/network/common/src/service.rs
  client/network/src/service.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12139 Fix flaky trie-db cache test
  primitives/trie/src/cache/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#12123 Force `rustix` to use libc
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#11970 Alliance pallet: retirement notice call
  bin/node/runtime/src/lib.rs
  frame/alliance/README.md
  frame/alliance/src/benchmarking.rs
  frame/alliance/src/lib.rs
  frame/alliance/src/migration.rs
  frame/alliance/src/mock.rs
  frame/alliance/src/tests.rs
  frame/alliance/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, E5-breaksapi, C1-low 📌, D2-notlive 💤, D2-breaksapi

#12140 Fix sporadic test failure
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12082 Simplify trait bounds in network to prepare for collator-rpc
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/lib.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/network/common/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/bitswap.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/src/service/tests.rs
  client/network/test/src/lib.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12158 Only log when the transaction is actually to be propagated
  client/network/src/transactions.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸
