Repository paritytech/substrate, pull requests merged in 2022-01, with the labels that each got.

#10571 Remove transaction-pool `test-helpers` feature
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/benches/basics.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/graph/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/tests.rs
  client/transaction-pool/tests/pool.rs
  client/transaction-pool/tests/revalidation.rs
  test-utils/runtime/transaction-pool/Cargo.toml
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10581 Use storage transaction when running with proof recorder
  client/service/src/client/call_executor.rs
  primitives/state-machine/src/backend.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10587 Warn on chain selection error.
  client/finality-grandpa/src/environment.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10463 Name changes for GrandPa and Beefy notifications protocols
  Cargo.lock
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/service.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  bin/utils/chain-spec-builder/src/main.rs
  client/beefy/Cargo.toml
  client/beefy/src/lib.rs
  client/chain-spec/src/chain_spec.rs
  client/chain-spec/src/lib.rs
  client/cli/src/commands/insert_key.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/src/communication/gossip.rs
  client/finality-grandpa/src/communication/mod.rs
  client/finality-grandpa/src/communication/tests.rs
  client/finality-grandpa/src/lib.rs
  client/finality-grandpa/src/tests.rs
  client/network/src/config.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10596 Fix Clippy
  client/chain-spec/src/chain_spec.rs
  client/service/src/client/call_executor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10593 Add benchmark tests for pallet bags list
  frame/bags-list/src/benchmarks.rs
  frame/bags-list/src/weights.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10588 Exclude big changes from file annotations
  .git-blame-ignore-revs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10590 some improvements to bounded vec API
  frame/support/src/storage/bounded_btree_map.rs
  frame/support/src/storage/bounded_btree_set.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10582 contracts: Improve documentation of lazy deletion config
  frame/contracts/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10568 Add BEEFY `latestFinalized` RPC and deduplicate code between BEEFY and GRANDPA
  Cargo.lock
  client/beefy/rpc/Cargo.toml
  client/beefy/rpc/src/lib.rs
  client/beefy/rpc/src/notification.rs
  client/beefy/src/lib.rs
  client/beefy/src/notification.rs
  client/beefy/src/worker.rs
  client/finality-grandpa/rpc/src/lib.rs
  client/finality-grandpa/src/notification.rs
  client/utils/Cargo.toml
  client/utils/src/lib.rs
  client/utils/src/notification.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10606 Fix docs
  frame/balances/src/lib.rs
Labels: A0-pleasereview, I5-documentation 📄, B0-silent, C1-low 📌, D2-notlive 💤

#10497 Add additionally functionality to contracts storage interface
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10612 frame-support: Use logging for printing corrupted state
  frame/support/src/storage/child.rs
  frame/support/src/storage/unhashed.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10615 Add Ord implementation for BoundedVec
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10614 add into function for PrefixIterator
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/counted_map.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10600 code-substitute: Switch from `block_hash` to `block_number`
  client/chain-spec/src/chain_spec.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  client/service/src/client/wasm_substitutes.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10498 Manual Seal: Calculate the block's post hash
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10503 Adds AuraConsensusDataProvider
  Cargo.lock
  Cargo.toml
  bin/node/test-runner-example/Cargo.toml
  bin/node/test-runner-example/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/consensus.rs
  client/consensus/manual-seal/src/consensus/aura.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/consensus/timestamp.rs
  client/consensus/manual-seal/src/error.rs
  test-utils/test-runner/Cargo.toml
  test-utils/test-runner/src/client.rs
  test-utils/test-runner/src/host_functions.rs
  test-utils/test-runner/src/lib.rs
  test-utils/test-runner/src/node.rs
  test-utils/test-runner/src/utils.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10627 frame/bench-cli: fix log formatting
  utils/frame/benchmarking-cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10628 Remove the `bench-test-full-crypto-feature` GHA & GitLab jobs
  .github/workflows/bench_gh_gl.yaml
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10629 Delete Process.json
  Process.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10594 pallet-lottery: add generate_storage_info
  frame/lottery/src/benchmarking.rs
  frame/lottery/src/lib.rs
  frame/lottery/src/tests.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#10637 followup #10594: re-benchmark pallet-lottery
  frame/lottery/src/weights.rs
  frame/preimage/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, D2-notlive 💤

#10620 reset events before apply runtime upgrade
  frame/aura/src/tests.rs
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/contracts/src/tests.rs
  frame/executive/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/merkle-mountain-range/src/tests.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10624 [ci] pipeline chores
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10562 Fast/warp sync fixes
  client/consensus/babe/src/lib.rs
  client/db/src/lib.rs
  client/network/src/protocol/sync.rs
  client/service/src/client/client.rs
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
  primitives/blockchain/src/header_metadata.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10646 Use free balance rather than total balance for elections phragmen
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#10659 Increase default rocksdb cache size
  client/cli/src/config.rs
  utils/frame/benchmarking-cli/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#10640 runtime-interface: Implement `register_only` functions
  primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/runtime-interface/proc-macro/src/utils.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/test-wasm/src/lib.rs
  primitives/runtime-interface/test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10673 Minor tweaks suggested by clippy
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
  test-utils/runtime/transaction-pool/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#10671 Move `EraIndex` to sp-staking
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/slashing.rs
  primitives/staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10656 Improve BoundedVec API (extracted from #10195)
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#10679 the report mod and REPORTING keyType is no longer used
  bin/node/primitives/src/lib.rs
  primitives/core/src/crypto.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10595 contracts: Get rid of the dreaded `Other` error
  frame/contracts/fixtures/invalid_import.wat
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10681 Bump sp-keyring to 4.1.0-dev so that we can publish 4.0.0 in the past
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/testing/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/indices/Cargo.toml
  primitives/keyring/Cargo.toml
  test-utils/client/Cargo.toml
  test-utils/runtime/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10674 Update wasmtime to 0.33.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
  primitives/wasm-interface/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10680 Switch from `pwasm-utils` to `wasm-instrument`
  Cargo.lock
  client/executor/common/Cargo.toml
  client/executor/common/src/runtime_blob/data_segments_snapshot.rs
  client/executor/common/src/runtime_blob/runtime_blob.rs
  frame/contracts/Cargo.toml
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/env_def/macros.rs
  frame/contracts/src/wasm/env_def/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10493 Add feature: `no-metadata-doc` which removes doc from metadata and `full-metadata` which build metadata with all doc
  .gitlab-ci.yml
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/constants.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/types/value.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_compatibility_instance.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#10649 Migration for over locked accounts in phgragmen elections
  frame/elections-phragmen/src/migrations/mod.rs
  frame/elections-phragmen/src/migrations/v5.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, E1-runtimemigration, C1-low 📌, D9-needsaudit 👮

#10677 bench/cli: extend --extrinsic name filtering
  utils/frame/benchmarking-cli/src/command.rs
Labels: A4-awaitingci, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#10693 Minor syntax and typo edits for tx pool docs
  client/transaction-pool/README.md
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌

#10688 Split peer slots between full and light nodes
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/protocol/sync.rs
  client/service/src/builder.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌

#10689 Allow the treasury to have a maximum bound on the bond
  bin/node/runtime/src/lib.rs
  docs/Upgrading-2.0-to-3.0.md
  frame/bounties/src/tests.rs
  frame/child-bounties/src/tests.rs
  frame/tips/src/tests.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#10650 Remove all stale `on_runtime_upgrade` hooks in the runtime
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/offences/src/lib.rs
  frame/offences/src/migration.rs
  frame/staking/src/pallet/mod.rs
  frame/support/src/traits/hooks.rs
  frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.stderr
  frame/uniques/src/lib.rs
  frame/uniques/src/migration.rs
  frame/vesting/src/lib.rs
  frame/vesting/src/migrations.rs
Labels: A0-pleasereview, B0-silent, E1-runtimemigration, C1-low 📌, D3-trivial 🧸

#10701 Improve Force Insert Keep Left for BoundedVec
  frame/support/src/storage/bounded_vec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#10714 Fix typo
  primitives/state-machine/src/overlayed_changes/mod.rs
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌, D3-trivial 🧸

#10700 wasm-builder: Improve workspace handling
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10715 Add `MaxEncodeLen` to `implement_per_thing!`
  frame/support/test/tests/pallet.rs
  primitives/arithmetic/src/per_things.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#10604 Script for publishing rustdocs at gh-pages
  .gitlab-ci.yml
  .maintain/rustdocs-release.sh
  docs/rustdocs-release.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10655 Remove some last `AccountId32::default()` leftovers
  frame/collective/src/lib.rs
  primitives/core/src/crypto.rs
Labels: A7-needspolkadotpr, B0-silent, C1-low 📌, D3-trivial 🧸

#10716 wasm-builder: Enable all features when running `cargo metadata`
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10721 Fix #10688 being misimplemented
  client/network/src/protocol.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10722 Changing the node package to be under @substrate namespace
  .gitlab-ci.yml
  .maintain/rustdocs-release.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10692 Optimized weights
  Cargo.toml
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/tests.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D3-trivial 🧸

#10691 Pre-Charge max size when contracts access storage
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#10361 chore: add example for balance AccountStore
  frame/balances/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#10601 Use proper bounded vector type for nominations
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/helpers.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/elections-phragmen/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/session/benchmarking/src/lib.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  frame/support/src/lib.rs
  frame/support/src/storage/bounded_vec.rs
  frame/support/src/storage/types/counted_map.rs
  frame/system/src/lib.rs
  primitives/npos-elections/fuzzer/src/common.rs
  primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
  primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/mock.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/phragmms.rs
  primitives/npos-elections/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D1-audited 👍

#10696 use `thiserror` instead of `derive_more` for error handling
  Cargo.lock
  bin/node/inspect/Cargo.toml
  bin/node/inspect/src/lib.rs
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/error.rs
  client/beefy/rpc/Cargo.toml
  client/beefy/rpc/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/babe/Cargo.toml
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/error.rs
  client/consensus/pow/Cargo.toml
  client/consensus/pow/src/lib.rs
  client/executor/common/Cargo.toml
  client/executor/common/src/error.rs
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  client/finality-grandpa/rpc/src/error.rs
  client/finality-grandpa/src/authorities.rs
  client/finality-grandpa/src/finality_proof.rs
  client/finality-grandpa/src/warp_proof.rs
  client/keystore/Cargo.toml
  client/keystore/src/lib.rs
  client/network/Cargo.toml
  client/network/src/bitswap.rs
  client/network/src/block_request_handler.rs
  client/network/src/error.rs
  client/network/src/light_client_requests/handler.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/state_request_handler.rs
  client/network/src/warp_request_handler.rs
  client/transaction-pool/api/Cargo.toml
  client/transaction-pool/api/src/error.rs
  client/transaction-pool/src/lib.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/lib.rs
  test-utils/runtime/transaction-pool/Cargo.toml
  test-utils/runtime/transaction-pool/src/lib.rs
  utils/prometheus/Cargo.toml
  utils/prometheus/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10697 basic-authorship: Add new metrics for block size limit and weight limit
  client/basic-authorship/src/basic_authorship.rs
  client/proposer-metrics/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10735 add CheckNonZeroSender in node-template-runtime
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌

#10734 [ci] pipeline chores
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10710 Update Node Template
  Cargo.lock
  bin/node-template/README.md
  bin/node-template/docs/rust-setup.md
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/runtime/Cargo.toml
Labels: A2-insubstantial, I5-documentation 📄, B0-silent, C1-low 📌, D3-trivial 🧸

#10663 better way to resolve `Phase::Emergency` via governance
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#10639 Add stale branches heads to finality notifications
  client/api/src/backend.rs
  client/api/src/client.rs
  client/network/src/protocol/sync/extra_requests.rs
  client/network/test/src/lib.rs
  client/service/src/client/client.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/tests/pool.rs
Labels: A0-pleasereview, B3-apinoteworthy, A7-needspolkadotpr, C1-low 📌

#10742 Arkadi's fix for the 0.9.16 release
  client/network/src/protocol/sync.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  frame/support/src/storage/child.rs
  frame/transaction-storage/src/benchmarking.rs
  test-utils/runtime/src/system.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10737 remote ext: make it possible to use an existing ws connection
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/src/rpc_api.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#10746 Add attributes and documentation to fork_id
  client/chain-spec/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#10725 MEL Fixes for Referenda and Conviction Voting
  frame/conviction-voting/src/conviction.rs
  frame/conviction-voting/src/lib.rs
  frame/conviction-voting/src/types.rs
  frame/conviction-voting/src/vote.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/types.rs
Labels: A0-pleasereview

#10728 Fix lazy batch contract removal
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#10749 Bump `wasm-instrument` 0.1.0 -> 0.1.1
  Cargo.lock
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10757 pallet-scheduler: Fix migrations V2 to V3
  bin/node/cli/src/chain_spec.rs
  bin/node/testing/src/genesis.rs
  frame/democracy/src/tests.rs
  frame/scheduler/src/lib.rs
  frame/scheduler/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10747 Add production profile to `substrate-wasm-builder`
  Cargo.lock
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/gilt/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/multisig/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#10758 Bump `strum` from 0.22 -> 0.23
  Cargo.lock
  client/beefy/Cargo.toml
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-multi-phase/src/lib.rs
  primitives/keyring/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
