Repository paritytech/substrate, pull requests merged in 2023-03, with the labels that each got.

#13479 Speed up storage iteration from within the runtime
  Cargo.lock
  frame/benchmarking/pov/src/benchmarking.rs
  frame/benchmarking/pov/src/lib.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
Labels: A0-please_review, I9-optimisation, B0-silent, C1-low, D3-trivial 🧸

#13490 Make unbounded channels size warning exact (part 1)
  Cargo.lock
  client/network/Cargo.toml
  client/network/src/service/out_events.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13495 sp-consensus: remove unused error variants
  Cargo.lock
  client/consensus/pow/src/lib.rs
  primitives/consensus/common/Cargo.toml
  primitives/consensus/common/src/error.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13488 Expose `ChargedAmount`
  frame/contracts/src/chain_extension.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13494 sc-consensus-beefy: fix metrics: use correct names
  client/consensus/beefy/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low

#13486 Assets pallet: Giving the asset owner the ability to set minimum balance
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/assets/src/weights.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#13493 im-online: don't disable offending validators
  frame/im-online/src/lib.rs
  frame/im-online/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13352 Return account's asset balances
  bin/node/runtime/src/assets_api.rs
  bin/node/runtime/src/lib.rs
  frame/assets/src/functions.rs
  frame/assets/src/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13509 bump API versions of {Beefy,Mmr}Api
  primitives/consensus/beefy/src/lib.rs
  primitives/merkle-mountain-range/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13525 [NFTs] Emit new PalletAttributeSet event
  frame/nfts/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13522 fix feature/enhancement issue template
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13521 Bump parity-db
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A2-insubstantial, B0-silent, D3-trivial 🧸

#13378 Salary pallet
  .gitignore
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/ranked-collective/src/lib.rs
  frame/salary/Cargo.toml
  frame/salary/README.md
  frame/salary/src/benchmarking.rs
  frame/salary/src/lib.rs
  frame/salary/src/tests.rs
  frame/salary/src/weights.rs
  frame/support/src/traits.rs
  frame/support/src/traits/members.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/misc.rs
  primitives/arithmetic/src/traits.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13510 Assets pallet: Don't allow `set_min_balance` when sufficient
  frame/assets/src/benchmarking.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/assets/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13447 bump `zombienet` version to v1.3.37
  .gitlab-ci.yml
  zombienet/0000-block-building/block-building.zndsl
  zombienet/0001-basic-warp-sync/test-warp-sync.zndsl
  zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
  zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.zndsl
Labels: A0-please_review, B0-silent, C1-low, A0-pleasereview

#13533 Just a typo
  frame/message-queue/src/lib.rs
  frame/salary/src/tests.rs
  frame/salary/src/weights.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13462 Update staking related code-owners
  docs/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#13443 [contracts] Forbid calling back to contracts after switching to runtime
  Cargo.lock
  frame/contracts/CHANGELOG.md
  frame/contracts/Cargo.toml
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, C3-medium, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#13547 [CI] Remove redundant trigger-review-pipeline job
  .github/workflows/trigger-review-pipeline.yml
Labels: A2-insubstantial, B0-silent, C1-low

#12828 Extract syncing protocol from `sc-network`
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
  client/cli/src/arg_enums.rs
  client/cli/src/params/network_params.rs
  client/cli/src/params/node_key_params.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/beefy/Cargo.toml
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
  client/consensus/grandpa/src/communication/mod.rs
  client/consensus/grandpa/src/communication/tests.rs
  client/consensus/grandpa/src/environment.rs
  client/consensus/grandpa/src/lib.rs
  client/consensus/grandpa/src/observer.rs
  client/consensus/grandpa/src/tests.rs
  client/informant/src/display.rs
  client/informant/src/lib.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network/common/Cargo.toml
  client/network/common/src/config.rs
  client/network/common/src/protocol/event.rs
  client/network/common/src/service.rs
  client/network/common/src/sync.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/service.rs
  client/network/src/service/metrics.rs
  client/network/src/service/out_events.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/src/service/tests/service.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/engine.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/service/chain_sync.rs
  client/network/sync/src/service/mock.rs
  client/network/sync/src/service/network.rs
  client/network/sync/src/tests.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/network/transactions/src/lib.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/src/metrics.rs
  client/service/test/Cargo.toml
  client/service/test/src/lib.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T2-API

#13539 Expose `new_full_parts_with_genesis_builder` from sc-service
  client/service/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#13504 Make unbounded channels size warning exact (part 2)
  Cargo.lock
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/common/src/import_queue/buffered_link.rs
  client/service/src/task_manager/mod.rs
  client/service/test/Cargo.toml
  client/service/test/src/client/mod.rs
  client/utils/Cargo.toml
  client/utils/README.md
  client/utils/src/lib.rs
  client/utils/src/metrics.rs
  client/utils/src/mpsc.rs
  client/utils/src/notification.rs
  client/utils/src/pubsub.rs
  client/utils/src/pubsub/tests/normal_operation.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13548 Switch to the `blake2b_simd` crate in `sp-core-hashing`
  Cargo.lock
  frame/benchmarking/src/weights.rs
  primitives/core/hashing/Cargo.toml
  primitives/core/hashing/src/lib.rs
Labels: A0-please_review, I9-optimisation, B0-silent, C1-low, D3-trivial 🧸

#13457 remove serde derive for BlockId
  primitives/runtime/src/generic/block.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13379 rpc/chainHead: Fix pruned blocks events from forks
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  client/rpc-spec-v2/src/chain_head/mod.rs
  client/rpc-spec-v2/src/chain_head/subscription.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#13552 core: remove unused localized signature type
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13551 consensus: remove caching functionality from block import pipeline
  bin/node/cli/benches/block_production.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/beefy/src/import.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/common/src/block_import.rs
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/consensus/grandpa/src/import.rs
  client/consensus/grandpa/src/tests.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/seal_block.rs
  client/consensus/pow/src/lib.rs
  client/consensus/pow/src/worker.rs
  client/consensus/slots/src/lib.rs
  client/db/src/lib.rs
  client/network/src/service/tests/mod.rs
  client/network/test/src/lib.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/blockchain/src/backend.rs
  primitives/consensus/common/src/lib.rs
  test-utils/client/src/client_ext.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13528 `MessageQueue`: unknit permanently overweight books
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/message-queue/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#13425 Offences report system rework
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/equivocation.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/src/lib.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
  primitives/consensus/grandpa/src/lib.rs
  primitives/consensus/slots/src/lib.rs
  primitives/staking/src/offence.rs
  test-utils/runtime/src/lib.rs
Labels: B0-silent, C1-low, D2-breaksapi

#13072 fix: Fixes #13071 change order of ldd command and update ./docker/README.md
  docker/README.md
  docker/substrate_builder.Dockerfile
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13560 Undeploy insecure randomness pallet
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
Labels: A0-please_review, A2-insubstantial, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13559 grandpa: send neighbor packets to light clients on set transition
  client/consensus/grandpa/src/communication/gossip.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13517 Make pallet_nfts storages public
  frame/nfts/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13514 Add amalgamation traits for NFT CollectionId and ItemId
  frame/support/src/traits/tokens/nonfungible_v2.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13575 Nfts: Make ItemConfig members public
  frame/nfts/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13576 Nfts: minor fixes
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/misc.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, F3-breaks_API, T2-API

#13503 Logic for the (Core) Fellowship
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/core-fellowship/Cargo.toml
  frame/core-fellowship/README.md
  frame/core-fellowship/src/benchmarking.rs
  frame/core-fellowship/src/lib.rs
  frame/core-fellowship/src/tests.rs
  frame/core-fellowship/src/weights.rs
  frame/salary/src/lib.rs
  frame/system/src/lib.rs
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/traits.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#13578 Fix dependabot labels
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13564 BEEFY: introduce offence report system
  frame/babe/src/equivocation.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy/src/equivocation.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  frame/grandpa/src/equivocation.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  frame/offences/benchmarking/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-breaksapi

#13482 [NFTs] Rework permissions model
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/approvals.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/create_delete_collection.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/lock.rs
  frame/nfts/src/features/metadata.rs
  frame/nfts/src/features/roles.rs
  frame/nfts/src/features/settings.rs
  frame/nfts/src/features/transfer.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/migration.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, E0-runtime_migration, T1-runtime

#13543 pallet-assets callback improvement
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/mock.rs
  frame/assets/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13452 Metadata V15: Expose pallet documentation
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/documentation.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/src/dispatch.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/pallet_doc_arg_non_path.rs
  frame/support/test/tests/pallet_ui/pallet_doc_arg_non_path.stderr
  frame/support/test/tests/pallet_ui/pallet_doc_empty.rs
  frame/support/test/tests/pallet_ui/pallet_doc_empty.stderr
  frame/support/test/tests/pallet_ui/pallet_doc_invalid_arg.rs
  frame/support/test/tests/pallet_ui/pallet_doc_invalid_arg.stderr
  frame/support/test/tests/pallet_ui/pallet_doc_multiple_args.rs
  frame/support/test/tests/pallet_ui/pallet_doc_multiple_args.stderr
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13590 sc-slots: Cleanup
  client/consensus/slots/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13591 [NFTs] Allow to set the role to None
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/roles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13601 update trie dependencies
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
  primitives/api/Cargo.toml
  primitives/core/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/trie/Cargo.toml
  test-utils/runtime/Cargo.toml
  utils/binary-merkle-tree/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13573 sp-api: Support expanding the macro code
  Cargo.lock
  primitives/api/proc-macro/Cargo.toml
  primitives/api/proc-macro/src/common.rs
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/ui/impl_missing_version.stderr
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13555 frame epm: expose `feasibility_check` in MinerConfig
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13128 Nomination Pool Commission
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/fuzzer/src/call.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/src/tests.rs
  frame/nomination-pools/src/weights.rs
  frame/nomination-pools/test-staking/src/mock.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, E0-runtime_migration, T1-runtime

#13341 Pallet dispatchable+storage doc module.
  frame/support/procedural/src/pallet/expand/doc_only.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/src/instances.rs
Labels: A3-in_progress, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13605 timestamp gitlab ci job outputs
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13287 Metadata V15: Expose API to fetch metadata for version
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
  client/rpc/src/state/tests.rs
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/constants.rs
  frame/support/procedural/src/pallet/expand/documentation.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/storage/metadata.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/src/dispatch.rs
  frame/support/src/hash.rs
  frame/support/src/lib.rs
  frame/support/src/metadata_ir/mod.rs
  frame/support/src/metadata_ir/types.rs
  frame/support/src/metadata_ir/v14.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/double_map.rs
  frame/support/src/storage/types/key.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/storage/types/mod.rs
  frame/support/src/storage/types/nmap.rs
  frame/support/src/storage/types/value.rs
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/pallet.rs
  primitives/api/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13613 pin specific version of timestamp script
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13612 Add dedicated `FeePolynomial` struct
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13609 Make Pay trait from salaries pallet more generic
  bin/node/runtime/src/lib.rs
  frame/salary/src/lib.rs
  frame/salary/src/tests.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/pay.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13616 Fix typos in example pallet
  frame/examples/offchain-worker/src/lib.rs
Labels: A2-insubstantial, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#13606 sc-consensus-beefy: improve beefy gossip validator
  client/consensus/beefy/src/aux_schema.rs
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/metrics.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
Labels: A0-please_review, B0-silent, C1-low

#13505 Try to fix flaky `temp-base-path-work` test
  bin/node/cli/tests/benchmark_pallet_works.rs
  bin/node/cli/tests/benchmark_storage_works.rs
  bin/node/cli/tests/common.rs
  bin/node/cli/tests/running_the_node_and_interrupt.rs
  bin/node/cli/tests/telemetry.rs
  bin/node/cli/tests/temp_base_path_works.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#12972 Integration tests for staking + election-provider-multi-phase
  frame/election-provider-multi-phase/test-staking-e2e/Cargo.lock
  frame/election-provider-multi-phase/test-staking-e2e/Cargo.toml
  frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: A0-please_review, I5-tests, B0-silent, C1-low, D2-notlive 💤

#13595 contracts: Simplify benchmarks
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#13615 Keystore overhaul
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/node/rpc/src/lib.rs
  bin/utils/chain-spec-builder/src/main.rs
  client/api/src/execution_extensions.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/error.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/keystore.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/grandpa/src/communication/mod.rs
  client/consensus/grandpa/src/lib.rs
  client/consensus/grandpa/src/observer.rs
  client/consensus/grandpa/src/tests.rs
  client/consensus/manual-seal/src/consensus/babe.rs
  client/keystore/src/local.rs
  client/rpc-api/src/author/error.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  frame/benchmarking/src/baseline.rs
  frame/contracts/src/tests.rs
  frame/examples/offchain-worker/src/tests.rs
  frame/nfts/src/mock.rs
  primitives/application-crypto/test/src/ecdsa.rs
  primitives/application-crypto/test/src/ed25519.rs
  primitives/application-crypto/test/src/sr25519.rs
  primitives/consensus/beefy/src/commitment.rs
  primitives/consensus/beefy/src/witness.rs
  primitives/consensus/grandpa/src/lib.rs
  primitives/io/src/lib.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
  test-utils/client/src/lib.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13622 Bump grandpa to 0.16.2
  Cargo.lock
  client/consensus/grandpa/Cargo.toml
  client/consensus/grandpa/rpc/Cargo.toml
  frame/grandpa/Cargo.toml
  primitives/consensus/grandpa/Cargo.toml
  primitives/consensus/grandpa/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13631 Ignore flaky test
  client/rpc-spec-v2/src/chain_head/tests.rs
  client/service/test/src/client/mod.rs
Labels: A0-please_review, I5-tests, B0-silent, C1-low, D3-trivial 🧸

#13630 Bump `trie-db` to 0.27.1 (fix storage iteration bug + change seek behavior with prefix)
  Cargo.lock
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/trie_backend.rs
Labels: A0-please_review, I3-bug, C3-medium, D3-trivial 🧸, B1-note_worthy, E3-host_functions, T2-API

#13600 contracts: Refactor `trait Ext::*_storage_transparent` functions
  bin/node/executor/tests/basic.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13628 Add linguist-generated to gitattributes
  .gitattributes
  frame/balances/src/weights.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#13651 Hotfix NIS benchmark
  frame/nis/src/benchmarking.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13634 Keystore overhaul (iter 2)
  Cargo.lock
  bin/node-template/node/src/service.rs
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/cli/src/service.rs
  bin/node/executor/tests/submit_transaction.rs
  bin/utils/chain-spec-builder/src/main.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/config.rs
  client/cli/src/params/keystore_params.rs
  client/cli/src/runner.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/Cargo.toml
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/keystore.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/grandpa/src/lib.rs
  client/consensus/grandpa/src/tests.rs
  client/keystore/src/local.rs
  client/rpc/src/author/mod.rs
  client/rpc/src/author/tests.rs
  client/service/src/builder.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
  frame/benchmarking/src/baseline.rs
  frame/contracts/src/tests.rs
  frame/examples/offchain-worker/src/tests.rs
  frame/nfts/src/mock.rs
  primitives/application-crypto/test/src/ecdsa.rs
  primitives/application-crypto/test/src/ed25519.rs
  primitives/application-crypto/test/src/sr25519.rs
  primitives/consensus/beefy/src/commitment.rs
  primitives/consensus/beefy/src/witness.rs
  primitives/consensus/grandpa/src/lib.rs
  primitives/io/src/lib.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13650 frame::executive: `LOG_TARGET` const added
  frame/executive/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#13312 contracts: Upgrade to wasmi 0.28
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13652 zombienet: renamed deprecated transfer function
  zombienet/0000-block-building/transaction-gets-finalized.js
Labels: B0-silent, C1-low, D3-trivial 🧸

#13656 Bump parity-db
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#13635 contracts: Follow up for benchmark simplification
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13663 fix publish docker description ci job
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13664 only push docker descriptions on master branch pipelines
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13649 refactor: state RPC remove `max_rpc_payload_size`
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/tests.rs
  client/service/src/builder.rs
  client/tracing/src/block/mod.rs
Labels: A0-please_review, B0-silent, C1-low

#13669 move back to ci-linux@production image
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13632 fix/chain_head: Ensure correct events for finalized branch
  client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  client/rpc-spec-v2/src/chain_head/subscription.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13558 GetCallIndex trait
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/metadata.rs
  frame/support/test/tests/pallet.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13682 Remove unused trait
  primitives/core/src/traits.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13687 Remove unused light-client leftover
  client/network/sync/src/engine.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13680 chain_head/tests: Check finalized block event before new block
  Cargo.lock
  client/rpc-spec-v2/Cargo.toml
  client/rpc-spec-v2/src/chain_head/mod.rs
  client/rpc-spec-v2/src/chain_head/test_utils.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13683 Keystore overhaul (final)
  bin/node/cli/src/service.rs
  bin/node/executor/tests/submit_transaction.rs
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/worker.rs
  client/consensus/aura/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/grandpa/src/lib.rs
  client/consensus/slots/src/lib.rs
  client/keystore/src/local.rs
  client/rpc/src/author/tests.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/traits.rs
  primitives/application-crypto/test/src/ecdsa.rs
  primitives/application-crypto/test/src/ed25519.rs
  primitives/application-crypto/test/src/sr25519.rs
  primitives/consensus/common/src/error.rs
  primitives/consensus/grandpa/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/io/src/lib.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
  primitives/runtime/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13655 Make ED of zero (kind of) work
  frame/balances/Cargo.toml
  frame/balances/src/lib.rs
  frame/balances/src/tests/currency_tests.rs
  frame/balances/src/tests/mod.rs
  frame/vesting/src/mock.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#13694 try-runtime: Use configured wasm execution method
  client/cli/src/arg_enums.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13709 Fix 'AppCrypto' docs
  primitives/application-crypto/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13700 Get the correct number of connected peers in `SyncState`
  client/informant/src/display.rs
  client/network/common/src/sync.rs
  client/network/sync/src/engine.rs
  client/network/sync/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#12287 Emit event when changing total locked value in pallet-balances
  frame/balances/src/lib.rs
  frame/balances/src/tests/currency_tests.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#13712 Fix failing offences bench test
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13688 chore(sc-cli): improve runner and signals
  client/cli/src/lib.rs
  client/cli/src/runner.rs
  client/cli/src/signals.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13673 add a new ci job to fuzz sp-arithmetic
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13716 sc-slots: Forward block size limit
  client/consensus/slots/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13704 FRAME: Fix the Referenda confirming alarm
  frame/referenda/src/lib.rs
  frame/referenda/src/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13648 contracts: Add host function tracing
  frame/contracts/README.md
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13465 Change license of node-template and FRAME examples to MIT-0
  bin/node-template/LICENSE
  bin/node-template/node/Cargo.toml
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/README.md
  bin/node-template/runtime/Cargo.toml
  frame/examples/basic/Cargo.toml
  frame/examples/basic/README.md
  frame/examples/offchain-worker/Cargo.toml
  frame/examples/offchain-worker/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13557 updating labels descriptions
  docs/CONTRIBUTING.adoc
Labels: A0-please_review, B0-silent

#13735 CI: rephrase `RUSTFLAGS`
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13729 contracts: proper event link in docs
  frame/contracts/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13580 Support stable rust for compiling the runtime
  Cargo.lock
  primitives/io/Cargo.toml
  primitives/io/build.rs
  primitives/io/src/lib.rs
  utils/wasm-builder/README.md
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/prerequisites.rs
  utils/wasm-builder/src/version.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13743 provide a default value for RELENG_SCRIPTS_BRANCH
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13744 roll out new debian 11 ci image
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13739 Swap 'base58' with 'bs58'
  Cargo.lock
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13762 Clean up after debian 11 rollout
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13760 [Fix] Bump tuple element number in frame-support.
  bin/node/runtime/Cargo.toml
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#13746 Application Crypto cleanup
  primitives/application-crypto/src/ecdsa.rs
  primitives/application-crypto/src/ed25519.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/sr25519.rs
  primitives/application-crypto/src/traits.rs
  primitives/core/src/crypto.rs
  primitives/runtime/src/testing.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13748 Fix nomiantion pools doc render
  frame/nomination-pools/src/lib.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#13770 sp-runtime-interface-test: Fix flaky test
  primitives/runtime-interface/test/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13772 Bump zombienet version
  .gitlab-ci.yml
Labels: A0-please_review, B0-silent, C1-low

#13702 [Contracts] Overflowing bounded `DeletionQueue` allows DoS against contract termination
  bin/node/runtime/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13764 Refactor: extract most aura logic out to standalone module, make use of these
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/aura/src/standalone.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T0-node

#13776 contracts: make test work with debugger
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸
