Repository paritytech/substrate, pull requests merged in 2023-01, with the labels that each got.

#13014 BlockId removal: refactor: BlockBackend::block|block_status
  client/api/src/client.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/network/sync/src/lib.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc/src/chain/chain_full.rs
  client/rpc/src/dev/mod.rs
  client/service/src/chain_ops/check_block.rs
  client/service/src/chain_ops/export_blocks.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/consensus/common/src/block_validation.rs
  utils/frame/benchmarking-cli/src/block/bench.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13036 Forbid stray tokens in call index
  frame/support/procedural/src/pallet/parse/call.rs
  frame/support/test/tests/pallet_ui/call_index_has_suffix.rs
  frame/support/test/tests/pallet_ui/call_index_has_suffix.stderr
  frame/support/test/tests/pallet_ui/weight_argument_has_suffix.rs
  frame/support/test/tests/pallet_ui/weight_argument_has_suffix.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13050 remove dex PR's custom RPC
  Cargo.lock
  Cargo.toml
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/dex/Cargo.toml
  frame/dex/rpc/Cargo.toml
  frame/dex/rpc/README.md
  frame/dex/rpc/runtime-api/Cargo.toml
  frame/dex/rpc/runtime-api/README.md
  frame/dex/rpc/runtime-api/src/lib.rs
  frame/dex/rpc/src/lib.rs
  frame/dex/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13053 dex child PR: no longer a need to upgrade rpc version
  Cargo.lock
  bin/node/executor/Cargo.toml
  client/rpc-api/Cargo.toml
  client/rpc/Cargo.toml
  client/tracing/Cargo.toml
  frame/transaction-payment/rpc/Cargo.toml
  primitives/rpc/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#12728 Use #[pallet::storage_version] for pallet staking
  frame/staking/src/lib.rs
  frame/staking/src/migrations.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, E1-runtimemigration, C1-low 📌, D3-trivial 🧸

#13052 Enrich TooManySiblingBlocks error info
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13051 Do not run `forced_canonicalization` for archive nodes
  client/db/src/lib.rs
  client/state-db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12839 remove unused constant: MaxValueSize
  bin/node/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#13056 Fix NFTs pallet's integration issues
  frame/nfts/Cargo.toml
  frame/nfts/src/lib.rs
  frame/nfts/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13054 Disallow burning externally locked nfts
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/lib.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13055 Allow to clear nft attributes via traits
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/tests.rs
  frame/support/src/traits/tokens/nonfungible_v2.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13045 Selectable on-runtime-upgrade checks
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/executive/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/try_runtime.rs
  frame/try-runtime/src/lib.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
Labels: A0-pleasereview, A7-needspolkadotpr, B5-clientnoteworthy, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12477 grandpa: pass the actual best block to voting rules
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13043 Remove `Copy` from `Ensure*` traits
  primitives/arithmetic/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13058 Aura: Do not verify on state import
  client/consensus/aura/src/import_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12734 upgrade libp2p to 0.50.0
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/runner.rs
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/transport.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/offchain/Cargo.toml
  client/peerset/Cargo.toml
  client/telemetry/Cargo.toml
  client/telemetry/src/transport.rs
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13064 grandpa: remove deprecated afg log target
  client/finality-grandpa/src/lib.rs
  client/tracing/src/logging/mod.rs
  frame/grandpa/src/lib.rs
  primitives/finality-grandpa/Cargo.toml
  primitives/finality-grandpa/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13066 Return `RuntimeVersion` of overwritten/substituted wasm binary
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  client/service/src/client/wasm_substitutes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13074 aura: remove stale check to skip execution
  client/consensus/aura/src/import_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13081 Kademlia: Speed-up the record fetching
  client/network/src/discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13032 [contracts] Add docs generator for the contracts API to the `#[define_env]` macro
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13073 Update trybuild to avoid random test failures.
  Cargo.lock
  frame/election-provider-support/solution-type/Cargo.toml
  frame/support/test/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/runtime-interface/Cargo.toml
  test-utils/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13086 Do not leak records
  client/network/src/discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12790 Only use `substrate-wasm-builder` when `std` feature is enabled.
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/build.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/build.rs
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/build.rs
  primitives/runtime-interface/test-wasm-deprecated/Cargo.toml
  primitives/runtime-interface/test-wasm-deprecated/build.rs
  primitives/runtime-interface/test-wasm/Cargo.toml
  primitives/runtime-interface/test-wasm/build.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/build.rs
  utils/wasm-builder/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13080 grandpa: bump version to v0.16.1
  Cargo.lock
  client/finality-grandpa/Cargo.toml
  client/finality-grandpa/rpc/Cargo.toml
  frame/grandpa/Cargo.toml
  primitives/finality-grandpa/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13090 Remove unused finalization_displaced variable in db
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13091 Remove unused mock types
  frame/atomic-swap/src/tests.rs
  frame/aura/src/mock.rs
  frame/authority-discovery/src/lib.rs
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/collective/src/tests.rs
  frame/conviction-voting/src/tests.rs
  frame/examples/basic/src/tests.rs
  frame/examples/offchain-worker/src/tests.rs
  frame/grandpa/src/mock.rs
  frame/identity/src/tests.rs
  frame/im-online/src/mock.rs
  frame/indices/src/mock.rs
  frame/membership/src/lib.rs
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/mock.rs
  frame/multisig/src/tests.rs
  frame/nicks/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/offences/src/mock.rs
  frame/preimage/src/mock.rs
  frame/proxy/src/tests.rs
  frame/randomness-collective-flip/src/lib.rs
  frame/ranked-collective/src/tests.rs
  frame/recovery/src/mock.rs
  frame/referenda/src/mock.rs
  frame/root-offences/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/session/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/src/mock.rs
  frame/sudo/src/mock.rs
  frame/system/benches/bench.rs
  frame/timestamp/src/mock.rs
  frame/treasury/src/tests.rs
  frame/vesting/src/mock.rs
  frame/whitelist/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13092 Run `frame_system` integrity tests in Externalities
  frame/system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13089 [trivial] add note on usage of twox hash
  frame/fast-unstake/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/staking/src/pallet/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13035 EPM and staking events improvement
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/src/unsigned.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13042 Add ensure_pow method
  primitives/arithmetic/src/traits.rs
  primitives/runtime/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13111 Add solution hint to error message
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/procedural/src/pallet/expand/storage.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13088 Avoid unintentionally canceling the scheduled crate publishing job
  .gitlab-ci.yml
  scripts/ci/gitlab/crate-publishing-pipeline.yml
  scripts/ci/gitlab/default-pipeline.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#13116 introduce log-target constant to more frame pallets
  frame/assets/src/lib.rs
  frame/assets/src/migration.rs
  frame/balances/src/lib.rs
  frame/balances/src/migration.rs
  frame/collective/src/lib.rs
  frame/collective/src/migrations/v4.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/migrations/v3.rs
  frame/elections-phragmen/src/migrations/v4.rs
  frame/membership/src/lib.rs
  frame/membership/src/migrations/v4.rs
  frame/session/src/migrations/v1.rs
  frame/system/src/lib.rs
  frame/system/src/migrations/mod.rs
  frame/tips/src/lib.rs
  frame/tips/src/migrations/v4.rs
  frame/uniques/src/lib.rs
  frame/uniques/src/migration.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13118 Update tests for 1.66 and switch CI to stable Rust 1.66
  .gitlab-ci.yml
  frame/support/test/tests/construct_runtime_ui/invalid_module_details.stderr
  frame/support/test/tests/derive_no_bound.rs
  frame/support/test/tests/pallet_ui/call_invalid_return.stderr
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13065 Allow duplicate topics in smart contract events
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13124 [NFTs] Track item's metadata depositor
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/create_delete_collection.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/metadata.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#13094 `IntegrityTest` implementation should be feature gated
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/lib.rs
  frame/system/benches/bench.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13105 Scheduler is already at V4
  frame/referenda/src/migration.rs
  frame/scheduler/src/lib.rs
  frame/scheduler/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#12857 Optimize merkle proofs for efficient verification in Solidity
  frame/beefy-mmr/primitives/src/lib.rs
  frame/beefy-mmr/src/tests.rs
  frame/merkle-mountain-range/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13130 [easy-but-important] client/beefy: fix logs
  client/beefy/src/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13127 Stop keeping track of epoch changes for the sync gap
  client/consensus/babe/src/lib.rs
  client/consensus/epochs/src/lib.rs
  client/consensus/epochs/src/migration.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13134 CI: Unpin `ci-linux` and use Rust 1.66.1
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13131 sp-beefy: align authority id key type with its signature type
  client/beefy/src/keystore.rs
  primitives/beefy/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13136 Use balance trait in transaction-payment pallets
  frame/transaction-payment/asset-tx-payment/src/payment.rs
  frame/transaction-payment/src/payment.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13139 CI: Code mark to request a pipeline failure
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13144 Annotate thiserror for sp_core::crypto::SecretStringError
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13153 More improvements for the crate publishing pipeline
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#13004 txpool: don't maintain the pool during major sync
  Cargo.lock
  client/transaction-pool/Cargo.toml
  client/transaction-pool/src/enactment_state.rs
  client/transaction-pool/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13152 [client/network] Add support for `/wss` addresses
  client/network/src/transport.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12928 NIS should retain funds in reserve
  bin/node/runtime/src/lib.rs
  frame/nis/src/benchmarking.rs
  frame/nis/src/lib.rs
  frame/nis/src/mock.rs
  frame/nis/src/tests.rs
  frame/nis/src/weights.rs
  frame/support/src/traits/tokens/fungible.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13150 Breakout mock runtimes to separate files
  frame/transaction-payment/asset-tx-payment/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/mock.rs
  frame/transaction-payment/asset-tx-payment/src/tests.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-payment/src/mock.rs
  frame/transaction-payment/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13161 frame-benchmarking: Macros should not force a particular env
  bin/node/runtime/src/lib.rs
  frame/benchmarking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13154 Fix the `storage_size`/`state_getStorageSize` RPC call
  client/api/src/backend.rs
  client/rpc-api/src/state/mod.rs
  client/rpc/Cargo.toml
  client/rpc/src/state/mod.rs
  client/rpc/src/state/state_full.rs
  client/rpc/src/state/tests.rs
  client/rpc/src/state/utils.rs
  client/service/src/client/client.rs
Labels: A0-pleasereview, B3-apinoteworthy, I7-footprint 👣, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#13015 zobmienet tests are not supposed to fail
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12993 [contracts] Add integrity checks by pallet hook
  bin/node/runtime/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12707 Expose `UnknownBlock` error via `ApiError`
  primitives/api/src/lib.rs
  primitives/blockchain/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13157 Notification-based block pinning
  Cargo.lock
  client/api/src/backend.rs
  client/api/src/client.rs
  client/api/src/in_mem.rs
  client/db/Cargo.toml
  client/db/src/lib.rs
  client/db/src/pinned_blocks_cache.rs
  client/finality-grandpa/src/until_imported.rs
  client/service/src/builder.rs
  client/service/src/client/client.rs
  test-utils/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13181 contracts: Remove fixtures from crate
  frame/contracts/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13180 txpool: LOG_TARGET const added
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/src/api.rs
  client/transaction-pool/src/enactment_state.rs
  client/transaction-pool/src/graph/base_pool.rs
  client/transaction-pool/src/graph/listener.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/graph/ready.rs
  client/transaction-pool/src/graph/validated_pool.rs
  client/transaction-pool/src/lib.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/tests/pool.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13183 Fix potential huge allocation as a result of `validate_block` output
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/runtime-test/Cargo.toml
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13185 sc-network: Ensure private addresses are disabled if requested
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#12620 Warn validators with slow hardware
  bin/node/cli/src/service.rs
  client/sysinfo/src/lib.rs
  client/sysinfo/src/sysinfo.rs
  utils/frame/benchmarking-cli/src/lib.rs
  utils/frame/benchmarking-cli/src/machine/hardware.rs
  utils/frame/benchmarking-cli/src/machine/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#13193 Use year 2023 in the License headers
  HEADER-APACHE2
  HEADER-GPL3
Labels: A2-insubstantial, A3-inprogress, B0-silent, C1-low 📌, D2-notlive 💤

#13198 Move slow hardware warning print logic to CLI
  bin/node/cli/src/service.rs
  client/sysinfo/src/sysinfo.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13191 dex quote bugfix
  frame/dex/src/lib.rs
  frame/dex/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13199 Fix flaky BABE test
  client/consensus/babe/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#12979 Add debug info in assert_has_event and assert_last_event
  frame/system/src/lib.rs
Labels: A2-insubstantial, A3-stale, B0-silent, C1-low 📌, D3-trivial 🧸

#12924 new proc-macro-based benchmarking syntax
  Cargo.lock
  frame/balances/src/benchmarking.rs
  frame/examples/basic/src/benchmarking.rs
  frame/message-queue/src/benchmarking.rs
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/benchmark.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/benchmark_ui.rs
  frame/support/test/tests/benchmark_ui/bad_param_name.rs
  frame/support/test/tests/benchmark_ui/bad_param_name.stderr
  frame/support/test/tests/benchmark_ui/bad_param_name_too_long.rs
  frame/support/test/tests/benchmark_ui/bad_param_name_too_long.stderr
  frame/support/test/tests/benchmark_ui/bad_param_name_upper_case.rs
  frame/support/test/tests/benchmark_ui/bad_param_name_upper_case.stderr
  frame/support/test/tests/benchmark_ui/bad_param_range.rs
  frame/support/test/tests/benchmark_ui/bad_param_range.stderr
  frame/support/test/tests/benchmark_ui/bad_params.rs
  frame/support/test/tests/benchmark_ui/bad_params.stderr
  frame/support/test/tests/benchmark_ui/dup_block.rs
  frame/support/test/tests/benchmark_ui/dup_block.stderr
  frame/support/test/tests/benchmark_ui/dup_extrinsic_call.rs
  frame/support/test/tests/benchmark_ui/dup_extrinsic_call.stderr
  frame/support/test/tests/benchmark_ui/extra_extra.rs
  frame/support/test/tests/benchmark_ui/extra_extra.stderr
  frame/support/test/tests/benchmark_ui/extra_skip_meta.rs
  frame/support/test/tests/benchmark_ui/extra_skip_meta.stderr
  frame/support/test/tests/benchmark_ui/extrinsic_call_out_of_fn.rs
  frame/support/test/tests/benchmark_ui/extrinsic_call_out_of_fn.stderr
  frame/support/test/tests/benchmark_ui/missing_call.rs
  frame/support/test/tests/benchmark_ui/missing_call.stderr
  frame/support/test/tests/benchmark_ui/missing_origin.rs
  frame/support/test/tests/benchmark_ui/missing_origin.stderr
  frame/support/test/tests/benchmark_ui/pass/valid_basic.rs
  frame/support/test/tests/benchmark_ui/unrecognized_option.rs
  frame/support/test/tests/benchmark_ui/unrecognized_option.stderr
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#13208 Rename `*-private-ipv4` to `*-private-ip` CLI args
  client/cli/src/params/network_params.rs
  client/network/common/src/config.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
  client/service/test/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#13213 Remove dead code
  client/db/src/storage_cache.rs
Labels: A0-pleasereview, I6-refactor 🧹, B0-silent, C1-low 📌, D3-trivial 🧸

#13214 [Fix] CountedMap::set now takes Counter into account
  frame/support/src/storage/types/counted_map.rs
  frame/support/src/storage/types/map.rs
Labels: A0-pleasereview, B3-apinoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#13217 Debug assert events at genesis
  frame/system/src/lib.rs
  frame/system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13173 BlockId removal: refactor: CallExecutor trait
  client/api/src/call_executor.rs
  client/finality-grandpa/src/lib.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc/src/state/state_full.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/src/client/wasm_substitutes.rs
  primitives/version/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13082 service: storage monitor added
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/cli/src/service.rs
  client/cli/src/params/database_params.rs
  client/service/Cargo.toml
  client/service/src/error.rs
  client/storage-monitor/Cargo.toml
  client/storage-monitor/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#13038 Upgrade wasm-opt to 0.111.0
  Cargo.lock
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13234 storage-monitor: statvfs arithmetic bug fixed
  client/storage-monitor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13226 Bump parity-db
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13229 pallet-assets: Rename `total_supply` to `amount`
  frame/assets/src/benchmarking.rs
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#13135 Babe: bad epoch index with skipped epochs and warp sync
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
Labels: A0-pleasereview, I2-bug 🐜, B0-silent, C1-low 📌, D3-trivial 🧸

#13204 contracts: Deprecate random interface
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/benchmarking/sandbox.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#13236 [contracts] Add upfront weight of merkle trie proofs for storage reading functions
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#13238 CI: Rewrite `check-each-crate` in python
  scripts/ci/gitlab/check-each-crate.py
  scripts/ci/gitlab/check-each-crate.sh
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13223 Fix try-runtime with create-snapshot
  utils/frame/try-runtime/cli/src/commands/create_snapshot.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13120 reduce exec time of fast-unstake benchmarks
  bin/node/runtime/src/lib.rs
  frame/fast-unstake/src/benchmarking.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#12982 Rework the trie cache
  Cargo.lock
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/finality-grandpa/Cargo.toml
  client/network-gossip/Cargo.toml
  primitives/state-machine/src/trie_backend.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/cache/mod.rs
  primitives/trie/src/cache/shared_cache.rs
Labels: A0-pleasereview, I2-bug 🐜, I6-refactor 🧹, I7-optimisation ⏱, I7-footprint 👣, B0-silent, C1-low 📌, D3-trivial 🧸

#13240 Add task type label to task metrics
  client/service/src/task_manager/mod.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low 📌, D3-trivial 🧸

#13230 upgrade nix to 0.26.1
  Cargo.lock
  bin/node/cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13110 Add WeightToFee and LengthToFee impls to transaction-payment Runtime API
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#13194 Correct arithmetical semantic of `PerDispatchClass`
  frame/support/src/dispatch.rs
  frame/support/src/weights.rs
  frame/system/src/extensions/check_weight.rs
  frame/system/src/lib.rs
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13221 Aura: Fix warp syncing
  client/consensus/aura/src/import_queue.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13008 Refactor nft fractionalisation pallet
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/assets/src/functions.rs
  frame/assets/src/impl_fungibles.rs
  frame/nft-fractionalisation/README.md
  frame/nft-fractionalisation/src/lib.rs
  frame/nft-fractionalisation/src/mock.rs
  frame/nft-fractionalisation/src/tests.rs
  frame/nft-fractionalization/Cargo.toml
  frame/nft-fractionalization/README.md
  frame/nft-fractionalization/src/benchmarking.rs
  frame/nft-fractionalization/src/lib.rs
  frame/nft-fractionalization/src/mock.rs
  frame/nft-fractionalization/src/tests.rs
  frame/nft-fractionalization/src/types.rs
  frame/nft-fractionalization/src/weights.rs
  frame/support/src/traits/tokens/fungibles/metadata.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13209 Use non-binary pronouns in comments.
  bin/utils/subkey/README.md
  client/beefy/src/tests.rs
  client/consensus/babe/src/lib.rs
  docs/README.adoc
  frame/contracts/src/exec.rs
  frame/elections-phragmen/src/benchmarking.rs
  frame/nfts/src/features/transfer.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/test-staking/src/lib.rs
  frame/root-offences/src/tests.rs
  frame/staking/src/tests.rs
  frame/uniques/src/functions.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13245 mutate_exists for StorageValue with ValueQuery
  frame/support/src/lib.rs
  frame/support/src/storage/generator/value.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/value.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13247 Fix derive PassByInner with generics
  primitives/runtime-interface/proc-macro/src/pass_by/inner.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13241 docs: Fix broken documentation links for pallets
  frame/multisig/README.md
  frame/multisig/src/lib.rs
  frame/nicks/README.md
  frame/proxy/README.md
  frame/sudo/README.md
  frame/utility/README.md
  frame/vesting/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13249 sc-finality-grandpa: Warp proof generation can not expect justifications
  client/cli/src/params/pruning_params.rs
  client/finality-grandpa/src/warp_proof.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13142 *: update criterion to v0.4.0
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/executor/Cargo.toml
  client/db/Cargo.toml
  client/executor/Cargo.toml
  client/tracing/Cargo.toml
  client/transaction-pool/Cargo.toml
  frame/system/Cargo.toml
  primitives/api/test/Cargo.toml
  primitives/arithmetic/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/benches/bench.rs
  primitives/trie/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13205 Fix Up Node Template
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13216 Remove `uncles` related code
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/service.rs
  bin/node/runtime/src/lib.rs
  client/consensus/uncles/Cargo.toml
  client/consensus/uncles/README.md
  client/consensus/uncles/src/lib.rs
  frame/authorship/Cargo.toml
  frame/authorship/src/lib.rs
  frame/babe/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/tests.rs
  frame/transaction-payment/asset-tx-payment/src/mock.rs
  primitives/authorship/Cargo.toml
  primitives/authorship/README.md
  primitives/authorship/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13256 Implement RIType traits for u8 array with an arbitrary size
  primitives/runtime-interface/src/impls.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13237 grandpa: cleanup stale entries in set id session mapping
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/migrations.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
