Repository paritytech/substrate, pull requests merged in 2023-02, with the labels that each got.

#13146 Benchmark's successful origin api update
  frame/alliance/src/benchmarking.rs
  frame/assets/src/benchmarking.rs
  frame/bounties/src/benchmarking.rs
  frame/democracy/src/benchmarking.rs
  frame/fast-unstake/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/lottery/src/benchmarking.rs
  frame/membership/src/lib.rs
  frame/nfts/src/benchmarking.rs
  frame/nis/src/benchmarking.rs
  frame/preimage/src/benchmarking.rs
  frame/ranked-collective/src/benchmarking.rs
  frame/ranked-collective/src/lib.rs
  frame/referenda/src/benchmarking.rs
  frame/scheduler/src/benchmarking.rs
  frame/support/src/traits/dispatch.rs
  frame/system/src/tests.rs
  frame/tips/src/benchmarking.rs
  frame/treasury/src/benchmarking.rs
  frame/uniques/src/benchmarking.rs
  frame/whitelist/src/benchmarking.rs
Labels: A3-inprogress, B3-apinoteworthy, C1-low 📌, D3-trivial 🧸

#13264 hooks default impl missing where clause
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/test/tests/pallet_ui/duplicate_store_attr.rs
  frame/support/test/tests/pallet_ui/pass/where_clause_missing_hooks.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#13232 implemented `contains_prefix` for StorageDoubleMap and StorageNMap
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/nmap.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/unhashed.rs
Labels: A0-pleasereview, B3-apinoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#13267 Calling proxy doesn't remove announcement
  frame/proxy/src/lib.rs
  frame/proxy/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13083 Fee and tip represented as asset ID inside `AssetTxFeePaid`
  frame/transaction-payment/asset-tx-payment/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/payment.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13076 Move beefy-merkle-tree to utils/binary-merkle-tree and make it generic
  Cargo.lock
  Cargo.toml
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
  utils/binary-merkle-tree/Cargo.toml
  utils/binary-merkle-tree/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13272 Metadata V15: Derive `TypeInfo` for describing runtime types
  Cargo.lock
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/lib.rs
  frame/benchmarking/src/utils.rs
  frame/contracts/primitives/Cargo.toml
  frame/contracts/primitives/src/lib.rs
  frame/support/src/traits/storage.rs
  frame/support/src/traits/try_runtime.rs
  frame/transaction-payment/src/types.rs
  primitives/consensus/babe/src/lib.rs
  primitives/core/src/lib.rs
  primitives/finality-grandpa/src/lib.rs
  primitives/inherents/Cargo.toml
  primitives/inherents/src/lib.rs
  primitives/merkle-mountain-range/src/lib.rs
  primitives/runtime/src/generic/block.rs
  primitives/runtime/src/transaction_validity.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13297 benchmarks: `EnsureRankedMember` must add ranked members
  frame/ranked-collective/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13190 Minor: Update output validity tests
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13215 BEEFY: define on-chain beefy-genesis and use it to coordinate voter initialization
  client/beefy/src/aux_schema.rs
  client/beefy/src/lib.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  frame/beefy/src/lib.rs
  primitives/beefy/src/lib.rs
  test-utils/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13291 feat: add event SkepticsChosen event in society
  frame/society/src/lib.rs
  frame/society/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13298 feat(client): significantly increase wasm instance limits
  client/executor/wasmtime/src/runtime.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13243 Remove in-tree bounded types and use bounded-collections crate
  Cargo.lock
  primitives/core/Cargo.toml
  primitives/core/src/bounded/bounded_btree_map.rs
  primitives/core/src/bounded/bounded_btree_set.rs
  primitives/core/src/bounded/bounded_vec.rs
  primitives/core/src/bounded/weak_bounded_vec.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13310 update linregress in frame-benchmarking to 0.5.1
  Cargo.lock
  frame/benchmarking/Cargo.toml
  frame/benchmarking/src/analysis.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13084 [client/network] remove peer entry from `ephemeral_addresses`
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13307 rpc-spec-v2/tx: Fix error typo
  client/rpc-spec-v2/src/transaction/error.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13285 BEEFY: client support for detecting equivocated votes
  Cargo.lock
  client/beefy/Cargo.toml
  client/beefy/src/aux_schema.rs
  client/beefy/src/communication/gossip.rs
  client/beefy/src/justification.rs
  client/beefy/src/keystore.rs
  client/beefy/src/metrics.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  primitives/beefy/Cargo.toml
  primitives/beefy/src/commitment.rs
  primitives/beefy/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#13160 Bump `wasmtime` to 5.0.0 (and a few other deps)
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/imports.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/wasm-interface/Cargo.toml
  primitives/wasm-interface/src/lib.rs
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13300 Fix: Off-chain-worker example
  frame/examples/offchain-worker/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#13301 Rename `pallet-random-collective-flip` to Insecure...
  Cargo.lock
  Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/src/tests.rs
  frame/insecure-randomness-collective-flip/Cargo.toml
  frame/insecure-randomness-collective-flip/README.md
  frame/insecure-randomness-collective-flip/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#13078 `zombienet`: warp-sync tests for validators
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet/0002-validators-warp-sync/README.md
  zombienet/0002-validators-warp-sync/chain-spec.json
  zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml
  zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
  zombienet/0003-block-building-warp-sync/README.md
  zombienet/0003-block-building-warp-sync/chain-spec.json
  zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.toml
  zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.zndsl
Labels: A0-pleasereview, B0-silent, C1-low 📌

#13326 Disable default features for `strum` (fix `polkadot` CI)
  primitives/beefy/Cargo.toml
  primitives/keyring/Cargo.toml
Labels: B0-silent, D3-trivial 🧸, A0-please_review, C1-low

#13323 Fix block pruning after long re-org
  client/db/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#12568 Referendum proposal's metadata
  frame/democracy/src/benchmarking.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/fast_tracking.rs
  frame/democracy/src/tests/metadata.rs
  frame/democracy/src/tests/public_proposals.rs
  frame/democracy/src/types.rs
  frame/democracy/src/weights.rs
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
  frame/referenda/src/weights.rs
Labels: A0-pleasereview, B3-apinoteworthy, C3-medium 📣, D1-audited 👍

#13178 contracts: Rework generated API docs
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/wasm/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13340 pallet-scheduler: Ensure we request a preimage
  frame/scheduler/src/lib.rs
  frame/scheduler/src/tests.rs
  frame/support/src/traits/preimages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, A0-please_review

#13296 [Fix] Try-state feature-gated for BagsList
  frame/bags-list/Cargo.toml
  frame/bags-list/fuzzer/src/main.rs
  frame/bags-list/remote-tests/Cargo.toml
  frame/bags-list/remote-tests/src/try_state.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/mock.rs
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/src/lib.rs
  frame/staking/Cargo.toml
  frame/staking/src/migrations.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#13359 bump version of zombienet and update snaps links
  .gitlab-ci.yml
  zombienet/0001-basic-warp-sync/test-warp-sync.toml
  zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml
  zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, A0-please_review, C1-low

#13289 Fix longest chain finalization target lookup
  client/consensus/common/src/longest_chain.rs
  client/finality-grandpa/src/tests.rs
  client/service/test/src/client/mod.rs
  primitives/blockchain/src/backend.rs
  primitives/consensus/common/src/select_chain.rs
Labels: A0-pleasereview, I2-bug 🐜, B0-silent, C1-low 📌, D3-trivial 🧸

#13159 SetMembers configurable origin
  bin/node/runtime/src/lib.rs
  frame/alliance/src/mock.rs
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
  frame/utility/src/tests.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, A0-please_review

#13364 grandpa: don't error if best block and finality target are inconsistent
  client/finality-grandpa/src/environment.rs
  client/finality-grandpa/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, C1-low

#13355 Improve Weight Template and API
  .maintain/frame-weight-template.hbs
  primitives/weights/src/weight_v2.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, C1-low

#13343 client/beefy: request justifs from peers further in consensus
  client/beefy/src/communication/peers.rs
  client/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, C1-low

#13375 [ci] Change GHA to add J2 labels instead Z0
  .github/workflows/auto-label-issues.yml
Labels: A0-please_review, B0-silent, C1-low

#13361 sc-client-db: Fix `PruningMode::ArchiveCanonical`
  client/db/src/lib.rs
  client/state-db/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13348 Cherry-pick / benchmarks: EnsureRankedMember must add ranked members (#13297)
  frame/ranked-collective/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13366 [Feature] Introduce storage_alias for CountedStorageMap
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/storage_alias.rs
  frame/support/src/storage/types/counted_map.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/storage_alias_ui/forbid_underscore_as_prefix.stderr
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13158 [NFTs] Offchain mint
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/nfts/Cargo.toml
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/common_functions.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/metadata.rs
  frame/nfts/src/features/settings.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/mock.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13374 feat: improve FinalityProofProvider api
  client/finality-grandpa/src/finality_proof.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13350 cleanup `<weight></weight>` from docs comments
  frame/balances/src/lib.rs
  frame/bounties/src/lib.rs
  frame/collective/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/multisig/src/lib.rs
  frame/nicks/src/lib.rs
  frame/scheduler/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/sudo/src/lib.rs
  frame/system/src/lib.rs
  frame/timestamp/src/lib.rs
  frame/tips/src/lib.rs
  frame/transaction-storage/src/lib.rs
  frame/treasury/src/lib.rs
  frame/utility/src/lib.rs
  frame/vesting/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13386 zombienet: is up timeout increased to 30s
  zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.zndsl
Labels: B0-silent, C1-low, D3-trivial 🧸

#13346 pallet-timestamp: Remove `ValidAtTimestamp` error variant
  frame/timestamp/src/lib.rs
  primitives/timestamp/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13197 [contracts] make `debug_message` execution outcome invariant to node debug logging setting
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  frame/contracts/fixtures/debug_message_invalid_utf8.wat
  frame/contracts/fixtures/debug_message_logging_disabled.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
  primitives/wasm-interface/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13327 Fork tree prune assumptions removal v2
  client/consensus/epochs/src/lib.rs
  utils/fork-tree/src/lib.rs
Labels: B0-silent, C1-low, A1-needs_burnin, D3-trivial 🧸

#13392 CI add subkey docker image description and CI job to publish it to the hub.docker.com
  scripts/ci/docker/subkey.Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#13268 contracts: Use `proof_size` from benchmarks
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/weights.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13395 [ci] Move publish-crates-locally to publish stage
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13397 [ci] Add dependencies for publish-crates
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-please_review, B0-silent, C1-low

#13398 CI fix `dockerhub-description` image name
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#12910 client/beefy: add more metrics for production visibility
  client/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/beefy/src/import.rs
  client/beefy/src/lib.rs
  client/beefy/src/metrics.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13369 contracts: Don't rely on reserved balances keeping an account alive
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/drain.wat
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/address.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13399 CI fix docker description publishing
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13394 `BlockId` removal: `CallApiAt::state_at`
  client/service/src/client/client.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#13393 `BlockId` removal: `Client::runtime_version_at`
  bin/node/bench/src/construct.rs
  bin/node/bench/src/import.rs
  bin/node/bench/src/txpool.rs
  bin/node/cli/src/service.rs
  bin/node/testing/src/bench.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#13121 BEEFY: implement equivocations detection, reporting and slashing
  Cargo.lock
  client/beefy/src/communication/gossip.rs
  client/beefy/src/error.rs
  client/beefy/src/justification.rs
  client/beefy/src/keystore.rs
  client/beefy/src/lib.rs
  client/beefy/src/metrics.rs
  client/beefy/src/round.rs
  client/beefy/src/tests.rs
  client/beefy/src/worker.rs
  client/consensus/babe/src/lib.rs
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy/Cargo.toml
  frame/beefy/src/default_weights.rs
  frame/beefy/src/equivocation.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  frame/beefy/src/tests.rs
  primitives/beefy/src/lib.rs
  primitives/beefy/src/test_utils.rs
  test-utils/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13396 network: Detect early that `NotificationOutSubstream` was closed by the remote
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13335 babe: account for skipped epochs when handling equivocations
  frame/babe/src/lib.rs
  frame/babe/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#12896 `try-runtime::fast-forward`
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  utils/frame/try-runtime/cli/Cargo.toml
  utils/frame/try-runtime/cli/src/block_building_info.rs
  utils/frame/try-runtime/cli/src/commands/fast_forward.rs
  utils/frame/try-runtime/cli/src/commands/mod.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#13367 Implements approval voting to use as a `NposSolver`
  bin/node/runtime/src/lib.rs
  frame/election-provider-support/benchmarking/src/lib.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/election-provider-support/src/weights.rs
  frame/elections/src/lib.rs
  primitives/npos-elections/src/approval_voting.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/tests.rs
Labels: A3-in_progress, B0-silent, C1-low, A0-pleasereview

#13409 Revert "network: Detect early that `NotificationOutSubstream` was closed by the remote"
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13414 state-db: Print warning when using large pruning window on RocksDb
  client/state-db/src/lib.rs
  client/state-db/src/noncanonical.rs
  client/state-db/src/pruning.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13219 Use async/await instead of manual polling of `NetworkWorker`
  client/authority-discovery/src/worker/tests.rs
  client/network/common/src/service.rs
  client/network/src/service.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/src/service/tests/mod.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/service/chain_sync.rs
  client/network/test/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13422 client/beefy: drop justification on block import if pallet-beefy not enabled
  client/beefy/src/import.rs
  client/beefy/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#13412 [contracts] rename call_runtime() returned error
  frame/contracts/src/wasm/runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13411 frame/beefy: prune entries in set id session mapping
  frame/beefy-mmr/src/mock.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  frame/beefy/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13421 Nomination Pools: Rename state-toggler to bouncer
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/fuzzer/src/call.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13423 Add `defensive_assert!` macro
  frame/support/src/traits/misc.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13401 `BlockId` removal: `BlockBuilderProvider::new_block_at`
  bin/node/cli/benches/block_production.rs
  client/basic-authorship/src/basic_authorship.rs
  client/beefy/src/tests.rs
  client/block-builder/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/finality-grandpa/src/tests.rs
  client/merkle-mountain-range/src/test_utils.rs
  client/network/src/service/tests/chain_sync.rs
  client/network/sync/src/lib.rs
  client/network/test/src/lib.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/client/src/trait_tests.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#12741 Update Template README
  bin/node-template/README.md
  bin/node-template/scripts/docker_run.sh
Labels: A2-insubstantial, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#12833 Glutton pallet
  Cargo.lock
  Cargo.toml
  bin/node/executor/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/glutton/Cargo.toml
  frame/glutton/README.md
  frame/glutton/src/benchmarking.rs
  frame/glutton/src/lib.rs
  frame/glutton/src/mock.rs
  frame/glutton/src/tests.rs
  frame/glutton/src/weights.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13410 Introduce EnsureOrigin to democracy.propose
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
Labels: C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime, A0-pleasereview

#13284 Rework storage iterators
  Cargo.lock
  client/api/src/backend.rs
  client/db/Cargo.toml
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/record_stats_state.rs
  client/rpc/src/state/state_full.rs
  client/service/src/chain_ops/export_raw_state.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/storage/src/lib.rs
  primitives/trie/Cargo.toml
  primitives/trie/src/cache/mod.rs
  primitives/trie/src/lib.rs
  primitives/trie/src/recorder.rs
  test-utils/runtime/Cargo.toml
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/read.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
Labels: A0-please_review, I7-refactor, I9-optimisation, I8-footprint, B0-silent, C1-low, D3-trivial 🧸

#12608 permissionless `bond_extra` in nomination pools
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
  frame/nomination-pools/src/weights.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#13431 Refactors election provider support benchmarks outside its own crate
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/benchmarking/Cargo.toml
  frame/election-provider-support/src/benchmarking.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/weights.rs
  scripts/run_all_benchmarks.sh
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13390 [NFTs] Update attributes with offchain signature
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
  frame/nfts/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13429 Bump `wasmtime` to 6.0.0
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  primitives/wasm-interface/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#12588 Abstracts elections-phragmen pallet to use NposSolver
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/benchmarking/Cargo.toml
  frame/election-provider-support/src/benchmarking.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/election-provider-support/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/elections/CHANGELOG.md
  frame/elections/Cargo.toml
  frame/elections/README.md
  frame/elections/src/benchmarking.rs
  frame/elections/src/lib.rs
  frame/elections/src/migrations/mod.rs
  frame/elections/src/migrations/v3.rs
  frame/elections/src/migrations/v4.rs
  frame/elections/src/migrations/v5.rs
  frame/elections/src/weights.rs
  primitives/npos-elections/src/approval_voting.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/tests.rs
  scripts/run_all_benchmarks.sh
  utils/frame/remote-externalities/Cargo.toml
Labels: C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#13428 CI Publish `substrate` docker image description to hub.docker.com.
  scripts/ci/docker/substrate.Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13349 Nfts attribute read interface
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/nfts/runtime-api/Cargo.toml
  frame/nfts/runtime-api/README.md
  frame/nfts/runtime-api/src/lib.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/support/src/traits/tokens/nonfungible_v2.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#13451 Revert "Abstracts elections-phragmen pallet to use NposSolver (#12588)"
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/election-provider-multi-phase/Cargo.toml
  frame/election-provider-support/Cargo.toml
  frame/election-provider-support/benchmarking/Cargo.toml
  frame/election-provider-support/benchmarking/src/lib.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/election-provider-support/src/weights.rs
  frame/elections-phragmen/CHANGELOG.md
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/README.md
  frame/elections-phragmen/src/benchmarking.rs
  frame/elections-phragmen/src/lib.rs
  frame/elections-phragmen/src/migrations/mod.rs
  frame/elections-phragmen/src/migrations/v3.rs
  frame/elections-phragmen/src/migrations/v4.rs
  frame/elections-phragmen/src/migrations/v5.rs
  frame/elections-phragmen/src/weights.rs
  frame/elections/src/weights.rs
  primitives/npos-elections/src/approval_voting.rs
  primitives/npos-elections/src/lib.rs
  primitives/npos-elections/src/phragmen.rs
  primitives/npos-elections/src/tests.rs
  scripts/run_all_benchmarks.sh
  utils/frame/remote-externalities/Cargo.toml
Labels: A0-please_review, B0-silent, C3-medium, D3-trivial 🧸

#12520 wasm-executor: Support growing the memory
  Cargo.lock
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/common.rs
  client/allocator/src/error.rs
  client/allocator/src/freeing_bump.rs
  client/allocator/src/lib.rs
  client/api/src/call_executor.rs
  client/executor/Cargo.toml
  client/executor/benches/bench.rs
  client/executor/common/Cargo.toml
  client/executor/common/src/runtime_blob/runtime_blob.rs
  client/executor/common/src/util.rs
  client/executor/common/src/wasm_runtime.rs
  client/executor/runtime-test/src/lib.rs
  client/executor/src/integration_tests/linux.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/native_executor.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmi/Cargo.toml
  client/executor/wasmi/src/lib.rs
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/host.rs
  client/executor/wasmtime/src/instance_wrapper.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
  client/finality-grandpa/src/lib.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc/src/state/state_full.rs
  client/service/src/client/call_executor.rs
  client/service/test/src/client/mod.rs
  primitives/core/src/traits.rs
  primitives/state-machine/src/lib.rs
  primitives/wasm-interface/Cargo.toml
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13441 Automatically format ci pipeline specs with prettier
  .gitattributes
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/check.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
  scripts/ci/gitlab/prettier.sh
Labels: B0-silent, C1-low

#13424 Yieldable queues for pallet `MessageQueue`
  bin/node/runtime/src/lib.rs
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/message-queue/src/weights.rs
  frame/support/src/traits.rs
  frame/support/src/traits/messages.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, E0-runtime_migration, T1-runtime

#13372 Support the subscription of every imported block
  client/api/src/backend.rs
  client/api/src/client.rs
  client/merkle-mountain-range/src/test_utils.rs
  client/service/src/client/client.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13444 [client/network] Remove unused argument
  client/network/src/protocol/notifications/behaviour.rs
  client/network/sync/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#13445 Further storage iterator refactoring
  client/api/src/backend.rs
  primitives/state-machine/src/backend.rs
  primitives/state-machine/src/ext.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
Labels: A0-please_review, I7-refactor, B0-silent, C1-low, D3-trivial 🧸

#13468 `pallet-treasury`: Ensure we respect `max_amount` for spend across batch calls
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/dispatch_context.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13466 Add Windows support for storage monitor
  Cargo.lock
  client/storage-monitor/Cargo.toml
  client/storage-monitor/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#13481 Service::Error: Storage variant removed
  bin/node/cli/src/service.rs
  client/service/src/error.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#13477 Adjust the ratio of the `in-peers`/`out-peers`
  client/cli/src/params/network_params.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13485 Fix V2 PoV benchmarking
  frame/balances/src/weights.rs
  frame/benchmarking/pov/src/benchmarking.rs
  frame/benchmarking/pov/src/weights.rs
  frame/glutton/src/tests.rs
  frame/glutton/src/weights.rs
  frame/message-queue/src/weights.rs
  frame/support/procedural/src/benchmark.rs
  utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13484 Move BEEFY code to consensus
  Cargo.lock
  Cargo.toml
  client/beefy/Cargo.toml
  client/consensus/beefy/Cargo.toml
  client/consensus/beefy/README.md
  client/consensus/beefy/rpc/Cargo.toml
  client/consensus/beefy/rpc/src/lib.rs
  client/consensus/beefy/rpc/src/notification.rs
  client/consensus/beefy/src/aux_schema.rs
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/communication/mod.rs
  client/consensus/beefy/src/communication/notification.rs
  client/consensus/beefy/src/communication/peers.rs
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/communication/request_response/mod.rs
  client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/consensus/beefy/src/error.rs
  client/consensus/beefy/src/import.rs
  client/consensus/beefy/src/justification.rs
  client/consensus/beefy/src/keystore.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/metrics.rs
  client/consensus/beefy/src/round.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
  client/merkle-mountain-range/Cargo.toml
  client/merkle-mountain-range/src/lib.rs
  client/merkle-mountain-range/src/offchain_mmr.rs
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy-mmr/src/tests.rs
  frame/beefy/Cargo.toml
  frame/beefy/src/equivocation.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  frame/beefy/src/tests.rs
  primitives/consensus/beefy/Cargo.toml
  primitives/consensus/beefy/src/commitment.rs
  primitives/consensus/beefy/src/lib.rs
  primitives/consensus/beefy/src/mmr.rs
  primitives/consensus/beefy/src/payload.rs
  primitives/consensus/beefy/src/test_utils.rs
  primitives/consensus/beefy/src/witness.rs
  primitives/consensus/beefy/test-res/large-raw-commitment
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#13427 chore: move genesis block builder to chain-spec crate.
  Cargo.lock
  client/block-builder/Cargo.toml
  client/block-builder/src/lib.rs
  client/chain-spec/Cargo.toml
  client/chain-spec/src/genesis.rs
  client/chain-spec/src/lib.rs
  client/service/src/client/client.rs
  client/service/src/client/mod.rs
  client/service/src/lib.rs
  test-utils/runtime/client/Cargo.toml
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/genesismap.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview
