Repository paritytech/substrate, pull requests merged in 2023-04, with the labels that each got.

#13774 Insert claim_commission weight
  frame/nomination-pools/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#13741 FRAME: Minor fix for failsafe.
  frame/balances/src/lib.rs
  frame/nis/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13698 Adjustments to RPC-query docstrings.
  client/rpc-api/src/state/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13806 Force upgrade snow to 0.9.2
  Cargo.lock
  client/network/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13231 Scheduler pre block limit note
  bin/node/runtime/src/lib.rs
  frame/referenda/src/lib.rs
  frame/scheduler/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13804 Disable `sign-ext` WASM feature when building runtimes
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13610 refactor: inconsistent BalanceConversion fn
  frame/assets/src/tests.rs
  frame/assets/src/types.rs
  frame/support/src/traits/tokens.rs
  frame/support/src/traits/tokens/misc.rs
  frame/transaction-payment/asset-tx-payment/src/payment.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13799 Remove deprecated batch verification
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
  frame/executive/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/core/src/traits.rs
  primitives/io/src/batch_verifier.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/testing.rs
  test-utils/client/src/lib.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, F3-breaks_API, T0-node

#13322 Update documentation for uniques (This PR renames classes and instances to collections and items in the Uniques pallet in order to follow the commonly accepted NFTs terminology.)
  frame/uniques/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13722 Implement #[pallet::composite_enum]
  frame/support/procedural/src/construct_runtime/expand/freeze_reason.rs
  frame/support/procedural/src/construct_runtime/expand/hold_reason.rs
  frame/support/procedural/src/construct_runtime/expand/lock_id.rs
  frame/support/procedural/src/construct_runtime/expand/mod.rs
  frame/support/procedural/src/construct_runtime/expand/slash_reason.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/tt_default_parts.rs
  frame/support/procedural/src/pallet/mod.rs
  frame/support/procedural/src/pallet/parse/composite.rs
  frame/support/procedural/src/pallet/parse/event.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/src/lib.rs
  frame/support/test/tests/construct_runtime_ui/invalid_module_details_keyword.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.stderr
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_ui/composite_enum_unsupported_identifier.rs
  frame/support/test/tests/pallet_ui/composite_enum_unsupported_identifier.stderr
  frame/support/test/tests/pallet_ui/event_wrong_item.stderr
  frame/support/test/tests/pallet_ui/hold_reason_non_enum.rs
  frame/support/test/tests/pallet_ui/hold_reason_non_enum.stderr
  frame/support/test/tests/pallet_ui/hold_reason_not_pub.rs
  frame/support/test/tests/pallet_ui/hold_reason_not_pub.stderr
  frame/support/test/tests/pallet_ui/lock_id_duplicate.rs
  frame/support/test/tests/pallet_ui/lock_id_duplicate.stderr
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13811 Expose WASM extensions in executor semantics
  client/executor/benches/bench.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/src/runtime.rs
  client/executor/wasmtime/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13699 Deprecate V1 Weights
  frame/alliance/src/lib.rs
  frame/collective/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/support/src/dispatch.rs
  frame/system/src/tests.rs
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13819 update links to ink! docs from pallet_contracts
  frame/contracts/README.md
  frame/contracts/benchmarks/README.md
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/lib.rs
Labels: I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#13820 Move registration of `ReadRuntimeVersionExt` to `ExecutionExtension`
  bin/node/testing/src/bench.rs
  client/api/src/execution_extensions.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/client.rs
  primitives/core/src/traits.rs
  primitives/state-machine/src/lib.rs
  test-utils/client/src/lib.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/fast_forward.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13797 Mention `on_idle` round-robin logic to `trait Hooks` cargo doc
  frame/support/src/traits/hooks.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13769 ProofRecorder: Implement transactional support
  client/block-builder/src/lib.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/trie/src/recorder.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/system.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13828 de-duplicate --help --sync docs
  client/cli/src/params/network_params.rs
Labels: A2-insubstantial, B0-silent, C1-low

#13823 Add HoldReason to the NIS pallet
  frame/nis/src/lib.rs
  frame/support/procedural/src/construct_runtime/expand/freeze_reason.rs
  frame/support/procedural/src/construct_runtime/expand/hold_reason.rs
  frame/support/procedural/src/construct_runtime/expand/lock_id.rs
  frame/support/procedural/src/construct_runtime/expand/slash_reason.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13817 Use proper weights in the `pallet-template`
  Cargo.lock
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/benchmarking.rs
  bin/node-template/pallets/template/src/lib.rs
  bin/node-template/pallets/template/src/mock.rs
  bin/node-template/pallets/template/src/weights.rs
  bin/node-template/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13842 Fix typos
  client/network/README.md
Labels: A2-insubstantial, B0-silent, C1-low

#13844 Update the frame-weight-template to use PhantomData from core
  .maintain/frame-weight-template.hbs
  Cargo.lock
  bin/node-template/pallets/template/Cargo.toml
  bin/node-template/pallets/template/src/weights.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13824 Make blocks per request configurable
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/sync/src/block_request_handler.rs
  client/network/sync/src/blocks.rs
  client/network/sync/src/engine.rs
  client/network/sync/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13841 WASM executor: add `OutputExceedsBounds` variant to `Error`
  client/executor/common/src/error.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13858 Warn if pallet provided to try-state does not exist
  frame/support/src/traits/try_runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13740 refactor(sc-executor): use wasm executor builder instead of old apis
  bin/node-template/node/src/service.rs
  bin/node/cli/benches/transaction_pool.rs
  bin/node/cli/src/service.rs
  bin/node/executor/benches/bench.rs
  bin/node/executor/tests/common.rs
  bin/node/inspect/src/command.rs
  bin/node/testing/src/bench.rs
  client/executor/benches/bench.rs
  client/executor/common/src/wasm_runtime.rs
  client/executor/src/executor.rs
  client/executor/src/integration_tests/linux.rs
  client/executor/src/integration_tests/mod.rs
  client/executor/src/lib.rs
  client/executor/src/wasm_runtime.rs
  client/executor/wasmtime/src/tests.rs
  client/service/src/builder.rs
  client/service/src/client/call_executor.rs
  client/service/src/client/wasm_override.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/service/test/src/lib.rs
  frame/system/src/tests.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/runtime-interface/test/src/lib.rs
  test-utils/client/src/lib.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/system.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#13868 Remove unused import from bench.rs
  client/executor/benches/bench.rs
Labels: A2-insubstantial, B0-silent, C1-low

#13833 simplify some pattern matches to appease 1.68 clippy
  client/consensus/grandpa/src/communication/mod.rs
  client/network/common/src/sync.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/sync/src/blocks.rs
  client/network/transactions/src/lib.rs
  client/service/test/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/offences/src/lib.rs
  frame/session/src/lib.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13302 Metadata V15: Add Runtime API metadata
  Cargo.lock
  Cargo.toml
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/src/lib.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/runtime_metadata.rs
  primitives/api/Cargo.toml
  primitives/api/proc-macro/Cargo.toml
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/lib.rs
  primitives/api/proc-macro/src/runtime_metadata.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/api/src/lib.rs
  primitives/consensus/beefy/src/lib.rs
  primitives/metadata-ir/Cargo.toml
  primitives/metadata-ir/src/lib.rs
  primitives/metadata-ir/src/types.rs
  primitives/metadata-ir/src/v14.rs
  primitives/metadata-ir/src/v15.rs
  primitives/test-primitives/Cargo.toml
  primitives/test-primitives/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13759 pallet nis: remove benchmarking hack
  frame/nis/src/benchmarking.rs
  frame/nis/src/lib.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13851 Fix fungible and fungibles set_balance return value
  frame/support/src/traits/tokens/fungible/regular.rs
  frame/support/src/traits/tokens/fungibles/regular.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13830 use stable rust toolchain in ci
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13815 Makes storage hashers optional in dev mode
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_default_hasher.rs
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_default_hasher.stderr
  frame/support/test/tests/pallet_ui/pass/dev_mode_valid.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13886 Fixes error message when _ is used without dev mode
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/test/tests/pallet_ui/dev_mode_without_arg_default_hasher.stderr
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13882 invoke clippy with `--locked`
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13881 sc-consensus-beefy: add peer reputation cost/benefit changes
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/communication/mod.rs
  client/consensus/beefy/src/communication/peers.rs
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/communication/request_response/mod.rs
  client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/consensus/beefy/src/import.rs
  client/consensus/beefy/src/justification.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/metrics.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13724 contracts: add sr25519_verify
  frame/contracts/fixtures/sr25519_verify.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13901 contracts: stabilize `[seal0] call_runtime()`
  frame/contracts/src/wasm/runtime.rs
Labels: B0-silent, D3-trivial 🧸, T4-smart_contracts

#13910 Disable timestamping for the crate publishing jobs
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13908 Refactor the automatic-crate-publishing logic, make triggered pipelines uninterruptible as well
  .gitlab-ci.yml
  scripts/ci/gitlab/crate-publishing-pipeline.yml
  scripts/ci/gitlab/default-pipeline.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13876 Update proc-macro-warning
  Cargo.lock
  frame/support/procedural/Cargo.toml
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13917 Drain all the pending messages in the channel when `TracingUnboundedReceiver` is dropped
  client/utils/src/mpsc.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#13919 Updates Benchmark macro parsing to use Generic Argument
  frame/support/procedural/src/benchmark.rs
  frame/support/test/tests/benchmark_ui/bad_param_range.rs
  frame/support/test/tests/benchmark_ui/bad_param_range.stderr
  frame/support/test/tests/benchmark_ui/pass/valid_const_expr.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13925 sc-allocator: Do not panic on invalid header pointer
  client/allocator/src/freeing_bump.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#13907 [Fix] Remove redundant stash from Stake
  frame/nomination-pools/src/mock.rs
  frame/staking/src/pallet/impls.rs
  primitives/staking/src/lib.rs
Labels: B0-silent, D3-trivial 🧸

#13645 Try-state for Collective pallet
  frame/collective/src/benchmarking.rs
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13929 Update links in the Referenda Readme
  frame/referenda/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13885 Balances: repatriate_reserved should respect freezes
  frame/balances/src/impl_currency.rs
  frame/balances/src/lib.rs
  frame/balances/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#13934 Poll the substream validation before polling `Notifications`
  client/network/src/protocol.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#13883 babe: replace usage of SharedEpochChanges with internal RPC
  Cargo.lock
  bin/node/cli/src/service.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  client/consensus/babe/rpc/src/lib.rs
  client/consensus/babe/src/lib.rs
  client/sync-state-rpc/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#13937 chore(docs): improve some comments
  client/network/common/src/sync/message.rs
  client/network/common/src/sync/warp.rs
  client/rpc-api/src/chain/mod.rs
  client/rpc/src/chain/mod.rs
  frame/staking/src/pallet/impls.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13608 feat: pallet asset-rate
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/asset-rate/Cargo.toml
  frame/asset-rate/src/benchmarking.rs
  frame/asset-rate/src/lib.rs
  frame/asset-rate/src/mock.rs
  frame/asset-rate/src/tests.rs
  frame/asset-rate/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13948 call_executor: Remove code deduplication
  client/service/src/client/call_executor.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13952 Improve has good jugement
  bin/node/runtime/src/impls.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13889 VRF refactory
  Cargo.lock
  Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/lib.rs
  client/consensus/babe/src/migration.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
  client/keystore/src/local.rs
  frame/babe/Cargo.toml
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/randomness.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/digests.rs
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/vrf/Cargo.toml
  primitives/consensus/vrf/README.md
  primitives/consensus/vrf/src/lib.rs
  primitives/consensus/vrf/src/schnorrkel.rs
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
  primitives/core/src/sr25519.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
  primitives/keystore/src/vrf.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13944 Adds example for dev_mode and updates doc
  Cargo.lock
  Cargo.toml
  frame/examples/dev-mode/Cargo.toml
  frame/examples/dev-mode/README.md
  frame/examples/dev-mode/src/lib.rs
  frame/examples/dev-mode/src/tests.rs
  frame/support/procedural/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13771 Collective pallet: max proposal weight
  bin/node/runtime/src/lib.rs
  frame/alliance/src/mock.rs
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
  frame/utility/src/tests.rs
Labels: A0-please_review, B0-silent, D1-audited 👍, F3-breaks_API

#13959 `build_network` doesn't require the `MaintainedTransactionPool` bound
  client/service/src/builder.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13961 ci: drop skip-if-draft job
  .gitlab-ci.yml
  scripts/ci/gitlab/skip_if_draft.sh
Labels: A2-insubstantial, B0-silent, C1-low

#13956 replace unused cargo-deny check with a new cargo-deny-licenses job
  .gitlab-ci.yml
  scripts/ci/deny.toml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13960 [NFTs] Improve offchain signature validation
  frame/nfts/src/common_functions.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13941 Keep track of the pending response for each peer individually
  client/network/sync/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#13829 Evict inactive peers from `SyncingEngine`
  client/network/sync/src/engine.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#13964 `balances` `impl_currency` WithdrawReasons note
  frame/balances/src/impl_currency.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13923 try-runtime: dynamic storage query sizes
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#13779 Add Freeze/Thaw events and tests
  frame/balances/src/lib.rs
  frame/balances/src/tests/fungible_tests.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13970 Update macro use and optimize storage collection
  frame/contracts/src/lib.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13973 update rocksdb to 0.20.1
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, E2-dependencies

#13972 Remove superfluous Pair::verify_weak
  primitives/application-crypto/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13914 Vote locks for all reasons except RESERVE
  frame/conviction-voting/src/lib.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/lock_voting.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#13989 [ci] Update buildah command and version
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-please_review, B0-silent, C1-low

#13996 frame-support-procedural: Fix detection of the tuples feature
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13827 pallet-democracy: Do not request the proposal when scheduling
  frame/democracy/src/lib.rs
  frame/democracy/src/tests/metadata.rs
  frame/support/src/traits/schedule.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14001 [ci] Add message to cargo-deny
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13870 refactor(cli): Make some run params reusable
  client/cli/src/commands/run_cmd.rs
  client/cli/src/params/keystore_params.rs
  client/cli/src/params/message_params.rs
  client/cli/src/params/mod.rs
  client/cli/src/params/prometheus_params.rs
  client/cli/src/params/pruning_params.rs
  client/cli/src/params/runtime_params.rs
  client/cli/src/params/shared_params.rs
  client/cli/src/params/telemetry_params.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#12401 frame-support: migrate some tests from `decl_*` macros to the new `pallet` macros
  Cargo.lock
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/src/storage/generator/nmap.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  primitives/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13936 Removes ReportsByKindIndex
  frame/offences/src/lib.rs
  frame/offences/src/migration.rs
  frame/offences/src/mock.rs
  frame/offences/src/tests.rs
Labels: A0-please_review, D9-needsaudit 👮, B1-note_worthy, C5-high, E0-runtime_migration, T1-runtime

#14011 Easy PR: Allow missing docs for autogen weights
  .maintain/frame-weight-template.hbs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13565 [contracts] Port host functions to Weight V2 and storage deposit limit
  bin/node/runtime/src/lib.rs
  frame/contracts/README.md
  frame/contracts/fixtures/call_with_limit.wat
  frame/contracts/fixtures/caller_contract.wat
  frame/contracts/fixtures/create_storage_and_call.wat
  frame/contracts/fixtures/create_storage_and_instantiate.wat
  frame/contracts/fixtures/store_call.wat
  frame/contracts/fixtures/store_deploy.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
Labels: A0-please_review, B0-silent, D5-nicetohaveaudit ⚠️

#14021 contracts: fix failing test
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14003 contracts Add storage_deposit test
  frame/contracts/fixtures/call.wat
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14004 remote-externalities: batch insert key/values
  primitives/state-machine/src/testing.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13988 pallet Collective: fix genesis member sort order
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
Labels: A0-please_review, C3-medium, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14025 sc-network-sync: Improve error reporting
  client/network/sync/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14028 contracts fix store-call test path
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14017 chore(cli): make cli display docs correctly
  client/cli/src/commands/build_spec_cmd.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_blocks_cmd.rs
  client/cli/src/commands/generate_node_key.rs
  client/cli/src/commands/import_blocks_cmd.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/commands/inspect_key.rs
  client/cli/src/commands/inspect_node_key.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/params/import_params.rs
  client/cli/src/params/network_params.rs
  client/cli/src/params/node_key_params.rs
  client/cli/src/params/offchain_worker_params.rs
  client/cli/src/params/prometheus_params.rs
  client/cli/src/params/pruning_params.rs
  client/cli/src/params/shared_params.rs
  client/cli/src/params/telemetry_params.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14023 improve staking interface methods
  Cargo.lock
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/tests.rs
  primitives/staking/Cargo.toml
  primitives/staking/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14030 try-runtime-cli: improve ci stability
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#13979 Implements `try_state` hook in elections and EPM pallets
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/elections-phragmen/src/lib.rs
Labels: A0-please_review, I5-tests, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14038 fix(in_mem): fix the clone logic
  client/api/src/in_mem.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13990 Contracts: runtime_call and storage_deposit
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/fixtures/call_runtime_and_call.wat
  frame/contracts/src/lib.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️
