Repository paritytech/substrate, pull requests merged in 2023-06, with the labels that each got.

#14270 FRAME: Introduce `ConvertToValue` adapter
  primitives/runtime/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14267 sp-api: Make the generated code act based on `std` in `sp-api`
  frame/executive/Cargo.toml
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/Cargo.toml
  primitives/core/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14261 frame: support for serde added
  frame/babe/Cargo.toml
  frame/beefy/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/im-online/Cargo.toml
  frame/membership/Cargo.toml
  frame/session/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/src/lib.rs
  frame/system/Cargo.toml
  frame/system/src/lib.rs
  primitives/runtime/src/traits.rs
  primitives/staking/Cargo.toml
  primitives/staking/src/lib.rs
Labels: C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14283 frame/support: Link call documentation only in prod-modes
  frame/support/procedural/src/pallet/expand/call.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14248 print error info for Database error in the `sp-blockchain::Error` type.
  primitives/blockchain/src/error.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14277 pallet-uniques: remove #[transactional] macro for buy_item
  frame/uniques/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14289 asset-conversion pallet: Generalise integrity test
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/mock.rs
  frame/asset-conversion/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14288 Bump version of `pallet-contracts-primitives` for release
  Cargo.lock
  bin/node/runtime/Cargo.toml
  frame/contracts/Cargo.toml
  frame/contracts/primitives/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14043 frame-support Add translate_next
  frame/support/src/storage/generator/map.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/map.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14299 sp-api: Remove requirement on `Get*BlockType`
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/decl_and_impl.rs
  primitives/api/test/tests/ui/changed_in_no_default_method.rs
  primitives/api/test/tests/ui/changed_in_no_default_method.stderr
  primitives/api/test/tests/ui/changed_in_unknown_version.rs
  primitives/api/test/tests/ui/changed_in_unknown_version.stderr
  primitives/api/test/tests/ui/empty_impl_runtime_apis_call.rs
  primitives/api/test/tests/ui/empty_impl_runtime_apis_call.stderr
  primitives/api/test/tests/ui/impl_incorrect_method_signature.rs
  primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  primitives/api/test/tests/ui/impl_missing_version.rs
  primitives/api/test/tests/ui/impl_missing_version.stderr
  primitives/api/test/tests/ui/impl_two_traits_with_same_name.rs
  primitives/api/test/tests/ui/impl_two_traits_with_same_name.stderr
  primitives/api/test/tests/ui/missing_block_generic_parameter.rs
  primitives/api/test/tests/ui/missing_block_generic_parameter.stderr
  primitives/api/test/tests/ui/missing_path_for_trait.rs
  primitives/api/test/tests/ui/missing_path_for_trait.stderr
  primitives/api/test/tests/ui/missing_versioned_method.rs
  primitives/api/test/tests/ui/missing_versioned_method.stderr
  primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.rs
  primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.stderr
  primitives/api/test/tests/ui/positive_cases/custom_where_bound.rs
  primitives/api/test/tests/ui/positive_cases/default_impls.rs
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.rs
  primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14297 Frame: Introduce `TryConvert` and `MaybeConvert` family of traits
  primitives/runtime/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14260 frame_system::remark: Allow any kind of origin
  frame/alliance/src/tests.rs
  frame/collective/src/benchmarking.rs
  frame/system/src/lib.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#14298 Remove unrequired check
  frame/asset-conversion/src/benchmarking.rs
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/mock.rs
  frame/asset-conversion/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14241 migration(tips): unreserve deposits
  frame/tips/src/migrations/mod.rs
  frame/tips/src/migrations/unreserve_deposits.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14303 upgrade macro_magic to v0.3.5
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E2-dependencies

#13031 arkworks integration
  Cargo.lock
  Cargo.toml
  primitives/crypto/ec-utils/Cargo.toml
  primitives/crypto/ec-utils/src/bls12_377.rs
  primitives/crypto/ec-utils/src/bls12_381.rs
  primitives/crypto/ec-utils/src/bw6_761.rs
  primitives/crypto/ec-utils/src/ed_on_bls12_377.rs
  primitives/crypto/ec-utils/src/ed_on_bls12_381_bandersnatch.rs
  primitives/crypto/ec-utils/src/lib.rs
  primitives/crypto/ec-utils/src/test-data/g1_compressed_valid_test_vectors.dat
  primitives/crypto/ec-utils/src/test-data/g1_uncompressed_valid_test_vectors.dat
  primitives/crypto/ec-utils/src/test-data/g2_compressed_valid_test_vectors.dat
  primitives/crypto/ec-utils/src/test-data/g2_uncompressed_valid_test_vectors.dat
  primitives/crypto/ec-utils/src/utils.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, E3-host_functions, T1-runtime

#14052 add pallet macro kitchensink example/template
  Cargo.lock
  Cargo.toml
  frame/examples/Cargo.toml
  frame/examples/kitchensink/Cargo.toml
  frame/examples/kitchensink/src/benchmarking.rs
  frame/examples/kitchensink/src/lib.rs
  frame/examples/kitchensink/src/tests.rs
  frame/examples/kitchensink/src/weights.rs
  frame/examples/src/lib.rs
  frame/support/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14308 Finalized should be before best
  client/service/src/client/client.rs
  client/service/test/src/client/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14316 Contracts: fix benchmark comment
  frame/contracts/src/benchmarking/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14302 Remove native deps: openssl-sys, git2-sys, libssh2-sys
  Cargo.lock
  scripts/ci/node-template-release/Cargo.toml
  scripts/ci/node-template-release/src/main.rs
  utils/frame/generate-bags/Cargo.toml
  utils/frame/generate-bags/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14220 refactor: define trait `HashOutput` for some Hash associate type
  bin/node/inspect/src/command.rs
  client/api/src/in_mem.rs
  client/cli/src/commands/check_block_cmd.rs
  client/cli/src/commands/export_state_cmd.rs
  client/cli/src/params/mod.rs
  client/consensus/grandpa/src/lib.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/record_stats_state.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/traits.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/try-runtime/cli/src/commands/create_snapshot.rs
  utils/frame/try-runtime/cli/src/commands/execute_block.rs
  utils/frame/try-runtime/cli/src/commands/fast_forward.rs
  utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14325 asset-conversion pallet: No need for AssetBalanceOf
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14309 Move `type Migrations` to `Config`
  bin/node/runtime/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, C1-low, D2-breaksapi, B1-note_worthy, F3-breaks_API, T1-runtime

#13330 It's always false...
  frame/assets/src/functions.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#14024 pallet-aura: Allow multiple blocks per slot
  bin/node-template/runtime/src/lib.rs
  frame/aura/src/lib.rs
  frame/aura/src/mock.rs
  frame/aura/src/tests.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#14326 Frame: Give Referendum `SubmitOrigin` argument
  frame/collective/src/lib.rs
  frame/core-fellowship/src/lib.rs
  frame/ranked-collective/src/lib.rs
  frame/ranked-collective/src/tests.rs
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/society/src/lib.rs
  frame/support/procedural/src/construct_runtime/expand/origin.rs
  frame/support/src/dispatch.rs
  frame/support/src/traits.rs
  frame/support/src/traits/dispatch.rs
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  primitives/runtime/src/traits.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#14348 Update Pallet placeholder struct as per FRAME v2
  frame/asset-conversion/src/lib.rs
  frame/atomic-swap/src/lib.rs
  frame/beefy/src/lib.rs
  frame/benchmarking/pov/src/lib.rs
  frame/benchmarking/src/tests.rs
  frame/contracts/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/indices/src/lib.rs
  frame/nft-fractionalization/src/lib.rs
  frame/preimage/src/lib.rs
  frame/scheduler/src/mock.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/support/src/dispatch.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/issue2219.rs
  frame/timestamp/src/lib.rs
  test-utils/runtime/src/substrate_test_pallet.rs
  utils/frame/rpc/support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14334 fix new warning in nightly
  bin/node/testing/src/client.rs
  client/rpc/src/state/mod.rs
  frame/staking/src/lib.rs
  test-utils/runtime/client/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14181 Improvements to node template README
  bin/node-template/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14148 PR template improvements
  docs/CONTRIBUTING.adoc
  docs/PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14367 Use Incrementable from frame_support::traits
  frame/nfts/src/lib.rs
  frame/nfts/src/macros.rs
  frame/nfts/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13958 Take into account proof size for transaction payment and priority
  bin/node/runtime/src/impls.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#14226 migration(democracy): unreserve deposits and clear locks
  frame/democracy/src/lib.rs
  frame/democracy/src/migrations/mod.rs
  frame/democracy/src/migrations/unlock_and_unreserve_all_funds.rs
  frame/democracy/src/migrations/v1.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14218 migration(elections-phragmen): unreserve deposits and clear locks
  frame/elections-phragmen/src/migrations/mod.rs
  frame/elections-phragmen/src/migrations/unlock_and_unreserve_all_funds.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14352 benchmark pallet: Error if files are overwritten twice
  utils/frame/benchmarking-cli/src/pallet/mod.rs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14370 sc-executor-wasmtime: Do not use absolute path to `Cargo.toml` in test
  client/executor/wasmtime/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14375 Restructure macro-related exports into private mods for frame
  frame/election-provider-support/solution-type/src/codec.rs
  frame/election-provider-support/solution-type/src/lib.rs
  frame/election-provider-support/solution-type/src/single_page.rs
  frame/election-provider-support/src/lib.rs
  frame/support/procedural/src/construct_runtime/expand/inherent.rs
  frame/support/src/inherent.rs
  frame/support/src/traits/filter.rs
  frame/support/test/tests/pallet.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14376 Expose ExtraFlags struct
  frame/balances/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14379 `construct_runtime`: support for expanding the macro code
  Cargo.lock
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14384 Fix for `pallet_assets::create` benchmark
  frame/assets/src/benchmarking.rs
  frame/assets/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14251 [frame/im-online] remove network state from heartbeats
  bin/node/executor/tests/submit_transaction.rs
  bin/node/runtime/src/lib.rs
  client/offchain/src/api.rs
  frame/im-online/src/benchmarking.rs
  frame/im-online/src/lib.rs
  frame/im-online/src/migration.rs
  frame/im-online/src/mock.rs
  frame/im-online/src/tests.rs
  frame/im-online/src/weights.rs
  frame/offences/benchmarking/src/mock.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14390 fix clippy warnings in node template
  bin/node-template/node/src/benchmarking.rs
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/rpc.rs
  bin/node-template/node/src/service.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14362 Sassafras protocol v0.3.3
  Cargo.lock
  Cargo.toml
  bin/node-sassafras/node/Cargo.toml
  bin/node-sassafras/node/src/chain_spec.rs
  bin/node-sassafras/runtime/Cargo.toml
  bin/node-sassafras/runtime/src/lib.rs
  client/consensus/sassafras/Cargo.toml
  client/consensus/sassafras/src/authorship.rs
  client/consensus/sassafras/src/lib.rs
  client/consensus/sassafras/src/tests.rs
  client/consensus/sassafras/src/verification.rs
  client/keystore/src/local.rs
  frame/sassafras/Cargo.toml
  frame/sassafras/src/benchmarking.rs
  frame/sassafras/src/lib.rs
  frame/sassafras/src/mock.rs
  frame/sassafras/src/session.rs
  frame/sassafras/src/tests.rs
  primitives/consensus/sassafras/Cargo.toml
  primitives/consensus/sassafras/src/digests.rs
  primitives/consensus/sassafras/src/lib.rs
  primitives/consensus/sassafras/src/ticket.rs
  primitives/core/src/bandersnatch.rs
  primitives/io/src/lib.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, D2-notlive 💤

#14396 Run all tests with `try-runtime` feature enabled
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/migration.rs
  frame/democracy/src/migrations/unlock_and_unreserve_all_funds.rs
  frame/elections-phragmen/src/migrations/unlock_and_unreserve_all_funds.rs
  frame/im-online/src/migration.rs
  frame/scheduler/src/migration.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14224 Add a deprecation warning to the old runtime GenesisConfig
  frame/support/procedural/src/construct_runtime/expand/config.rs
Labels: C3-medium, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14371 Fix links to CONTRIBUTING.adoc in PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14397 Delete 1D weight ctors and set explicit deprecation dates
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/store_trait.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/event.rs
  frame/support/src/storage/migration.rs
  frame/support/test/tests/pallet_ui/deprecated_store_attr.stderr
  frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr
  frame/treasury/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14406 [network] Extend `Notifications` logs with `SetId` where missing
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol_controller.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14388 expose the fields of Dust type to public
  frame/support/src/traits/tokens/fungible/regular.rs
  frame/support/src/traits/tokens/fungibles/regular.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14408 pallet benchmarking: Bump default steps and repeat
  utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#11324 Society v2
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/asset-conversion/src/benchmarking.rs
  frame/core-fellowship/src/benchmarking.rs
  frame/democracy/src/vote.rs
  frame/nft-fractionalization/src/benchmarking.rs
  frame/salary/src/benchmarking.rs
  frame/society/Cargo.toml
  frame/society/src/benchmarking.rs
  frame/society/src/lib.rs
  frame/society/src/migrations.rs
  frame/society/src/mock.rs
  frame/society/src/tests.rs
  frame/society/src/weights.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/map.rs
  frame/support/src/traits/storage.rs
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/runtime/src/lib.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#14405 Refactor `BlockBuilder::propose_with`
  client/basic-authorship/src/basic_authorship.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13933 Baseline weights VM runners
  frame/alliance/src/weights.rs
  frame/asset-conversion/src/weights.rs
  frame/asset-rate/src/weights.rs
  frame/assets/src/weights.rs
  frame/bags-list/src/weights.rs
  frame/balances/src/weights.rs
  frame/benchmarking/src/weights.rs
  frame/bounties/src/weights.rs
  frame/child-bounties/src/weights.rs
  frame/collective/src/weights.rs
  frame/contracts/src/weights.rs
  frame/conviction-voting/src/weights.rs
  frame/core-fellowship/src/weights.rs
  frame/democracy/src/weights.rs
  frame/election-provider-multi-phase/src/weights.rs
  frame/elections-phragmen/src/weights.rs
  frame/fast-unstake/src/weights.rs
  frame/glutton/src/weights.rs
  frame/identity/src/weights.rs
  frame/im-online/src/weights.rs
  frame/indices/src/weights.rs
  frame/lottery/src/weights.rs
  frame/membership/src/weights.rs
  frame/message-queue/src/weights.rs
  frame/multisig/src/weights.rs
  frame/nft-fractionalization/src/weights.rs
  frame/nfts/src/weights.rs
  frame/nis/src/weights.rs
  frame/nomination-pools/src/weights.rs
  frame/preimage/src/weights.rs
  frame/proxy/src/weights.rs
  frame/ranked-collective/src/weights.rs
  frame/recovery/src/weights.rs
  frame/referenda/src/weights.rs
  frame/remark/src/weights.rs
  frame/salary/src/weights.rs
  frame/scheduler/src/weights.rs
  frame/session/src/weights.rs
  frame/staking/src/weights.rs
  frame/state-trie-migration/src/weights.rs
  frame/sudo/src/weights.rs
  frame/support/src/weights/block_weights.rs
  frame/support/src/weights/extrinsic_weights.rs
  frame/system/src/weights.rs
  frame/timestamp/src/weights.rs
  frame/tips/src/weights.rs
  frame/transaction-storage/src/weights.rs
  frame/treasury/src/weights.rs
  frame/uniques/src/weights.rs
  frame/utility/src/weights.rs
  frame/vesting/src/weights.rs
  frame/whitelist/src/weights.rs
Labels: B0-silent, D3-trivial 🧸

#14369 Update DOCUMENTATION_GUIDELINES.md
  docs/DOCUMENTATION_GUIDELINES.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14399 ci: bump ci image for rust 1.70
  .cargo/config.toml
  .gitlab-ci.yml
  frame/support/test/tests/construct_runtime_ui/number_of_pallets_exceeds_tuple_size.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr
  frame/support/test/tests/derive_impl_ui/bad_disambiguation_path.stderr
  frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.stderr
  primitives/api/test/tests/ui/impl_missing_version.stderr
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14313 Update contract multi-block migration
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v10.rs
  frame/contracts/src/migration/v11.rs
  frame/contracts/src/migration/v9.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14424 Remove clippy workaround
  .cargo/config.toml
  frame/assets/src/benchmarking.rs
  frame/benchmarking/src/v1.rs
  frame/nfts/src/benchmarking.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14365 fix(remote-externalities): child trie not loaded
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14417 suppress unused warning in kitchensink example
  frame/examples/kitchensink/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14391 expose setting kademlia replication factor through node CLI
  client/cli/src/params/network_params.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/service.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14341 inspect role for nonfungibles_v2
  frame/nfts/src/impl_nonfungibles.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14433 [minor] Extend logging with `SetId` in `ProtocolController` where missing
  client/network/src/protocol_controller.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14435 Adds ability to prepare/initialize before running `set_code` benchmark
  frame/system/benchmarking/src/lib.rs
  frame/system/src/weights.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#14441 child PR: Tidy swap event
  frame/asset-conversion/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14402 once_cell in std from 1.70
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  client/executor/wasmtime/src/util.rs
  client/tracing/Cargo.toml
  client/tracing/src/logging/directives.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/storage/metadata.rs
  frame/support/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14452 Remove k256 crate from frame-support dependencies
  Cargo.lock
  Cargo.toml
  frame/support/Cargo.toml
  frame/support/src/crypto/ecdsa.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14131 `GenesisBuilder` runtime API
  Cargo.lock
  Cargo.toml
  primitives/genesis-builder/Cargo.toml
  primitives/genesis-builder/README.md
  primitives/genesis-builder/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14461 Added missing BLS feature
  client/keystore/Cargo.toml
  primitives/application-crypto/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13950 [FRAME Core] Adds ability to split a pallet across multiple files
  Cargo.lock
  Cargo.toml
  frame/examples/Cargo.toml
  frame/examples/split/Cargo.toml
  frame/examples/split/README.md
  frame/examples/split/src/benchmarking.rs
  frame/examples/split/src/events.rs
  frame/examples/split/src/lib.rs
  frame/examples/split/src/mock.rs
  frame/examples/split/src/tests.rs
  frame/examples/split/src/weights.rs
  frame/examples/src/lib.rs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
  frame/support/test/tests/split_ui.rs
  frame/support/test/tests/split_ui/import_without_pallet.rs
  frame/support/test/tests/split_ui/import_without_pallet.stderr
  frame/support/test/tests/split_ui/no_section_found.rs
  frame/support/test/tests/split_ui/no_section_found.stderr
  frame/support/test/tests/split_ui/pass/split_valid.rs
  frame/support/test/tests/split_ui/pass/split_valid_disambiguation.rs
  frame/support/test/tests/split_ui/section_not_imported.rs
  frame/support/test/tests/split_ui/section_not_imported.stderr
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14464 Cleanup dependencies
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/inspect/Cargo.toml
  bin/node/primitives/Cargo.toml
  bin/node/testing/Cargo.toml
  client/authority-discovery/Cargo.toml
  client/cli/Cargo.toml
  client/consensus/babe/Cargo.toml
  client/consensus/beefy/Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/statement/Cargo.toml
  client/network/test/Cargo.toml
  client/offchain/Cargo.toml
  client/service/Cargo.toml
  client/service/test/Cargo.toml
  client/statement-store/Cargo.toml
  client/storage-monitor/Cargo.toml
  client/tracing/Cargo.toml
  primitives/application-crypto/test/Cargo.toml
  primitives/arithmetic/fuzzer/Cargo.toml
  primitives/block-builder/Cargo.toml
  primitives/consensus/aura/Cargo.toml
  primitives/consensus/babe/Cargo.toml
  primitives/core/hashing/Cargo.toml
  primitives/core/hashing/proc-macro/Cargo.toml
  primitives/inherents/Cargo.toml
  primitives/io/Cargo.toml
  primitives/keystore/Cargo.toml
  primitives/npos-elections/fuzzer/Cargo.toml
  primitives/runtime-interface/test-wasm-deprecated/Cargo.toml
  primitives/statement-store/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/transaction-storage-proof/Cargo.toml
  test-utils/cli/Cargo.toml
  test-utils/runtime/Cargo.toml
  test-utils/runtime/client/Cargo.toml
  utils/build-script-utils/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A3-in_progress, B0-silent, D3-trivial 🧸, T0-node

#14411 fix(test-externalities): include memory db reference counts in snapshots
  primitives/state-machine/src/testing.rs
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/test_data/proxy_test
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14318 `pallet-message-queue`: add queue pausing
  bin/node/runtime/src/lib.rs
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/support/src/traits.rs
  frame/support/src/traits/messages.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, E6-needs_polkadot_pr, T1-runtime

#14143 Metadata V15: Expose types for the overarching Call, Event, Error enums
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/expand/event.rs
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/procedural/src/construct_runtime/expand/mod.rs
  frame/support/procedural/src/construct_runtime/expand/outer_enums.rs
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/construct_runtime/parse.rs
  frame/support/procedural/src/pallet/expand/tt_default_parts.rs
  frame/support/test/tests/common/mod.rs
  frame/support/test/tests/common/outer_enums.rs
  frame/support/test/tests/construct_runtime_ui/generics_in_invalid_module.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_details_keyword.stderr
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.rs
  frame/support/test/tests/construct_runtime_ui/invalid_module_entry.stderr
  frame/support/test/tests/construct_runtime_ui/missing_event_generic_on_module_with_instance.rs
  frame/support/test/tests/construct_runtime_ui/missing_event_generic_on_module_with_instance.stderr
  frame/support/test/tests/construct_runtime_ui/missing_origin_generic_on_module_with_instance.rs
  frame/support/test/tests/construct_runtime_ui/missing_origin_generic_on_module_with_instance.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.rs
  frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_outer_enums_explicit.rs
  frame/support/test/tests/pallet_outer_enums_implicit.rs
  primitives/metadata-ir/Cargo.toml
  primitives/metadata-ir/src/lib.rs
  primitives/metadata-ir/src/types.rs
  primitives/metadata-ir/src/v15.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14455 sc-network: Improve invalid boot node reporting
  client/network/src/service.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14123 Metadata V15: Enrich extrinsic type info for decoding
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/src/traits/misc.rs
  frame/support/test/tests/pallet.rs
  primitives/metadata-ir/src/lib.rs
  primitives/metadata-ir/src/types.rs
  primitives/metadata-ir/src/v15.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/testing.rs
  primitives/runtime/src/traits.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14403 Make triecache generic and work for no-std environments
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/lib.rs
  primitives/state-machine/src/trie_backend.rs
  primitives/state-machine/src/trie_backend_essence.rs
  primitives/trie/src/cache/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14467 fix on-runtime-upgrade --checks docs
  utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
Labels: A2-insubstantial, B0-silent, C1-low

#13317 Update Reference Hardware Specs
  utils/frame/benchmarking-cli/src/machine/hardware.rs
  utils/frame/benchmarking-cli/src/machine/reference_hardware.json
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14465 Unify `SyncMode` data structures under one
  client/cli/src/arg_enums.rs
  client/network/common/src/sync.rs
  client/network/src/config.rs
  client/network/sync/src/engine.rs
  client/network/sync/src/lib.rs
  client/network/sync/src/mock.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/service/src/builder.rs
  client/service/src/config.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14474 frame-benchmarking-cli: Remove native dispatch requirement
  Cargo.lock
  bin/node-template/node/src/command.rs
  bin/node/cli/Cargo.toml
  bin/node/cli/src/command.rs
  client/consensus/babe/src/lib.rs
  client/consensus/beefy/src/worker.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/service/traits.rs
  client/rpc-spec-v2/src/chain_head/event.rs
  frame/benchmarking/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/im-online/src/lib.rs
  frame/recovery/src/lib.rs
  frame/support/src/lib.rs
  primitives/npos-elections/src/balancing.rs
  primitives/runtime/src/offchain/http.rs
  primitives/staking/src/offence.rs
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/wasm-builder/src/builder.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14447 sp-api: Support nested transactions
  Cargo.lock
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/test/Cargo.toml
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14481 Stabilize V15 Metadata
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/procedural/src/construct_runtime/expand/metadata.rs
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/pallet.rs
  frame/support/test/tests/pallet_instance.rs
  primitives/metadata-ir/Cargo.toml
  primitives/metadata-ir/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime
