Repository paritytech/substrate, pull requests merged in 2023-08, with the labels that each got.

#14690 ci: remove `--locked` from `check-runtime-migration` script
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-please_review, B0-silent, C1-low

#14696 docs: example of using `cargo run` with features
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14689 network: optimize update procedure for listen_addrs and external_addrs
  client/network/src/behaviour.rs
  client/network/src/peer_info.rs
  client/network/src/service.rs
Labels: A0-please_review, B0-silent, C1-low

#14694 Update missing dev mode docs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
Labels: A2-insubstantial, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14664 [fix docs compiler warnings] Glutton pallet
  frame/glutton/src/lib.rs
Labels: A0-please_review, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14634 Add `FixedPointOperand` blanket implementation
  bin/node/runtime/src/lib.rs
  frame/asset-rate/src/lib.rs
  frame/asset-rate/src/mock.rs
  frame/assets/src/types.rs
  frame/nis/src/lib.rs
  frame/support/src/traits/tokens/currency.rs
  frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
  frame/transaction-payment/asset-tx-payment/src/lib.rs
  frame/transaction-payment/src/lib.rs
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14373 Support for multiple signature scheme for BEEFY primitves
  Cargo.lock
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  client/consensus/beefy/src/import.rs
  client/consensus/beefy/src/justification.rs
  client/consensus/beefy/src/keystore.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/round.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
  frame/beefy-mmr/src/lib.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy-mmr/src/tests.rs
  frame/beefy/src/equivocation.rs
  frame/beefy/src/mock.rs
  frame/beefy/src/tests.rs
  primitives/application-crypto/Cargo.toml
  primitives/application-crypto/src/bls377.rs
  primitives/consensus/beefy/Cargo.toml
  primitives/consensus/beefy/src/commitment.rs
  primitives/consensus/beefy/src/lib.rs
  primitives/consensus/beefy/src/mmr.rs
  primitives/consensus/beefy/src/test_utils.rs
  primitives/consensus/beefy/src/witness.rs
  primitives/core/Cargo.toml
  primitives/core/src/bls.rs
  primitives/core/src/crypto.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14703 [network] fix: always set Kademlia mode to server
  client/network/src/discovery.rs
Labels: A0-please_review, B0-silent, C1-low

#14649 pallet-aura: add feature-flagged explicit slot duration type
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/aura/Cargo.toml
  frame/aura/src/lib.rs
  frame/aura/src/mock.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14672 Use relative docify paths
  Cargo.lock
  frame/fast-unstake/Cargo.toml
  frame/paged-list/Cargo.toml
  frame/paged-list/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E2-dependencies

#14678 Cross-contract calling: simple debugger
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/tests/unsafe_debug.rs
  frame/contracts/src/unsafe_debug.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14726 [asset-conversion] nits: removed unnecessary pool_id.clone()
  frame/asset-conversion/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14670 Add description to sp-crypto-ec-utils
  primitives/crypto/ec-utils/Cargo.toml
Labels: A0-please_review, A2-insubstantial, B0-silent, D2-notlive 💤

#14729 dont print proof size
  utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A0-please_review, B0-silent, C1-low

#14730 update weight file template
  .maintain/frame-weight-template.hbs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
Labels: A0-please_review, B0-silent, C1-low

#14704 test-utils: programatically spawn dev nodes
  Cargo.lock
  bin/node/cli/Cargo.toml
  test-utils/cli/Cargo.toml
  test-utils/cli/src/lib.rs
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#14692 chainHead: Produce method responses on `chainHead_follow`
  client/rpc-spec-v2/Cargo.toml
  client/rpc-spec-v2/src/chain_head/api.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  client/rpc-spec-v2/src/chain_head/event.rs
  client/rpc-spec-v2/src/chain_head/mod.rs
  client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  client/rpc-spec-v2/src/chain_head/subscription/mod.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14466 fixed a comment in the system pallet
  frame/system/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#14706 Remove deprecated old weight items
  frame/support/procedural/src/construct_runtime/expand/call.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/src/weights.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14738 Publish subkey
  bin/utils/subkey/Cargo.toml
Labels: A0-please_review, B0-silent, D2-notlive 💤, T9-release

#14412 Bandersnatch VRF
  Cargo.lock
  client/keystore/Cargo.toml
  client/keystore/src/local.rs
  primitives/application-crypto/Cargo.toml
  primitives/application-crypto/src/bandersnatch.rs
  primitives/application-crypto/src/lib.rs
  primitives/application-crypto/src/traits.rs
  primitives/core/Cargo.toml
  primitives/core/src/bandersnatch.rs
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/lib.rs
  primitives/core/src/sr25519.rs
  primitives/core/src/testing.rs
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/keyring/Cargo.toml
  primitives/keyring/src/bandersnatch.rs
  primitives/keyring/src/lib.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#12970 [NPoS] Implements dynamic number of nominators
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/bags-list/remote-tests/src/snapshot.rs
  frame/beefy/src/mock.rs
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/src/signed.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  frame/election-provider-support/src/bounds.rs
  frame/election-provider-support/src/lib.rs
  frame/election-provider-support/src/onchain.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/offences/benchmarking/src/mock.rs
  frame/root-offences/src/mock.rs
  frame/session/benchmarking/src/lib.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/election_size_tracker.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/tests.rs
  primitives/npos-elections/src/lib.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#14538 Pallets: Treasury deprecate `propose_spend` dispatchable
  frame/bounties/src/tests.rs
  frame/treasury/src/benchmarking.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14748 Sync NFT metadata limits with AssetHub values
  bin/node/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14754 sc-cli: add no-beefy flag to cli config
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/runner.rs
  client/service/src/config.rs
  client/service/test/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#14752 sc-consensus-beefy: fix BEEFY fast sync
  client/consensus/beefy/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#14714 make `BagsList::put_in_front_of` be permissionless
  Cargo.lock
  frame/bags-list/Cargo.toml
  frame/bags-list/src/lib.rs
  frame/bags-list/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#14723 [contracts] Derive useful traits for public types
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14453 add `frame_system::DefaultConfig` to individual pallet `DefaultConfigs`
  Cargo.lock
  frame/balances/src/lib.rs
  frame/examples/default-config/src/lib.rs
  frame/multisig/Cargo.toml
  frame/multisig/src/tests.rs
  frame/proxy/src/tests.rs
  frame/support/procedural/src/pallet/expand/config.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/test/tests/pallet_ui/default_config_with_no_default_in_system.rs
  frame/support/test/tests/pallet_ui/default_config_with_no_default_in_system.stderr
  frame/support/test/tests/pallet_ui/pass/default_config.rs
  frame/system/src/lib.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#14763 Fixes CI
  frame/multisig/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14718 fix: node cli docs
  bin/node/cli/build.rs
  bin/node/cli/doc/shell-completion.adoc
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/service.rs
Labels: A3-in_progress, B0-silent, C1-low, D3-trivial 🧸

#13502 Add `try_state` check to Pallet `MessageQueue`
  frame/message-queue/src/integration_test.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14769 Remove duplicate sentence
  docs/DOCUMENTATION_GUIDELINES.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14648 [fix lint warnings: NFTs pallet] fix clippy::missing_errors_doc lint warnings
  frame/nfts/src/common_functions.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/create_delete_collection.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/metadata.rs
  frame/nfts/src/features/transfer.rs
Labels: A0-please_review, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14740 Update Scheduler Pallet Documentation
  Cargo.lock
  frame/scheduler/Cargo.toml
  frame/scheduler/src/lib.rs
  frame/scheduler/src/tests.rs
  frame/support/src/traits/hooks.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#14772 Add `--workspace` to clippy
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#14619 Make peer evictions less aggressive
  client/network/sync/src/engine.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14693 `cargo clippy +nightly --fix` run on downstream node template
  bin/node-template/pallets/template/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14773 Improve `storage_alias` and make `UnlockAndUnreserveAllFunds` independent of the pallet
  Cargo.lock
  frame/democracy/src/migrations/unlock_and_unreserve_all_funds.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/storage_alias.rs
  frame/support/src/lib.rs
  frame/support/src/tests/mod.rs
  frame/support/src/tests/storage_alias.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14610 [fix lint warnings: NFTs pallet] fix clippy::missing_docs_in_private_items warnings
  frame/nfts/src/features/approvals.rs
  frame/nfts/src/features/atomic_swap.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/buy_sell.rs
  frame/nfts/src/features/create_delete_collection.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/features/lock.rs
  frame/nfts/src/features/metadata.rs
  frame/nfts/src/features/roles.rs
  frame/nfts/src/features/settings.rs
  frame/nfts/src/features/transfer.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/macros.rs
  frame/nfts/src/migration.rs
  frame/nfts/src/types.rs
Labels: A2-insubstantial, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14695 Update wasm-opt to 0.114
  Cargo.lock
  utils/wasm-builder/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14722 Revert "chore: update libp2p to 0.52.1 (#14429)"
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/protocol/notifications/upgrade/collec.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/types.rs
  client/network/statement/Cargo.toml
  client/network/statement/src/lib.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/network/transactions/src/lib.rs
  client/offchain/Cargo.toml
  client/service/src/lib.rs
  client/telemetry/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14731 deprecate `try-runtime` subcommand and direct users to standalone cli
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  scripts/ci/gitlab/pipeline/build.yml
  utils/frame/try-runtime/cli/src/lib.rs
  utils/frame/try-runtime/cli/tests/create_snapshot.rs
  utils/frame/try-runtime/cli/tests/execute_block.rs
  utils/frame/try-runtime/cli/tests/follow_chain.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#14663 Runtime: avoid duplication and test all signature
  primitives/runtime/src/traits.rs
  test-utils/runtime/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14712 Contracts: expose charge_storage to chain_extension
  frame/contracts/src/chain_extension.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/wasm/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14767 Transfer to beneficiary after `transfer_on_hold`
  frame/contracts/src/exec.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-smart_contracts

#14589 Contracts remove deposit accounts
  frame/contracts/src/address.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v10.rs
  frame/contracts/src/migration/v13.rs
  frame/contracts/src/migration/v14.rs
  frame/contracts/src/migration/v15.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
  frame/support/src/traits/tokens/fungible/hold.rs
  frame/support/src/traits/tokens/fungibles/hold.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, E0-runtime_migration, T1-runtime

#14793 fix: `try_on_runtime_upgrade` for `Tuple` weight summation
  frame/support/src/traits/hooks.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14776 bump ed25519-dalek to 2.0
  Cargo.lock
  primitives/io/Cargo.toml
  primitives/io/src/lib.rs
  primitives/statement-store/Cargo.toml
  primitives/statement-store/src/ecies.rs
Labels: A0-please_review, B0-silent, C3-medium, A1-needs_burnin, D5-nicetohaveaudit ⚠️

#14800 [NFTs] Make owned_item in MintWitness optional
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14811 asset-conversion pallet: pool's `AccountId` derivation warn docs
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/tests.rs
  frame/asset-conversion/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14750 contracts: Expose environment types for offchain tooling
  bin/node/runtime/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14650 return proof size on manually created blocks (for tests only)
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/rpc.rs
  client/consensus/manual-seal/src/seal_block.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14709 Add conditional compilation support for `iml_runtime_apis!`
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/Cargo.toml
  primitives/api/test/tests/decl_and_impl.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14755 chainHead: Add support for storage pagination and cancellation
  client/rpc-spec-v2/src/chain_head/api.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  client/rpc-spec-v2/src/chain_head/subscription/mod.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14568 Frame: Agile Coretime Broker pallet (RFC-1)
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/consensus/grandpa/src/communication/gossip.rs
  frame/broker/Cargo.toml
  frame/broker/README.md
  frame/broker/src/adapt_price.rs
  frame/broker/src/benchmarking.rs
  frame/broker/src/core_mask.rs
  frame/broker/src/coretime_interface.rs
  frame/broker/src/dispatchable_impls.rs
  frame/broker/src/lib.rs
  frame/broker/src/mock.rs
  frame/broker/src/nonfungible_impl.rs
  frame/broker/src/test_fungibles.rs
  frame/broker/src/tests.rs
  frame/broker/src/tick_impls.rs
  frame/broker/src/types.rs
  frame/broker/src/utility_impls.rs
  frame/broker/src/weights.rs
  frame/core-fellowship/src/lib.rs
  frame/glutton/src/lib.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/types/value.rs
  frame/support/src/traits/dispatch.rs
  frame/support/src/traits/tokens/fungible/hold.rs
  frame/support/src/traits/tokens/fungibles/hold.rs
  primitives/arithmetic/src/fixed_point.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#12092 [FRAME Core] New pallets: `safe-mode` and `tx-pause`
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/safe-mode/Cargo.toml
  frame/safe-mode/src/benchmarking.rs
  frame/safe-mode/src/lib.rs
  frame/safe-mode/src/mock.rs
  frame/safe-mode/src/tests.rs
  frame/safe-mode/src/weights.rs
  frame/support/src/traits.rs
  frame/support/src/traits/safe_mode.rs
  frame/support/src/traits/tx_pause.rs
  frame/system/src/lib.rs
  frame/tx-pause/Cargo.toml
  frame/tx-pause/src/benchmarking.rs
  frame/tx-pause/src/lib.rs
  frame/tx-pause/src/mock.rs
  frame/tx-pause/src/tests.rs
  frame/tx-pause/src/weights.rs
Labels: A0-please_review, C1-low, D2-notlive 💤, B1-note_worthy, T1-runtime

#14821 sc-consensus-beefy: restart voter on pallet reset
  client/consensus/beefy/src/communication/peers.rs
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/communication/request_response/mod.rs
  client/consensus/beefy/src/error.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/worker.rs
  primitives/consensus/beefy/src/mmr.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14682 Adds ability to provide defaults for types provided by `construct_runtime`
  Cargo.lock
  frame/balances/src/lib.rs
  frame/examples/default-config/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/src/derive_impl.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/config.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/src/lib.rs
  frame/support/src/tests/inject_runtime_type.rs
  frame/support/src/tests/mod.rs
  frame/support/test/tests/derive_impl_ui/inject_runtime_type_fails_when_type_not_in_scope.rs
  frame/support/test/tests/derive_impl_ui/inject_runtime_type_fails_when_type_not_in_scope.stderr
  frame/support/test/tests/derive_impl_ui/inject_runtime_type_invalid.rs
  frame/support/test/tests/derive_impl_ui/inject_runtime_type_invalid.stderr
  frame/support/test/tests/derive_impl_ui/pass/runtime_type_working.rs
  frame/support/test/tests/pallet_ui/default_config_with_no_default_in_system.rs
  frame/support/test/tests/pallet_ui/default_config_with_no_default_in_system.stderr
  frame/support/test/tests/pallet_ui/no_default_bounds_but_missing_with_default.rs
  frame/support/test/tests/pallet_ui/no_default_bounds_but_missing_with_default.stderr
  frame/system/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14813 update readme: archived repo
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤
