Repository paritytech/substrate, pull requests merged in 2023-07, with the labels that each got.

#14443 Pallets: Assets `destroy_accounts` releases the deposit
  frame/assets/src/functions.rs
  frame/assets/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#14311 migrations: VersionedRuntimeUpgrade
  frame/support/Cargo.toml
  frame/support/src/migrations.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/versioned_runtime_upgrade.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14489 Whitelist key `:intrablock_entropy`
  frame/benchmarking/src/v1.rs
  frame/support/procedural/src/benchmark.rs
  primitives/storage/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14493 contracts: stabilize `[seal0] instantiation_nonce()`
  frame/contracts/src/wasm/runtime.rs
Labels: B0-silent, D3-trivial 🧸, T4-smart_contracts

#14487 sc-tracing: Only print events for whitelisted targets
  client/tracing/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14398 sp-api: Put `frame-metadata` behind some feature
  frame/support/Cargo.toml
  primitives/api/Cargo.toml
  primitives/api/proc-macro/Cargo.toml
  primitives/api/proc-macro/src/decl_runtime_apis.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/lib.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/api/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14490 wasm-builder: Make `hash` and `date` optional
  utils/wasm-builder/src/version.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14084 contracts: switch to wasmi gas metering
  Cargo.lock
  frame/contracts/Cargo.toml
  frame/contracts/README.md
  frame/contracts/fixtures/seal_input_noop.wat
  frame/contracts/fixtures/seal_input_once.wat
  frame/contracts/fixtures/seal_input_twice.wat
  frame/contracts/proc-macro/src/lib.rs
  frame/contracts/src/benchmarking/code.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/benchmarking/sandbox.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/gas.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v10.rs
  frame/contracts/src/migration/v12.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/code_cache.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, Z4-involved, D5-nicetohaveaudit ⚠️, B1-note_worthy, C5-high, E0-runtime_migration, T1-runtime

#14480 Fix typo (#14479)
  frame/babe/src/equivocation.rs
  frame/beefy/src/equivocation.rs
  frame/grandpa/src/equivocation.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14496 Nomination pools: disallow setting above global max commission
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/tests.rs
Labels: A3-in_progress, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14499 Revert k256 removal
  Cargo.lock
  Cargo.toml
  frame/support/Cargo.toml
  frame/support/src/crypto/ecdsa.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14511 sc-cli: Remove `SubstrateCli::native_runtime_version` function
  bin/node-template/node/src/command.rs
  bin/node/cli/src/command.rs
  bin/node/executor/benches/bench.rs
  client/cli/src/commands/insert_key.rs
  client/cli/src/lib.rs
  client/cli/src/runner.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14510 Improve NFT locking
  frame/nft-fractionalization/src/lib.rs
  frame/nft-fractionalization/src/tests.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/impl_nonfungibles.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#14497 Use set_balance() instead of write_balance() in benchmark
  frame/asset-conversion/src/benchmarking.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14513 nom-pool try-state: improve logs
  frame/nomination-pools/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14515 chore: update some deps to prune duplicated deps
  Cargo.lock
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  client/cli/Cargo.toml
  client/cli/src/commands/generate_node_key.rs
  client/consensus/beefy/Cargo.toml
  client/consensus/beefy/src/communication/mod.rs
  client/consensus/grandpa/Cargo.toml
  client/consensus/grandpa/src/communication/tests.rs
  client/db/Cargo.toml
  client/executor/Cargo.toml
  client/keystore/Cargo.toml
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/light/Cargo.toml
  client/network/statement/Cargo.toml
  client/network/sync/Cargo.toml
  client/network/transactions/Cargo.toml
  client/offchain/Cargo.toml
  client/rpc-spec-v2/Cargo.toml
  client/service/test/Cargo.toml
  client/transaction-pool/Cargo.toml
  frame/alliance/Cargo.toml
  frame/beefy-mmr/Cargo.toml
  frame/beefy-mmr/src/tests.rs
  frame/benchmarking/Cargo.toml
  frame/contracts/Cargo.toml
  frame/contracts/src/exec.rs
  frame/contracts/src/wasm/mod.rs
  frame/executive/Cargo.toml
  frame/merkle-mountain-range/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-storage/Cargo.toml
  primitives/consensus/beefy/Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/bls.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/merkle-mountain-range/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/state-machine/src/testing.rs
  primitives/trie/Cargo.toml
  test-utils/client/Cargo.toml
  utils/binary-merkle-tree/Cargo.toml
  utils/binary-merkle-tree/src/lib.rs
  utils/frame/benchmarking-cli/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14502 ci: run tests with --features experimental
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#14363 Add `try-state` hook to pallet aura
  frame/aura/src/lib.rs
  frame/aura/src/mock.rs
  frame/aura/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14528 Fix typo: benchmarking module
  frame/benchmarking/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14503 contracts: Refactor instantiate with code
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration/v11.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14535 Fix spellcheck for benchmarking comments
  .maintain/frame-weight-template.hbs
  frame/balances/src/weights.rs
  utils/frame/benchmarking-cli/src/pallet/template.hbs
  utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14527 remove `OnStakerSlash` replace with `OnStakingEvents`
  Cargo.lock
  bin/node/runtime/src/lib.rs
  frame/babe/src/mock.rs
  frame/beefy/src/mock.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/root-offences/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/support/src/traits.rs
  frame/support/src/traits/voting.rs
  primitives/staking/Cargo.toml
  primitives/staking/src/currency_to_vote.rs
  primitives/staking/src/lib.rs
  utils/frame/generate-bags/Cargo.toml
  utils/frame/generate-bags/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14539 deps: replace lru with schnellru
  Cargo.lock
  client/executor/Cargo.toml
  client/executor/src/wasm_runtime.rs
  client/network-gossip/Cargo.toml
  client/network-gossip/src/state_machine.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/block_request_handler.rs
  client/network/sync/src/engine.rs
  client/network/sync/src/state_request_handler.rs
  primitives/blockchain/Cargo.toml
  primitives/blockchain/src/header_metadata.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14521 Better handling of error in inherents logic.
  frame/support/procedural/src/construct_runtime/expand/inherent.rs
  frame/support/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14537 Add missing workspace member
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14533 Contracts rename v9 to v09
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v09.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14557 Pallet balances quick updates
  frame/balances/src/lib.rs
  frame/support/src/traits/tokens/currency.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14552 Update `subkey` README.md
  bin/utils/subkey/README.md
Labels: I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14561 Fix refund benchmark for pallet_assets
  frame/assets/src/benchmarking.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14570 update to docify 0.2.0 / crate-relative embed paths
  Cargo.lock
  frame/fast-unstake/Cargo.toml
  frame/fast-unstake/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, E2-dependencies, T1-runtime

#14421 Fix Society v2 migration
  frame/society/Cargo.toml
  frame/society/src/lib.rs
  frame/society/src/migrations.rs
  frame/society/src/tests.rs
  frame/support/src/migrations.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A4-companion, E0-runtime_migration

#14558 Refactor the asset-conversion-tx-payment pallet
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/types.rs
  frame/support/src/traits/tokens/fungibles/mod.rs
  frame/support/src/traits/tokens/fungibles/regular.rs
  frame/transaction-payment/asset-conversion-tx-payment/Cargo.toml
  frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
  frame/transaction-payment/asset-conversion-tx-payment/src/payment.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14567 Re-add deprecated `--execution` arg on `benchmark pallet`
  bin/node/cli/tests/benchmark_block_works.rs
  bin/node/cli/tests/benchmark_extrinsic_works.rs
  bin/node/cli/tests/benchmark_overhead_works.rs
  bin/node/cli/tests/benchmark_pallet_works.rs
  primitives/core/src/defer.rs
  utils/frame/benchmarking-cli/src/pallet/command.rs
  utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14573 Fixes link to inflation documentation
  frame/staking/reward-fn/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14508 WasmExecutor flag to ignore onchain heappages value
  client/executor/src/executor.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14575 wrong name regex to filter url when provide --name=www as parameter in cli
  client/cli/src/commands/run_cmd.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14564 Remove redundant sync primitives for metrics
  client/network/src/service/out_events.rs
Labels: A0-please_review, B0-silent, C1-low

#14571 change $location from tt* to ty and remove unnecessary cb_* versions
  frame/balances/src/weights.rs
  frame/benchmarking/src/v1.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14523 Contracts add code_len to ContractsInfo
  frame/contracts/src/migration/v12.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/tests/pallet_dummy.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14580 Contracts add code_len to ContractsInfo (#14523)
  frame/contracts/src/migration/v12.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/tests/pallet_dummy.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/prepare.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A6-backport

#14554 fixing return types in crypto module documentation
  primitives/core/src/crypto.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14583 basic improvements to `sp-runtime` docs
  primitives/runtime/src/generic/mod.rs
  primitives/runtime/src/lib.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14578 improve pallet hooks docs
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/src/traits/hooks.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14532 [Do not merge] migration to ci-unified image
  .gitlab-ci.yml
Labels: A3-in_progress, B0-silent, C1-low

#14423 grandpa: avoid importing unnecessary justifications
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/consensus/grandpa/src/communication/gossip.rs
  client/consensus/grandpa/src/communication/tests.rs
  client/consensus/grandpa/src/environment.rs
  client/consensus/grandpa/src/import.rs
  client/consensus/grandpa/src/lib.rs
  client/consensus/grandpa/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#14440 Encryption support for the statement store
  Cargo.lock
  bin/node/cli/src/service.rs
  client/cli/src/runner.rs
  client/keystore/src/lib.rs
  client/network/src/discovery.rs
  client/network/src/protocol_controller.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  client/service/src/lib.rs
  client/statement-store/Cargo.toml
  client/statement-store/src/lib.rs
  frame/glutton/src/lib.rs
  frame/support/procedural/src/benchmark.rs
  frame/support/procedural/src/construct_runtime/expand/outer_enums.rs
  primitives/api/proc-macro/src/runtime_metadata.rs
  primitives/api/proc-macro/src/utils.rs
  primitives/application-crypto/src/lib.rs
  primitives/arithmetic/fuzzer/src/multiply_by_rational_with_rounding.rs
  primitives/blockchain/src/backend.rs
  primitives/core/Cargo.toml
  primitives/core/src/ed25519.rs
  primitives/core/src/sr25519.rs
  primitives/io/src/lib.rs
  primitives/statement-store/Cargo.toml
  primitives/statement-store/src/ecies.rs
  primitives/statement-store/src/lib.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14593 client: fix invalid node name pattern regex
  client/cli/src/commands/run_cmd.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14590 Handle the AllowMultiAssetPools=false case in benchmarks
  frame/asset-conversion/src/benchmarking.rs
  frame/asset-conversion/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14546 Run `integrity_test` in Externalities
  frame/fast-unstake/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/traits/hooks.rs
  frame/system/benchmarking/src/lib.rs
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14292 Improves the EPM/Staking e2e test setup
  Cargo.lock
  frame/election-provider-multi-phase/test-staking-e2e/Cargo.toml
  frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: A0-please_review, I5-tests, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14471 Don't use fixed nominator count for report_equivocation weight calculation
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/babe/src/default_weights.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  frame/beefy-mmr/src/mock.rs
  frame/beefy/src/default_weights.rs
  frame/beefy/src/lib.rs
  frame/beefy/src/mock.rs
  frame/beefy/src/tests.rs
  frame/grandpa/src/default_weights.rs
  frame/grandpa/src/lib.rs
  frame/grandpa/src/mock.rs
  frame/grandpa/src/tests.rs
  test-utils/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍

#14586 `WeightMeter`: more consistent naming
  frame/glutton/src/lib.rs
  frame/message-queue/src/benchmarking.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/scheduler/src/lib.rs
  primitives/weights/src/weight_meter.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14516 Make trie-cache resettable from backend
  client/db/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14247 Staking e2e test - Add case when ledger active balance falls below ED
  frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: A0-please_review, I5-tests, B0-silent, C1-low, D3-trivial 🧸

#14120 Introduce Pallet `paged-list`
  Cargo.lock
  Cargo.toml
  frame/paged-list/Cargo.toml
  frame/paged-list/fuzzer/Cargo.toml
  frame/paged-list/fuzzer/src/paged_list.rs
  frame/paged-list/src/lib.rs
  frame/paged-list/src/mock.rs
  frame/paged-list/src/paged_list.rs
  frame/paged-list/src/tests.rs
  frame/support/src/lib.rs
  frame/support/src/storage/mod.rs
  frame/support/src/storage/stream_iter.rs
Labels: A0-please_review, C1-low, D1-audited 👍, B1-note_worthy, T1-runtime

#14596 Improve logging for the request-response protocol
  client/network/src/request_responses.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14600 `chain-spec-builder`: redundant file removed `src/main.rs`
  bin/utils/chain-spec-builder/src/main.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14579 Contracts: Tweak call_runtime test
  frame/contracts/src/tests.rs
  frame/contracts/src/tests/pallet_dummy.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14565 Contracts: Enabled signed extension
  frame/contracts/src/wasm/prepare.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14572 Asset conversion `get_pool_id` fix (`Ord` does not count with `is_native` flag)
  frame/asset-conversion/src/benchmarking.rs
  frame/asset-conversion/src/lib.rs
  frame/asset-conversion/src/mock.rs
  frame/asset-conversion/src/tests.rs
  frame/asset-conversion/src/types.rs
  frame/asset-conversion/src/weights.rs
  frame/assets/src/impl_fungibles.rs
  frame/support/src/traits/tokens/fungibles/regular.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#14551 chainHead_storage: Backport queries for value types
  client/rpc-spec-v2/src/chain_head/api.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  client/rpc-spec-v2/src/chain_head/error.rs
  client/rpc-spec-v2/src/chain_head/event.rs
  client/rpc-spec-v2/src/chain_head/mod.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14604 Update logging from error to trace
  client/offchain/src/api/http.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14608 Do some cleanups
  client/consensus/beefy/src/communication/gossip.rs
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/justification.rs
  client/consensus/beefy/src/worker.rs
  client/consensus/grandpa/src/communication/gossip.rs
  client/consensus/grandpa/src/communication/mod.rs
  client/consensus/grandpa/src/communication/periodic.rs
  client/consensus/grandpa/src/justification.rs
  client/consensus/grandpa/src/warp_proof.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14614 minor updates to the substrate doc crate
  bin/utils/chain-spec-builder/src/lib.rs
  client/chain-spec/src/lib.rs
  scripts/ci/gitlab/pipeline/build.yml
  src/lib.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14603 Accept only `--in-peers` many inbound full nodes in `SyncingEngine`
  client/network/src/event.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/sync/src/engine.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14245 Do not include voters that have zero voter weight in the election snapshot
  frame/election-provider-multi-phase/src/benchmarking.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14591 [fix lint warnings: Uniques pallet] fix clippy::missing_docs_in_private_items warnings
  frame/uniques/src/lib.rs
  frame/uniques/src/types.rs
Labels: A0-please_review, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14592 [fix lint warnings: Uniques pallet] fix clippy::doc_markdown warnings
  .maintain/frame-weight-template.hbs
  frame/uniques/src/weights.rs
Labels: A0-please_review, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14310 `test-runtime`: `GenesisBuilder` runtime API impl + tests
  Cargo.lock
  client/rpc-spec-v2/src/chain_head/tests.rs
  client/rpc/src/state/tests.rs
  frame/support/Cargo.toml
  frame/support/src/genesis_builder_helper.rs
  frame/support/src/lib.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/build.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/test_json/README.md
  test-utils/runtime/src/test_json/default_genesis_config.json
  test-utils/runtime/src/test_json/default_genesis_config_incomplete.json
  test-utils/runtime/src/test_json/default_genesis_config_invalid.json
Labels: B0-silent, C1-low, D3-trivial 🧸

#14186 Removes incorrect `try-state` check in staking
  frame/staking/src/pallet/impls.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14626 Contracts: Enabled signed extension (#14565)
  frame/contracts/src/wasm/prepare.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A6-backport

#14627 upgrade to macro_magic 0.4.2
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, E2-dependencies, T1-runtime

#14395 changes to nfts pallet for xcm integration
  frame/asset-conversion/src/lib.rs
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/common_functions.rs
  frame/nfts/src/features/create_delete_collection.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/support/src/traits/storage.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-please_review, C3-medium, D2-notlive 💤, B1-note_worthy, T1-runtime

#14429 chore: update libp2p to 0.52.1
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/addr_cache.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network-gossip/Cargo.toml
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/lib.rs
  client/network-gossip/src/state_machine.rs
  client/network-gossip/src/validator.rs
  client/network/Cargo.toml
  client/network/bitswap/Cargo.toml
  client/network/common/Cargo.toml
  client/network/light/Cargo.toml
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/protocol/notifications/upgrade/collec.rs
  client/network/src/protocol/notifications/upgrade/notifications.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/types.rs
  client/network/statement/Cargo.toml
  client/network/statement/src/lib.rs
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/network/transactions/src/lib.rs
  client/offchain/Cargo.toml
  client/service/src/lib.rs
  client/telemetry/Cargo.toml
  frame/support/Cargo.toml
  primitives/core/hashing/Cargo.toml
  primitives/state-machine/Cargo.toml
  primitives/statement-store/Cargo.toml
  primitives/weights/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14483 change HashFor to HashingFor
  bin/node/inspect/src/lib.rs
  bin/node/rpc/src/lib.rs
  client/api/src/backend.rs
  client/api/src/in_mem.rs
  client/basic-authorship/src/basic_authorship.rs
  client/block-builder/src/lib.rs
  client/consensus/common/src/block_import.rs
  client/consensus/slots/src/lib.rs
  client/db/src/bench.rs
  client/db/src/lib.rs
  client/db/src/record_stats_state.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/protocol_controller.rs
  client/network/sync/src/lib.rs
  client/service/src/client/client.rs
  client/transaction-pool/src/api.rs
  frame/state-trie-migration/src/lib.rs
  primitives/api/proc-macro/src/impl_runtime_apis.rs
  primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  primitives/api/src/lib.rs
  primitives/api/test/tests/runtime_calls.rs
  primitives/consensus/common/src/lib.rs
  primitives/runtime/src/traits.rs
  utils/frame/benchmarking-cli/src/storage/cmd.rs
  utils/frame/benchmarking-cli/src/storage/write.rs
  utils/frame/remote-externalities/src/lib.rs
Labels: A2-insubstantial, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14642 Contracts: Bugfix Wasm prepare check for chain extension
  frame/contracts/fixtures/chain_extension.wat
  frame/contracts/src/wasm/prepare.rs
Labels: I3-bug, B0-silent, D3-trivial 🧸

#14079 Contracts Add deposit for dependencies
  bin/node/runtime/src/lib.rs
  frame/contracts/fixtures/add_remove_delegate_dependency.wat
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v13.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, E0-runtime_migration, T1-runtime

#14514 Pallets: Asset Rate - Rename AssetId to AssetKind, Introduce AssetKindFactory Trait
  bin/node/runtime/src/lib.rs
  frame/asset-rate/Cargo.toml
  frame/asset-rate/src/benchmarking.rs
  frame/asset-rate/src/lib.rs
  frame/asset-rate/src/mock.rs
  frame/asset-rate/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, F3-breaks_API

#14647 Relax Send/Sync/Clone requirements for Pair
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/import_queue.rs
  primitives/core/src/crypto.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14644 Export trait `HandleMessage`
  frame/support/src/traits.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13894 Update reservable docs to reflect actual ed
  frame/support/src/traits/tokens/currency/reservable.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14646 Update Matrix and secrets
  .github/workflows/burnin-label-notification.yml
  .github/workflows/release-bot.yml
  .github/workflows/release-tagging.yml
  scripts/ci/common/lib.sh
  scripts/ci/gitlab/publish_draft_release.sh
Labels: A0-please_review, B0-silent

#14671 Remove readme from pallet-example-kitchensink's Cargo.toml
  frame/examples/kitchensink/Cargo.toml
Labels: A0-please_review, A2-insubstantial, B0-silent, D2-notlive 💤

#14668 [fix docs compiler warnings] Nicks pallet
  frame/nicks/src/lib.rs
Labels: A2-insubstantial, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#14674 Add discord invite to contributing doc
  README.md
  docs/CONTRIBUTING.adoc
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/README.adoc
Labels: A0-please_review, I6-documentation, B0-silent, C1-low, D3-trivial 🧸

#13949 Try-state for Referenda pallet
  frame/referenda/src/benchmarking.rs
  frame/referenda/src/lib.rs
  frame/referenda/src/migration.rs
  frame/referenda/src/mock.rs
  frame/referenda/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14654 chainHead: Sync events with spec
  client/rpc-spec-v2/src/chain_head/api.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  client/rpc-spec-v2/src/chain_head/event.rs
  client/rpc-spec-v2/src/chain_head/mod.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14667 use `Toggle` instead of Option for mdns
  client/network/src/discovery.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14676 Contracts: Ensure latest migration match pallet_version
  bin/node/runtime/src/lib.rs
  frame/contracts/Cargo.toml
  frame/contracts/build.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14685 [FRAME] Remove V1 Module Syntax
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/no_bound/clone.rs
  frame/support/procedural/src/no_bound/debug.rs
  frame/support/procedural/src/no_bound/default.rs
  frame/support/procedural/src/no_bound/mod.rs
  frame/support/procedural/src/no_bound/partial_eq.rs
  frame/support/procedural/src/storage/genesis_config/builder_def.rs
  frame/support/procedural/src/storage/genesis_config/genesis_config_def.rs
  frame/support/procedural/src/storage/genesis_config/mod.rs
  frame/support/procedural/src/storage/getters.rs
  frame/support/procedural/src/storage/instance_trait.rs
  frame/support/procedural/src/storage/metadata.rs
  frame/support/procedural/src/storage/mod.rs
  frame/support/procedural/src/storage/parse.rs
  frame/support/procedural/src/storage/print_pallet_upgrade.rs
  frame/support/procedural/src/storage/storage_info.rs
  frame/support/procedural/src/storage/storage_struct.rs
  frame/support/procedural/src/storage/store_trait.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/event.rs
  frame/support/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime
