Repository paritytech/substrate, pull requests merged in 2023-05, with the labels that each got.

#14047 Fix bags-list tests execution
  frame/bags-list/src/lib.rs
  frame/bags-list/src/mock.rs
  frame/election-provider-support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13994 CI: migrate to Google Cloud
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#13708 contracts: Make Origin information available
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/exec.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/schedule.rs
  frame/contracts/src/storage/meter.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/contracts/src/weights.rs
  primitives/runtime/src/lib.rs
Labels: B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14061 Bump clap to 4.2.5
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node/bench/Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/inspect/Cargo.toml
  bin/utils/chain-spec-builder/Cargo.toml
  bin/utils/subkey/Cargo.toml
  client/cli/Cargo.toml
  client/storage-monitor/Cargo.toml
  frame/election-provider-support/solution-type/fuzzer/Cargo.toml
  primitives/npos-elections/fuzzer/Cargo.toml
  utils/frame/benchmarking-cli/Cargo.toml
  utils/frame/frame-utilities-cli/Cargo.toml
  utils/frame/generate-bags/node-runtime/Cargo.toml
  utils/frame/try-runtime/cli/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸, E2-dependencies

#13999 Manual seal delayed finalize
  Cargo.lock
  client/consensus/manual-seal/Cargo.toml
  client/consensus/manual-seal/src/lib.rs
  client/consensus/manual-seal/src/rpc.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14064 Don't run `check-crates-publishing` job on prs
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low

#14067 Only calculate tree route during finalization when there are multiple leaves
  client/service/src/client/client.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14062 test-staking-e2e: Add to main `Cargo.toml`.
  Cargo.lock
  Cargo.toml
  frame/election-provider-multi-phase/test-staking-e2e/Cargo.lock
  frame/election-provider-multi-phase/test-staking-e2e/Cargo.toml
  frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13807 contracts: add events to ContractResult
  bin/node/runtime/src/lib.rs
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/tests.rs
Labels: A0-please_review, C3-medium, D2-breaksapi, B1-note_worthy, T2-API

#14069 Backport of #14067 for release 0.9.42
  client/service/src/client/client.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A6-backport, T0-node

#13384 rpc server: break legacy CLI options and remove "backward compatible HTTP server"
  .gitlab-ci.yml
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/runner.rs
  client/rpc-servers/src/lib.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
  test-utils/cli/src/lib.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#14063 Account touch trait
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
Labels: A0-please_review, B0-silent, C1-low, D1-audited 👍, T1-runtime

#14036 Refinements to VRF types
  client/consensus/babe/src/authorship.rs
  client/consensus/babe/src/tests.rs
  client/consensus/babe/src/verification.rs
  client/keystore/src/local.rs
  frame/babe/src/lib.rs
  frame/babe/src/mock.rs
  frame/babe/src/tests.rs
  primitives/consensus/babe/src/lib.rs
  primitives/core/src/crypto.rs
  primitives/core/src/sr25519.rs
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13737 substrate-test-runtime migrated to "pure" frame runtime
  Cargo.lock
  client/basic-authorship/src/basic_authorship.rs
  client/basic-authorship/src/lib.rs
  client/block-builder/src/lib.rs
  client/consensus/babe/src/tests.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/grandpa/src/tests.rs
  client/consensus/grandpa/src/warp_proof.rs
  client/network/bitswap/src/lib.rs
  client/network/test/src/lib.rs
  client/network/test/src/sync.rs
  client/offchain/src/lib.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
  client/rpc/src/author/tests.rs
  client/rpc/src/dev/tests.rs
  client/rpc/src/state/tests.rs
  client/service/src/lib.rs
  client/service/test/src/client/mod.rs
  client/transaction-pool/benches/basics.rs
  client/transaction-pool/src/graph/pool.rs
  client/transaction-pool/src/revalidation.rs
  client/transaction-pool/src/tests.rs
  client/transaction-pool/tests/pool.rs
  primitives/api/test/tests/runtime_calls.rs
  test-utils/runtime/Cargo.toml
  test-utils/runtime/client/src/block_builder_ext.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/extrinsic.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/substrate_test_pallet.rs
  test-utils/runtime/src/system.rs
  test-utils/runtime/transaction-pool/src/lib.rs
  utils/frame/rpc/system/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#13852 fungible conformance tests: Inspect and Mutate
  Cargo.lock
  frame/balances/Cargo.toml
  frame/balances/src/tests/fungible_conformance_tests.rs
  frame/balances/src/tests/mod.rs
  frame/support/src/traits/tokens/fungible/conformance_tests/inspect_mutate.rs
  frame/support/src/traits/tokens/fungible/conformance_tests/mod.rs
  frame/support/src/traits/tokens/fungible/mod.rs
  frame/support/src/traits/tokens/fungible/regular.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14077 Add fast-unstake pallet to Staking proxy
  bin/node/runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14057 remote-externalities: 'instant' snapshots, threading refactor, better progress logs
  Cargo.lock
  primitives/state-machine/src/testing.rs
  primitives/state-machine/src/trie_backend.rs
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
  utils/frame/remote-externalities/test_data/proxy_test
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13574 Upgrade wasm-opt to 0.112.0
  Cargo.lock
  utils/wasm-builder/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#13654 Add Junit test reports
  .config/nextest.toml
  scripts/ci/gitlab/pipeline/test.yml
Labels: B0-silent

#14078 Update codeowners file
  docs/CODEOWNERS
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14082 contracts: add error logging to `call_runtime`
  frame/contracts/src/wasm/runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14083 Improve `try-runtime::on_runtime_upgrade` and fix some storage version issues
  frame/bounties/src/lib.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/traits/hooks.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14086 Remote ext parallel download fix
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14088 fix cli: make rpc port Option<u16> again
  bin/node/cli/benches/block_production.rs
  bin/node/cli/benches/transaction_pool.rs
  client/cli/src/commands/run_cmd.rs
  client/cli/src/config.rs
  client/cli/src/runner.rs
  client/service/src/config.rs
  client/service/src/lib.rs
  client/service/test/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#13843 Allow Creation of Asset Accounts That Don't Exist Yet and Add `Blocked` Status
  frame/assets/src/benchmarking.rs
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/migration.rs
  frame/assets/src/tests.rs
  frame/assets/src/types.rs
  frame/assets/src/weights.rs
  frame/support/src/traits.rs
  frame/support/src/traits/misc.rs
  frame/support/src/traits/tokens/misc.rs
  primitives/runtime/src/lib.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#14093 Re-enable `node-cli` tests in CI and fix them
  scripts/ci/gitlab/pipeline/test.yml
  test-utils/cli/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#12445 frame-support-test: migrate tests from `decl_*` macros to the new `pallet` macros
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/tests_instance.rs
  frame/collective/src/tests.rs
  frame/executive/src/lib.rs
  frame/support/test/compile_pass/Cargo.toml
  frame/support/test/compile_pass/src/lib.rs
  frame/support/test/pallet/src/lib.rs
  frame/support/test/src/lib.rs
  frame/support/test/src/pallet_version.rs
  frame/support/test/tests/benchmark_ui/invalid_origin.rs
  frame/support/test/tests/benchmark_ui/invalid_origin.stderr
  frame/support/test/tests/construct_runtime.rs
  frame/support/test/tests/construct_runtime_ui/old_unsupported_pallet_decl.rs
  frame/support/test/tests/construct_runtime_ui/old_unsupported_pallet_decl.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr
  frame/support/test/tests/decl_module_ui.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.rs
  frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr
  frame/support/test/tests/decl_storage.rs
  frame/support/test/tests/decl_storage_ui.rs
  frame/support/test/tests/decl_storage_ui/config_duplicate.rs
  frame/support/test/tests/decl_storage_ui/config_duplicate.stderr
  frame/support/test/tests/decl_storage_ui/config_get_duplicate.rs
  frame/support/test/tests/decl_storage_ui/config_get_duplicate.stderr
  frame/support/test/tests/decl_storage_ui/get_duplicate.rs
  frame/support/test/tests/decl_storage_ui/get_duplicate.stderr
  frame/support/test/tests/final_keys.rs
  frame/support/test/tests/genesisconfig.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/support/test/tests/origin.rs
  frame/support/test/tests/pallet_compatibility.rs
  frame/support/test/tests/pallet_compatibility_instance.rs
  frame/support/test/tests/pallet_instance.rs
  frame/support/test/tests/pallet_with_name_trait_is_valid.rs
  frame/support/test/tests/storage_layers.rs
  frame/support/test/tests/storage_transaction.rs
  frame/support/test/tests/system.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14099 Emit events related to asset mutations
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13705 Deprecate Pallet `decl_*` Macros
  frame/support/procedural/src/lib.rs
  frame/support/src/dispatch.rs
  frame/support/src/error.rs
  frame/support/src/event.rs
Labels: A3-in_progress, C3-medium, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14104 macros: Add non_camel_case_types for storage_alias
  frame/support/procedural/src/storage_alias.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14105 Move back to ci-linux:production image after upgrade
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#13618 BLS Core Crypto attempt #2
  Cargo.lock
  client/keystore/Cargo.toml
  client/keystore/src/local.rs
  primitives/application-crypto/src/bls377.rs
  primitives/application-crypto/src/bls381.rs
  primitives/application-crypto/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/bls.rs
  primitives/core/src/hexdisplay.rs
  primitives/core/src/lib.rs
  primitives/core/src/testing.rs
  primitives/keystore/Cargo.toml
  primitives/keystore/src/lib.rs
  primitives/keystore/src/testing.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14102 Backport 14099
  frame/assets/src/impl_fungibles.rs
  frame/assets/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A6-backport

#14111 Remove the `Copy` bound on `CollectionId` in the uniques pallet
  frame/uniques/src/benchmarking.rs
  frame/uniques/src/functions.rs
  frame/uniques/src/impl_nonfungibles.rs
  frame/uniques/src/lib.rs
Labels: A0-please_review, I7-refactor, B0-silent, C1-low, D3-trivial 🧸

#14106 Timeout only if the referendum is not queued
  frame/referenda/src/lib.rs
  frame/referenda/src/tests.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#14103 Include `node-template-release` in workspace
  .gitignore
  Cargo.lock
  Cargo.toml
  scripts/ci/deny.toml
  scripts/ci/node-template-release/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14113 Bump `kvdb-rocksdb` to 0.19.0
  Cargo.lock
  bin/node/bench/Cargo.toml
  client/db/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#14116 Remove `#[pallet::generate_storage_info]` from docs
  frame/support/procedural/src/lib.rs
  frame/support/src/lib.rs
  frame/support/test/tests/pallet_ui/pallet_struct_invalid_attr.rs
  frame/support/test/tests/pallet_ui/pallet_struct_invalid_attr.stderr
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14121 Bump `Cargo.lock`
  Cargo.lock
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low

#14080 Prepare `sc-network` for `ProtocolController`/`NotificationService`
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node/cli/src/service.rs
  client/cli/src/params/network_params.rs
  client/consensus/beefy/src/communication/mod.rs
  client/consensus/grandpa/src/lib.rs
  client/network/src/config.rs
  client/network/src/protocol.rs
  client/network/src/service.rs
  client/network/sync/src/engine.rs
  client/network/test/src/lib.rs
  client/network/test/src/service.rs
  client/service/src/builder.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#13880 Benchmark pallet sudo
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/sudo/Cargo.toml
  frame/sudo/src/benchmarking.rs
  frame/sudo/src/lib.rs
  frame/sudo/src/mock.rs
  frame/sudo/src/weights.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, F3-breaks_API

#14039 Staking::{bond, set_controller} to set controllers to stash only.
  .gitlab-ci.yml
  bin/node/cli/src/chain_spec.rs
  bin/node/testing/src/genesis.rs
  frame/babe/src/mock.rs
  frame/beefy/src/mock.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  frame/fast-unstake/src/mock.rs
  frame/fast-unstake/src/tests.rs
  frame/grandpa/src/mock.rs
  frame/offences/benchmarking/src/lib.rs
  frame/root-offences/src/mock.rs
  frame/session/benchmarking/src/lib.rs
  frame/staking/README.md
  frame/staking/src/benchmarking.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/staking/src/testing_utils.rs
  frame/staking/src/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13587 Upgrade to libp2p 0.51.3
  Cargo.lock
  client/authority-discovery/Cargo.toml
  client/authority-discovery/src/error.rs
  client/authority-discovery/src/tests.rs
  client/authority-discovery/src/worker.rs
  client/authority-discovery/src/worker/schema/tests.rs
  client/authority-discovery/src/worker/tests.rs
  client/cli/Cargo.toml
  client/cli/src/commands/generate_node_key.rs
  client/cli/src/commands/inspect_node_key.rs
  client/cli/src/params/node_key_params.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/import_queue/basic_queue.rs
  client/network-gossip/Cargo.toml
  client/network/Cargo.toml
  client/network/README.md
  client/network/bitswap/Cargo.toml
  client/network/bitswap/src/lib.rs
  client/network/common/Cargo.toml
  client/network/common/src/sync.rs
  client/network/light/Cargo.toml
  client/network/light/src/light_client_requests/handler.rs
  client/network/src/behaviour.rs
  client/network/src/config.rs
  client/network/src/discovery.rs
  client/network/src/event.rs
  client/network/src/lib.rs
  client/network/src/peer_info.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/request_responses.rs
  client/network/src/service.rs
  client/network/src/service/signature.rs
  client/network/src/service/traits.rs
  client/network/src/transport.rs
  client/network/statement/Cargo.toml
  client/network/sync/Cargo.toml
  client/network/test/Cargo.toml
  client/network/transactions/Cargo.toml
  client/offchain/Cargo.toml
  client/peerset/Cargo.toml
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
  client/peerset/tests/fuzz.rs
  client/telemetry/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#14125 fix broken gensis state doc link
  frame/support/procedural/src/pallet/expand/genesis_config.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14133 chore(storage-monitor): improve `free_space` calculation and cli default value
  client/storage-monitor/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14134 remove `sp-serializer` which is not useful
  Cargo.lock
  Cargo.toml
  primitives/core/Cargo.toml
  primitives/core/src/hash.rs
  primitives/core/src/uint.rs
  primitives/serializer/Cargo.toml
  primitives/serializer/README.md
  primitives/serializer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14140 Fix staking genesis build
  frame/staking/src/pallet/mod.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14142 Postpone public key creation in the test GenesisStorageBuilder
  client/service/test/src/client/mod.rs
  test-utils/runtime/client/src/lib.rs
  test-utils/runtime/src/genesismap.rs
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/substrate_test_pallet.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13717 Adds integration test for slashed/chilled validator with subsequent validation intention
  frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: A0-please_review, Z0-trivial, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14149 Introduce `entropy` function into frame System
  frame/system/src/lib.rs
  frame/system/src/tests.rs
  primitives/storage/src/lib.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#14136 fully enable `RuntimeDebug` in `feature = try-runtime`
  Cargo.lock
  frame/support/Cargo.toml
  frame/support/procedural/src/lib.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#14152 FRAME: Tweak `frame_system::unique` to avoid minor entropy loss
  frame/system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14132 expose transport, peer_info and discovery in sc-network
  client/network/src/lib.rs
  client/network/src/peer_info.rs
  client/network/src/transport.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14058 Move node-template Cargo.toml dependencies to workspace
  Cargo.lock
  docs/node-template-release.md
  scripts/ci/node-template-release/Cargo.toml
  scripts/ci/node-template-release/src/main.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14122 Add review rules regarding the owned files
  .github/pr-custom-review.yml
Labels: A0-please_review, B0-silent, C1-low

#14124 Change unit test upload step
  scripts/ci/gitlab/pipeline/test.yml
Labels: B0-silent

#14161 Fix indent for pr-custom-review config
  .github/pr-custom-review.yml
Labels: A0-please_review, B0-silent, C1-low

#13460 remove deprecated remove_prefix to clear era_info
  frame/staking/src/pallet/impls.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#13313 Max class voters for ranked collective vote tally
  frame/ranked-collective/src/lib.rs
  frame/ranked-collective/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#13027 Add `serde` feature flag to primitives
  Cargo.lock
  primitives/application-crypto/Cargo.toml
  primitives/application-crypto/src/lib.rs
  primitives/arithmetic/Cargo.toml
  primitives/arithmetic/src/fixed_point.rs
  primitives/arithmetic/src/lib.rs
  primitives/arithmetic/src/per_things.rs
  primitives/consensus/babe/Cargo.toml
  primitives/consensus/babe/src/lib.rs
  primitives/consensus/beefy/Cargo.toml
  primitives/consensus/beefy/src/mmr.rs
  primitives/consensus/grandpa/Cargo.toml
  primitives/consensus/grandpa/src/lib.rs
  primitives/consensus/slots/Cargo.toml
  primitives/consensus/slots/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/crypto.rs
  primitives/core/src/ecdsa.rs
  primitives/core/src/ed25519.rs
  primitives/core/src/lib.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/sr25519.rs
  primitives/merkle-mountain-range/Cargo.toml
  primitives/merkle-mountain-range/src/lib.rs
  primitives/npos-elections/Cargo.toml
  primitives/npos-elections/src/assignments.rs
  primitives/npos-elections/src/lib.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/generic/block.rs
  primitives/runtime/src/generic/digest.rs
  primitives/runtime/src/generic/era.rs
  primitives/runtime/src/generic/header.rs
  primitives/runtime/src/generic/unchecked_extrinsic.rs
  primitives/runtime/src/legacy/byte_sized_error.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/runtime_string.rs
  primitives/runtime/src/traits.rs
  primitives/runtime/src/transaction_validity.rs
  primitives/storage/Cargo.toml
  primitives/storage/src/lib.rs
  primitives/test-primitives/Cargo.toml
  primitives/test-primitives/src/lib.rs
  primitives/version/Cargo.toml
  primitives/version/src/lib.rs
  primitives/weights/Cargo.toml
  primitives/weights/src/lib.rs
  primitives/weights/src/weight_v2.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14130 chore: move whitelist test to better place and add missing `Inactive Issuance`
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  frame/balances/src/tests/mod.rs
  frame/system/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14166 Added serde feature to sp-consensus-aura
  primitives/consensus/aura/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14164 Adds ability to use default hasher in `dev_mode` for explicit key binding
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/parse/storage.rs
  frame/support/test/tests/pallet_ui/non_dev_mode_storage_map_explicit_key_default_hasher.rs
  frame/support/test/tests/pallet_ui/non_dev_mode_storage_map_explicit_key_default_hasher.stderr
  frame/support/test/tests/pallet_ui/pass/dev_mode_valid.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14177 Fix typos
  bin/utils/subkey/README.md
Labels: A2-insubstantial, B0-silent, C1-low

#14179 Core-Fellowship: use right origin for `approve` call
  frame/core-fellowship/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14167 remote-externalities: retry for get_keys
  Cargo.lock
  utils/frame/remote-externalities/Cargo.toml
  utils/frame/remote-externalities/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#14108 frame: Enable GenesisConfig in no_std
  frame/alliance/src/lib.rs
  frame/assets/src/lib.rs
  frame/aura/src/lib.rs
  frame/authority-discovery/src/lib.rs
  frame/babe/src/lib.rs
  frame/balances/src/lib.rs
  frame/beefy/src/lib.rs
  frame/collective/src/lib.rs
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/examples/basic/src/lib.rs
  frame/grandpa/src/lib.rs
  frame/im-online/src/lib.rs
  frame/indices/src/lib.rs
  frame/membership/src/lib.rs
  frame/node-authorization/src/lib.rs
  frame/nomination-pools/src/lib.rs
  frame/scored-pool/src/lib.rs
  frame/session/src/lib.rs
  frame/society/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/sudo/src/lib.rs
  frame/support/procedural/src/pallet/expand/genesis_config.rs
  frame/support/test/pallet/src/lib.rs
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr
  frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr
  frame/system/src/lib.rs
  frame/transaction-payment/src/lib.rs
  frame/transaction-storage/src/lib.rs
  frame/treasury/src/lib.rs
  frame/vesting/src/lib.rs
Labels: C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#13706 Update the nix build configuration.
  .gitignore
  bin/node-template/.envrc
  bin/node-template/README.md
  bin/node-template/flake.lock
  bin/node-template/flake.nix
  bin/node-template/rust-toolchain.toml
  bin/node-template/shell.nix
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14183 FRAME: Allow message ID to be mutated in `ProcessMessage`
  frame/message-queue/src/benchmarking.rs
  frame/message-queue/src/lib.rs
  frame/message-queue/src/mock.rs
  frame/message-queue/src/mock_helpers.rs
  frame/message-queue/src/tests.rs
  frame/support/src/traits/messages.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#14182 RevertCmd: Expose database params via CLI
  client/cli/src/commands/revert_cmd.rs
Labels: A2-insubstantial, Z0-trivial, C1-low, B1-note_worthy, T0-node

#13967 Improve try-state docs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14180 test-runtime: Return hashed call as provides in unsigned validation
  test-utils/runtime/src/lib.rs
  test-utils/runtime/src/substrate_test_pallet.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14176 Revert "Optimize merkle proofs for efficient verification in Solidity (#12857)"
  frame/beefy-mmr/src/tests.rs
  frame/merkle-mountain-range/src/lib.rs
  utils/binary-merkle-tree/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14184 Executor: Add `create_runtime_from_artifact_bytes`
  client/executor/benches/bench.rs
  client/executor/wasmtime/src/lib.rs
  client/executor/wasmtime/src/runtime.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14190 WarpSync: Show number of required peers in informant
  client/network/common/src/sync/warp.rs
  client/network/sync/src/lib.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#13993 BREAKING - Try-runtime: Use proper error types
  frame/assets/src/migration.rs
  frame/bags-list/src/lib.rs
  frame/bags-list/src/list/mod.rs
  frame/bags-list/src/list/tests.rs
  frame/bags-list/src/migrations.rs
  frame/collective/src/lib.rs
  frame/contracts/src/migration.rs
  frame/democracy/src/migrations.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/election-provider-support/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/executive/src/lib.rs
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/migrations.rs
  frame/multisig/src/migrations.rs
  frame/nfts/src/migration.rs
  frame/nomination-pools/src/lib.rs
  frame/nomination-pools/src/migration.rs
  frame/nomination-pools/src/tests.rs
  frame/offences/src/migration.rs
  frame/preimage/src/migration.rs
  frame/referenda/src/migration.rs
  frame/scheduler/src/migration.rs
  frame/staking/src/migrations.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  frame/support/procedural/src/pallet/expand/hooks.rs
  frame/support/src/dispatch.rs
  frame/support/src/migrations.rs
  frame/support/src/traits/hooks.rs
  frame/support/src/traits/try_runtime.rs
  frame/support/test/tests/pallet.rs
  primitives/runtime/src/lib.rs
  utils/frame/try-runtime/cli/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#12565 NFTs fractionalization
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/assets/src/functions.rs
  frame/assets/src/impl_fungibles.rs
  frame/nft-fractionalization/Cargo.toml
  frame/nft-fractionalization/README.md
  frame/nft-fractionalization/src/benchmarking.rs
  frame/nft-fractionalization/src/lib.rs
  frame/nft-fractionalization/src/mock.rs
  frame/nft-fractionalization/src/tests.rs
  frame/nft-fractionalization/src/types.rs
  frame/nft-fractionalization/src/weights.rs
  frame/nfts/src/features/attributes.rs
  frame/nfts/src/features/transfer.rs
  frame/nfts/src/impl_nonfungibles.rs
  frame/nfts/src/types.rs
  frame/support/src/traits/tokens/fungible/regular.rs
  frame/support/src/traits/tokens/fungibles/metadata.rs
  frame/support/src/traits/tokens/misc.rs
  frame/support/src/traits/tokens/nonfungible_v2.rs
  frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#14144 Actually respect locks of zero
  frame/balances/src/impl_currency.rs
  frame/offences/benchmarking/src/lib.rs
Labels: A0-please_review, C3-medium, D9-needsaudit 👮, B1-note_worthy, T1-runtime

#13611 Split `Peerset` into reputation store & `ProtocolController`s
  Cargo.lock
  client/consensus/grandpa/src/communication/tests.rs
  client/network-gossip/src/bridge.rs
  client/network-gossip/src/state_machine.rs
  client/network/src/protocol.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/notifications/tests.rs
  client/network/src/service.rs
  client/network/src/service/traits.rs
  client/network/sync/src/service/mock.rs
  client/offchain/src/api.rs
  client/offchain/src/lib.rs
  client/peerset/Cargo.toml
  client/peerset/src/lib.rs
  client/peerset/src/peer_store.rs
  client/peerset/src/peersstate.rs
  client/peerset/src/protocol_controller.rs
  client/peerset/tests/fuzz.rs
  client/utils/src/mpsc.rs
Labels: A0-please_review, B0-silent, C1-low, D2-breaksapi

#14188 Add genesis config to Glutton pallet
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/glutton/src/lib.rs
  frame/glutton/src/mock.rs
  frame/glutton/src/tests.rs
Labels: A0-please_review, J0-enhancement, B0-silent, C1-low, D3-trivial 🧸, T5-parachains

#14191 TrieCache: Fine tune the size of the local and node cache
  primitives/trie/src/cache/mod.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14195 Easy PR: Fix warnings from latest nightly
  bin/node/bench/src/tempdb.rs
  client/db/src/parity_db.rs
  client/db/src/pinned_blocks_cache.rs
  client/network/src/protocol/notifications/handler.rs
  client/network/sync/src/state.rs
  client/statement-store/src/lib.rs
  frame/bounties/src/lib.rs
  frame/child-bounties/src/lib.rs
  frame/nomination-pools/benchmarking/src/lib.rs
  frame/staking/src/pallet/mod.rs
  frame/support/src/storage/generator/double_map.rs
  frame/support/src/storage/generator/map.rs
  primitives/npos-elections/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14178 wasm: Update from v6.0.2 to v8.0.1
  Cargo.lock
  client/executor/wasmtime/Cargo.toml
  primitives/wasm-interface/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14205 sc-client-db: add test for reverting finalized blocks
  client/db/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14199 Fix request-response protocols backpressure mechanism
  Cargo.lock
  client/consensus/beefy/Cargo.toml
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/communication/request_response/mod.rs
  client/network/bitswap/Cargo.toml
  client/network/bitswap/src/lib.rs
  client/network/light/Cargo.toml
  client/network/light/src/light_client_requests/handler.rs
  client/network/src/request_responses.rs
  client/network/sync/Cargo.toml
  client/network/sync/src/block_request_handler.rs
  client/network/sync/src/state_request_handler.rs
  client/network/sync/src/warp_request_handler.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#13869 HoldReason: Improve usage
  bin/node-template/runtime/src/lib.rs
  bin/node/runtime/src/lib.rs
  client/executor/benches/bench.rs
  frame/alliance/src/mock.rs
  frame/asset-rate/src/mock.rs
  frame/assets/src/mock.rs
  frame/atomic-swap/src/tests.rs
  frame/babe/src/mock.rs
  frame/balances/src/impl_fungible.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests/mod.rs
  frame/beefy/src/mock.rs
  frame/bounties/src/tests.rs
  frame/child-bounties/src/tests.rs
  frame/contracts/src/tests.rs
  frame/conviction-voting/src/tests.rs
  frame/democracy/src/tests.rs
  frame/election-provider-multi-phase/src/mock.rs
  frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  frame/elections-phragmen/src/lib.rs
  frame/examples/basic/src/tests.rs
  frame/examples/dev-mode/src/tests.rs
  frame/executive/src/lib.rs
  frame/fast-unstake/src/mock.rs
  frame/grandpa/src/mock.rs
  frame/identity/src/tests.rs
  frame/indices/src/mock.rs
  frame/lottery/src/mock.rs
  frame/multisig/src/tests.rs
  frame/nft-fractionalization/src/lib.rs
  frame/nft-fractionalization/src/mock.rs
  frame/nfts/src/mock.rs
  frame/nicks/src/lib.rs
  frame/nis/src/lib.rs
  frame/nis/src/mock.rs
  frame/nomination-pools/benchmarking/src/mock.rs
  frame/nomination-pools/src/mock.rs
  frame/nomination-pools/test-staking/src/mock.rs
  frame/offences/benchmarking/src/mock.rs
  frame/preimage/src/mock.rs
  frame/proxy/src/tests.rs
  frame/recovery/src/mock.rs
  frame/referenda/src/mock.rs
  frame/root-offences/src/mock.rs
  frame/scored-pool/src/mock.rs
  frame/session/benchmarking/src/mock.rs
  frame/society/src/mock.rs
  frame/staking/src/mock.rs
  frame/state-trie-migration/src/lib.rs
  frame/statement/src/mock.rs
  frame/tips/src/tests.rs
  frame/transaction-payment/asset-tx-payment/src/mock.rs
  frame/transaction-payment/src/mock.rs
  frame/transaction-storage/src/mock.rs
  frame/treasury/src/tests.rs
  frame/uniques/src/mock.rs
  frame/utility/src/tests.rs
  frame/vesting/src/mock.rs
  frame/whitelist/src/mock.rs
  test-utils/runtime/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14212 Get rid of some pointless pin_project stuff
  Cargo.lock
  client/network/transactions/Cargo.toml
  client/network/transactions/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14189 Support for `cfg` attributes in host functions definitions
  primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  primitives/runtime-interface/src/lib.rs
  primitives/runtime-interface/tests/ui/no_feature_gated_method.rs
  primitives/runtime-interface/tests/ui/no_feature_gated_method.stderr
  primitives/runtime-interface/tests/ui/no_versioned_conditional_build.rs
  primitives/runtime-interface/tests/ui/no_versioned_conditional_build.stderr
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14217 sc-consensus-beefy: graceful support for pallet-beefy reset
  client/consensus/beefy/src/aux_schema.rs
  client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  client/consensus/beefy/src/error.rs
  client/consensus/beefy/src/lib.rs
  client/consensus/beefy/src/tests.rs
  client/consensus/beefy/src/worker.rs
  frame/beefy/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14216 Don't start evicting peers right after `SyncingEngine` is started
  client/network/sync/src/engine.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#14227 bump zombienet version
  .gitlab-ci.yml
Labels: A0-please_review, B0-silent, C1-low

#14107 frame: GenesisBuild::build allowed in no_std
  Cargo.lock
  frame/elections-phragmen/src/lib.rs
  frame/support/procedural/src/pallet/expand/genesis_build.rs
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/support/src/traits/hooks.rs
  frame/support/test/Cargo.toml
  frame/support/test/pallet/Cargo.toml
  frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr
  frame/support/test/tests/pallet_ui/pass/no_std_genesis_config.rs
  frame/system/src/lib.rs
  test-utils/runtime/src/substrate_test_pallet.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#12714 Add remove_proxies API for pallet-proxies #7557
  frame/proxy/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14210 Soft deprecate GenesisConfig
  bin/node-template/node/src/chain_spec.rs
  bin/node/cli/src/chain_spec.rs
  bin/node/testing/src/bench.rs
  bin/node/testing/src/genesis.rs
  bin/utils/chain-spec-builder/src/main.rs
  frame/alliance/src/mock.rs
  frame/benchmarking/src/tests.rs
  frame/benchmarking/src/tests_instance.rs
  frame/bounties/src/tests.rs
  frame/collective/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/examples/basic/src/tests.rs
  frame/examples/dev-mode/src/tests.rs
  frame/remark/src/mock.rs
  frame/support/procedural/src/construct_runtime/expand/config.rs
  frame/support/src/lib.rs
  frame/support/src/storage/generator/mod.rs
  frame/support/test/tests/instance.rs
  frame/support/test/tests/issue2219.rs
  frame/system/src/mock.rs
  frame/tips/src/tests.rs
  frame/transaction-storage/src/mock.rs
  frame/whitelist/src/mock.rs
  test-utils/runtime/src/genesismap.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14115 add new documentation guidelines
  docs/CODEOWNERS
  docs/CONTRIBUTING.adoc
  docs/DOCUMENTATION_GUIDELINES.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#14215 test-utils: Fix wait_for_blocks in presence of reorgs
  test-utils/client/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#14185 Improves documentation on `num_slashing_spans` when calling `withdraw_unbounded` in Staking.
  frame/staking/src/pallet/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#14244 RPC-Spec-V2: Rename `runtimeUpdates` flag to `withRuntime`
  client/rpc-spec-v2/src/chain_head/api.rs
  client/rpc-spec-v2/src/chain_head/chain_head.rs
  client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  client/rpc-spec-v2/src/chain_head/event.rs
  client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T2-API

#14228 wasm-builder: Enforce `runtime_version` wasm section
  Cargo.lock
  bin/node-template/node/Cargo.toml
  client/executor/runtime-test/build.rs
  primitives/runtime-interface/test-wasm-deprecated/build.rs
  primitives/runtime-interface/test-wasm/build.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/builder.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14239 [minor] Fix misleading comment in `Notifications`
  client/network/src/protocol/notifications/behaviour.rs
Labels: A0-please_review, A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14252 sp-api: Set correct where bound in the generated code
  Cargo.lock
  primitives/api/proc-macro/src/runtime_metadata.rs
  primitives/api/test/Cargo.toml
  primitives/api/test/tests/ui/positive_cases/custom_where_bound.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T0-node

#14208 sp-wasm-interface: remove useless wasmi impl
  Cargo.lock
  primitives/wasm-interface/Cargo.toml
  primitives/wasm-interface/src/lib.rs
  primitives/wasm-interface/src/wasmi_impl.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14242 [NFTs] Add minting price to the pre-signed mint object
  frame/nfts/src/benchmarking.rs
  frame/nfts/src/features/create_delete_item.rs
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14258 `Pay` trait gets `Error` item
  frame/salary/src/lib.rs
  frame/salary/src/tests.rs
  frame/support/src/traits/tokens/pay.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14256 primitives: added serde feature
  primitives/authority-discovery/Cargo.toml
  primitives/statement-store/Cargo.toml
Labels: B0-silent, C1-low, D3-trivial 🧸

#14259 FRAME: Pay trait benchmark helper should use asset kind
  frame/salary/src/benchmarking.rs
  frame/salary/src/tests.rs
  frame/support/src/traits/tokens/pay.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#14255 bounded-collections bump to 0.1.7
  Cargo.lock
  primitives/core/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#14257 [NFTs] Add mint price to the witness object on mint and confirm it
  frame/nfts/src/lib.rs
  frame/nfts/src/tests.rs
  frame/nfts/src/types.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#14101 Improve documentation for `fast-unstake` pallet
  Cargo.lock
  frame/fast-unstake/Cargo.toml
  frame/fast-unstake/src/lib.rs
  frame/fast-unstake/src/tests.rs
  frame/fast-unstake/src/types.rs
  frame/support/procedural/src/pallet/expand/call.rs
  frame/support/procedural/src/pallet/expand/config.rs
  frame/support/procedural/src/pallet/expand/doc_only.rs
  frame/support/procedural/src/pallet/expand/error.rs
  frame/support/procedural/src/pallet/expand/event.rs
  frame/support/procedural/src/pallet/expand/mod.rs
  frame/support/procedural/src/pallet/expand/pallet_struct.rs
  frame/support/procedural/src/pallet/expand/storage.rs
  frame/support/src/lib.rs
  frame/support/test/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#13454 Default Pallet Config Trait / derive_impl
  Cargo.lock
  Cargo.toml
  frame/examples/default-config/Cargo.toml
  frame/examples/default-config/README.md
  frame/examples/default-config/src/lib.rs
  frame/support/Cargo.toml
  frame/support/procedural/Cargo.toml
  frame/support/procedural/src/construct_runtime/mod.rs
  frame/support/procedural/src/derive_impl.rs
  frame/support/procedural/src/lib.rs
  frame/support/procedural/src/pallet/expand/config.rs
  frame/support/procedural/src/pallet/parse/config.rs
  frame/support/procedural/src/pallet/parse/helper.rs
  frame/support/procedural/src/pallet/parse/mod.rs
  frame/support/src/lib.rs
  frame/support/test/Cargo.toml
  frame/support/test/tests/derive_impl_ui.rs
  frame/support/test/tests/derive_impl_ui/attached_to_non_impl.rs
  frame/support/test/tests/derive_impl_ui/attached_to_non_impl.stderr
  frame/support/test/tests/derive_impl_ui/bad_default_impl_path.rs
  frame/support/test/tests/derive_impl_ui/bad_default_impl_path.stderr
  frame/support/test/tests/derive_impl_ui/bad_disambiguation_path.rs
  frame/support/test/tests/derive_impl_ui/bad_disambiguation_path.stderr
  frame/support/test/tests/derive_impl_ui/missing_disambiguation_path.rs
  frame/support/test/tests/derive_impl_ui/missing_disambiguation_path.stderr
  frame/support/test/tests/derive_impl_ui/pass/basic_overriding.rs
  frame/support/test/tests/derive_impl_ui/pass/macro_magic_working.rs
  frame/support/test/tests/pallet_ui/no_default_but_missing_with_default.rs
  frame/support/test/tests/pallet_ui/no_default_but_missing_with_default.stderr
  frame/support/test/tests/pallet_ui/trait_invalid_item.stderr
  frame/support/test/tests/pallet_ui/trait_item_duplicate_constant_attr.rs
  frame/support/test/tests/pallet_ui/trait_item_duplicate_constant_attr.stderr
  frame/support/test/tests/pallet_ui/trait_item_duplicate_no_default.rs
  frame/support/test/tests/pallet_ui/trait_item_duplicate_no_default.stderr
  frame/system/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, B1-note_worthy, T1-runtime

#14230 Make offchain tx pool creation reusable
  Cargo.lock
  client/api/src/execution_extensions.rs
  client/offchain/src/lib.rs
  client/transaction-pool/api/Cargo.toml
  client/transaction-pool/api/src/lib.rs
  client/transaction-pool/src/lib.rs
Labels: A0-please_review, C1-low, B1-note_worthy, T0-node

#14266 Remove `enum-as-inner` pin
  Cargo.lock
  bin/node-template/node/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#14045 contracts: Multi block migrations
  frame/contracts/primitives/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/migration.rs
  frame/contracts/src/migration/v10.rs
  frame/contracts/src/migration/v11.rs
  frame/contracts/src/migration/v9.rs
  frame/contracts/src/tests.rs
  frame/contracts/src/weights.rs
  frame/support/src/traits/metadata.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, B1-note_worthy, T1-runtime

#14238 Expose `build_system_rpc_future` and `TransactionPoolAdapator` in sc-service
  client/service/src/builder.rs
  client/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸
